### ISSUE TITLE
release: v0.16.0-rc2 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10016]
No PRs in [`v0.16.0-rc2`](https://github.com/MaterializeInc/materialize/tree/v0.16.0-rc2) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`d887a8253` Revert #9909 and #9982 (#10001)](https://github.com/MaterializeInc/materialize/commit/d887a8253d326a2867b2c1d05667e1245687b54f) (@ruchirK)
* [x] [`25254c2ff` Keep types consistent when replacing an IF expression. (#10007)](https://github.com/MaterializeInc/materialize/commit/25254c2ff4f50e6a4ffa8b375437d65a1cbbcdd5) (@ruchirK)
* [x] [`1e533e7a3` release: v0.16.0-rc2](https://github.com/MaterializeInc/materialize/commit/1e533e7a3dbe8dc5787c859f0e37486fc102663d) (@ruchirK)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`d887a8253` Revert #9909 and #9982 (#10001)](https://github.com/MaterializeInc/materialize/commit/d887a8253d326a2867b2c1d05667e1245687b54f) (@ruchirK)
* [ ] [`25254c2ff` Keep types consistent when replacing an IF expression. (#10007)](https://github.com/MaterializeInc/materialize/commit/25254c2ff4f50e6a4ffa8b375437d65a1cbbcdd5) (@ruchirK)
* [ ] [`1e533e7a3` release: v0.16.0-rc2](https://github.com/MaterializeInc/materialize/commit/1e533e7a3dbe8dc5787c859f0e37486fc102663d) (@ruchirK)

**Comment by ruchirK** [comment]
these were all reviewed separately and are being cherry picked onto a new tag

**Comment by benesch** [comment]
LGTM
