### ISSUE TITLE
release: v0.17.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10100]
The following PRs in [`v0.17.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.17.0-rc1) require review:
* [x] [#9989 sql: iterate on flaky test_tail_table_rw_timestamps](https://github.com/MaterializeInc/materialize/pull/9989) (@sploiselle)
* [x] [#10001 Revert #9909 and #9982](https://github.com/MaterializeInc/materialize/pull/10001) (@cjubb39)
* [x] [#10012 feature-benchmark: Add scenario for ORDER BY within dataflows](https://github.com/MaterializeInc/materialize/pull/10012) (@philip-stoev)
* [x] [#10020 convert kafka-ssl to a python mzworkflow](https://github.com/MaterializeInc/materialize/pull/10020) (@guswynn)
* [x] [#10023 Fix merge skew](https://github.com/MaterializeInc/materialize/pull/10023) (@umanwizard)
* [x] [#10034 www: deploy to S3 too](https://github.com/MaterializeInc/materialize/pull/10034) (@benesch)
* [x] [#10037 www: remove Netlify configuration](https://github.com/MaterializeInc/materialize/pull/10037) (@benesch)
* [x] [#10038 doc/user: add missing `bool` type link](https://github.com/MaterializeInc/materialize/pull/10038) (@benesch)
* [x] [#10040 ci/deploy: copy contents of website directory, not directory itself](https://github.com/MaterializeInc/materialize/pull/10040) (@benesch)
* [x] [#10045 test,persistence: re-enable kafka-sources/failpoint-after.td](https://github.com/MaterializeInc/materialize/pull/10045) (@philip-stoev)
* [x] [#10052 rust-dec: bump version to 0.4.6 + refactor as necessary](https://github.com/MaterializeInc/materialize/pull/10052) (@sploiselle)
* [x] [#10070 test,persistence: Run the persistence scenarios with and without comp…](https://github.com/MaterializeInc/materialize/pull/10070) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`c772c7fdc` release: v0.17.0-rc1](https://github.com/MaterializeInc/materialize/commit/c772c7fdc7b706e34c0518f275ded4d33d727bf9) (@quodlibetor)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#9923 persist: pass around Metrics wrapped in an Arc](https://github.com/MaterializeInc/materialize/pull/9923) (@danhhz)
* [ ] [#9979 feature-benchmark: Add to Nightly build](https://github.com/MaterializeInc/materialize/pull/9979) (@philip-stoev)
* [ ] [#9986 Prepare 0.16.1 dev](https://github.com/MaterializeInc/materialize/pull/9986) (@ruchirK)
* [ ] [#9983 avro: initialize buffer to avoid potential UB](https://github.com/MaterializeInc/materialize/pull/9983) (@petrosagg)
* [ ] [#9987 issue_templates: fix release issue template to point to correct relea…](https://github.com/MaterializeInc/materialize/pull/9987) (@ruchirK)
* [ ] [#9989 sql: iterate on flaky test_tail_table_rw_timestamps](https://github.com/MaterializeInc/materialize/pull/9989) (@sploiselle)
* [ ] [#9994 mzcloud-cli catalog restore mode](https://github.com/MaterializeInc/materialize/pull/9994) (@alex-hunt-materialize)
* [ ] [#9941 sql: support jsonb subscripting](https://github.com/MaterializeInc/materialize/pull/9941) (@benesch)
* [ ] [#9977 build(deps-dev): bump types-pymysql from 1.0.10 to 1.0.11 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/9977) (@dependabot[bot])
* [ ] [#9996 build(deps): bump clap from 3.0.0 to 3.0.6](https://github.com/MaterializeInc/materialize/pull/9996) (@dependabot[bot])
* [ ] [#9659 persist,dataflow: verify expected as_of when replaying streams](https://github.com/MaterializeInc/materialize/pull/9659) (@aljoscha)
* [ ] [#9656 persist: take persistence since into account when calculating source since](https://github.com/MaterializeInc/materialize/pull/9656) (@aljoscha)
* [ ] [#9998 sqllogictest: Allow --rewrite-results to process hash results](https://github.com/MaterializeInc/materialize/pull/9998) (@philip-stoev)
* [ ] [#9747 test: SLT test with queries were all parts of the query are essential](https://github.com/MaterializeInc/materialize/pull/9747) (@philip-stoev)
* [ ] [#10001 Revert #9909 and #9982](https://github.com/MaterializeInc/materialize/pull/10001) (@cjubb39)
* [ ] [#10002 pg-cdc: Fix default argument and usage](https://github.com/MaterializeInc/materialize/pull/10002) (@quodlibetor)
* [ ] [#10003 sql: link now() error to docs explainer](https://github.com/MaterializeInc/materialize/pull/10003) (@mjibson)
* [ ] [#10004 doc: describe and link to TAIL transaction limits](https://github.com/MaterializeInc/materialize/pull/10004) (@mjibson)
* [ ] [#9887  dataflow,sources: only restore timestamp bindings on workers that need them](https://github.com/MaterializeInc/materialize/pull/9887) (@aljoscha)
* [ ] [#9701 persist: use parquet as the permanent format for data blobs](https://github.com/MaterializeInc/materialize/pull/9701) (@danhhz)
* [ ] [#10007 Expr: fix crash when case has error condition](https://github.com/MaterializeInc/materialize/pull/10007) (@wangandi)
* [ ] [#9897 dataflow: add a permanent storage format for {Source,Assigned}Timestamp](https://github.com/MaterializeInc/materialize/pull/9897) (@danhhz)
* [ ] [#10009 aws-util: resolve TODO about obviated Arc](https://github.com/MaterializeInc/materialize/pull/10009) (@benesch)
* [ ] [#10011 sql-parser: correct roundtripping of aliased ROWS FROM clauses](https://github.com/MaterializeInc/materialize/pull/10011) (@benesch)
* [ ] [#10012 feature-benchmark: Add scenario for ORDER BY within dataflows](https://github.com/MaterializeInc/materialize/pull/10012) (@philip-stoev)
* [ ] [#9621 docs: Change "Observing local Materialize" to use tabs](https://github.com/MaterializeInc/materialize/pull/9621) (@quodlibetor)
* [ ] [#10015 deny: describe RUSTSEC-2021-0122 mitigation](https://github.com/MaterializeInc/materialize/pull/10015) (@danhhz)
* [ ] [#10014 www: fix bug reporting link](https://github.com/MaterializeInc/materialize/pull/10014) (@petrosagg)
* [ ] [#10020 convert kafka-ssl to a python mzworkflow](https://github.com/MaterializeInc/materialize/pull/10020) (@guswynn)
* [ ] [#9990 log::macros! -> tracing::macros!](https://github.com/MaterializeInc/materialize/pull/9990) (@guswynn)
* [ ] [#10021 Make a last-ditch effort to plan the arrangements necessary for a delta join during LIR planning](https://github.com/MaterializeInc/materialize/pull/10021) (@umanwizard)
* [ ] [#10023 Fix merge skew](https://github.com/MaterializeInc/materialize/pull/10023) (@umanwizard)
* [ ] [#9938 persist: relax allow_compaction() requirements](https://github.com/MaterializeInc/materialize/pull/9938) (@aljoscha)
* [ ] [#9933 pg-cdc: check that the publication exists](https://github.com/MaterializeInc/materialize/pull/9933) (@petrosagg)
* [ ] [#9881 release checklist: convenience command and small fix](https://github.com/MaterializeInc/materialize/pull/9881) (@petrosagg)
* [ ] [#10030 Introduce modules into `dataflow-types`](https://github.com/MaterializeInc/materialize/pull/10030) (@frankmcsherry)
* [ ] [#10029  persist: add allow_compaction() operator](https://github.com/MaterializeInc/materialize/pull/10029) (@aljoscha)
* [ ] [#10033 persist: split persist::indexed::runtime into persist::{client,runtime}](https://github.com/MaterializeInc/materialize/pull/10033) (@danhhz)
* [ ] [#10032 minimize frontier updates returned](https://github.com/MaterializeInc/materialize/pull/10032) (@frankmcsherry)
* [ ] [#9993 doc/user: Polish release notes for v0.16.0](https://github.com/MaterializeInc/materialize/pull/9993) (@morsapaes)
* [ ] [#9997 sql: prefer CCSR SSL options](https://github.com/MaterializeInc/materialize/pull/9997) (@aakside)
* [ ] [#10035 Update released versions to include v0.16.0](https://github.com/MaterializeInc/materialize/pull/10035) (@ruchirK)
* [ ] [#10034 www: deploy to S3 too](https://github.com/MaterializeInc/materialize/pull/10034) (@benesch)
* [ ] [#10037 www: remove Netlify configuration](https://github.com/MaterializeInc/materialize/pull/10037) (@benesch)
* [ ] [#10038 doc/user: add missing `bool` type link](https://github.com/MaterializeInc/materialize/pull/10038) (@benesch)
* [ ] [#10040 ci/deploy: copy contents of website directory, not directory itself](https://github.com/MaterializeInc/materialize/pull/10040) (@benesch)
* [ ] [#10043 issue_templates: two small edits to the release template](https://github.com/MaterializeInc/materialize/pull/10043) (@ruchirK)
* [ ] [#7356 persist: update README with latest thinking](https://github.com/MaterializeInc/materialize/pull/7356) (@danhhz)
* [ ] [#10039 add bin/scratch push](https://github.com/MaterializeInc/materialize/pull/10039) (@guswynn)
* [ ] [#10026 [kafka sink] Remove blocking tx calls from dataflow thread](https://github.com/MaterializeInc/materialize/pull/10026) (@cjubb39)
* [ ] [#10045 test,persistence: re-enable kafka-sources/failpoint-after.td](https://github.com/MaterializeInc/materialize/pull/10045) (@philip-stoev)
* [ ] [#10046 Add test to ensure create-certs.sh doesnt regress in kafka-ssl/multi.td](https://github.com/MaterializeInc/materialize/pull/10046) (@guswynn)
* [ ] [#10049 filter MetricsRecorderLayer with the same filter as the fmt layer](https://github.com/MaterializeInc/materialize/pull/10049) (@guswynn)
* [ ] [#9406 repr: introduce a protobuf-backed permanent storage format for Row](https://github.com/MaterializeInc/materialize/pull/9406) (@danhhz)
* [ ] [#10052 rust-dec: bump version to 0.4.6 + refactor as necessary](https://github.com/MaterializeInc/materialize/pull/10052) (@sploiselle)
* [ ] [#10053 repr: upgrade to proposed dec v0.4.7](https://github.com/MaterializeInc/materialize/pull/10053) (@benesch)
* [ ] [#10070 test,persistence: Run the persistence scenarios with and without comp…](https://github.com/MaterializeInc/materialize/pull/10070) (@philip-stoev)
* [ ] [`c772c7fdc` release: v0.17.0-rc1](https://github.com/MaterializeInc/materialize/commit/c772c7fdc7b706e34c0518f275ded4d33d727bf9) (@quodlibetor)
