### ISSUE TITLE
release: v0.18.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10208]
The following PRs in [`v0.18.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.18.0-rc1) require review:
* [x] [#10088 feature-benchmark: Add senario for exactly-once sinks](https://github.com/MaterializeInc/materialize/pull/10088) (@philip-stoev)
* [x] [#10116 deps: upgrade to latest autotools-rs](https://github.com/MaterializeInc/materialize/pull/10116) (@benesch)
* [x] [#10140 test,persist: disable kafka-sources/failpoint-after.td until #9687 is fixed](https://github.com/MaterializeInc/materialize/pull/10140) (@danhhz)
* [x] [#10149 Update released versions to include v0.17.0](https://github.com/MaterializeInc/materialize/pull/10149) (@quodlibetor)
* [x] [#10157 feature-benchmark: Sleep 10ms when retrying a query](https://github.com/MaterializeInc/materialize/pull/10157) (@philip-stoev)
* [x] [#10131 misc: various little fixes](https://github.com/MaterializeInc/materialize/pull/10131) (@benesch)
* [x] [#10196 Python dependency bump 2022-01-23](https://github.com/MaterializeInc/materialize/pull/10196) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`4f4dd5cab` release: v0.18.0-rc1](https://github.com/MaterializeInc/materialize/commit/4f4dd5cab2b1b82877d18eb60a4d75f1816e6086) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#10056 build(deps): bump os_info from 3.0.9 to 3.1.0](https://github.com/MaterializeInc/materialize/pull/10056) (@dependabot[bot])
* [ ] [#10057 build(deps): bump aws-sdk-sqs from 0.4.0 to 0.4.1](https://github.com/MaterializeInc/materialize/pull/10057) (@dependabot[bot])
* [ ] [#10059 build(deps): bump smallvec from 1.7.0 to 1.8.0](https://github.com/MaterializeInc/materialize/pull/10059) (@dependabot[bot])
* [ ] [#10061 build(deps): bump postgres from `4320cb7` to `5ae9ff0`](https://github.com/MaterializeInc/materialize/pull/10061) (@dependabot[bot])
* [ ] [#10064 build(deps): bump tracing-subscriber from 0.3.5 to 0.3.6](https://github.com/MaterializeInc/materialize/pull/10064) (@dependabot[bot])
* [ ] [#10065 build(deps): bump aws-config from 0.4.0 to 0.4.1](https://github.com/MaterializeInc/materialize/pull/10065) (@dependabot[bot])
* [ ] [#10066 build(deps-dev): bump boto3 from 1.20.31 to 1.20.37 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10066) (@dependabot[bot])
* [ ] [#10069 build(deps-dev): bump numpy from 1.22.0 to 1.22.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10069) (@dependabot[bot])
* [ ] [#10074 build(deps): bump serde_json from 1.0.74 to 1.0.75](https://github.com/MaterializeInc/materialize/pull/10074) (@dependabot[bot])
* [ ] [#10067 build(deps-dev): bump boto3-stubs[ec2,kinesis,s3,sqs,ssm,sts] from 1.20.31 to 1.20.37 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10067) (@dependabot[bot])
* [ ] [#10087 build(deps): bump krb5-src from 0.3.1+1.19.2 to 0.3.2+1.19.2](https://github.com/MaterializeInc/materialize/pull/10087) (@dependabot[bot])
* [ ] [#10088 feature-benchmark: Add senario for exactly-once sinks](https://github.com/MaterializeInc/materialize/pull/10088) (@philip-stoev)
* [ ] [#9934 qgm: add validation support for QGM models](https://github.com/MaterializeInc/materialize/pull/9934) (@aalexandrov)
* [ ] [#9812 persist: mzworkflows based load test](https://github.com/MaterializeInc/materialize/pull/9812) (@ruchirK)
* [ ] [#10051 Add basic counters to Postgres source](https://github.com/MaterializeInc/materialize/pull/10051) (@nharring-adjacent)
* [ ] [#10090 sql: fix bugs in LIKE](https://github.com/MaterializeInc/materialize/pull/10090) (@benesch)
* [ ] [#10091 [sql] move get_partitions to kafka_util](https://github.com/MaterializeInc/materialize/pull/10091) (@cjubb39)
* [ ] [#10093 [testdrive] Allow for missing initial items in kafka-verify](https://github.com/MaterializeInc/materialize/pull/10093) (@cjubb39)
* [ ] [#10097 switch dev-box.json to larger machines](https://github.com/MaterializeInc/materialize/pull/10097) (@guswynn)
* [ ] [#10098 upgrade to rust 1.58](https://github.com/MaterializeInc/materialize/pull/10098) (@guswynn)
* [ ] [#10102 python: remove many `type: ignore` comments](https://github.com/MaterializeInc/materialize/pull/10102) (@benesch)
* [ ] [#10079 *: replace rust-protobuf with prost](https://github.com/MaterializeInc/materialize/pull/10079) (@benesch)
* [ ] [#10104 doc/user: polish and complete release notes/docs for v0.17.0](https://github.com/MaterializeInc/materialize/pull/10104) (@benesch)
* [ ] [#10058 build(deps): bump rdkafka from `a640a00` to `dac9d41`](https://github.com/MaterializeInc/materialize/pull/10058) (@dependabot[bot])
* [ ] [#10108 build(deps): bump predicates from 2.1.0 to 2.1.1](https://github.com/MaterializeInc/materialize/pull/10108) (@dependabot[bot])
* [ ] [#10085 build(deps): bump assert_cmd from 2.0.2 to 2.0.4](https://github.com/MaterializeInc/materialize/pull/10085) (@dependabot[bot])
* [ ] [#10112 build(deps): bump sysinfo from 0.22.5 to 0.23.0](https://github.com/MaterializeInc/materialize/pull/10112) (@dependabot[bot])
* [ ] [#10110 build(deps): bump reqwest from 0.11.8 to 0.11.9](https://github.com/MaterializeInc/materialize/pull/10110) (@dependabot[bot])
* [ ] [#10111 build(deps): bump clap from 3.0.6 to 3.0.10](https://github.com/MaterializeInc/materialize/pull/10111) (@dependabot[bot])
* [ ] [#10116 deps: upgrade to latest autotools-rs](https://github.com/MaterializeInc/materialize/pull/10116) (@benesch)
* [ ] [#10117 .github: add qa template](https://github.com/MaterializeInc/materialize/pull/10117) (@uce)
* [ ] [#9578 lowertest: Recursively add to ReflectedTypeInfo](https://github.com/MaterializeInc/materialize/pull/9578) (@wangandi)
* [ ] [#10092 sql+coord: add return types for builtin functions](https://github.com/MaterializeInc/materialize/pull/10092) (@sploiselle)
* [ ] [#10124 scratch: add 'sftp' command that connects via msftp](https://github.com/MaterializeInc/materialize/pull/10124) (@aljoscha)
* [ ] [#10127 dataflow: extract rendering local source into its own function](https://github.com/MaterializeInc/materialize/pull/10127) (@ruchirK)
* [ ] [#10118 interchange,testdrive: use prost-reflect instead of rust-protobuf](https://github.com/MaterializeInc/materialize/pull/10118) (@benesch)
* [ ] [#10133 misc/scratch: add new alias for a big dev box](https://github.com/MaterializeInc/materialize/pull/10133) (@ruchirK)
* [ ] [#10135 scratch: add persist-benchmarking shortcut for create](https://github.com/MaterializeInc/materialize/pull/10135) (@danhhz)
* [ ] [#10115 testdrive: merge workflows into one ergonomic pile](https://github.com/MaterializeInc/materialize/pull/10115) (@benesch)
* [ ] [#10101 [testdrive] Fix search-greedy option](https://github.com/MaterializeInc/materialize/pull/10101) (@cjubb39)
* [ ] [#10140 test,persist: disable kafka-sources/failpoint-after.td until #9687 is fixed](https://github.com/MaterializeInc/materialize/pull/10140) (@danhhz)
* [ ] [#10137 testdrive: invoke real protoc in protobuf-compile action](https://github.com/MaterializeInc/materialize/pull/10137) (@benesch)
* [ ] [#10143 core,test: Allow stack traces on SIGSEGV/SIGBUS to be disabled](https://github.com/MaterializeInc/materialize/pull/10143) (@philip-stoev)
* [ ] [#10125 s3: Improve error messages and handling](https://github.com/MaterializeInc/materialize/pull/10125) (@quodlibetor)
* [ ] [#10095 sql: Handle SHOW TIME ZONE as an alias for SHOW TIMEZONE #9908](https://github.com/MaterializeInc/materialize/pull/10095) (@pH14)
* [ ] [#9576 Reject multiple materializations of sources that cannot handle them](https://github.com/MaterializeInc/materialize/pull/9576) (@quodlibetor)
* [ ] [#10122 Reworking `import_source`](https://github.com/MaterializeInc/materialize/pull/10122) (@frankmcsherry)
* [ ] [#9665 add support for tokio-console behind a hidden flag and feature](https://github.com/MaterializeInc/materialize/pull/9665) (@guswynn)
* [ ] [#10149 Update released versions to include v0.17.0](https://github.com/MaterializeInc/materialize/pull/10149) (@quodlibetor)
* [ ] [#10157 feature-benchmark: Sleep 10ms when retrying a query](https://github.com/MaterializeInc/materialize/pull/10157) (@philip-stoev)
* [ ] [#10142 Switch from rust-protobuf to protobuf-native for proto compilation](https://github.com/MaterializeInc/materialize/pull/10142) (@benesch)
* [ ] [#10158 doc/user: add comma and remove braces](https://github.com/MaterializeInc/materialize/pull/10158) (@joacoc)
* [ ] [#10086 build(deps): bump rand_distr from 0.4.2 to 0.4.3](https://github.com/MaterializeInc/materialize/pull/10086) (@dependabot[bot])
* [ ] [#10160 deps: upgrade to aws-sdk v0.5.0](https://github.com/MaterializeInc/materialize/pull/10160) (@benesch)
* [ ] [#10161 http-proxy: make hyper connector constructor infallible](https://github.com/MaterializeInc/materialize/pull/10161) (@benesch)
* [ ] [#10162 testdrive: fix redpanda nightlies](https://github.com/MaterializeInc/materialize/pull/10162) (@benesch)
* [ ] [#10136 Add optional Avro namespace to CREATE SINK #8352](https://github.com/MaterializeInc/materialize/pull/10136) (@pH14)
* [ ] [#10153 persist: ensure there is a tokio runtime available in BlobCache](https://github.com/MaterializeInc/materialize/pull/10153) (@danhhz)
* [ ] [#10164 Cargo.lock: bump prost to pick up the latest changes in our fork](https://github.com/MaterializeInc/materialize/pull/10164) (@danhhz)
* [ ] [#10044 [kafka sink] Rewrite sink to take advantage of async_op](https://github.com/MaterializeInc/materialize/pull/10044) (@cjubb39)
* [ ] [#10134 Support regexes in testdrive](https://github.com/MaterializeInc/materialize/pull/10134) (@quodlibetor)
* [ ] [#10168 sql: fix some more edge cases in column name inference](https://github.com/MaterializeInc/materialize/pull/10168) (@benesch)
* [ ] [#10169 Fix timestamp logic around metadata availability](https://github.com/MaterializeInc/materialize/pull/10169) (@antifuchs)
* [ ] [#10151 Platform commands](https://github.com/MaterializeInc/materialize/pull/10151) (@frankmcsherry)
* [ ] [#10170 nix: move from play to misc](https://github.com/MaterializeInc/materialize/pull/10170) (@benesch)
* [ ] [#10096 persist: chunk up ColumnarRecords construction](https://github.com/MaterializeInc/materialize/pull/10096) (@danhhz)
* [ ] [#10175 mzcompose: re-fetch deps when `Composition.override` is called](https://github.com/MaterializeInc/materialize/pull/10175) (@benesch)
* [ ] [#10131 misc: various little fixes](https://github.com/MaterializeInc/materialize/pull/10131) (@benesch)
* [ ] [#10176 sql-parser: permit nested empty SELECTs](https://github.com/MaterializeInc/materialize/pull/10176) (@benesch)
* [ ] [#10174 Add note on recommended editors and IDEs to the developer guide](https://github.com/MaterializeInc/materialize/pull/10174) (@umanwizard)
* [ ] [#10181 build(deps): bump syn from 1.0.85 to 1.0.86](https://github.com/MaterializeInc/materialize/pull/10181) (@dependabot[bot])
* [ ] [#10182 build(deps): bump console-subscriber from 0.1.0 to 0.1.1](https://github.com/MaterializeInc/materialize/pull/10182) (@dependabot[bot])
* [ ] [#10183 build(deps): bump libc from 0.2.112 to 0.2.113](https://github.com/MaterializeInc/materialize/pull/10183) (@dependabot[bot])
* [ ] [#10184 build(deps): bump crc32fast from 1.3.0 to 1.3.1](https://github.com/MaterializeInc/materialize/pull/10184) (@dependabot[bot])
* [ ] [#10186 build(deps): bump serde from 1.0.133 to 1.0.135](https://github.com/MaterializeInc/materialize/pull/10186) (@dependabot[bot])
* [ ] [#10194 build(deps): bump serde_json from 1.0.75 to 1.0.78](https://github.com/MaterializeInc/materialize/pull/10194) (@dependabot[bot])
* [ ] [#10196 Python dependency bump 2022-01-23](https://github.com/MaterializeInc/materialize/pull/10196) (@benesch)
* [ ] [#10177 testdrive: switch to anyhow](https://github.com/MaterializeInc/materialize/pull/10177) (@benesch)
* [ ] [#10199 test/proxy: support redpanda](https://github.com/MaterializeInc/materialize/pull/10199) (@benesch)
* [ ] [#10072 feature-benchmark: Large-scale persistence recovery benchmark](https://github.com/MaterializeInc/materialize/pull/10072) (@philip-stoev)
* [ ] [#10073  dataflow,persistence: enable persistence for ENVELOPE NONE ](https://github.com/MaterializeInc/materialize/pull/10073) (@aljoscha)
* [ ] [#10179 Use the default toolchain.](https://github.com/MaterializeInc/materialize/pull/10179) (@umanwizard)
* [ ] [#10198 build(deps): bump rdkafka from `dac9d41` to `4da6a61`](https://github.com/MaterializeInc/materialize/pull/10198) (@dependabot[bot])
* [ ] [`4f4dd5cab` release: v0.18.0-rc1](https://github.com/MaterializeInc/materialize/commit/4f4dd5cab2b1b82877d18eb60a4d75f1816e6086) (@umanwizard)
