### ISSUE TITLE
Tracking issue: Add outer-to-inner join conversion in QGM

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#10232]
## Summary

To keep things more focused than #8073, we introduce this tracking issue that contains a minimal set of changes needed in order to have an MVP for QGM that is able to transform outer to inner joins in the presence of null-rejecting predicates.

## Goals

* Transform outer to inner joins in the presence of null-rejecting predicates.

## Non-Goals

* Anything else QGM related, except technical debt issues that can be as part of the delivery of this feature without incurring substantial slowdown.

## Roadmap

- [ ] Address feedback & merge QGM rewrite engine
  - Estimate: 1 day
  - Dependencies: {}
- [ ] Tighten up mutable reference leakage
  - Estimate: 1 day timeboxed
  - Dependencies: {}
- [ ] Refactor visibility & module structure
  - Estimate: 1 day
  - Dependencies: {A, B}
- [ ] Derived attributes: framework
  - Estimate: 2 days
  - Dependencies: {C}
- [ ] Derived attributes: _non null requirements_ and _rejected nulls_
  - Estimate: 1 day
  - Dependencies: {D}
- [ ] Implement outer to inner join conversion rule
  - Estimate: 1 day
  - Dependencies: {A, E}
- [ ] Type inference
  - Estimate: 1 day
  - Dependencies: {E}

**Comment by wangandi** [comment]
This issue should allow #6987 to be resolved.

**Comment by aalexandrov** [comment]
> This issue should allow #6987 to be resolved.

This will not resolve the issue, but it lays out the groundwork to do so as a follow-up. We will need to:

- Introduce an attribute that computes unique keys in a bottom-up manner.
- Introduce a rule that simplifies `A ⟕ B` to `A` if the predicate support on `B` is a superset of some unique key.
