### ISSUE TITLE
release: v0.19.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10367]
The following PRs in [`v0.19.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.19.0-rc1) require review:
* [x] [#10200 mzcompose: rename `env` -> `env_extra` in Composition.run](https://github.com/MaterializeInc/materialize/pull/10200) (@benesch)
* [x] [#10231 ci: remove outdated reference to nightly.stamp](https://github.com/MaterializeInc/materialize/pull/10231) (@benesch)
* [x] [#10250 feature-benchmark: Address merge skew](https://github.com/MaterializeInc/materialize/pull/10250) (@philip-stoev)
* [x] [#10270 feature-benchmark: Allow scenarios to be run at multiple scales](https://github.com/MaterializeInc/materialize/pull/10270) (@philip-stoev)
* [x] [#10273 Add platform overview document](https://github.com/MaterializeInc/materialize/pull/10273) (@frankmcsherry)
* [x] [#10262 Continue 0.18.1 dev](https://github.com/MaterializeInc/materialize/pull/10262) (@umanwizard)
* [x] [#10287 deps: bump to protobuf-src v1.0.5+3.19.3](https://github.com/MaterializeInc/materialize/pull/10287) (@benesch)
* [x] [#10307 doc/platform: describe candidate SQL catalog mapping](https://github.com/MaterializeInc/materialize/pull/10307) (@benesch)
* [x] [#10308 doc/platform: create a proper README](https://github.com/MaterializeInc/materialize/pull/10308) (@benesch)
* [x] [#10309 ci/test: correct input globs for test/debezium-avro](https://github.com/MaterializeInc/materialize/pull/10309) (@benesch)
* [x] [#10296 mzcompose: Raise an error if the same service is specified twice](https://github.com/MaterializeInc/materialize/pull/10296) (@quodlibetor)
* [x] [#10311 mzcompose: the chbench load-test workflow needs to run default now](https://github.com/MaterializeInc/materialize/pull/10311) (@benesch)
* [x] [#10341 Dependabot amalgamation](https://github.com/MaterializeInc/materialize/pull/10341) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`6ef7eb456` release: v0.19.0-rc1](https://github.com/MaterializeInc/materialize/commit/6ef7eb456471e8b3286ad72870bcc1a0010e4b45) (@petrosagg)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#10200 mzcompose: rename `env` -> `env_extra` in Composition.run](https://github.com/MaterializeInc/materialize/pull/10200) (@benesch)
* [ ] [#10171 testdrive: Allow passing in variables at the command line](https://github.com/MaterializeInc/materialize/pull/10171) (@quodlibetor)
* [ ] [#10203 Fix security advisory https://buildkite.com/materialize/security/builds/595](https://github.com/MaterializeInc/materialize/pull/10203) (@umanwizard)
* [ ] [#10206 build(deps): bump clap from 3.0.10 to 3.0.11](https://github.com/MaterializeInc/materialize/pull/10206) (@dependabot[bot])
* [ ] [#10204 test: hook s3 storage up in the kafka-ingest-open-loop benchmark](https://github.com/MaterializeInc/materialize/pull/10204) (@danhhz)
* [ ] [#9574 persist: split out a read-only runtime](https://github.com/MaterializeInc/materialize/pull/9574) (@danhhz)
* [ ] [#10201 Docs compaction withclause](https://github.com/MaterializeInc/materialize/pull/10201) (@joacoc)
* [ ] [#10210 Fix some C++ build issues ](https://github.com/MaterializeInc/materialize/pull/10210) (@benesch)
* [ ] [#10211 aws-util: depend on openssl-sys with the "vendored" feature](https://github.com/MaterializeInc/materialize/pull/10211) (@danhhz)
* [ ] [#9988 sql: support non-nested arbitrary table functions](https://github.com/MaterializeInc/materialize/pull/9988) (@mjibson)
* [ ] [#10212 build(deps): bump clap from 3.0.11 to 3.0.12](https://github.com/MaterializeInc/materialize/pull/10212) (@dependabot[bot])
* [ ] [#10209 Prepare next phase of development: v0.18.1-dev](https://github.com/MaterializeInc/materialize/pull/10209) (@umanwizard)
* [ ] [#10221 mzcompose: use new --var feature instead of env vars](https://github.com/MaterializeInc/materialize/pull/10221) (@benesch)
* [ ] [#10215 qgm: Tighten up mutable reference leakage](https://github.com/MaterializeInc/materialize/pull/10215) (@aalexandrov)
* [ ] [#10202 sql: remove expression deduplication in GROUP BY planning #8302 ](https://github.com/MaterializeInc/materialize/pull/10202) (@pH14)
* [ ] [#10227 test: fix test for cdcv2](https://github.com/MaterializeInc/materialize/pull/10227) (@ruchirK)
* [ ] [#9612 sql: support experimental hopping, timestamp binning table-value function](https://github.com/MaterializeInc/materialize/pull/9612) (@sploiselle)
* [ ] [#10154 doc/user: Improve documentation of EOS](https://github.com/MaterializeInc/materialize/pull/10154) (@morsapaes)
* [ ] [#10229 [testdrive] improve required match specifier error](https://github.com/MaterializeInc/materialize/pull/10229) (@guswynn)
* [ ] [#10231 ci: remove outdated reference to nightly.stamp](https://github.com/MaterializeInc/materialize/pull/10231) (@benesch)
* [ ] [#10220 doc/user: polish release notes and docs for v0.18.0](https://github.com/MaterializeInc/materialize/pull/10220) (@benesch)
* [ ] [#10129 refuse unused WITH options in CONFLUENT SCHEMA REGISTRY](https://github.com/MaterializeInc/materialize/pull/10129) (@guswynn)
* [ ] [#9380 persist: convert trace batches to use ColumnarRecords](https://github.com/MaterializeInc/materialize/pull/9380) (@ruchirK)
* [ ] [#10242 persist: remove <K, V> bounds from MultiWriteHandle](https://github.com/MaterializeInc/materialize/pull/10242) (@danhhz)
* [ ] [#10109 QGM: Basic rewrite engine.](https://github.com/MaterializeInc/materialize/pull/10109) (@wangandi)
* [ ] [#10246 clean up the tokio-console initialization code](https://github.com/MaterializeInc/materialize/pull/10246) (@guswynn)
* [ ] [#10222 feature-benchmark: Allow parameterized scenarios](https://github.com/MaterializeInc/materialize/pull/10222) (@philip-stoev)
* [ ] [#10250 feature-benchmark: Address merge skew](https://github.com/MaterializeInc/materialize/pull/10250) (@philip-stoev)
* [ ] [#10251 mzbuild: always perform docker pull on acquire()](https://github.com/MaterializeInc/materialize/pull/10251) (@philip-stoev)
* [ ] [#9937 Decouple debezium envelope processing from format decoding](https://github.com/MaterializeInc/materialize/pull/9937) (@petrosagg)
* [ ] [#10230 dataflow,coord: tweeze apart Response and AllowCompaction messages](https://github.com/MaterializeInc/materialize/pull/10230) (@aljoscha)
* [ ] [#10244 mzcompose: Use the "default" workflow by default in CI](https://github.com/MaterializeInc/materialize/pull/10244) (@quodlibetor)
* [ ] [#10248 Cleanup `create-certs.sh`](https://github.com/MaterializeInc/materialize/pull/10248) (@guswynn)
* [ ] [#10259 persist: lint for `Arc::clone(&foo)` vs `foo.clone()`](https://github.com/MaterializeInc/materialize/pull/10259) (@danhhz)
* [ ] [#10260 Turn on clippy::clone_on_ref_ptr repo-wide](https://github.com/MaterializeInc/materialize/pull/10260) (@guswynn)
* [ ] [#10166 add spawn/spawn_blocking apis to ore to optionally name tasks](https://github.com/MaterializeInc/materialize/pull/10166) (@guswynn)
* [ ] [#10264 persist: use a single main for all benches](https://github.com/MaterializeInc/materialize/pull/10264) (@danhhz)
* [ ] [#9806 Fold permutations into MFPs; determine which arrangement to use during planning rather than implicitly during rendering.](https://github.com/MaterializeInc/materialize/pull/9806) (@umanwizard)
* [ ] [#10243 [kafka sink] use flush instead of in_flight_count](https://github.com/MaterializeInc/materialize/pull/10243) (@cjubb39)
* [ ] [#10249 mzcompose: optionalize forwarding AWS environment variables](https://github.com/MaterializeInc/materialize/pull/10249) (@benesch)
* [ ] [#10253 testdrive: shard](https://github.com/MaterializeInc/materialize/pull/10253) (@benesch)
* [ ] [#10267 ci: prune unpushed images before acquisition](https://github.com/MaterializeInc/materialize/pull/10267) (@benesch)
* [ ] [#10268 coord: remove leftover println!](https://github.com/MaterializeInc/materialize/pull/10268) (@aljoscha)
* [ ] [#10270 feature-benchmark: Allow scenarios to be run at multiple scales](https://github.com/MaterializeInc/materialize/pull/10270) (@philip-stoev)
* [ ] [#9819 expr,sql: add array_cat function + operator](https://github.com/MaterializeInc/materialize/pull/9819) (@andrioni)
* [ ] [#10272 feature-benchmark: give time for Mz to settle in the KafkaRecovery sc…](https://github.com/MaterializeInc/materialize/pull/10272) (@philip-stoev)
* [ ] [#10252 qgm: introduce `Rule::Match` and `ApplyRule`](https://github.com/MaterializeInc/materialize/pull/10252) (@aalexandrov)
* [ ] [#10273 Add platform overview document](https://github.com/MaterializeInc/materialize/pull/10273) (@frankmcsherry)
* [ ] [#10277 mzbuild: perform inline graph traversal when acquiring deps](https://github.com/MaterializeInc/materialize/pull/10277) (@benesch)
* [ ] [#10278 docs on how to use `tokio-console`](https://github.com/MaterializeInc/materialize/pull/10278) (@guswynn)
* [ ] [#9602 persist: handle trace compaction outside of main Indexed loop.](https://github.com/MaterializeInc/materialize/pull/9602) (@ruchirK)
* [ ] [#10276 doc: add required reading](https://github.com/MaterializeInc/materialize/pull/10276) (@mjibson)
* [ ] [#10262 Continue 0.18.1 dev](https://github.com/MaterializeInc/materialize/pull/10262) (@umanwizard)
* [ ] [#10279 turn on clippy::disallowed_method](https://github.com/MaterializeInc/materialize/pull/10279) (@guswynn)
* [ ] [#10283 fix basic auth for ccsr](https://github.com/MaterializeInc/materialize/pull/10283) (@guswynn)
* [ ] [#10287 deps: bump to protobuf-src v1.0.5+3.19.3](https://github.com/MaterializeInc/materialize/pull/10287) (@benesch)
* [ ] [#10284 fix the ability to make a patch rc in mkrelease](https://github.com/MaterializeInc/materialize/pull/10284) (@umanwizard)
* [ ] [#10255 coord,persist: fetch latest persist frontiers when rendering source](https://github.com/MaterializeInc/materialize/pull/10255) (@aljoscha)
* [ ] [#10266 QGM: Refactor module structures and crate visibility](https://github.com/MaterializeInc/materialize/pull/10266) (@wangandi)
* [ ] [#10265 persist: add s3 variants of a couple key benchmarks](https://github.com/MaterializeInc/materialize/pull/10265) (@danhhz)
* [ ] [#10094 [kafka exactly once sink] Fence consistency topics before determining latest ts](https://github.com/MaterializeInc/materialize/pull/10094) (@cjubb39)
* [ ] [#10291 fix spawn_named merge_skew](https://github.com/MaterializeInc/materialize/pull/10291) (@guswynn)
* [ ] [#10292 Ensure CCSR's basic_auth code is exercised in test/kafka-ssl/](https://github.com/MaterializeInc/materialize/pull/10292) (@guswynn)
* [ ] [#10302 persist: add temporary workaround for persisted table compaction bug](https://github.com/MaterializeInc/materialize/pull/10302) (@danhhz)
* [ ] [#10293 [sql] add a migration to remove extraneous confluent_wire_format WITH parameter](https://github.com/MaterializeInc/materialize/pull/10293) (@guswynn)
* [ ] [#10307 doc/platform: describe candidate SQL catalog mapping](https://github.com/MaterializeInc/materialize/pull/10307) (@benesch)
* [ ] [#10308 doc/platform: create a proper README](https://github.com/MaterializeInc/materialize/pull/10308) (@benesch)
* [ ] [#10309 ci/test: correct input globs for test/debezium-avro](https://github.com/MaterializeInc/materialize/pull/10309) (@benesch)
* [ ] [#10296 mzcompose: Raise an error if the same service is specified twice](https://github.com/MaterializeInc/materialize/pull/10296) (@quodlibetor)
* [ ] [#10311 mzcompose: the chbench load-test workflow needs to run default now](https://github.com/MaterializeInc/materialize/pull/10311) (@benesch)
* [ ] [#10314 remove concept of original ID from sources](https://github.com/MaterializeInc/materialize/pull/10314) (@petrosagg)
* [ ] [#10316 doc/platform: split UX and architecture](https://github.com/MaterializeInc/materialize/pull/10316) (@benesch)
* [ ] [#10318 doc/platform: reorg](https://github.com/MaterializeInc/materialize/pull/10318) (@benesch)
* [ ] [#10320 remove transient id allocation from dataflow builder](https://github.com/MaterializeInc/materialize/pull/10320) (@frankmcsherry)
* [ ] [#10304 Introduce create and drop source commands](https://github.com/MaterializeInc/materialize/pull/10304) (@frankmcsherry)
* [ ] [#10323 build(deps): bump libc from 0.2.113 to 0.2.116](https://github.com/MaterializeInc/materialize/pull/10323) (@dependabot[bot])
* [ ] [#10324 build(deps): bump async-compression from 0.3.8 to 0.3.12](https://github.com/MaterializeInc/materialize/pull/10324) (@dependabot[bot])
* [ ] [#10325 build(deps): bump tokio from 1.15.0 to 1.16.1](https://github.com/MaterializeInc/materialize/pull/10325) (@dependabot[bot])
* [ ] [#10327 build(deps): bump backtrace from 0.3.63 to 0.3.64](https://github.com/MaterializeInc/materialize/pull/10327) (@dependabot[bot])
* [ ] [#10338 build(deps): bump rdkafka from `4da6a61` to `6b4c8ca`](https://github.com/MaterializeInc/materialize/pull/10338) (@dependabot[bot])
* [ ] [#10339 build(deps): bump clap from 3.0.12 to 3.0.13](https://github.com/MaterializeInc/materialize/pull/10339) (@dependabot[bot])
* [ ] [#10341 Dependabot amalgamation](https://github.com/MaterializeInc/materialize/pull/10341) (@benesch)
* [ ] [#10342 build(deps): bump serde from 1.0.135 to 1.0.136](https://github.com/MaterializeInc/materialize/pull/10342) (@dependabot[bot])
* [ ] [#10346 build(deps): bump tracing-subscriber from 0.3.6 to 0.3.7](https://github.com/MaterializeInc/materialize/pull/10346) (@dependabot[bot])
* [ ] [#10289 persist: make MultiWriteHandle construction infallible](https://github.com/MaterializeInc/materialize/pull/10289) (@aljoscha)
* [ ] [#10321 Have Catalog produce a canonical SourceDesc](https://github.com/MaterializeInc/materialize/pull/10321) (@frankmcsherry)
* [ ] [#10139 kafka-ingest: small ergonomic cleanups.](https://github.com/MaterializeInc/materialize/pull/10139) (@ruchirK)
* [ ] [#10240 match postgres interval handling with head/tail time units](https://github.com/MaterializeInc/materialize/pull/10240) (@pH14)
* [ ] [#10356 Revert "Fold permutations into MFPs; determine which arrangement to u…](https://github.com/MaterializeInc/materialize/pull/10356) (@umanwizard)
* [ ] [`6ef7eb456` release: v0.19.0-rc1](https://github.com/MaterializeInc/materialize/commit/6ef7eb456471e8b3286ad72870bcc1a0010e4b45) (@petrosagg)

**Comment by petrosagg** [comment]
all looks good
