### ISSUE TITLE
[Epic] Reconciliation of compute commands

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#10549]
### Goals

Compute controller restarts don’t require restart of dataflows.

Start a design/implementation for reconciliation of compute commands. We expect both the compute controller and compute instances to go down and up. When they do, they need to re-establish the correct set-up. The controller is probably the source of truth, and should tell instances what to do, but instances may already have resident dataflows (described by the commands they were issued) and want to "recover" to the correct state more efficiently than dropping all dataflows and restarting from the controller's instructions. The caveats that seemed hard here are
1. understanding where the source of truth is (we probably make the Controller issue commands only after they are durably in some WAL, so that each instance can safely e.g. allow compaction that it can't unallow).
2. mapping out version upgrades, and what happens if either instance is older / newer than the other. What needs to be required of the versions of commands (non-failing upgrade, and fallible downgrade?).
3. mapping out what sinks look like, as their "state" is not just a SQL statement but also the progress they have made (we do not want to have to recover them from the start, as we have likely compacted that data; map out what compaction hold we need to be able to recover sinks).

* This is useful not only for restarts but brief connection interruptions
* Doesn’t solve the problem of surviving network interruptions between Timely processes

### Acceptance Criteria

* Controller can restart independently of computed
* We're able to survive short network interruptions between coordinator and compute once the network stack can recover from it (not scoped for M2).

### Tasks

* [ ] Validate current implementation
* [ ] Identify missing pieces of current implementation (which is disabled by default)
* [ ] Teach adapter to re-init a few tables?
* [ ] Extend implementation + test
* [ ] Test: Sink a dataflow to kafka - kill controller - data keeps being sinked
* [ ] Enable by default: https://github.com/MaterializeInc/materialize/pull/13391
* [ ] https://github.com/MaterializeInc/materialize/issues/13603
### Testing

* Computeds stay up and running during environmentd restarts.
* Commands are reconciled and existing objects matched to the command stream.

### Related

* (soft) Restarts of adapter/storage (to enable by default) #12857

**Comment by benesch** [comment]
One thing that looks sketchy in the existing reconciliation logic: ISTM that `FrontierUppers` responses can flow to a new controller before that controller has declared interest in them via a `CreateDataflows` command. Seems possible that it sees frontiers for dataflows that it doesn't care about, and before those frontiers get corrected by the reconciliation logic to retract the initial `0` frontier.

**Comment by uce** [comment]
Marking this epic is done. Reconciliation for multi process clusters is being tracked in #14255.
