### ISSUE TITLE
release: v0.20.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10555]
The following PRs in [`v0.20.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.20.0-rc1) require review:
* [x] [#10374 ci/test: fix git diff invocation](https://github.com/MaterializeInc/materialize/pull/10374) (@benesch)
* [x] [#10389 xcompile: fix bootstrap on darwin](https://github.com/MaterializeInc/materialize/pull/10389) (@benesch)
* [x] [#9825 Add support for MySQL in testdrive and mzcompose](https://github.com/MaterializeInc/materialize/pull/9825) (@philip-stoev)
* [x] [#10400 redpanda,test: consolidate all kafka_time_offset tests in one file.](https://github.com/MaterializeInc/materialize/pull/10400) (@philip-stoev)
* [x] [#10407 persistence,test: Add start_offset and kafka_time_offset to tests](https://github.com/MaterializeInc/materialize/pull/10407) (@philip-stoev)
* [x] [#10411 Update released versions to include v0.19.0](https://github.com/MaterializeInc/materialize/pull/10411) (@petrosagg)
* [x] [#10413 [kafka EOS] disable flaky timestamp compaction verification](https://github.com/MaterializeInc/materialize/pull/10413) (@cjubb39)
* [x] [#10417 [kafka exactly once sink] Reenable timestamp compaction verification](https://github.com/MaterializeInc/materialize/pull/10417) (@cjubb39)
* [x] [#10479 testdrive: small cleanups to skip-if](https://github.com/MaterializeInc/materialize/pull/10479) (@benesch)
* [x] [#10489 test/persistence: temporarily disable flaky test](https://github.com/MaterializeInc/materialize/pull/10489) (@benesch)
* [x] [#10497 limits test: Cap SelectExpression to 500 items](https://github.com/MaterializeInc/materialize/pull/10497) (@philip-stoev)
* [x] [#10525 test: Add explicit topic_metadata_refresh_interval_ms to product limi…](https://github.com/MaterializeInc/materialize/pull/10525) (@philip-stoev)
* [x] [#10538 doc/developer: correct release timing in release.md](https://github.com/MaterializeInc/materialize/pull/10538) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`d0034994c` Call `as_collection` instead of `flat_map` in `as_collection_core` when the MFP is trivial. (#10553)](https://github.com/MaterializeInc/materialize/commit/d0034994c8d710e2c75e6d77378fb063788ab06a) (@quodlibetor)
* [x] [`34b8c786d` release: v0.20.0-rc1](https://github.com/MaterializeInc/materialize/commit/34b8c786d1169883f8aa147b525dc4f34bb7655d) (@quodlibetor)

**Comment by umanwizard** [comment]
[d0034994c](https://github.com/MaterializeInc/materialize/commit/d0034994c8d710e2c75e6d77378fb063788ab06a) was cherry-picked from https://github.com/MaterializeInc/materialize/pull/10553 .
