### ISSUE TITLE
[Epic] Improve & Standardize SUBSCRIBE output

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#10593]
## Product Outcome
- Increase [Orgs using SUBSCRIBE](https://analytics.amplitude.com/materialize-org/chart/2nmqq81)
- Enable SUBSCRIBE for GUI use cases

## Documentation
- [Spec](https://www.notion.so/materialize/SUBSCRIBE-UX-b3c185ee0bd44d5a8ff47331b4082b34)
- [Design]()

## Issues
```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/materialize/issues/18129
- [ ] https://github.com/MaterializeInc/materialize/issues/5875
- [ ] https://github.com/MaterializeInc/materialize/issues/18436
- [ ] https://github.com/MaterializeInc/materialize/issues/18435
- [ ] https://github.com/MaterializeInc/materialize/issues/15685
- [ ] https://github.com/MaterializeInc/materialize/issues/18341
```

```[tasklist]
### Nice to Have
- [ ] https://github.com/MaterializeInc/materialize/issues/7435
- [ ] https://github.com/MaterializeInc/materialize/issues/17541
```

## Blockers
 

---
Original content for posterity
### Feature request

Recently we had https://github.com/MaterializeInc/materialize/issues/10437 come up

This behavior is within the spec for TAIL, but it is a confusing user experience - sometimes TAIL gives an initial snapshot as the first output, sometimes it gives a progress message catching up to the AS OF and then a snapshot. This behavior is correct, but also organic - we never really decided what we'd like the output to look like in all these cases, we're just shuffling messages from dataflow.

Scope of this task is actually determining _what_ we want TAIL to output in these cases (candidate proposal is, eg. "always output an initial progress messaging catching up to AS OF, synthesizing it in cases where we wouldn't generate it today"). Once we've determined that we can work with dataflow to conform to the spec, but need that spec first.

Some relevant internal discussion https://materializeinc.slack.com/archives/C02PPB50ZHS/p1644013693423659

**Comment by benesch** [comment]
One other piece I'd like in the `TAIL` spec: some way to guarantee that you can restart a `TAIL` within some time window. Right now, if your `TAIL` connection is severed, you might not be able to restart `AS OF` the last timestamp you saw closed, because the logical compaction window may have advanced beyond what you saw. (Right now, it almost _certainly_ has advanced, because the default logical compaction window is 1ms.) You can get a new snapshot, of course, but that might be annoying/expensive to handle.

Per @andrioni, a workaround for now is to `ALTER INDEX ... SET logical_compaction_window = 'something larger than 1ms'`. This isn't ideal, though, because you override the logical compaction window permanently, and will compete with another session's desires.

Roughly speaking, I'm imagining something like:

```
TAIL AS OF ... KEEP LEASE FOR INTERVAL '1 minute'
```

That would guarantee that if your `TAIL` was severed, the `ADAPTER` would keep a read hold on the underlying collection for up to 1m, to give you a chance to reconnect and start streaming again from where you left off, without needing to fetch a brand new snapshot.

One of the motivations here is to provide the illusion of zero-downtime upgrades of Materialize Platform. When we upgrade `materialized`, we have no choice but to sever existing SQL connections; clients can paper over this interruption if they have a shot at restarting `TAIL` as long as Materialize comes back online relatively quickly.

**Comment by benesch** [comment]
Looks like the idea I posted above is actually already tracked by #7435.

**Comment by RobinClowers** [comment]
From my perspective, it would be great if we could always return the initial snapshot first, then the progress message, that way I tell if there are currently no results for the query easily.

**Comment by frankmcsherry** [comment]
Two concrete proposals (perhaps there are others):
1. The first messages `SUBSCRIBE` receives should be *updates* without the `progressed` bit set. They should all be for exactly the same time, and should be followed by a *progress* message with the `progressed` bit set and a `timestamp` of time + 1, indicating the completion of the snapshot.
2. The first message `SUBSCRIBE` receives should be a *progress* message with the `progressed` bit set and a `timestamp` of the snapshot timestamp. Subsequence updates follow the protocol without constraint, but the recipient understands that only updates at the snapshot timestamp should be part of the timestamp, even if MZ continues to send them updates at subsequent timestamps without an intervening progress message.

Both of these seem unambiguous. They could be different amounts of user-friendly, depending on whether it is more stressful to special case receiving the snapshot (1.) or more stressful having to watch for the snapshot's completion on your own (2.). The second approach is probably easiest for us to implement (as (1.) may require a state machine to tease apart snapshot data from not); I'm not sure if that means that the first approach is probably easier for the user, but it often works out that way. :D

**Comment by benesch** [comment]
If I were a user, I think I would want (1.)!

**Comment by frankmcsherry** [comment]
Fwiw, I think I would want (2.)!. At least, I foresee repeatedly getting the "empty snapshot" logic incorrect, failing to notice, and then needing to discover the snapshot time from the first `progressed` utterance subtracting one from its time .. blah blah.

**Comment by umanwizard** [comment]
FWIW what Debezium does is just includes something like "snapshot = true" in the data messages. What's wrong with doing something like that?

**Comment by benesch** [comment]
> FWIW what Debezium does is just includes something like "snapshot = true" in the data messages. What's wrong with doing something like that?

Makes it impossible to conclusively determine that you have received an empty snapshot.

**Comment by frankmcsherry** [comment]
We could also do "both" by starting with a progress message, then providing exactly the snapshot data, then a bracketing progress message that should always happen.

**Comment by chaas** [comment]
Linking in some additional customer feedback/suggestions: https://materializeinc.slack.com/archives/C02FWJ94HME/p1678128852826799

**Comment by rjnn** [comment]
Could we do the work on the materialize side to tag the updates, so there are 4 classes of updates? Like so:
CREATE
DELETE
UCREATE
UDELETE (these two will always be presented in Create followed by Delete order)

This way if you see a UCREATE then you know you're seeing the first half of an update, as opposed to a true CREATE.

**Comment by frankmcsherry** [comment]
+1 on the idea that if the users need `UPSERT` we should do that, and in other cases we may not want to read too much in to what they need (positives before negatives, the other way around, etc). My main recommendation would be to have the updates come ordered first by time (so that our batch boundaries needn't be surfaced) and then by row, so that the interested user can put their key columns first and receive and retire those results in a streaming fashion.

**Comment by rjnn** [comment]
Yes. The product requirement (as I understand it) is that the user wants is to be able to consume updates in a streaming fashion when the batches are large, without buffering the entire batch.

The mental model you should have is of a streaming set of stock ticker prices - at the first tick of the day, you get an update for every single ticker symbol, and right now you must buffer them all up to match up the Before/Afters, as there is no ordering guarantee. The specific ordering guarantee is maybe not relevant, as long as the user can keep a small buffer, and not have to write a separate code path for the "large batch" case.

**Comment by umanwizard** [comment]
@rjnn Not sure if I understand your point, can you clarify?

We already emit SUBSCRIBE records in timestamp order, and within a timestamp, all the updates are consolidated (so you won't see -1 and +1 for the same stock ticker at the same timestamp in your example).

So, if you wanted to maintain the set of all current stock prices, you could do so by just processing them in order and updating that set -- you would never need to buffer any diffs.

**Comment by ggnall** [comment]
@umanwizard can you describe this a bit more or give an example? I haven't seen a case in practice (or in our docs) where the -1/+1 pair is _not_ returned.

**Comment by chaas** [comment]
Following up @ggnall 's comment, here's a typical output and I see the -1/+1 pair being produced, and also the ordering of -1/+1 being inconsistent. Adding an index didn't change anything.
```
materialize=> CREATE SOURCE counter
  FROM LOAD GENERATOR COUNTER
  WITH (SIZE = '1');
materialize=> CREATE MATERIALIZED VIEW aggregate_sum AS
SELECT sum(counter) FROM counter;
materialize=> COPY (SUBSCRIBE (SELECT * FROM aggregate_sum)) TO STDOUT;
1678996793141	1	1711
1678996794000	1	1770
1678996794000	-1	1711
1678996795000	-1	1770
1678996795000	1	1830
1678996796000	-1	1830
1678996796000	1	1891
1678996797000	-1	1891
1678996797000	1	1953
1678996798000	1	2016
1678996798000	-1	1953
```

**Comment by benesch** [comment]
From discussion with @umanwizard and from reading up on the customer use case, I think there are three features we should add to `SUBSCRIBE`:

#### `WITHIN TIMESTAMP ORDER BY <expr>, ...`

When specified, the `SUBSCRIBE` output will be ordered by the specified expressions within each distinct timestamp. If the columns you specify form a key, then you're guaranteed that updates for a given key will be adjacent within each timestamp. If you want to order the diffs in a particular way, you can just toss `mz_diff` into the expression.

To be consistent with `SELECT`, I think the ordering of `SUBSCRIBE` should be unspecified if users do not explicitly request an ordering.

#### `ENVELOPE UPSERT (KEY <expr>)`

When specified, the output of the subscribe becomes `(mz_timestamp, mz_key, mz_value)`. `mz_key` is the specified key expression and `mz_value` is the data. There is no diff field.

Within each timestamp, the upsert envelope accumulates updates into a series of diff pairs (i.e., before/after pairs). Diff pairs representing an insert or update are emitted with `mz_value` set to the after value. Diff pairs representing a delete are emitted with an `mz_value` of `NULL`

The type of `mz_key` is the type of the key expression. The type of `mz_value` is a record type matching the row type of the `SUBSCRIBE` query.

#### `ENVELOPE DEBEZIUM (KEY <expr>)`

When specified, the output of the subscribe becomes `(mz_timestamp, mz_before, mz_after)`. There is again no diff field. Within each timestamp, the Debezium envelope accumulates updates into a series of diff pairs (i.e., before/after pairs). Diff pairs are emitted directly in `mz_before` and `mz_after`.

The type of `mz_before` and `mz_after` is a record type matching the row type of the `SUBSCRIBE` query.

----

All three forms allow users to avoid buffering an entire timestamp in memory client side, as long as the data has a key.

I believe most users will want `ENVELOPE UPSERT`, as I think the code to update local state is the most familiar to users:

```py
data = {}
for row in db.query("SUBSCRIBE ... ENVELOPE UPSERT (KEY ...)"):
    if row.mz_value:
        data[row.mz_key] = row.mz_value
    else:
        del data[row.mz_key]
```

`ENVELOPE DEBEZIUM` is good for users who want to be able to distinguish between a create and an update without 1) tracking that state client side and 2) reasoning about diffs.

**Comment by umanwizard** [comment]
@ggnall, @chaas let me explain more fully what I meant. You will never see -1 and +1 for the _entire same row_ within the same timestamp. This furthermore implies that, for relations with a primary key, you will never seen more than one positive diff for a given primary key for a given timestamp.

For example, in the stock ticket example, you might see

```
t0 +1 AMZN 999
t0 -1 AMZN 1000
```

if at time `t0` the value of `AMZN` decreased from 1000 to 999. However, you will _not_ see a bunch of intermediate states, like so:

```
t0 +1 AMZN 999
t0 -1 AMZN 998
t0 +1 AMZN 998
t0 -1 AMZN 1000
```

The reason is simply that we consolidate all the records within a timestamp, cancelling out the -1s and +1s, before we ship them to the user. We don't document this property AFAIK but it's currently true.

I agree with what @benesch wrote about the general set of desirable envelopes (although I'm not 100% sold on the name `ENVELOPE DEBEZIUM` for the third one).

However, it's maybe useful to note that until we create `ENVELOPE UPSERT`, the above discussion suggests a workaround that might possibly be useful. Users can simulate the effect of `ENVELOPE UPSERT` by simply ignoring all negative diffs. Since there can only be one positive diff per key per timestamp, this does not risk accidentally recording any phantom values.

Thus, @benesch 's example code becomes:

```
data = {}
for (ts, diff, k, v) in db.query("SUBSCRIBE ... "):
    if diff < 0:
        pass
    else:
        assert(diff == 1)
        data[k] = v
```

There is one major caveat that I'm aware of, which is that since you're ignoring the negative diffs, there's no straightforward way to detect deletes. However, since the buffering cost is mainly an issue during the initial snapshot, in which deletes can't appear anyway, this is fine for the majority of use cases that I can imagine; it just requires writing some slightly cumbersome code (e.g. to do the ignoring-negatives logic during the initial timestamp and then cut over to full buffering, or to detect deletes in some other non-obvious way that I haven't thought of).

**Comment by ggnall** [comment]
Thank you Brennan for the summary! And Nikhil for the stub. 

I similarly think these paths are useful but want to workshop naming, syntax for options and pk selection, and result format in the design doc. It makes perfect sense to reinforce concept of envelopes (and the types) as in our sinks, but it seems like it could be confusing to associate "debezium"(like) with an implementation that may not use debezium in the pipeline at all. But I will save my bikeshedding for the next phase!

**Comment by umanwizard** [comment]
Another thing I want to point out is that `ENVELOPE DEBEZIUM` probably has large (O(the relation))  memory requirements.

**Comment by benesch** [comment]
Wait, why? Aren’t they all O(n) in the number of elements per timestamp in
space and O(nlogn) in the number of elements per time?

**Comment by umanwizard** [comment]
Sorry, I did not fully think that through -- on further reflection I think you're right

**Comment by benesch** [comment]
> I similarly think these paths are useful but want to workshop naming, syntax for options and pk selection, and result format in the design doc. It makes perfect sense to reinforce concept of envelopes (and the types) as in our sinks, but it seems like it could be confusing to associate "debezium"(like) with an implementation that may not use debezium in the pipeline at all. But I will save my bikeshedding for the next phase!

Sounds great! It occurs to me that feature flags will work splendidly here. We can ship all these envelope formats behind a feature flag without stabilizing them, even before we've finished the bikeshedding! And then you can shop the prototype around with some select prospect/customers and we can incorporate any feedback before stabilizing.

**Comment by rjnn** [comment]
I can confirm that "envelope debezium" is my understanding of what the user asked for

**Comment by andrewrodriguez-m** [comment]
@benesch. Question about the syntax of `ENVELOPE UPSERT (KEY <expr>)`. It seems like `ENVELOPE UPSERT KEY (c1, c2)` is more aligned with the rest of the syntax (vs `ENVELOPE UPSERT (KEY c1, c2)`). Wdyt?

**Comment by benesch** [comment]
> @benesch: Question about the syntax of `ENVELOPE UPSERT (KEY <expr>)`. It seems like `ENVELOPE UPSERT KEY (c1, c2)` is more aligned with the rest of the syntax (vs `ENVELOPE UPSERT (KEY c1, c2)`). Wdyt?

Ah, good point about multi-column keys, but I think we want `ENVELOPE UPSERT (KEY (c1, c2))`. The per-envelope options nested in parens are a syntactic construct that we've been slowly moving towards:

  * `ENVELOPE DEBEZIUM` used to support `ENVELOPE DEBEZIUM (TRANSACTION METADATA ...)`, and we'll want to bring that back at some point.
  * We've got another change in flight that proposes to add a similar per-envelope option to the upsert envelope for sources: https://github.com/MaterializeInc/materialize/pull/18722#discussion_r1165065299
