### ISSUE TITLE
dbt-materialize: epic

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10600]
Here is the laundry list of work I think we should do on our dbt adapter:

  * [x] Produce a proper error message when attempting to use an incremental materialization. See [TODO in incremental.sql](https://github.com/MaterializeInc/materialize/blob/main/misc/dbt-materialize/dbt/include/materialize/macros/materializations/incremental.sql). (#11263)
  * [x] Deprecate the index custom materialization and replace it with support for https://docs.getdbt.com/reference/resource-configs/postgres-configs#indexes. This probably just requires implementing `materialize__get_create_index_sql` the same way as [`postgresql__get_create_index_sql`](https://github.com/dbt-labs/dbt-core/blob/22416980d19888d7bbbcfcda639c16d37a80b948/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L17-L30) (#11538).
  * [x] ~Consider whether to deprecate the `materializedview` custom materialization in favor of explicit index creation, since a materialized view is just a view with an index on it.~
  * [x] ~Evaluate whether we can replace the source custom materialization with [external tables](https://github.com/dbt-labs/dbt-external-tables).~
  * [x] ~Evaluate whether we can replace the sink custom materialization with [post-hooks](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook) on models.~
  * [x] ~Explore whether custom metadata on [exposures](https://docs.getdbt.com/docs/building-a-dbt-project/exposures) could be a better long-term integration point for sinks.~
  * [x] Audit macros in [adapters.sql](https://github.com/MaterializeInc/materialize/blob/main/misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql). Pretty much all of those macros should be direct copies of their [PostgreSQL counterparts](https://github.com/dbt-labs/dbt-core/blob/22416980d19888d7bbbcfcda639c16d37a80b948/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L17-L30). #12428 
  * [x] Check whether #10391 is causing subtle bugs when dbt is talking to a `materialized` instance with more than one database.
  * [ ] #13131

**Blocked tasks:**

  * [ ] #12436
  * [x] https://github.com/MaterializeInc/materialize-dbt-utils/issues/17

Other bugs to look into:

  * [x] #7675
  * [x] https://github.com/MaterializeInc/materialize/issues/5448
  * [x] https://github.com/MaterializeInc/materialize/issues/5462

Work items for the SQL team:

  * [ ] #5266
  * [ ] #5301
  * [x] #5302
  * [x] #10449
  * [x] #10601
  * [x] #10391

**Comment by benesch** [comment]
Noting down Zoom discussion from today: dbt external tables are a bit nonstandard. Maybe we should stick with our current approach of using custom materializations.

On that subject, the thing that's funniest about our current custom materializations is that we require you to invent exactly the name for your source/sink that dbt expects you to use. For example:

```sql
{% set source_name %}
    {{ mz_generate_name('market_orders_raw') }}
{% endset %}

CREATE MATERIALIZED SOURCE {{ source_name }} FROM PUBNUB
SUBSCRIBE KEY 'sub-c-4377ab04-f100-11e3-bffd-02ee2ddab7fe'
CHANNEL 'pubnub-market-orders'
```

If you don't name your source the same way as your file, I _think_ lots of things go wrong, too.

To make this work more like dbt views, we'd drop the `CREATE SOURCE` bit, and instead you'd write:

```sql
# market_orders_raw.sql
PUBNUB SUBSCRIBE KEY 'sub-c-4377ab04-f100-11e3-bffd-02ee2ddab7fe'
CHANNEL 'pubnub-market-orders'
```

It looks a bit funny at first, but I think it's much more in line with the dbt way! If we go with this approach, we won't need to invent new YAML for the `CREATE SOURCE` and `CREATE SINK` statements.

**Comment by morsapaes** [comment]
+1, it makes sense to explore this before going down a more complicated path. I'll write an overview covering both approaches so we can also get some feedback from current `dbt-materialize` users.

**Comment by jwills** [comment]
My two cents: I think I got it wrong by including SOURCES/SINKS as core concepts in `dbt-materialize`; I think they should live outside of the core dbt workflow and treated as [dbt sources](https://docs.getdbt.com/docs/building-a-dbt-project/using-sources/) or [exposures](https://docs.getdbt.com/docs/building-a-dbt-project/exposures/).

**Comment by benesch** [comment]
Yeah, we've been trying to wrap our heads around exactly that question!

---

**Claim:** Materialize sources should correspond to dbt sources, managed via [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables). Materialize sinks correspond to dbt exposures, managed via an as-yet unwritten dbt plugin.

**Argument for:** This is more in line with the dbt philosophy. Models are meant to represent *transformations* of data. Sources and sinks are neither; and in fact they are correspond nearly _exactly_ to dbt sources and exposures. Users will be less confused if dbt sources correspond directly to Materialize sources.

**Argument against:** Managing Materialize sources with dbt becomes harder. Users have to add `dbt run-operation stage_external_sources` to their dbt deployment. We have to reinvent the `CREATE SOURCE` syntax in YAML. Keeping this up to date is a permanent maintenance burden. The same argument applies to sinks, except there isn't even a `dbt-external-exposures` plugin yet, so we'd have to invent it.

---

**Claim:** Materialize sources and sinks should remain as custom materialization types.

**Argument for:** this approach "just works" with dbt. Users don't need to change their dbt deployment; they just keep running `dbt run` like normal. We don't need to invent new YAML syntax for sources or sinks. We don't need to write new dbt adapters or macros.

**Argument against:** Users are confused that Materialize sources are not dbt sources. You can't write `{{ source('name_of_source') }}; you have to write `{{ ref('name_of_source') }}`. I imagine there is a similar confusion with sinks: you can write `{{ ref('name_of_sink') }}`, and dbt will accept it, but you can't actually `SELECT` from a sink, and that query will fail.

---

@jwills I'd love to get your thoughts on the above, if you have a sec.

**Comment by jwills** [comment]
Here's another thought to consider-- have the sinks and sources be defined as pre-or-post hooks on the corresponding model definitions? (So a SOURCE would be defined via a pre-hook on the initial view creation and then SINK would be defined as a post-hook on the final view creation) https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook

Virtue: it's just dbt (no external tables, no `dbt run-operation`), and the source/sink definitions can be done inline in SQL with or without macros (so no re-defining sources/sinks via YAML, which, yuck.)
Cons: still not as clean/expected as the `sources` construct (which unfortunately doesn't allow you to include pre/post-hooks for source references, although I wonder if we could hack the mz adapter to allow it to via some other mechanism?)

**Comment by jwills** [comment]
and yeah @benesch happy to chat about it if you want, just DM me in the dbt/MZ Slacks and we can find a time

**Comment by benesch** [comment]
Sounds great! I think @morsapaes was planning to poll some dbt-materialize users about what they'd like, so maybe we'll plan to snag you once we've collected that data!

**Comment by morsapaes** [comment]
Thanks everyone for pitching in! For the most part, the discussions and different options considered for sources/sinks are captured in [this gist](https://gist.github.com/morsapaes/03cb046ba4a984da644263c7e22cf094).

The **TL;DR** is that there isn't a good abstraction in dbt for this right now. To avoid changing the implementation multiple times, we'll stick to the custom materializations and follow the discussions around [external nodes](https://github.com/dbt-labs/dbt-core/discussions/5073) + [revamping dbt's interfaces](https://github.com/dbt-labs/dbt-core/blob/main/docs/roadmap/2022-05-dbt-a-core-story.md#scene-2-modular-programmatic-interfaces). In the meantime, we can also factor in the platform work on our side.

**Comment by morsapaes** [comment]
Closing out this epic, as the remaining two tasks are blocked by engineering work. We're working with the dbt team to figure out some ways to improve support for sources (in particular, multi-output sources) and sinks (see [this discussion](https://github.com/dbt-labs/dbt-core/discussions/6104#discussioncomment-3957001)).
