### ISSUE TITLE
release: v0.21.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10727]
The following PRs in [`v0.21.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.21.0-rc1) require review:
* [x] [#10562 Prepare next phase of development: v0.20.1-dev](https://github.com/MaterializeInc/materialize/pull/10562) (@quodlibetor)
* [x] [#10579 test,limits: Adjust the WhereExpression to match reality](https://github.com/MaterializeInc/materialize/pull/10579) (@philip-stoev)
* [x] [#10580 test,nightly: remove the --workers 32 scenario](https://github.com/MaterializeInc/materialize/pull/10580) (@philip-stoev)
* [x] [#10490 testdrive: various cleanups](https://github.com/MaterializeInc/materialize/pull/10490) (@benesch)
* [x] [#10574 Try adding cargo2junit for cargo test step](https://github.com/MaterializeInc/materialize/pull/10574) (@nharring-adjacent)
* [x] [#10603 xcompile: use alternate target directory](https://github.com/MaterializeInc/materialize/pull/10603) (@benesch)
* [x] [#10602 Tidying `Command`s and `Response`s](https://github.com/MaterializeInc/materialize/pull/10602) (@frankmcsherry)
* [x] [#10604 testdrive,sqllogictest,mzcompose: add basic test analytics integration](https://github.com/MaterializeInc/materialize/pull/10604) (@benesch)
* [x] [#10615 ci: upload test analytics report on failure, too](https://github.com/MaterializeInc/materialize/pull/10615) (@benesch)
* [x] [#10614 sql: hoist name resolution out of plan::query module](https://github.com/MaterializeInc/materialize/pull/10614) (@benesch)
* [x] [#10618 *: format cargo.toml manifests](https://github.com/MaterializeInc/materialize/pull/10618) (@benesch)
* [x] [#10616 ci: wire up junit annotations](https://github.com/MaterializeInc/materialize/pull/10616) (@benesch)
* [x] [#10620 ci/test: fix pipeline trimming with new analyze job](https://github.com/MaterializeInc/materialize/pull/10620) (@benesch)
* [x] [#10619 sql: use `ScalarType` rather than `mz_pgrepr::Type` as param type](https://github.com/MaterializeInc/materialize/pull/10619) (@benesch)
* [x] [#10256 ci: enable sccache](https://github.com/MaterializeInc/materialize/pull/10256) (@benesch)
* [x] [#10625 ci/deploy: fix devsite deploy](https://github.com/MaterializeInc/materialize/pull/10625) (@benesch)
* [x] [#10626 ci/test: fix a few buglets](https://github.com/MaterializeInc/materialize/pull/10626) (@benesch)
* [x] [#10652 mzcompose: always install dev deps when invoked from the root](https://github.com/MaterializeInc/materialize/pull/10652) (@benesch)
* [x] [#10654 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/10654) (@benesch)
* [x] [#10653 ci/test: fix test analysis from failing when no jobs](https://github.com/MaterializeInc/materialize/pull/10653) (@benesch)
* [x] [#10657 doc/user: complete and polish release notes for v0.20.0](https://github.com/MaterializeInc/materialize/pull/10657) (@benesch)
* [x] [#10665 Release v0.20.0](https://github.com/MaterializeInc/materialize/pull/10665) (@quodlibetor)
* [x] [#10677 dbt-materialize: fix hooks that specify `transaction: true`](https://github.com/MaterializeInc/materialize/pull/10677) (@benesch)
* [x] [#10683 antithesis: Avoid network disruption between Testdrive and Kafka](https://github.com/MaterializeInc/materialize/pull/10683) (@philip-stoev)
* [x] [#10685 test: Adjust tests to account for #10661](https://github.com/MaterializeInc/materialize/pull/10685) (@philip-stoev)
* [x] [#10686 feature-benchmark: Add scenarios around basic coordinator operations:](https://github.com/MaterializeInc/materialize/pull/10686) (@philip-stoev)
* [x] [#10688 feature-benchmark: Discard the first measurement obtained](https://github.com/MaterializeInc/materialize/pull/10688) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`e278d5afa` materialized: add missing "MZ_" prefix to new frontegg environment variables](https://github.com/MaterializeInc/materialize/commit/e278d5afadbfedf20ad84767c12e742188663943) (@ruchirK)
* [ ] [`29098818b` release: v0.21.0-rc1](https://github.com/MaterializeInc/materialize/commit/29098818b10f91a3e6a8dfbab97ceb00da7455e1) (@ruchirK)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#10527 mzcompose,feature-benchmark: Ensure --dev option is in effect when ne…](https://github.com/MaterializeInc/materialize/pull/10527) (@philip-stoev)
* [ ] [#10517 Add issue template for a proposal for a new optimization.](https://github.com/MaterializeInc/materialize/pull/10517) (@wangandi)
* [ ] [#10541 test/persist: add test that compaction is happening as expected](https://github.com/MaterializeInc/materialize/pull/10541) (@ruchirK)
* [ ] [#10543 test/kafka-ingest: remove demand optimization when rendering upsert s…](https://github.com/MaterializeInc/materialize/pull/10543) (@ruchirK)
* [ ] [#10514 persist,dataflow: simplify source restore logic by assuming atomic seal](https://github.com/MaterializeInc/materialize/pull/10514) (@aljoscha)
* [ ] [#10434 coord: only allow one materialization for persisted sources](https://github.com/MaterializeInc/materialize/pull/10434) (@aljoscha)
* [ ] [#10553 Call `as_collection` instead of `flat_map` in `as_collection_core` when the MFP is trivial.](https://github.com/MaterializeInc/materialize/pull/10553) (@umanwizard)
* [ ] [#10552 rename all workspace crates to have `mz-` prefix](https://github.com/MaterializeInc/materialize/pull/10552) (@petrosagg)
* [ ] [#10558 Fix nightly test aws-config config](https://github.com/MaterializeInc/materialize/pull/10558) (@quodlibetor)
* [ ] [#10557 sql: if list slice is empty, return {} instead of NULL](https://github.com/MaterializeInc/materialize/pull/10557) (@sploiselle)
* [ ] [#10551 Further partition storage and compute state](https://github.com/MaterializeInc/materialize/pull/10551) (@frankmcsherry)
* [ ] [#10562 Prepare next phase of development: v0.20.1-dev](https://github.com/MaterializeInc/materialize/pull/10562) (@quodlibetor)
* [ ] [#10560 sql,sql-parser: hoist operator semantic analysis out of parser](https://github.com/MaterializeInc/materialize/pull/10560) (@benesch)
* [ ] [#10564 build(deps-dev): bump types-requests from 2.27.7 to 2.27.8 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10564) (@dependabot[bot])
* [ ] [#10528 doc/user: Update Postgres source documentation page and guides](https://github.com/MaterializeInc/materialize/pull/10528) (@morsapaes)
* [ ] [#10569 Fix full upgrade tests](https://github.com/MaterializeInc/materialize/pull/10569) (@quodlibetor)
* [ ] [#10542 Add lossless, fallible conversion from Type->ScalarType](https://github.com/MaterializeInc/materialize/pull/10542) (@nharring-adjacent)
* [ ] [#10508 Revert "test/persistence: temporarily disable flaky test"](https://github.com/MaterializeInc/materialize/pull/10508) (@ruchirK)
* [ ] [#10570 upgrade: Make --tests metavar reflect the legal choices](https://github.com/MaterializeInc/materialize/pull/10570) (@quodlibetor)
* [ ] [#10573 repr: change numeric constant types to decrease fallible conversions](https://github.com/MaterializeInc/materialize/pull/10573) (@benesch)
* [ ] [#10575 ci/test/cargo-test: convert workflow to Python](https://github.com/MaterializeInc/materialize/pull/10575) (@benesch)
* [ ] [#10579 test,limits: Adjust the WhereExpression to match reality](https://github.com/MaterializeInc/materialize/pull/10579) (@philip-stoev)
* [ ] [#10580 test,nightly: remove the --workers 32 scenario](https://github.com/MaterializeInc/materialize/pull/10580) (@philip-stoev)
* [ ] [#10568 Partition worker logic into storage and compute](https://github.com/MaterializeInc/materialize/pull/10568) (@frankmcsherry)
* [ ] [#10583 dataflow: directly get the element from the map](https://github.com/MaterializeInc/materialize/pull/10583) (@petrosagg)
* [ ] [#10584 dataflow/storage: Use Duration instead of ms](https://github.com/MaterializeInc/materialize/pull/10584) (@antiguru)
* [ ] [#10585 use `std::time::Duration` instead of `_ms` suffixed variables](https://github.com/MaterializeInc/materialize/pull/10585) (@petrosagg)
* [ ] [#10591 Update mkrelease for new process](https://github.com/MaterializeInc/materialize/pull/10591) (@quodlibetor)
* [ ] [#10544 sql: move type name resolution into name resolution pass](https://github.com/MaterializeInc/materialize/pull/10544) (@benesch)
* [ ] [#10588 ci/nightly: permit skipping tests when manually triggering build](https://github.com/MaterializeInc/materialize/pull/10588) (@benesch)
* [ ] [#10590 Add Interval binary encoding test](https://github.com/MaterializeInc/materialize/pull/10590) (@jkosh44)
* [ ] [#10592 improve docs for mz_ore::task](https://github.com/MaterializeInc/materialize/pull/10592) (@guswynn)
* [ ] [#10565 Add new release qualification tests to dashboard-links](https://github.com/MaterializeInc/materialize/pull/10565) (@quodlibetor)
* [ ] [#10509 qgm: implement `SimplifyOuterJoins` rule in QGM](https://github.com/MaterializeInc/materialize/pull/10509) (@aalexandrov)
* [ ] [#10597 sql: exclude scalar table funcs from select *](https://github.com/MaterializeInc/materialize/pull/10597) (@mjibson)
* [ ] [#10216 Add docs for AWS per-source roles/profiles](https://github.com/MaterializeInc/materialize/pull/10216) (@quodlibetor)
* [ ] [#10382 Document how to bin/scratch launched items into Grafana](https://github.com/MaterializeInc/materialize/pull/10382) (@quodlibetor)
* [ ] [#10490 testdrive: various cleanups](https://github.com/MaterializeInc/materialize/pull/10490) (@benesch)
* [ ] [#10599 sqllogictest,testdrive: add junit output reports](https://github.com/MaterializeInc/materialize/pull/10599) (@benesch)
* [ ] [#10574 Try adding cargo2junit for cargo test step](https://github.com/MaterializeInc/materialize/pull/10574) (@nharring-adjacent)
* [ ] [#10603 xcompile: use alternate target directory](https://github.com/MaterializeInc/materialize/pull/10603) (@benesch)
* [ ] [#10567 Improve feature benchmark experience in Buildkite](https://github.com/MaterializeInc/materialize/pull/10567) (@quodlibetor)
* [ ] [#10596 Remove AWS External IDs from any part of source descriptions](https://github.com/MaterializeInc/materialize/pull/10596) (@quodlibetor)
* [ ] [#10598 Fix bounds check when creating Intervals](https://github.com/MaterializeInc/materialize/pull/10598) (@jkosh44)
* [ ] [#10611 ci/cargo-test: include package name in test name](https://github.com/MaterializeInc/materialize/pull/10611) (@benesch)
* [ ] [#10606 Advance bindings *past* last offset](https://github.com/MaterializeInc/materialize/pull/10606) (@frankmcsherry)
* [ ] [#10610 Move AWS stuff to StorageState](https://github.com/MaterializeInc/materialize/pull/10610) (@frankmcsherry)
* [ ] [#10602 Tidying `Command`s and `Response`s](https://github.com/MaterializeInc/materialize/pull/10602) (@frankmcsherry)
* [ ] [#10604 testdrive,sqllogictest,mzcompose: add basic test analytics integration](https://github.com/MaterializeInc/materialize/pull/10604) (@benesch)
* [ ] [#10607 correct kafka error message during purification](https://github.com/MaterializeInc/materialize/pull/10607) (@elindsey)
* [ ] [#10594 docs: running confluent with the right JDK version](https://github.com/MaterializeInc/materialize/pull/10594) (@pH14)
* [ ] [#10608 ci: Annotate each build with its docker image tags](https://github.com/MaterializeInc/materialize/pull/10608) (@antifuchs)
* [ ] [#10572 Support for LIKE escape strings, not just escape characters.](https://github.com/MaterializeInc/materialize/pull/10572) (@TonyRippy)
* [ ] [#10615 ci: upload test analytics report on failure, too](https://github.com/MaterializeInc/materialize/pull/10615) (@benesch)
* [ ] [#10614 sql: hoist name resolution out of plan::query module](https://github.com/MaterializeInc/materialize/pull/10614) (@benesch)
* [ ] [#10612 Introduce an owned boundary type to Worker](https://github.com/MaterializeInc/materialize/pull/10612) (@frankmcsherry)
* [ ] [#10618 *: format cargo.toml manifests](https://github.com/MaterializeInc/materialize/pull/10618) (@benesch)
* [ ] [#10616 ci: wire up junit annotations](https://github.com/MaterializeInc/materialize/pull/10616) (@benesch)
* [ ] [#10620 ci/test: fix pipeline trimming with new analyze job](https://github.com/MaterializeInc/materialize/pull/10620) (@benesch)
* [ ] [#10619 sql: use `ScalarType` rather than `mz_pgrepr::Type` as param type](https://github.com/MaterializeInc/materialize/pull/10619) (@benesch)
* [ ] [#10256 ci: enable sccache](https://github.com/MaterializeInc/materialize/pull/10256) (@benesch)
* [ ] [#10625 ci/deploy: fix devsite deploy](https://github.com/MaterializeInc/materialize/pull/10625) (@benesch)
* [ ] [#10626 ci/test: fix a few buglets](https://github.com/MaterializeInc/materialize/pull/10626) (@benesch)
* [ ] [#10627 build(deps): bump hyper from 0.14.16 to 0.14.17](https://github.com/MaterializeInc/materialize/pull/10627) (@dependabot[bot])
* [ ] [#10628 build(deps): bump rdkafka from `9594a34` to `cc45e9e`](https://github.com/MaterializeInc/materialize/pull/10628) (@dependabot[bot])
* [ ] [#10629 build(deps): bump console-subscriber from 0.1.1 to 0.1.2](https://github.com/MaterializeInc/materialize/pull/10629) (@dependabot[bot])
* [ ] [#10631 build(deps): bump crc32fast from 1.3.1 to 1.3.2](https://github.com/MaterializeInc/materialize/pull/10631) (@dependabot[bot])
* [ ] [#10633 build(deps): bump prost-reflect from 0.5.3 to 0.5.6](https://github.com/MaterializeInc/materialize/pull/10633) (@dependabot[bot])
* [ ] [#10645 build(deps): bump rlimit from 0.6.2 to 0.7.0](https://github.com/MaterializeInc/materialize/pull/10645) (@dependabot[bot])
* [ ] [#10646 build(deps): bump digest from 0.10.0 to 0.10.2](https://github.com/MaterializeInc/materialize/pull/10646) (@dependabot[bot])
* [ ] [#10650 build(deps): bump sysinfo from 0.23.0 to 0.23.2](https://github.com/MaterializeInc/materialize/pull/10650) (@dependabot[bot])
* [ ] [#10651 build(deps): bump timely from `3cf1540` to `731b06e`](https://github.com/MaterializeInc/materialize/pull/10651) (@dependabot[bot])
* [ ] [#10632 build(deps): bump serde_json from 1.0.78 to 1.0.79](https://github.com/MaterializeInc/materialize/pull/10632) (@dependabot[bot])
* [ ] [#10652 mzcompose: always install dev deps when invoked from the root](https://github.com/MaterializeInc/materialize/pull/10652) (@benesch)
* [ ] [#10654 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/10654) (@benesch)
* [ ] [#10466 build(deps): bump tracing from 0.1.29 to 0.1.30](https://github.com/MaterializeInc/materialize/pull/10466) (@dependabot[bot])
* [ ] [#10653 ci/test: fix test analysis from failing when no jobs](https://github.com/MaterializeInc/materialize/pull/10653) (@benesch)
* [ ] [#10319 doc/platform: flesh out user experience doc](https://github.com/MaterializeInc/materialize/pull/10319) (@benesch)
* [ ] [#10657 doc/user: complete and polish release notes for v0.20.0](https://github.com/MaterializeInc/materialize/pull/10657) (@benesch)
* [ ] [#10658 doc/user: fix typo in AWS credential docs](https://github.com/MaterializeInc/materialize/pull/10658) (@benesch)
* [ ] [#10659 deps: move junit-xml to requirements.txt](https://github.com/MaterializeInc/materialize/pull/10659) (@benesch)
* [ ] [#10660 test,testdrive: Add a Nightly testdrive run with $ kafka-create-topic…](https://github.com/MaterializeInc/materialize/pull/10660) (@philip-stoev)
* [ ] [#10648 test/kafka-ingest: don't demand column key0](https://github.com/MaterializeInc/materialize/pull/10648) (@ruchirK)
* [ ] [#10589 Fix underflow/overflow during binary encoding/decoding of Intervals](https://github.com/MaterializeInc/materialize/pull/10589) (@jkosh44)
* [ ] [#10622 Documents a footgun in the `VariadicFunc::propagates_nulls` function.](https://github.com/MaterializeInc/materialize/pull/10622) (@TonyRippy)
* [ ] [#10535 avro: improve schema resolution errors](https://github.com/MaterializeInc/materialize/pull/10535) (@pH14)
* [ ] [#10623 Adds sqllogictests that verifies nulls are propagated properly  ](https://github.com/MaterializeInc/materialize/pull/10623) (@TonyRippy)
* [ ] [#10668 Send WARNING instead of NOTICE when trying to commit with no active tx](https://github.com/MaterializeInc/materialize/pull/10668) (@andrioni)
* [ ] [#10443 dbt-materialize: fix list_relations_without_caching](https://github.com/MaterializeInc/materialize/pull/10443) (@benesch)
* [ ] [#10670 dbt-materialize: release v1.0.1.post1](https://github.com/MaterializeInc/materialize/pull/10670) (@benesch)
* [ ] [#10663 mkrelease: Set git-ref var in dashboard-links generated urls](https://github.com/MaterializeInc/materialize/pull/10663) (@quodlibetor)
* [ ] [#10665 Release v0.20.0](https://github.com/MaterializeInc/materialize/pull/10665) (@quodlibetor)
* [ ] [#10674 skip ssl test for versions it can't be run for](https://github.com/MaterializeInc/materialize/pull/10674) (@guswynn)
* [ ] [#10624 sql: refactor type types](https://github.com/MaterializeInc/materialize/pull/10624) (@benesch)
* [ ] [#10677 dbt-materialize: fix hooks that specify `transaction: true`](https://github.com/MaterializeInc/materialize/pull/10677) (@benesch)
* [ ] [#10683 antithesis: Avoid network disruption between Testdrive and Kafka](https://github.com/MaterializeInc/materialize/pull/10683) (@philip-stoev)
* [ ] [#10685 test: Adjust tests to account for #10661](https://github.com/MaterializeInc/materialize/pull/10685) (@philip-stoev)
* [ ] [#10686 feature-benchmark: Add scenarios around basic coordinator operations:](https://github.com/MaterializeInc/materialize/pull/10686) (@philip-stoev)
* [ ] [#10688 feature-benchmark: Discard the first measurement obtained](https://github.com/MaterializeInc/materialize/pull/10688) (@philip-stoev)
* [ ] [#10662 persistence,test: A generalized test to test multiple failpoints in a…](https://github.com/MaterializeInc/materialize/pull/10662) (@philip-stoev)
* [ ] [#10687 doc/user: Update instructions to run lint check locally](https://github.com/MaterializeInc/materialize/pull/10687) (@morsapaes)
* [ ] [#10691 Support setting `standard_conforming_strings` to `on`](https://github.com/MaterializeInc/materialize/pull/10691) (@andrioni)
* [ ] [#10690 doc/user: Update CDC guides](https://github.com/MaterializeInc/materialize/pull/10690) (@morsapaes)
* [ ] [#10672 test/kafka-ingest: add a smoke test in CI](https://github.com/MaterializeInc/materialize/pull/10672) (@ruchirK)
* [ ] [#10695 allow non `Send` futures in a few coord related traits](https://github.com/MaterializeInc/materialize/pull/10695) (@petrosagg)
* [ ] [#10684 coord: test that type OIDs match PostgreSQL](https://github.com/MaterializeInc/materialize/pull/10684) (@benesch)
* [ ] [#10698 coord: add the Send bound only where needed](https://github.com/MaterializeInc/materialize/pull/10698) (@petrosagg)
* [ ] [#10682 pgtest: error and docs improvements](https://github.com/MaterializeInc/materialize/pull/10682) (@mjibson)
* [ ] [#10697 Move Client methods to Controller inherents](https://github.com/MaterializeInc/materialize/pull/10697) (@frankmcsherry)
* [ ] [#10696 persist: add s3 coverage to nemesis](https://github.com/MaterializeInc/materialize/pull/10696) (@danhhz)
* [ ] [#10702 persist: remove unused allow_compaction dataflow operator](https://github.com/MaterializeInc/materialize/pull/10702) (@ruchirK)
* [ ] [#10703 persist: remove PersistentUnorderedInput operator](https://github.com/MaterializeInc/materialize/pull/10703) (@danhhz)
* [ ] [#10359 optimize: fuse filters during canonicalize mfp](https://github.com/MaterializeInc/materialize/pull/10359) (@pH14)
* [ ] [#10577 materialized: support Materialize Cloud authentication](https://github.com/MaterializeInc/materialize/pull/10577) (@mjibson)
* [ ] [#10704 Remove `Controller` assertions and return errors instead](https://github.com/MaterializeInc/materialize/pull/10704) (@frankmcsherry)
* [ ] [`e278d5afa` materialized: add missing "MZ_" prefix to new frontegg environment variables](https://github.com/MaterializeInc/materialize/commit/e278d5afadbfedf20ad84767c12e742188663943) (@ruchirK)
* [ ] [`29098818b` release: v0.21.0-rc1](https://github.com/MaterializeInc/materialize/commit/29098818b10f91a3e6a8dfbab97ceb00da7455e1) (@ruchirK)

**Comment by ruchirK** [comment]
Can someone from the sql team verify that #10619 looks ok @benesch @sploiselle ? Thanks!

**Comment by sploiselle** [comment]
#10619 is very above-board!

**Comment by ruchirK** [comment]
tyvm!
