### ISSUE TITLE
Streaming Improvements

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1078]
This is an epic to house things that are maybe a bit more than musings about things we should consider to improve our streaming support.

Streaming in this case means *both* things that should emit events immediately when differential can emit them, and also cursors into query results. My intuition is that both of these categories should use similar machinery, and so all of them should be considered together.

- [ ] #1031 Push `Portal` suspension back into the dataflow.
- [x] #1076 Use postgres' LISTEN/NOTIFY to support TAIL inside the pgwire protocol
- [ ] #1077 Support a postgres sink
- [x] #1080 Add something like a `stream_now()` function for dataflows

**Comment by benesch** [comment]
#1076 and #1080 are done now. #1031 and #1077 are still todo, but low priority. Going to close this issue because empirically I don't think this framing has panned out.
