### ISSUE TITLE
release: v0.21.0-rc2 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10857]
The following PRs in [`v0.21.0-rc2`](https://github.com/MaterializeInc/materialize/tree/v0.21.0-rc2) require review:
* [x] [#10647 dataflow: refactor PartitionTimestamps](https://github.com/MaterializeInc/materialize/pull/10647) (@ruchirK)
* [x] [#10692 feature-benchmark: Add scenario for Postgres CDC](https://github.com/MaterializeInc/materialize/pull/10692) (@philip-stoev)
* [x] [#10741 test,persistence: Adjust the --logical-compaction-window=off test for…](https://github.com/MaterializeInc/materialize/pull/10741) (@philip-stoev)
* [x] [#10754 test,persistence: Split the failpoints test in a separate Buildkite step](https://github.com/MaterializeInc/materialize/pull/10754) (@philip-stoev)
* [x] [#10770 ci/test: re-enable unused deps lint](https://github.com/MaterializeInc/materialize/pull/10770) (@benesch)
* [x] [#10802 redpanda: Update CI to use v21.11.8](https://github.com/MaterializeInc/materialize/pull/10802) (@philip-stoev)
* [x] [#10809 test: Move the postgres part of the debezium test to a subdirectory](https://github.com/MaterializeInc/materialize/pull/10809) (@philip-stoev)
* [x] [#10817 debezium,mysql: An end-to-end smoke test for MySQL + Debezium + Mz](https://github.com/MaterializeInc/materialize/pull/10817) (@philip-stoev)
* [x] [#10822 deps: update to AWS SDK v0.7.0](https://github.com/MaterializeInc/materialize/pull/10822) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`886ad8d2e` dataflow/timestamp: reallow duplicate times in add_binding](https://github.com/MaterializeInc/materialize/commit/886ad8d2ea6a4f349f0520c1c50fc12727f36db8) (@umanwizard)
* [x] [`de8349596` kafka: immediately cleanup metadata threads on drop](https://github.com/MaterializeInc/materialize/commit/de83495964a425894138019685d239504ccd2499) (@umanwizard)
* [x] [`178d64a46` release: v0.21.0-rc2](https://github.com/MaterializeInc/materialize/commit/178d64a4682f4a3e6b18c1fff4c07243418313da) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#10647 dataflow: refactor PartitionTimestamps](https://github.com/MaterializeInc/materialize/pull/10647) (@ruchirK)
* [ ] [#10689 sources: remove unused return value from SourceReader](https://github.com/MaterializeInc/materialize/pull/10689) (@petrosagg)
* [ ] [#10692 feature-benchmark: Add scenario for Postgres CDC](https://github.com/MaterializeInc/materialize/pull/10692) (@philip-stoev)
* [ ] [#9615 persist: periodically yield in Replay operator](https://github.com/MaterializeInc/materialize/pull/9615) (@danhhz)
* [ ] [#10676 add bin/unused-deps](https://github.com/MaterializeInc/materialize/pull/10676) (@guswynn)
* [ ] [#10710 materialized: add missing "MZ_" prefix to new frontegg environment variables](https://github.com/MaterializeInc/materialize/pull/10710) (@benesch)
* [ ] [#10709 ci: increase the priority of longer-running jobs](https://github.com/MaterializeInc/materialize/pull/10709) (@philip-stoev)
* [ ] [#10644 Adds support for ESCAPE clauses on LIKE/LIKE expressions ](https://github.com/MaterializeInc/materialize/pull/10644) (@TonyRippy)
* [ ] [#10705 sql: support multi-dimensional array subscripts](https://github.com/MaterializeInc/materialize/pull/10705) (@sploiselle)
* [ ] [#10712 test: Re-enable the --workers 32 Nightly job](https://github.com/MaterializeInc/materialize/pull/10712) (@philip-stoev)
* [ ] [#10707 coord, pgwire: implement client_min_messages](https://github.com/MaterializeInc/materialize/pull/10707) (@andrioni)
* [ ] [#10725 misc: small misc. fixes overlooked in #10705 ](https://github.com/MaterializeInc/materialize/pull/10725) (@sploiselle)
* [ ] [#10433 multi-worker tails](https://github.com/MaterializeInc/materialize/pull/10433) (@umanwizard)
* [ ] [#10715 dbt-materialize: Point to correct Materialize profile](https://github.com/MaterializeInc/materialize/pull/10715) (@morsapaes)
* [ ] [#10716 add unused-deps check to ci](https://github.com/MaterializeInc/materialize/pull/10716) (@guswynn)
* [ ] [#10711 ci/test: hoist ci_try out of subshell](https://github.com/MaterializeInc/materialize/pull/10711) (@benesch)
* [ ] [#10736 Revert "Revert "test/persistence: temporarily disable flaky test""](https://github.com/MaterializeInc/materialize/pull/10736) (@ruchirK)
* [ ] [#10737 doc/user: polish release notes for v0.21.0](https://github.com/MaterializeInc/materialize/pull/10737) (@benesch)
* [ ] [#10719 qgm: introduce `QGMError` type and use it in the HIR ⇒ QGM conversion](https://github.com/MaterializeInc/materialize/pull/10719) (@aalexandrov)
* [ ] [#10741 test,persistence: Adjust the --logical-compaction-window=off test for…](https://github.com/MaterializeInc/materialize/pull/10741) (@philip-stoev)
* [ ] [#10744 doc/user: mention that arbitrary expressions are supported in CREATE INDEX](https://github.com/MaterializeInc/materialize/pull/10744) (@benesch)
* [ ] [#10746 persist: split unsealed_drain into req/res components](https://github.com/MaterializeInc/materialize/pull/10746) (@danhhz)
* [ ] [#10694 Convert all tracing::*! invocations to be unprefixed](https://github.com/MaterializeInc/materialize/pull/10694) (@quodlibetor)
* [ ] [#10747 turn off unused deps ci temporarily](https://github.com/MaterializeInc/materialize/pull/10747) (@guswynn)
* [ ] [#10700 Add support for Array subqueries](https://github.com/MaterializeInc/materialize/pull/10700) (@jkosh44)
* [ ] [#10733 properly propagate csr server errors when fetching key schemas](https://github.com/MaterializeInc/materialize/pull/10733) (@guswynn)
* [ ] [#10752 Decorrelation: Do not attempt outer join if the join kind is inner.](https://github.com/MaterializeInc/materialize/pull/10752) (@wangandi)
* [ ] [#10750 dbt-materialize: fix custom materialization types](https://github.com/MaterializeInc/materialize/pull/10750) (@benesch)
* [ ] [#10754 test,persistence: Split the failpoints test in a separate Buildkite step](https://github.com/MaterializeInc/materialize/pull/10754) (@philip-stoev)
* [ ] [#10714 mzcompose,feature-benchmark: Usability improvements](https://github.com/MaterializeInc/materialize/pull/10714) (@philip-stoev)
* [ ] [#10748 persist: return all descriptions instead of querying one](https://github.com/MaterializeInc/materialize/pull/10748) (@danhhz)
* [ ] [#10753 Prevent paninc on Interval negation](https://github.com/MaterializeInc/materialize/pull/10753) (@jkosh44)
* [ ] [#10730 Support all KeyEnvelopes in upsert rendering](https://github.com/MaterializeInc/materialize/pull/10730) (@guswynn)
* [ ] [#10761 aws-util: depend on openssl-sys with the "vendored" feature](https://github.com/MaterializeInc/materialize/pull/10761) (@danhhz)
* [ ] [#10767 truncate datums](https://github.com/MaterializeInc/materialize/pull/10767) (@umanwizard)
* [ ] [#10768 Establish correct `since` for indexes](https://github.com/MaterializeInc/materialize/pull/10768) (@frankmcsherry)
* [ ] [#10150 mention username and password in CSR docs](https://github.com/MaterializeInc/materialize/pull/10150) (@guswynn)
* [ ] [#10770 ci/test: re-enable unused deps lint](https://github.com/MaterializeInc/materialize/pull/10770) (@benesch)
* [ ] [#10774 Make commands and responses generic in `Timestamp`](https://github.com/MaterializeInc/materialize/pull/10774) (@frankmcsherry)
* [ ] [#10773 Refactor `Controller` into `Compute` and `Storage` facets](https://github.com/MaterializeInc/materialize/pull/10773) (@frankmcsherry)
* [ ] [#10775 dataflow: Explicitly construct storage dataflows](https://github.com/MaterializeInc/materialize/pull/10775) (@antiguru)
* [ ] [#10776 Slice controller states by `GlobalId`](https://github.com/MaterializeInc/materialize/pull/10776) (@frankmcsherry)
* [ ] [#10779 build(deps): bump rand from 0.8.4 to 0.8.5](https://github.com/MaterializeInc/materialize/pull/10779) (@dependabot[bot])
* [ ] [#10782 build(deps): bump libc from 0.2.117 to 0.2.119](https://github.com/MaterializeInc/materialize/pull/10782) (@dependabot[bot])
* [ ] [#10784 build(deps): bump tracing from 0.1.30 to 0.1.31](https://github.com/MaterializeInc/materialize/pull/10784) (@dependabot[bot])
* [ ] [#10787 build(deps-dev): bump types-requests from 2.27.9 to 2.27.10 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10787) (@dependabot[bot])
* [ ] [#10788 build(deps): bump prettytable from 3.1.0 to 3.1.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10788) (@dependabot[bot])
* [ ] [#10790 build(deps): bump click from 8.0.3 to 8.0.4 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10790) (@dependabot[bot])
* [ ] [#10791 build(deps): bump setuptools from 60.8.2 to 60.9.3 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10791) (@dependabot[bot])
* [ ] [#10792 build(deps-dev): bump boto3 from 1.20.54 to 1.21.3 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10792) (@dependabot[bot])
* [ ] [#10786 build(deps): bump tracing-subscriber from 0.3.7 to 0.3.9](https://github.com/MaterializeInc/materialize/pull/10786) (@dependabot[bot])
* [ ] [#10796 build(deps): bump differential-dataflow from `19808dc` to `f862b65`](https://github.com/MaterializeInc/materialize/pull/10796) (@dependabot[bot])
* [ ] [#10797 build(deps): bump anyhow from 1.0.53 to 1.0.54](https://github.com/MaterializeInc/materialize/pull/10797) (@dependabot[bot])
* [ ] [#10789 build(deps-dev): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.20.49 to 1.21.3 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10789) (@dependabot[bot])
* [ ] [#10802 redpanda: Update CI to use v21.11.8](https://github.com/MaterializeInc/materialize/pull/10802) (@philip-stoev)
* [ ] [#10806 build(deps): bump anyhow from 1.0.54 to 1.0.55](https://github.com/MaterializeInc/materialize/pull/10806) (@dependabot[bot])
* [ ] [#10809 test: Move the postgres part of the debezium test to a subdirectory](https://github.com/MaterializeInc/materialize/pull/10809) (@philip-stoev)
* [ ] [#10811 testdrive: support env logger](https://github.com/MaterializeInc/materialize/pull/10811) (@antiguru)
* [ ] [#10817 debezium,mysql: An end-to-end smoke test for MySQL + Debezium + Mz](https://github.com/MaterializeInc/materialize/pull/10817) (@philip-stoev)
* [ ] [#10820 build(deps): bump cc from 1.0.72 to 1.0.73](https://github.com/MaterializeInc/materialize/pull/10820) (@dependabot[bot])
* [ ] [#10804 build(deps): bump prost-reflect from 0.5.7 to 0.6.0](https://github.com/MaterializeInc/materialize/pull/10804) (@dependabot[bot])
* [ ] [#10822 deps: update to AWS SDK v0.7.0](https://github.com/MaterializeInc/materialize/pull/10822) (@benesch)
* [ ] [#10803 build(deps): bump clap from 3.0.14 to 3.1.1](https://github.com/MaterializeInc/materialize/pull/10803) (@dependabot[bot])
* [ ] [#10777 repr: switch Diff type from isize -> i64](https://github.com/MaterializeInc/materialize/pull/10777) (@petrosagg)
* [ ] [#10785 build(deps): bump askama from 0.11.0 to 0.11.1](https://github.com/MaterializeInc/materialize/pull/10785) (@dependabot[bot])
* [ ] [#10826 build(deps): bump console-subscriber from 0.1.2 to 0.1.3](https://github.com/MaterializeInc/materialize/pull/10826) (@dependabot[bot])
* [ ] [#10823 build(deps): bump tokio from 1.16.1 to 1.17.0](https://github.com/MaterializeInc/materialize/pull/10823) (@dependabot[bot])
* [ ] [#10825 build(deps): bump semver from 1.0.5 to 1.0.6](https://github.com/MaterializeInc/materialize/pull/10825) (@dependabot[bot])
* [ ] [#10678 doc/user: Merge all Kafka documentation pages into one + restructure the content](https://github.com/MaterializeInc/materialize/pull/10678) (@morsapaes)
* [ ] [#10722 ..= in query plans](https://github.com/MaterializeInc/materialize/pull/10722) (@umanwizard)
* [ ] [#10830 doc/user: Patch release notes after #10687](https://github.com/MaterializeInc/materialize/pull/10830) (@morsapaes)
* [ ] [#10813 expr,sql: add chr function](https://github.com/MaterializeInc/materialize/pull/10813) (@andrioni)
* [ ] [#10824 build(deps): bump digest from 0.10.2 to 0.10.3](https://github.com/MaterializeInc/materialize/pull/10824) (@dependabot[bot])
* [ ] [#10827 build(deps): bump tikv-jemallocator from 0.4.1 to 0.4.3](https://github.com/MaterializeInc/materialize/pull/10827) (@dependabot[bot])
* [ ] [#10836 Fix typo in JOIN doc](https://github.com/MaterializeInc/materialize/pull/10836) (@jseldess)
* [ ] [`886ad8d2e` dataflow/timestamp: reallow duplicate times in add_binding](https://github.com/MaterializeInc/materialize/commit/886ad8d2ea6a4f349f0520c1c50fc12727f36db8) (@umanwizard)
* [ ] [`de8349596` kafka: immediately cleanup metadata threads on drop](https://github.com/MaterializeInc/materialize/commit/de83495964a425894138019685d239504ccd2499) (@umanwizard)
* [ ] [`178d64a46` release: v0.21.0-rc2](https://github.com/MaterializeInc/materialize/commit/178d64a4682f4a3e6b18c1fff4c07243418313da) (@umanwizard)

**Comment by benesch** [comment]
@umanwizard's unreviewed commits LGTM.
