### ISSUE TITLE
release: v0.22.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#10985]
The following PRs in [`v0.22.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.22.0-rc1) require review:
* [ ] [#10936 antithesis: Update docker-compose.yml](https://github.com/MaterializeInc/materialize/pull/10936) (@philip-stoev)
* [ ] [#10862 .github: fix link to release note instructions in pull request template](https://github.com/MaterializeInc/materialize/pull/10862) (@benesch)
* [ ] [#10882 pgwire: add missing docstring to Config::frontegg](https://github.com/MaterializeInc/materialize/pull/10882) (@benesch)
* [ ] [#10794 Capability tracking in `Controller`](https://github.com/MaterializeInc/materialize/pull/10794) (@frankmcsherry)
* [ ] [#10887 Prepare 0.21.1 dev](https://github.com/MaterializeInc/materialize/pull/10887) (@umanwizard)
* [ ] [#10892 [kafka resumption] More emphatically kill toxiproxy between failure modes](https://github.com/MaterializeInc/materialize/pull/10892) (@cjubb39)
* [ ] [#10894 Revert "[kafka resumption] More emphatically kill toxiproxy between failure modes"](https://github.com/MaterializeInc/materialize/pull/10894) (@cjubb39)
* [ ] [#10895 Revert "[kafka sink] Retry message send failures"](https://github.com/MaterializeInc/materialize/pull/10895) (@cjubb39)
* [ ] [#10893 [kafka eos] [testdrive] verify-timestamp-compaction requires existence of timestamps](https://github.com/MaterializeInc/materialize/pull/10893) (@cjubb39)
* [ ] [#10898 Correct massive error in timestamp management](https://github.com/MaterializeInc/materialize/pull/10898) (@frankmcsherry)
* [ ] [#10905 *: miscellaneous crate naming + dependency improvements](https://github.com/MaterializeInc/materialize/pull/10905) (@benesch)
* [ ] [#10926 deps: bump to latest AWS SDK](https://github.com/MaterializeInc/materialize/pull/10926) (@benesch)
* [ ] [#10965 feature-benchmark: stabilize some Kafka scenarios](https://github.com/MaterializeInc/materialize/pull/10965) (@philip-stoev)
* [ ] [#10937 platform: Text about the Adapter layer](https://github.com/MaterializeInc/materialize/pull/10937) (@frankmcsherry)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`656c757fa` release: v0.22.0-rc1](https://github.com/MaterializeInc/materialize/commit/656c757fa181eac23d1811f80b8b7b4d0cd06992) (@petrosagg)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#10396 doc/platform: rename CONTROL to ADAPTER](https://github.com/MaterializeInc/materialize/pull/10396) (@benesch)
* [ ] [#10936 antithesis: Update docker-compose.yml](https://github.com/MaterializeInc/materialize/pull/10936) (@philip-stoev)
* [ ] [#10783 build(deps): bump hyper-openssl from 0.9.1 to 0.9.2](https://github.com/MaterializeInc/materialize/pull/10783) (@dependabot[bot])
* [ ] [#10829 sql: support int2vector](https://github.com/MaterializeInc/materialize/pull/10829) (@sploiselle)
* [ ] [#10838 doc/user: Cleaning up unused files after #10678](https://github.com/MaterializeInc/materialize/pull/10838) (@morsapaes)
* [ ] [#10680 doc/design: propose design for cluster SQL API](https://github.com/MaterializeInc/materialize/pull/10680) (@benesch)
* [ ] [#10845 kafka: immediately cleanup metadata threads on drop](https://github.com/MaterializeInc/materialize/pull/10845) (@petrosagg)
* [ ] [#10673 Move unrolling of peek multiplicities to coordinator.](https://github.com/MaterializeInc/materialize/pull/10673) (@umanwizard)
* [ ] [#10812 Dataflow ID](https://github.com/MaterializeInc/materialize/pull/10812) (@antiguru)
* [ ] [#10679 QGM: Lower outer join boxes](https://github.com/MaterializeInc/materialize/pull/10679) (@wangandi)
* [ ] [#10842 Unify 'drop' and 'compact to empty frontier'](https://github.com/MaterializeInc/materialize/pull/10842) (@frankmcsherry)
* [ ] [#10833 dataflow-types: make more types generic over `Timestamp`](https://github.com/MaterializeInc/materialize/pull/10833) (@mjibson)
* [ ] [#10766 make INCLUDE KEY AS compatible with 'bare' format USING CSR](https://github.com/MaterializeInc/materialize/pull/10766) (@guswynn)
* [ ] [#10846 update `rr` image to latest version with multi-arch support + fix rm paths](https://github.com/MaterializeInc/materialize/pull/10846) (@pH14)
* [ ] [#10850 dataflow/timestamp: reallow duplicate times in add_binding](https://github.com/MaterializeInc/materialize/pull/10850) (@ruchirK)
* [ ] [#10828 dataflow: switch `position` from an `Option<i64>` to an `i64` across the whole codebase](https://github.com/MaterializeInc/materialize/pull/10828) (@guswynn)
* [ ] [#10856 Bump Materialize CDC back to "Connect"](https://github.com/MaterializeInc/materialize/pull/10856) (@ruf-io)
* [ ] [#10851 qgm: Handle QGM ⇒ MIR lowering of global aggregates](https://github.com/MaterializeInc/materialize/pull/10851) (@aalexandrov)
* [ ] [#10858 persist: refactor set_{trace|unsealed}_batch to explicitly take a for…](https://github.com/MaterializeInc/materialize/pull/10858) (@ruchirK)
* [ ] [#10860 Expr/relation: Minor interface changes](https://github.com/MaterializeInc/materialize/pull/10860) (@wangandi)
* [ ] [#10772 repr: (re)introduce RowPacker](https://github.com/MaterializeInc/materialize/pull/10772) (@benesch)
* [ ] [#10449 expr,coord: standardize handling of nonpure functions](https://github.com/MaterializeInc/materialize/pull/10449) (@benesch)
* [ ] [#10834 Change process for writing release notes](https://github.com/MaterializeInc/materialize/pull/10834) (@benesch)
* [ ] [#10862 .github: fix link to release note instructions in pull request template](https://github.com/MaterializeInc/materialize/pull/10862) (@benesch)
* [ ] [#10864 test/aws-config: update for improved region handling in v0.7.0](https://github.com/MaterializeInc/materialize/pull/10864) (@benesch)
* [ ] [#10863 *: replace all usage of env_logger with tracing](https://github.com/MaterializeInc/materialize/pull/10863) (@benesch)
* [ ] [#10865 doc/user: incorporate new release notes for rc2](https://github.com/MaterializeInc/materialize/pull/10865) (@benesch)
* [ ] [#10808 mzcompose: pull "latest" images on override()](https://github.com/MaterializeInc/materialize/pull/10808) (@philip-stoev)
* [ ] [#10867 coord: allow +00:00 as a valid value for timezone](https://github.com/MaterializeInc/materialize/pull/10867) (@andrioni)
* [ ] [#10873 unreachable! requires a string literal](https://github.com/MaterializeInc/materialize/pull/10873) (@antiguru)
* [ ] [#10751 persist: allow TraceBatchMeta to hold multiple keys](https://github.com/MaterializeInc/materialize/pull/10751) (@ruchirK)
* [ ] [#10872 Clarify upgrade test README](https://github.com/MaterializeInc/materialize/pull/10872) (@jkosh44)
* [ ] [#10877 make newline linter catch multiple files](https://github.com/MaterializeInc/materialize/pull/10877) (@nharring-adjacent)
* [ ] [#10861 materialized: allow specifying the same flag multiple times](https://github.com/MaterializeInc/materialize/pull/10861) (@benesch)
* [ ] [#10881 test/kafka-matrix: restore full suite of kafka matrix tests](https://github.com/MaterializeInc/materialize/pull/10881) (@benesch)
* [ ] [#10882 pgwire: add missing docstring to Config::frontegg](https://github.com/MaterializeInc/materialize/pull/10882) (@benesch)
* [ ] [#10794 Capability tracking in `Controller`](https://github.com/MaterializeInc/materialize/pull/10794) (@frankmcsherry)
* [ ] [#10749 Store days separately in Intervals](https://github.com/MaterializeInc/materialize/pull/10749) (@jkosh44)
* [ ] [#10869 feat: support date/time unit aliases](https://github.com/MaterializeInc/materialize/pull/10869) (@sunisdown)
* [ ] [#10762 persist: push decode down into snapshot iteration to save allocs](https://github.com/MaterializeInc/materialize/pull/10762) (@danhhz)
* [ ] [#10887 Prepare 0.21.1 dev](https://github.com/MaterializeInc/materialize/pull/10887) (@umanwizard)
* [ ] [#10609 add basic shell completion to `bin/scratch`](https://github.com/MaterializeInc/materialize/pull/10609) (@pH14)
* [ ] [#10666 document some useful dev tools in the repo](https://github.com/MaterializeInc/materialize/pull/10666) (@pH14)
* [ ] [#10734 support named composite types](https://github.com/MaterializeInc/materialize/pull/10734) (@pH14)
* [ ] [#10853 [kafka sink] Retry message send failures](https://github.com/MaterializeInc/materialize/pull/10853) (@cjubb39)
* [ ] [#10892 [kafka resumption] More emphatically kill toxiproxy between failure modes](https://github.com/MaterializeInc/materialize/pull/10892) (@cjubb39)
* [ ] [#10894 Revert "[kafka resumption] More emphatically kill toxiproxy between failure modes"](https://github.com/MaterializeInc/materialize/pull/10894) (@cjubb39)
* [ ] [#10895 Revert "[kafka sink] Retry message send failures"](https://github.com/MaterializeInc/materialize/pull/10895) (@cjubb39)
* [ ] [#10893 [kafka eos] [testdrive] verify-timestamp-compaction requires existence of timestamps](https://github.com/MaterializeInc/materialize/pull/10893) (@cjubb39)
* [ ] [#10898 Correct massive error in timestamp management](https://github.com/MaterializeInc/materialize/pull/10898) (@frankmcsherry)
* [ ] [#10890 fix bug causing results buffer to be sorted repeatedly](https://github.com/MaterializeInc/materialize/pull/10890) (@umanwizard)
* [ ] [#10900 coord: fix merge skew](https://github.com/MaterializeInc/materialize/pull/10900) (@benesch)
* [ ] [#10902 Teach `Worker` to support multiple compute instances](https://github.com/MaterializeInc/materialize/pull/10902) (@frankmcsherry)
* [ ] [#10905 *: miscellaneous crate naming + dependency improvements](https://github.com/MaterializeInc/materialize/pull/10905) (@benesch)
* [ ] [#10904 dataflow: remove SQL name from SourceDesc](https://github.com/MaterializeInc/materialize/pull/10904) (@benesch)
* [ ] [#10899 expr,[pg]repr,sql: fix handling of OIDs](https://github.com/MaterializeInc/materialize/pull/10899) (@benesch)
* [ ] [#10907 repr: don't hardcode empty array and list rows](https://github.com/MaterializeInc/materialize/pull/10907) (@benesch)
* [ ] [#10912 dataflow-types: make some things generic](https://github.com/MaterializeInc/materialize/pull/10912) (@mjibson)
* [ ] [#10911 sql: make guess_best_common_type exactly match PostgreSQL](https://github.com/MaterializeInc/materialize/pull/10911) (@benesch)
* [ ] [#10910 Clarify source timestamping](https://github.com/MaterializeInc/materialize/pull/10910) (@frankmcsherry)
* [ ] [#10917 build(deps): bump rusqlite from 0.26.3 to 0.27.0](https://github.com/MaterializeInc/materialize/pull/10917) (@dependabot[bot])
* [ ] [#10920 build(deps): bump hmac from 0.12.0 to 0.12.1](https://github.com/MaterializeInc/materialize/pull/10920) (@dependabot[bot])
* [ ] [#10923 build(deps-dev): bump types-requests from 2.27.10 to 2.27.11 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10923) (@dependabot[bot])
* [ ] [#10924 build(deps-dev): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.21.3 to 1.21.8 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10924) (@dependabot[bot])
* [ ] [#10916 build(deps): bump rdkafka from `9594a34` to `cc45e9e`](https://github.com/MaterializeInc/materialize/pull/10916) (@dependabot[bot])
* [ ] [#10922 build(deps-dev): bump boto3 from 1.21.3 to 1.21.8 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/10922) (@dependabot[bot])
* [ ] [#10926 deps: bump to latest AWS SDK](https://github.com/MaterializeInc/materialize/pull/10926) (@benesch)
* [ ] [#10928 testdrive: temporarily disable EOS sink test](https://github.com/MaterializeInc/materialize/pull/10928) (@benesch)
* [ ] [#10925 build(deps): bump clap from 3.1.1 to 3.1.2](https://github.com/MaterializeInc/materialize/pull/10925) (@dependabot[bot])
* [ ] [#10933 build(deps): bump md-5 from 0.10.0 to 0.10.1](https://github.com/MaterializeInc/materialize/pull/10933) (@dependabot[bot])
* [ ] [#10932 build(deps): bump prost-reflect from 0.6.0 to 0.6.1](https://github.com/MaterializeInc/materialize/pull/10932) (@dependabot[bot])
* [ ] [#10929 build(deps): bump sysinfo from 0.23.2 to 0.23.4](https://github.com/MaterializeInc/materialize/pull/10929) (@dependabot[bot])
* [ ] [#10930 build(deps): bump askama_shared from 0.12.1 to 0.12.2](https://github.com/MaterializeInc/materialize/pull/10930) (@dependabot[bot])
* [ ] [#10931 build(deps): bump sha2 from 0.10.1 to 0.10.2](https://github.com/MaterializeInc/materialize/pull/10931) (@dependabot[bot])
* [ ] [#10914 doc/user: Merge all KDS documentation pages into one + restructure the content](https://github.com/MaterializeInc/materialize/pull/10914) (@morsapaes)
* [ ] [#10757 Introduce formalism.md document](https://github.com/MaterializeInc/materialize/pull/10757) (@frankmcsherry)
* [ ] [#10889 Continue 0.21.1 dev](https://github.com/MaterializeInc/materialize/pull/10889) (@umanwizard)
* [ ] [#10760 TCP boundary between STORAGE and COMPUTE](https://github.com/MaterializeInc/materialize/pull/10760) (@antiguru)
* [ ] [#10940 repr,expr,sql: rename ScalarType::{default_embedded_value => without_modifiers}](https://github.com/MaterializeInc/materialize/pull/10940) (@benesch)
* [ ] [#10941 coord: batch timestamp compactions in same transaction](https://github.com/MaterializeInc/materialize/pull/10941) (@benesch)
* [ ] [#10959 expr-test-util: Redo test to avoid hardcoding `Row`s.](https://github.com/MaterializeInc/materialize/pull/10959) (@wangandi)
* [ ] [#10885 Implement justify interval methods](https://github.com/MaterializeInc/materialize/pull/10885) (@jkosh44)
* [ ] [#10841 Add RAISE WARNING (NOTICE, INFO, etc) statement](https://github.com/MaterializeInc/materialize/pull/10841) (@andrioni)
* [ ] [#10942 [testdrive] Reenable non-flaky parts of kafka EOS](https://github.com/MaterializeInc/materialize/pull/10942) (@cjubb39)
* [ ] [#10947 doc/design: clarify cluster server/session variable plan](https://github.com/MaterializeInc/materialize/pull/10947) (@sploiselle)
* [ ] [#10946 Docs: `kafka_time_offset` is broken in Redpanda, not `start_offset`](https://github.com/MaterializeInc/materialize/pull/10946) (@ruf-io)
* [ ] [#10949 doc/user: Move metabase to "beta", remove forked driver reference](https://github.com/MaterializeInc/materialize/pull/10949) (@ruf-io)
* [ ] [#10948 doc/dev: add COST paper to required reading](https://github.com/MaterializeInc/materialize/pull/10948) (@benesch)
* [ ] [#10960 coord: make `version()` match `server_version` session var](https://github.com/MaterializeInc/materialize/pull/10960) (@benesch)
* [ ] [#10961 coord: clean up since_handles](https://github.com/MaterializeInc/materialize/pull/10961) (@benesch)
* [ ] [#10965 feature-benchmark: stabilize some Kafka scenarios](https://github.com/MaterializeInc/materialize/pull/10965) (@philip-stoev)
* [ ] [#10937 platform: Text about the Adapter layer](https://github.com/MaterializeInc/materialize/pull/10937) (@frankmcsherry)
* [ ] [#10964 expr: fix (modulo) division type inference](https://github.com/MaterializeInc/materialize/pull/10964) (@aalexandrov)
* [ ] [#10966 doc/user: Merge all S3 documentation pages into one + restructure the content](https://github.com/MaterializeInc/materialize/pull/10966) (@morsapaes)
* [ ] [#10970 coord: share PostgreSQL version number constants](https://github.com/MaterializeInc/materialize/pull/10970) (@benesch)
* [ ] [#10764 coord: improve timestamp determination to avoid no complete timestamps](https://github.com/MaterializeInc/materialize/pull/10764) (@mjibson)
* [ ] [#10979 Revert "coord: improve timestamp determination to avoid no complete timestamps"](https://github.com/MaterializeInc/materialize/pull/10979) (@mjibson)
* [ ] [#10983 pg-cdc: fix logic bug with COPY iterator](https://github.com/MaterializeInc/materialize/pull/10983) (@petrosagg)
* [ ] [#10982 Allow dataflow `Client` to error on `send`](https://github.com/MaterializeInc/materialize/pull/10982) (@frankmcsherry)
* [ ] [`656c757fa` release: v0.22.0-rc1](https://github.com/MaterializeInc/materialize/commit/656c757fa181eac23d1811f80b8b7b4d0cd06992) (@petrosagg)

**Comment by petrosagg** [comment]
everything lookds good

**Comment by benesch** [comment]
As does your unreviewed commit, @petrosagg!
