### ISSUE TITLE
[Epic] STORAGE: Explicit Reclocking information

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11218]
### Feature request

Our sources currently perform "informal reclocking" where internally they use `TimestampBinding` structures to record information about progress made through their sources. This information varies source-by-source, but roughly resembles a time-varying collection whose contents at each `time` describe: "what records have already been read from this source". The history of this collection describes the timestamps that were assigned to each record. Compacting this collection to a frontier removes our ability to determine precise historical timestamp information, but still allows us to determine the collection contents at that frontier, and receive precise timestamps for each uncompacted time thereafter.

Reclocking is valuable in that it lets us speak precisely about the contents of collections, and to accurately debug issues with implementation or specification when issues arise (which they have already). It is additionally a "product feature" in that we could bounce collections between timelines and allow users to specify their own reclocking (in effect, our former BYO). However, the main motivation for me, at least, is not the feature but the ability to speak clearly and correctly about the contents of our collections.

### What needs to be done for reclocking?

At the meta-level, we need structure put in place to compel reclocking information from sources. An example of this is https://github.com/MaterializeInc/materialize/pull/11192 which engages source purification as a moment to determine "initial bindings" even if none have yet been recorded, and stubs out locations for each of the sources to contribute their own. It is a good start, and we could use more of this to make it clear where specific source implementations are lacking.

* Each source type needs to specify a type (a "binding" in the current lingo) that can represent "records already read", for use in the time-varying collection. For some collections this is possibly a mess (e.g. Kinesis) and that is fine; they can become second-tier sources that cannot (easily) provide properties like linearizability, without explicit transcription to a more reliable source media. This type does not need to be a variant in one large `enum`, but it could be. That constraint exists at the moment because this information is shuttled between various layers, but ultimately we would like this information to be housed in STORAGE primarily, and shared with others under its terms.

* Each created source needs to be able to produce a time-varying collection of these bindings, even without instantiating the source. Ideally this would be a relatively cheap operation, like reading the existing parts in a Kafka topic and their maximum offsets. Our file sources at the moment use line number rather than file offset, which makes this substantially harder for them, and might require a rethinking of their offset type. It is possible there ends up not much distinction between source *creation* and source *instantiation*, in a world where source creation is tantamount to a single source instantiation for transcription into a common backing format. Nonetheless, it would be somewhat surprising to see fault-tolerant, available source implementations that do not first agree on these bindings.

* *Bonus*: each created source should *publish* their collection of bindings as a collection that can be observed and manipulated. This allows users to inspect the progress through their sources as of various query results they have received.

* Each source instantiation needs to take as input a source of these bindings. This can depend a bit based on the planned mechanism to produce further bindings (e.g. external to the source instance, or by the source instance and then durably recorded). But all source instantiations want to start with these bindings or an explicit statement from their instantiator that they are welcome to start from nothing (probably a bit of a smell). In a distributed implementation, it would be very surprising to see independent source instantiations both 1. mint their own bindings and 2. satisfy definiteness, but it seems plausible as long as there is only one instance of the source (e.g. in the STORAGE layer, as part of transcription to a time-based representation).

**Comment by nmeagan11** [comment]
## Product Spec

### Summary

Every source comes with its own notion of time and progress, which are not compatible with one another. With reclocking, we can maintain a uniform sense of time for all collections and sources, which allows us to speak correctly about the contents of collections at a point in time. This can also provide end users a simple way to calculate source/view lag, which currently is only available for Kafka (and is not user friendly).

### Use Cases

1. **Uniform Observability of Sources for Health Checks:** A frequent complaint from users is the lack of visibility into when their sources and views are “caught up” (i.e. not stale). Easy access to this information is necessary in order to determine if their instance is healthy. Though we can calculate this for Kafka today, the query is expensive. Reclocking will simplify this, and is required in order to expand to other sources. If this feature is built successfully, users should be able to run a simple query on our system tables for their health checks. Additionally, we will have the ability to easily expose this information in the Platform UI, should we choose to.
2. **BYO:** We used to have a feature called “BYO Timestamping”, which allowed users to provide a mapping between offsets and timestamps. This feature was specific to Kafka and (to my knowledge) not actually used by anyone. The feature as proposed here could allow users to specify their own reclocking for any source. However, this should not be a focus of the reclocking work, but rather either a by-product, or hardened by future work if we receive feature requests for it.
3. **Correctness:** As mentioned above, this feature will allow us to speak clearly and correctly about collections, and help debug implementations.

### Functional Spec

Suppose you have a Kafka source `foo` with a single topic which contains multiple partitions. For each record in `foo`, we would have an associated `partition_id` and `timestamp`, like the following:

![Reclocking-foo drawio](https://user-images.githubusercontent.com/19657850/161601977-f7d52a6f-6566-426c-8b71-7b5b740d3848.png)

The columns `partition_id` and `timestamp` are meta data on `foo` maintained in the backend, and would be hidden from the end user (but could be queried like [we have today](https://materialize.com/docs/sql/create-source/kafka/#partition-offset-timestamp)). Note that `partition_id` is specific to Kafka; this column would be different for other sources.

We would also maintain another table, `foo_timestamps`, which contains a mapping between the timestamp and that source’s corresponding notion of time (i.e. offset, LSN, etc.). The schema for this table depends on the source type. For Kafka, the schema includes the `partition_id`, `timestamp`, and `offset` columns. For Postgres, the schema includes the `timestamp`and `lsn` columns.

Further down the road, this may allow us to introduce a new system table, `mz_view_frontiers`, which would store the `view_id` and `timestamp`, for the purposes of observability on views.

### TODO

- [ ] Update the [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20210714_reclocking.md) to account for Platform designs and the above
- [ ] Create engineering tasks for both the MVP for this feature and future work
- [ ] Determine the structure of `x_timestamps`, where `x` is a source other than Kafka or Postgres (i.e. S3, Kinesis, etc.)

**Comment by benesch** [comment]
> We would also maintain another table, `foo_timestamps`, which contains a mapping between the timestamp and that source’s corresponding notion of time (i.e. offset, LSN, etc.). The schema for this table depends on the source type. For Kafka, the schema includes the `partition_id`, `timestamp`, and `offset` columns. For Postgres, the schema includes the `timestamp`and `lsn` columns.

👍🏽 

> Further down the road, this may allow us to introduce a new system table, mz_view_frontiers, which would store the view_id and timestamp, for the purposes of observability on views.

This already exists, by the way! It's just called [`mz_materialization_frontiers`](https://materialize.com/docs/sql/system-catalog/#mz_materialization_frontiers) and is keyed by index. (Index is the correct thing to key on, as a single view may be indexed in multiple clusters, and those views may be progressing at different rates; you can join against `mz_views` to get the frontier–view mapping if you need it.)

**Comment by nmeagan11** [comment]
> This already exists, by the way! It's just called [`mz_materialization_frontiers`](https://materialize.com/docs/sql/system-catalog/#mz_materialization_frontiers) and is keyed by index. (Index is the correct thing to key on, as a single view may be indexed in multiple clusters, and those views may be progressing at different rates; you can join against `mz_views` to get the frontier–view mapping if you need it.)

Ah, I was thinking that! I think it might be nice to not have to join, but it doesn't really matter so long that it's already in a place that cloud can easily present it in the UI (should they choose to).

**Comment by petrosagg** [comment]
* [ ] https://github.com/MaterializeInc/materialize/issues/11907
* [ ] https://github.com/MaterializeInc/materialize/issues/11908

**Comment by benesch** [comment]
I added #11899 to the task list above.

**Comment by benesch** [comment]
I added #12257 to the list too.

**Comment by cjubb39** [comment]
I added #12267 to the list (followup from addressing #11907)

**Comment by nmeagan11** [comment]
Can we close this? It looks like the outstanding engineering tasks are out of scope for M1 (cc @elindsey, @benesch).
