### ISSUE TITLE
release: v0.23.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#11264]
The following PRs in [`v0.23.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.23.0-rc1) require review:
* [x] [#11044 coord: remove builtin table indexes](https://github.com/MaterializeInc/materialize/pull/11044) (@benesch)
* [x] [#11069 coord: unify timestamp determination for peeks and tails](https://github.com/MaterializeInc/materialize/pull/11069) (@benesch)
* [x] [#11093 coord,sql: rename "default database" to "active database"](https://github.com/MaterializeInc/materialize/pull/11093) (@benesch)
* [x] [#11094 coord: remove a few more usages of DEFAULT_COMPUTE_INSTANCE_ID](https://github.com/MaterializeInc/materialize/pull/11094) (@benesch)
* [x] [#11095 feature benchmark: Add index to the Update scenario](https://github.com/MaterializeInc/materialize/pull/11095) (@philip-stoev)
* [x] [#11125 walkabout: remove hack](https://github.com/MaterializeInc/materialize/pull/11125) (@benesch)
* [x] [#11135 test: Tone down the Indexes scenario in the limits test](https://github.com/MaterializeInc/materialize/pull/11135) (@philip-stoev)
* [ ] [#11126 sql,coord: allow specifying the cluster of an index or sink](https://github.com/MaterializeInc/materialize/pull/11126) (@benesch)
* [x] [#11157 feature-benchmark: Stabilize the KafkaEnvelopeNoneBytes](https://github.com/MaterializeInc/materialize/pull/11157) (@philip-stoev)
* [x] [#11189 ore: absorb UnparkOnDrop thread handle from dataflow](https://github.com/MaterializeInc/materialize/pull/11189) (@benesch)
* [x] [#11191 sql: remove catalog from purification](https://github.com/MaterializeInc/materialize/pull/11191) (@benesch)
* [x] [#11210 deps: bump python dependencies](https://github.com/MaterializeInc/materialize/pull/11210) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`6bef52d0c` release: v0.23.0-rc1](https://github.com/MaterializeInc/materialize/commit/6bef52d0c7ef117f9e3324b2c5ddc47cc15de8a1) (@ruchirK)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#10974 expr: rename nullary functions to nonpure functions](https://github.com/MaterializeInc/materialize/pull/10974) (@benesch)
* [ ] [#11035 coord: declosureify Session::get_transaction_timestamp](https://github.com/MaterializeInc/materialize/pull/11035) (@benesch)
* [ ] [#11019 Gut frontiers from Coordinator](https://github.com/MaterializeInc/materialize/pull/11019) (@frankmcsherry)
* [ ] [#11036 Have STORAGE advance table definite frontiers on input advance](https://github.com/MaterializeInc/materialize/pull/11036) (@frankmcsherry)
* [ ] [#11037 coord: allow SELECTing from unmaterialized sources](https://github.com/MaterializeInc/materialize/pull/11037) (@benesch)
* [ ] [#11038 Clean up left over #11019 messes](https://github.com/MaterializeInc/materialize/pull/11038) (@frankmcsherry)
* [ ] [#10883 coord,dataflow: remove special cases for table indexes](https://github.com/MaterializeInc/materialize/pull/10883) (@benesch)
* [ ] [#11042 Further introduce coordinator to compute instances](https://github.com/MaterializeInc/materialize/pull/11042) (@frankmcsherry)
* [ ] [#11043 coord: introduce type to bundle storage and compute IDs](https://github.com/MaterializeInc/materialize/pull/11043) (@benesch)
* [ ] [#11045 coord: give logging indexes a unique ID per cluster](https://github.com/MaterializeInc/materialize/pull/11045) (@benesch)
* [ ] [#11044 coord: remove builtin table indexes](https://github.com/MaterializeInc/materialize/pull/11044) (@benesch)
* [ ] [#11047 coord: rename IdBundle to CollectionIdBundle](https://github.com/MaterializeInc/materialize/pull/11047) (@benesch)
* [ ] [#11049 testdrive: sleep a different way in fetch-select-during-ingest.td](https://github.com/MaterializeInc/materialize/pull/11049) (@benesch)
* [ ] [#11050 Allow table inputs to be dropped](https://github.com/MaterializeInc/materialize/pull/11050) (@frankmcsherry)
* [ ] [#11051 dataflow: hoist responsibilities out of import_table](https://github.com/MaterializeInc/materialize/pull/11051) (@benesch)
* [ ] [#11064 dataflow-types: automatically derive depends_on for dataflow exports](https://github.com/MaterializeInc/materialize/pull/11064) (@benesch)
* [ ] [#11046 Use Timeline struct to ensure write and read order](https://github.com/MaterializeInc/materialize/pull/11046) (@frankmcsherry)
* [ ] [#11052 build(deps): bump sysinfo from 0.23.4 to 0.23.5](https://github.com/MaterializeInc/materialize/pull/11052) (@dependabot[bot])
* [ ] [#11053 build(deps): bump termcolor from 1.1.2 to 1.1.3](https://github.com/MaterializeInc/materialize/pull/11053) (@dependabot[bot])
* [ ] [#11054 build(deps): bump clap from 3.1.2 to 3.1.5](https://github.com/MaterializeInc/materialize/pull/11054) (@dependabot[bot])
* [ ] [#11057 build(deps): bump rdkafka from `cc45e9e` to `221fb05`](https://github.com/MaterializeInc/materialize/pull/11057) (@dependabot[bot])
* [ ] [#11058 build(deps): bump ipnet from 2.3.1 to 2.4.0](https://github.com/MaterializeInc/materialize/pull/11058) (@dependabot[bot])
* [ ] [#11060 build(deps): bump ubuntu from focal-20220113 to focal-20220302 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11060) (@dependabot[bot])
* [ ] [#11061 build(deps-dev): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.21.8 to 1.21.13 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11061) (@dependabot[bot])
* [ ] [#11063 build(deps): bump pg8000 from 1.24.0 to 1.24.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11063) (@dependabot[bot])
* [ ] [#11065 build(deps): bump num_enum from 0.5.6 to 0.5.7](https://github.com/MaterializeInc/materialize/pull/11065) (@dependabot[bot])
* [ ] [#11059 build(deps): bump sysctl from 0.4.3 to 0.4.4](https://github.com/MaterializeInc/materialize/pull/11059) (@dependabot[bot])
* [ ] [#11062 build(deps-dev): bump boto3 from 1.21.8 to 1.21.13 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11062) (@dependabot[bot])
* [ ] [#10980 Support \d <object> meta command](https://github.com/MaterializeInc/materialize/pull/10980) (@jkosh44)
* [ ] [#11066 coord: remove dead code from the dataflow builder](https://github.com/MaterializeInc/materialize/pull/11066) (@benesch)
* [ ] [#11074 expr: make array_to_string handle empty arrays](https://github.com/MaterializeInc/materialize/pull/11074) (@andrioni)
* [ ] [#11068 dataflow-types: split out immutable controllers](https://github.com/MaterializeInc/materialize/pull/11068) (@benesch)
* [ ] [#10718 persist: chunk up a trace batch into multiple keys](https://github.com/MaterializeInc/materialize/pull/10718) (@ruchirK)
* [ ] [#11069 coord: unify timestamp determination for peeks and tails](https://github.com/MaterializeInc/materialize/pull/11069) (@benesch)
* [ ] [#11080 bump arrow2 for advisory RUSTSEC-2022-0012](https://github.com/MaterializeInc/materialize/pull/11080) (@umanwizard)
* [ ] [#11082 test/persistence: disable suddenly flaky part of compaction test](https://github.com/MaterializeInc/materialize/pull/11082) (@danhhz)
* [ ] [#10897 QGM: Add support for QGM error in QGM -> MIR lowering](https://github.com/MaterializeInc/materialize/pull/10897) (@wangandi)
* [ ] [#11067 Find collections using instance indentifiers](https://github.com/MaterializeInc/materialize/pull/11067) (@frankmcsherry)
* [ ] [#11079 dataflow: Only send frontier uppers for non-empty lists](https://github.com/MaterializeInc/materialize/pull/11079) (@antiguru)
* [ ] [#10951 Design document for incorporating Kafka message headers](https://github.com/MaterializeInc/materialize/pull/10951) (@guswynn)
* [ ] [#11022 doc/developer: add secrets design](https://github.com/MaterializeInc/materialize/pull/11022) (@benesch)
* [ ] [#11031 mzcloud-cli: Allow connecting to user/pass authenticated deployments](https://github.com/MaterializeInc/materialize/pull/11031) (@antifuchs)
* [ ] [#11077 coordd: Remove unused --workers](https://github.com/MaterializeInc/materialize/pull/11077) (@antiguru)
* [ ] [#10896 [kafka sink] Retry message send failures](https://github.com/MaterializeInc/materialize/pull/10896) (@cjubb39)
* [ ] [#11086 persist: simplify compaction test](https://github.com/MaterializeInc/materialize/pull/11086) (@ruchirK)
* [ ] [#11088 transform: introduce a trait for available indexes](https://github.com/MaterializeInc/materialize/pull/11088) (@benesch)
* [ ] [#11089 dataflow-types: validate IDs during allow_compaction](https://github.com/MaterializeInc/materialize/pull/11089) (@mjibson)
* [ ] [#11091 dataflow: make TableState generic over T](https://github.com/MaterializeInc/materialize/pull/11091) (@mjibson)
* [ ] [#11090 Add more than one index per collection](https://github.com/MaterializeInc/materialize/pull/11090) (@frankmcsherry)
* [ ] [#11092 coord: extract index oracle type](https://github.com/MaterializeInc/materialize/pull/11092) (@benesch)
* [ ] [#11093 coord,sql: rename "default database" to "active database"](https://github.com/MaterializeInc/materialize/pull/11093) (@benesch)
* [ ] [#11094 coord: remove a few more usages of DEFAULT_COMPUTE_INSTANCE_ID](https://github.com/MaterializeInc/materialize/pull/11094) (@benesch)
* [ ] [#11095 feature benchmark: Add index to the Update scenario](https://github.com/MaterializeInc/materialize/pull/11095) (@philip-stoev)
* [ ] [#10901 qgm: add type inference support ](https://github.com/MaterializeInc/materialize/pull/10901) (@aalexandrov)
* [ ] [#11098 pg-cdc: handle errors while reading from PG copy out stream](https://github.com/MaterializeInc/materialize/pull/11098) (@pH14)
* [ ] [#11110 coord: add+use ComputeInstanceId to indexes, sinks](https://github.com/MaterializeInc/materialize/pull/11110) (@sploiselle)
* [ ] [#11104 sql-parser: parse CREATE SECRET](https://github.com/MaterializeInc/materialize/pull/11104) (@mkysel)
* [ ] [#11108 sql-parser: add support for DROP SECRET](https://github.com/MaterializeInc/materialize/pull/11108) (@mkysel)
* [ ] [#11102 Render time redux](https://github.com/MaterializeInc/materialize/pull/11102) (@frankmcsherry)
* [ ] [#11106 sql: add `CREATE CLUSTER` and `DROP CLUSTER` statements](https://github.com/MaterializeInc/materialize/pull/11106) (@benesch)
* [ ] [#11008 dataflow: InstanceConfig to distinguish local/remote](https://github.com/MaterializeInc/materialize/pull/11008) (@antiguru)
* [ ] [#11113 materialized: refactor panic handling setup](https://github.com/MaterializeInc/materialize/pull/11113) (@benesch)
* [ ] [#11114 coord: simplify alter_index_enable](https://github.com/MaterializeInc/materialize/pull/11114) (@benesch)
* [ ] [#11118 persist: handle TODO around empty build version](https://github.com/MaterializeInc/materialize/pull/11118) (@ruchirK)
* [ ] [#11115 coord: introduce notion of CLUSTER, use it for indexes and sinks](https://github.com/MaterializeInc/materialize/pull/11115) (@sploiselle)
* [ ] [#11121 coord: add cluster session variable](https://github.com/MaterializeInc/materialize/pull/11121) (@benesch)
* [ ] [#11120 http-proxy: make hyper connector generic over inner connector](https://github.com/MaterializeInc/materialize/pull/11120) (@benesch)
* [ ] [#11119 [testdrive] Turn back on non-flaky EOS compaction checks](https://github.com/MaterializeInc/materialize/pull/11119) (@cjubb39)
* [ ] [#11122 Update `Timeline` naming to clash less, match others](https://github.com/MaterializeInc/materialize/pull/11122) (@frankmcsherry)
* [ ] [#11124 coord: install clusters in the catalog on CREATE](https://github.com/MaterializeInc/materialize/pull/11124) (@sploiselle)
* [ ] [#11125 walkabout: remove hack](https://github.com/MaterializeInc/materialize/pull/11125) (@benesch)
* [ ] [#11011 add support for intervals in date_trunc. fix #9871](https://github.com/MaterializeInc/materialize/pull/11011) (@lluki)
* [ ] [#11135 test: Tone down the Indexes scenario in the limits test](https://github.com/MaterializeInc/materialize/pull/11135) (@philip-stoev)
* [ ] [#11101 qgm: introduce `RequiredAttributes` type](https://github.com/MaterializeInc/materialize/pull/11101) (@aalexandrov)
* [ ] [#11141 pg-cdc: add timeouts to connection / copy out postgres calls](https://github.com/MaterializeInc/materialize/pull/11141) (@pH14)
* [ ] [#11126 sql,coord: allow specifying the cluster of an index or sink](https://github.com/MaterializeInc/materialize/pull/11126) (@benesch)
* [ ] [#11142 expr: fix nullability analysis for string_agg](https://github.com/MaterializeInc/materialize/pull/11142) (@andrioni)
* [ ] [#11107 Add opentelemetry-tracing support to materialized](https://github.com/MaterializeInc/materialize/pull/11107) (@guswynn)
* [ ] [#11112 sql-parser: fix alter index hint](https://github.com/MaterializeInc/materialize/pull/11112) (@mkysel)
* [ ] [#11140 sql-parser: support SHOW SECRETS](https://github.com/MaterializeInc/materialize/pull/11140) (@mkysel)
* [ ] [#11075 coord: add columns required for Superset compat](https://github.com/MaterializeInc/materialize/pull/11075) (@andrioni)
* [ ] [#11083 Create views from source refactor to use catalog data only](https://github.com/MaterializeInc/materialize/pull/11083) (@nharring-adjacent)
* [ ] [#11149 bump regex](https://github.com/MaterializeInc/materialize/pull/11149) (@umanwizard)
* [ ] [#11003 repr,pgrepr: add PostgreSQL "char" type](https://github.com/MaterializeInc/materialize/pull/11003) (@benesch)
* [ ] [#11153 scratch: Improve debugging of test failures in CI](https://github.com/MaterializeInc/materialize/pull/11153) (@philip-stoev)
* [ ] [#11154 Deduplicate imported indexes](https://github.com/MaterializeInc/materialize/pull/11154) (@frankmcsherry)
* [ ] [#11151 coord: support dropping clusters](https://github.com/MaterializeInc/materialize/pull/11151) (@sploiselle)
* [ ] [#11156 sql: support SHOW CLUSTERS](https://github.com/MaterializeInc/materialize/pull/11156) (@sploiselle)
* [ ] [#11157 feature-benchmark: Stabilize the KafkaEnvelopeNoneBytes](https://github.com/MaterializeInc/materialize/pull/11157) (@philip-stoev)
* [ ] [#11146 opentelemetry: setup timeout correctly](https://github.com/MaterializeInc/materialize/pull/11146) (@guswynn)
* [ ] [#11165 now config and coord cleanup](https://github.com/MaterializeInc/materialize/pull/11165) (@mjibson)
* [ ] [#11168 coord: make session and dataflow builder generic](https://github.com/MaterializeInc/materialize/pull/11168) (@mjibson)
* [ ] [#11169 dataflow-types: partition StorageCommand::Insert by hash of data](https://github.com/MaterializeInc/materialize/pull/11169) (@benesch)
* [ ] [#11173 feature-benchmark: Increase CI timeout to 3 hours](https://github.com/MaterializeInc/materialize/pull/11173) (@philip-stoev)
* [ ] [#11009 doc: Cloud static IP docs](https://github.com/MaterializeInc/materialize/pull/11009) (@bobbyiliev)
* [ ] [#11007 doc/user: Add PHP PDO guide](https://github.com/MaterializeInc/materialize/pull/11007) (@bobbyiliev)
* [ ] [#11180 pgwire: plumb full PeekResponseUnary to pgwire](https://github.com/MaterializeInc/materialize/pull/11180) (@mjibson)
* [ ] [#11184 doc/user: Make function names searchable in docs](https://github.com/MaterializeInc/materialize/pull/11184) (@ruf-io)
* [ ] [#10667 test/testdrive: add a smoke test verifying results from unmat sources…](https://github.com/MaterializeInc/materialize/pull/10667) (@ruchirK)
* [ ] [#11189 ore: absorb UnparkOnDrop thread handle from dataflow](https://github.com/MaterializeInc/materialize/pull/11189) (@benesch)
* [ ] [#11191 sql: remove catalog from purification](https://github.com/MaterializeInc/materialize/pull/11191) (@benesch)
* [ ] [#11203 build(deps): bump tracing from 0.1.31 to 0.1.32](https://github.com/MaterializeInc/materialize/pull/11203) (@dependabot[bot])
* [ ] [#11204 build(deps): bump timely from `4db679a` to `dd6187c`](https://github.com/MaterializeInc/materialize/pull/11204) (@dependabot[bot])
* [ ] [#11205 build(deps): bump differential-dataflow from `f862b65` to `27492f2`](https://github.com/MaterializeInc/materialize/pull/11205) (@dependabot[bot])
* [ ] [#11207 build(deps): bump clap from 3.1.5 to 3.1.6](https://github.com/MaterializeInc/materialize/pull/11207) (@dependabot[bot])
* [ ] [#11209 build(deps): bump dogsdogsdogs from `f862b65` to `27492f2`](https://github.com/MaterializeInc/materialize/pull/11209) (@dependabot[bot])
* [ ] [#11210 deps: bump python dependencies](https://github.com/MaterializeInc/materialize/pull/11210) (@benesch)
* [ ] [#11211 build(deps): bump pprof from 0.6.2 to 0.7.0](https://github.com/MaterializeInc/materialize/pull/11211) (@dependabot[bot])
* [ ] [#11187 coord: add EXPLAIN TIMESTAMP](https://github.com/MaterializeInc/materialize/pull/11187) (@mjibson)
* [ ] [#11212 build(deps): bump syn from 1.0.86 to 1.0.87](https://github.com/MaterializeInc/materialize/pull/11212) (@dependabot[bot])
* [ ] [#11217 build(deps): bump libc from 0.2.119 to 0.2.120](https://github.com/MaterializeInc/materialize/pull/11217) (@dependabot[bot])
* [ ] [#11182 Modify planner to work with augmented statements](https://github.com/MaterializeInc/materialize/pull/11182) (@jkosh44)
* [ ] [#11190 sql+coord: propagate index, sink relationship to clusters to system tables](https://github.com/MaterializeInc/materialize/pull/11190) (@sploiselle)
* [ ] [#11221 Match uid regex in testdrive rename testcase](https://github.com/MaterializeInc/materialize/pull/11221) (@nharring-adjacent)
* [ ] [#10962 doc/user: Revamp Third-Party Tools Page](https://github.com/MaterializeInc/materialize/pull/10962) (@ruf-io)
* [ ] [#11224 Temporarily disable problematic unmaterialized source test](https://github.com/MaterializeInc/materialize/pull/11224) (@guswynn)
* [ ] [#11163 coord: make the TimestampOracle generic](https://github.com/MaterializeInc/materialize/pull/11163) (@mjibson)
* [ ] [#11220 qgm: reorganize hir module structure](https://github.com/MaterializeInc/materialize/pull/11220) (@aalexandrov)
* [ ] [#11171 transform: rewrite single row FlatMap to Map](https://github.com/MaterializeInc/materialize/pull/11171) (@lluki)
* [ ] [#11235 build(deps): bump reqwest from 0.11.9 to 0.11.10](https://github.com/MaterializeInc/materialize/pull/11235) (@dependabot[bot])
* [ ] [#11236 build(deps): bump syn from 1.0.87 to 1.0.88](https://github.com/MaterializeInc/materialize/pull/11236) (@dependabot[bot])
* [ ] [#11237 build(deps): bump crossbeam-channel from 0.5.2 to 0.5.3](https://github.com/MaterializeInc/materialize/pull/11237) (@dependabot[bot])
* [ ] [#11144 sql-parser: add support for ALTER SECRET](https://github.com/MaterializeInc/materialize/pull/11144) (@mkysel)
* [ ] [#11241 tests: fix merge skew between SHOW SECRETS and SHOW...IN CLUSTER](https://github.com/MaterializeInc/materialize/pull/11241) (@sploiselle)
* [ ] [#11159 Add test for create views from source after an alter table](https://github.com/MaterializeInc/materialize/pull/11159) (@nharring-adjacent)
* [ ] [#11233 Change default listen_addr to localhost](https://github.com/MaterializeInc/materialize/pull/11233) (@andrioni)
* [ ] [#11244 coord: disable SELECTing from non-table unmaterialized sources](https://github.com/MaterializeInc/materialize/pull/11244) (@benesch)
* [ ] [`6bef52d0c` release: v0.23.0-rc1](https://github.com/MaterializeInc/materialize/commit/6bef52d0c7ef117f9e3324b2c5ddc47cc15de8a1) (@ruchirK)

**Comment by benesch** [comment]
#11126 is my change, so we need @sploiselle to sign off!

**Comment by sploiselle** [comment]
https://github.com/MaterializeInc/materialize/pull/11126 LGTM

**Comment by materializer** [comment]
LGTM
