### ISSUE TITLE
release: v0.24.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#11360]
The following PRs in [`v0.24.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.24.0-rc1) require review:
* [ ] [#11248 testdrive: various improvements](https://github.com/MaterializeInc/materialize/pull/11248) (@benesch)
* [ ] [#11265 Prepare 0.23.1 dev](https://github.com/MaterializeInc/materialize/pull/11265) (@ruchirK)
* [ ] [#11291 antithesis: Update the Antithesis container to new realities](https://github.com/MaterializeInc/materialize/pull/11291) (@philip-stoev)
* [ ] [#11329 coordtest: remove](https://github.com/MaterializeInc/materialize/pull/11329) (@benesch)
* [ ] [#11333 feature-benchmark: Tone down the StartupLoaded scenario](https://github.com/MaterializeInc/materialize/pull/11333) (@philip-stoev)
* [ ] [#11342 feature-benchmark: fortify the UpdateMultiNoIndex scenario](https://github.com/MaterializeInc/materialize/pull/11342) (@philip-stoev)
* [ ] [#11354 deps: get back on mainline rust_mysql and autotools](https://github.com/MaterializeInc/materialize/pull/11354) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`d26f477cd` release: v0.24.0-rc1](https://github.com/MaterializeInc/materialize/commit/d26f477cdb7edc807a9928e31faf8aec2b1a5431) (@petrosagg)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#11248 testdrive: various improvements](https://github.com/MaterializeInc/materialize/pull/11248) (@benesch)
* [ ] [#11228 qgm: add `Union` support to `FromHir`](https://github.com/MaterializeInc/materialize/pull/11228) (@aalexandrov)
* [ ] [#11245 Modify SCL planning to use augmented statements](https://github.com/MaterializeInc/materialize/pull/11245) (@jkosh44)
* [ ] [#10978 persist: skeleton of new multi-writer persist interface](https://github.com/MaterializeInc/materialize/pull/10978) (@danhhz)
* [ ] [#11256 Restore timely config to `materialized`](https://github.com/MaterializeInc/materialize/pull/11256) (@frankmcsherry)
* [ ] [#11260 coord: run coordd in experimental mode](https://github.com/MaterializeInc/materialize/pull/11260) (@sploiselle)
* [ ] [#11251 coord: warn not crash on unknown peek response](https://github.com/MaterializeInc/materialize/pull/11251) (@antiguru)
* [ ] [#11265 Prepare 0.23.1 dev](https://github.com/MaterializeInc/materialize/pull/11265) (@ruchirK)
* [ ] [#11148 Add prometheus metric for per partition high watermark](https://github.com/MaterializeInc/materialize/pull/11148) (@nharring-adjacent)
* [ ] [#11263 dbt-materialize: error on incremental materialization](https://github.com/MaterializeInc/materialize/pull/11263) (@ahelium)
* [ ] [#11272 build(deps): bump syn from 1.0.88 to 1.0.89](https://github.com/MaterializeInc/materialize/pull/11272) (@dependabot[bot])
* [ ] [#11249 Reaffirm values of correctness for platform](https://github.com/MaterializeInc/materialize/pull/11249) (@frankmcsherry)
* [ ] [#11274 doc/developer: add blog post on distributed locking](https://github.com/MaterializeInc/materialize/pull/11274) (@benesch)
* [ ] [#11253 expr: add unique key information to `TableFunc::output_type()`](https://github.com/MaterializeInc/materialize/pull/11253) (@aalexandrov)
* [ ] [#11267 Change cloud sign up link](https://github.com/MaterializeInc/materialize/pull/11267) (@ruf-io)
* [ ] [#11273 feature-benchmark: Add scenario for measuring startup performance](https://github.com/MaterializeInc/materialize/pull/11273) (@philip-stoev)
* [ ] [#11279 bump openssl](https://github.com/MaterializeInc/materialize/pull/11279) (@umanwizard)
* [ ] [#11252 qgm: add `CallTable` support to `FromHir`](https://github.com/MaterializeInc/materialize/pull/11252) (@aalexandrov)
* [ ] [#11269 docs: fix reference to resolve_names](https://github.com/MaterializeInc/materialize/pull/11269) (@guswynn)
* [ ] [#11286 doc/user: compile release notes for v0.23](https://github.com/MaterializeInc/materialize/pull/11286) (@benesch)
* [ ] [#11291 antithesis: Update the Antithesis container to new realities](https://github.com/MaterializeInc/materialize/pull/11291) (@philip-stoev)
* [ ] [#11289 dataflow: Better error log for SplitClient](https://github.com/MaterializeInc/materialize/pull/11289) (@antiguru)
* [ ] [#11290 timely-util: remove Max1Antichain](https://github.com/MaterializeInc/materialize/pull/11290) (@benesch)
* [ ] [#11287 coord: Drop instance drops client](https://github.com/MaterializeInc/materialize/pull/11287) (@antiguru)
* [ ] [#11301 Continue 0.23.1 dev](https://github.com/MaterializeInc/materialize/pull/11301) (@ruchirK)
* [ ] [#11299 doc/user: Improve icons on supported tools page](https://github.com/MaterializeInc/materialize/pull/11299) (@ruf-io)
* [ ] [#11303 coord: verify portals](https://github.com/MaterializeInc/materialize/pull/11303) (@mjibson)
* [ ] [#11305 doc/user: Add "click to copy" on docs codeblocks](https://github.com/MaterializeInc/materialize/pull/11305) (@ruf-io)
* [ ] [#11315 doc/user: make COPY button consistent with docs style](https://github.com/MaterializeInc/materialize/pull/11315) (@morsapaes)
* [ ] [#11316 doc/user: Add header tags to enable rich snippets for docs links](https://github.com/MaterializeInc/materialize/pull/11316) (@ruf-io)
* [ ] [#11317 dataflow-types: avoid unsafe stream generation](https://github.com/MaterializeInc/materialize/pull/11317) (@benesch)
* [ ] [#11319 build(deps): bump ubuntu from focal-20220302 to focal-20220316 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11319) (@dependabot[bot])
* [ ] [#11322 build(deps-dev): bump mypy from 0.940 to 0.941 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11322) (@dependabot[bot])
* [ ] [#11323 build(deps-dev): bump boto3 from 1.21.18 to 1.21.22 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11323) (@dependabot[bot])
* [ ] [#11325 build(deps): bump setuptools from 60.9.3 to 60.10.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11325) (@dependabot[bot])
* [ ] [#11326 build(deps-dev): bump types-setuptools from 57.4.10 to 57.4.11 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11326) (@dependabot[bot])
* [ ] [#11327 build(deps-dev): bump types-pymysql from 1.0.13 to 1.0.14 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11327) (@dependabot[bot])
* [ ] [#11328 build(deps-dev): bump pytest from 7.1.0 to 7.1.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11328) (@dependabot[bot])
* [ ] [#11329 coordtest: remove](https://github.com/MaterializeInc/materialize/pull/11329) (@benesch)
* [ ] [#11324 build(deps-dev): bump types-pyyaml from 6.0.4 to 6.0.5 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11324) (@dependabot[bot])
* [ ] [#11321 build(deps-dev): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.21.18 to 1.21.22 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11321) (@dependabot[bot])
* [ ] [#11309 Restartable sources groundwork](https://github.com/MaterializeInc/materialize/pull/11309) (@frankmcsherry)
* [ ] [#11320 build(deps-dev): bump types-requests from 2.27.12 to 2.27.14 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11320) (@dependabot[bot])
* [ ] [#11318 materialized: absorb coordd](https://github.com/MaterializeInc/materialize/pull/11318) (@benesch)
* [ ] [#11331 doc/user: use long form for `materialized` commands](https://github.com/MaterializeInc/materialize/pull/11331) (@morsapaes)
* [ ] [#11333 feature-benchmark: Tone down the StartupLoaded scenario](https://github.com/MaterializeInc/materialize/pull/11333) (@philip-stoev)
* [ ] [#11311 coord: initialize table since to the timeline write ts, not 0](https://github.com/MaterializeInc/materialize/pull/11311) (@mjibson)
* [ ] [#11336 Allow `GenericClient::recv` to produce errors; reset TCP connections](https://github.com/MaterializeInc/materialize/pull/11336) (@frankmcsherry)
* [ ] [#11338 coord,sql: untangle cluster logging](https://github.com/MaterializeInc/materialize/pull/11338) (@benesch)
* [ ] [#11340 Hold compaction for peeks](https://github.com/MaterializeInc/materialize/pull/11340) (@frankmcsherry)
* [ ] [#11234 doc: Add Azure and DO postgres](https://github.com/MaterializeInc/materialize/pull/11234) (@bobbyiliev)
* [ ] [#11342 feature-benchmark: fortify the UpdateMultiNoIndex scenario](https://github.com/MaterializeInc/materialize/pull/11342) (@philip-stoev)
* [ ] [#11292 sql: limit `pg_catalog` views to the current database](https://github.com/MaterializeInc/materialize/pull/11292) (@necaris)
* [ ] [#11348 Add OS and arch to telemetry data](https://github.com/MaterializeInc/materialize/pull/11348) (@andrioni)
* [ ] [#11350 materialized: disable persistent system tables test by default](https://github.com/MaterializeInc/materialize/pull/11350) (@danhhz)
* [ ] [#11351 mock_telemetry_server: fix bug in cert generation](https://github.com/MaterializeInc/materialize/pull/11351) (@benesch)
* [ ] [#11143 debugging: add hidden flag to print tracing log level](https://github.com/MaterializeInc/materialize/pull/11143) (@guswynn)
* [ ] [#11354 deps: get back on mainline rust_mysql and autotools](https://github.com/MaterializeInc/materialize/pull/11354) (@benesch)
* [ ] [`d26f477cd` release: v0.24.0-rc1](https://github.com/MaterializeInc/materialize/commit/d26f477cdb7edc807a9928e31faf8aec2b1a5431) (@petrosagg)
