### ISSUE TITLE
release: v0.25.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#11479]
The following PRs in [`v0.25.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.25.0-rc1) require review:
* [x] [#11358 Prepare 0.24.1 dev](https://github.com/MaterializeInc/materialize/pull/11358) (@petrosagg)
* [x] [#11282 doc/user: another example about how to use date_trunc to create windo…](https://github.com/MaterializeInc/materialize/pull/11282) (@joacoc)
* [x] [#11382 Update released versions to include v0.24.0](https://github.com/MaterializeInc/materialize/pull/11382) (@petrosagg)
* [x] [#11385 Attempt to simplify TAIL responses](https://github.com/MaterializeInc/materialize/pull/11385) (@frankmcsherry)
* [x] [#11391 cluster: nerf the cluster smoke test](https://github.com/MaterializeInc/materialize/pull/11391) (@philip-stoev)
* [x] [#11398 revert "ore: introduce a canceling retry_async variant"](https://github.com/MaterializeInc/materialize/pull/11398) (@philip-stoev)
* [x] [#11415 deps: upgrade to AWS SDK v0.9.0](https://github.com/MaterializeInc/materialize/pull/11415) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`a2d6c100b` release: v0.25.0-rc1](https://github.com/MaterializeInc/materialize/commit/a2d6c100b5d968e3169ed810960eb3a80f10aa68) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#11177 ore: introduce a canceling retry_async variant](https://github.com/MaterializeInc/materialize/pull/11177) (@benesch)
* [ ] [#11335 Restartable, replicated client](https://github.com/MaterializeInc/materialize/pull/11335) (@frankmcsherry)
* [ ] [#11358 Prepare 0.24.1 dev](https://github.com/MaterializeInc/materialize/pull/11358) (@petrosagg)
* [ ] [#11162 consolidate the type of the current_values map in upsert_core](https://github.com/MaterializeInc/materialize/pull/11162) (@guswynn)
* [ ] [#11347 sql, coord: create secret](https://github.com/MaterializeInc/materialize/pull/11347) (@mkysel)
* [ ] [#11352 Fix panic on over-qualified names](https://github.com/MaterializeInc/materialize/pull/11352) (@jkosh44)
* [ ] [#11363 add --redpanda to persistence tests](https://github.com/MaterializeInc/materialize/pull/11363) (@guswynn)
* [ ] [#11174 doc/user: add golang guide](https://github.com/MaterializeInc/materialize/pull/11174) (@ahelium)
* [ ] [#11367 doc/user: Update golang row on integrations page](https://github.com/MaterializeInc/materialize/pull/11367) (@ruf-io)
* [ ] [#11370 expr: decode numeral values in base64](https://github.com/MaterializeInc/materialize/pull/11370) (@sploiselle)
* [ ] [#11339 orchestrator: capture initial sketch](https://github.com/MaterializeInc/materialize/pull/11339) (@benesch)
* [ ] [#11372 doc/user: add release notes for v0.24.0](https://github.com/MaterializeInc/materialize/pull/11372) (@benesch)
* [ ] [#11364 doc: add CrunchyBridge to supported tools](https://github.com/MaterializeInc/materialize/pull/11364) (@bobbyiliev)
* [ ] [#10649 build(deps): bump tokio-util from 0.6.9 to 0.7.0](https://github.com/MaterializeInc/materialize/pull/10649) (@dependabot[bot])
* [ ] [#11395 set the default service name](https://github.com/MaterializeInc/materialize/pull/11395) (@edude03)
* [ ] [#11282 doc/user: another example about how to use date_trunc to create windo…](https://github.com/MaterializeInc/materialize/pull/11282) (@joacoc)
* [ ] [#11152 Update pg source docs](https://github.com/MaterializeInc/materialize/pull/11152) (@nharring-adjacent)
* [ ] [#11380 Start TcpClient in disconnected state; connect for storage clients](https://github.com/MaterializeInc/materialize/pull/11380) (@frankmcsherry)
* [ ] [#11383 dataflow: retry storage-compute boundary connections](https://github.com/MaterializeInc/materialize/pull/11383) (@benesch)
* [ ] [#11382 Update released versions to include v0.24.0](https://github.com/MaterializeInc/materialize/pull/11382) (@petrosagg)
* [ ] [#11243 QGM => HIR](https://github.com/MaterializeInc/materialize/pull/11243) (@wangandi)
* [ ] [#11384 Squash various bugs in managed clusters](https://github.com/MaterializeInc/materialize/pull/11384) (@benesch)
* [ ] [#11385 Attempt to simplify TAIL responses](https://github.com/MaterializeInc/materialize/pull/11385) (@frankmcsherry)
* [ ] [#11391 cluster: nerf the cluster smoke test](https://github.com/MaterializeInc/materialize/pull/11391) (@philip-stoev)
* [ ] [#11386 sql: simplify typeconv::get_cast](https://github.com/MaterializeInc/materialize/pull/11386) (@sploiselle)
* [ ] [#11389 Support tail in the replicated client](https://github.com/MaterializeInc/materialize/pull/11389) (@frankmcsherry)
* [ ] [#11394 Tcp boundary reliability](https://github.com/MaterializeInc/materialize/pull/11394) (@antiguru)
* [ ] [#11398 revert "ore: introduce a canceling retry_async variant"](https://github.com/MaterializeInc/materialize/pull/11398) (@philip-stoev)
* [ ] [#11396 Allow replica removal by name](https://github.com/MaterializeInc/materialize/pull/11396) (@frankmcsherry)
* [ ] [#11268 doc/user: literals/exp filtering](https://github.com/MaterializeInc/materialize/pull/11268) (@joacoc)
* [ ] [#11392 sql: remove CastInPlace](https://github.com/MaterializeInc/materialize/pull/11392) (@sploiselle)
* [ ] [#11403 Surface replica manipulation operations on compute instance controller](https://github.com/MaterializeInc/materialize/pull/11403) (@frankmcsherry)
* [ ] [#11404 sql,coord: beginnings of ALTER CLUSTER](https://github.com/MaterializeInc/materialize/pull/11404) (@benesch)
* [ ] [#11405 dataflow-types: make TcpClient::recv cancellation safe](https://github.com/MaterializeInc/materialize/pull/11405) (@benesch)
* [ ] [#11407 dataflow-types: teach PartitionedClient to absorb errors](https://github.com/MaterializeInc/materialize/pull/11407) (@benesch)
* [ ] [#11408 build(deps): bump quote from 1.0.14 to 1.0.17](https://github.com/MaterializeInc/materialize/pull/11408) (@dependabot[bot])
* [ ] [#11409 build(deps): bump setuptools from 60.10.0 to 61.2.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11409) (@dependabot[bot])
* [ ] [#11411 build(deps-dev): bump mypy from 0.941 to 0.942 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11411) (@dependabot[bot])
* [ ] [#11412 build(deps-dev): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.21.22 to 1.21.27 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11412) (@dependabot[bot])
* [ ] [#11413 build(deps-dev): bump types-requests from 2.27.14 to 2.27.15 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11413) (@dependabot[bot])
* [ ] [#11410 build(deps-dev): bump boto3 from 1.21.22 to 1.21.27 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/11410) (@dependabot[bot])
* [ ] [#11330 build(deps): bump dbt-postgres from 1.0.3 to 1.0.4 in /misc/dbt-materialize](https://github.com/MaterializeInc/materialize/pull/11330) (@dependabot[bot])
* [ ] [#11414 build(deps): bump time from 0.3.7 to 0.3.9](https://github.com/MaterializeInc/materialize/pull/11414) (@dependabot[bot])
* [ ] [#11415 deps: upgrade to AWS SDK v0.9.0](https://github.com/MaterializeInc/materialize/pull/11415) (@benesch)
* [ ] [#11416 build(deps): bump zip from 0.5.13 to 0.6.0](https://github.com/MaterializeInc/materialize/pull/11416) (@dependabot[bot])
* [ ] [#11419 build(deps): bump ctor from 0.1.21 to 0.1.22](https://github.com/MaterializeInc/materialize/pull/11419) (@dependabot[bot])
* [ ] [#11418 build(deps): bump native-tls from 0.2.8 to 0.2.9](https://github.com/MaterializeInc/materialize/pull/11418) (@dependabot[bot])
* [ ] [#11425 Reenable testdrive retry cancelation timeout](https://github.com/MaterializeInc/materialize/pull/11425) (@philip-stoev)
* [ ] [#11432 build(deps): bump libc from 0.2.120 to 0.2.121](https://github.com/MaterializeInc/materialize/pull/11432) (@dependabot[bot])
* [ ] [#11420 build(deps): bump hyper from 0.14.17 to 0.14.18](https://github.com/MaterializeInc/materialize/pull/11420) (@dependabot[bot])
* [ ] [#11421 build(deps): bump paste from 1.0.6 to 1.0.7](https://github.com/MaterializeInc/materialize/pull/11421) (@dependabot[bot])
* [ ] [#11424 build(deps): bump semver from 1.0.6 to 1.0.7](https://github.com/MaterializeInc/materialize/pull/11424) (@dependabot[bot])
* [ ] [#11433 build(deps): bump tokio-util from 0.7.0 to 0.7.1](https://github.com/MaterializeInc/materialize/pull/11433) (@dependabot[bot])
* [ ] [#11365 persist: flesh out an in-mem placeholder implementation of the API](https://github.com/MaterializeInc/materialize/pull/11365) (@danhhz)
* [ ] [#11436 partitioned client: Partition state by instance](https://github.com/MaterializeInc/materialize/pull/11436) (@antiguru)
* [ ] [#11440 build(deps): bump native-tls from 0.2.9 to 0.2.10](https://github.com/MaterializeInc/materialize/pull/11440) (@dependabot[bot])
* [ ] [#11441 build(deps): bump crossbeam-channel from 0.5.3 to 0.5.4](https://github.com/MaterializeInc/materialize/pull/11441) (@dependabot[bot])
* [ ] [#11423 build(deps): bump log from 0.4.14 to 0.4.16](https://github.com/MaterializeInc/materialize/pull/11423) (@dependabot[bot])
* [ ] [#11442 build(deps): bump syn from 1.0.89 to 1.0.90](https://github.com/MaterializeInc/materialize/pull/11442) (@dependabot[bot])
* [ ] [#11449 materialized: exclude SIGPIPE from termination signal handling](https://github.com/MaterializeInc/materialize/pull/11449) (@benesch)
* [ ] [#11362 coord, sql: partial support for DROP SECRET and ALTER SECRET .. RENAME TO ..](https://github.com/MaterializeInc/materialize/pull/11362) (@mkysel)
* [ ] [#11452 build(deps): bump async-trait from 0.1.52 to 0.1.53](https://github.com/MaterializeInc/materialize/pull/11452) (@dependabot[bot])
* [ ] [#11451 Correct sink logging](https://github.com/MaterializeInc/materialize/pull/11451) (@frankmcsherry)
* [ ] [#11438 persist: initial Consensus trait definition + in-mem implementation](https://github.com/MaterializeInc/materialize/pull/11438) (@ruchirK)
* [ ] [#11456 formalism: rename UpdateAndDowngrade to Append](https://github.com/MaterializeInc/materialize/pull/11456) (@danhhz)
* [ ] [#11313 Modify planner/catalog to use database/schema ids](https://github.com/MaterializeInc/materialize/pull/11313) (@jkosh44)
* [ ] [#11457 doc/user: patch JSON examples for Kafka and Kinesis sources](https://github.com/MaterializeInc/materialize/pull/11457) (@morsapaes)
* [ ] [#11458 Organize dataflow exports as BTreeMaps](https://github.com/MaterializeInc/materialize/pull/11458) (@frankmcsherry)
* [ ] [#11462 build(deps): bump sysinfo from 0.23.5 to 0.23.6](https://github.com/MaterializeInc/materialize/pull/11462) (@dependabot[bot])
* [ ] [`a2d6c100b` release: v0.25.0-rc1](https://github.com/MaterializeInc/materialize/commit/a2d6c100b5d968e3169ed810960eb3a80f10aa68) (@umanwizard)

**Comment by umanwizard** [comment]
@benesch please stamp mine

**Comment by benesch** [comment]
LGTM.
