### ISSUE TITLE
[Epic] Kafka Sinks (with EOS) for Platform

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11503]
### Initiative and Theme

Materialize is Flexible; Materialize makes it easy to build new applications
Materialize is Friendly; Materialize makes it easy to add downstream data sinks

### Problem

In order to power many of our use cases, users must be able to stream data out of Materialize in a form that can be consumed by a downstream service (in this case, Kafka). This epic is for the implementation of #11501 for Kafka.

### Success Criteria

A user can create a sink in Platform from Materialize into Kafka with at least the same functionality and performance as previously.

### Time Horizon

XLarge

### Tasks

- [x] Remove Kafka sink from compute
- [x] [Move Kafka sinks out of un-safe mode](https://github.com/MaterializeInc/materialize/pull/14600)
- [x] https://github.com/MaterializeInc/materialize/issues/11216 (nice to have)
- [x] https://github.com/MaterializeInc/materialize/issues/8411 (confirm if still relevant?)
- [x] https://github.com/MaterializeInc/materialize/issues/14200
- [x] https://github.com/MaterializeInc/materialize/issues/14202
- [x] https://github.com/MaterializeInc/materialize/issues/14203
- [x] https://github.com/MaterializeInc/materialize/issues/14220
- [x] https://github.com/MaterializeInc/materialize/issues/14221
- [x] https://github.com/MaterializeInc/materialize/issues/14267
- [x] https://github.com/MaterializeInc/materialize/issues/14372
- [x] https://github.com/MaterializeInc/materialize/issues/13782
- [x] https://github.com/MaterializeInc/materialize/issues/14488
- [x] https://github.com/MaterializeInc/materialize/issues/14659
- [x] https://github.com/MaterializeInc/materialize/issues/14957

### Testing

- [x] Make sure sinks are present in the Zippy, Feature Benchmark, and Platform Checks frameworks
- [x] Make sure sinks are tested in multi-replica scenarios
- [x] Test behavior upon message broker restart (draft pr - #14097)
- [ ] Check that Postgres sources work with Kafka sinks

### Bugs

- [x] #14098
- [x] #11334
- [x] #8573
- [x] #14728
- [x] #14825

### Blockers

- [x] #11501

**Comment by nmeagan11** [comment]
There are a variety of historical sink bugs. We may not want to address them now (or they may not be relevant anymore), but I wanted to list them here in a single location to at least triage as part of the epic:

- [ ] https://github.com/MaterializeInc/materialize/issues/10876
- [ ] https://github.com/MaterializeInc/materialize/issues/11085
- [ ] https://github.com/MaterializeInc/materialize/issues/7396
- [ ] https://github.com/MaterializeInc/materialize/issues/8540
- [ ] https://github.com/MaterializeInc/materialize/issues/8561
- [ ] https://github.com/MaterializeInc/materialize/issues/12669
- [ ] https://github.com/MaterializeInc/materialize/issues/11942

**Comment by aljoscha** [comment]
Nice! Some of them feel like they could still be issues. We just have to walk through each of them and try. 🙈

**Comment by bkirwi** [comment]
Took a quick look through the issues for severity. In personal and very subjective order of most to least critial:
- #14555 - This error is easy to reproduce, and if it prevents the sink from ever working again: AFAICT only option is to drop and recreate it.
- #14098 - Similar. The error in the log is related to transactions, but transaction state generally doesn't survive a restart... either things aren't restarting correctly or somehow the new storaged is immediately driving itself into an error state. Bad either way.
- #8540 - Autoresolves when the process is restarted; probably a missing error handling path.
- #7396 - In theory this should autoresolve when the broker comes back up. I think this is also better now that sinks run in an isolated process, but we'd have to check. Shouldn't take long.
- #12669 - The minimal fix is not to complex: just log more. This really shouldn't be a panic, if we're not enforcing the invariant anywhere, though... ideally we'd handle the fix at the application level.
- #8573 - This is made less severe by the fact that we don't share storageds among sinks, so leaked threads would be cleaned up by process shutdown.

Issues I'm not sure about yet:
- #10876 - Another transaction timeout error. I can't tell from the issue whether this is transient or not. Might be resolved by fixing the producer error bubbling that some of the critical issues above are also running into.
- #11942 and #11085 - Great-looking tests which would be good to re-enable. There's enough reported issues above that I'm not sure it's worth figuring out exactly which errors cause these, but we should try and re-enable once things are in better shape.
- #8561 - Not obvious from the issue whether the affected branch ever hit main. Probably worth investigating once the known-serious stuff is squared away.

**Comment by nmeagan11** [comment]
Linking potential user reported issue: https://github.com/MaterializeInc/materialize/issues/14780

**Comment by benesch** [comment]
Heads up that I added #13889 to the list of tasks.

**Comment by cjubb39** [comment]
Current status update (mod a pending PR that I expect to merge later today):

There are only (!?) two outstanding tasks:
- https://github.com/MaterializeInc/materialize/issues/14220.  This is something we'd like to do and is definitely an improvement but isn't super urgent/critical
- https://github.com/MaterializeInc/materialize/issues/7396.  This is still a real, outstanding issue.  Perhaps it's better rolled into an error handling epic but I'm not sure.  We should certainly be able to start MZ even if a kafka broker is down

One note for our future selves.  I've defered https://github.com/MaterializeInc/materialize/issues/8573 (threads sticking around after `DROP SINK`) because it'll become relevant again [whether it's still actually happening is another question --  but it probably is] if we attempt to manage multiple sources / sinks on a single `storaged` process.  Right now we tear down the whole process so it's moot.

I'd expect to see some number of follow-up tasks now that #14965 is merged but I think it remains to be seen the best place to track those.

**Comment by bkirwi** [comment]
re: #14780 - it's no longer reproducible for sinks on the latest main branch, either in details (since `reuse_topic` has been removed) or in broad strokes (we no longer run sinks in the same process as views, so a sink can't affect a view's behaviour in the same way). We'll leave it open for now, but we'll handle it separately from this epic.

**Comment by cjubb39** [comment]
And I think that's everything for this epic!   The last PRs have been merged for a few days now and I don't see any signs of flaking so I think we're good to call this one complete!
