### ISSUE TITLE
Fancy streaming data generation in chbench

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1152]
We would like to demonstrate the fact that materialize is good at maintaining views over quickly changing data.

Two parts of this are: 

* having data that is amenable to querying/dashboarding
* being able to handle a large amount of data

This epic is about having a data source that can generate reasonable-ish looking data -- human names from a set of size N, times that have some sort of temporal locality, numbers in ranges, etc. Really we just want to match `tpchgen` in chbench.

(Large amounts of data is separate, and largely dependent on #1019)

## Task List
- [ ] #1146  chbench: generate transaction times as system::now()
- [ ] #1147 chbench: generate user names that look like words
- [ ]  #1148 chbench: support generating column data and constraining it to a pool of size N
- [ ] #1150 chbench: generate numbers from within a (possibly stepwise) range
- [ ] #1151 chbench: support generating data that has keys from other tables
- [ ] #1157 Run PoC with only valid-looking data
- [ ] #1241 chbench: fancy orderline
- [ ] #1246 chbench: support `--speedup` for timestamps
- [ ] #1149 chbench: generate zipcodes that are valid zipcodes (or at least 5-digit numbers)
- [x] #1145 Generate state columns with the 50 state abbreviations

**Comment by morsapaes** [comment]
Not sure if this is still relevant or not, but since we're using Kafka Connect anyways in `chbench`, it could be worth looking into [Voluble](https://github.com/MichaelDrogalis/voluble) instead of handling the data generation ourselves.

**Comment by sploiselle** [comment]
No one has any plans in the foreseeable future to work on `chbench` and our other load generator sources (e.g. auctions) fill a lot of the roles mentioned in this set of issues.
