### ISSUE TITLE
dbt-materialize: refactor index configuration

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#11538]
Addresses the following point in #10600:

> Deprecate the index custom materialization and replace it with support for https://docs.getdbt.com/reference/resource-configs/postgres-configs#indexes. This probably just requires implementing materialize__get_create_index_sql the same way as [postgresql__get_create_index_sql](https://github.com/dbt-labs/dbt-core/blob/22416980d19888d7bbbcfcda639c16d37a80b948/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L17-L30).

## Assumptions

The custom index materialization uses the `materialize__create_arbitrary_object(sql)` macro, which allows users to write "freehand SQL", and use both the `CREATE INDEX ... USING <col_expr>` and `CREATE DEFAULT INDEX ON` syntax. 

We should default to **not support** default index creation through this macro, and instead make it clear that users should create materialized objects explicitly instead. Does this make sense, @benesch?

### Open questions

* If we deprecate and eventually remove the custom index materialization, users will have to re-run their models to adjust the indexes created. Is this behaviour expected? It might have unwanted consequences, like dropping and recreating a "long-running" materialized view. With the custom materialization, indexes can be added more flexibly.

## Tasks

- [x] Implement `materialize__get_create_index_sql` (including tests in `materialize.dbtspec`)
- [x] Mark the custom index materialization `index.sql` (https://github.com/MaterializeInc/materialize/blob/main/misc/dbt-materialize/dbt/include/materialize/macros/materializations/index.sql) as deprecated
- [x] Add a page to the dbt documentation similar to [Postgres configurations](https://docs.getdbt.com/reference/resource-configs/postgres-configs)
- [x] Update the [Materialize profile](https://docs.getdbt.com/reference/warehouse-profiles/materialize-profile) in the dbt documentation
- [x] Update the [`README`](https://github.com/MaterializeInc/materialize/tree/main/misc/dbt-materialize) in the repo

## Testing

- [x] Set `WITH logical_compaction_window=`
- [x] Try using [expressions](https://materialize.com/docs/sql/create-index/#speed-up-filtering-with-indexes) (I don't think these are supported in the original implementation, according to [dbt-core #3106](https://github.com/dbt-labs/dbt-core/pull/3106))

**Comment by benesch** [comment]
> We should default to not support default index creation through this macro, and instead make it clear that users should create materialized objects explicitly instead. Does this make sense, @benesch?

Yes!

> If we deprecate and eventually remove the custom index materialization, users will have to re-run their models to adjust the indexes created. Is this behaviour expected? It might have unwanted consequences, like dropping and recreating a "long-running" materialized view. With the custom materialization, indexes can be added more flexibly.

I'm not sure I follow this, but it could be gaps in my understanding of dbt. How is the workflow different with a custom materialization vs the index config? Aren't both deployed via `dbt run`?

**Comment by morsapaes** [comment]
> I'm not sure I follow this, but it could be gaps in my understanding of dbt. How is the workflow different with a custom materialization vs the index config? Aren't both deployed via dbt run?

Both are deployed using `dbt run`, but with the macro you'd define an index as part of _e.g._ `some_materializedview.sql` model, like:

```sql
{{ config(
    materialized = 'materializedview',
    indexes=[
      {'columns': ['column_a']}
    ]
)}}
```

, instead of a dedicated `some_index.sql` model. So, if you want to add an index, you'd have to change the `some_materializedview.sql` model, which would drop and recreate the materialized view. With a dedicated index model, you could do:

```bash
dbt run --select some_other_index
```

Maybe this is not a real issue, since users probably set on whatever indexes make sense before deploying the models to production, and might only need to adjust themif/when the actual definition of the materialized view model also changes.

**Comment by benesch** [comment]
Ah, I see! I say we call that a `materialized` bug if it's not efficient. I think dbt in its default configuration renames the old view, adds the new view, then drops the old view; that should be enough for `materialized` to avoid the index rebuild operation.

**Comment by morsapaes** [comment]
Opened a PR for the remaining dbt documentation bit in: https://github.com/dbt-labs/docs.getdbt.com/pull/1401
