### ISSUE TITLE
[Epic] Adapter: Real-time Recency MVP

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11531]
### Initiative and Theme

Materialize is Dependable; Materialize makes observability easy

### Problem

Real-time recency is a property not only needed for Jepsen testing, but also for our consistency guarantees. This property relies on Storage providing a hook for each class of source for which we provide this property, and for Adapter to correctly invoke the hook and use the result for timestamp determination. It may be no more complicated than that, though. As a subtle property, the issues requires ownership to design and document why we have this property.

On SELECT commands, Materialize is in principle able to acquire the currentmost data of upstream sources, and ensure that any response reflects at least all of that data. This involves an interaction with the upstream source, but it ensures that the response to the SELECT command has a "real-time recency" guarantee: the answer is correct for a real-time moment greater than that at which the SELECT command was entered.

This is less than strict serializability for Materialize, as we are unable to ensure that _all_ events have orders that respect their real-time orders. In particular, we are unable to ensure that we correctly order events in unrelated external sources, and misordering them relative to their real-time order would be a violation of strict serializability. This property is meant to be the appropriate weakening of strict serializability vis-a-vis this fundamental ambiguity.

### Success Criteria
- Create a RTR implementation in the adapter layer against mock APIs.

### Must have
- [x] https://github.com/MaterializeInc/materialize/pull/16608
- [x] https://github.com/MaterializeInc/materialize/issues/16651

### Nice to have
- [ ] https://github.com/MaterializeInc/materialize/issues/17148

### Followups
- https://github.com/MaterializeInc/materialize/issues/16060 -> 
- https://github.com/MaterializeInc/materialize/issues/17130

**Comment by frankmcsherry** [comment]
Adding a few specific use cases for RTR, to add context:

1. Many users want to know "how up to date are my views of my sources". This has led to work on reclocking observability, and various jiggery pokery. RTR would allow the user to ask a query to which the answer is "always up to date". They wouldn't have to, but it seems reasonable that providing that option might be more appealing to many than learning about the right polling strategy over the reclocking views.
2. Many users have expressed surprise that we will show them partially hydrated views. They know that the results are not correct (the data were present before MZ was turned on) and seeing a count that is only half the data is an expectation violation for them.
3. MZ is meant to be a "push" system, where you hear about things the moment they are ready. RTR allows SELECT statements to be both "fresh" and "push". Without it, "fresh" require polling MZ until the reclocking information looks a certain way. In that mode, MZ is a "pull" system and it's a bit of mixed messaging.
4. Testing struggles a bit at the moment because without RTR there is no guarantee that a query will return a specific answer; this leads us to a test methodology that is "requery a few times and see if any are correct". This has at least once led us to ignore bugs where the answers were a bit random but eventually one was correct (but became wrong after, were we to look again). A system that is able to produce specific answers is much easier to test and debug than one that makes no such properties.

**Comment by nmeagan11** [comment]
Linking to related a pg-snapshot-resumption bug: https://github.com/MaterializeInc/materialize/issues/14533

**Comment by ggnall** [comment]
Porting remaining nice to have issue https://github.com/MaterializeInc/materialize/issues/17148 and some details to our follow up epic -> https://github.com/MaterializeInc/materialize/issues/17130.
