### ISSUE TITLE
[Epic] Role Based Access Control

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#11579]
## Background
Customers in large organizations want fine grained control over who can do what.  Examples of this include separating who can create versus read sources, who can create versus read tables and views, who can create and write to sinks, who can read/modify clusters.

## Customer Outcome
- Companies have the controls they need for data, cost, production/performance management to feel comfortable onboarding team members.

## Product Outcome
- Increase org deployments
- Increase users per org

## Specification
- [Spec](https://www.notion.so/materialize/RBAC-d768d2534ebf45f3a4ab551e26456b08)
- [Legacy: Authentication and Authorization](https://docs.google.com/document/d/1UcVEvavcoW1tMK_1oJxeN7koh3s37WZK8cj1wNBcpns/edit?usp=sharing)

## Documentation
- [Postgres: RBAC](https://www.postgresql.org/docs/current/user-manag.html)

## Tasks

```[tasklist]
### Must Haves
- [X] Design Doc (#17702)
- [X] Role Attributes (#17727, #17785, #17806, #17873, #17875, #17888, #17960, #17962, #17970, #18299, #18779)
- [X] Role Membership (#18034, #18217, #18311, #18780, #18781)
- [X] Public Role (#18196, #18273)
- [X] Object Ownership (#18280, #18402, #18430, #18456, #18516, #18804, #18873, #18877)
- [ ] Object Privileges (#18513, #18660, #18700, #18777, #18783, #18811, #18827)
- [ ] QA-Sign off (#18650)
```

```[tasklist]
### Nice to Haves
- [ ] `REASSIGN OWNED BY` command
- [ ] `DROP OWNED BY` command
```

## Blockers
- [X] https://github.com/MaterializeInc/materialize/issues/6754

**Comment by heeringa** [comment]
See https://github.com/MaterializeInc/materialize/issues/677 for original ask

**Comment by benesch** [comment]
Took a quick look through the spec last week, and it's looking good!

What I would suggest is that we have engineering start working on a design document that spells out:

  * The exact privileges that are supported by each object (`USAGE`, `CREATE`, etc.).
  * How object ownership works. (The creating user owns the object, but ownership can be reassigned.)
  * What privileges are required for each operation (e.g., a `SELECT` query requires `USAGE` on the active cluster, plus `SELECT` from all directly referenced objects, but not transitively referenced objects.)
  * How default roles are assigned.

I would suggest approaching the engineering design document with a bottom up methodology. We should seek to be 100% compatible with PostgreSQL _for the subset of features we choose to support in v1_. Co-evolving the engineering design and product spec will help us find the right boundary; we want to implement the minimal subset of PostgreSQL RBAC that supports the customer use cases that the product spec identifies.

**Comment by benesch** [comment]
One non procedural note: I've been thinking about how privileges on clusters should work. Here's an example of the bottom up methodology at work:

  * Clusters are like databases in PostgreSQL, in that they are a global resource. They're not scoped to a database or schema. Therefore the permission to create a cluster should be analogous to the `CREATEDB` permission in PostgreSQL.
  * Clusters are like virtual warehouses in Snowflake. The permissions to use a cluster should be similar to the `USAGE` privilege to use a warehouse in Snowflake.

So, I think it is (potentially) as simple as:

  * Creating a cluster requires that your role has the `CREATECLUSTER` privilege. 
  * Altering or dropping a cluster is limited to the cluster's owner.
  * Running queries on a cluster requires that you have the `USAGE` privilege on that cluster.
  * Creating indexes, sources, sinks, or materialized views requires that you have the `USAGE` privilege on the cluster to which you're binding the object.

My gut says we don't need to make it more complicated than this. For sure there's a distinction between fast path peeks on a cluster and slow dataflows (whether peeks or indexes), but I'm not sure that distinction needs to be represented at the RBAC level. I think it's easiest to say that either you're trusted to make use of the cluster or any purpose (`USAGE`) or not at all (no `USAGE`). If you want to give users access to data in your cluster without putting your cluster at risk... create a materialized view, and tell users to read from _that_ instead!

**Comment by jkosh44** [comment]
PostgreSQL is in the process of refactoring their privilege error messages: https://commitfest.postgresql.org/42/4145/. We should probably consult this when coming up with the error messages.

**Comment by jkosh44** [comment]
@philip-stoev I added QA sign off as a task here

@heeringa I somehow wiped all of the other tasks and have no idea how to get them back...

**Comment by ggnall** [comment]
@jkosh44 change history to the rescue! looks like nothing was actually dropped, unless you previously linked up sub-issues?
![CleanShot 2023-02-28 at 13 48 22](https://user-images.githubusercontent.com/4104582/221950131-9750ce7d-7621-4b3f-b5d7-905420e6616c.png)

**Comment by jkosh44** [comment]
> @jkosh44 change history to the rescue! looks like nothing was actually dropped, unless you previously linked up sub-issues? ![CleanShot 2023-02-28 at 13 48 22](https://user-images.githubusercontent.com/4104582/221950131-9750ce7d-7621-4b3f-b5d7-905420e6616c.png)

Oh that's useful to know how to do. Nevermind about clearing tasks, I mistakenly thought there were per-existing tasks.

**Comment by jkosh44** [comment]
I found a bunch of relevant PostgreSQL tests that we can probably use:

- https://github.com/postgres/postgres/blob/master/src/test/regress/expected/privileges.out
- https://github.com/postgres/postgres/blob/master/src/test/regress/expected/inherit.out
- https://github.com/postgres/postgres/blob/master/src/test/regress/expected/init_privs.out
- https://github.com/postgres/postgres/blob/master/src/test/regress/expected/create_role.out

FYI @def-
