### ISSUE TITLE
persist: M1 checklist

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#11605]
Shipping is a long way off, but I'd like to get ahead of maintaining a list of everything we think we need to fix before shipping the first production version.

# M1

- Impl
  - [x] #12223
  - [x] Figure out append semantics (aka refactor it to be a wrapper around compare_and_append)
  - [x] #12477
- Tests, tests, tests
  - [ ] #12408
  - [ ] (ruchir) Test coverage of every `PartialOrder::less_*` call
  - [ ] Regression test for multi-level result in apply_cmd_unbatched
  - [x] #12826
  - [ ] SnapshotSplit coverage
  - [ ] Idempotence tests (and probably some more precise semantics around it)
  - [ ] For each method in public API, verify that dropping future cancels/drops location use
  - [ ] For each location impl, verify that dropping location use correctly stops work (how?). Stop using FOREVER for Blob/Consensus timeouts
  - [x] ~Nemesis~ #12108
    - [x] #12237
- Performance
  - [x] #12601
  - [x] Initial performance tuning
    - [x] #12741
    - [x] (ruchir) Figure out why aurora is slower than we expect
    - [x] (aljoscha) Improve performance of many small ops (downgrade_since + advance for tables)
  - [x] Improve end-to-end latency for tests?
    - [x] https://github.com/MaterializeInc/materialize/pull/12348
- Liveness
  - [x] #12788
  - [x] #12264: Sneaky space optimization to make state O(non-empty trace batches) instead of O(batches)
- Bugs and Storage/Compute feedback
  - [x] #11625
  - [x] #12336
  - [x] #12263
  - [x] #12225
  - [x] #12134
  - [x] #12133
  - [x] #11997
  - [x] #11996
  - [x] #11758
  - [x] #12440
  - [x] #12435
  - [x] #12370
  - [x] #12360
  - [x] #12566
  - [x] #12452
  - [x] #12444
  - [x] #12534
  - [x] #12435
  - [x] #12555
  - [x] #12231
    - [x] #12301
    - [x] Audit (or delete) old persist code for futures_executor::block_on use

Also see #12847

**Comment by danhhz** [comment]
Done!
