### ISSUE TITLE
[EPIC] Transactions in Materialize are strictly serializable with respect to the operations that occur inside of Materialize. 

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11631]
### Feature request

The first of three consistency desiderata.

Materialize should be [serializable](https://jepsen.io/consistency/models/serializable), optionally [strictly serializable](https://jepsen.io/consistency/models/strict-serializable), when we consider transactions that involve exclusively reads from and writes to its own tables. Specifically, if we rule out reading from "external" sources, Materialize is fully able to provide strong consistency guarantees.

Materialize is not able to provide strict serializability, at least when multiple external sources are involved, as it cannot disambiguate the real-time order of writes that may have happened to unrelated sources. This rules out that strong guarantee without qualification. This property is one such qualification that provides meaningful guarantees.

--- 

Materialize is currently possibly serializable (all reads and writes have specific times, which form the total order serializability requires), but it is not strictly serializable in that the times may be assigned out of order. It may be that forcing timestamp assignment to be in-order would resolve this issue. However, the issue has some amount of ownership required, and research and documentation before we can make this claim with confidence.

--

### Tasks

- [X] https://github.com/MaterializeInc/materialize/issues/12288
- [x] https://github.com/MaterializeInc/materialize/issues/12287
- [x] https://github.com/MaterializeInc/materialize/issues/12283
- [x] https://github.com/MaterializeInc/materialize/issues/12307
- [x] https://github.com/MaterializeInc/materialize/issues/12309
- [x] https://github.com/MaterializeInc/materialize/issues/13461

**Comment by frankmcsherry** [comment]
I want to edit the above, based on conversations with @benesch, but will do that here to clarify the distinction.

Rather than restrict our attention exclusively to interactions with Materialize's own tables, we should be able to restrict our attention to all reads and writes Materialize *serves*, excluding reads and writes done through foreign systems. So, e.g. we should be able to provide strict serializability with respect to transactions that read and write MZ tables, and read from and write to foreign tables, as long as they are done through Materialize. The point is, the events that we cannot correctly order are the writes to upstream sources (and potentially, reads from downstream sources); we can still correctly order our reads from upstream sources and writes to downstream sources.

Materialize reclocking an upstream source is a "read transaction" and it can be correctly serialized or strictly serialized. Materialize writing to a downstream source is a "write transaction" and it can be correctly serialized (not sure about strictly serialized, without some head scratching about what that means).

**Comment by benesch** [comment]
@jkosh44 I assume this was an accidental closure?

**Comment by jkosh44** [comment]
With the merge of #13461, this is now complete.
