### ISSUE TITLE
release: v0.26.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#11676]
The following PRs in [`v0.26.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.26.0-rc1) require review:
* [x] [#11467 feature-benchmark: Add an outer join scenario](https://github.com/MaterializeInc/materialize/pull/11467) (@philip-stoev)
* [x] [#11466 antithesis: Run Mz in the Antithesis environment with --workers 2](https://github.com/MaterializeInc/materialize/pull/11466) (@philip-stoev)
* [x] [#11465 feature-benchmark: retry scenarios that report a regression](https://github.com/MaterializeInc/materialize/pull/11465) (@philip-stoev)
* [x] [#11478 Prepare 0.25.1 dev](https://github.com/MaterializeInc/materialize/pull/11478) (@umanwizard)
* [x] [#11498 Continue 0.25.1 dev](https://github.com/MaterializeInc/materialize/pull/11498) (@umanwizard)
* [x] [#11488 testdrive,mzcompose: Enable a persistent testdrive-svc container](https://github.com/MaterializeInc/materialize/pull/11488) (@philip-stoev)
* [x] [#11542 ci/test: add timeouts to all tests](https://github.com/MaterializeInc/materialize/pull/11542) (@benesch)
* [x] [#11562 ci/builder: bump python dependencies](https://github.com/MaterializeInc/materialize/pull/11562) (@benesch)
* [x] [#11565 docs: Recommend `--bin materialized` for building](https://github.com/MaterializeInc/materialize/pull/11565) (@teskje)
* [x] [#11586 mzcompose: drop "svc" from the name of the testdrive svc](https://github.com/MaterializeInc/materialize/pull/11586) (@benesch)
* [x] [#11592 feature-benchmark: stabilize and shorten the KafkaRestart scenario](https://github.com/MaterializeInc/materialize/pull/11592) (@philip-stoev)
* [x] [#11610 sql: Update old documentation comment](https://github.com/MaterializeInc/materialize/pull/11610) (@jkosh44)
* [x] [#11602 docs/user: fix copy commands](https://github.com/MaterializeInc/materialize/pull/11602) (@sjwiesman)
* [x] [#11635 Trigger pod replacement by hash annotation](https://github.com/MaterializeInc/materialize/pull/11635) (@alex-hunt-materialize)
* [x] [#11640 Give `metrics::Metrics` a real name](https://github.com/MaterializeInc/materialize/pull/11640) (@frankmcsherry)
* [x] [#11656 mzcompose: Update Redpanda to v21.11.12](https://github.com/MaterializeInc/materialize/pull/11656) (@BenPope)
* [x] [#11658 materialized: allow content-type CORS header](https://github.com/MaterializeInc/materialize/pull/11658) (@benesch)
* [x] [#11626 repr: Add protobuf for ScalarType](https://github.com/MaterializeInc/materialize/pull/11626) (@lluki)
* [x] [#11663 Hoist commonly used timely operators](https://github.com/MaterializeInc/materialize/pull/11663) (@frankmcsherry)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`fd8cae08c` release: v0.26.0-rc1](https://github.com/MaterializeInc/materialize/commit/fd8cae08c2c5d8d267aa74fa88bb68d939670809) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#11467 feature-benchmark: Add an outer join scenario](https://github.com/MaterializeInc/materialize/pull/11467) (@philip-stoev)
* [ ] [#11446 storage: introduce StorageController trait](https://github.com/MaterializeInc/materialize/pull/11446) (@petrosagg)
* [ ] [#11466 antithesis: Run Mz in the Antithesis environment with --workers 2](https://github.com/MaterializeInc/materialize/pull/11466) (@philip-stoev)
* [ ] [#11465 feature-benchmark: retry scenarios that report a regression](https://github.com/MaterializeInc/materialize/pull/11465) (@philip-stoev)
* [ ] [#10868 sql: make literal records coercible into scalar records](https://github.com/MaterializeInc/materialize/pull/10868) (@pH14)
* [ ] [#11463 Get rid of DeclareKeys](https://github.com/MaterializeInc/materialize/pull/11463) (@umanwizard)
* [ ] [#11471 [sql] Make normalize::full_name take mut instead of mut ref](https://github.com/MaterializeInc/materialize/pull/11471) (@cjubb39)
* [ ] [#11450 sql, coord: implement CREATE SECRET AS expr evaluation](https://github.com/MaterializeInc/materialize/pull/11450) (@mkysel)
* [ ] [#11478 Prepare 0.25.1 dev](https://github.com/MaterializeInc/materialize/pull/11478) (@umanwizard)
* [ ] [#11475 doc/user: Fix postgres docs 404s on system-catalog page](https://github.com/MaterializeInc/materialize/pull/11475) (@ruf-io)
* [ ] [#11453 sql: refactor polymorphic type resolution](https://github.com/MaterializeInc/materialize/pull/11453) (@sploiselle)
* [ ] [#11470 Tidy logic for command compaction](https://github.com/MaterializeInc/materialize/pull/11470) (@frankmcsherry)
* [ ] [#11484 doc/user: polish release notes for v0.25.0](https://github.com/MaterializeInc/materialize/pull/11484) (@morsapaes)
* [ ] [#11472 persist-client: add compare_and_append(), a cas-esque operation](https://github.com/MaterializeInc/materialize/pull/11472) (@aljoscha)
* [ ] [#11474 add 'linearize_sources' API to `StorageController`](https://github.com/MaterializeInc/materialize/pull/11474) (@guswynn)
* [ ] [#11490 Fix error message to be human readable](https://github.com/MaterializeInc/materialize/pull/11490) (@jkosh44)
* [ ] [#11494 Clean up error msg for unsupported call](https://github.com/MaterializeInc/materialize/pull/11494) (@jkosh44)
* [ ] [#11498 Continue 0.25.1 dev](https://github.com/MaterializeInc/materialize/pull/11498) (@umanwizard)
* [ ] [#11500 Add Excalidraw to Cloud Architecture doc](https://github.com/MaterializeInc/materialize/pull/11500) (@necaris)
* [ ] [#11488 testdrive,mzcompose: Enable a persistent testdrive-svc container](https://github.com/MaterializeInc/materialize/pull/11488) (@philip-stoev)
* [ ] [#11512 dataflow: Make Peek a proper struct](https://github.com/MaterializeInc/materialize/pull/11512) (@antiguru)
* [ ] [#11513 Prefer to use btree keys/values over iter](https://github.com/MaterializeInc/materialize/pull/11513) (@antiguru)
* [ ] [#11514 Dataflowd: Correct logging env symbol](https://github.com/MaterializeInc/materialize/pull/11514) (@antiguru)
* [ ] [#11103 Command reconciliation](https://github.com/MaterializeInc/materialize/pull/11103) (@antiguru)
* [ ] [#11519 build(deps): bump clap from 3.1.6 to 3.1.8](https://github.com/MaterializeInc/materialize/pull/11519) (@dependabot[bot])
* [ ] [#11455 persist: implement Consensus on top of sqlite.](https://github.com/MaterializeInc/materialize/pull/11455) (@ruchirK)
* [ ] [#11523 Cleanup unused deps on main](https://github.com/MaterializeInc/materialize/pull/11523) (@guswynn)
* [ ] [#11525 build(deps): bump tracing-subscriber from 0.3.9 to 0.3.10](https://github.com/MaterializeInc/materialize/pull/11525) (@dependabot[bot])
* [ ] [#11515 Add `map_length` sql function](https://github.com/MaterializeInc/materialize/pull/11515) (@guswynn)
* [ ] [#11521 ore: compensate for missing default max duration](https://github.com/MaterializeInc/materialize/pull/11521) (@benesch)
* [ ] [#11532 Use correct datum type (i32) in array_length implementations](https://github.com/MaterializeInc/materialize/pull/11532) (@guswynn)
* [ ] [#11535 ore/retry: improve semantics of canceling retry errors](https://github.com/MaterializeInc/materialize/pull/11535) (@benesch)
* [ ] [#11517 build(deps): bump timely from `6f50573` to `c4145f0`](https://github.com/MaterializeInc/materialize/pull/11517) (@dependabot[bot])
* [ ] [#11529 Create introspect source indexes with unique name](https://github.com/MaterializeInc/materialize/pull/11529) (@jkosh44)
* [ ] [#11534 Remove some more dead code related to bare vs. transformed sources.](https://github.com/MaterializeInc/materialize/pull/11534) (@umanwizard)
* [ ] [#11537 build(deps): bump rlimit from 0.7.0 to 0.8.1](https://github.com/MaterializeInc/materialize/pull/11537) (@dependabot[bot])
* [ ] [#11539 doc/user: add temporary note to demos](https://github.com/MaterializeInc/materialize/pull/11539) (@morsapaes)
* [ ] [#11542 ci/test: add timeouts to all tests](https://github.com/MaterializeInc/materialize/pull/11542) (@benesch)
* [ ] [#11540 Advance write frontier for `TAIL`](https://github.com/MaterializeInc/materialize/pull/11540) (@frankmcsherry)
* [ ] [#11541 coord,dataflow,sql: remove virtual clusters](https://github.com/MaterializeInc/materialize/pull/11541) (@benesch)
* [ ] [#11546 dataflow: split storage and compute clients in server](https://github.com/MaterializeInc/materialize/pull/11546) (@benesch)
* [ ] [#11551 build(deps): bump timely from `6f50573` to `c4145f0`](https://github.com/MaterializeInc/materialize/pull/11551) (@dependabot[bot])
* [ ] [#11561 build(deps): bump rdkafka from `221fb05` to `8821585`](https://github.com/MaterializeInc/materialize/pull/11561) (@dependabot[bot])
* [ ] [#11562 ci/builder: bump python dependencies](https://github.com/MaterializeInc/materialize/pull/11562) (@benesch)
* [ ] [#11206 build(deps): bump anyhow from 1.0.55 to 1.0.56](https://github.com/MaterializeInc/materialize/pull/11206) (@dependabot[bot])
* [ ] [#11223 Move timestamp bindings in STORAGE](https://github.com/MaterializeInc/materialize/pull/11223) (@petrosagg)
* [ ] [#11565 docs: Recommend `--bin materialized` for building](https://github.com/MaterializeInc/materialize/pull/11565) (@teskje)
* [ ] [#11489 repr: add protobuf support for `InvalidArrayError`](https://github.com/MaterializeInc/materialize/pull/11489) (@aalexandrov)
* [ ] [#11573 expr: align protobuf layout with `repr`](https://github.com/MaterializeInc/materialize/pull/11573) (@aalexandrov)
* [ ] [#11208 build(deps): bump urlencoding from 1.3.3 to 2.1.0](https://github.com/MaterializeInc/materialize/pull/11208) (@dependabot[bot])
* [ ] [#11570 dataflowd: Storage does not support reconciliation](https://github.com/MaterializeInc/materialize/pull/11570) (@antiguru)
* [ ] [#11055 build(deps): bump parquet2 from 0.8.1 to 0.10.3](https://github.com/MaterializeInc/materialize/pull/11055) (@dependabot[bot])
* [ ] [#11571 Storage: Discover storage workers in tcp_boundary](https://github.com/MaterializeInc/materialize/pull/11571) (@antiguru)
* [ ] [#11564 deps: unfork rust-prometheus](https://github.com/MaterializeInc/materialize/pull/11564) (@benesch)
* [ ] [#11353 design doc for connectors](https://github.com/MaterializeInc/materialize/pull/11353) (@nharring-adjacent)
* [ ] [#11584 force regenerate test certificates](https://github.com/MaterializeInc/materialize/pull/11584) (@petrosagg)
* [ ] [#11473 stash: split into trait + impl](https://github.com/MaterializeInc/materialize/pull/11473) (@mjibson)
* [ ] [#11583 coord: limit transactions to a single cluster](https://github.com/MaterializeInc/materialize/pull/11583) (@mjibson)
* [ ] [#11460 persist: skeleton of real impl delegating to durable Blob + Consensus](https://github.com/MaterializeInc/materialize/pull/11460) (@danhhz)
* [ ] [#11563 [storage] Render invalid sources](https://github.com/MaterializeInc/materialize/pull/11563) (@frankmcsherry)
* [ ] [#11543 test/metrics: merge into test/testdrive](https://github.com/MaterializeInc/materialize/pull/11543) (@benesch)
* [ ] [#11586 mzcompose: drop "svc" from the name of the testdrive svc](https://github.com/MaterializeInc/materialize/pull/11586) (@benesch)
* [ ] [#11582 Validate data dir in database copy](https://github.com/MaterializeInc/materialize/pull/11582) (@jkosh44)
* [ ] [#11548 doc: Add Python psycopg2 guide](https://github.com/MaterializeInc/materialize/pull/11548) (@bobbyiliev)
* [ ] [#11592 feature-benchmark: stabilize and shorten the KafkaRestart scenario](https://github.com/MaterializeInc/materialize/pull/11592) (@philip-stoev)
* [ ] [#11595 repr: add `ProtoRepr` trait](https://github.com/MaterializeInc/materialize/pull/11595) (@aalexandrov)
* [ ] [#11574 expr: add protobuf for global and local id](https://github.com/MaterializeInc/materialize/pull/11574) (@lluki)
* [ ] [#11597 storage: guard timestamp binding seal frontier from regressing](https://github.com/MaterializeInc/materialize/pull/11597) (@petrosagg)
* [ ] [#11600 doc/user: Fix typo in custom types](https://github.com/MaterializeInc/materialize/pull/11600) (@ruf-io)
* [ ] [#11601 sql: Make "item exists" error messages consistent](https://github.com/MaterializeInc/materialize/pull/11601) (@teskje)
* [ ] [#11585 [kafka eos] [testdrive] Reenable compaction verification](https://github.com/MaterializeInc/materialize/pull/11585) (@cjubb39)
* [ ] [#11603 stash: offer batched API to amortize operation cost](https://github.com/MaterializeInc/materialize/pull/11603) (@petrosagg)
* [ ] [#11608 persist-client: separate state of multiple shards in Consensus](https://github.com/MaterializeInc/materialize/pull/11608) (@aljoscha)
* [ ] [#11536 sql: Dynamically allocate system global IDs](https://github.com/MaterializeInc/materialize/pull/11536) (@jkosh44)
* [ ] [#11610 sql: Update old documentation comment](https://github.com/MaterializeInc/materialize/pull/11610) (@jkosh44)
* [ ] [#11602 docs/user: fix copy commands](https://github.com/MaterializeInc/materialize/pull/11602) (@sjwiesman)
* [ ] [#11611 docs/user: fix source description](https://github.com/MaterializeInc/materialize/pull/11611) (@sjwiesman)
* [ ] [#11581 persist: add new unit tests for Consensus.](https://github.com/MaterializeInc/materialize/pull/11581) (@ruchirK)
* [ ] [#11614 doc/user: merge all local files documentation pages into one + restructure the content](https://github.com/MaterializeInc/materialize/pull/11614) (@morsapaes)
* [ ] [#11612 orchestrator: improve port naming and service labeling](https://github.com/MaterializeInc/materialize/pull/11612) (@benesch)
* [ ] [#11599 stash: lighten the load on SQLite](https://github.com/MaterializeInc/materialize/pull/11599) (@petrosagg)
* [ ] [#11607 repr: add `strconv.proto`](https://github.com/MaterializeInc/materialize/pull/11607) (@aalexandrov)
* [ ] [#11567 feature-benchmark: Add scenarios around concurrency](https://github.com/MaterializeInc/materialize/pull/11567) (@philip-stoev)
* [ ] [#11593 deb822 installation](https://github.com/MaterializeInc/materialize/pull/11593) (@antiguru)
* [ ] [#11619 devsite: Upload all, not only index](https://github.com/MaterializeInc/materialize/pull/11619) (@antiguru)
* [ ] [#11617 expr: Add property testing of ID proto-ization](https://github.com/MaterializeInc/materialize/pull/11617) (@teskje)
* [ ] [#11621 doc/user: Fix time example](https://github.com/MaterializeInc/materialize/pull/11621) (@ruf-io)
* [ ] [#11618 persist: make API structs Send + Sync](https://github.com/MaterializeInc/materialize/pull/11618) (@aljoscha)
* [ ] [#11622 testdrive: Avoid unnecessary storage copies](https://github.com/MaterializeInc/materialize/pull/11622) (@jkosh44)
* [ ] [#11604 repr: add protobuf for (Var)CharLength, NumericMaxScale](https://github.com/MaterializeInc/materialize/pull/11604) (@lluki)
* [ ] [#11625 persist: don't validate sorting of batches, because we don't sort right now](https://github.com/MaterializeInc/materialize/pull/11625) (@aljoscha)
* [ ] [#11635 Trigger pod replacement by hash annotation](https://github.com/MaterializeInc/materialize/pull/11635) (@alex-hunt-materialize)
* [ ] [#11629 sql: Clean up coord bootstrapping](https://github.com/MaterializeInc/materialize/pull/11629) (@jkosh44)
* [ ] [#11636 dbt-materialize: add maintainer instructions](https://github.com/MaterializeInc/materialize/pull/11636) (@benesch)
* [ ] [#11640 Give `metrics::Metrics` a real name](https://github.com/MaterializeInc/materialize/pull/11640) (@frankmcsherry)
* [ ] [#11648 materialized: allow enabling CORS by origin](https://github.com/MaterializeInc/materialize/pull/11648) (@benesch)
* [ ] [#11012 Implement INCLUDE HEADERS for kafka sources](https://github.com/MaterializeInc/materialize/pull/11012) (@guswynn)
* [ ] [#11439 Proposal: unban 'thiserror'](https://github.com/MaterializeInc/materialize/pull/11439) (@guswynn)
* [ ] [#11645 Fix nonsensical string](https://github.com/MaterializeInc/materialize/pull/11645) (@umanwizard)
* [ ] [#11649 Update api-components.md](https://github.com/MaterializeInc/materialize/pull/11649) (@umanwizard)
* [ ] [#11650 Split storage and compute within dataflow](https://github.com/MaterializeInc/materialize/pull/11650) (@frankmcsherry)
* [ ] [#11652 fix obvious bug](https://github.com/MaterializeInc/materialize/pull/11652) (@umanwizard)
* [ ] [#11653 Reorient boundary between storage and compute](https://github.com/MaterializeInc/materialize/pull/11653) (@frankmcsherry)
* [ ] [#11623 persist: hook up transmissible Location to Client construction](https://github.com/MaterializeInc/materialize/pull/11623) (@danhhz)
* [ ] [#11656 mzcompose: Update Redpanda to v21.11.12](https://github.com/MaterializeInc/materialize/pull/11656) (@BenPope)
* [ ] [#11655 Decouple storage and compute introspection](https://github.com/MaterializeInc/materialize/pull/11655) (@frankmcsherry)
* [ ] [#11658 materialized: allow content-type CORS header](https://github.com/MaterializeInc/materialize/pull/11658) (@benesch)
* [ ] [#11647 repr: add `TryIntoIfSome` trait](https://github.com/MaterializeInc/materialize/pull/11647) (@aalexandrov)
* [ ] [#11642 coord,sql: Support `pg_get_viewdef` SQL functions](https://github.com/MaterializeInc/materialize/pull/11642) (@teskje)
* [ ] [#11643 sql: Dynamically allocate builtin type global IDs](https://github.com/MaterializeInc/materialize/pull/11643) (@jkosh44)
* [ ] [#11654 coord: Detect schema changes for builtin objects](https://github.com/MaterializeInc/materialize/pull/11654) (@jkosh44)
* [ ] [#11662 Tidy up bits of isolation in dataflow](https://github.com/MaterializeInc/materialize/pull/11662) (@frankmcsherry)
* [ ] [#11626 repr: Add protobuf for ScalarType](https://github.com/MaterializeInc/materialize/pull/11626) (@lluki)
* [ ] [#11663 Hoist commonly used timely operators](https://github.com/MaterializeInc/materialize/pull/11663) (@frankmcsherry)
* [ ] [#11613 dbt-materialize: refactor custom index materialization](https://github.com/MaterializeInc/materialize/pull/11613) (@ahelium)
* [ ] [#11670 Update guide.md's "Our Crates" section to be more explicit about our code organization philosophy](https://github.com/MaterializeInc/materialize/pull/11670) (@umanwizard)
* [ ] [`fd8cae08c` release: v0.26.0-rc1](https://github.com/MaterializeInc/materialize/commit/fd8cae08c2c5d8d267aa74fa88bb68d939670809) (@benesch)

**Comment by benesch** [comment]
And the rest are LGTM.
