### ISSUE TITLE
[Epic] Table Persistence

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11774]
### Description

This is a tracking epic for table persistence.

Separately, we have a broader goal of "make controller commands durable" (which is forced by command reconciliation), whereby each of the methods on the controller should durably commit the state transition to `materialized` metadata before returning.

### Blocks

- Zero-downtime version upgrades (Compute epic; link needed) which is supported by [command reconciliation](https://github.com/MaterializeInc/materialize/pull/11103)

### QA Tasks
- [x] evaluate performance impact of table persistence for a wide range of transaction sizes and concurrencies
- [x] make sure table persistence is enabled in CI across the board; including feature-benchmark and Zippy
- [x] revive the persistence tests for the Platform era
- [x] Add user tables to the Checks framework in order to test separate failures in storaged, computed and materialized
- [x] confirm that table persistence is exercised in upgrade tests

**Comment by elindsey** [comment]
Is there a distinction between this and https://github.com/MaterializeInc/materialize/issues/11499 ?

**Comment by nmeagan11** [comment]
> Is there a distinction between this and #11499 ?

Sorry, I missed this comment! Not really, I'm closing #11499 in favor of this one.

**Comment by nmeagan11** [comment]
@heeringa Table persistence is there from storage's perspective, so I believe the rest of the work and ownership should belong to adapter for M2 (cc @elindsey).

**Comment by benesch** [comment]
The code here is all done. @philip-stoev, looks like what remains is additional QA work for the new table persistence implementation!

**Comment by heeringa** [comment]
@nmeagan11 should we continue to use this epic to track the the QA work?  I want to make sure this doesn't fall through the cracks w.r.t. tracking...

**Comment by philip-stoev** [comment]
The following tests were done on this Epic:
- user tables were added to Zippy in order to test recovery, running in CI
- additional INSERT scenarios were added to the feature benchmark framework
- the old recovery test with user tables was enabled to run in the CI
- user table scenarios were added to the Checks framework so that recovery of storaged and environmentd can be tested as soon as such restarts become supported.
