### ISSUE TITLE
[Epic] Introspection sources/views across replicas

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11782]
### Feature request

Our introspection sources and views (but not tables) are local to timely instances. This means they have unclear semantics in situations when there are cluster replicas. The same query issued against each of the replicas will likely return results that are not compatible with other replicas, and our active replication logic will certainly not surface all of the data, just a random mishmash of the data.

We should determine the intended use cases for the introspection data, and produce a design for how to present this information to the user with ideally a minimum of confusion and chaos in breaking from the transparent active replication idiom.

### Tasks
 * [x] Enable for default cluster
 * [x] Check if we can read from other (not log-writing) clusters
 * [x] Restore state on environmentd bootstrap
 * [x] Check with add/remove replica after a cluster has been started
 * [x] Add testing for metadata (catalog entries disappear upon removal of replicas etc.)
 * [x] Finalize design in #13934 
 * [x] Writing data from each replica using a unique name
 * [x] #13882
 * [x] #13883
 * [x] #13935
 * [x] #14057

### Related
Introducing this change has put a lot stress on the storage subsystem and revealed the following bugs:
 #13854
 #13879

### Future work (ie. not necessary to complete this epic)
 * [ ] #14164
 * [ ] #14165
 * [ ] #14166
 * [ ] #14167

 * [ ] https://github.com/MaterializeInc/materialize/issues/12660

### Dependencies:
 * (soft) Storage compaction (in order to enable by default) #11491
 * (soft) Storage multi-shard read/write (perf optimization)
 * (soft) [Fat storage client](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/architecture-storage.md#fat-client)
 * (related) #12860 to enable querying across multiple replicas.
