### ISSUE TITLE
v0.26 LTS tracking issue

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11933]
This is a tracking issue for PRs that should be considered for backport to the v0.26.x series:

Special cases:

* [x] #12222

CI improvements:

 * [x] #11916 (just so that PRs play nicer in CI)
 * [x] #11932
 * [x] #11985
 * [x] 55ccb4531278bf022dd0ea6efb0af0c85f5e7520

Critical bug fixes or bug fixes with customer/Materialize Cloud demand:

 * [x] #11909
 * [x] #11949
 * [x] #11999
 * [x] #11817
 * [x] #12081

Minor bug fixes:

 * [ ] ~#11878~ rejected
 * [ ] ~#11766~ rejected

Features:

 * [x] #11891
 * [x] #11377
 * [x] #11785
 * [x] #12073
 * [x] #12195
 * [ ] ~#11306~ rejected

**Comment by morsapaes** [comment]
Though it's technically _new functionality_, would it make sense to backport #11306 (since it's behind `experimental`)? It's such a cool PR and it'd be great to let whoever is interested in this play around with it in the `LTS` release.

**Comment by andrioni** [comment]
#11891, #11377 and #11785, as they are relevant to prospects trying out Materialize.

**Comment by benesch** [comment]
Thanks, y'all! I've added everything to the issue description and sorted by category. We should have a philosophical discussion with @heeringa when he gets back. I think we want to take a hard stance on not backporting features and minor bug fixes. (Even when a new feature applies cleanly, it may cause a critical bug, and the backport for that bugfix might be a good deal harder.)

**Comment by philip-stoev** [comment]
> Though it's technically new functionality, would it make sense to backport https://github.com/MaterializeInc/materialize/pull/11306 (since it's behind experimental)? It's such a cool PR and it'd be great to let whoever is interested play around with it in the LTS release.

Unfortunately there are follow-up bugs for that functionality -- I think those will need to be addressed first  ( https://github.com/MaterializeInc/materialize/issues/11919, https://github.com/MaterializeInc/materialize/issues/11820)

**Comment by morsapaes** [comment]
Thanks for linking the existing issues, @philip-stoev! I was half-expecting it to be a long shot and am still adapting to the idea of the LTS version. In the end, I agree with:

> I think we want to take a hard stance on not backporting features and minor bug fixes.

**Comment by benesch** [comment]
We've now got a branch (v0.26) to host these backports. I've updated the issue description with the list of PRs that have been backported. So far its just one PR that the cloud team submitted that will help them debug an issue with username/password auth (thanks, @antifuchs!).

**Comment by benesch** [comment]
#11658 is actually in v0.26.0, and I'm pretty sure #11827 fixed a bug introduced after v0.26. I think #11817 is the only required backport, and #11766 is optional.

**Comment by morsapaes** [comment]
#11909 fixes a blocking issue for Mark@Flow Traders (see [this thread](https://materializecommunity.slack.com/archives/G01E317QB47/p1650988025816059)), so it would be neat to include it in the release.

**Comment by benesch** [comment]
Yes, #11909 will almost surely be part of v0.26.1! Firm commitment coming later this week.

**Comment by benesch** [comment]
Our policy for v0.26 backports has been shared internally in the #release channel. I'm going to backport everything currently listed in the "CI improvements" and "critical bug fixes" sections and cut v0.26.1-rc1 later today.

**Comment by benesch** [comment]
Two requests for backport to v0.26.2 so far:

* [ ] #12279 (by request of Materialize Cloud)
* [ ] A revert of #11564 to restore some per-thread metrics

**Comment by guswynn** [comment]
@benesch I suggest we backport https://github.com/MaterializeInc/materialize/pull/12082 as well, to match last weeks backport of the compute version of this

**Comment by guswynn** [comment]
Ok @benesch, I tested, and I think that #12082 fixes a bug that is ONLY in `tcp_boundary`. As far as I can tell, in 0.26, that boundary is only used with the experimental k8s orchestrator (can someone help confirm this?) When I `cargo run` on the v0.26 branch, I can't repro the bug, so I think for on-prem, single process, mz, we don't need to backport

**Comment by benesch** [comment]
> Ok @benesch, I tested, and I think that #12082 fixes a bug that is ONLY in `tcp_boundary`. As far as I can tell, in 0.26, that boundary is only used with the experimental k8s orchestrator (can someone help confirm this?) When I `cargo run` on the v0.26 branch, I can't repro the bug, so I think for on-prem, single process, mz, we don't need to backport

Oh, yes, you're completely right! I knew there was a reason that I didn't backport it to v0.26.1. Sorry I forgot! Sounds like we're good to go on v0.26.2.

**Comment by guswynn** [comment]
@benesch I believe its an actual bug a customer hit, cc @umanwizard

**Comment by guswynn** [comment]
as for the fix: I feel fairly confident, its even a unit-testable change

**Comment by pH14** [comment]
Looking for input on whether to backport a fix to https://github.com/MaterializeInc/materialize/issues/12275. This causes a crash if a Kafka message is received without a key when using `ENVELOPE NONE`, and was reported by a member of the community Slack. Writing up and testing a fix took ~2 days on the latest version, so I'd guess backporting would by upper bounded by that amount of time.

**Comment by guswynn** [comment]
@pH14 this code hasnt changed that much so a cherry-pick would not be too bad

**Comment by pH14** [comment]
Update: from the discussion (https://materializeinc.slack.com/archives/CTESPM7FU/p1654702741186949) and reading through our backport policy, #12275 does not meet the criteria for an LTS backport.

**Comment by benesch** [comment]
I'm proposing https://github.com/MaterializeInc/materialize/pull/13190 for inclusion in v0.26.3, which is a combination of a backport and new feature development per user feedback in #13153.

**Comment by benesch** [comment]
v0.26 is no longer relevant! 🎉
