### ISSUE TITLE
Measure scaling performance

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#12069]
We plan to support multi-process clusters in order to allow customers to handle _larger_ workloads by using _larger_ clusters.

Our initial mapping of cluster T-Shirt sizes to physical resources has been implemented in https://github.com/MaterializeInc/cloud/pull/2865.

@frankmcsherry's experience with TD/DD (outside of Materialize) is that adding additional processes can improve performance as soon as you have 16 workers/process. How does this translate to Materialize?

Part of #11238.

### Goals

* Measure scaling behavior and identify bottlenecks
* Confirm sizing decisions or propose adjustments

### Non-Goals

* Fix all scaling bottlenecks
* Establish benchmarks 
* Establish performance regression tests

### Subtasks

* [ ] Measure throughput/latency while keeping input sizes fixed and increasing cluster sizes
* [ ] Measure throughput/latency while increasing input sizes with cluster sizes
* [ ] Provide guidance on scaling decisions in https://github.com/MaterializeInc/cloud/pull/2865

### Related

* https://github.com/MaterializeInc/cloud/pull/2865

**Comment by antiguru** [comment]
Related to #17591
