### ISSUE TITLE
release: v0.26.1-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#12113]
No PRs in [`v0.26.1-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.26.1-rc1) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`1a784b8f2` Correct values going into metric labels (#12081)](https://github.com/MaterializeInc/materialize/commit/1a784b8f2ca12b9d69a235b1a28f5f1f0d5bec25) (@benesch)
* [ ] [`92f6b0d0d` Experiment with logic in  planning (#11909)](https://github.com/MaterializeInc/materialize/commit/92f6b0d0d8eb31e6015c0db2c10dec80a2c5d8b3) (@benesch)
* [ ] [`39415f11f` Cease replaying sources on token drop (#11949)](https://github.com/MaterializeInc/materialize/commit/39415f11f514715ced79703017bef03fcd764100) (@benesch)
* [ ] [`02bff4a14` Merge pull request #11817 from benesch/cors-defaults](https://github.com/MaterializeInc/materialize/commit/02bff4a14c1727414c1b327caff9857e25c4869b) (@benesch)
* [ ] [`374d77643` mzcompose: Enable kafka-time-offset.td for Redpanda](https://github.com/MaterializeInc/materialize/commit/374d776439c8dca94a7563873d61e40d63c364d9) (@benesch)
* [ ] [`088500414` [ci] Allow test jobs to run on builder agents](https://github.com/MaterializeInc/materialize/commit/088500414760f042605e7f674dfa3573526e476e) (@benesch)
* [ ] [`c8a1b599a` ci: improve queue selection logic](https://github.com/MaterializeInc/materialize/commit/c8a1b599a9f24d47da6fd473bb9936100cece60c) (@benesch)
* [ ] [`c4197388c` ci/deploy: remove queue specification on trigger steps](https://github.com/MaterializeInc/materialize/commit/c4197388ca6cefcfbd01348e39368901d6c75307) (@benesch)
* [ ] [`8eeeeecac` release: v0.26.1-rc1](https://github.com/MaterializeInc/materialize/commit/8eeeeecacfad548b92988041e5d6ff2ddb46b2d3) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#11999 Warn on frontegg authentication failures in pgwire & http](https://github.com/MaterializeInc/materialize/pull/11999) (@antifuchs)
* [ ] [`1a784b8f2` Correct values going into metric labels (#12081)](https://github.com/MaterializeInc/materialize/commit/1a784b8f2ca12b9d69a235b1a28f5f1f0d5bec25) (@benesch)
* [ ] [`92f6b0d0d` Experiment with logic in  planning (#11909)](https://github.com/MaterializeInc/materialize/commit/92f6b0d0d8eb31e6015c0db2c10dec80a2c5d8b3) (@benesch)
* [ ] [`39415f11f` Cease replaying sources on token drop (#11949)](https://github.com/MaterializeInc/materialize/commit/39415f11f514715ced79703017bef03fcd764100) (@benesch)
* [ ] [`02bff4a14` Merge pull request #11817 from benesch/cors-defaults](https://github.com/MaterializeInc/materialize/commit/02bff4a14c1727414c1b327caff9857e25c4869b) (@benesch)
* [ ] [`374d77643` mzcompose: Enable kafka-time-offset.td for Redpanda](https://github.com/MaterializeInc/materialize/commit/374d776439c8dca94a7563873d61e40d63c364d9) (@benesch)
* [ ] [`088500414` [ci] Allow test jobs to run on builder agents](https://github.com/MaterializeInc/materialize/commit/088500414760f042605e7f674dfa3573526e476e) (@benesch)
* [ ] [`c8a1b599a` ci: improve queue selection logic](https://github.com/MaterializeInc/materialize/commit/c8a1b599a9f24d47da6fd473bb9936100cece60c) (@benesch)
* [ ] [`c4197388c` ci/deploy: remove queue specification on trigger steps](https://github.com/MaterializeInc/materialize/commit/c4197388ca6cefcfbd01348e39368901d6c75307) (@benesch)
* [ ] [`8eeeeecac` release: v0.26.1-rc1](https://github.com/MaterializeInc/materialize/commit/8eeeeecacfad548b92988041e5d6ff2ddb46b2d3) (@benesch)

**Comment by umanwizard** [comment]
lgtm
