### ISSUE TITLE
[EPIC] QA: Update existing tests, frameworks and tooling for the Platform era

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12221]
### Goal(s)

Various tools and tests need to be updated for the platform era.

### Steps
- [x] #12280
- [ ] Integrate Kubernetes/minicube into the testing infrastructure
- [x] ##11888
- [ ] write testing scenarios for Kubernetes-specific stuff
    - [ ]  Instantiation of Mz instances/clusters in a K8S environment 
    - [ ]  secrets storage in Kubernetes and use in sources
    - [ ]  handling the termination of individual pods and containers

**Comment by philip-stoev** [comment]
The non-K8S items in this epic have been completed. A separate M2 epic will be opened for the K8S stuff, so I am closing this one.
