### ISSUE TITLE
Basic platform observability

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12230]
This issue tracks the work items that will be required to support basic debugging of Materialize Platform in production:

* [x] Add an `/api/health` endpoint to all of `storaged`, `computed`, and `materialized`. See MaterializeInc/cloud#2896.
* [ ] Enable Tokio Console for `storaged` and `computed`.
  * [ ] Consider enabling Tokio's unstable features in our released binaries, so we can use it to debug in production.
* [ ] Wire up opentel on computed and storaged
* [ ] Wire up basic distributed tracing. Probably dust off #11378, then see if we can get a basic trace into Jaeger that shows a query moving through pgwire, coord, compute, and back.
  * [ ] MVP: just wire up a tracing id between pgwire, coord, and the peek response
  * [ ] switch transport to grpc and move tracing id/etc between all services
  * [ ] see this m1 goal: https://github.com/MaterializeInc/cloud/issues/2884

cc @guswynn

**Comment by guswynn** [comment]
@benesch for the last one, did we ever figure out how we could make a trace work across multiple services? is it just using a trace id?

**Comment by benesch** [comment]
Yeah! I tracked down the example of how to do this with OpenTelemetry and Tonic here: https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/tracing-grpc

The hypothesis is still that we'll pivot `storaged` and `computed` to use gRPC so that we get this sort of stuff for free, but it's a bit of a large project to scope out.

**Comment by guswynn** [comment]
@benesch that WILD! it may be possible to hack something up without using grpc, by implementing `Injector`/`Extractor` manually

**Comment by benesch** [comment]
Oh, almost certainly! There's many other reasons to want to switch to gRPC, though. Integrates well with Protobuf and allows for easy observability via linkerd.

**Comment by guswynn** [comment]
After talking to some people (mostly @jpepin), I have some more context about what I think should happen here:

To me, there are 2 kinds of "traces" or "metrics" we can use to observe our running system:

* "prescriptive", which is when we proactively think about what metrics are important.
  * [ ] `/api/health` end points fall squarely in this seciton See MaterializeInc/cloud#2896.
  * [ ] Thinking about what we _think_ running services should behave like, and add traces to produce those
  * [ ] metrics from outside of mz itself, like:
    * [ ] k8s metrics, things like "are the correct number of services actually running and not crash looping"

* "descriptive", which are traces/metrics that purely describe some specific flow/path within the system
  * [ ] Enable Tokio Console for `storaged` and `computed`, to enable `tokio-console` use from
    * [ ] enabling this in production is more concerning, as its unclear what kind of performance/stability hit we will take.
  * [ ] Wire up distributed tracing for queries against mz. 
    * [ ] A good goal is to see if we can get a basic trace into honeycomb that shows a read query moving through pgwire, coord, compute, (maybe storage, and back through coord and pgwire.
    * [ ] switch transport to grpc and move tracing id/etc between all services
      * Part of this work is tracked in #12292 and #12358. #11378 may have a good starting point.
    * [ ] A minimal start that doesn't require grpc: just wire up a trace between pgwire, coord, and the response back from compute in coord
  * [ ] additionally, add collectors for other standard things like cpu usage, memory usage (more difficult to get right). This I know less about hooking up, but it sounds like @antifuchs knows how to hook this up to honeycomb)
    * [ ] some of these may be instrumented outside of mz itself

Additionally, there are general infra changes that need to happen to enable both types of observability:
* [ ] Wire up opentel on computed and storaged

Additionally, I think there are 2 important points to keep in mind, in M1 and going forward:
- Lean on over-tracing (to the extent possible by things like honeycomb), so we can learn what's actually useful, and change the set of things we instrument later.
- Welcome additional tracing sources as we see fit
  - As a concrete example, we may find its a useful signal to watch the latency of requests _between services_, and may find its easiest to lean on what linkerd and/or cilium gives us, as opposed to implementing it ourselves

**Comment by necaris** [comment]
> As a concrete example, we may find its a useful signal to watch the latency of requests between services, and may find its easiest to lean on what linkerd and/or cilium gives us, as opposed to implementing it ourselves

This is in my experience _very much a thing_ and I would recommend trying to surface it as soon as we're able to. I believe Cilium gives us decent tools to do so, though.

**Comment by necaris** [comment]
Thanks for the writeup @guswynn ! I agree with your broad categorization of prescriptive vs descriptive, and that we can get a better intuition for what we should prescribe from watching descriptive metrics better. I would add that one of the things we need to do in M2, i.e. on-call and strong customer support, is going to rely on a good set of prescriptive metrics.

**Comment by guswynn** [comment]
@necaris I appreciate your summary, that we can lean more on descriptive in m1, and develop and refine prescriptive as we move down the milestones!

(as for the cilium thing, its unclear to me if cilium gives us http[2] level metrics, which I think (?) things like linkerd give us, but i could be wrong)

**Comment by guswynn** [comment]
@elindsey @JLDLaughlin, Here is a roughly ordered temporal plan that I plan to follow! There are roughly two main projects that can happen simultaneously, but I am focussing on the former at the beginning:


## Distributed tracing
- Implement the MVP where we show that propagation of trace id's works for peeks: https://github.com/MaterializeInc/materialize/pull/12483
- Setup opentelemetry for `storaged` and `computed`
- Wait for the `coord-compute` grpc change to merge
- Implement an MVP propagating trace context's between coord and compute for peeks
- Wait for the `coord-storage` grpc work to merge
- Implement an MVP propagating trace context's between coord and storaged for at least one request type, say
And then finally:
- Systematically instrument all query types across coord-computed-storaged
- (Instrument the behavior of storaged interacting with upstream external sources)

## "Prescriptive Metrics" (I think has a very small m1 goal)
- Implement `/api/health` https://github.com/MaterializeInc/cloud/issues/2896
  - (its unclear to me who will implement this)

### Things that can happen in free time:
- setup `tokio-console` for `storaged` and `computed`

**Comment by necaris** [comment]
> Implement /api/health https://github.com/MaterializeInc/cloud/issues/2896
> (its unclear to me who will implement this)

This might be a(nother) good dipping-toe-into-Rust project for @jpepin ? I'd also be very happy to tackle it

**Comment by guswynn** [comment]
do we need `/api/health` in addition to the prometheus sql exporter endpoint described in https://github.com/MaterializeInc/cloud/issues/3082?

**Comment by benesch** [comment]
Yeah, I think we want it for integration with Kubernetes liveness/readiness probes, which really want a single HTTP endpoint that returns 200 OK that can be hit repeatedly and don't support fancier reasoning about e.g. Prometheus metrics.

**Comment by necaris** [comment]
Yes, we definitely need a basic "200 OK I'm alive" endpoint. I think more fanciness on top of this -- e.g. what @jpepin and @joacoc were talking about investigating -- comes later.

**Comment by guswynn** [comment]
Basic overview of plan for the implementor (cc @jpepin)

In mz, we use a library call `axum` (https://docs.rs/axum/latest/axum/) to build http servers, using async-await.

Axum has 3 main pieces:
- The actual http server impl, which is from a library called `hyper`, re-exported as `axum::Server`
- a `Router` (https://docs.rs/axum/latest/axum/struct.Router.html) that maps paths (and other info, like request type, etc) to handler
- _handlers_, which basically boil down to, just async functions that take requests (anything that implements `FromRequest`) to anything that implements 

an example of setting up the first 2 is here: https://github.com/MaterializeInc/materialize/blob/be1517246965f5fc399e8cd3bc4fe3708d17e907/src/materialized/src/http.rs#L355-L367, and an example handler used by it is here: https://github.com/MaterializeInc/materialize/blob/be1517246965f5fc399e8cd3bc4fe3708d17e907/src/materialized/src/http.rs#L355-L367

Luckily, axum handles requests on the same, shared, global runtime (basically a thread pool), so we can add as many axum servers as we want, bound to different addresses!

So, we need to:
1. find a place to write this common server setup, as it will be the same in all three (materialized, computed, storaged) binaries
2. write a simpler axum server+handler that responds A-OK
3. hook up that server in all 3 binaries, by spawning it into a _task_ (like this: https://github.com/MaterializeInc/materialize/blob/main/src/materialized/src/lib.rs#L430-L435), so it runs in the background

these can definitely be done separately, in order!

**Comment by benesch** [comment]
Thanks for writing this up, @guswynn! To zero in a bit: all of `materialized`, `storaged`, and `computed` already have this simpler server!

In `materialized`, it's the metrics server:

https://github.com/MaterializeInc/materialize/blob/762a3a4529796d722daee85c5595449a13f4a021/src/materialized/src/lib.rs#L433

In `computed`, it's the HTTP console server:

https://github.com/MaterializeInc/materialize/blob/762a3a4529796d722daee85c5595449a13f4a021/src/compute/src/bin/computed.rs#L245

And similarly in `storaged`:

https://github.com/MaterializeInc/materialize/blob/762a3a4529796d722daee85c5595449a13f4a021/src/storaged/src/main.rs#L170

So all you'll need to do is write a new `health` handler and route it in all three servers. The right place for this handler is the `http-util` crate.

**Comment by guswynn** [comment]
@benesch Oh I wasn't sure that we should use those existing servers! even easier!

**Comment by benesch** [comment]
This has all been completed!
