### ISSUE TITLE
[Epic] Compute/storage boundary can race with source compaction

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#12576]
Goal: Guarantee correct replication behavior with storage compaction

### Tasks
 * [ ] Produce example of problematic behavior after storage compaction lands
 * [ ] Design for how to handle storage compaction and replication failure scenarios
 * [ ] TODO: Discuss Alternative 1: Compute read frontier as minimum across replicas to hold back compaction to the slowest replica
 * [ ] TODO: Discuss Alternative 2: Add a user-configurable parameter that determines a compaction lag for storage. Document it as an advanced feature.
 * [ ] Implement

# Bug report

* Related: #13117
* Related: #12885

### What version of Materialize are you using?

735f07e5bb10f439a2915223ccb9d9f117afcc46 

### How did you install Materialize?

Built from source

### What is the issue?

Dataflow subscriptions of sources can race with source compaction for multi-replica clusters. Currently, sources are announced to `storaged`, but only rendered once a `computed` subscribes to a source. We delay the rendering because `storaged` doesn't know how many instances of a source it needs to render because it is oblivious to replicas.

For a multi-replica cluster, the following sequence can potentially happen:
1. Create a source
2. Create dataflow ingesting the source
3. (replica 1) renders dataflow, announces subscription to `storaged`.
4. (replica 1) reports data.
5. The coordinator allows compaction of the dataflow + source because it's request is fulfilled.
6. (replica 2) was slow and now renders the dataflow and wants to subscribe to `storaged`'s source.
7. (replica 2) waits indefinitely for the subscription to succeed, as it cannot receive process for the source its dataflow will stay around, or worse it'll crash.

To fix this, we need to change the boundary to prevent compaction until all expected replicas have subscribed, or maintain a window in the past lagging compaction. Maybe this'll be solved by @petrosagg's work to loop sources through persist.

**Comment by petrosagg** [comment]
I don't understand the original description. My understanding is that in a replicated compute cluster the compute controller receives frontier notifications from both replicas and following their dependencies eventually forward the constraints to the storage controller, which would then drive compaction.

So even if the coordinator was expressing a desire for compaction the compute dependencies would hold back the compaction frontier anyway. @antiguru is my understanding correct?

**Comment by frankmcsherry** [comment]
It would be great to hoist it up into the API (e.g. return a `Result`) as I think there is potentially a recovery option: advance the dataflow locally and produce outputs from the new time. It's not certain that we can do this in all cases, but we certainly cannot do it if this panics. Not a high priority to fix, but seems like an easy thing whoever looks into this issue can either do or liase with storage on.

**Comment by teskje** [comment]
> Produce example of problematic behavior after storage compaction lands

I don't think we need to wait for compaction. Persist already returns an error when you try to read at an `as_of` that's less than the shard's current `since`. See #12885.

**Comment by teskje** [comment]
> TODO: Discuss Alternative 2: Add a user-configurable parameter that determines a compaction lag for storage. Document it as an advanced feature.

Looks like the STORAGE team is already thinking about something in this vein to improve performance: https://materializeinc.slack.com/archives/C02KE368L8P/p1654707028632509?thread_ts=1654706753.845169&cid=C02KE368L8P

**Comment by lluki** [comment]
Possibly related [slack comment](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1656621281615749)

**Comment by lluki** [comment]
Some ideas how we could reproduce the issues:

1. Write an (untargeted) stress test: Have x processes connect via SQL interface and have them: create a replica, create materialized view, select from a it, then drop replicas. 
2. Alternatively, we could instrument one of the computed's to delay the processing of an incoming command (ie. a sleep after the GRPC receive or so). Then activate the sleep only in one replica, and use the cluster mzcompose test to check if we run into this issue.  
3. As a slight alteration, we also might just slow down the dataflow rendering. 
4. Instead of sleep, we could use the [docker resource settings](https://docs.docker.com/config/containers/resource_constraints/#cpu) to limit the cpu usage . 

Any of these ideas can also be combined with setting the compaction window to very small values.

I briefly tried option 4) but without further tweaking, does not reproduce the issue.

**Comment by antiguru** [comment]
Here's a test where this seemed to have happened: https://buildkite.com/materialize/tests/builds/39331#01828cc0-fe0d-43e9-9b61-d5ffa545b8b1

**Comment by teskje** [comment]
Another instance of this bug: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1663600296010169
