### ISSUE TITLE
[Epic] persist: MFP Pushdown - understand column structure of data and push down filters

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#12684]
### Product Outcome

Select SQL queries fetch less irrelevant data from s3, resulting in faster dataflow startup.

### Specification

TODO

### Design

A design doc will be written as an artifact of prototyping, once it has advanced far enough.

The rough idea is for persist to keep metadata about the range of `(key, value, ts)` in each "part" as well as min/max values for the SQL columns stored. Then `persist_source` can use the `MapFilterProject` handed to it to reason about which parts contain only data that would be filtered out once fetched, then skip fetching them. This is a technique represented in OLAP database literature.

Because persist internally keeps data sorted by `(key, value, ts)`, this should be effective for any query that is a range over any prefix of that. Trivially, imagine an exact key lookup, but also something like `WHERE key_col_1 BETWEEN foo AND bar`. Note that CockroachDB manages to express its entire SQL implementation in terms of key range queries, so this is more powerful that it may initially seem. The major drawback is that it depends on the SQL columns that make up `key` being ordered usefully, which is hard to change and is also not something we particularly go out of our way to do right now.

Because persist internally inherits the Spine/Batch/Description structure from differential dataflow arrangements, data in a shard keeps temporal locality with respect to when it was inserted. It also is structured with the most recent data in the smallest batches, and the least recent data in the largest, compacted batches. The former means that these filters should be effective when run against any column whose values tend to be correlated with realtime. The latter means that they should be especially effective when run against ranges of recent realtime. These are both true _even when this realtime-correlated column is not a prefix of the key columns_. Concretely: it's pretty much exactly a temporal filter.

This is complementary to the `TRANSFORM USING` approach discussed in #15899 and elsewhere. As [Petros notes](https://materializeinc.slack.com/archives/C04QHS93G0Z/p1677011988662109?thread_ts=1677011365.207529&cid=C04QHS93G0Z), there will likely always be cases where a user wants to push down a transformation that can't be expressed as these filters. `TRANSFORM USING` also might be a useful building block for something like GDPR, where the user cares about what data is being stored beyond how that affects compute start up times.

This, on the other hand, is more suited to ad-hoc data exploration and other cases where the user doesn't want to (or can't ) do the upfront work of `TRANSFORM USING` before the data is written. This also, counter-intuitively, might be cheaper in a number of cases: data at rest on S3 is cheap [($23/TiB/month)](https://aws.amazon.com/s3/pricing/), while `TRANSFORM USING` relies on persist aggressively advancing timestamps and consolidating out retractions, which requires S3 Puts (surprisingly expensive).

```[tasklist]
### Required Issues (Must Haves)
- [ ] #16883
- [ ] Finalize SourceData <-> parquet mapping
- [x] Use new format for persist batch/part files
- [x] Agree on an API boundary between persist and MFP
- [x] Implement filter pushdown itself
- [x] Darktest (mark batches as fetchable, but fetch them anyway, then error if anything in them isn't filtered by MFP)
```

```[tasklist]
### Discretionary Issues (Nice To Haves)
- [ ] 
```

**Comment by danhhz** [comment]
Confirming that this is still relevant but M3

**Comment by danhhz** [comment]
Status update: @pH14 is working on a prototype for this, which is progressing nicely. This has already considerably de-risked the project (I'm increasingly confidant that we can ship this with sufficient elbow grease). Along the way, he's uncovered a fair bit of work that would be necessary for any (even aggressively) minimal version of this (i.e. we're gonna need a _lot_ of elbow grease).
