### ISSUE TITLE
persist: M2 checklist

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#12847]
[a] = alpha, [b] = beta, [g] = ga, [p] = post-ga (these are all _worst case_, not ideal)

[compact] = Compaction (Bounded S3 Usage)
[mem] = Bounded Memory Usage
[perf] = Performance
[prod] = Production Hardening

# Bugs
- [ ] [a/b][perf] #12992
- [ ] [a/b] #13861
- [x] [g] #13975
- [x] [g] #13802
- [x] [g] #14261
- [x] [g] #14043
- [x] [g] #14670
- [x] #13858
- [x] #13804
- [x] [g] #14021

# Pre-GA (sorted by order of work)
- [x] [perf] #12859
- [x] [prod] Implement drop-is-cancel semantics in the prod Consensus/Blob impl
  - [x] #13583
- [x] [compact]  Garbage collection of blob and consensus data
  - [x] #13575
  - [x] #13656
- [x] [mem] #12980
- [x] [a/b][prod] Permanent storage format for State
  - [x] #13512
- [x] [g][compact]  Physical and logical compaction
  - [x] #13160
- [x] [prod] Metrics
  - [x] #12942
  - [x] #12934
  - [x] #12941
  - [x] [a] #13945
  - [x] [g] #13964
  - [x] [g] #14005
    - [x] [g] #14079
- [x] [prod] #12237
- [x] [g][compact] Backward-incompatible prep needed for leaked blob detection
  - [x] #13617
  - [x] #14155
- [x] [b/g][perf] #14250
- [x] [b/g][perf] #13623
  - [x] #14175
- [x] [g][compact] Leasing
  - [x] #13916
  - [x] #14672
- [x] [g][perf] Distribute batch parts, not batches in persist_source
  - [x] #14452
  - [x] #14525
    - [x] Use serde instead of proto for ExchangeData impls
- [x] [g][prod] Set up dashboards in shared Grafana
- [x] [g][prod] Support storage/usage billing efforts
  - [x] #13754
- [x] [g][prod] Logging
  - [x] #13466
- [x] [g] #14675
- [x] [g] ~Store ProtoBatchFormat on ProtoHollowBatch?~ nah
- [x] [g][prod] #14156
- [x] [g][prod] #13952
- [x] [b/g][mem] #14527
- [ ] [g/p][compact] #8185
  - [ ] #14704
- [ ] [g(/p?)] Additional compaction tuning as necessary
- [x] Backward-incompatible changes
   - [x] ~[g][prod] Renumber protos~ not needed
   - [x] [g][prod] #14723 (merge)
   - [x] ~[g][perf] Revisit encoding for batch keys (make them smaller)~ can be done backward compatible, if necessary
- [ ] [g][prod] Anything else we need to understand how persist is currently going in prod
  - [x] Add inc state support to "persistcli inspect"
  - [ ] Metric for blobs that are only sticking around because of seqno hold
  - [ ] Metrics for how close readers/writers are getting to expiry before leases being extended
  - [x] Metrics for snapshots, listens, batches fetched, seqno leases, etc
  - [ ] Metric for number of live diffs in consensus (should be available in gc)

# Post-GA (unsorted)
- [p] #14490
- [p] `downgrade_since([])` should also expire the ReaderId and internally replace the ReadHandle with a stub (context #14263 and [slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1660670449094529))
- [p][prod] Don't ignore maintenance in any command (was too hard to reason about when diagnosing #14719)
- [p][prod] #12797
- [p] Tune down the size at which we chunk off a new s3 blob (currently 128MiB, ideally more like 8-32MiB)
- [p] Resurrect the golden test
- [p][prod] Periodic cleanup task for leaked blobs
- [p][prod] Rate limiting for gc (the deploy that un-broke it took down prod crdb) (p assuming that not running all gc in environmentd)
  - [x] #14064
- [p][prod] #13961
- [p][prod] #13918 (b if other debugging tools don't work well enough; p otherwise)
- [p][perf] Multi-worker shard reads
  - #13849
  - #14177
- [p][perf] Multi-worker shard writes
  - #13594
  - #14001
- [p][perf] Update open_loop benchmark to stress sharded reads and writes
- [p][perf] Compaction micro-benchmark
- [p][perf] Encoded state size test (like encoded_batch_sizes)
- [p][perf] Compaction RPC server to increase storage throughput (only if necessary)
- [g/p][perf] crazy idea?: One machine impl per shard per process to reduce contention (only if necessary)
- [g/p][perf] See if we can reduce contention by moving downgrade_since calls to storaged/computed
- [g/p][perf] Add more prompt listening for changes in Consensus (only if necessary)
- [p][mem] #12734
  - [p] Possibly write an operator that runs after the persist one that chunks it down to single digit MB
- [p] Pipeline batch fetches in persist_source stage 2
- [p][perf] Add a cache around location usage (only if necessary)
  - This would help with a MATERIALIZED VIEW that is being maintained in the same cluster as a dataflow that is using it. Also possibly the new rendition-lite persist_sink
- [p][prod] Use tls in our prod Consensus impl (p only because we _currently_ store no sensitive data in consensus)
  - #13108
  - hook this up in cloud
- [?][prod] [Tag s3 blobs](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1655331174017759)
  - #13154
- [p][prod] Use u64s instead of UUIDs for ReaderId/WriterId (and PartId?)
- [g/p][compact] #13347
  - #13117
- [p][compact]  Bring back the blob.delete call in Batch::delete
- [p][mem] Somehow ensure O(consolidated) space usage when reading a sharded snapshot
  - #14086
- [p][prod] Tests for Consensus/Blob drop-is-cancel semantics
- [p][prod] Verify somehow that blob matches consensus to prevent accidental misuse
- [p][prod] Proptest coverage of persist protos
- [p][prod] Reintroduce encoded state checksum
- [p][perf] RPC server for cmd contention (only if necessary)
- [p][perf]  Cmd batching
- [p][perf] Secret idea to inline small writes
- [p][perf] Special case compaction for append-only workloads

# Debt

Keep engineers sane and happy.

- [x] Document ordering guarantees for snapshots and listen
  - [x] #13022
  - [x] #13031
- [x] #13143

.

- [p] Remove the K, V, and D bounds from State and Machine (do the codec checking for them only in ReadHandle/WriteHandle/etc. They'll always need T, though, to be able to use various Antichain logic when evaluating a state transition
- [p] Crate mz_persist_client shouldn't depend on mz_persist. Pull common code
  out into mz_persist_types or a new crate.
- [p] Document the new timeout/error/retry philosophy
- [p] Tidy up datadriven test infra and port eligible existing tests to it

# Other

- [p] persist blog post

**Comment by danhhz** [comment]
It's certainly not M2 anymore :)
