### ISSUE TITLE
[Epic] Enable Postgres Source in Platform

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12856]
### Initiative and Theme

Materialize is Friendly; Materialize makes it easy to add new upstream data sources

### Problem

Postgres is our next highest priority source after Kafka. Since this is mostly there at present, this epic is more of a placeholder to track remaining engineering tasks.

### Success Criteria

A user can connect their Postgres source to Materialize with the same or greater ease than they did previously.

### Time Horizon

Small

### Blockers

- #13749

### Eng Tasks

- [x] https://github.com/MaterializeInc/materialize/issues/11953
- [x] #13246
- [x] #12857
- [x] #13254
- [x] Resuming Postgres sources correctly (#13369)
- [x] #13749
- [x] #14311

### Testing and QA sign-off
- [x] Add Postgres sources to Zippy
- [x] Add Postgres sources to the Platform Checks
- [ ] #13724

**Comment by benesch** [comment]
Just to clarify: this is blocked on renditions because of #11953? I'm not _entirely_ sure that we need renditions to solve that issue!

**Comment by nmeagan11** [comment]
It was! But based on https://github.com/MaterializeInc/materialize/issues/11953#issuecomment-1147451582, we are proposing to just crash, but isn't that sort of a non-starter given the current state of `storaged`?

**Comment by benesch** [comment]
Not at all, actually! As part of the fault tolerance work we’ll learn to handle restarting failed `storaged` processes.

**Comment by nmeagan11** [comment]
Great! Removing renditions as a blocker based on the conversation in the other issue.

**Comment by benesch** [comment]
So I think the only work item here is #11953!

**Comment by benesch** [comment]
I added #12857 as a work item, as we can't test restart of a PostgreSQL source until we have storage reconciliation. After that, there is still a bit more work to do. We need to restart from the latest WAL we've made durable—probably using a replication slot that's created in the catalog at `CREATE SOURCE` time, rather than created in the storaged process at render time.

**Comment by nmeagan11** [comment]
I'm removing https://github.com/MaterializeInc/materialize/issues/13450 as a task associated with this epic, because it shouldn't block us from closing once QA is complete.
