### ISSUE TITLE
[Epic] Internal Storage Sink

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12860]
This feature gives us the ability to send the data to storage and have another cluster read from it. Note that this epic covers both design and implementation.

### Goals

* Provide a means to sink the output from sources and views to persistent storage
* Provide a means to read sinked data from persistent storage

### Acceptance Criteria

* Users can create internal storage sinks in SQL
* Users can read back data from sinked to internal storage in SQL
* Data is sinked exactly once, even in the face of replica restarts

### Tasks

* [x] Define SQL syntax for defining internal sinks and reading back data
* [x] Validate the current persist_sink implementation to identify missing parts
    * Behavior in the face of multiple replicas
    * Behavior in the face of slow replicas
    * Behavior in the face of restarting replicas
* [x] Create a (possibly retroactive) design for internal sinks
* [x] Implement the design
  * [x] Enable creating, selecting from, and dropping recorded views.
  * [x] Remove the old `CREATE SINK ... INTO PERSIST` syntax.
  * [x] Introduce helpful errors when users try to use regular view commands to drop/alter/show recorded views.
  * [x] Disallow creating recorded views on log sources.
  * [x] https://github.com/MaterializeInc/materialize/issues/13471
  * [x] Add support for `SHOW OBJECTS`.
  * [x] Add support for `SHOW INDEXES`.
  * [x] Propagate dataflow errors.
* [x] Rename recorded views to materialized views. 
* [x] Add/adjust documentation.
  * Tracked in https://github.com/MaterializeInc/developer-experience/issues/165 

### Testing

* [x] Add recorded views to Zippy
* [x] Add recorded views to the Checks framework
* [x] Add a test that kills the cluster that maintains the recorded view, makes sure other clusters are not affected

### Bugs

*

### Related

* [Internal Storage Sink design document](https://www.notion.so/materialize/Internal-Storage-Sink-505983857bb24ae2b36cdc15ff9cc3a4)
* [Notes - Sinks Kickoff](https://docs.google.com/document/d/11EF9ogFgKLJ7Uo36EC7mR98tFy_3UdMMvTg3jCQY8jk/edit#heading=h.o9l87q7wmf7j)
* https://github.com/MaterializeInc/materialize/pull/11964 - Persist sinks already implement some of the functionality we need.
* https://github.com/MaterializeInc/materialize/issues/12866 - Eventually, compute will use the fat storage client to sink data to persist. Until this is done, we can use the `persist` library directly.
* https://github.com/MaterializeInc/materialize/issues/12854 - We plan to rely on renditions for version upgrades.

### Questions

*

**Comment by benesch** [comment]
@danhhz and I have talked about this on and off over the past few months. One of the ideas that's come up is modeling this as a "persistent index", as in:

```
CREATE VIEW v AS ...
CREATE PERSISTENT INDEX ON v (a, b);
```

The key point is that these internal sinks are fundamentally different than external sinks, and we may want to model that explicitly in the nouns and syntax we choose. I expect that we will only be able to build an external sink by creating an internal sink first. It seems perhaps clean to model that via persistent indexes, so that we can tell users "you can only build a sink on top of a view with a persistent index."

Or, maybe we don't want to muddy up the concept of an index. Perhaps there's some other noun we can besides "sink" and "index" to describe the concept of an internal sink.

cc @frankmcsherry @aljoscha who both have had thoughts in this area.

**Comment by frankmcsherry** [comment]
"Materialized View" seems like a great name! Only sort of kidding.

I don't see the way in which they would be "indexes"? At least, not without the additional work to have them support random access, slot in for DD indexes in e.g. things like joins...

Seems like the concepts are / could be: 
1. persistent collections, 
2. sources (instructions to populate a persistent collection from some external foo)
3. sinks (instructions to feed some external foo from some persistent collection)

Tbh, "materializing" a view seems like a natural way to express that you'd like it written back. I understand that the name is already in use, but .. starting from scratch it would check out, right? More than "persistent index" imo.

**Comment by benesch** [comment]
> Seems like the concepts are / could be:
>
> persistent collections,
> sources (instructions to populate a persistent collection from some external foo)
> sinks (instructions to feed some external foo from some persistent collection)

💯 

> Tbh, "materializing" a view seems like a natural way to express that you'd like it written back.

I ... agree. In fact it's way more akin to what a materialized view is in other database. Oops.

Let's set aside the naming question for a second. I'm going to use the term `RECORDING` to mean "make a persistent recording of this view in a storage collection."

```
> CREATE VIEW v AS SELECT ... ;
CREATE VIEW
> CREATE SINK v_sink FROM v INTO KAFKA BROKER 'elsewhere:9092';
ERROR: v is not recorded
> CREATE RECORDING v_recording OF v IN CLUSTER c;
CREATE RECORDING
> CREATE SINK v_sink FROM v INTO KAFKA BROKER 'elsewhere:9092';
CREATE SINK
```

ISMT like sinks then don't need to be cluster scoped objects. But, somewhat weirdly, they depend implicitly on a recording existing, and records _are_ cluster scoped, because you need somewhere to compute `v` so that you can write it down. What happens if you drop `v_recording`? Do we prevent that because `v_sink` depends on it? Or is it okay because you might show up and run

```
CREATE RECORDING v_recording_new OF v IN CLUSTER c2
```

and create a new recording for `v` later? And because of definiteness that recording is known to be equivalent to the original `v_recording`.

**Comment by benesch** [comment]
@teskje has proposed the following strawman in the [internal sinks design doc](https://www.notion.so/materialize/Internal-Storage-Sink-505983857bb24ae2b36cdc15ff9cc3a4):

```
CREATE SINK foo FROM some_view INTO STORAGE;
SELECT * FROM foo;
```

----

I think there are a few questions to answer to help us evaluate the design space here.

* Should we use the name "sink" in the syntax for this feature? My sense is no. I'd love to find a term besides "sink" in the syntax/docs, so that we can reserve the term "sink" for the process by which a storage collection is exported to the outside world.
* Let's say we introduce the concept of a "recording", where "recording" is a strawman name that I have chosen simply because it does not have the baggage of "sink" or "materialization". Are recordings like indexes, in that they are selected automatically by the optimizer when they exist, but are not directly selectable? (You never name an index in a `SELECT` query—they just magically get used.) Or are recordings a selectable object, which you have to name explicitly in a `SELECT` query to use?

@frankmcsherry had some takes on the above, and I'm sure @teskje does too now! Let's discuss with product in the meeting tomorrow.

**Comment by philip-stoev** [comment]
Now that `MATERIALIZED` means `RECORDED` , all the items from the QA checklist are being implemented by existing tests. I can not think of anything else to test at this time.
