### ISSUE TITLE
[Epic] Surfacing Source/Sink Errors

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12864]
### Product Outcome

Source/sink errors are presented clearly to the end user so they know when sources or sinks aren't working as expected. For example, currently if a user enters a wrong password for a Kafka source, it still looks successful from the user's perspective. This should be exposable via a query or in the UI.

### Specification

[Here!](https://www.notion.so/materialize/Exposing-source-errors-via-SQL-1c83b2070b5a48db967b829b7ccd88dc)

### Design

[Here!](https://www.notion.so/materialize/Exposing-source-errors-via-SQL-1c83b2070b5a48db967b829b7ccd88dc)

### Documentation

- [x] https://github.com/MaterializeInc/materialize/issues/16370

### Required Issues (Must Haves)

- [x] #15061
- [x] #15162
- [x] #15163
- [x] #15164
- [x] #15165
- [x] #15166
- [x] #16065
- [x] #16426

#### Postgres sources

- [ ] https://github.com/MaterializeInc/materialize/issues/14823

#### Kafka sources

- [ ] https://github.com/MaterializeInc/materialize/issues/14518

#### Kafka sinks

- [ ] https://github.com/MaterializeInc/materialize/issues/15251
- [ ] tbd

### Blockers

None

### Blocks

- [ ] https://github.com/MaterializeInc/cloud/issues/4268
- [ ] https://github.com/MaterializeInc/cloud/issues/4267
- [ ] P1 deliverable of https://github.com/MaterializeInc/cloud/issues/3259

### QA

- [ ] Make sure a comprehensive tests are present for all possible source and sink errors
- [ ] Add source and sink errors to the Platform Checks framework (to confirm proper behavior across upgrades and restarts)
- [ ] Go through all the known previously-filed GH tickets and make sure that the error is surfaced properly
- [ ] Remove the source/sink error writes from unsafe mode
- [ ] Unify and clean up the source status history abstractions across sources and sinks

**Comment by elindsey** [comment]
Previously https://github.com/MaterializeInc/materialize/issues/7115

**Comment by aljoscha** [comment]
We need to audit which source errors make it into the `Err` collection, and eventually into the persist shard. As of now, I think too many errors make it in there that shouldn't be there. They instead should go to the new status shard that @andrioni introduced.

10_000 ft summary: Only _definite_ errors should make it into the `Err` collection. System errors/runtime errors, which are transient should not make it in there.

**Comment by aljoscha** [comment]
This internal message (and thread) is important for things we need to thing about when we pick the work on this back up: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1660726837927649.

We need to figure out:
 - who writes to the status shard, who advances it's upper when nothing happens?
 - how does the storage controller learn about the upper of the status shard?

Potential solutions from the thread:
 - storage controller or the `storaged` instances make sure the upper advances
 - we change storage controller to _actively_ listen for upper changes of all shards/collections it knows about. Instead of controller relying of `StorageResponse::Uppers` and `append()` advancing the upper.

Pluswhich we need to rename this type of collection (that `mz_source_status_history` is) from "storage collection", because all collections that storage knows about are really storage collections.

**Comment by nmeagan11** [comment]
[Linking an issue](https://materializeinc.slack.com/archives/C03SXGGEN3Y/p1661182769465109) we came across in external testing that we should surface.

**Comment by nmeagan11** [comment]
Below is a collection of problems that users have encountered in the wild.

**Sources:**

- [ ] Using the wrong `SASL_MECHANISMS` option causes the source to complain under the hood (see https://github.com/MaterializeInc/materialize/issues/12864#issuecomment-1222544893).
- [ ] Flagging if an upstream database has a setting that doesn't allow the WAL held back by a slot fo exceed a certain size during source creation ([reference](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1661789975382539?thread_ts=1661788827.366789&cid=C01CFKM1QRF)).
- [ ] "Hidden" connection string issues and network timeouts([reference](https://materializeinc.slack.com/archives/C02JEJ7SHTP/p1663624432756889), [another reference](https://materializeinc.slack.com/archives/C03SXGGEN3Y/p1663635498886499)).
- [ ] Kafka read errors. For example, when using Redpanda, we need `WRITE` priviledges to perform ingestion in addition to `READ`, `DESCRIBE`, and `DESCRIBE CONF` ([reference](https://materializeinc.slack.com/archives/C03SXGGEN3Y/p1663724129078899))

**Sinks:**

- [ ] Sinks stop emitting without any errors in the logs ([reference](https://materializeinc.slack.com/archives/C03K23ECB8U/p1663929450276179?thread_ts=1663863804.673439&cid=C03K23ECB8U)).

**Comment by nmeagan11** [comment]
Semi-related: https://github.com/MaterializeInc/materialize/issues/15892

**Comment by bkirwi** [comment]
Linking in https://github.com/MaterializeInc/materialize/issues/15949 - which is triggered by the increased write contention on the status shards. It's a blocker for taking this feature out of unsafe mode.

**Comment by bkirwi** [comment]
Went through @nmeagan11's comment [here](https://github.com/MaterializeInc/materialize/issues/12864#issuecomment-1258386968) and checked through the linked issues. Most of them are in-principle fixed by the implementation currently in `main`. (In the sense that, given our best understanding of the customer's issue getting set up, we'd have something helpful for them in the new status tables.) A couple are not:
- The postgres configuration check should in principle be a warning at creation / purification time.
- For sinks, we still ignore any errors in the upstream collection. We really ought to do _something_ with those errors, but we're not sure what: none of the behaviours we can come up with for this seem like the obvious right thing for users.

I don't think either of those are blockers for this epic, though I'll confirm that they're tracked _somewhere_ if we don't get to them before we close this out.

**Comment by uce** [comment]
The required work on this epic is considered done. 🎉  @philip-stoev has worked with @bkirwi on tests and signed off on this. We will treat additional error scenarios as future work and track separately.
