### ISSUE TITLE
[Epic] Improve the Performance of Source Ingestion

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12863]
### Product Outcome

Performance is critical to Materialize. Once adapter spins up the end-to-end performance tests (https://github.com/MaterializeInc/materialize/issues/13047) and tracing, there is a yet unknown amount of work to be done in Storage to address the arising issues. See https://github.com/MaterializeInc/materialize/issues/13043 and [Internal Performance Target Goals](https://docs.google.com/document/d/1_NUMlZCUkilYlvQU3O4UVya3shKJ1INrtVLM3c3FtXc/edit) for concrete outcomes.

### Specification

See https://github.com/MaterializeInc/materialize/issues/13043 and [Internal Performance Target Goals](https://docs.google.com/document/d/1_NUMlZCUkilYlvQU3O4UVya3shKJ1INrtVLM3c3FtXc/edit) for context.

### Design

This will be on a per-issue basis.

### Documentation

TBD

### Required Issues (Must Haves)

(needs triaging)
- [x] https://github.com/MaterializeInc/materialize/issues/12775
- [x] https://github.com/MaterializeInc/materialize/issues/13651
- [x] #13854 (caused by replica spinup writing a bunch of things to persist, from `create_collections`)
- [ ] Benchmarking for sharded persist reads/writes per https://github.com/MaterializeInc/materialize/issues/13884#issuecomment-1313941210
- [x] https://github.com/MaterializeInc/materialize/issues/16090

### Discretionary Issues (Nice To Haves)

N/A

### Blockers

Results from https://github.com/MaterializeInc/materialize/issues/13047

**Comment by benesch** [comment]
> be able to compare it to results from pre-Platform.

This is going to be fairly hard. Is this a hard requirement? Or can we limit scope to tracking improvements over time in Platform?

**Comment by nmeagan11** [comment]
Some numbers we're seeing with a prospect using Postgres sources:

A user has 84 tables in his upstream Postgres database, with about 13 million rows in total. The larger tables (4 of them) are on the order of magnitude of 1 million, and the rest are either in order of magnitude of 100,000 or 100. The user was using a source of size `large` for his `CREATE SOURCE` statement. We approximated that one of the larger tables (~1 million rows) took about 40 minutes to finish, and their entire source took around 90 minutes to load in.

**Comment by nmeagan11** [comment]
Some internal notes: https://github.com/MaterializeInc/product/issues/211

**Comment by uce** [comment]
@aljoscha is reviewing linked issues and moving relevant ones over to the next milestone.

**Comment by aljoscha** [comment]
I added relevant subtasks to the next milestone (M4), Next, and Later (also known as "no milestone").  All the moved issues have the `T-performance` label and can be tracked under https://github.com/orgs/MaterializeInc/projects/26/views/13
