### ISSUE TITLE
M1 demo tracking

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12917]
* [x] https://github.com/MaterializeInc/materialize/issues/12401 is preventing use of Materialize Cloud with several cloud Kafka providers
* [x] `CREATE SOURCE` takes 30s due to MaterializeInc/cloud#3168
* [x] #12944
* [x] https://github.com/MaterializeInc/cloud/issues/3252

**Comment by benesch** [comment]
To be clear, the demo blocker for "poor query latency" is _specifically_ scoped to `SELECT 1`. We don't need to solve `SELECT * FROM table` being slow, but we _do_ need to make sure that a simple query like `SELECT 1` does not sometimes take 750ms.

**Comment by benesch** [comment]
Calling #12944 done for the purposes of the demo. Several mitigations went in that bring down the time of `advance_local_timestamps` to something much safer.

**Comment by benesch** [comment]
Also calling https://github.com/MaterializeInc/cloud/issues/3252 done for the purposes of the demo since we haven't seen it in a while.

**Comment by benesch** [comment]
These are all resolved to the satisfaction of the demo. Leaving several of the issues open to track permanent fixes. 

Folks at the company can follow along with the demo work here: https://www.notion.so/materialize/M1-board-demo-8da2c9a7f7264087a317da4d59fcf6de
