### ISSUE TITLE
[Epic] Measure latency of out-of-core peek lookups

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#13036]
### Goals

Benchmark out-of-core performance in cloud.
* Caveat: Personal stacks use a different size mapping than staging/prod.

### Tasks

* [ ] Identify performance targets for lookups (eg < 10 ms/lookup)
* [ ] Benchmark out-of-core performance with swap in cloud
* [ ] Document findings (Do we oom? How does performance degrade?)

### Related

* See also: https://github.com/MaterializeInc/cloud/issues/2705

### Questions

* Do we need to monitor swap utilization and add billing accordingly?

**Comment by antiguru** [comment]
Done as part of #6763.
