### ISSUE TITLE
[Epic] Region-allocated data in arrangements

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#13037]
### Goals

Productionize columnization prototype (#6763)

### Tasks

* [ ] Re-run out-of-core benchmarks with prototype code
* [ ] Specify targets for columnar data
* [ ] If results are promising, productionize prototype

### Related

* (blocker) #13036.

**Comment by antiguru** [comment]
Fixed by #6763.
