### ISSUE TITLE
[Epic] Consolidate `EXPLAIN` plan formats across IRs

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#13137]
The following capabilities are not unified across the different IRs (MIR, HIR, LIR):

- Text-based `EXPLAIN` output.
- Graphical `EXPLAIN` output.
- Testing input and output format.

Each of these formats has specific set of requirements. We want to identify those requirements and fix a specific format as a prerequisite for future work.

As part of this effort, we should also try to include TDO (timely + differential operators). Currently, it only has graphical output (dataflow graph visualization).

### Goals

- [x] Enumerate the requirements for each of the following use-cases:
    - Text-based `EXPLAIN` output. Possible options: current format, ...
    - Testing input and `EXPLAIN` (output) format. Possible options: Custom DSL, JSON, ...
    - Graphical `EXPLAIN` output. Possible options: DOT, JSON, ...
- [x] Refactor the code so we can maximize sharing for each of these formats across the common part of our IRs.
- [x] Specify what information needs to be rendered and how a specific format will render this information at every explain stage.
- [x] Implement the above spec for text-based and testing format.

The requirements for the test format should be aligned with @philip-stoev since we probably want to use the same format for both unit and end to end tests. 

### Non-Goals

- Working out all the details and the actual implementation of any testing and graphical `EXPLAIN` format that is not JSON.
- Implement anything beyond basic working version for JSON (no attributes, pretty-printing of rows, etc).

### Acceptance Criteria

- [ ]  We have answered the questions above and have accepted a design how to encode support for each of these formats in an ergonomic and non-redundant way.
- [ ] The text-based has been realized.
- [ ] At least one format that can support testing in the short term has been realized (most likely JSON).
- [ ] At least one format that can be used as an input for a graphical view in the short term has been realized (most likely JSON).

### Tasks

Rather than gradually migrating the current to the target state in a breaking fashion, we agreed to devise a strategy where we temporary accommodate both paths in `main` and then eliminate the old path once we are comfortable.

There are three main areas that need to be fixed to facilitate that:

- SQL Parser (`parse_explain`)
- SQL Planner (`plan_explain`)
- Coordinator (`sequence_explain`)

Here is a tentative list of tasks to achieve these changes over the next few weeks in a non-disturbing manner.

- [x] #13293
- [x] #13294
- [x] #13295
- [x] #13296
- [x] #13472
- [x] #13730
- [x] #13471
- [x] #13297
- [x] #13476
- [x] #13299
- [x] #13298
- [x] #13302

### Testing

See #13297.

### Bugs

TODO

#### Design Docs
- [Consolidate EXPLAIN plan formats across IRs](https://www.notion.so/materialize/Consolidate-EXPLAIN-plan-formats-across-IRs-7963ed3c1f28483dae9b2d0495d63bbb)
- [EXPLAIN Usability Considerations](https://www.notion.so/materialize/EXPLAIN-Usability-Considerations-bce37d82abaa484fbb489cf72c1d37f3)

#### Issues & PRs
- #1752

### Questions

TODO

**Comment by aalexandrov** [comment]
Closing this after doing a pass on the design doc. Follow-up suggestions have been summarized in #13302.
