### ISSUE TITLE
[Epic] IN planning with no subqueries

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#13151]
This is for queries such as `SELECT * FROM table WHERE col IN (7,8,9)`

### Goals
- Reduce probability of stack overflow by unnesting the ORs that INs get decomposed to. 
- Improve qps of queries involving IN clauses with constant
### Acceptance Criteria
- Performance should improve for queries such as the above.
- We should be able to avoid some stack overflows that are currently due to the deeply nested OR chains.
### Tasks
- [x] Make AND/OR into variadic functions.
- [x] Investigate these alternatives and implement one of them:
  - Have dataflow rendering use an index in cases of `(x=<constant> OR x=<otherconstant>...)`
  - Have MIR=>LIR use an index in cases of `(x=<constant> OR x=<otherconstant>...)` by decomposing into a union and thus relying on the existing rendering code.
  - Join. This will be the one. Subtasks:
    - [x] Measure different join variants for performance and decide which one to use. (Done: it has to be a differential join, with the constant collection as starting collection, at least until #14059 is fixed.)
    - [x] move the `x=<constant>` recognition to MIR (done by https://github.com/MaterializeInc/materialize/pull/13713)
    - [x] Introduce a join with a constant collection (PR: https://github.com/MaterializeInc/materialize/pull/14169)
    - [x] Transform `record_create(e1, e2) = Literal(record(c1,c2))` to `e1=c1 AND e2=c2`. This is necessary because `(e1,e2) IN ((1,2))` is desugared to a `record_create`. (PR: https://github.com/MaterializeInc/materialize/pull/14258)
    - [x] Make `literal_constraints` smarter to be able to capture an OR of different constraints. For this, I need to convert the MFP into a different canonical form: (PR: https://github.com/MaterializeInc/materialize/pull/14353)
      - [x] Inline literal constraints that were CSEd by `mfp.optimize`.
      - [x] Distribute AND/OR. (This is the inverse of the `undistribute_and_or` in `MirScalar_Expr::reduce()`.)
      - [x] Turn the list of predicates into a variadic AND of predicates.
    - [x] Remove the found literal constraints from the MFP. (It was ok that they have not been removed so far, but now we will be able to handle a potentially very big OR expression there, which can have a serious evaluation cost, so it should definitely be removed.) (PR: https://github.com/MaterializeInc/materialize/pull/14353)
    - [x] Fast path should be upgraded to be able to handle multiple literal constraints. (PR: https://github.com/MaterializeInc/materialize/pull/14403)
    - [x] Decompose `record_create(...) = record_create(...)` (PR: https://github.com/MaterializeInc/materialize/pull/14465)
### Related
- https://github.com/MaterializeInc/materialize/issues/9473
- (from Philip) https://github.com/MaterializeInc/materialize/issues/6247
- (from Philip) https://github.com/MaterializeInc/materialize/issues/6246
- (distantly related) https://github.com/MaterializeInc/materialize/issues/4229

**Comment by ggevay** [comment]
Design doc: https://www.notion.so/materialize/IN-planning-with-no-subqueries-f66956a3e744462fae74292b3f129149#0b758fd4ca804521974a2c38d39869ab
It looks like broadcast join is winning in terms of performance. So now I'll look into the implementation details of broadcast join to see
- how much effort would be to implement it,
- confirm the performance characteristics.

**Comment by wangandi** [comment]
@ggevay A potential follow up to keep in mind.

As stated in the description of #13713
> Our aggressive CSE slash deficiencies in our <expr>=literal detection code means that we do not speed up <expr>=literal predicates if the <expr> is also an output column.

A concrete example:
```
CREATE TABLE fizz(f1 string, f2 int);

CREATE INDEX fizz_f1_idx ON fizz(substr(f1, 3));

explain select substr(f1, 3), f2 from fizz where substr(f1, 3) = 'FED';

             Optimized Plan              
-----------------------------------------
 %0 =                                   +
 | Get materialize.public.fizz (u44)    +
 | Map substr(#0, 3)                    +
 | Filter (#2 = "FED"), (#0) IS NOT NULL+
 | Project (#2, #1)                     +
```

Our code that speeds up filters of the form `<expr>=literal` only looks in the "Filter" line and thus sees `#2 = "FED"` instead of `substr(#0, 3) = "FED"`. This shouldn't matter much in the `<expr>=literal` case because
1. the `<expr>=literal`  is likely to be selective.
2. The user can just rewrite the query to `select 'FED', f2 from fizz where substr(f1, 3) = 'FED'`.

However, this might be more of a problem if the query is `select substr(f1, 3), f2 from fizz where substr(f1, 3) in ('FED', 'OCL', ..)`.

**Comment by ggevay** [comment]
The "potential follow up" from the above comment is also handled in https://github.com/MaterializeInc/materialize/pull/14353 by a little bit of extra code in `inline_literal_constraints`.

**Comment by ggevay** [comment]
This should still be documented, see https://github.com/MaterializeInc/materialize/issues/14645#issuecomment-1266551760
