### ISSUE TITLE
[Epic] Add Support for `ENVELOPE DEBEZIUM` in Platform

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#13310]
### Initiative and Theme

Materialize is Friendly; Materialize works with your existing pipelines

### Problem

Subset of https://github.com/MaterializeInc/materialize/issues/13044. Supporting Debezium envelopes is necessary for users that already have Kafka + Debezium. This is our highest priority envelope to support in Platform.

### Success Criteria

Users can successfully execute a `CREATE SOURCE ... FROM KAFKA ... ENVELOPE DEBEZIUM` statement.

### Time Horizon

Large

### QA Sign-off

- [x] Add ENVELOPE DEBEZIUM to Zippy, Platform Checks, Feature Benchmark
- [ ] Add `TRANSACTION METADATA` to all applicable tests and frameworks

### Blockers

- Resolve open question in https://github.com/MaterializeInc/materialize/issues/13121#issuecomment-1165140138
- https://github.com/MaterializeInc/materialize/issues/11772

### Known Bugs

 - #13490 Debezium sources that specify a `TRANSACTION METADATA` source don't acquire read holds for the transaction source. This leads to panics at runtime. Does not affect `DEBEZIUM UPSERT` sources!
 - #11919
 - #11820
 - #13629

### For Consideration

- [ ] https://github.com/MaterializeInc/materialize/issues/12077
