### ISSUE TITLE
release: v0.26.4-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#13351]
No PRs in [`v0.26.4-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.26.4-rc1) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`02555ee19` Nullable array fields (#13255)](https://github.com/MaterializeInc/materialize/commit/02555ee1959752fe2b7f4b1cc1376aeb4a2db830) (@umanwizard)
* [ ] [`65b20187d` release: v0.26.4-rc1](https://github.com/MaterializeInc/materialize/commit/65b20187da72b22093aef881dd575322551b3909) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#13190 [LTS] Improve handling of CORS](https://github.com/MaterializeInc/materialize/pull/13190) (@benesch)
* [ ] [#13330 [LTS] backport kafka ENVELOPE NONE null key handling](https://github.com/MaterializeInc/materialize/pull/13330) (@pH14)
* [ ] [`02555ee19` Nullable array fields (#13255)](https://github.com/MaterializeInc/materialize/commit/02555ee1959752fe2b7f4b1cc1376aeb4a2db830) (@umanwizard)
* [ ] [`65b20187d` release: v0.26.4-rc1](https://github.com/MaterializeInc/materialize/commit/65b20187da72b22093aef881dd575322551b3909) (@umanwizard)

**Comment by benesch** [comment]
Brennan’s unreviewed commits LGTM.
