### ISSUE TITLE
SQL-ify explain representations of scalars

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#13482]
Our explanations currently print out scalars in a way that reflects how they are represented internally in our code base. We should change them to conform to the representation that a user familiar with SQL is used to.

Changes include but are not limited to:
- [x] `filter (<pred1>), (<pred2>), (<pred3>)` -> `filter <pred1> AND <pred2> AND <pred3>`
- [x] join conditions in MIR / LIR (as above)
- [x] `#0 && #1` -> `#0 AND #1`
- [x] `#0 || #1` -> `#0 OR #1`
- [x] `!#0` -> `NOT #0`
- [x] `isnull(#0)` -> `#0 IS NULL` (resolved in [#13598](13598))
- [x] `!(isnull(#0))` -> `#0 IS NOT NULL` (resolved in [#13598](13598))
- [x] `istrue(#0)` -> `#0 IS TRUE` (resolved in [#13598](13598))
- [x] `!(istrue(#0))` -> `#0 IS NOT TRUE` (resolved in [#13598](13598))
- [x] `isfalse(#0)` -> `#0 IS FALSE` (resolved in [#13598](13598))
- [x] `!isfalse(#0)` -> `#0 IS NOT FALSE` (resolved in [#13598](13598))
- [x] improve casts (resolved in [#13554](13554))
- [x] Records, lists, arrays: (resolved in [#14033](14033))
  - A record is printed as `[1,2]`, whereas in the SQL syntax it can be written either as `(1,2)` or `ROW(1,2)`, and in the query output it's `(1,2)`.
    - This is because records are actually represented as `Datum::List`. Maybe we could look at the `ColumnType` of the `Literal` to distinguish a list from a record.
  - A list is also currently printed as `[1, 2]`, whereas in SQL syntax it's `LIST[1,2]`, and in query output it's `{1,2}`.
  - An array is printed as `{1, 2}`, whereas in SQL syntax it's `ARRAY[1,2]`, and in query output it's `{1,2}`.

**Comment by ggevay** [comment]
Added an item about records, lists, arrays.

**Comment by wangandi** [comment]
Closing issue to record that many of the associated subtasks have been done. Remaining subtasks have been transferred to https://github.com/MaterializeInc/materialize/issues/14841
