### ISSUE TITLE
[Epic] Kubernetes testing

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13580]
Tracking ticket for a Kubernetes test framework that allows us to test the controllers in this repository and our internal cloud infrastructure repository. Details forthcoming. @philip-stoev is working on a [design document](https://www.notion.so/materialize/K2s-Testing-Framework-Design-Draft-99e2bf59434948cead2831ee57171c3d?d=2ede95987ece4114b26326a2199e390a#b4761cffa032406bb837a47c44163bc3).

Internal Slack channel: https://materializeinc.slack.com/archives/C03N44NCD9V

Things that require Kubernetes testing:

  * [x] Kubernetes secret implementation
  * [ ] Version upgrade orchestration
  * [ ] gRPC version checks (#13569)
  * [x] Killing environmentd should cause K8s to restart it
  * [x] Killing computed or storaged should cause the K8s orchestrator to restart them
  * [x] Dropping a cluster should cause the computeds to go away
  * [x] Dropping a source/materialized view/sink should cause the storageds to go away 
  * [x] Creating a cluster replica should place the replica in the least full AZ

**Comment by philip-stoev** [comment]
All items from the checklist have been implemented except for the version-related ones. Those will wait for a dedicated Epic on upgrades to show up before they can be worked on.
