### ISSUE TITLE
doc/user: document `CREATE CONNECTION`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#13657]
### Documentation request

Connections are now reusable across sources, so this needs to be documented:

- [x] Add `CREATE CONNECTION` page broken down by supported connector (Kafka, Postgres) (#13674, thanks to @mjibson!)
- [x] Add `DROP CONNECTION` page (#13798)
- [x] Add `SHOW CONNECTIONS` page (#13798)
- [x] Add `SHOW CREATE CONNECTION` page (#13798)
- [x] Add grammar to `sql-grammar.bnf` (#13798)
- [ ] Embed new concept into `CREATE SOURCE` landing page 🚫 + dedicated connector pages ✅  (#13876)
- [ ] Adapt key concepts page (#13876) 🚫
- [x] Adapt examples to use the new syntax (#13876)

### Sample syntax

```sql
CREATE CONNECTION kafka
  FOR KAFKA
    BROKER '{config[ConfigKey.BROKERS.value]}',
    SASL MECHANISMS = 'PLAIN',
    SASL USERNAME = SECRET sasl_username,
    SASL PASSWORD = SECRET sasl_password;

CREATE CONNECTION csr_ssl
  FOR CONFLUENT SCHEMA REGISTRY
    URL '{config[ConfigKey.REGISTRY.value]}',
    USERNAME = '{config[ConfigKey.REGISTRY_USERNAME.value]}',
    PASSWORD = SECRET registry_password;
```

### Related work

- https://github.com/MaterializeInc/materialize/pull/13161
- https://github.com/MaterializeInc/materialize/pull/13383
- https://github.com/MaterializeInc/materialize/pull/13552
- https://github.com/MaterializeInc/materialize/pull/13646
- https://github.com/MaterializeInc/materialize/issues/13374
- https://github.com/MaterializeInc/materialize/issues/11504

**Comment by benesch** [comment]
So sorry about rewarding all the `CREATE SOURCE` restructuring work with ... even more restructuring work. 🙈 On the bright side, at least the conceptual model of the code nouns matches the conceptual model of the docs!
