### ISSUE TITLE
Implement `AS JSON` output format

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#13730]
### Tasks

- [x] Figure out how to represent rows. (https://github.com/MaterializeInc/materialize/pull/14026)
- [x] Figure out how to represent scalars. (https://github.com/MaterializeInc/materialize/pull/14026)
- [x] Implement `AS JSON` output format for `HIR`. (https://github.com/MaterializeInc/materialize/pull/14562)
- [x] Implement `AS JSON` output format for `MIR`. (https://github.com/MaterializeInc/materialize/pull/14562)
- [x] Fix `AS JSON` output format for `LIR`. (https://github.com/MaterializeInc/materialize/pull/14562)

### Related
- Related PR that makes `JSON` a more flexible output format for tests: #13238.
