### ISSUE TITLE
cratemap: customer beta

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#1376]
Our goals for the customer beta involve a number of large-scale projects that have the potential to conflict with one another as well as with more routine work. I'm trying to centralize and track the list of these large-scale projects here, so folks can plan accordingly.

Links to specific issues coming shortly.

* [x] **`catalog`**
  * [x] Switch to using [Diesel](https://diesel.rs), so that we can more tightly manage updates to the on-disk format of the catalog. (#1333)
  * [x] Support namespacing with databases and schemas. (#1126)
* [x] **`ccsr`**
* [x] **`comm`**
* [x] **`coord`**
  * [x] Handle runtime errors from dataflows. (#489)
  * [x] Unification of sources, views, sinks, and indexes. (#1348)
* [x] **`dataflow`**
  * [x] Propagate runtime errors from dataflows. (#489)
  * [x] Unification of sources, views, sinks, and indexes. (#1348)
* [x] **`dataflow-bin`**
* [x] **`dataflow-types`**
  * [x] Stabilize the types that get persisted to disk in the catalog. (#1333)
  * [x] Unification of sources, views, sinks, and indexes. (#1348)
* [ ] **`expr`**
  * [x] Add casts to/from string for every data type. (#1378)
  * [ ] Reorganize functions into modules, so that `expr::scalar::func` is not a massive file. (#1379)
* [x] **`interchange`**
  * [x] Add Protobuf decoding support. (#1191)
  * [x] Add Avro encoding support. (#1374)
* [x] **`materialized`**
  * [x] Teach the build script not to rebuild when a test file changes. (This originally looked like it would be a much larger refactor that involved splitting the crate in two.) (#1382)
* [x] **`ore`**
* [x] **`peeker`**
* [x] **`pgwire`**
  * [x] Add SSL support. (#739)
* [x] **`repr`**
  * [x] Learn to decode and encode the textual format for all datums. These are required by a) pgwire, b) the SQL planner, for literal coercion; and c) the expr crate, for evaluating casts to and from strings, so they logically belong in repr. (#1377)
* [x] **`sql`**
  * [x] Handle literal coercions. (#481)
  * [x] Generalize operators and functions, so that type inference/checking is not handcrafted per function/operator. (#1381)
  * [x] Support namespacing with databases and schemas. (#1126)
* [x] **`sqlparser`**
  * [x] Merge into materialize repository. (#1384)
  * [x] Forget how to parse literals, so that `repr` can have that responsibility instead. (#1377)
* [x] **`sqllogictest`**
* [x] **`symbiosis`**
  * [x] Learn to decode intervals and decimals, so we no longer need to depend on the [pginterval](https://github.com/piperRyan/rust-postgres-interval) and [rust_decimal](https://github.com/paupino/rust-decimal) crates, which are both rather spotty and don't support the soon-to-be-released version of the postgres crate. (#1380)
* [x] **`testdrive`**

**Comment by benesch** [comment]
The only remaining work item here is #1379, so closing this out! 🎉
