### ISSUE TITLE
[Epic] SIZE Parameter in CREATE SINK

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#13889]
This is the sink counterpart to #13125. We're splitting the sink side out of #13125, because it overlaps with the ongoing work on sinks in #11503.

The existing [design document](https://www.notion.so/materialize/storaged-sizing-and-pricing-cbc30495a87845fa981432adb97e5ea1) covers both sources and sinks. This epic tracks implementation of the sink side.

### Time Horizon

Small

### Work items

* [x] #15214
  * Add parser and planner support for `WITH (SIZE)` parameter
  * Plumb `SIZE` parameter through to storage host configuration to the storage controller
* [x] #15215
* [x] #15216
* [x] #15310
* [x] #15304
* [x] Testing/QA sign off
* [x] Add documentation

### Related

* Blocked by: ~#13125~, ~#11503~

**Comment by bkirwi** [comment]
I'm not sure if this is tracked elsewhere, but for consistency I think we should also have:
- [ ] `ALTER SINK ... SIZE` support
- [ ] Support the `REMOTE` config for sinks, with the same semantics as sources

**Comment by andrioni** [comment]
Thanks, these were only mentioned in Slack conversations, I've added those (plus updating `mz_sinks` and `SHOW SINKS`) to the main issue!

**Comment by philip-stoev** [comment]
` ALTER SINK ... SIZE` seems to have been implemented, at least there is a test for it. All the stuff in this epic is exercised in some way or another, so I am checking the QA Sign-off box while leaving the Epic open as there are other checkboxes to be checked.

**Comment by benesch** [comment]
Docs were written in #15400, so we can call this one done! 🥳
