### ISSUE TITLE
release: v0.27.0-alpha.6 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#13911]
The following PRs in [`v0.27.0-alpha.6`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.6) require review:
* [x] [#13907 doc/user: clean up last bits of PubNub](https://github.com/MaterializeInc/materialize/pull/13907) (@morsapaes)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`9190192a6` release: v0.27.0-alpha.6](https://github.com/MaterializeInc/materialize/commit/9190192a646b4b2267906c3dc5859765dde5fbda) (@arusahni)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#13876 doc/user: document `CREATE CONNECTION`, pt. II](https://github.com/MaterializeInc/materialize/pull/13876) (@morsapaes)
* [ ] [#13907 doc/user: clean up last bits of PubNub](https://github.com/MaterializeInc/materialize/pull/13907) (@morsapaes)
* [ ] [#13908 compute: only truncate log collections on one worker](https://github.com/MaterializeInc/materialize/pull/13908) (@teskje)
* [ ] [`9190192a6` release: v0.27.0-alpha.6](https://github.com/MaterializeInc/materialize/commit/9190192a646b4b2267906c3dc5859765dde5fbda) (@arusahni)

**Comment by jpepin** [comment]
@arusahni Are we good to close this?

**Comment by arusahni** [comment]
@jpepin we don't merge the cloud release PRs, so I believe so.
