### ISSUE TITLE
[Epic] perf: TPC-H optimization and dataflow

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#14139]
Run TPC-H queries with eye towards optimization and dataflow performance.

### Description

* Optimization
  * Plan quality (analytical assessment)
* Dataflow
  * Execution: one-off, materialized view, materialized view with index
  * How does varying the cluster size impact query performance?

### Steps

- [ ] dataflow: Create playbook for gathering measurements
- [ ] optimization: Identify suboptimal query plans
- [ ] Summarize results in [tracking doc](https://www.notion.so/materialize/TPC-H-Optimization-and-Dataflow-performance-d43aa9cb379d46ccaa0be07e83d658db)

### Discovery

Please update this section with links to issues that were discovered as part of this epic (e.g. an improvement to the optimizer).

* [ ] TBD

### Related

* Cross-cutting benchmarking and performance work in other teams

**Comment by frankmcsherry** [comment]
In case it is helpful, here are notes from a similar exercise for CH-benCHmark: https://github.com/MaterializeInc/materialize/issues/521

**Comment by antiguru** [comment]
Unassigning @vmarcos because this now serves as a tracking ticket and we're not actively spending time on any of the tasks.

**Comment by antiguru** [comment]
Closing because the work has been completed.
