### ISSUE TITLE
release: v0.27.0-alpha.12 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#14152]
No PRs in [`v0.27.0-alpha.12`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.12) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`84f59c1fb` release: v0.27.0-alpha.12](https://github.com/MaterializeInc/materialize/commit/84f59c1fbb00a41a4a839a952accde91a47d529d) (@doy)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#14101 persist: fix "unexpected missing blob" bug](https://github.com/MaterializeInc/materialize/pull/14101) (@danhhz)
* [ ] [#14121 Update guide.md](https://github.com/MaterializeInc/materialize/pull/14121) (@lluki)
* [ ] [#14129 Un-unsafify `CREATE SOURCE ... SIZE`](https://github.com/MaterializeInc/materialize/pull/14129) (@brennanvincent)
* [ ] [`84f59c1fb` release: v0.27.0-alpha.12](https://github.com/MaterializeInc/materialize/commit/84f59c1fbb00a41a4a839a952accde91a47d529d) (@doy)

**Comment by benesch** [comment]
@doy-materialize's commit LGTM.
