### ISSUE TITLE
[Epic] Enable multi-process replicas

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#14255]
Enable multi-process replicas in Materialize Cloud.

## Description

We want to be able to reliably host multi-process replicas in Materialize. For this to happen, we need to have the right integration with Kubernetes, a strategy on version upgrades, and support to reconcile state correctly to enable `environmentd` restarts. At the moment, multi-process replicas work with severe constraints.
* We cannot guarantee graceful version upgrades because Kubernetes does not know that the pods of a multi-process replica are shared-fate.
* We cannot reconcile the state of multi-process clusters after `environmentd` restarts.

## Tasks
* [x] https://github.com/MaterializeInc/materialize/issues/13603
* [ ] https://github.com/MaterializeInc/cloud/issues/3767
* [ ] TODO: Kubernetes integration. Depending on what kind of deployment strategy we chose, we might have follow-up work to integrate the strategy in `environmentd`. File an issue with concrete details onced the the compute and cloud teams align on a strategy.

## Blocked by
* [ ] #13141

## Acceptance criteria

* We can successfully spawn multi-process replicas in Mz cloud.
* We can restart `environmentd` independently.
* ~We can upgrade the binary versions without causing downtime.~

**Comment by benesch** [comment]
I added #13141 as a work item here.

 > We can upgrade the binary versions without causing downtime.

@antiguru I don't think this should be part of the acceptance criteria! We can't upgrade any clusters without downtime right now!

**Comment by antiguru** [comment]
I moved #13141 to a blocker, because this epic should be about enabling multi-process replicas and not specifically about fixing known bugs, but it should result in the same effort. I also removed zero-downtime from the acceptance because it's not related (but this epic might block zero-downtime efforts.)

**Comment by lluki** [comment]
The ComputeCommand dissemination using timely is merged and rehydrates of multi process replicas should work correctly from the compute side again.

**Comment by benesch** [comment]
Can we call this one closed? With #13141 fixed (it's just pending QA approval) and #13603 fixed, I think there's actually no more work to be done here! Multi-process replicas _are_ already enabled on cloud.

https://github.com/MaterializeInc/cloud/issues/3767 is still outstanding, of course, but we can track that as a separate work item.

**Comment by antiguru** [comment]
Yes, we can track QA separately. Thanks everyone for their efforts!
