### ISSUE TITLE
release: v0.27.0-alpha.14 required reviews

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#14362]
The following PRs in [`v0.27.0-alpha.14`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.14) require review:
* [ ] [#14256 platform checks: Add table-based sinks](https://github.com/MaterializeInc/materialize/pull/14256) (@philip-stoev)
* [ ] [#14269 Fix nightly role.td test](https://github.com/MaterializeInc/materialize/pull/14269) (@jkosh44)
* [ ] [#14274 ci: Add missing depends_on directives to the checks jobs](https://github.com/MaterializeInc/materialize/pull/14274) (@philip-stoev)
* [ ] [#14276 zippy: Add sinks over user tables](https://github.com/MaterializeInc/materialize/pull/14276) (@philip-stoev)
* [ ] [#14278 limits test: Adjust the timeout for the ViewsMaterializedNested scenario](https://github.com/MaterializeInc/materialize/pull/14278) (@philip-stoev)
* [ ] [#14285 doc/user: point Get Started callout to `/unstable`](https://github.com/MaterializeInc/materialize/pull/14285) (@morsapaes)
* [ ] [#14288 doc/user: hide, remove and shuffle pages around](https://github.com/MaterializeInc/materialize/pull/14288) (@morsapaes)
* [ ] [#14299 cloudtest: Move to the default CI pipeline](https://github.com/MaterializeInc/materialize/pull/14299) (@philip-stoev)
* [ ] [#14300 limits test: Tone down the 'instance size' workflow](https://github.com/MaterializeInc/materialize/pull/14300) (@philip-stoev)
* [ ] [#14318 test: fix syntax errors in test/cloudtest/test_secrets.py](https://github.com/MaterializeInc/materialize/pull/14318) (@sploiselle)
* [ ] [#14326 doc/developer: fix heading formatting in fast-compiles.md](https://github.com/MaterializeInc/materialize/pull/14326) (@teskje)
* [ ] [#14343 persist: add metric to track number of live updates in a shard](https://github.com/MaterializeInc/materialize/pull/14343) (@danhhz)
* [ ] [#14345 [avro] Fix busted PCF logic](https://github.com/MaterializeInc/materialize/pull/14345) (@brennanvincent)
* [ ] [#14357 cloudtest: remove CONNECTION references from SOURCEs](https://github.com/MaterializeInc/materialize/pull/14357) (@sploiselle)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`317dfbea3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/317dfbea3100255301968a86b3de3173a0c92e04) (UNKNOWN COMMITTER!)
* [ ] [`240c42c62` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/240c42c629e95256f85766faaceda7429b5d9184) (UNKNOWN COMMITTER!)
* [ ] [`e6c0fe31e` doc/user: fix documentation logo link](https://github.com/MaterializeInc/materialize/commit/e6c0fe31eadfbe888994b2f9c2f017c6869ab033) (@benesch)
* [ ] [`f54c11098` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f54c11098a78aaa27fa447470dbfd2729155f002) (UNKNOWN COMMITTER!)
* [ ] [`fd04d53a1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fd04d53a13fecc658bb98f14ac47a4722cef6943) (UNKNOWN COMMITTER!)
* [ ] [`1cca1dc8c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1cca1dc8c35486502c5f1b8014790c5fe7c3a0e9) (UNKNOWN COMMITTER!)
* [ ] [`feb399bf8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/feb399bf8add59898c2df05a73ac681dce4316a5) (UNKNOWN COMMITTER!)
* [ ] [`0c39397a5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0c39397a5c4f9993a4cfeebb845005d8c0be4c1d) (UNKNOWN COMMITTER!)
* [ ] [`81dc08472` release: v0.27.0-alpha.14](https://github.com/MaterializeInc/materialize/commit/81dc0847232f0a73b2ee7e5ba5e0967be2f80745) (@alex-hunt-materialize)

**Comment by benesch** [comment]
All PRs and unassociated commits:

* [ ] [#14252 doc/user: unstable docs more apparent, less threatening](https://github.com/MaterializeInc/materialize/pull/14252) (@ruf-io)
* [ ] [#14257 storage: allow all storage collections to be written to a Sink](https://github.com/MaterializeInc/materialize/pull/14257) (@aljoscha)
* [ ] [#14256 platform checks: Add table-based sinks](https://github.com/MaterializeInc/materialize/pull/14256) (@philip-stoev)
* [ ] [#14249 storage: thread worker count config through to K8s command](https://github.com/MaterializeInc/materialize/pull/14249) (@bkirwi)
* [ ] [#14262 environmentd: Fix connection ID allocation](https://github.com/MaterializeInc/materialize/pull/14262) (@jkosh44)
* [ ] [#14259 sql-parser: remove old CONSISTENCY syntax from CREATE SINK](https://github.com/MaterializeInc/materialize/pull/14259) (@aljoscha)
* [ ] [#14263 storage: replace dropped ReadHandles in PersistWorker with placeholder](https://github.com/MaterializeInc/materialize/pull/14263) (@danhhz)
* [ ] [#14219 persist: use new state before expiring leases and reporting metrics](https://github.com/MaterializeInc/materialize/pull/14219) (@pH14)
* [ ] [#14269 Fix nightly role.td test](https://github.com/MaterializeInc/materialize/pull/14269) (@jkosh44)
* [ ] [#14254 persist: panic on missing blob](https://github.com/MaterializeInc/materialize/pull/14254) (@pH14)
* [ ] [#14193 catalog: Limit resource creation with sys config](https://github.com/MaterializeInc/materialize/pull/14193) (@jkosh44)
* [ ] [#14270 Optimization: fix unique key calculation error](https://github.com/MaterializeInc/materialize/pull/14270) (@wangandi)
* [ ] [#14274 ci: Add missing depends_on directives to the checks jobs](https://github.com/MaterializeInc/materialize/pull/14274) (@philip-stoev)
* [ ] [#14247 Revert the removal of the literal constraints detection code in lowering](https://github.com/MaterializeInc/materialize/pull/14247) (@ggevay)
* [ ] [#14276 zippy: Add sinks over user tables](https://github.com/MaterializeInc/materialize/pull/14276) (@philip-stoev)
* [ ] [#14258 Decompose record in `Literal(record(c1, c2)) = record_create(e1, e2)`](https://github.com/MaterializeInc/materialize/pull/14258) (@ggevay)
* [ ] [#14278 limits test: Adjust the timeout for the ViewsMaterializedNested scenario](https://github.com/MaterializeInc/materialize/pull/14278) (@philip-stoev)
* [ ] [#14155 persist: add writer leases](https://github.com/MaterializeInc/materialize/pull/14155) (@pH14)
* [ ] [#14210 Implement explode_one to consolidate explosions](https://github.com/MaterializeInc/materialize/pull/14210) (@antiguru)
* [ ] [#14213 Avoid ArrangeBySelf in reductions](https://github.com/MaterializeInc/materialize/pull/14213) (@antiguru)
* [ ] [#14271 adapter: process stash consolidations out of user request path](https://github.com/MaterializeInc/materialize/pull/14271) (@mjibson)
* [ ] [#14277 Ensure that there are no redundant concatenate operators in rendered reductions](https://github.com/MaterializeInc/materialize/pull/14277) (@vmarcos)
* [ ] [#14279 Indexed vs. Non-Indexed optbench runs for TPC-H queries](https://github.com/MaterializeInc/materialize/pull/14279) (@vmarcos)
* [ ] [#13952 persist: add a long-lived listener to txn-list-append maelstrom impl](https://github.com/MaterializeInc/materialize/pull/13952) (@danhhz)
* [ ] [#14284 dbt-materialize: release v1.1.3](https://github.com/MaterializeInc/materialize/pull/14284) (@morsapaes)
* [ ] [#14285 doc/user: point Get Started callout to `/unstable`](https://github.com/MaterializeInc/materialize/pull/14285) (@morsapaes)
* [ ] [#14081 adapter+repr: tidy up Datum -> json conversion](https://github.com/MaterializeInc/materialize/pull/14081) (@sploiselle)
* [ ] [#14280 adapter: temporarily disable source status collection](https://github.com/MaterializeInc/materialize/pull/14280) (@benesch)
* [ ] [#14189 Assert that only single node replicas use reconciliation](https://github.com/MaterializeInc/materialize/pull/14189) (@lluki)
* [ ] [#14033 adapter: implement `EXPLAIN ... AS TEXT` for `Mir` plans](https://github.com/MaterializeInc/materialize/pull/14033) (@aalexandrov)
* [ ] [#14282 catalog: Add more columns to pg_roles](https://github.com/MaterializeInc/materialize/pull/14282) (@jkosh44)
* [ ] [#14288 doc/user: hide, remove and shuffle pages around](https://github.com/MaterializeInc/materialize/pull/14288) (@morsapaes)
* [ ] [#14299 cloudtest: Move to the default CI pipeline](https://github.com/MaterializeInc/materialize/pull/14299) (@philip-stoev)
* [ ] [#14300 limits test: Tone down the 'instance size' workflow](https://github.com/MaterializeInc/materialize/pull/14300) (@philip-stoev)
* [ ] [#14286 adapter: align fast and slow path output for `EXPLAIN ... AS TEXT`](https://github.com/MaterializeInc/materialize/pull/14286) (@aalexandrov)
* [ ] [#13665 S3 connection](https://github.com/MaterializeInc/materialize/pull/13665) (@sploiselle)
* [ ] [#14289 persist: shoring up missing blobs from FileBlob](https://github.com/MaterializeInc/materialize/pull/14289) (@pH14)
* [ ] [#14306 sql: Fix overflow when negating min ints](https://github.com/MaterializeInc/materialize/pull/14306) (@jkosh44)
* [ ] [#14214 sql: require CONNECTION when creating SINK](https://github.com/MaterializeInc/materialize/pull/14214) (@sploiselle)
* [ ] [#14268 persist: rename mod r#impl to internal](https://github.com/MaterializeInc/materialize/pull/14268) (@danhhz)
* [ ] [#14309 sql: deprecate consistency_topic option for sinks](https://github.com/MaterializeInc/materialize/pull/14309) (@sploiselle)
* [ ] [#14318 test: fix syntax errors in test/cloudtest/test_secrets.py](https://github.com/MaterializeInc/materialize/pull/14318) (@sploiselle)
* [ ] [#14326 doc/developer: fix heading formatting in fast-compiles.md](https://github.com/MaterializeInc/materialize/pull/14326) (@teskje)
* [ ] [#13978 build(deps): bump tracing from 0.1.35 to 0.1.36](https://github.com/MaterializeInc/materialize/pull/13978) (@dependabot[bot])
* [ ] [#14305 sql: guard fallible cast expression](https://github.com/MaterializeInc/materialize/pull/14305) (@petrosagg)
* [ ] [#14283 Convert missing-id error to something more helpful](https://github.com/MaterializeInc/materialize/pull/14283) (@bkirwi)
* [ ] [#14332 persist: return err rather than panic if compaction sees missing blob](https://github.com/MaterializeInc/materialize/pull/14332) (@pH14)
* [ ] [#14329 build(deps): bump either from 1.7.0 to 1.8.0](https://github.com/MaterializeInc/materialize/pull/14329) (@dependabot[bot])
* [ ] [#14090 build(deps): bump proc-macro2 from 1.0.40 to 1.0.43](https://github.com/MaterializeInc/materialize/pull/14090) (@dependabot[bot])
* [ ] [#14328 info-level logging of persist reader and writer actions](https://github.com/MaterializeInc/materialize/pull/14328) (@pH14)
* [ ] [#14260 [WIP] Extend generator trait to return batches of rows at the same logical offset](https://github.com/MaterializeInc/materialize/pull/14260) (@sjwiesman)
* [ ] [#14316 expr: Have methods that calculate the type of scalar take the argument &[ColumnType].](https://github.com/MaterializeInc/materialize/pull/14316) (@wangandi)
* [ ] [#14340 persist: remove pub from maybe_heartbeat_reader](https://github.com/MaterializeInc/materialize/pull/14340) (@danhhz)
* [ ] [#14343 persist: add metric to track number of live updates in a shard](https://github.com/MaterializeInc/materialize/pull/14343) (@danhhz)
* [ ] [#14344 [avro] Use short names whenever possible](https://github.com/MaterializeInc/materialize/pull/14344) (@brennanvincent)
* [ ] [#14331 doc add ACLs step to MSK guide](https://github.com/MaterializeInc/materialize/pull/14331) (@bobbyiliev)
* [ ] [#14310 Maintain introspection upper frontiers across restarts](https://github.com/MaterializeInc/materialize/pull/14310) (@frankmcsherry)
* [ ] [#14345 [avro] Fix busted PCF logic](https://github.com/MaterializeInc/materialize/pull/14345) (@brennanvincent)
* [ ] [#14317 sql: move common Kafka config option next to CONNECTION reference](https://github.com/MaterializeInc/materialize/pull/14317) (@sploiselle)
* [ ] [#14169 Compiling a literal constraint into a join](https://github.com/MaterializeInc/materialize/pull/14169) (@ggevay)
* [ ] [#14308 coord: ensure secrets' bytes can be cast to strings](https://github.com/MaterializeInc/materialize/pull/14308) (@sploiselle)
* [ ] [#14348 compute: retain logging sinks during reconciliation](https://github.com/MaterializeInc/materialize/pull/14348) (@teskje)
* [ ] [#14354 Correct botched rebase](https://github.com/MaterializeInc/materialize/pull/14354) (@ggevay)
* [ ] [#14357 cloudtest: remove CONNECTION references from SOURCEs](https://github.com/MaterializeInc/materialize/pull/14357) (@sploiselle)
* [ ] [`317dfbea3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/317dfbea3100255301968a86b3de3173a0c92e04) (UNKNOWN COMMITTER!)
* [ ] [`240c42c62` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/240c42c629e95256f85766faaceda7429b5d9184) (UNKNOWN COMMITTER!)
* [ ] [`e6c0fe31e` doc/user: fix documentation logo link](https://github.com/MaterializeInc/materialize/commit/e6c0fe31eadfbe888994b2f9c2f017c6869ab033) (@benesch)
* [ ] [`f54c11098` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f54c11098a78aaa27fa447470dbfd2729155f002) (UNKNOWN COMMITTER!)
* [ ] [`fd04d53a1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fd04d53a13fecc658bb98f14ac47a4722cef6943) (UNKNOWN COMMITTER!)
* [ ] [`1cca1dc8c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1cca1dc8c35486502c5f1b8014790c5fe7c3a0e9) (UNKNOWN COMMITTER!)
* [ ] [`feb399bf8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/feb399bf8add59898c2df05a73ac681dce4316a5) (UNKNOWN COMMITTER!)
* [ ] [`0c39397a5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0c39397a5c4f9993a4cfeebb845005d8c0be4c1d) (UNKNOWN COMMITTER!)
* [ ] [`81dc08472` release: v0.27.0-alpha.14](https://github.com/MaterializeInc/materialize/commit/81dc0847232f0a73b2ee7e5ba5e0967be2f80745) (@alex-hunt-materialize)

**Comment by alex-hunt-materialize** [comment]
They all LGTM.

**Comment by antifuchs** [comment]
81dc08472 LGTM too (:
