### ISSUE TITLE
[Epic] Reliable network fabric for Timely

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#14377]
Timely dataflow has a TCP-based network fabric. It either initializes its own sockets, or takes prefabricated sockets on initialization. However, there is no mechanism to re-initialize sockets while a Timely cluster is running. At the moment, terminating one connection results in the cluster terminating.

A reliable transport fabric is important to enable active replication and high-availability for Materialize. We have anecdotal evidence that connection problems are correlated, which means that not only a single cluster might go down, but many simultaneously.

## Goals

* Introduce a networking fabric for Timely that is resilient to temporary connection loss.

## Non-goals

* Dynamic sizing of Timely clusters

## Acceptance criteria

Multi-process replica can survive temporary network interruptions.

## Subtasks

* [ ] Design a mechanism that would allow compute processes to re-establish connections on the Timely fabric.
* [ ] Implement the mechanism.
  * [ ] Changes required in Timely. A design goal is to change the Timely implementation as little as possible, only to provide the interfaces required for Materialize to implement a policy.
  * [ ] Implement a policy and mechanism in Materialize.

## Testing

* [ ] Create a test that severs the connection between processes of a multi-process replica and let the recovery mechanism do its work.

## Related

* https://github.com/TimelyDataflow/timely-dataflow/issues/386
