### ISSUE TITLE
release: v0.27.0-alpha.15 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#14371]
The following PRs in [`v0.27.0-alpha.15`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.15) require review:
* [ ] [#14365 ci/license: fix email address for materializer account](https://github.com/MaterializeInc/materialize/pull/14365) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`b5bd6646f` release: v0.27.0-alpha.15](https://github.com/MaterializeInc/materialize/commit/b5bd6646fca1b0363056e602659f168d71502818) (@alex-hunt-materialize)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#14064 persist: consolidate pending gc requests per handle](https://github.com/MaterializeInc/materialize/pull/14064) (@pH14)
* [ ] [#14361 Refresh DD to pick up `until` frontier](https://github.com/MaterializeInc/materialize/pull/14361) (@frankmcsherry)
* [ ] [#14365 ci/license: fix email address for materializer account](https://github.com/MaterializeInc/materialize/pull/14365) (@benesch)
* [ ] [#14367 sql: remove unsafe_mode from KAFKA..CONNECTION](https://github.com/MaterializeInc/materialize/pull/14367) (@sploiselle)
* [ ] [`b5bd6646f` release: v0.27.0-alpha.15](https://github.com/MaterializeInc/materialize/commit/b5bd6646fca1b0363056e602659f168d71502818) (@alex-hunt-materialize)

**Comment by alex-hunt-materialize** [comment]
https://github.com/MaterializeInc/materialize/pull/14365 LGTM

**Comment by benesch** [comment]
Alex's commit LGTM too.
