### ISSUE TITLE
release: v0.27.0-alpha.16 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#14522]
The following PRs in [`v0.27.0-alpha.16`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.16) require review:
* [x] [#14381 doc/user: adapt documentation to nu-materialized views, pt. II](https://github.com/MaterializeInc/materialize/pull/14381) (@morsapaes)
* [x] [#14404 Update command-and-response-binary-encoding.md](https://github.com/MaterializeInc/materialize/pull/14404) (@aalexandrov)
* [x] [#14427 ci/builder: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14427) (@benesch)
* [x] [#14462 environmentd: bump pgtest timeout more](https://github.com/MaterializeInc/materialize/pull/14462) (@mjibson)
* [x] [#14448 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14448) (@benesch)
* [x] [#14481 deps: switch from `sha-1` to `sha1`](https://github.com/MaterializeInc/materialize/pull/14481) (@benesch)
* [ ] [#14482 cloudtest: Fix test_secrets.py](https://github.com/MaterializeInc/materialize/pull/14482) (@philip-stoev)
* [x] [#14483 zippy: Increase the timeout for the UserTables scenario](https://github.com/MaterializeInc/materialize/pull/14483) (@philip-stoev)
* [x] [#14484 limits test: Fix syntax errors](https://github.com/MaterializeInc/materialize/pull/14484) (@philip-stoev)
* [x] [#14197 Implement SSH tunnels for Postgres connections](https://github.com/MaterializeInc/materialize/pull/14197) (@andrioni)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`60591a68b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/60591a68bb30be8ecfc7e666aec641bdd4f13d03) (@materializer)
* [x] [`3e741f13f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3e741f13f99fff925991d13b8f906126c51810d3) (@materializer)
* [x] [`78045dc54` Correct name of client_builder in computed](https://github.com/MaterializeInc/materialize/commit/78045dc5408353ff19ef230f6ecbc3fd6f543972) (@brennanvincent)
* [x] [`ebf054648` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ebf05464865f0782cd7da4e4a781c78ecc081e2e) (@materializer)
* [x] [`45802286b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/45802286b697feb1205911543abc62c640ad63f6) (@materializer)
* [x] [`88fb72bb6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/88fb72bb60e49848ed19536a6a17d6df9bac5490) (@materializer)
* [x] [`a6a202489` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a6a202489e465003e2f7bc7f9fdf952a939501b6) (@materializer)
* [x] [`d6f35ce35` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d6f35ce35763ee6dd582d5647002b3fd423aa309) (@materializer)
* [x] [`3e400a919` release: v0.27.0-alpha.16](https://github.com/MaterializeInc/materialize/commit/3e400a919d0e7f11dae7bd70968dfa5fbe8a39cc) (@arusahni)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#14337 build(deps): bump axum from 0.5.13 to 0.5.15](https://github.com/MaterializeInc/materialize/pull/14337) (@dependabot[bot])
* [ ] [#14373 build(deps): bump paste from 1.0.7 to 1.0.8](https://github.com/MaterializeInc/materialize/pull/14373) (@dependabot[bot])
* [ ] [#14350 adapter,compute: remove undocumented mz_perf views](https://github.com/MaterializeInc/materialize/pull/14350) (@benesch)
* [ ] [#14303 adapter: partially implement `EXPLAIN AS TEXT` for LIR](https://github.com/MaterializeInc/materialize/pull/14303) (@aalexandrov)
* [ ] [#14380 Simplify PartialOrder::less_than invocations](https://github.com/MaterializeInc/materialize/pull/14380) (@teskje)
* [ ] [#14375 storage: remove some derived arbitrary implementations](https://github.com/MaterializeInc/materialize/pull/14375) (@benesch)
* [ ] [#14334 Add all objects that have a GlobalId and SchemaId to mz_objects](https://github.com/MaterializeInc/materialize/pull/14334) (@chaas)
* [ ] [#14381 doc/user: adapt documentation to nu-materialized views, pt. II](https://github.com/MaterializeInc/materialize/pull/14381) (@morsapaes)
* [ ] [#14223 build(deps): bump clap from 3.2.14 to 3.2.17](https://github.com/MaterializeInc/materialize/pull/14223) (@dependabot[bot])
* [ ] [#14298 stash: switch serialization to JSON](https://github.com/MaterializeInc/materialize/pull/14298) (@mjibson)
* [ ] [#14148 [sources] Support for ALTER SOURCE to change the configuration of the backing storaged](https://github.com/MaterializeInc/materialize/pull/14148) (@bkirwi)
* [ ] [#14177 storage: use all Timely workers when performing reads from persist](https://github.com/MaterializeInc/materialize/pull/14177) (@sploiselle)
* [ ] [#14383 CI: Fix "Join Slack" Redirect](https://github.com/MaterializeInc/materialize/pull/14383) (@ruf-io)
* [ ] [#13984 build(deps): bump ctor from 0.1.22 to 0.1.23](https://github.com/MaterializeInc/materialize/pull/13984) (@dependabot[bot])
* [ ] [#13987 build(deps): bump bytes from 1.2.0 to 1.2.1](https://github.com/MaterializeInc/materialize/pull/13987) (@dependabot[bot])
* [ ] [#14364 Use a unique producer ID](https://github.com/MaterializeInc/materialize/pull/14364) (@bkirwi)
* [ ] [#14304 sql: Add unsigned int types](https://github.com/MaterializeInc/materialize/pull/14304) (@jkosh44)
* [ ] [#14386 build(deps): bump ryu from 1.0.10 to 1.0.11](https://github.com/MaterializeInc/materialize/pull/14386) (@dependabot[bot])
* [ ] [#14091 build(deps): bump arrow2 from 0.12.0 to 0.13.1](https://github.com/MaterializeInc/materialize/pull/14091) (@dependabot[bot])
* [ ] [#14108 build(deps): bump ubuntu from jammy-20220531 to jammy-20220801 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14108) (@dependabot[bot])
* [ ] [#14393 [sources] WITH TIMELINE](https://github.com/MaterializeInc/materialize/pull/14393) (@bkirwi)
* [ ] [#14404 Update command-and-response-binary-encoding.md](https://github.com/MaterializeInc/materialize/pull/14404) (@aalexandrov)
* [ ] [#14405 storage: clean up requirements on storage timestamp types](https://github.com/MaterializeInc/materialize/pull/14405) (@petrosagg)
* [ ] [#14402 compute: remove remnants of Kafka sinks](https://github.com/MaterializeInc/materialize/pull/14402) (@teskje)
* [ ] [#14388 Advance timeline when we create a table](https://github.com/MaterializeInc/materialize/pull/14388) (@frankmcsherry)
* [ ] [#14410 build(deps): bump time from 0.3.11 to 0.3.14](https://github.com/MaterializeInc/materialize/pull/14410) (@dependabot[bot])
* [ ] [#14409 sql: Add arithmetic operaotrs for unsigned ints](https://github.com/MaterializeInc/materialize/pull/14409) (@jkosh44)
* [ ] [#14366 storage: move start_offset and kafka_time_offset out of legacy with_options](https://github.com/MaterializeInc/materialize/pull/14366) (@guswynn)
* [ ] [#14387 catalog: Add unsigned ints to builtin tables](https://github.com/MaterializeInc/materialize/pull/14387) (@jkosh44)
* [ ] [#14416 storage: parse legacy with options with LEGACYWITH](https://github.com/MaterializeInc/materialize/pull/14416) (@guswynn)
* [ ] [#14363 Explain: Add arity and column type attributes.](https://github.com/MaterializeInc/materialize/pull/14363) (@wangandi)
* [ ] [#14250 persist: commit state updates to durable storage incrementally](https://github.com/MaterializeInc/materialize/pull/14250) (@danhhz)
* [ ] [#14415 doc/user: Update DocSearch to V3](https://github.com/MaterializeInc/materialize/pull/14415) (@ruf-io)
* [ ] [#14420 Update doc explaining justification for lack of jemalloc on macOS.](https://github.com/MaterializeInc/materialize/pull/14420) (@brennanvincent)
* [ ] [#14418 Update a doccomment for accuracy](https://github.com/MaterializeInc/materialize/pull/14418) (@brennanvincent)
* [ ] [#14419 catalog: Add unsigned ints to builtin tables](https://github.com/MaterializeInc/materialize/pull/14419) (@jkosh44)
* [ ] [#12109 Source ingestion pipeline recipe](https://github.com/MaterializeInc/materialize/pull/12109) (@frankmcsherry)
* [ ] [#14422 sql: WITH (timestamp_frequency ... ) => WITH (TIMESTAMP GRANULARITY ...)](https://github.com/MaterializeInc/materialize/pull/14422) (@benesch)
* [ ] [#13983 build(deps): bump indicatif from 0.16.2 to 0.17.0](https://github.com/MaterializeInc/materialize/pull/13983) (@dependabot[bot])
* [ ] [#14320 build(deps): bump sysinfo from 0.24.7 to 0.25.3](https://github.com/MaterializeInc/materialize/pull/14320) (@dependabot[bot])
* [ ] [#14117 build(deps): bump ubuntu from jammy-20220531 to jammy-20220801 in /misc/images/ubuntu-base](https://github.com/MaterializeInc/materialize/pull/14117) (@dependabot[bot])
* [ ] [#14374 build(deps): bump futures-util from 0.3.21 to 0.3.23](https://github.com/MaterializeInc/materialize/pull/14374) (@dependabot[bot])
* [ ] [#14426 build(deps): bump similar from 2.1.0 to 2.2.0](https://github.com/MaterializeInc/materialize/pull/14426) (@dependabot[bot])
* [ ] [#14382 build(deps): bump phf from 0.11.0 to 0.11.1](https://github.com/MaterializeInc/materialize/pull/14382) (@dependabot[bot])
* [ ] [#14395 build(deps): bump libc from 0.2.126 to 0.2.132](https://github.com/MaterializeInc/materialize/pull/14395) (@dependabot[bot])
* [ ] [#14427 ci/builder: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14427) (@benesch)
* [ ] [#14433 sql: convert the next batch of enum options](https://github.com/MaterializeInc/materialize/pull/14433) (@benesch)
* [ ] [#14423 adapter,compute,storage: rename GRANULARITY to INTERVAL](https://github.com/MaterializeInc/materialize/pull/14423) (@benesch)
* [ ] [#14428 build(deps): bump os_info from 3.4.0 to 3.5.0](https://github.com/MaterializeInc/materialize/pull/14428) (@dependabot[bot])
* [ ] [#14431 build(deps): bump enum-iterator from 1.1.3 to 1.2.0](https://github.com/MaterializeInc/materialize/pull/14431) (@dependabot[bot])
* [ ] [#14432 build(deps): bump syn from 1.0.98 to 1.0.99](https://github.com/MaterializeInc/materialize/pull/14432) (@dependabot[bot])
* [ ] [#14368 Allow SELECT queries to execute on time-bounded dataflows](https://github.com/MaterializeInc/materialize/pull/14368) (@frankmcsherry)
* [ ] [#14450 sql-parser: fix merge skew](https://github.com/MaterializeInc/materialize/pull/14450) (@aljoscha)
* [ ] [#14452 persist: flatten snapshot LeasedBatches into parts](https://github.com/MaterializeInc/materialize/pull/14452) (@danhhz)
* [ ] [#14355  storage: distribute source work across all timely workers](https://github.com/MaterializeInc/materialize/pull/14355) (@aljoscha)
* [ ] [#14454 Correct the testdrive regex docs](https://github.com/MaterializeInc/materialize/pull/14454) (@bkirwi)
* [ ] [#14453 sql: remove AS OF from CREATE SINK](https://github.com/MaterializeInc/materialize/pull/14453) (@sploiselle)
* [ ] [#14458 doc/user: document that OFFSET and LIMIT must be constants](https://github.com/MaterializeInc/materialize/pull/14458) (@benesch)
* [ ] [#14353 Detect an OR of literal constraints](https://github.com/MaterializeInc/materialize/pull/14353) (@ggevay)
* [ ] [#14403 Literal constraints -- support multiple lookups on fast path](https://github.com/MaterializeInc/materialize/pull/14403) (@ggevay)
* [ ] [#14457 sql: modularize KafkaConfigOptionExtracted access](https://github.com/MaterializeInc/materialize/pull/14457) (@sploiselle)
* [ ] [#14466 Fix NonNegative attribute on constant collections](https://github.com/MaterializeInc/materialize/pull/14466) (@ggevay)
* [ ] [#14462 environmentd: bump pgtest timeout more](https://github.com/MaterializeInc/materialize/pull/14462) (@mjibson)
* [ ] [#14447 build(deps): bump semver from 1.0.12 to 1.0.13](https://github.com/MaterializeInc/materialize/pull/14447) (@dependabot[bot])
* [ ] [#14446 build(deps): bump pin-project from 1.0.11 to 1.0.12](https://github.com/MaterializeInc/materialize/pull/14446) (@dependabot[bot])
* [ ] [#14430 build(deps): bump sysctl from 0.4.4 to 0.4.6](https://github.com/MaterializeInc/materialize/pull/14430) (@dependabot[bot])
* [ ] [#14429 build(deps): bump async-trait from 0.1.56 to 0.1.57](https://github.com/MaterializeInc/materialize/pull/14429) (@dependabot[bot])
* [ ] [#14448 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14448) (@benesch)
* [ ] [#14470 build(deps): bump thiserror from 1.0.31 to 1.0.32](https://github.com/MaterializeInc/materialize/pull/14470) (@dependabot[bot])
* [ ] [#14469 build(deps): bump futures from 0.3.21 to 0.3.23](https://github.com/MaterializeInc/materialize/pull/14469) (@dependabot[bot])
* [ ] [#14406 all: remove unused deps from Cargo.toml files](https://github.com/MaterializeInc/materialize/pull/14406) (@petrosagg)
* [ ] [#14476 build(deps): bump sysctl from 0.4.6 to 0.5.2](https://github.com/MaterializeInc/materialize/pull/14476) (@dependabot[bot])
* [ ] [#14468 build(deps): bump quote from 1.0.20 to 1.0.21](https://github.com/MaterializeInc/materialize/pull/14468) (@dependabot[bot])
* [ ] [#14445 build(deps): bump serde from 1.0.140 to 1.0.144](https://github.com/MaterializeInc/materialize/pull/14445) (@dependabot[bot])
* [ ] [#14478 build(deps): bump anyhow from 1.0.58 to 1.0.62](https://github.com/MaterializeInc/materialize/pull/14478) (@dependabot[bot])
* [ ] [#14471 build(deps): bump once_cell from 1.13.0 to 1.13.1](https://github.com/MaterializeInc/materialize/pull/14471) (@dependabot[bot])
* [ ] [#14475 build(deps): bump boto3 from 1.24.60 to 1.24.61 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14475) (@dependabot[bot])
* [ ] [#14338 build(deps): bump chrono from 0.4.19 to 0.4.20](https://github.com/MaterializeInc/materialize/pull/14338) (@dependabot[bot])
* [ ] [#13896 build(deps): update dbt-postgres requirement from ~=1.1.0 to >=1.1,<1.3 in /misc/dbt-materialize](https://github.com/MaterializeInc/materialize/pull/13896) (@dependabot[bot])
* [ ] [#14233 build(deps): bump prost-reflect from 0.8.1 to 0.9.2](https://github.com/MaterializeInc/materialize/pull/14233) (@dependabot[bot])
* [ ] [#14481 deps: switch from `sha-1` to `sha1`](https://github.com/MaterializeInc/materialize/pull/14481) (@benesch)
* [ ] [#14414 build(deps): bump nix from 0.24.2 to 0.25.0](https://github.com/MaterializeInc/materialize/pull/14414) (@dependabot[bot])
* [ ] [#14477 build(deps): bump serde_json from 1.0.82 to 1.0.85](https://github.com/MaterializeInc/materialize/pull/14477) (@dependabot[bot])
* [ ] [#14482 cloudtest: Fix test_secrets.py](https://github.com/MaterializeInc/materialize/pull/14482) (@philip-stoev)
* [ ] [#14483 zippy: Increase the timeout for the UserTables scenario](https://github.com/MaterializeInc/materialize/pull/14483) (@philip-stoev)
* [ ] [#14302 cloudtest: Introduce scenarios around killing compute clusters](https://github.com/MaterializeInc/materialize/pull/14302) (@philip-stoev)
* [ ] [#14484 limits test: Fix syntax errors](https://github.com/MaterializeInc/materialize/pull/14484) (@philip-stoev)
* [ ] [#14464 Don't generate empty literal_constraints in Arbitrary Peek](https://github.com/MaterializeInc/materialize/pull/14464) (@ggevay)
* [ ] [#14486 nix: add a flake.nix with a devshell that delegates to shell.nix](https://github.com/MaterializeInc/materialize/pull/14486) (@aljoscha)
* [ ] [#14455 Set a standard indent for .td files](https://github.com/MaterializeInc/materialize/pull/14455) (@bkirwi)
* [ ] [#14339 [sinks] Remove the old reuse-topic option](https://github.com/MaterializeInc/materialize/pull/14339) (@bkirwi)
* [ ] [#14492 persist: temporarily disable StateDiff::validate_roundtrip](https://github.com/MaterializeInc/materialize/pull/14492) (@danhhz)
* [ ] [#14491 compute,storage: disable spurious tonic recompiles](https://github.com/MaterializeInc/materialize/pull/14491) (@benesch)
* [ ] [#14495 adapter: Require unsafe mode for all index opts](https://github.com/MaterializeInc/materialize/pull/14495) (@jkosh44)
* [ ] [#14421 storage: add a pg snapshot recoverable failure test](https://github.com/MaterializeInc/materialize/pull/14421) (@guswynn)
* [ ] [#14465 Decompose `record_create(...) = record_create(...)`](https://github.com/MaterializeInc/materialize/pull/14465) (@ggevay)
* [ ] [#14413 pgwire: separate ExecuteResponse tags+non-fatal errors from sending them](https://github.com/MaterializeInc/materialize/pull/14413) (@sploiselle)
* [ ] [#14489 lower log level of global id / persist shard id mapping](https://github.com/MaterializeInc/materialize/pull/14489) (@pH14)
* [ ] [#14497 persist: use columnar format for ProtoStateFieldDiffs](https://github.com/MaterializeInc/materialize/pull/14497) (@danhhz)
* [ ] [#14503 deps: swap sha-1 for sha1 in transitive dependency graph](https://github.com/MaterializeInc/materialize/pull/14503) (@benesch)
* [ ] [#14460 Rename `mz_dataflow_names` -> `mz_dataflows`](https://github.com/MaterializeInc/materialize/pull/14460) (@chaas)
* [ ] [#14502 adapter: Convert system config to unsigned ints](https://github.com/MaterializeInc/materialize/pull/14502) (@jkosh44)
* [ ] [#14197 Implement SSH tunnels for Postgres connections](https://github.com/MaterializeInc/materialize/pull/14197) (@andrioni)
* [ ] [#14467 sql: Mandate CSR connections use `CONNECTION`](https://github.com/MaterializeInc/materialize/pull/14467) (@sploiselle)
* [ ] [#14378 Non-differential FrontierUppers](https://github.com/MaterializeInc/materialize/pull/14378) (@teskje)
* [ ] [#14451 Tighten compute controller public API](https://github.com/MaterializeInc/materialize/pull/14451) (@teskje)
* [ ] [#14408 compute-client: remove DataflowDescription::id](https://github.com/MaterializeInc/materialize/pull/14408) (@teskje)
* [ ] [#14514 storage: in errors.proto, fix whitespace](https://github.com/MaterializeInc/materialize/pull/14514) (@aljoscha)
* [ ] [#14118 Cli general usage improvements](https://github.com/MaterializeInc/materialize/pull/14118) (@joacoc)
* [ ] [`60591a68b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/60591a68bb30be8ecfc7e666aec641bdd4f13d03) (@materializer)
* [ ] [`3e741f13f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3e741f13f99fff925991d13b8f906126c51810d3) (@materializer)
* [ ] [`78045dc54` Correct name of client_builder in computed](https://github.com/MaterializeInc/materialize/commit/78045dc5408353ff19ef230f6ecbc3fd6f543972) (@brennanvincent)
* [ ] [`ebf054648` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ebf05464865f0782cd7da4e4a781c78ecc081e2e) (@materializer)
* [ ] [`45802286b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/45802286b697feb1205911543abc62c640ad63f6) (@materializer)
* [ ] [`88fb72bb6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/88fb72bb60e49848ed19536a6a17d6df9bac5490) (@materializer)
* [ ] [`a6a202489` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a6a202489e465003e2f7bc7f9fdf952a939501b6) (@materializer)
* [ ] [`d6f35ce35` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d6f35ce35763ee6dd582d5647002b3fd423aa309) (@materializer)
* [ ] [`3e400a919` release: v0.27.0-alpha.16](https://github.com/MaterializeInc/materialize/commit/3e400a919d0e7f11dae7bd70968dfa5fbe8a39cc) (@arusahni)

**Comment by benesch** [comment]
The commits that are not mine LGTM. @brennanvincent can you sign off on the rest?

**Comment by brennanvincent** [comment]
lgtm
