### ISSUE TITLE
release: v0.27.0-alpha.19 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#14685]
The following PRs in [`v0.27.0-alpha.19`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.19) require review:
* [x] [#14521 Fix crash in scratch.py](https://github.com/MaterializeInc/materialize/pull/14521) (@brennanvincent)
* [x] [#14523 test: fix nightly tests broken by #14467](https://github.com/MaterializeInc/materialize/pull/14523) (@sploiselle)
* [x] [#14441 Avoid crash during the handling of a RecursionLimitError](https://github.com/MaterializeInc/materialize/pull/14441) (@ggevay)
* [x] [#14570 persist: add `<T>` timestamp parameter to BlobTraceBatchPart](https://github.com/MaterializeInc/materialize/pull/14570) (@danhhz)
* [x] [#14571 test: triage nightly test failures 22-09-01](https://github.com/MaterializeInc/materialize/pull/14571) (@sploiselle)
* [x] [#14593 ci: save node-log artifacts in persist maelstrom job](https://github.com/MaterializeInc/materialize/pull/14593) (@danhhz)
* [x] [#14583 Remove `LinearOperator`](https://github.com/MaterializeInc/materialize/pull/14583) (@frankmcsherry)
* [x] [#14604 mzcompose: upgrade to ARM-supporting Confluent Platform](https://github.com/MaterializeInc/materialize/pull/14604) (@benesch)
* [x] [#14631 ci/builder: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14631) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`59e8807b0` fix typo](https://github.com/MaterializeInc/materialize/commit/59e8807b0ac246532ea42d65c8d4b8e607aaa426) (@brennanvincent)
* [x] [`bbf69c588` fix another typo](https://github.com/MaterializeInc/materialize/commit/bbf69c588fc37a815d2780e7cfd6d6f131bda0a1) (@brennanvincent)
* [x] [`1f2458775` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1f24587750b1fff661f0c4de64774c3aeff0ec06) (@materializer)
* [x] [`a63196d8c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a63196d8cf26eca95caa762ce67ab6596aab63e2) (@materializer)
* [x] [`4aef03db4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4aef03db4709aade5dfee5d3d6235681cc825f3b) (@materializer)
* [x] [`aeabe1044` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aeabe1044eae352ad444c9f966bbb668331332f6) (@materializer)
* [x] [`7e444638c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7e444638c6d3a19dc970a2f1a43ace75734a0ded) (@materializer)
* [x] [`e83c79d1a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e83c79d1aa56526354f0aa89971d377284c2698f) (@materializer)
* [x] [`37b70aa05` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/37b70aa057428aec96205cb002e71fd2b7ceb84a) (@materializer)
* [x] [`63d73eec4` release: v0.27.0-alpha.19](https://github.com/MaterializeInc/materialize/commit/63d73eec442674fb7edb450486288afaa1f72950) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#14521 Fix crash in scratch.py](https://github.com/MaterializeInc/materialize/pull/14521) (@brennanvincent)
* [ ] [#14498 get rid of testdrive `publish` flag](https://github.com/MaterializeInc/materialize/pull/14498) (@brennanvincent)
* [ ] [#14530 compute-client: remove DataflowDescription::global_id](https://github.com/MaterializeInc/materialize/pull/14530) (@teskje)
* [ ] [#14534 Remove duplicates from indexes_to_undistribute](https://github.com/MaterializeInc/materialize/pull/14534) (@ggevay)
* [ ] [#14523 test: fix nightly tests broken by #14467](https://github.com/MaterializeInc/materialize/pull/14523) (@sploiselle)
* [ ] [#14541 build: Fix dependency for orchestrator-process](https://github.com/MaterializeInc/materialize/pull/14541) (@jkosh44)
* [ ] [#14441 Avoid crash during the handling of a RecursionLimitError](https://github.com/MaterializeInc/materialize/pull/14441) (@ggevay)
* [ ] [#14485 Use timely fabric to forward ComputeCommands](https://github.com/MaterializeInc/materialize/pull/14485) (@lluki)
* [ ] [#14496 [sources] Move alter source implementation into the catalog](https://github.com/MaterializeInc/materialize/pull/14496) (@bkirwi)
* [ ] [#14528 revert erroneous changes to test_remote_storaged](https://github.com/MaterializeInc/materialize/pull/14528) (@guswynn)
* [ ] [#14510 Retry broken connections when establishing...](https://github.com/MaterializeInc/materialize/pull/14510) (@brennanvincent)
* [ ] [#14553 Allow SSH connections outside of unsafe mode](https://github.com/MaterializeInc/materialize/pull/14553) (@andrioni)
* [ ] [#14525 persist: flatten listen LeasedBatches into parts](https://github.com/MaterializeInc/materialize/pull/14525) (@danhhz)
* [ ] [#14552 install cloudtest prerequisites (+k9s) in scratch boxes](https://github.com/MaterializeInc/materialize/pull/14552) (@brennanvincent)
* [ ] [#14549 Deduplicate in detect_literal_constraints](https://github.com/MaterializeInc/materialize/pull/14549) (@ggevay)
* [ ] [#14556 adapter,pgwire: fix command tags for `CREATE {CLUSTER|VIEWS}`](https://github.com/MaterializeInc/materialize/pull/14556) (@benesch)
* [ ] [#14560 repr: fork persist's ProtoU64Antichain for non-persist use](https://github.com/MaterializeInc/materialize/pull/14560) (@danhhz)
* [ ] [#14195 dbt-materialize: enable cluster use, test suite profiles](https://github.com/MaterializeInc/materialize/pull/14195) (@ahelium)
* [ ] [#14561 expr,storage: various u64 -> mz_repr::Timestamp](https://github.com/MaterializeInc/materialize/pull/14561) (@mjibson)
* [ ] [#14505 explain: add unique keys attribute to new interface](https://github.com/MaterializeInc/materialize/pull/14505) (@wangandi)
* [ ] [#14563 docs: Fix a typo in ssh connection docs](https://github.com/MaterializeInc/materialize/pull/14563) (@bobbyiliev)
* [ ] [#14564 storage: avoid interleaving postgres connections](https://github.com/MaterializeInc/materialize/pull/14564) (@andrioni)
* [ ] [#14537 Minor improvements to `persist_source`](https://github.com/MaterializeInc/materialize/pull/14537) (@frankmcsherry)
* [ ] [#14570 persist: add `<T>` timestamp parameter to BlobTraceBatchPart](https://github.com/MaterializeInc/materialize/pull/14570) (@danhhz)
* [ ] [#14574 Minor cleanup in the literal constraints detection](https://github.com/MaterializeInc/materialize/pull/14574) (@ggevay)
* [ ] [#14517 Determine infallibility of some expressions, optimize joins](https://github.com/MaterializeInc/materialize/pull/14517) (@frankmcsherry)
* [ ] [#14507 adapter: Prevent OOM from expanding binary result](https://github.com/MaterializeInc/materialize/pull/14507) (@jkosh44)
* [ ] [#14577 Temporarily disable cloudtest](https://github.com/MaterializeInc/materialize/pull/14577) (@brennanvincent)
* [ ] [#14550 adapter: enrich SimpleResult::Ok](https://github.com/MaterializeInc/materialize/pull/14550) (@sploiselle)
* [ ] [#14571 test: triage nightly test failures 22-09-01](https://github.com/MaterializeInc/materialize/pull/14571) (@sploiselle)
* [ ] [#14581 persist: fix over-aggressive assertion in GC](https://github.com/MaterializeInc/materialize/pull/14581) (@danhhz)
* [ ] [#14578 coord: Refactor peek response handling](https://github.com/MaterializeInc/materialize/pull/14578) (@jkosh44)
* [ ] [#14589 .github: add an issue template for CI flakes](https://github.com/MaterializeInc/materialize/pull/14589) (@benesch)
* [ ] [#14588 compute-client: remove a misleading error log](https://github.com/MaterializeInc/materialize/pull/14588) (@teskje)
* [ ] [#14593 ci: save node-log artifacts in persist maelstrom job](https://github.com/MaterializeInc/materialize/pull/14593) (@danhhz)
* [ ] [#14594 persist: safely return snapshot leases on drop](https://github.com/MaterializeInc/materialize/pull/14594) (@sploiselle)
* [ ] [#14539 sql: Refactor SINK parsing](https://github.com/MaterializeInc/materialize/pull/14539) (@sploiselle)
* [ ] [#14535 adapter: add join support to `EXPLAIN AS TEXT` for LIR plans](https://github.com/MaterializeInc/materialize/pull/14535) (@aalexandrov)
* [ ] [#14562 adapter: implement EXPLAIN AS JSON](https://github.com/MaterializeInc/materialize/pull/14562) (@aalexandrov)
* [ ] [#14583 Remove `LinearOperator`](https://github.com/MaterializeInc/materialize/pull/14583) (@frankmcsherry)
* [ ] [#14604 mzcompose: upgrade to ARM-supporting Confluent Platform](https://github.com/MaterializeInc/materialize/pull/14604) (@benesch)
* [ ] [#14592 Allow dropping clusters with active replicas](https://github.com/MaterializeInc/materialize/pull/14592) (@teskje)
* [ ] [#14526 [sinks] New progress topic implementation](https://github.com/MaterializeInc/materialize/pull/14526) (@bkirwi)
* [ ] [#14572  storage: in persist_source, don't use async_op! macro for fetcher operator](https://github.com/MaterializeInc/materialize/pull/14572) (@aljoscha)
* [ ] [#14629 build(deps): bump ubuntu from jammy-20220801 to jammy-20220815 in /misc/images/ubuntu-base](https://github.com/MaterializeInc/materialize/pull/14629) (@dependabot[bot])
* [ ] [#14619 build(deps): bump ubuntu from jammy-20220801 to jammy-20220815 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14619) (@dependabot[bot])
* [ ] [#14611 build(deps): bump sha1 from 0.10.1 to 0.10.4](https://github.com/MaterializeInc/materialize/pull/14611) (@dependabot[bot])
* [ ] [#14613 build(deps): bump anyhow from 1.0.62 to 1.0.64](https://github.com/MaterializeInc/materialize/pull/14613) (@dependabot[bot])
* [ ] [#14609 build(deps): bump paste from 1.0.8 to 1.0.9](https://github.com/MaterializeInc/materialize/pull/14609) (@dependabot[bot])
* [ ] [#14610 build(deps): bump futures from 0.3.23 to 0.3.24](https://github.com/MaterializeInc/materialize/pull/14610) (@dependabot[bot])
* [ ] [#14615 build(deps): bump protobuf-src from 1.0.5+3.19.3 to 1.1.0+21.5](https://github.com/MaterializeInc/materialize/pull/14615) (@dependabot[bot])
* [ ] [#14616 build(deps): bump futures-util from 0.3.23 to 0.3.24](https://github.com/MaterializeInc/materialize/pull/14616) (@dependabot[bot])
* [ ] [#14638 Simplify compute controller drop api](https://github.com/MaterializeInc/materialize/pull/14638) (@teskje)
* [ ] [#14617 build(deps): bump aws-config from 0.47.0 to 0.48.0](https://github.com/MaterializeInc/materialize/pull/14617) (@dependabot[bot])
* [ ] [#14637 build(deps): bump console-subscriber from 0.1.7 to 0.1.8](https://github.com/MaterializeInc/materialize/pull/14637) (@dependabot[bot])
* [ ] [#14635 build(deps): bump sha2 from 0.10.2 to 0.10.5](https://github.com/MaterializeInc/materialize/pull/14635) (@dependabot[bot])
* [ ] [#14631 ci/builder: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14631) (@benesch)
* [ ] [#14652 build(deps): bump chrono from 0.4.20 to 0.4.21](https://github.com/MaterializeInc/materialize/pull/14652) (@dependabot[bot])
* [ ] [#14634 build(deps): bump md-5 from 0.10.1 to 0.10.4](https://github.com/MaterializeInc/materialize/pull/14634) (@dependabot[bot])
* [ ] [#14658 build(deps): bump sysinfo from 0.25.3 to 0.26.2](https://github.com/MaterializeInc/materialize/pull/14658) (@dependabot[bot])
* [ ] [#14459 persist: track blob size in HollowBatch](https://github.com/MaterializeInc/materialize/pull/14459) (@danhhz)
* [ ] [#14175 persist: split batch fetching from decoding](https://github.com/MaterializeInc/materialize/pull/14175) (@danhhz)
* [ ] [`59e8807b0` fix typo](https://github.com/MaterializeInc/materialize/commit/59e8807b0ac246532ea42d65c8d4b8e607aaa426) (@brennanvincent)
* [ ] [`bbf69c588` fix another typo](https://github.com/MaterializeInc/materialize/commit/bbf69c588fc37a815d2780e7cfd6d6f131bda0a1) (@brennanvincent)
* [ ] [`1f2458775` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1f24587750b1fff661f0c4de64774c3aeff0ec06) (@materializer)
* [ ] [`a63196d8c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a63196d8cf26eca95caa762ce67ab6596aab63e2) (@materializer)
* [ ] [`4aef03db4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4aef03db4709aade5dfee5d3d6235681cc825f3b) (@materializer)
* [ ] [`aeabe1044` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aeabe1044eae352ad444c9f966bbb668331332f6) (@materializer)
* [ ] [`7e444638c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7e444638c6d3a19dc970a2f1a43ace75734a0ded) (@materializer)
* [ ] [`e83c79d1a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e83c79d1aa56526354f0aa89971d377284c2698f) (@materializer)
* [ ] [`37b70aa05` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/37b70aa057428aec96205cb002e71fd2b7ceb84a) (@materializer)
* [ ] [`63d73eec4` release: v0.27.0-alpha.19](https://github.com/MaterializeInc/materialize/commit/63d73eec442674fb7edb450486288afaa1f72950) (@benesch)

**Comment by benesch** [comment]
LGTM, modulo my own commits. @brennanvincent can you take a look at those?

**Comment by guswynn** [comment]
LGTM, benesch's commits (and bot commits)
