### ISSUE TITLE
release: v0.27.0-alpha.21 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#14894]
The following PRs in [`v0.27.0-alpha.21`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.21) require review:
* [x] [#14686 nightly: repair tests back to operational status](https://github.com/MaterializeInc/materialize/pull/14686) (@philip-stoev)
* [x] [#14690 cloudtest: Drastically tone down the 'shared fate' tests](https://github.com/MaterializeInc/materialize/pull/14690) (@philip-stoev)
* [x] [#14691 cloudtest: Make sure kubeconfig is always available](https://github.com/MaterializeInc/materialize/pull/14691) (@philip-stoev)
* [x] [#14697 cloudtest: wire the internal port through](https://github.com/MaterializeInc/materialize/pull/14697) (@philip-stoev)
* [x] [#14693 cloudtest: Disable the 'shared fate' scenarios altogether](https://github.com/MaterializeInc/materialize/pull/14693) (@philip-stoev)
* [x] [#14713 feature-benchmark: Disable the Nightly CI jobs](https://github.com/MaterializeInc/materialize/pull/14713) (@philip-stoev)
* [x] [#14731 kafka-multi-broker: Fix the test](https://github.com/MaterializeInc/materialize/pull/14731) (@philip-stoev)
* [x] [#14737 nightly: Increase the timeout of all testdrive-based tests to 3h](https://github.com/MaterializeInc/materialize/pull/14737) (@philip-stoev)
* [x] [#14733 zippy: Add Debezium with a Postgres source](https://github.com/MaterializeInc/materialize/pull/14733) (@philip-stoev)
* [x] [#14792 platform checks: Add checks for the various Kafka source formats](https://github.com/MaterializeInc/materialize/pull/14792) (@philip-stoev)
* [x] [#14795 ci: Force csv-sources.td to use 1 partition](https://github.com/MaterializeInc/materialize/pull/14795) (@philip-stoev)
* [x] [#14800 nightly: Add CI jobs with REPLICA SIZE '4' and 4 replicas](https://github.com/MaterializeInc/materialize/pull/14800) (@philip-stoev)
* [x] [#14796 persist-maelstrom: Parameterize and add a Nightly CI job](https://github.com/MaterializeInc/materialize/pull/14796) (@philip-stoev)
* [x] [#14839 doc/user: correct documentation about storage usage retention](https://github.com/MaterializeInc/materialize/pull/14839) (@benesch)
* [x] [#14073 doc: describe api/sql output + new parameters input](https://github.com/MaterializeInc/materialize/pull/14073) (@sploiselle)
* [x] [#14863 [sinks] Add more extensive logging](https://github.com/MaterializeInc/materialize/pull/14863) (@cjubb39)
* [x] [#14826 limits test: Adjust the KafkaSinks* scenarios to reality](https://github.com/MaterializeInc/materialize/pull/14826) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`608aacb7c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/608aacb7c8154afb767e065bd269dac191c4eefc) (@materializer)
* [x] [`bab109609` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bab10960970504b04eb7fa65303f3558bc330921) (@materializer)
* [x] [`3d8de4de3` Fix typo in comment](https://github.com/MaterializeInc/materialize/commit/3d8de4de3604e3cca8eb1fe5fb049327b2fa7260) (@brennanvincent)
* [x] [`9db7ada53` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9db7ada53a802a095a6c46c7cd10b1d479246374) (@materializer)
* [x] [`e8c35e387` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e8c35e38770ee9256168a103f28101017b1c59fb) (@materializer)
* [x] [`a562db213` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a562db2130329bd80bd2d9a59c9d68d0547fe89a) (@materializer)
* [x] [`930edad01` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/930edad018733efafda4d1cd64a29f927ae37054) (@materializer)
* [x] [`b56004751` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b5600475136c9d1bf65ad394888b5ae47a841dad) (@materializer)
* [x] [`eb5b6b2bc` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/eb5b6b2bc6440a2d06e248c2d993d61c55805fea) (@materializer)
* [x] [`c82d7bce0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c82d7bce06301c4aa697c0907faf9efbfae6e89a) (@materializer)
* [x] [`8078ce80c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8078ce80cba4017976224c4ea030494ce4d1b2b2) (@materializer)
* [x] [`58f2b35c6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/58f2b35c62d9942aa6c6ea7928aceb8dc8f38678) (@materializer)
* [x] [`db7561736` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/db7561736d1ff633c78fe0a20e3b9e996cbd5959) (@materializer)
* [x] [`7105fb007` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7105fb007f747aa35c4fdfd80df81c8279163f25) (@materializer)
* [x] [`ea6bf3d81` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ea6bf3d81a7a44898d707d85c5fd10e2888d09c7) (@materializer)
* [x] [`a4f49274b` sql: Scarily unbreak option syntax](https://github.com/MaterializeInc/materialize/commit/a4f49274bb01f2965089099bfd418fe3090a68da) (@jkosh44)
* [x] [`77b684cee` release: v0.27.0-alpha.21](https://github.com/MaterializeInc/materialize/commit/77b684cee81ec42bc80715b93f41ef14d920ff71) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#14608 *: make mz_repr::Timestamp opaque](https://github.com/MaterializeInc/materialize/pull/14608) (@mjibson)
* [ ] [#14641 Compute controller structs refactor](https://github.com/MaterializeInc/materialize/pull/14641) (@teskje)
* [ ] [#14596 Repurpose `flatten_and_or` as `flatten_associative`](https://github.com/MaterializeInc/materialize/pull/14596) (@brennanvincent)
* [ ] [#14677 environmentd: cleanup js formatting and react](https://github.com/MaterializeInc/materialize/pull/14677) (@mjibson)
* [ ] [#14661 sql: support SHOW as a table factor](https://github.com/MaterializeInc/materialize/pull/14661) (@mjibson)
* [ ] [#14686 nightly: repair tests back to operational status](https://github.com/MaterializeInc/materialize/pull/14686) (@philip-stoev)
* [ ] [#14690 cloudtest: Drastically tone down the 'shared fate' tests](https://github.com/MaterializeInc/materialize/pull/14690) (@philip-stoev)
* [ ] [#14691 cloudtest: Make sure kubeconfig is always available](https://github.com/MaterializeInc/materialize/pull/14691) (@philip-stoev)
* [ ] [#14576 test: Reset all system config before testdrive](https://github.com/MaterializeInc/materialize/pull/14576) (@jkosh44)
* [ ] [#14672 persist: store read lease duration in state](https://github.com/MaterializeInc/materialize/pull/14672) (@danhhz)
* [ ] [#14669 Make `remove_literal_constraints` support OR in the residual](https://github.com/MaterializeInc/materialize/pull/14669) (@ggevay)
* [ ] [#14697 cloudtest: wire the internal port through](https://github.com/MaterializeInc/materialize/pull/14697) (@philip-stoev)
* [ ] [#14698 pgtest: add a bit more transaction testing](https://github.com/MaterializeInc/materialize/pull/14698) (@mjibson)
* [ ] [#14693 cloudtest: Disable the 'shared fate' scenarios altogether](https://github.com/MaterializeInc/materialize/pull/14693) (@philip-stoev)
* [ ] [#14673 [sinks] Recover some exactly-once tests](https://github.com/MaterializeInc/materialize/pull/14673) (@bkirwi)
* [ ] [#14699 sql: Add more unsigned int funcs and operators](https://github.com/MaterializeInc/materialize/pull/14699) (@jkosh44)
* [ ] [#14582 api/sql: simple protocol-style txns](https://github.com/MaterializeInc/materialize/pull/14582) (@sploiselle)
* [ ] [#14675 persist: start an allowlist of metrics into honeycomb for alerting](https://github.com/MaterializeInc/materialize/pull/14675) (@danhhz)
* [ ] [#14679 [sinks] Rename some lingering references to the consistency topic](https://github.com/MaterializeInc/materialize/pull/14679) (@bkirwi)
* [ ] [#14712 testdrive: Fix bit rot in Kafka-topic related tests](https://github.com/MaterializeInc/materialize/pull/14712) (@philip-stoev)
* [ ] [#14688 adapter: rename SSH tunnel connections to `ssh-tunnel` in `mz_connections`](https://github.com/MaterializeInc/materialize/pull/14688) (@andrioni)
* [ ] [#14713 feature-benchmark: Disable the Nightly CI jobs](https://github.com/MaterializeInc/materialize/pull/14713) (@philip-stoev)
* [ ] [#14509 storage: implement the resumption frontier operator](https://github.com/MaterializeInc/materialize/pull/14509) (@guswynn)
* [ ] [#14709 [sinks] Move ComputeSink structs out of storage](https://github.com/MaterializeInc/materialize/pull/14709) (@cjubb39)
* [ ] [#14600 Allow using sinks outside of unsafe mode](https://github.com/MaterializeInc/materialize/pull/14600) (@bkirwi)
* [ ] [#14558 storage: make ReclockFollower shareable](https://github.com/MaterializeInc/materialize/pull/14558) (@guswynn)
* [ ] [#14718 ci/plugins/scratch: assume AWS role for 12 hours](https://github.com/MaterializeInc/materialize/pull/14718) (@benesch)
* [ ] [#14731 kafka-multi-broker: Fix the test](https://github.com/MaterializeInc/materialize/pull/14731) (@philip-stoev)
* [ ] [#14327 storage: assert on Sink as_of/gate timestamp correctness](https://github.com/MaterializeInc/materialize/pull/14327) (@aljoscha)
* [ ] [#14716 storage: remove `select!` from pg source and gain indentation back](https://github.com/MaterializeInc/materialize/pull/14716) (@petrosagg)
* [ ] [#14735 storage: enrich persist_source error message](https://github.com/MaterializeInc/materialize/pull/14735) (@aljoscha)
* [ ] [#14737 nightly: Increase the timeout of all testdrive-based tests to 3h](https://github.com/MaterializeInc/materialize/pull/14737) (@philip-stoev)
* [ ] [#14717 test: Fix flaky storage test](https://github.com/MaterializeInc/materialize/pull/14717) (@jkosh44)
* [ ] [#14557 compute: Prevent sending large peek results](https://github.com/MaterializeInc/materialize/pull/14557) (@jkosh44)
* [ ] [#14733 zippy: Add Debezium with a Postgres source](https://github.com/MaterializeInc/materialize/pull/14733) (@philip-stoev)
* [ ] [#14745 persist: fix bug where we'd incorrectly delete an initial rollup](https://github.com/MaterializeInc/materialize/pull/14745) (@danhhz)
* [ ] [#14726 sql: Remove full and extended from SHOW commands](https://github.com/MaterializeInc/materialize/pull/14726) (@jkosh44)
* [ ] [#14751 sql-parser: simplify and consistentize SHOW INDEX syntax](https://github.com/MaterializeInc/materialize/pull/14751) (@benesch)
* [ ] [#14606 Abstract hierarchical reduced within region.](https://github.com/MaterializeInc/materialize/pull/14606) (@frankmcsherry)
* [ ] [#14632 build(deps): bump clap from 3.2.17 to 3.2.20](https://github.com/MaterializeInc/materialize/pull/14632) (@dependabot[bot])
* [ ] [#14633 build(deps): bump once_cell from 1.13.1 to 1.14.0](https://github.com/MaterializeInc/materialize/pull/14633) (@dependabot[bot])
* [ ] [#14700 build(deps): bump timely from `1f3a315` to `9548bf9`](https://github.com/MaterializeInc/materialize/pull/14700) (@dependabot[bot])
* [ ] [#14650 build(deps): bump aho-corasick from 0.7.18 to 0.7.19](https://github.com/MaterializeInc/materialize/pull/14650) (@dependabot[bot])
* [ ] [#14756 build(deps): bump axum from 0.5.15 to 0.5.16](https://github.com/MaterializeInc/materialize/pull/14756) (@dependabot[bot])
* [ ] [#14767 build(deps): bump prometheus from 0.13.1 to 0.13.2](https://github.com/MaterializeInc/materialize/pull/14767) (@dependabot[bot])
* [ ] [#14766 build(deps): bump tonic from 0.8.0 to 0.8.1](https://github.com/MaterializeInc/materialize/pull/14766) (@dependabot[bot])
* [ ] [#14758 build(deps): bump url from 2.2.2 to 2.3.0](https://github.com/MaterializeInc/materialize/pull/14758) (@dependabot[bot])
* [ ] [#14759 build(deps): bump cryptography from 37.0.4 to 38.0.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14759) (@dependabot[bot])
* [ ] [#14760 build(deps): bump types-requests from 2.28.9 to 2.28.10 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14760) (@dependabot[bot])
* [ ] [#14761 build(deps): bump boto3 from 1.24.66 to 1.24.70 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14761) (@dependabot[bot])
* [ ] [#14757 build(deps): bump http-serde from 1.1.0 to 1.1.2](https://github.com/MaterializeInc/materialize/pull/14757) (@dependabot[bot])
* [ ] [#14765 build(deps): bump tiberius from 0.10.0 to 0.11.0](https://github.com/MaterializeInc/materialize/pull/14765) (@dependabot[bot])
* [ ] [#14755 sql: Remove type column from show commands](https://github.com/MaterializeInc/materialize/pull/14755) (@jkosh44)
* [ ] [#14653 build(deps): bump thiserror from 1.0.32 to 1.0.34](https://github.com/MaterializeInc/materialize/pull/14653) (@dependabot[bot])
* [ ] [#14768 build(deps): bump criterion from `f82ce59` to `935c632`](https://github.com/MaterializeInc/materialize/pull/14768) (@dependabot[bot])
* [ ] [#14762 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.24.66 to 1.24.70 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14762) (@dependabot[bot])
* [ ] [#14770 build(deps): bump url from 2.3.0 to 2.3.1](https://github.com/MaterializeInc/materialize/pull/14770) (@dependabot[bot])
* [ ] [#14769 build(deps): bump chrono from 0.4.21 to 0.4.22](https://github.com/MaterializeInc/materialize/pull/14769) (@dependabot[bot])
* [ ] [#14771 sql: Remove mz_classify_object_id function](https://github.com/MaterializeInc/materialize/pull/14771) (@jkosh44)
* [ ] [#14772 sql: Add type column to SHOW CONNECTIONS](https://github.com/MaterializeInc/materialize/pull/14772) (@jkosh44)
* [ ] [#14773 sql: Add type column to SHOW OBJECTS](https://github.com/MaterializeInc/materialize/pull/14773) (@jkosh44)
* [ ] [#14630 timely-util: no nonsense timely/async bridge](https://github.com/MaterializeInc/materialize/pull/14630) (@petrosagg)
* [ ] [#14774 pgetst: test behavior of empty queries in extended protocol](https://github.com/MaterializeInc/materialize/pull/14774) (@sploiselle)
* [ ] [#14721 Extract a compute controller](https://github.com/MaterializeInc/materialize/pull/14721) (@teskje)
* [ ] [#14741 [sinks] Replace ConfigKey with some constants](https://github.com/MaterializeInc/materialize/pull/14741) (@bkirwi)
* [ ] [#14782 timely-util: fix bug with CapabilityRefs now having a Drop impl](https://github.com/MaterializeInc/materialize/pull/14782) (@petrosagg)
* [ ] [#14784 Disable eviction by the cluster-autoscaler](https://github.com/MaterializeInc/materialize/pull/14784) (@alex-hunt-materialize)
* [ ] [#14786 storage: delete dead code](https://github.com/MaterializeInc/materialize/pull/14786) (@petrosagg)
* [ ] [#14516 Remove `mz_catalog_names` system table](https://github.com/MaterializeInc/materialize/pull/14516) (@chaas)
* [ ] [#14736 sql: misc. txn handling corner case fixes](https://github.com/MaterializeInc/materialize/pull/14736) (@sploiselle)
* [ ] [#14783 compute-client: reduce allocations](https://github.com/MaterializeInc/materialize/pull/14783) (@teskje)
* [ ] [#14715 test: properly name kafka topics in testdrive](https://github.com/MaterializeInc/materialize/pull/14715) (@sploiselle)
* [ ] [#14789 persist: fix bug in gc that breaks later calls to gc](https://github.com/MaterializeInc/materialize/pull/14789) (@danhhz)
* [ ] [#14683  adapter: accept parameters in /api/sql endpoint using portals](https://github.com/MaterializeInc/materialize/pull/14683) (@sploiselle)
* [ ] [#14792 platform checks: Add checks for the various Kafka source formats](https://github.com/MaterializeInc/materialize/pull/14792) (@philip-stoev)
* [ ] [#14795 ci: Force csv-sources.td to use 1 partition](https://github.com/MaterializeInc/materialize/pull/14795) (@philip-stoev)
* [ ] [#14753 sql: Fix row size calculation](https://github.com/MaterializeInc/materialize/pull/14753) (@jkosh44)
* [ ] [#14799 buildkite: More agressive cleanup in the mzcompose plugin](https://github.com/MaterializeInc/materialize/pull/14799) (@philip-stoev)
* [ ] [#14714 test: better mzcompose tests for SSH connections](https://github.com/MaterializeInc/materialize/pull/14714) (@andrioni)
* [ ] [#14706 docs: Add consistency docs](https://github.com/MaterializeInc/materialize/pull/14706) (@jkosh44)
* [ ] [#14678 [sinks] Replace the transaction field with a Kafka header in the sink](https://github.com/MaterializeInc/materialize/pull/14678) (@bkirwi)
* [ ] [#14804 storage: statically check source connection types](https://github.com/MaterializeInc/materialize/pull/14804) (@petrosagg)
* [ ] [#14781 storage: use `CapabilityRef`s directly](https://github.com/MaterializeInc/materialize/pull/14781) (@petrosagg)
* [ ] [#14800 nightly: Add CI jobs with REPLICA SIZE '4' and 4 replicas](https://github.com/MaterializeInc/materialize/pull/14800) (@philip-stoev)
* [ ] [#14788 Reorder columns in SHOW MATERIALIZED VIEWS](https://github.com/MaterializeInc/materialize/pull/14788) (@chaas)
* [ ] [#14787 coord: Make storage usage interval configurable](https://github.com/MaterializeInc/materialize/pull/14787) (@jkosh44)
* [ ] [#14734 storage: pg: handle excessive WAL lag edge-cases](https://github.com/MaterializeInc/materialize/pull/14734) (@petrosagg)
* [ ] [#14785 [sinks] Generate updated as_of in rehydrating client](https://github.com/MaterializeInc/materialize/pull/14785) (@cjubb39)
* [ ] [#14811 Update TAIL documentation](https://github.com/MaterializeInc/materialize/pull/14811) (@frankmcsherry)
* [ ] [#14752 sql: rename mz_cluster_id to mz_environment_id](https://github.com/MaterializeInc/materialize/pull/14752) (@benesch)
* [ ] [#14527 persist: bounded memory compaction](https://github.com/MaterializeInc/materialize/pull/14527) (@pH14)
* [ ] [#14710 storage: implement ReclockFollower::source_upper_at_frontier](https://github.com/MaterializeInc/materialize/pull/14710) (@guswynn)
* [ ] [#14806 persist: various small gc commits](https://github.com/MaterializeInc/materialize/pull/14806) (@danhhz)
* [ ] [#14813 storage: make the source reader operator async](https://github.com/MaterializeInc/materialize/pull/14813) (@guswynn)
* [ ] [#14824 sql-parser: date() cast support; temp hack](https://github.com/MaterializeInc/materialize/pull/14824) (@mjibson)
* [ ] [#14820 Move ComputeSinkId into mz-adapter](https://github.com/MaterializeInc/materialize/pull/14820) (@teskje)
* [ ] [#14796 persist-maelstrom: Parameterize and add a Nightly CI job](https://github.com/MaterializeInc/materialize/pull/14796) (@philip-stoev)
* [ ] [#14821 doc/user: add reference documentation for load generator sources](https://github.com/MaterializeInc/materialize/pull/14821) (@benesch)
* [ ] [#14839 doc/user: correct documentation about storage usage retention](https://github.com/MaterializeInc/materialize/pull/14839) (@benesch)
* [ ] [#14833 build(deps): bump sha2 from 0.10.5 to 0.10.6](https://github.com/MaterializeInc/materialize/pull/14833) (@dependabot[bot])
* [ ] [#14829 build(deps): bump indicatif from 0.17.0 to 0.17.1](https://github.com/MaterializeInc/materialize/pull/14829) (@dependabot[bot])
* [ ] [#14832 build(deps): bump open from 3.0.2 to 3.0.3](https://github.com/MaterializeInc/materialize/pull/14832) (@dependabot[bot])
* [ ] [#14831 build(deps): bump semver from 1.0.13 to 1.0.14](https://github.com/MaterializeInc/materialize/pull/14831) (@dependabot[bot])
* [ ] [#14837 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.24.70 to 1.24.75 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14837) (@dependabot[bot])
* [ ] [#14835 build(deps): bump itertools from 0.10.3 to 0.10.4](https://github.com/MaterializeInc/materialize/pull/14835) (@dependabot[bot])
* [ ] [#14846 build(deps): bump anyhow from 1.0.64 to 1.0.65](https://github.com/MaterializeInc/materialize/pull/14846) (@dependabot[bot])
* [ ] [#14834 build(deps): bump sha1 from 0.10.4 to 0.10.5](https://github.com/MaterializeInc/materialize/pull/14834) (@dependabot[bot])
* [ ] [#14848 build(deps): bump tokio-stream from 0.1.9 to 0.1.10](https://github.com/MaterializeInc/materialize/pull/14848) (@dependabot[bot])
* [ ] [#14844 build(deps): bump thiserror from 1.0.34 to 1.0.35](https://github.com/MaterializeInc/materialize/pull/14844) (@dependabot[bot])
* [ ] [#14838 build(deps): bump boto3 from 1.24.70 to 1.24.75 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/14838) (@dependabot[bot])
* [ ] [#14850 build(deps): bump syn from 1.0.99 to 1.0.100](https://github.com/MaterializeInc/materialize/pull/14850) (@dependabot[bot])
* [ ] [#14830 build(deps): bump arrow2 from 0.13.1 to 0.14.0](https://github.com/MaterializeInc/materialize/pull/14830) (@dependabot[bot])
* [ ] [#14851 build(deps): bump unicode-width from 0.1.9 to 0.1.10](https://github.com/MaterializeInc/materialize/pull/14851) (@dependabot[bot])
* [ ] [#14856 Bump versions to v0.27.0-dev](https://github.com/MaterializeInc/materialize/pull/14856) (@bobbyiliev)
* [ ] [#14814 persist: clean up datadriven tests](https://github.com/MaterializeInc/materialize/pull/14814) (@danhhz)
* [ ] [#14801 sql: improve syntax and output of SHOW INDEXES](https://github.com/MaterializeInc/materialize/pull/14801) (@jkosh44)
* [ ] [#14808 storage: in reclock operator, heartbeat handle to hold back the remap since](https://github.com/MaterializeInc/materialize/pull/14808) (@aljoscha)
* [ ] [#14857 sql: check type of referenced object in SHOW COLUMNS](https://github.com/MaterializeInc/materialize/pull/14857) (@benesch)
* [ ] [#14853 adapter: remove unneeded clone of RowSetFinishing](https://github.com/MaterializeInc/materialize/pull/14853) (@teskje)
* [ ] [#14073 doc: describe api/sql output + new parameters input](https://github.com/MaterializeInc/materialize/pull/14073) (@sploiselle)
* [ ] [#14810 coord: Make storage usage collection more precise](https://github.com/MaterializeInc/materialize/pull/14810) (@jkosh44)
* [ ] [#14865 remove dbz upsert from unsafe mode](https://github.com/MaterializeInc/materialize/pull/14865) (@brennanvincent)
* [ ] [#14863 [sinks] Add more extensive logging](https://github.com/MaterializeInc/materialize/pull/14863) (@cjubb39)
* [ ] [#14868 [environmentd] Thread through a environment string](https://github.com/MaterializeInc/materialize/pull/14868) (@bkirwi)
* [ ] [#13654 LICENSE: update additional use grant](https://github.com/MaterializeInc/materialize/pull/13654) (@benesch)
* [ ] [#14874 bin/environmentd: avoid crashing if mzdata directory already exists](https://github.com/MaterializeInc/materialize/pull/14874) (@benesch)
* [ ] [#14859 sql: allow setting TOPIC option without unsafe mode](https://github.com/MaterializeInc/materialize/pull/14859) (@benesch)
* [ ] [#14877 environmentd: improve hierarchical addr check](https://github.com/MaterializeInc/materialize/pull/14877) (@mjibson)
* [ ] [#14826 limits test: Adjust the KafkaSinks* scenarios to reality](https://github.com/MaterializeInc/materialize/pull/14826) (@philip-stoev)
* [ ] [#14885 docs: Escape <> characters in isolation docs](https://github.com/MaterializeInc/materialize/pull/14885) (@jkosh44)
* [ ] [#14883 Coord: Fix livelock in concurrent writes](https://github.com/MaterializeInc/materialize/pull/14883) (@jkosh44)
* [ ] [#14858 persist-maelstrom: cover high-throughput mem + multi-node postgres](https://github.com/MaterializeInc/materialize/pull/14858) (@pH14)
* [ ] [#14519 CLI API changes, docs, and code legibility](https://github.com/MaterializeInc/materialize/pull/14519) (@joacoc)
* [ ] [`608aacb7c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/608aacb7c8154afb767e065bd269dac191c4eefc) (@materializer)
* [ ] [`bab109609` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bab10960970504b04eb7fa65303f3558bc330921) (@materializer)
* [ ] [`3d8de4de3` Fix typo in comment](https://github.com/MaterializeInc/materialize/commit/3d8de4de3604e3cca8eb1fe5fb049327b2fa7260) (@brennanvincent)
* [ ] [`9db7ada53` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9db7ada53a802a095a6c46c7cd10b1d479246374) (@materializer)
* [ ] [`e8c35e387` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e8c35e38770ee9256168a103f28101017b1c59fb) (@materializer)
* [ ] [`a562db213` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a562db2130329bd80bd2d9a59c9d68d0547fe89a) (@materializer)
* [ ] [`930edad01` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/930edad018733efafda4d1cd64a29f927ae37054) (@materializer)
* [ ] [`b56004751` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b5600475136c9d1bf65ad394888b5ae47a841dad) (@materializer)
* [ ] [`eb5b6b2bc` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/eb5b6b2bc6440a2d06e248c2d993d61c55805fea) (@materializer)
* [ ] [`c82d7bce0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c82d7bce06301c4aa697c0907faf9efbfae6e89a) (@materializer)
* [ ] [`8078ce80c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8078ce80cba4017976224c4ea030494ce4d1b2b2) (@materializer)
* [ ] [`58f2b35c6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/58f2b35c62d9942aa6c6ea7928aceb8dc8f38678) (@materializer)
* [ ] [`db7561736` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/db7561736d1ff633c78fe0a20e3b9e996cbd5959) (@materializer)
* [ ] [`7105fb007` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7105fb007f747aa35c4fdfd80df81c8279163f25) (@materializer)
* [ ] [`ea6bf3d81` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ea6bf3d81a7a44898d707d85c5fd10e2888d09c7) (@materializer)
* [ ] [`a4f49274b` sql: Scarily unbreak option syntax](https://github.com/MaterializeInc/materialize/commit/a4f49274bb01f2965089099bfd418fe3090a68da) (@jkosh44)
* [ ] [`77b684cee` release: v0.27.0-alpha.21](https://github.com/MaterializeInc/materialize/commit/77b684cee81ec42bc80715b93f41ef14d920ff71) (@jkosh44)

**Comment by jkosh44** [comment]
I have signed off on all the un-reviewed commits and PRs.
