### ISSUE TITLE
[Epic] Timestamp selection improvements

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#14941]
## Motivation
Improve performance on simple selects and reads out of system tables

**Issues: Vetted**
- [x] https://github.com/MaterializeInc/materialize/issues/14696
- [x] https://github.com/MaterializeInc/materialize/issues/15366
- [x] https://github.com/MaterializeInc/materialize/issues/3751
- [x] https://github.com/MaterializeInc/materialize/issues/14899

**Related issues**
https://github.com/MaterializeInc/materialize/issues/14060

**Comment by ggnall** [comment]
Peeled out https://github.com/MaterializeInc/materialize/issues/13778 to https://github.com/MaterializeInc/materialize/issues/14052
