### ISSUE TITLE
[Epic] Documentation switch (`lts-docs`->`unstable`)

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#14978]
#### `main`
- [x] https://github.com/MaterializeInc/materialize/issues/8663 (https://github.com/MaterializeInc/materialize/pull/15103)
- [x] https://github.com/MaterializeInc/materialize/issues/13716 (https://github.com/MaterializeInc/materialize/pull/15101)
- [x] https://github.com/MaterializeInc/materialize/issues/8665 (https://github.com/MaterializeInc/materialize/pull/15121)
- [x] https://github.com/MaterializeInc/materialize/issues/13760 (https://github.com/MaterializeInc/materialize/pull/15115)

The above issues are a pre-requisite for the switch. Other foundational but less critical TODOs are tracked in [DevEx #165](https://github.com/MaterializeInc/developer-experience/issues/165).

#### `lts`
- [x] **:raised_hand: Needs action!** Add "unsupported version" warning (see [this thread](https://materializeinc.slack.com/archives/CPNFV9CVB/p1663593825186819?thread_ts=1663593583.722689&cid=CPNFV9CVB) and [#11976](https://github.com/MaterializeInc/materialize/pull/11976) for examples)
  - [x] https://github.com/MaterializeInc/materialize/pull/15128

### Build

- [x] **:raised_hand: Needs action!** Make `main` deploy to `materialize.com/docs/` + `lts` deploy to `materialize.com/docs/lts` (see [#11795](https://github.com/MaterializeInc/materialize/pull/11795) for steps)
   - [x] https://github.com/MaterializeInc/materialize/pull/15129
   - [ ] https://github.com/MaterializeInc/materialize/pull/15130

### UI

- [x] **:raised_hand: Needs action!** https://github.com/MaterializeInc/cloud/issues/4063  (PR: [Cloud #4082](https://github.com/MaterializeInc/cloud/pull/4082))

### Other repos:

- [x] Add "unsupported version" warning to: 
  - [x] [`MaterializeInc/demos`](https://github.com/MaterializeInc/demos)
  - [x] [`MaterializeInc/mz-hack-day-2022`](https://github.com/MaterializeInc/mz-hack-day-2022)
- [x] Switch `unstable`->`main` in [`MaterializeInc/connection-examples`](https://github.com/MaterializeInc/connection-examples)

**Comment by morsapaes** [comment]
@ruf-io @benesch, tagging you both here in case I go MIA.
