### ISSUE TITLE
release: v0.27.0-alpha.23 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15033]
The following PRs in [`v0.27.0-alpha.23`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.23) require review:
* [x] [#14882 zippy: Add replica support to Zippy](https://github.com/MaterializeInc/materialize/pull/14882) (@philip-stoev)
* [x] [#14908 persist-nightly: fix param name for maelstrom run](https://github.com/MaterializeInc/materialize/pull/14908) (@pH14)
* [x] [#14936 mzcompose: Update Redpanda to v22.2.3](https://github.com/MaterializeInc/materialize/pull/14936) (@BenPope)
* [x] [#14948 persist: add a pointer to the lease expiration panics](https://github.com/MaterializeInc/materialize/pull/14948) (@danhhz)
* [x] [#14953 compute-client: ignore flaky test dataflow_description_protobuf_roundtrip](https://github.com/MaterializeInc/materialize/pull/14953) (@teskje)
* [x] [#14360 Add Confluent Kafka integrations guide](https://github.com/MaterializeInc/materialize/pull/14360) (@bobbyiliev)
* [x] [#14991 doc/user: minor updates to documentation mentioning sinks](https://github.com/MaterializeInc/materialize/pull/14991) (@morsapaes)
* [x] [#14989 deps: upgrade criterion to v0.4.0](https://github.com/MaterializeInc/materialize/pull/14989) (@benesch)
* [x] [#14990 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14990) (@benesch)
* [x] [#14997 ci: Do not fail the build on Buildkite Analytics failure](https://github.com/MaterializeInc/materialize/pull/14997) (@philip-stoev)
* [x] [#13747 checks framework: Add Postgres sources](https://github.com/MaterializeInc/materialize/pull/13747) (@philip-stoev)
* [x] [#14999 pg-cdc: Disable replica-identity-default-nothing.td](https://github.com/MaterializeInc/materialize/pull/14999) (@philip-stoev)
* [x] [#14958 persist: cherrypick datadriven changes from #14704](https://github.com/MaterializeInc/materialize/pull/14958) (@pH14)
* [x] [#15015 deps: upgrade to latest segment release](https://github.com/MaterializeInc/materialize/pull/15015) (@benesch)
* [x] [#15019 cloudtest: Allow running .td files with testdrive](https://github.com/MaterializeInc/materialize/pull/15019) (@philip-stoev)
* [x] [#15007 persist: batch part read metrics](https://github.com/MaterializeInc/materialize/pull/15007) (@pH14)
* [x] [#15012 persist: more detailed batch write / compaction timing metrics](https://github.com/MaterializeInc/materialize/pull/15012) (@pH14)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`6ab6b1307` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6ab6b1307efe46930a720c7b5c6c0b72cb172bba) (@materializer)
* [ ] [`44828f4d1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/44828f4d11d95a021218ad431d80cc99ee9c02f0) (@materializer)
* [ ] [`1fb56d3b0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1fb56d3b052e7c5dcf56c2e22b6224d5fefe468b) (@materializer)
* [ ] [`a33bf435b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a33bf435b42df04beb42e36e156943c9c9223d0a) (@materializer)
* [ ] [`c00eeaa24` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c00eeaa248e0464501be6f0efe41aa02a4263209) (@materializer)
* [ ] [`a330eb674` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a330eb6741aaa96a59ac0e1de944cfb47ba57e74) (@materializer)
* [ ] [`4572d383b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4572d383bd56b52c3e83e1b8763ab1d27a08de97) (@materializer)
* [ ] [`8246581f8` release: bump to version v0.27.0-alpha.23](https://github.com/MaterializeInc/materialize/commit/8246581f8b64e4bba335b1d964e34b10d876213c) (@brennanvincent)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#14819 Consolidate compute controller](https://github.com/MaterializeInc/materialize/pull/14819) (@teskje)
* [ ] [#14862 [BREAKING] persist: update Shard|Writer|ReaderId serde to use string representation](https://github.com/MaterializeInc/materialize/pull/14862) (@pH14)
* [ ] [#14680 [sinks] Rename the `consistency_topic` field in the catalog](https://github.com/MaterializeInc/materialize/pull/14680) (@bkirwi)
* [ ] [#14891 expr: document preserves_uniqueness](https://github.com/MaterializeInc/materialize/pull/14891) (@mjibson)
* [ ] [#14750 sql: back Date by i32](https://github.com/MaterializeInc/materialize/pull/14750) (@mjibson)
* [ ] [#14676 compute: Replace Int64 with UInt64 for sys object](https://github.com/MaterializeInc/materialize/pull/14676) (@jkosh44)
* [ ] [#14884 sql: Standardize output of SHOW CREATE commands](https://github.com/MaterializeInc/materialize/pull/14884) (@jkosh44)
* [ ] [#14896 pgtest: add test for multiple DDL statements in one extended req](https://github.com/MaterializeInc/materialize/pull/14896) (@sploiselle)
* [ ] [#14790 sql: correlate statements to execute responses](https://github.com/MaterializeInc/materialize/pull/14790) (@sploiselle)
* [ ] [#14827 storage: make MzOffset 0-indexed](https://github.com/MaterializeInc/materialize/pull/14827) (@benesch)
* [ ] [#14882 zippy: Add replica support to Zippy](https://github.com/MaterializeInc/materialize/pull/14882) (@philip-stoev)
* [ ] [#14379 Initialize Timely lazily in computed](https://github.com/MaterializeInc/materialize/pull/14379) (@antiguru)
* [ ] [#14504 Rename `mz_materialization_dependencies` -> `mz_worker_materialization_dependencies`](https://github.com/MaterializeInc/materialize/pull/14504) (@chaas)
* [ ] [#14890 Add FROM SCHEMA to SHOW INDEXES sql command](https://github.com/MaterializeInc/materialize/pull/14890) (@chaas)
* [ ] [#14701 System tables rename global_id -> object_id](https://github.com/MaterializeInc/materialize/pull/14701) (@chaas)
* [ ] [#14907 persist: track key size, not blob size, in list_keys_and_metadata metric](https://github.com/MaterializeInc/materialize/pull/14907) (@danhhz)
* [ ] [#14900 [sinks] Fastforward asof in storage controller and rehydration](https://github.com/MaterializeInc/materialize/pull/14900) (@cjubb39)
* [ ] [#14908 persist-nightly: fix param name for maelstrom run](https://github.com/MaterializeInc/materialize/pull/14908) (@pH14)
* [ ] [#14912 sql: add hint to invalid broker string error](https://github.com/MaterializeInc/materialize/pull/14912) (@sploiselle)
* [ ] [#14916 audit-log: add ids to cluster operations](https://github.com/MaterializeInc/materialize/pull/14916) (@mjibson)
* [ ] [#14893 storage: attempt to deflake publication-with-publish-option.td](https://github.com/MaterializeInc/materialize/pull/14893) (@guswynn)
* [ ] [#14559 System tables: make all id columns suffixed with `_id`](https://github.com/MaterializeInc/materialize/pull/14559) (@chaas)
* [ ] [#14920 Disable pg-snapshot-resumption/03-while-storaged-down cluster smoke test](https://github.com/MaterializeInc/materialize/pull/14920) (@chaas)
* [ ] [#14923 compute-client: ignore flaking test](https://github.com/MaterializeInc/materialize/pull/14923) (@mjibson)
* [ ] [#14917 storage: in upsert operator, fix hashing of previous and current updates](https://github.com/MaterializeInc/materialize/pull/14917) (@aljoscha)
* [ ] [#14463 sql: add MzTimestamp type and mz_now function](https://github.com/MaterializeInc/materialize/pull/14463) (@mjibson)
* [ ] [#14901 orchestrator: drop created k8s service ](https://github.com/MaterializeInc/materialize/pull/14901) (@uce)
* [ ] [#14930 test: Fix syntax in instance size test](https://github.com/MaterializeInc/materialize/pull/14930) (@lluki)
* [ ] [#14818 make stderr log filter dynamically configurable](https://github.com/MaterializeInc/materialize/pull/14818) (@pH14)
* [ ] [#14931 build: fix warnings that pop up with Rust 1.64](https://github.com/MaterializeInc/materialize/pull/14931) (@aljoscha)
* [ ] [#14932 storage: in upsert source, be extra cautious about what we hash](https://github.com/MaterializeInc/materialize/pull/14932) (@aljoscha)
* [ ] [#14692 ore: refactor SSH key handling logic](https://github.com/MaterializeInc/materialize/pull/14692) (@andrioni)
* [ ] [#14928 adapter: init audit log with replicas](https://github.com/MaterializeInc/materialize/pull/14928) (@mjibson)
* [ ] [#14887 postgres-util: refactor implementation to use openssh instead](https://github.com/MaterializeInc/materialize/pull/14887) (@andrioni)
* [ ] [#14898 sql: Require Kafka connection for Kafka sources](https://github.com/MaterializeInc/materialize/pull/14898) (@jkosh44)
* [ ] [#14935 Remove unused method](https://github.com/MaterializeInc/materialize/pull/14935) (@jkosh44)
* [ ] [#14886 Improve the error message when a field is missing](https://github.com/MaterializeInc/materialize/pull/14886) (@bkirwi)
* [ ] [#14940 docker: add ssh to enviromentd and storage Docker images](https://github.com/MaterializeInc/materialize/pull/14940) (@andrioni)
* [ ] [#14939 bin/bump-version: add script to bump version during releases](https://github.com/MaterializeInc/materialize/pull/14939) (@benesch)
* [ ] [#14902 storage: fix potential kafka sink bug](https://github.com/MaterializeInc/materialize/pull/14902) (@aljoscha)
* [ ] [#14944 Remove unsafe mode requirement for ENVELOPE UPSERT](https://github.com/MaterializeInc/materialize/pull/14944) (@brennanvincent)
* [ ] [#14936 mzcompose: Update Redpanda to v22.2.3](https://github.com/MaterializeInc/materialize/pull/14936) (@BenPope)
* [ ] [#14942 Add support for LIKE filter in SHOW INDEXES command](https://github.com/MaterializeInc/materialize/pull/14942) (@chaas)
* [ ] [#14943 sql: Update output format of EXPLAIN TIMESTAMP](https://github.com/MaterializeInc/materialize/pull/14943) (@jkosh44)
* [ ] [#14948 persist: add a pointer to the lease expiration panics](https://github.com/MaterializeInc/materialize/pull/14948) (@danhhz)
* [ ] [#14929 Move introspection sources into mz_internal](https://github.com/MaterializeInc/materialize/pull/14929) (@teskje)
* [ ] [#14953 compute-client: ignore flaky test dataflow_description_protobuf_roundtrip](https://github.com/MaterializeInc/materialize/pull/14953) (@teskje)
* [ ] [#14954 sql: error instead of panic when Kafka connection does not have topic](https://github.com/MaterializeInc/materialize/pull/14954) (@sploiselle)
* [ ] [#14951 storage: add testdrive command to verify kafka committed offsets](https://github.com/MaterializeInc/materialize/pull/14951) (@guswynn)
* [ ] [#14945 persist: record storage usage as prometheus metrics](https://github.com/MaterializeInc/materialize/pull/14945) (@pH14)
* [ ] [#14816 persist: spin off separate compaction worker per shard](https://github.com/MaterializeInc/materialize/pull/14816) (@pH14)
* [ ] [#14895 [sinks] Start bringing Kafka docs up to date](https://github.com/MaterializeInc/materialize/pull/14895) (@bkirwi)
* [ ] [#14867 storage: implement the core bounded input reliance logic](https://github.com/MaterializeInc/materialize/pull/14867) (@guswynn)
* [ ] [#14926 [kafka sink] Don't emit updates until input frontier passes AS OF](https://github.com/MaterializeInc/materialize/pull/14926) (@cjubb39)
* [ ] [#14956 doc: document api/sql HTTP endpoint](https://github.com/MaterializeInc/materialize/pull/14956) (@sploiselle)
* [ ] [#14872 doc/user: Add mention of where to find generated key](https://github.com/MaterializeInc/materialize/pull/14872) (@ruf-io)
* [ ] [#14966 doc/user: add documentation for source sizes](https://github.com/MaterializeInc/materialize/pull/14966) (@benesch)
* [ ] [#14725 Join-Dependent Predicate Duplication](https://github.com/MaterializeInc/materialize/pull/14725) (@ggevay)
* [ ] [#14976 Update Rust version to 1.64](https://github.com/MaterializeInc/materialize/pull/14976) (@teskje)
* [ ] [#14955 Add human-readable output to `EXPLAIN TIMESTAMP`](https://github.com/MaterializeInc/materialize/pull/14955) (@brennanvincent)
* [ ] [#14360 Add Confluent Kafka integrations guide](https://github.com/MaterializeInc/materialize/pull/14360) (@bobbyiliev)
* [ ] [#14401 storage: expose Kafka offsets as uint8 rather than int4](https://github.com/MaterializeInc/materialize/pull/14401) (@benesch)
* [ ] [#14991 doc/user: minor updates to documentation mentioning sinks](https://github.com/MaterializeInc/materialize/pull/14991) (@morsapaes)
* [ ] [#14989 deps: upgrade criterion to v0.4.0](https://github.com/MaterializeInc/materialize/pull/14989) (@benesch)
* [ ] [#14990 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/14990) (@benesch)
* [ ] [#14997 ci: Do not fail the build on Buildkite Analytics failure](https://github.com/MaterializeInc/materialize/pull/14997) (@philip-stoev)
* [ ] [#13747 checks framework: Add Postgres sources](https://github.com/MaterializeInc/materialize/pull/13747) (@philip-stoev)
* [ ] [#14999 pg-cdc: Disable replica-identity-default-nothing.td](https://github.com/MaterializeInc/materialize/pull/14999) (@philip-stoev)
* [ ] [#14992 doc/user: make integration guide titles consistent](https://github.com/MaterializeInc/materialize/pull/14992) (@morsapaes)
* [ ] [#14993 doc/user: adapt language cheatsheets to nu Materialize](https://github.com/MaterializeInc/materialize/pull/14993) (@morsapaes)
* [ ] [#15001 doc/user: document `DROP` and `SHOW` commands for clusters and cluster replicas](https://github.com/MaterializeInc/materialize/pull/15001) (@morsapaes)
* [ ] [#14958 persist: cherrypick datadriven changes from #14704](https://github.com/MaterializeInc/materialize/pull/14958) (@pH14)
* [ ] [#14996 *: rename TAIL to SUBSCRIBE](https://github.com/MaterializeInc/materialize/pull/14996) (@benesch)
* [ ] [#14967 coord: Refactor determine_timestamp](https://github.com/MaterializeInc/materialize/pull/14967) (@jkosh44)
* [ ] [#14963 coord: Extract timeline logic from group commit](https://github.com/MaterializeInc/materialize/pull/14963) (@jkosh44)
* [ ] [#14995 adapter: export audit events to Segment](https://github.com/MaterializeInc/materialize/pull/14995) (@benesch)
* [ ] [#14934 System tables rename compute introspection table prefix from `materializations` to `compute`](https://github.com/MaterializeInc/materialize/pull/14934) (@chaas)
* [ ] [#14873 Get rid of non-upsert dbz](https://github.com/MaterializeInc/materialize/pull/14873) (@brennanvincent)
* [ ] [#14969 opentel: make tracing filter dynamic](https://github.com/MaterializeInc/materialize/pull/14969) (@pH14)
* [ ] [#14597 sql: parse PG CONNECTION DETAILS + PUBLICATION as options](https://github.com/MaterializeInc/materialize/pull/14597) (@sploiselle)
* [ ] [#15013 [system] Create mz_kafka_connections table](https://github.com/MaterializeInc/materialize/pull/15013) (@cjubb39)
* [ ] [#15015 deps: upgrade to latest segment release](https://github.com/MaterializeInc/materialize/pull/15015) (@benesch)
* [ ] [#15006 sql: remove default ENVELOPE DEBEZIUM for sinks](https://github.com/MaterializeInc/materialize/pull/15006) (@benesch)
* [ ] [#15019 cloudtest: Allow running .td files with testdrive](https://github.com/MaterializeInc/materialize/pull/15019) (@philip-stoev)
* [ ] [#15007 persist: batch part read metrics](https://github.com/MaterializeInc/materialize/pull/15007) (@pH14)
* [ ] [#14913 adapter: implement `EXPLAIN OPTIMIZER TRACE`](https://github.com/MaterializeInc/materialize/pull/14913) (@aalexandrov)
* [ ] [#15018 adapter: disallow unstable dependencies](https://github.com/MaterializeInc/materialize/pull/15018) (@teskje)
* [ ] [#15012 persist: more detailed batch write / compaction timing metrics](https://github.com/MaterializeInc/materialize/pull/15012) (@pH14)
* [ ] [#14964 Support date function: split out builtin catalog by item type](https://github.com/MaterializeInc/materialize/pull/14964) (@chaas)
* [ ] [#15004 Make a certain Testdrive error message less confusing.](https://github.com/MaterializeInc/materialize/pull/15004) (@brennanvincent)
* [ ] [#15016 adapter: rework sink progress topic exposure in system catalog](https://github.com/MaterializeInc/materialize/pull/15016) (@benesch)
* [ ] [#15002 test: add cloudtest-based test for ssh tunnels](https://github.com/MaterializeInc/materialize/pull/15002) (@andrioni)
* [ ] [#15014 storage: commit kafka offsets upstream](https://github.com/MaterializeInc/materialize/pull/15014) (@guswynn)
* [ ] [#14961 storage: bound pg status updates within the resumption frontier](https://github.com/MaterializeInc/materialize/pull/14961) (@guswynn)
* [ ] [#15025 test: fix merge skew on cloudtest](https://github.com/MaterializeInc/materialize/pull/15025) (@andrioni)
* [ ] [#14972 storage: fix some followups for the bir pr](https://github.com/MaterializeInc/materialize/pull/14972) (@guswynn)
* [ ] [#14369 coord: Fix builtin schema migration create order](https://github.com/MaterializeInc/materialize/pull/14369) (@jkosh44)
* [ ] [`6ab6b1307` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6ab6b1307efe46930a720c7b5c6c0b72cb172bba) (@materializer)
* [ ] [`44828f4d1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/44828f4d11d95a021218ad431d80cc99ee9c02f0) (@materializer)
* [ ] [`1fb56d3b0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1fb56d3b052e7c5dcf56c2e22b6224d5fefe468b) (@materializer)
* [ ] [`a33bf435b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a33bf435b42df04beb42e36e156943c9c9223d0a) (@materializer)
* [ ] [`c00eeaa24` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c00eeaa248e0464501be6f0efe41aa02a4263209) (@materializer)
* [ ] [`a330eb674` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a330eb6741aaa96a59ac0e1de944cfb47ba57e74) (@materializer)
* [ ] [`4572d383b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4572d383bd56b52c3e83e1b8763ab1d27a08de97) (@materializer)
* [ ] [`8246581f8` release: bump to version v0.27.0-alpha.23](https://github.com/MaterializeInc/materialize/commit/8246581f8b64e4bba335b1d964e34b10d876213c) (@brennanvincent)

**Comment by benesch** [comment]
@brennanvincent's commits LGTM.
