### ISSUE TITLE
[Evergreen] Support all postgres datatypes

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#15072]
https://www.postgresql.org/docs/current/datatype.html

## TODO
- [ ] add list of current supported/non-supported types
- [ ] highlight related features or workarounds for handling non-supported types
- [ ] track new requests/cases in this issue

## Workarounds
https://github.com/MaterializeInc/materialize/issues/15073

## Cases
- [ ] https://github.com/MaterializeInc/materialize/issues/14748
- [ ] https://github.com/MaterializeInc/materialize/issues/6818
- [ ] https://github.com/MaterializeInc/materialize/issues/6819
- [ ] https://github.com/MaterializeInc/materialize/issues/15803

**Comment by morsapaes** [comment]
We now explicitly document the types we **do** support [here](https://materialize.com/docs/sql/create-source/postgres/#supported-types), as well as the workaround to ingest unsupported types. Closing this issue since it hasn't been used, and the mentioned types are being tracked in the quarterly Storage mega tracker.
