### ISSUE TITLE
release: v0.27.0-alpha.24 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15168]
The following PRs in [`v0.27.0-alpha.24`](https://github.com/MaterializeInc/materialize/tree/v0.27.0-alpha.24) require review:
* [x] [#15042 ci: Increase timeout of testdrive jobs to 10 hours](https://github.com/MaterializeInc/materialize/pull/15042) (@philip-stoev)
* [x] [#15023 Fix limit test indentation](https://github.com/MaterializeInc/materialize/pull/15023) (@jkosh44)
* [x] [#15034 persist: fix `persistcli inspect` post incremental state](https://github.com/MaterializeInc/materialize/pull/15034) (@pH14)
* [x] [#15045 doc/user: add alias to `mz_now` function page](https://github.com/MaterializeInc/materialize/pull/15045) (@morsapaes)
* [x] [#15047 doc/user: update grammar for Postgres source](https://github.com/MaterializeInc/materialize/pull/15047) (@morsapaes)
* [x] [#15055 doc/user: adjust Kafka `CONNECTION` options](https://github.com/MaterializeInc/materialize/pull/15055) (@morsapaes)
* [x] [#15064 ci: Disable the testdrive-aarch64 Nightly job](https://github.com/MaterializeInc/materialize/pull/15064) (@philip-stoev)
* [x] [#15081 doc/user: adjust Kafka connection options for sinks](https://github.com/MaterializeInc/materialize/pull/15081) (@morsapaes)
* [x] [#15085 doc/user: add note about changing active cluster to `CREATE CLUSTER`](https://github.com/MaterializeInc/materialize/pull/15085) (@morsapaes)
* [x] [#15088 cloudtest: fix fallout from changing testdrive reset semantics](https://github.com/MaterializeInc/materialize/pull/15088) (@sploiselle)
* [x] [#15097 doc/user: remove operations docs from main menu](https://github.com/MaterializeInc/materialize/pull/15097) (@morsapaes)
* [x] [#15103 doc/user: minimal updates to What is Materialize? page](https://github.com/MaterializeInc/materialize/pull/15103) (@morsapaes)
* [x] [#15111 environmentd: move internal catalog API to internal HTTP port](https://github.com/MaterializeInc/materialize/pull/15111) (@benesch)
* [x] [#15114 doc/user: prepare documentation for switch](https://github.com/MaterializeInc/materialize/pull/15114) (@morsapaes)
* [x] [#15115 doc/user: adapt get started guide](https://github.com/MaterializeInc/materialize/pull/15115) (@morsapaes)
* [x] [#15101 doc/user: revamp architecture overview](https://github.com/MaterializeInc/materialize/pull/15101) (@morsapaes)
* [x] [#15096 mzcompose: Add support for Minio S3-compatible object storage](https://github.com/MaterializeInc/materialize/pull/15096) (@philip-stoev)
* [x] [#14970 fix(mz) app-passwords replacing secrets and client_id. ](https://github.com/MaterializeInc/materialize/pull/14970) (@joacoc)
* [x] [#15142 persist: inspect cli tools for blob counts / unreferenced blobs](https://github.com/MaterializeInc/materialize/pull/15142) (@pH14)
* [x] [#15147 bin/cluster-{dev,psql,reset}: remove](https://github.com/MaterializeInc/materialize/pull/15147) (@benesch)
* [x] [#15156 platform checks: Add upgrade scenarios from v0.27.0-alpha.23](https://github.com/MaterializeInc/materialize/pull/15156) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`9549de339` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9549de339e1459555313c447abe8c70878c6c4ec) (@materializer)
* [x] [`a7f4ffd36` fix error message](https://github.com/MaterializeInc/materialize/commit/a7f4ffd3631de71f6de74195efeb36ab85a9f124) (@brennanvincent)
* [x] [`bdc13c4fc` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bdc13c4fc54f9a28b6dc5e5b9ef7407908ae0725) (@materializer)
* [x] [`80e33a3c7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/80e33a3c7d0405afc8316af1db780a52d845e12e) (@materializer)
* [x] [`521727b31` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/521727b315d6888e6be1aa7dd1707a2779342798) (@materializer)
* [x] [`5c13c9202` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5c13c9202b875ca5cb7f1a98709cca54fdd75f62) (@materializer)
* [x] [`ead0c5479` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ead0c54790bf6876b82f7dd4b807b9539e323234) (@materializer)
* [x] [`3b8ceba49` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3b8ceba49c50fbbf8320bf06e82b7ab525317a4b) (@materializer)
* [x] [`4d0429880` release: bump to version v0.27.0-alpha.24](https://github.com/MaterializeInc/materialize/commit/4d04298807367f7d3397f10be59eee50aeb7002c) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15027 remove kafka's ENABLE AUTO COMMIT](https://github.com/MaterializeInc/materialize/pull/15027) (@guswynn)
* [ ] [#15017 storage: rename IngestSources/ExportSinks => CreateSources/CreateSinks](https://github.com/MaterializeInc/materialize/pull/15017) (@benesch)
* [ ] [#15031 adapter: segment: send org_id as context.groupId](https://github.com/MaterializeInc/materialize/pull/15031) (@ahelium)
* [ ] [#15040 avro: prevent panic during time encoding](https://github.com/MaterializeInc/materialize/pull/15040) (@mjibson)
* [ ] [#15039 doc: replace mz_logical_timestamp with mz_now](https://github.com/MaterializeInc/materialize/pull/15039) (@mjibson)
* [ ] [#15042 ci: Increase timeout of testdrive jobs to 10 hours](https://github.com/MaterializeInc/materialize/pull/15042) (@philip-stoev)
* [ ] [#15043 docs: remove vestiges of `DEBEZIUM UPSERT` from docs](https://github.com/MaterializeInc/materialize/pull/15043) (@aljoscha)
* [ ] [#15023 Fix limit test indentation](https://github.com/MaterializeInc/materialize/pull/15023) (@jkosh44)
* [ ] [#15034 persist: fix `persistcli inspect` post incremental state](https://github.com/MaterializeInc/materialize/pull/15034) (@pH14)
* [ ] [#15045 doc/user: add alias to `mz_now` function page](https://github.com/MaterializeInc/materialize/pull/15045) (@morsapaes)
* [ ] [#15047 doc/user: update grammar for Postgres source](https://github.com/MaterializeInc/materialize/pull/15047) (@morsapaes)
* [ ] [#15049 compute-client,adapter: remove `Concrete` prefixes](https://github.com/MaterializeInc/materialize/pull/15049) (@teskje)
* [ ] [#14880 Fix replicated compaction](https://github.com/MaterializeInc/materialize/pull/14880) (@teskje)
* [ ] [#15050 sql: Fix parser create error message](https://github.com/MaterializeInc/materialize/pull/15050) (@jkosh44)
* [ ] [#15041 sql: rename mztimestamp type to mz_timestamp](https://github.com/MaterializeInc/materialize/pull/15041) (@benesch)
* [ ] [#15054 [github] Reference actual name of T-proto label](https://github.com/MaterializeInc/materialize/pull/15054) (@cjubb39)
* [ ] [#15051 doc/user: indicate that debezium-enveloped sources may need larger sizes](https://github.com/MaterializeInc/materialize/pull/15051) (@benesch)
* [ ] [#14001 storage: shard write work in `persist_sink`](https://github.com/MaterializeInc/materialize/pull/14001) (@aljoscha)
* [ ] [#15053 [sinks] Rename some lingering consistency refernces to progress](https://github.com/MaterializeInc/materialize/pull/15053) (@cjubb39)
* [ ] [#15030 catalog: Refactor catalog transactions](https://github.com/MaterializeInc/materialize/pull/15030) (@jkosh44)
* [ ] [#15057 release: bump to version v0.27.0-alpha.23.post](https://github.com/MaterializeInc/materialize/pull/15057) (@brennanvincent)
* [ ] [#15059 testdrive: improve avro debugging and redo](https://github.com/MaterializeInc/materialize/pull/15059) (@mjibson)
* [ ] [#15055 doc/user: adjust Kafka `CONNECTION` options](https://github.com/MaterializeInc/materialize/pull/15055) (@morsapaes)
* [ ] [#15063 avro: correctly describe interval schema](https://github.com/MaterializeInc/materialize/pull/15063) (@mjibson)
* [ ] [#15064 ci: Disable the testdrive-aarch64 Nightly job](https://github.com/MaterializeInc/materialize/pull/15064) (@philip-stoev)
* [ ] [#14973 `undistribute_and_or` should prefer absorptions](https://github.com/MaterializeInc/materialize/pull/14973) (@ggevay)
* [ ] [#15069 Docs: Remove extra characters and strings in HTTP API](https://github.com/MaterializeInc/materialize/pull/15069) (@joacoc)
* [ ] [#15071 doc: fix python guide connection example](https://github.com/MaterializeInc/materialize/pull/15071) (@bobbyiliev)
* [ ] [#15075 Add `--dev` flag to cloudtest](https://github.com/MaterializeInc/materialize/pull/15075) (@brennanvincent)
* [ ] [#15076 [cloudtest] Actually use the dev hash](https://github.com/MaterializeInc/materialize/pull/15076) (@brennanvincent)
* [ ] [#15080 [sink] Log specific sink that causes primary key error](https://github.com/MaterializeInc/materialize/pull/15080) (@cjubb39)
* [ ] [#14965 [sinks] More error handling in the Kafka sink](https://github.com/MaterializeInc/materialize/pull/14965) (@bkirwi)
* [ ] [#15081 doc/user: adjust Kafka connection options for sinks](https://github.com/MaterializeInc/materialize/pull/15081) (@morsapaes)
* [ ] [#15085 doc/user: add note about changing active cluster to `CREATE CLUSTER`](https://github.com/MaterializeInc/materialize/pull/15085) (@morsapaes)
* [ ] [#15078 testdrive: remove undo](https://github.com/MaterializeInc/materialize/pull/15078) (@sploiselle)
* [ ] [#15083 [kafka resumption test] Re-enable timeout hold failure mode](https://github.com/MaterializeInc/materialize/pull/15083) (@cjubb39)
* [ ] [#15077 sql: stabilize ALTER SOURCE](https://github.com/MaterializeInc/materialize/pull/15077) (@benesch)
* [ ] [#15088 cloudtest: fix fallout from changing testdrive reset semantics](https://github.com/MaterializeInc/materialize/pull/15088) (@sploiselle)
* [ ] [#15087 interchange: support protobuf unsigned types](https://github.com/MaterializeInc/materialize/pull/15087) (@benesch)
* [ ] [#15097 doc/user: remove operations docs from main menu](https://github.com/MaterializeInc/materialize/pull/15097) (@morsapaes)
* [ ] [#15091 testdrive: clean up kafka state at beginning of test script](https://github.com/MaterializeInc/materialize/pull/15091) (@benesch)
* [ ] [#15103 doc/user: minimal updates to What is Materialize? page](https://github.com/MaterializeInc/materialize/pull/15103) (@morsapaes)
* [ ] [#14889 storage: compact the remap shard to just before the resumption frontier](https://github.com/MaterializeInc/materialize/pull/14889) (@guswynn)
* [ ] [#15062 doc/user: update dbt integration page](https://github.com/MaterializeInc/materialize/pull/15062) (@ahelium)
* [ ] [#15099 compute-client: fix multi-process frontier tracking](https://github.com/MaterializeInc/materialize/pull/15099) (@teskje)
* [ ] [#14975 `inline_literal_constraints` should also kick in for complex expressions](https://github.com/MaterializeInc/materialize/pull/14975) (@ggevay)
* [ ] [#15106 Refactor system catalog docs into separate pages per schema](https://github.com/MaterializeInc/materialize/pull/15106) (@chaas)
* [ ] [#15109 testdrive: set variables at runtime](https://github.com/MaterializeInc/materialize/pull/15109) (@sploiselle)
* [ ] [#15102 Enable more clippy lints](https://github.com/MaterializeInc/materialize/pull/15102) (@teskje)
* [ ] [#15111 environmentd: move internal catalog API to internal HTTP port](https://github.com/MaterializeInc/materialize/pull/15111) (@benesch)
* [ ] [#15110 Using schema file cleanup](https://github.com/MaterializeInc/materialize/pull/15110) (@sploiselle)
* [ ] [#15114 doc/user: prepare documentation for switch](https://github.com/MaterializeInc/materialize/pull/15114) (@morsapaes)
* [ ] [#15116 pgwire: force internal SQL connections to use user mz_system](https://github.com/MaterializeInc/materialize/pull/15116) (@benesch)
* [ ] [#15115 doc/user: adapt get started guide](https://github.com/MaterializeInc/materialize/pull/15115) (@morsapaes)
* [ ] [#15101 doc/user: revamp architecture overview](https://github.com/MaterializeInc/materialize/pull/15101) (@morsapaes)
* [ ] [#15121 update readme to remove residual binary references](https://github.com/MaterializeInc/materialize/pull/15121) (@sjwiesman)
* [ ] [#15133 limits test: use correct compute port number](https://github.com/MaterializeInc/materialize/pull/15133) (@lluki)
* [ ] [#15096 mzcompose: Add support for Minio S3-compatible object storage](https://github.com/MaterializeInc/materialize/pull/15096) (@philip-stoev)
* [ ] [#15127 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.24.80 to 1.24.84 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15127) (@dependabot[bot])
* [ ] [#15125 build(deps): bump mypy from 0.961 to 0.981 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15125) (@dependabot[bot])
* [ ] [#15123 build(deps): bump setuptools from 65.4.0 to 65.4.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15123) (@dependabot[bot])
* [ ] [#15122 build(deps): bump types-pyyaml from 6.0.11 to 6.0.12 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15122) (@dependabot[bot])
* [ ] [#15130 doc/user: switch build from `/docs/unstable` to `/docs`](https://github.com/MaterializeInc/materialize/pull/15130) (@morsapaes)
* [ ] [#15124 build(deps): bump boto3 from 1.24.80 to 1.24.84 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15124) (@dependabot[bot])
* [ ] [#15126 build(deps): bump types-setuptools from 65.3.0 to 65.4.0.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15126) (@dependabot[bot])
* [ ] [#14970 fix(mz) app-passwords replacing secrets and client_id. ](https://github.com/MaterializeInc/materialize/pull/14970) (@joacoc)
* [ ] [#15142 persist: inspect cli tools for blob counts / unreferenced blobs](https://github.com/MaterializeInc/materialize/pull/15142) (@pH14)
* [ ] [#15148 testdrive: absorb schema selection tests](https://github.com/MaterializeInc/materialize/pull/15148) (@benesch)
* [ ] [#15147 bin/cluster-{dev,psql,reset}: remove](https://github.com/MaterializeInc/materialize/pull/15147) (@benesch)
* [ ] [#15108 storage: add test to assert we restart sources at a reasonable resume_upper](https://github.com/MaterializeInc/materialize/pull/15108) (@guswynn)
* [ ] [#15158 limits test: Fix port typo](https://github.com/MaterializeInc/materialize/pull/15158) (@lluki)
* [ ] [#15139 `None` the initial `JoinClosure` when its MFP is identity](https://github.com/MaterializeInc/materialize/pull/15139) (@ggevay)
* [ ] [#15157 doc/user: cleanup links in system-catalog](https://github.com/MaterializeInc/materialize/pull/15157) (@teskje)
* [ ] [#15140 compute controller: don't crash on hydration](https://github.com/MaterializeInc/materialize/pull/15140) (@lluki)
* [ ] [#15105 persist: fix handling of empty batches in compaction](https://github.com/MaterializeInc/materialize/pull/15105) (@pH14)
* [ ] [#15156 platform checks: Add upgrade scenarios from v0.27.0-alpha.23](https://github.com/MaterializeInc/materialize/pull/15156) (@philip-stoev)
* [ ] [#15161 adapter: add metrics for query counts and active sessions/subscribes](https://github.com/MaterializeInc/materialize/pull/15161) (@benesch)
* [ ] [`9549de339` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9549de339e1459555313c447abe8c70878c6c4ec) (@materializer)
* [ ] [`a7f4ffd36` fix error message](https://github.com/MaterializeInc/materialize/commit/a7f4ffd3631de71f6de74195efeb36ab85a9f124) (@brennanvincent)
* [ ] [`bdc13c4fc` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bdc13c4fc54f9a28b6dc5e5b9ef7407908ae0725) (@materializer)
* [ ] [`80e33a3c7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/80e33a3c7d0405afc8316af1db780a52d845e12e) (@materializer)
* [ ] [`521727b31` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/521727b315d6888e6be1aa7dd1707a2779342798) (@materializer)
* [ ] [`5c13c9202` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5c13c9202b875ca5cb7f1a98709cca54fdd75f62) (@materializer)
* [ ] [`ead0c5479` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ead0c54790bf6876b82f7dd4b807b9539e323234) (@materializer)
* [ ] [`3b8ceba49` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3b8ceba49c50fbbf8320bf06e82b7ab525317a4b) (@materializer)
* [ ] [`4d0429880` release: bump to version v0.27.0-alpha.24](https://github.com/MaterializeInc/materialize/commit/4d04298807367f7d3397f10be59eee50aeb7002c) (@benesch)

**Comment by benesch** [comment]
The commits that are not mine LGTM.

**Comment by guswynn** [comment]
rest LGTM
