### ISSUE TITLE
release: v0.27.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15346]
The following PRs in [`v0.27.0`](https://github.com/MaterializeInc/materialize/tree/v0.27.0) require review:
* [x] [#15180 ci: Increase the timeout of the replica isolation test](https://github.com/MaterializeInc/materialize/pull/15180) (@philip-stoev)
* [ ] [#15174 release: bump to version v0.27.0-alpha.24.post](https://github.com/MaterializeInc/materialize/pull/15174) (@benesch)
* [x] [#15020 ci: Add complete testdrive run inside K8s](https://github.com/MaterializeInc/materialize/pull/15020) (@philip-stoev)
* [x] [#15210 cloudtest: Run Platform Checks upgrade in K8s](https://github.com/MaterializeInc/materialize/pull/15210) (@philip-stoev)
* [x] [#15219 remove inadvertently committed scratch notes](https://github.com/MaterializeInc/materialize/pull/15219) (@sploiselle)
* [x] [#15239 clodutest: use --orchestrator-kubernetes-image-pull-policy=if-not-pre…](https://github.com/MaterializeInc/materialize/pull/15239) (@philip-stoev)
* [x] [#15240 cloudtest: Add Debezium to cloudtest](https://github.com/MaterializeInc/materialize/pull/15240) (@philip-stoev)
* [ ] [#15250 doc/user: fix some lingering issues with LTS switch](https://github.com/MaterializeInc/materialize/pull/15250) (@benesch)
* [ ] [#15254 ci/deploy: try again to fix docs deployment](https://github.com/MaterializeInc/materialize/pull/15254) (@benesch)
* [ ] [#15263 testdrive: remove vestiges of action building](https://github.com/MaterializeInc/materialize/pull/15263) (@benesch)
* [ ] [#15264 testdrive: further cleanups](https://github.com/MaterializeInc/materialize/pull/15264) (@benesch)
* [ ] [#15267 adapter: consistentize a few more catalog tables](https://github.com/MaterializeInc/materialize/pull/15267) (@benesch)
* [ ] [#15273 sql: add warning to PRIMARY KEY ... NOT ENFORCED unsafe-mode restriction](https://github.com/MaterializeInc/materialize/pull/15273) (@benesch)
* [ ] [#15295 deps: amalgamate dependabot PRs](https://github.com/MaterializeInc/materialize/pull/15295) (@benesch)
* [x] [#15301 zippy: Add Postgres CDC sources in Zippy](https://github.com/MaterializeInc/materialize/pull/15301) (@philip-stoev)
* [x] [#15306 ci,test: Remove residual mentions of ENVELOPE DEBEZIUM UPSERT](https://github.com/MaterializeInc/materialize/pull/15306) (@philip-stoev)
* [ ] [#15312 sql: require SIZE option for sources and sinks](https://github.com/MaterializeInc/materialize/pull/15312) (@benesch)
* [x] [#15326 testdrive: Make sure 'default_replica' always exists](https://github.com/MaterializeInc/materialize/pull/15326) (@philip-stoev)
* [x] [#15313 persist: add client timeouts to S3 API calls](https://github.com/MaterializeInc/materialize/pull/15313) (@pH14)
* [x] [#15330 ci: Add missing dependency for the checks-restart-redpanda job](https://github.com/MaterializeInc/materialize/pull/15330) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`84c10cb15` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/84c10cb15881dcb8382504358702a2b18f5c85a9) (@materializer)
* [x] [`b8bb32ab1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b8bb32ab1f8e00b4c932b071c59e14e08e2bd681) (@materializer)
* [x] [`347a2508e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/347a2508e5148d776982e724d53a4fb3738dd12a) (@materializer)
* [x] [`c88e21836` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c88e218362399cf64c6eba66a782d377e978ebf9) (@materializer)
* [ ] [`b268e7bf3` adapter: don't allow subscribing to arranged log sources](https://github.com/MaterializeInc/materialize/commit/b268e7bf3b1c7ea31eccd9d2ec9c78bd117e3a09) (@benesch)
* [ ] [`636b78a66` adapter: distinguish between arranged/persisted logs](https://github.com/MaterializeInc/materialize/commit/636b78a663b566d8d618c33bae800a310089519b) (@benesch)
* [x] [`e6aa08c50` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e6aa08c5022d230ab83f5d43d57cc81efc6481ec) (@materializer)
* [x] [`10468ba3f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/10468ba3f9ea52f899b01fa39b7420f030792f87) (@materializer)
* [x] [`441fd9703` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/441fd97038fe61dda7014820d9f0801e1891d8e4) (@materializer)
* [x] [`33daee53a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/33daee53a7a9100057279be492d129e2b31ae3d5) (@materializer)
* [ ] [`218138173` release: bump to version v0.27.0](https://github.com/MaterializeInc/materialize/commit/218138173e6ac42252b7fe5884d43132f4b61214) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15154 compute-client: align explain timestamp](https://github.com/MaterializeInc/materialize/pull/15154) (@mjibson)
* [ ] [#15048 Introspection configuration per replica](https://github.com/MaterializeInc/materialize/pull/15048) (@teskje)
* [ ] [#15119 adapter,repr: finalize `EXPLAIN AS TEXT` rendering (alternative)](https://github.com/MaterializeInc/materialize/pull/15119) (@aalexandrov)
* [ ] [#15146 [sinks] create sinks in storaged before in catalog](https://github.com/MaterializeInc/materialize/pull/15146) (@cjubb39)
* [ ] [#15028 storage: start pg status updates with initial lsn](https://github.com/MaterializeInc/materialize/pull/15028) (@guswynn)
* [ ] [#15170 build: fix dev-web feature](https://github.com/MaterializeInc/materialize/pull/15170) (@benesch)
* [ ] [#15092 sql,adapter: expose source sizes in mz_sources and SHOW SOURCES](https://github.com/MaterializeInc/materialize/pull/15092) (@benesch)
* [ ] [#15060 storage: support non-ordered batches in reclock_operator](https://github.com/MaterializeInc/materialize/pull/15060) (@guswynn)
* [ ] [#15153 [sinks] move building sink connection into storage crate](https://github.com/MaterializeInc/materialize/pull/15153) (@cjubb39)
* [ ] [#15176 Revert "[sinks] create sinks in storaged before in catalog"](https://github.com/MaterializeInc/materialize/pull/15176) (@cjubb39)
* [ ] [#15180 ci: Increase the timeout of the replica isolation test](https://github.com/MaterializeInc/materialize/pull/15180) (@philip-stoev)
* [ ] [#15189 Fix subscribe tracking](https://github.com/MaterializeInc/materialize/pull/15189) (@teskje)
* [ ] [#15182 storage: in reclock.rs, remove outdated allow(dead_code) stanzas](https://github.com/MaterializeInc/materialize/pull/15182) (@aljoscha)
* [ ] [#15174 release: bump to version v0.27.0-alpha.24.post](https://github.com/MaterializeInc/materialize/pull/15174) (@benesch)
* [ ] [#15035 coord: Update builtin fingerprint representation](https://github.com/MaterializeInc/materialize/pull/15035) (@jkosh44)
* [ ] [#15100 Rename "compute instance replica" to "compute replica"](https://github.com/MaterializeInc/materialize/pull/15100) (@teskje)
* [ ] [#15032 sql: check all timestamps for a valid range](https://github.com/MaterializeInc/materialize/pull/15032) (@mjibson)
* [ ] [#15011 Rename mz_peek_active system table to mz_active_peeks](https://github.com/MaterializeInc/materialize/pull/15011) (@chaas)
* [ ] [#15112 repr: replace strconv-based parse_duration with humantime crate](https://github.com/MaterializeInc/materialize/pull/15112) (@benesch)
* [ ] [#15113 sql: remove the last of the legacy with option handling](https://github.com/MaterializeInc/materialize/pull/15113) (@benesch)
* [ ] [#15198 storage: heartbeat write handles in (compute) persist_sink](https://github.com/MaterializeInc/materialize/pull/15198) (@aljoscha)
* [ ] [#15197 environmentd: improve HTTP servers](https://github.com/MaterializeInc/materialize/pull/15197) (@benesch)
* [ ] [#15159 foundation for multi-output sources](https://github.com/MaterializeInc/materialize/pull/15159) (@petrosagg)
* [ ] [#15086 Improve UX of histogram system tables](https://github.com/MaterializeInc/materialize/pull/15086) (@chaas)
* [ ] [#15052 storage: `StorageCollection` support + shard ID mappings](https://github.com/MaterializeInc/materialize/pull/15052) (@sploiselle)
* [ ] [#15205 adapter,expr: reject unmaterializable functions in WHERE clauses](https://github.com/MaterializeInc/materialize/pull/15205) (@benesch)
* [ ] [#15020 ci: Add complete testdrive run inside K8s](https://github.com/MaterializeInc/materialize/pull/15020) (@philip-stoev)
* [ ] [#15183 `tpch.slt` -- Remove PRIMARY KEY annotations and add explicit `pk_` indexes](https://github.com/MaterializeInc/materialize/pull/15183) (@ggevay)
* [ ] [#15210 cloudtest: Run Platform Checks upgrade in K8s](https://github.com/MaterializeInc/materialize/pull/15210) (@philip-stoev)
* [ ] [#15194 Add SIZE Parameter to CREATE SINK](https://github.com/MaterializeInc/materialize/pull/15194) (@andrioni)
* [ ] [#15187 compute: use explicit wrapping in float reduction](https://github.com/MaterializeInc/materialize/pull/15187) (@lluki)
* [ ] [#15207 adapter: add view to compute storage usage by object](https://github.com/MaterializeInc/materialize/pull/15207) (@benesch)
* [ ] [#15219 remove inadvertently committed scratch notes](https://github.com/MaterializeInc/materialize/pull/15219) (@sploiselle)
* [ ] [#15175 Fix memory visualizers to work with multiple clusters/replicas](https://github.com/MaterializeInc/materialize/pull/15175) (@chaas)
* [ ] [#15220 catalog: Remove unsigned ints from pg schemas](https://github.com/MaterializeInc/materialize/pull/15220) (@jkosh44)
* [ ] [#15134 Revisions to Troubleshooting docs motivated by Materialize Platform changes](https://github.com/MaterializeInc/materialize/pull/15134) (@vmarcos)
* [ ] [#15217 adapter,sql: expose sink sizes in mz_sinks and SHOW SINKS](https://github.com/MaterializeInc/materialize/pull/15217) (@andrioni)
* [ ] [#15224 repr: fix flaky `test_optimizer_trace` test](https://github.com/MaterializeInc/materialize/pull/15224) (@aalexandrov)
* [ ] [#15190 storage: convert pg sources to multi-output sources](https://github.com/MaterializeInc/materialize/pull/15190) (@petrosagg)
* [ ] [#15231 storage: avoid holding the remap output handle across an await](https://github.com/MaterializeInc/materialize/pull/15231) (@guswynn)
* [ ] [#15232 sql: don't crash on EXPLAIN (SHOW ...)](https://github.com/MaterializeInc/materialize/pull/15232) (@benesch)
* [ ] [#15238 test: convert mz_storage_usage_by_shard tests to mz_storage_usage](https://github.com/MaterializeInc/materialize/pull/15238) (@sploiselle)
* [ ] [#15239 clodutest: use --orchestrator-kubernetes-image-pull-policy=if-not-pre…](https://github.com/MaterializeInc/materialize/pull/15239) (@philip-stoev)
* [ ] [#15240 cloudtest: Add Debezium to cloudtest](https://github.com/MaterializeInc/materialize/pull/15240) (@philip-stoev)
* [ ] [#15212 adapter: prepare cluster replica tables for stabilization](https://github.com/MaterializeInc/materialize/pull/15212) (@teskje)
* [ ] [#15250 doc/user: fix some lingering issues with LTS switch](https://github.com/MaterializeInc/materialize/pull/15250) (@benesch)
* [ ] [#15233 [sinks] Add pending interface to storage exports](https://github.com/MaterializeInc/materialize/pull/15233) (@cjubb39)
* [ ] [#15247 storage: convert loadgen sources to multi-output sources](https://github.com/MaterializeInc/materialize/pull/15247) (@petrosagg)
* [ ] [#15228 [sinks] async retry creating sink connection on startup](https://github.com/MaterializeInc/materialize/pull/15228) (@cjubb39)
* [ ] [#15235 [sinks] create sinks in storaged before in catalog](https://github.com/MaterializeInc/materialize/pull/15235) (@cjubb39)
* [ ] [#15254 ci/deploy: try again to fix docs deployment](https://github.com/MaterializeInc/materialize/pull/15254) (@benesch)
* [ ] [#15245 storage: batch stash writes in create_collections](https://github.com/MaterializeInc/materialize/pull/15245) (@teskje)
* [ ] [#15252 storage: remove connection_id from ingestion and sink](https://github.com/MaterializeInc/materialize/pull/15252) (@guswynn)
* [ ] [#15256 load generator: make `id` column a key](https://github.com/MaterializeInc/materialize/pull/15256) (@sploiselle)
* [ ] [#15261 adapter: robustify references to arranged log sources](https://github.com/MaterializeInc/materialize/pull/15261) (@benesch)
* [ ] [#15259 storage: add the connection id to the kafka group id](https://github.com/MaterializeInc/materialize/pull/15259) (@guswynn)
* [ ] [#15263 testdrive: remove vestiges of action building](https://github.com/MaterializeInc/materialize/pull/15263) (@benesch)
* [ ] [#15265 doc/user: note SUBSCRIBE limitation in troubleshooting docs](https://github.com/MaterializeInc/materialize/pull/15265) (@benesch)
* [ ] [#15264 testdrive: further cleanups](https://github.com/MaterializeInc/materialize/pull/15264) (@benesch)
* [ ] [#14097 platform checks: Add a scenario that restarts Redpanda](https://github.com/MaterializeInc/materialize/pull/14097) (@philip-stoev)
* [ ] [#15136 environmentd: remove deprecated sql parameter from HTTP API](https://github.com/MaterializeInc/materialize/pull/15136) (@benesch)
* [ ] [#15117 adapter,pgwire,environmentd: generalize notice handling](https://github.com/MaterializeInc/materialize/pull/15117) (@benesch)
* [ ] [#15266 storage: refactor load generator batches](https://github.com/MaterializeInc/materialize/pull/15266) (@mjibson)
* [ ] [#15267 adapter: consistentize a few more catalog tables](https://github.com/MaterializeInc/materialize/pull/15267) (@benesch)
* [ ] [#15273 sql: add warning to PRIMARY KEY ... NOT ENFORCED unsafe-mode restriction](https://github.com/MaterializeInc/materialize/pull/15273) (@benesch)
* [ ] [#15276 build(deps): bump const_format from 0.2.26 to 0.2.28](https://github.com/MaterializeInc/materialize/pull/15276) (@dependabot[bot])
* [ ] [#15278 build(deps): bump uuid from 1.1.2 to 1.2.1](https://github.com/MaterializeInc/materialize/pull/15278) (@dependabot[bot])
* [ ] [#15279 build(deps): bump ubuntu from jammy-20220815 to jammy-20221003 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15279) (@dependabot[bot])
* [ ] [#15281 build(deps): bump tokio from 1.19.2 to 1.20.2](https://github.com/MaterializeInc/materialize/pull/15281) (@dependabot[bot])
* [ ] [#15291 build(deps): bump openssl-sys from 0.9.75 to 0.9.76](https://github.com/MaterializeInc/materialize/pull/15291) (@dependabot[bot])
* [ ] [#15290 build(deps): bump ubuntu from jammy-20220815 to jammy-20221003 in /misc/images/ubuntu-base](https://github.com/MaterializeInc/materialize/pull/15290) (@dependabot[bot])
* [ ] [#15295 deps: amalgamate dependabot PRs](https://github.com/MaterializeInc/materialize/pull/15295) (@benesch)
* [ ] [#15301 zippy: Add Postgres CDC sources in Zippy](https://github.com/MaterializeInc/materialize/pull/15301) (@philip-stoev)
* [ ] [#15306 ci,test: Remove residual mentions of ENVELOPE DEBEZIUM UPSERT](https://github.com/MaterializeInc/materialize/pull/15306) (@philip-stoev)
* [ ] [#15227 Reconcile materialized views](https://github.com/MaterializeInc/materialize/pull/15227) (@frankmcsherry)
* [ ] [#15237 storage: switch reclocking data format to rows](https://github.com/MaterializeInc/materialize/pull/15237) (@petrosagg)
* [ ] [#15302 `CanonicalizeMfp` before `JoinImplementation`](https://github.com/MaterializeInc/materialize/pull/15302) (@ggevay)
* [ ] [#15305 sql: add support for REMOTE on CREATE SINK](https://github.com/MaterializeInc/materialize/pull/15305) (@andrioni)
* [ ] [#15271 doc/user: fix documentation of sink SNAPSHOT option](https://github.com/MaterializeInc/materialize/pull/15271) (@benesch)
* [ ] [#15315 sql: rename the schema presented for auction load generator sources](https://github.com/MaterializeInc/materialize/pull/15315) (@petrosagg)
* [ ] [#15318 sql: refactor load gen ast -> storage calls](https://github.com/MaterializeInc/materialize/pull/15318) (@mjibson)
* [ ] [#15269 doc/user: polish v0.27.0 release notes](https://github.com/MaterializeInc/materialize/pull/15269) (@benesch)
* [ ] [#15324 doc/user: add `https://` prepend to CSR connection examples](https://github.com/MaterializeInc/materialize/pull/15324) (@morsapaes)
* [ ] [#15323 sql: even more loadgen refactors](https://github.com/MaterializeInc/materialize/pull/15323) (@mjibson)
* [ ] [#15312 sql: require SIZE option for sources and sinks](https://github.com/MaterializeInc/materialize/pull/15312) (@benesch)
* [ ] [#15316 adapter: Add system compute instances](https://github.com/MaterializeInc/materialize/pull/15316) (@jkosh44)
* [ ] [#15322 sql-parser: remove VIEWS from error message about mistyped CREATE](https://github.com/MaterializeInc/materialize/pull/15322) (@benesch)
* [ ] [#15326 testdrive: Make sure 'default_replica' always exists](https://github.com/MaterializeInc/materialize/pull/15326) (@philip-stoev)
* [ ] [#15325 Make show indexes consistent with other show commands](https://github.com/MaterializeInc/materialize/pull/15325) (@chaas)
* [ ] [#15314 replicated: track frontiers of arranged logs](https://github.com/MaterializeInc/materialize/pull/15314) (@teskje)
* [ ] [#15268 Fix some issues in `ColumnKnowledge`](https://github.com/MaterializeInc/materialize/pull/15268) (@ggevay)
* [ ] [#15313 persist: add client timeouts to S3 API calls](https://github.com/MaterializeInc/materialize/pull/15313) (@pH14)
* [ ] [#15329 sql-parser: parse subsources before WITH block](https://github.com/MaterializeInc/materialize/pull/15329) (@andrioni)
* [ ] [#15331 Tweaks in literal constraints detection](https://github.com/MaterializeInc/materialize/pull/15331) (@ggevay)
* [ ] [#15334 test: Fix merge skew with defualt replica](https://github.com/MaterializeInc/materialize/pull/15334) (@jkosh44)
* [ ] [#15330 ci: Add missing dependency for the checks-restart-redpanda job](https://github.com/MaterializeInc/materialize/pull/15330) (@philip-stoev)
* [ ] [#15311 adapter,sql: add ALTER SINK statement](https://github.com/MaterializeInc/materialize/pull/15311) (@andrioni)
* [ ] [#15337 environmentd: use correct query param name](https://github.com/MaterializeInc/materialize/pull/15337) (@mjibson)
* [ ] [#15253 docs: re add operations + migrate speed ups](https://github.com/MaterializeInc/materialize/pull/15253) (@joacoc)
* [ ] [#15234 persist: add DropSafeLeaseStream to prevent panic when dropping persist source](https://github.com/MaterializeInc/materialize/pull/15234) (@sploiselle)
* [ ] [#15255 coord: Optimize single statement read transaction](https://github.com/MaterializeInc/materialize/pull/15255) (@jkosh44)
* [ ] [#15343 adapter: last-minute audit log updates](https://github.com/MaterializeInc/materialize/pull/15343) (@benesch)
* [ ] [`84c10cb15` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/84c10cb15881dcb8382504358702a2b18f5c85a9) (@materializer)
* [ ] [`b8bb32ab1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b8bb32ab1f8e00b4c932b071c59e14e08e2bd681) (@materializer)
* [ ] [`347a2508e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/347a2508e5148d776982e724d53a4fb3738dd12a) (@materializer)
* [ ] [`c88e21836` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c88e218362399cf64c6eba66a782d377e978ebf9) (@materializer)
* [ ] [`b268e7bf3` adapter: don't allow subscribing to arranged log sources](https://github.com/MaterializeInc/materialize/commit/b268e7bf3b1c7ea31eccd9d2ec9c78bd117e3a09) (@benesch)
* [ ] [`636b78a66` adapter: distinguish between arranged/persisted logs](https://github.com/MaterializeInc/materialize/commit/636b78a663b566d8d618c33bae800a310089519b) (@benesch)
* [ ] [`e6aa08c50` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e6aa08c5022d230ab83f5d43d57cc81efc6481ec) (@materializer)
* [ ] [`10468ba3f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/10468ba3f9ea52f899b01fa39b7420f030792f87) (@materializer)
* [ ] [`441fd9703` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/441fd97038fe61dda7014820d9f0801e1891d8e4) (@materializer)
* [ ] [`33daee53a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/33daee53a7a9100057279be492d129e2b31ae3d5) (@materializer)
* [ ] [`218138173` release: bump to version v0.27.0](https://github.com/MaterializeInc/materialize/commit/218138173e6ac42252b7fe5884d43132f4b61214) (@benesch)

**Comment by benesch** [comment]
All the unreviewed PRs/commits that are not mine LGTM.

**Comment by mjibson** [comment]
Changes from @benesch LGTM.
