### ISSUE TITLE
compute: disable persisted introspection shards by default for the next release

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15415]
The persisted introspection shards exacerbate the compaction issues identified in #15093. On Slack, consensus was building for temporarily disabling the persisted introspection shards for new replicas, with an eye towards re-enabling them once `persist` compaction can keep up.

Slack conversation: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1665668526628809

## Work items
* [ ] Affirm that we have consensus on this decision. 
* [ ] Decide where we want this option to live. Is it an `environmentd` option that we force to `false` for now? Is it a permanent replica option that you can specify when you create the replica, that defaults to `false` now but we switch to `true` later (e.g., `INTROSPECTION PERSISTED`). Do we just comment the code out? https://github.com/MaterializeInc/materialize/pull/15392
* [ ] Write up the PR.

**Comment by antiguru** [comment]
@teskje and me discussed this issue and we propose the following plan:
* Create a PR that will disable writing to introspection shards within compute while leaving everything else untouched. We would still create the persist shards but never write to them. This is not great, because it's possible to select from the sources, but they'll never contain data. It would serve as a easy-to-implement solution should all other attempts fail. @antiguru will work on a PR.
* Create a different PR that changes the creation of replicas to not include persistent introspection data. All current replicas will be unchanged since the introspection shards are stored in the catalog. @teskje will work on a draft.
  * Once re-enabled, we can write a migration to add the introspection sources on upgrade.
  * We could add a migration to remove the introspection sources on upgrade for the next release.

We discussed adding an option to SQL to explicitly enable persistent introspection, but decided against it. This would require a more extensive design and at the moment, it seems we don't have a clear picture of what we'll commit to in the long run. For this reason, we de-prioritize this approach.
