### ISSUE TITLE
release: v0.28.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15500]
The following PRs in [`v0.28.0`](https://github.com/MaterializeInc/materialize/tree/v0.28.0) require review:
* [x] [#15348 release: bump to version v0.28.0-dev](https://github.com/MaterializeInc/materialize/pull/15348) (@benesch)
* [x] [#15349 zippy: Increase the timeout on MzStart](https://github.com/MaterializeInc/materialize/pull/15349) (@philip-stoev)
* [x] [#15362 doc/user: update dbt integration guide](https://github.com/MaterializeInc/materialize/pull/15362) (@morsapaes)
* [x] [#15403 persist: re-enable skip_consensus_fetch_optimization test](https://github.com/MaterializeInc/materialize/pull/15403) (@danhhz)
* [x] [#15404 testdrive: drop clusters created during testing](https://github.com/MaterializeInc/materialize/pull/15404) (@philip-stoev)
* [x] [#15417 ci: Remove the legacy upgrade job from Nightly](https://github.com/MaterializeInc/materialize/pull/15417) (@philip-stoev)
* [x] [#15418 Fix broken links in 101-query-compilation.md](https://github.com/MaterializeInc/materialize/pull/15418) (@ggevay)
* [x] [#15434 environmentd: bump timeout for test_no_block to 60s](https://github.com/MaterializeInc/materialize/pull/15434) (@benesch)
* [x] [#15454 Weekly dependency bump PR](https://github.com/MaterializeInc/materialize/pull/15454) (@benesch)
* [x] [#15461 platform checks: Revert to CREATE CONNECTION ... FOR syntax](https://github.com/MaterializeInc/materialize/pull/15461) (@philip-stoev)
* [x] [#15459 zippy: Increase the stressfullness of the ClusterReplicas scenario](https://github.com/MaterializeInc/materialize/pull/15459) (@philip-stoev)
* [x] [#15482 storage: bandaid over as_of panic](https://github.com/MaterializeInc/materialize/pull/15482) (@guswynn)
* [x] [#15497 coord: Set default cluster for mz_system user](https://github.com/MaterializeInc/materialize/pull/15497) (@jkosh44)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`de5b2f35f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/de5b2f35fb1132c9b411511ee4d0ba8b444a4a32) (@materializer)
* [x] [`c816ccdc9` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c816ccdc96f69c0beb9c95053c1060c9f4a3c1f9) (@materializer)
* [x] [`787bcfb2a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/787bcfb2a37ac62ccafd332bd0396fd82eeb5639) (@materializer)
* [x] [`17ded04b0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/17ded04b0e7be7cd352ac821627d67729d950ff4) (@materializer)
* [x] [`a8be298ed` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a8be298ed2b79858ef9e0cde32102c90494b08bb) (@materializer)
* [x] [`d29ce949b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d29ce949bdfafbdd7ca96cbda359f388a5ab5b68) (@materializer)
* [x] [`76cb6647d` release: bump to version v0.28.0](https://github.com/MaterializeInc/materialize/commit/76cb6647dc9fba4f43b51eada7ae543b08f718c4) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15297 build(deps): bump once_cell from 1.14.0 to 1.15.0](https://github.com/MaterializeInc/materialize/pull/15297) (@dependabot[bot])
* [ ] [#15348 release: bump to version v0.28.0-dev](https://github.com/MaterializeInc/materialize/pull/15348) (@benesch)
* [ ] [#15349 zippy: Increase the timeout on MzStart](https://github.com/MaterializeInc/materialize/pull/15349) (@philip-stoev)
* [ ] [#15351 storage: in CollectionManager, ignore sender hanging up](https://github.com/MaterializeInc/materialize/pull/15351) (@aljoscha)
* [ ] [#15339 adapter: Add system cluster tests](https://github.com/MaterializeInc/materialize/pull/15339) (@jkosh44)
* [ ] [#15319 Remove some sketchy source error variants](https://github.com/MaterializeInc/materialize/pull/15319) (@bkirwi)
* [ ] [#15356 persist: re-enable fast path for apply_merge_res in apply_diffs](https://github.com/MaterializeInc/materialize/pull/15356) (@danhhz)
* [ ] [#15355 sql: Fix SHOW INDEXES in non-active schemas](https://github.com/MaterializeInc/materialize/pull/15355) (@jkosh44)
* [ ] [#15341 [storage] Heartbeat writer in storage persist sink](https://github.com/MaterializeInc/materialize/pull/15341) (@cjubb39)
* [ ] [#15328 storage: in sources, track max-seen-offset and offset frontier separately](https://github.com/MaterializeInc/materialize/pull/15328) (@aljoscha)
* [ ] [#15358 docs: list mz_now as breaking change](https://github.com/MaterializeInc/materialize/pull/15358) (@mjibson)
* [ ] [#14314 [design] add Bounded Input Reliance design doc](https://github.com/MaterializeInc/materialize/pull/14314) (@guswynn)
* [ ] [#15362 doc/user: update dbt integration guide](https://github.com/MaterializeInc/materialize/pull/15362) (@morsapaes)
* [ ] [#15364 sql: Simplify SHOW command queries](https://github.com/MaterializeInc/materialize/pull/15364) (@jkosh44)
* [ ] [#15222 Remove storage managed table](https://github.com/MaterializeInc/materialize/pull/15222) (@sploiselle)
* [ ] [#15376 persist: semaphore to increase/limit compaction concurrency](https://github.com/MaterializeInc/materialize/pull/15376) (@pH14)
* [ ] [#15352 web,upgrade: Handle unreleased Mz versions](https://github.com/MaterializeInc/materialize/pull/15352) (@philip-stoev)
* [ ] [#15383 ci,testdrive: Add a Nightly CI job with SIZE 4](https://github.com/MaterializeInc/materialize/pull/15383) (@philip-stoev)
* [ ] [#15353 adapter: set compute read policies for persisted logs](https://github.com/MaterializeInc/materialize/pull/15353) (@teskje)
* [ ] [#15370 doc/user: update documentation to account for multi-output sources](https://github.com/MaterializeInc/materialize/pull/15370) (@morsapaes)
* [ ] [#15360 fix(mz) swallow ctrl-c when executing psql](https://github.com/MaterializeInc/materialize/pull/15360) (@sjwiesman)
* [ ] [#15399 persist: call maybe_heartbeat_reader in next_listen_batch loop](https://github.com/MaterializeInc/materialize/pull/15399) (@danhhz)
* [ ] [#15400 doc/user: fix lingering source/sink `SIZE` issues](https://github.com/MaterializeInc/materialize/pull/15400) (@benesch)
* [ ] [#15403 persist: re-enable skip_consensus_fetch_optimization test](https://github.com/MaterializeInc/materialize/pull/15403) (@danhhz)
* [ ] [#15393 sql: Prevent SHOW CREATE statement for system obj](https://github.com/MaterializeInc/materialize/pull/15393) (@jkosh44)
* [ ] [#15404 testdrive: drop clusters created during testing](https://github.com/MaterializeInc/materialize/pull/15404) (@philip-stoev)
* [ ] [#15369 doc: Fix create index syntax](https://github.com/MaterializeInc/materialize/pull/15369) (@jkosh44)
* [ ] [#15390 doc/user: dbt integration guide: remove cluster parameter from source materialization](https://github.com/MaterializeInc/materialize/pull/15390) (@ahelium)
* [ ] [#15394 allow telling environmentd about egress ips](https://github.com/MaterializeInc/materialize/pull/15394) (@doy-materialize)
* [ ] [#15332 Simplify draining logic](https://github.com/MaterializeInc/materialize/pull/15332) (@frankmcsherry)
* [ ] [#15408 environmentd: improve non-COPY http support](https://github.com/MaterializeInc/materialize/pull/15408) (@mjibson)
* [ ] [#15391 sql: Prevent altering system objects](https://github.com/MaterializeInc/materialize/pull/15391) (@jkosh44)
* [ ] [#15413 doc/user: add more missing sizes to CREATE SINK examples](https://github.com/MaterializeInc/materialize/pull/15413) (@benesch)
* [ ] [#15381 upgrade: Have all frameworks test upgrade from v0.27.0](https://github.com/MaterializeInc/materialize/pull/15381) (@philip-stoev)
* [ ] [#15385 cloudtest: Run S3/Kinesis tests against AWS not Minio](https://github.com/MaterializeInc/materialize/pull/15385) (@philip-stoev)
* [ ] [#15414 doc/user: add basic reference docs about replica introspection](https://github.com/MaterializeInc/materialize/pull/15414) (@benesch)
* [ ] [#15416 cloudtest: Do not pass announce-egress-ip on the command line](https://github.com/MaterializeInc/materialize/pull/15416) (@philip-stoev)
* [ ] [#15417 ci: Remove the legacy upgrade job from Nightly](https://github.com/MaterializeInc/materialize/pull/15417) (@philip-stoev)
* [ ] [#15344 sql: Fix SHOW INDEXES for empty columns](https://github.com/MaterializeInc/materialize/pull/15344) (@jkosh44)
* [ ] [#15421 doc/user: add missing `SIZE` to `CREATE SOURCE` and `CREATE SINK` examples](https://github.com/MaterializeInc/materialize/pull/15421) (@morsapaes)
* [ ] [#15410 adapter: Create default indexes for SHOW commands](https://github.com/MaterializeInc/materialize/pull/15410) (@jkosh44)
* [ ] [#15420 sql-parser: improve clarity of CREATE CONNECTION syntax](https://github.com/MaterializeInc/materialize/pull/15420) (@benesch)
* [ ] [#15431 adapter: use correct type for pg_type.typcategory](https://github.com/MaterializeInc/materialize/pull/15431) (@mjibson)
* [ ] [#15386 adapter: remove the old `EXPLAIN` code path](https://github.com/MaterializeInc/materialize/pull/15386) (@aalexandrov)
* [ ] [#15418 Fix broken links in 101-query-compilation.md](https://github.com/MaterializeInc/materialize/pull/15418) (@ggevay)
* [ ] [#15338 Document the new `EXPLAIN` syntax](https://github.com/MaterializeInc/materialize/pull/15338) (@aalexandrov)
* [ ] [#15434 environmentd: bump timeout for test_no_block to 60s](https://github.com/MaterializeInc/materialize/pull/15434) (@benesch)
* [ ] [#15422 Disable persisted introspection sources](https://github.com/MaterializeInc/materialize/pull/15422) (@teskje)
* [ ] [#15262 adapter: notify on replica changes during peeks](https://github.com/MaterializeInc/materialize/pull/15262) (@mjibson)
* [ ] [#15440 dbt-materialize: disallow cluster config in view materializations](https://github.com/MaterializeInc/materialize/pull/15440) (@morsapaes)
* [ ] [#15437 sql: don't ever interpret idents as objects for string options](https://github.com/MaterializeInc/materialize/pull/15437) (@benesch)
* [ ] [#15442 build(deps): bump tokio-stream from 0.1.10 to 0.1.11](https://github.com/MaterializeInc/materialize/pull/15442) (@dependabot[bot])
* [ ] [#15454 Weekly dependency bump PR](https://github.com/MaterializeInc/materialize/pull/15454) (@benesch)
* [ ] [#15436 sql: use kebab case for materialized view type](https://github.com/MaterializeInc/materialize/pull/15436) (@benesch)
* [ ] [#15460 storage: in reclock.rs, make time control more explicit in tests](https://github.com/MaterializeInc/materialize/pull/15460) (@aljoscha)
* [ ] [#15461 platform checks: Revert to CREATE CONNECTION ... FOR syntax](https://github.com/MaterializeInc/materialize/pull/15461) (@philip-stoev)
* [ ] [#15459 zippy: Increase the stressfullness of the ClusterReplicas scenario](https://github.com/MaterializeInc/materialize/pull/15459) (@philip-stoev)
* [ ] [#15428 docs: Add docs about SHOW command indexes](https://github.com/MaterializeInc/materialize/pull/15428) (@jkosh44)
* [ ] [#15463 doc: Confluent Cloud guide SASL details](https://github.com/MaterializeInc/materialize/pull/15463) (@bobbyiliev)
* [ ] [#15424 persist: hook up existing per shard metric for compaction](https://github.com/MaterializeInc/materialize/pull/15424) (@pH14)
* [ ] [#15308 testing: Check AllowCompaction delivery](https://github.com/MaterializeInc/materialize/pull/15308) (@lluki)
* [ ] [#15405 persist: automatically heartbeat handles in background tasks (for now)](https://github.com/MaterializeInc/materialize/pull/15405) (@danhhz)
* [ ] [#15466 coord: Normalize storage update timestamps](https://github.com/MaterializeInc/materialize/pull/15466) (@jkosh44)
* [ ] [#15375 persist: allow `apply_merge_res` to replace subset of fueled merge parts](https://github.com/MaterializeInc/materialize/pull/15375) (@pH14)
* [ ] [#15471 doc/user: revert unreleased syntax changes](https://github.com/MaterializeInc/materialize/pull/15471) (@morsapaes)
* [ ] [#15477 storage: in reclock_operator, fix premature capability downgrading](https://github.com/MaterializeInc/materialize/pull/15477) (@aljoscha)
* [ ] [#15473 Add is_empty to MergeBatch and SpineBatch](https://github.com/MaterializeInc/materialize/pull/15473) (@antiguru)
* [ ] [#15401 For SHOW commands, only support IN CLUSTER for materialized views and indexes](https://github.com/MaterializeInc/materialize/pull/15401) (@chaas)
* [ ] [#15005 integrate Sentry into telemetry stack](https://github.com/MaterializeInc/materialize/pull/15005) (@pH14)
* [ ] [#15469 fix task_ready ordering in timely async builder](https://github.com/MaterializeInc/materialize/pull/15469) (@guswynn)
* [ ] [#15483 doc/user: Fixed syntax error in code example](https://github.com/MaterializeInc/materialize/pull/15483) (@parkerhendo)
* [ ] [#15482 storage: bandaid over as_of panic](https://github.com/MaterializeInc/materialize/pull/15482) (@guswynn)
* [ ] [#15468 Heartbeat table writers in storage controller](https://github.com/MaterializeInc/materialize/pull/15468) (@frankmcsherry)
* [ ] [#15260 persist: set a timeout on compaction requests](https://github.com/MaterializeInc/materialize/pull/15260) (@pH14)
* [ ] [#15497 coord: Set default cluster for mz_system user](https://github.com/MaterializeInc/materialize/pull/15497) (@jkosh44)
* [ ] [`de5b2f35f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/de5b2f35fb1132c9b411511ee4d0ba8b444a4a32) (@materializer)
* [ ] [`c816ccdc9` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c816ccdc96f69c0beb9c95053c1060c9f4a3c1f9) (@materializer)
* [ ] [`787bcfb2a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/787bcfb2a37ac62ccafd332bd0396fd82eeb5639) (@materializer)
* [ ] [`17ded04b0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/17ded04b0e7be7cd352ac821627d67729d950ff4) (@materializer)
* [ ] [`a8be298ed` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a8be298ed2b79858ef9e0cde32102c90494b08bb) (@materializer)
* [ ] [`d29ce949b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d29ce949bdfafbdd7ca96cbda359f388a5ab5b68) (@materializer)
* [ ] [`76cb6647d` release: bump to version v0.28.0](https://github.com/MaterializeInc/materialize/commit/76cb6647dc9fba4f43b51eada7ae543b08f718c4) (@jkosh44)

**Comment by benesch** [comment]
The commits and PRs that are not mine LGTM. @jkosh44 you'll need to sign off on mine.

**Comment by jkosh44** [comment]
@benesch's commits and PRs LGTM.
