### ISSUE TITLE
release: v0.28.1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15537]
No PRs in [`v0.28.1`](https://github.com/MaterializeInc/materialize/tree/v0.28.1) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`0368ad73c` Merge pull request #15513 from mjibson/stash-count](https://github.com/MaterializeInc/materialize/commit/0368ad73ce15300a4d6478a7f30e590e8340b473) (@jkosh44)
* [ ] [`031b66964` add size column to show cluster replicas command (already in the docs) (#15506)](https://github.com/MaterializeInc/materialize/commit/031b66964731bc6c202a3ebd5533fc52846128cc) (@jkosh44)
* [ ] [`9308a968c` Merge pull request #15507 from danhhz/persist_diff_apply_panic](https://github.com/MaterializeInc/materialize/commit/9308a968c7987bceb2c4a2417adce62cc35244d4) (@jkosh44)
* [ ] [`e3ae00717` Merge pull request #15504 from teskje/replicated-peek-read-holds](https://github.com/MaterializeInc/materialize/commit/e3ae007176bf0be37db0eabce06bb4234cd0bc17) (@jkosh44)
* [ ] [`8c2f949b4` coord: Remove panic from canceling closed conns (#15505)](https://github.com/MaterializeInc/materialize/commit/8c2f949b499d4e38a11f47c9b81493d22807a8c2) (@jkosh44)
* [ ] [`5504664b1` persist: no-op rather than panic when `maybe_replace` would increase the number of updates (#15519)](https://github.com/MaterializeInc/materialize/commit/5504664b1c377200128d3886aa3bb590dbf2bc21) (@jkosh44)
* [ ] [`48937ef3c` release: bump to version v0.28.1](https://github.com/MaterializeInc/materialize/commit/48937ef3c8a9ffa74d855bbbdd7f1bba8a7fb07b) (@jkosh44)

**Comment by jkosh44** [comment]
All commits were part of previously reviewed and approved PRs.

**Comment by benesch** [comment]
(And I've verified the above.)
