### ISSUE TITLE
[Epic] Add tooling for testing and debugging breaking changes

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#15648]
## Goal
* Catch breaking changes in our testing pipeline
* Add functionality to restore customer environments 

## Tasks
- [x] https://github.com/MaterializeInc/materialize/issues/15439
- [x] https://github.com/MaterializeInc/materialize/issues/14708
- [x] https://github.com/MaterializeInc/materialize/issues/14681
- [x] https://github.com/MaterializeInc/materialize/pull/15456

## TODO
- [ ] Discuss integrating above features into CI and release cycle.

**Comment by ggnall** [comment]
Re-scoped and marking this as complete as core tooling work is done. Adding a follow up epic to be considered by the Cloud team: https://github.com/MaterializeInc/cloud/issues/5057

cc: @chaas @jonathan-k-shapiro @hlburak
