### ISSUE TITLE
release: v0.29.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15681]
The following PRs in [`v0.29.0`](https://github.com/MaterializeInc/materialize/tree/v0.29.0) require review:
* [x] [#15488 doc/user: fix link to lts version](https://github.com/MaterializeInc/materialize/pull/15488) (@joacoc)
* [x] [#15555 mzcompose,cloudtest: Get Debezium to retry network errors](https://github.com/MaterializeInc/materialize/pull/15555) (@philip-stoev)
* [x] [#15571 persist: `inspect state-rollups` to pull down all known rollups](https://github.com/MaterializeInc/materialize/pull/15571) (@pH14)
* [x] [#15578 testdrive,mzcompose: Remove all traces of --validate-data-dir](https://github.com/MaterializeInc/materialize/pull/15578) (@philip-stoev)
* [x] [#15580 testdrive: Fix various tests to be SIZE-independent](https://github.com/MaterializeInc/materialize/pull/15580) (@philip-stoev)
* [x] [#15626 platform checks: Allow parallel execution of Checks](https://github.com/MaterializeInc/materialize/pull/15626) (@philip-stoev)
* [x] [#15627 platform checks: remove erroneous assert in test framework](https://github.com/MaterializeInc/materialize/pull/15627) (@philip-stoev)
* [x] [#15659 doc/user: improve intra-page links in Key Concepts](https://github.com/MaterializeInc/materialize/pull/15659) (@morsapaes)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`520579c5c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/520579c5c072aec7e2943440a45c06c90bcc5ef8) (@materializer)
* [x] [`87f6ba701` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/87f6ba70128e63ffeffa14b28529606f91b6e6b1) (@materializer)
* [x] [`d0a7d3a27` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0a7d3a273e6a1a6ef4b9f0bfde1e6585534f97e) (@materializer)
* [x] [`2ad4a4c71` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/2ad4a4c71bbee5aef50621550573e7fbcec46f8b) (@materializer)
* [x] [`3a4e68220` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3a4e68220c4fbd9d5e77536b9404009ff667ead3) (@materializer)
* [x] [`755576a67` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/755576a67a1bae35071efe6ae890f79becd9a4ed) (@materializer)
* [x] [`c2f6a887e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c2f6a887e8eaea9be1726466dc49aa811097ef62) (@materializer)
* [ ] [`7a421f7b8` release: bump to version v0.29.0](https://github.com/MaterializeInc/materialize/commit/7a421f7b87c015c3ea3455f1f26f022c70789a50) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15489 doc/user: fix support email](https://github.com/MaterializeInc/materialize/pull/15489) (@joacoc)
* [ ] [#15487 Doc/user: small improvements to the http api](https://github.com/MaterializeInc/materialize/pull/15487) (@joacoc)
* [ ] [#15488 doc/user: fix link to lts version](https://github.com/MaterializeInc/materialize/pull/15488) (@joacoc)
* [ ] [#15501 release: bump to version v0.29.0-dev](https://github.com/MaterializeInc/materialize/pull/15501) (@jkosh44)
* [ ] [#15503 doc/user: restore `CREATE CONNECTION` syntax](https://github.com/MaterializeInc/materialize/pull/15503) (@morsapaes)
* [ ] [#15494 sql-parser: support option value sequences with parentheses](https://github.com/MaterializeInc/materialize/pull/15494) (@benesch)
* [ ] [#15507 persist: add debugging info to "state diff should apply cleanly" panic](https://github.com/MaterializeInc/materialize/pull/15507) (@danhhz)
* [ ] [#15505 coord: Remove panic from canceling closed conns](https://github.com/MaterializeInc/materialize/pull/15505) (@jkosh44)
* [ ] [#15429 sql: Allow indexes on system objects](https://github.com/MaterializeInc/materialize/pull/15429) (@jkosh44)
* [ ] [#15398 [sources] Revive source status history collection](https://github.com/MaterializeInc/materialize/pull/15398) (@bkirwi)
* [ ] [#15513 stash: log statement execution count](https://github.com/MaterializeInc/materialize/pull/15513) (@mjibson)
* [ ] [#15425 storage: add bare-bones UNITTEST source](https://github.com/MaterializeInc/materialize/pull/15425) (@guswynn)
* [ ] [#15516 coord: Don't count subsources for resource limits](https://github.com/MaterializeInc/materialize/pull/15516) (@jkosh44)
* [ ] [#15506 Add size column to SHOW CLUSTER REPLICAS command (already in the docs)](https://github.com/MaterializeInc/materialize/pull/15506) (@chaas)
* [ ] [#15523 stash: improve memory performance](https://github.com/MaterializeInc/materialize/pull/15523) (@mjibson)
* [ ] [#15504 compute-client: maintain peek read holds long enough](https://github.com/MaterializeInc/materialize/pull/15504) (@teskje)
* [ ] [#15526 storage: in reclock::compact, turn assert into no-op](https://github.com/MaterializeInc/materialize/pull/15526) (@aljoscha)
* [ ] [#15509 Fix CREATE CONNECTION so that it errors on item already exists, unless command contains 'if not exists'](https://github.com/MaterializeInc/materialize/pull/15509) (@chaas)
* [ ] [#15529 storage: communicate resumption operator termination through token](https://github.com/MaterializeInc/materialize/pull/15529) (@petrosagg)
* [ ] [#15486 doc/user: [Kafka sources] add confluent schema registry basic auth](https://github.com/MaterializeInc/materialize/pull/15486) (@joacoc)
* [ ] [#15522 stash: only count if logging enabled](https://github.com/MaterializeInc/materialize/pull/15522) (@mjibson)
* [ ] [#15519 persist: no-op rather than panic when `maybe_replace` would increase updates](https://github.com/MaterializeInc/materialize/pull/15519) (@pH14)
* [ ] [#14994 storage: add TPCH load generator](https://github.com/MaterializeInc/materialize/pull/14994) (@mjibson)
* [ ] [#15229 doc/user: Make Key Concepts more prominent in Search](https://github.com/MaterializeInc/materialize/pull/15229) (@ruf-io)
* [ ] [#15530 adapter: Add mz_introspection system user](https://github.com/MaterializeInc/materialize/pull/15530) (@jkosh44)
* [ ] [#15512 storage: resolve various followups from #15477](https://github.com/MaterializeInc/materialize/pull/15512) (@guswynn)
* [ ] [#15544 storage: fix log line in common case reclock compact calls](https://github.com/MaterializeInc/materialize/pull/15544) (@guswynn)
* [ ] [#15548 stash: improve perf of upsert_key](https://github.com/MaterializeInc/materialize/pull/15548) (@mjibson)
* [ ] [#15532 + Add subsource as source type](https://github.com/MaterializeInc/materialize/pull/15532) (@heeringa)
* [ ] [#15533 doc/user: polish v0.28.0 release notes](https://github.com/MaterializeInc/materialize/pull/15533) (@morsapaes)
* [ ] [#15554 mzcompose: Pass --volumes to docker-compose down](https://github.com/MaterializeInc/materialize/pull/15554) (@philip-stoev)
* [ ] [#15555 mzcompose,cloudtest: Get Debezium to retry network errors](https://github.com/MaterializeInc/materialize/pull/15555) (@philip-stoev)
* [ ] [#14974 timely-util: efficient type to represent partitioned timestamps](https://github.com/MaterializeInc/materialize/pull/14974) (@petrosagg)
* [ ] [#15542 doc/user: Consolidate pagerank to 10-90 system](https://github.com/MaterializeInc/materialize/pull/15542) (@ruf-io)
* [ ] [#15484 doc/user: track a subscription sources](https://github.com/MaterializeInc/materialize/pull/15484) (@joacoc)
* [ ] [#15524 sql-parser,sql: use standard macro for cluster replica parsing](https://github.com/MaterializeInc/materialize/pull/15524) (@benesch)
* [ ] [#15563 sql: Fix connection renaming](https://github.com/MaterializeInc/materialize/pull/15563) (@jkosh44)
* [ ] [#15562 adapter: Set default cluster for internal users](https://github.com/MaterializeInc/materialize/pull/15562) (@jkosh44)
* [ ] [#15546 persist: fallback to rebuild spine before applying diffs](https://github.com/MaterializeInc/materialize/pull/15546) (@pH14)
* [ ] [#15565 storage: use async `OperatorBuilder` for resumption operator](https://github.com/MaterializeInc/materialize/pull/15565) (@petrosagg)
* [ ] [#15200 [sources] Restructuring / renaming for source error handling](https://github.com/MaterializeInc/materialize/pull/15200) (@bkirwi)
* [ ] [#15560 sql: Prevent users from altering system clusters](https://github.com/MaterializeInc/materialize/pull/15560) (@jkosh44)
* [ ] [#15551 adapter: fix wonky error message on `CREATE SUBSOURCE`](https://github.com/MaterializeInc/materialize/pull/15551) (@benesch)
* [ ] [#15571 persist: `inspect state-rollups` to pull down all known rollups](https://github.com/MaterializeInc/materialize/pull/15571) (@pH14)
* [ ] [#15575 persist: prefetch compaction inputs](https://github.com/MaterializeInc/materialize/pull/15575) (@danhhz)
* [ ] [#15456 stash debug: new tool for viewing and editing stashes](https://github.com/MaterializeInc/materialize/pull/15456) (@mjibson)
* [ ] [#15578 testdrive,mzcompose: Remove all traces of --validate-data-dir](https://github.com/MaterializeInc/materialize/pull/15578) (@philip-stoev)
* [ ] [#15581 Include map prefix in the `column_types` passed to `column_knowledge::optimize`](https://github.com/MaterializeInc/materialize/pull/15581) (@aalexandrov)
* [ ] [#15580 testdrive: Fix various tests to be SIZE-independent](https://github.com/MaterializeInc/materialize/pull/15580) (@philip-stoev)
* [ ] [#15476 Use index when `a=<literal>` gets an implicit cast](https://github.com/MaterializeInc/materialize/pull/15476) (@ggevay)
* [ ] [#15292 build(deps): bump tracing from 0.1.36 to 0.1.37](https://github.com/MaterializeInc/materialize/pull/15292) (@dependabot[bot])
* [ ] [#15423 Fix recursive calls in `extract_non_errors_from_expr`](https://github.com/MaterializeInc/materialize/pull/15423) (@ggevay)
* [ ] [#15592 sql: Include system indexes in SHOW INDEXES](https://github.com/MaterializeInc/materialize/pull/15592) (@jkosh44)
* [ ] [#15601 coord: Log timestamp selected for every query](https://github.com/MaterializeInc/materialize/pull/15601) (@jkosh44)
* [ ] [#15608 Update docs for pre push hook](https://github.com/MaterializeInc/materialize/pull/15608) (@jacobsimpson)
* [ ] [#15589 adapter: Set default cluster size correctly](https://github.com/MaterializeInc/materialize/pull/15589) (@jkosh44)
* [ ] [#15577 testdrive: use readonly stash during catalog verify](https://github.com/MaterializeInc/materialize/pull/15577) (@mjibson)
* [ ] [#15610 compute-client: merge ActiveReplication into the compute controller](https://github.com/MaterializeInc/materialize/pull/15610) (@teskje)
* [ ] [#15587 Doc: clarify source name in Confluent guide](https://github.com/MaterializeInc/materialize/pull/15587) (@bobbyiliev)
* [ ] [#15607 doc/user: ssh bastion server guide](https://github.com/MaterializeInc/materialize/pull/15607) (@joacoc)
* [ ] [#15527 Add `allowed_cluster_replica_sizes` system variable](https://github.com/MaterializeInc/materialize/pull/15527) (@aalexandrov)
* [ ] [#15626 platform checks: Allow parallel execution of Checks](https://github.com/MaterializeInc/materialize/pull/15626) (@philip-stoev)
* [ ] [#15627 platform checks: remove erroneous assert in test framework](https://github.com/MaterializeInc/materialize/pull/15627) (@philip-stoev)
* [ ] [#15609 [sinks] Allow non-default partition count for already-existing topic](https://github.com/MaterializeInc/materialize/pull/15609) (@cjubb39)
* [ ] [#15510 [sources] Centralize health-checking for a source](https://github.com/MaterializeInc/materialize/pull/15510) (@bkirwi)
* [ ] [#15636 [sources] Fix merge skew: pick up the source_errors rename](https://github.com/MaterializeInc/materialize/pull/15636) (@bkirwi)
* [ ] [#15574 storage: fix source reader remap trace compaction, and improve logging](https://github.com/MaterializeInc/materialize/pull/15574) (@guswynn)
* [ ] [#15640 [sinks] Add sink status history collection](https://github.com/MaterializeInc/materialize/pull/15640) (@cjubb39)
* [ ] [#15490 doc/user: add clusters and connections to the menu](https://github.com/MaterializeInc/materialize/pull/15490) (@joacoc)
* [ ] [#15430 storage: add way to run the source ingestion pipeline as a unit test](https://github.com/MaterializeInc/materialize/pull/15430) (@guswynn)
* [ ] [#15645 persist: stop recomputing since in expire_reader (for now)](https://github.com/MaterializeInc/materialize/pull/15645) (@danhhz)
* [ ] [#15591 sql: add right_inverse to LazyUnaryFunc](https://github.com/MaterializeInc/materialize/pull/15591) (@sploiselle)
* [ ] [#15363 persist: special case compaction for a single nonempty batch in inputs](https://github.com/MaterializeInc/materialize/pull/15363) (@pH14)
* [ ] [#15646 [testing] Switch to a version of the DBZ image with ARM support](https://github.com/MaterializeInc/materialize/pull/15646) (@bkirwi)
* [ ] [#15656 storage: restore aggressive remap shard compaction behavior](https://github.com/MaterializeInc/materialize/pull/15656) (@guswynn)
* [ ] [#15661 stash: log postgres errors to sentry](https://github.com/MaterializeInc/materialize/pull/15661) (@mjibson)
* [ ] [#15118 storage: add DATUMS load generator](https://github.com/MaterializeInc/materialize/pull/15118) (@mjibson)
* [ ] [#15659 doc/user: improve intra-page links in Key Concepts](https://github.com/MaterializeInc/materialize/pull/15659) (@morsapaes)
* [ ] [#15673 storage: ensure reclock state moves in fully formed batches](https://github.com/MaterializeInc/materialize/pull/15673) (@petrosagg)
* [ ] [#15666 storage: when rehydrating, retry connecting much more eagerly](https://github.com/MaterializeInc/materialize/pull/15666) (@aljoscha)
* [ ] [#15667 storage: move persist source to new timely/async integration](https://github.com/MaterializeInc/materialize/pull/15667) (@petrosagg)
* [ ] [#15668 storage: in relock.rs, improve information content of as_of assert](https://github.com/MaterializeInc/materialize/pull/15668) (@aljoscha)
* [ ] [#15634 doc: Confluent Cloud guide API Key steps](https://github.com/MaterializeInc/materialize/pull/15634) (@bobbyiliev)
* [ ] [#15647 Add TPC-H output correctness test](https://github.com/MaterializeInc/materialize/pull/15647) (@ggevay)
* [ ] [#15120 Join ordering based on input filters](https://github.com/MaterializeInc/materialize/pull/15120) (@ggevay)
* [ ] [#15491 doc/user: port ttl pattern guide](https://github.com/MaterializeInc/materialize/pull/15491) (@joacoc)
* [ ] [#15676 Doc: remove table persist warning](https://github.com/MaterializeInc/materialize/pull/15676) (@bobbyiliev)
* [ ] [#15671 compute: don't report empty frontiers during reconciliation](https://github.com/MaterializeInc/materialize/pull/15671) (@teskje)
* [ ] [#15677 persist: ensure handle heartbeats are monotonic](https://github.com/MaterializeInc/materialize/pull/15677) (@pH14)
* [ ] [`520579c5c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/520579c5c072aec7e2943440a45c06c90bcc5ef8) (@materializer)
* [ ] [`87f6ba701` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/87f6ba70128e63ffeffa14b28529606f91b6e6b1) (@materializer)
* [ ] [`d0a7d3a27` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0a7d3a273e6a1a6ef4b9f0bfde1e6585534f97e) (@materializer)
* [ ] [`2ad4a4c71` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/2ad4a4c71bbee5aef50621550573e7fbcec46f8b) (@materializer)
* [ ] [`3a4e68220` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3a4e68220c4fbd9d5e77536b9404009ff667ead3) (@materializer)
* [ ] [`755576a67` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/755576a67a1bae35071efe6ae890f79becd9a4ed) (@materializer)
* [ ] [`c2f6a887e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c2f6a887e8eaea9be1726466dc49aa811097ef62) (@materializer)
* [ ] [`7a421f7b8` release: bump to version v0.29.0](https://github.com/MaterializeInc/materialize/commit/7a421f7b87c015c3ea3455f1f26f022c70789a50) (@benesch)

**Comment by benesch** [comment]
All the unreviewed PRs/commits that are not mine LGTM.

**Comment by brennanvincent** [comment]
LGTM
