### ISSUE TITLE
release: v0.29.2 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15711]
No PRs in [`v0.29.2`](https://github.com/MaterializeInc/materialize/tree/v0.29.2) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`de23e3a21` Revert "persist: special case compaction for a single nonempty batch in inputs (#15363)"](https://github.com/MaterializeInc/materialize/commit/de23e3a216f9a70c6e025b89f1f497efce3fe97a) (@danhhz)
* [x] [`d0b37ae7a` adapter: add log lines to bootstrap (#15635)](https://github.com/MaterializeInc/materialize/commit/d0b37ae7aca6217dd244d91160033749c3f593ce) (@danhhz)
* [x] [`f11ba97f3` release: bump to version v0.29.2](https://github.com/MaterializeInc/materialize/commit/f11ba97f3872731aaab33d2d227646eaf439cc08) (@danhhz)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`de23e3a21` Revert "persist: special case compaction for a single nonempty batch in inputs (#15363)"](https://github.com/MaterializeInc/materialize/commit/de23e3a216f9a70c6e025b89f1f497efce3fe97a) (@danhhz)
* [ ] [`d0b37ae7a` adapter: add log lines to bootstrap (#15635)](https://github.com/MaterializeInc/materialize/commit/d0b37ae7aca6217dd244d91160033749c3f593ce) (@danhhz)
* [ ] [`f11ba97f3` release: bump to version v0.29.2](https://github.com/MaterializeInc/materialize/commit/f11ba97f3872731aaab33d2d227646eaf439cc08) (@danhhz)

**Comment by danhhz** [comment]
All unreviewed commits/PRs that are not mine LGTM.

**Comment by arusahni** [comment]
LGTM!
