### ISSUE TITLE
release: v0.29.3 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15752]
No PRs in [`v0.29.3`](https://github.com/MaterializeInc/materialize/tree/v0.29.3) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`5a3d72fea` persist: substantially improve compaction perf (#15732)](https://github.com/MaterializeInc/materialize/commit/5a3d72fea93c75f4fea18a05fcf6f92caa66a0a7) (@benesch)
* [x] [`95bacb00b` tracing: filter librdkafka events out from sentry](https://github.com/MaterializeInc/materialize/commit/95bacb00bf9a00bd9ddef99fe6d84828221f92ef) (@benesch)
* [x] [`d4bdfb09f` stash: Add batched APIs for update and remove (#15738)](https://github.com/MaterializeInc/materialize/commit/d4bdfb09ffa615ab5267aa7ae93e63d6e440b3c7) (@benesch)
* [x] [`10941821e` storage: turn off strict host checking in ssh tunnels](https://github.com/MaterializeInc/materialize/commit/10941821e80cae3cadd05316fb2e262a9d8fb8b2) (@benesch)
* [x] [`41d84bbec` release: bump to version v0.29.3](https://github.com/MaterializeInc/materialize/commit/41d84bbec01248ef9d82c3c3d7c8084d7ec2fcd7) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`5a3d72fea` persist: substantially improve compaction perf (#15732)](https://github.com/MaterializeInc/materialize/commit/5a3d72fea93c75f4fea18a05fcf6f92caa66a0a7) (@benesch)
* [ ] [`95bacb00b` tracing: filter librdkafka events out from sentry](https://github.com/MaterializeInc/materialize/commit/95bacb00bf9a00bd9ddef99fe6d84828221f92ef) (@benesch)
* [ ] [`d4bdfb09f` stash: Add batched APIs for update and remove (#15738)](https://github.com/MaterializeInc/materialize/commit/d4bdfb09ffa615ab5267aa7ae93e63d6e440b3c7) (@benesch)
* [ ] [`10941821e` storage: turn off strict host checking in ssh tunnels](https://github.com/MaterializeInc/materialize/commit/10941821e80cae3cadd05316fb2e262a9d8fb8b2) (@benesch)
* [ ] [`41d84bbec` release: bump to version v0.29.3](https://github.com/MaterializeInc/materialize/commit/41d84bbec01248ef9d82c3c3d7c8084d7ec2fcd7) (@benesch)

**Comment by guswynn** [comment]
LGTM
