### ISSUE TITLE
[Epic] Expose CPU and memory usage of clusters and storage hosts in system catalog

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15808]
### Product Outcome

We will expose the CPU and memory usage of clusters and storage hosts in the system catalog so users can monitor their usage.

### Specification

Subset of https://github.com/MaterializeInc/cloud/issues/4120

### Design

Subset of https://github.com/MaterializeInc/cloud/issues/4120

### Documentation

- [x] Covered in https://github.com/MaterializeInc/materialize/pull/16209 for compute
- [ ] Storage hosts outstanding

### Required Issues (Must Haves)
- [x] https://github.com/MaterializeInc/materialize/issues/16323 (for storage)
- [x] https://github.com/MaterializeInc/materialize/issues/16477
- [x] Improve size mapping table to show all available sizes (pending PR)
- [ ] Add `mz_source_utilization` and `mz_sink_utilization` convenience views (based on `mz_storage_host_metrics`)

### Blockers

None

**Comment by benesch** [comment]
How actively are you working on this? I've got some design thoughts that we should chat about!

**Comment by umanwizard** [comment]
This requires some work: we either need to figure out how to proxy Prometheus to avoid opening it completely unpermissioned to user-controlled environments, which would require us to validate in perpetuity that we didn't accidentally enable a way to make malicious HTTP requests (see discussion [here](https://materializeinc.slack.com/archives/CL68GT3AT/p1664917470416489)), or get these metrics in another way, like the Kubernetes metrics API (see discussion [here](https://materializeinc.slack.com/archives/CL68GT3AT/p1667750053254749?thread_ts=1667743619.078759&cid=CL68GT3AT)), or measuring the values from within the running processes themselves (which isn't very reliable).
