### ISSUE TITLE
[Epic] Ability to Measure and Debug Against Adapter SLOs

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#15811]
## Product Outcome
- Establish key scenarios in which we want to measure SLOs
- Ability to measure our current execution time against SLOs
- Ability to debug requests where response times that do not hit our SLOs
- Run against the basic case (Case 1: Get Started) and benchmark where we are

## Required Issues (Must Haves)
- [x] Define key scenarios to measure - Done (see Key Scenario Definition section below)
- [x] https://github.com/MaterializeInc/cloud/issues/4167 (Jaeger tracing)
- [x] https://github.com/MaterializeInc/materialize/issues/15495
- [x] https://github.com/MaterializeInc/materialize/issues/17215  (must have a most recent measure by end of milestone)

## Discovered Issues 
- https://github.com/MaterializeInc/materialize/issues/14244
- https://github.com/MaterializeInc/materialize/issues/14018
- https://github.com/MaterializeInc/materialize/issues/17191

## Related
- https://github.com/MaterializeInc/materialize/issues/13043
- https://github.com/MaterializeInc/materialize/issues/13772
- https://github.com/MaterializeInc/materialize/issues/15906
- https://github.com/MaterializeInc/materialize/issues/16531

## Key Scenario Definition
We will start with most simple case (getting started script) and expand to additional cases as we have confidence in the previous ones.
These steps will be repeated at a regular cadence (e.g. every 2 weeks) on staging.
1. Run the script 5 times, collect the max response time for each statement (may be helpful to also collect the min and average to understand variance)
2. For each case where measured response time > target response time, investigate core contributors and create a ticket with a) t-shirt size for fixing (or route to another team where applicable to make this estimate) b) estimated impact on response time.
3. For each case where measured response time > previously measured response time, investigate what changed. Create a ticket similar to above.
4. Beyond the scope of this epic, engineering & product will prioritize the fixes.

### Case 1: Getting Started
- [Get Started response time SLAs](https://docs.google.com/document/d/1yVnjIoEz91nzytQv066cwrjOncAYVM3pm3m4gdlMijQ/edit)
- Identify
  a) consistent slowness and
  b) spikiness (see https://github.com/MaterializeInc/materialize/issues/14060)

### Case 2: Create View, Drop View, in a loop
- This reflects a common use case by `dbt run`

### Case 3: Create maximum # of tables and sources allows
- Including live kafka and postgres sources
- With no or low amounts of data
- Todo: overhead of setting up these sources

### Case 4: Cases 2-3 with higher volumes of data.
- The above cases are meant to be simple. Once we achieve performance on these base cases, we'll focus on maintaining it with higher loads of data in the same scenarios.

**Comment by mjibson** [comment]
I enabled tracing in production and ran the script a few times. The traces in honeycomb had three problems:

1. The traces list shows the slowest 10, making it fairly hard to just look around.
2. Only environmentd was ever in the trace. I think a few were supposed to have some computed stuff for peeks, but I never saw it.
3. Traces mostly didn't have anything interested in them, and sometimes only had 1 span. This could have been because not all messages were traced (see https://github.com/MaterializeInc/materialize/pull/16261 for fix), but I suspect it's actually because HC is not getting all spans for a trace due to sampling or some other effect we don't know about.

Due to these problems, I'm waiting for the next release to include the above fix, and also waiting for cloud to have non-HC tracing implemented before digging down into perf problems again.

**Comment by mjibson** [comment]
All attached issues closed.
