### ISSUE TITLE
release: v0.30.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15834]
The following PRs in [`v0.30.0`](https://github.com/MaterializeInc/materialize/tree/v0.30.0) require review:
* [x] [#15669 zippy: Add a scenario using parallel Kafka inserts](https://github.com/MaterializeInc/materialize/pull/15669) (@philip-stoev)
* [x] [#15682 release: bump to version v0.30.0-dev](https://github.com/MaterializeInc/materialize/pull/15682) (@benesch)
* [x] [#15695 zippy: Reduce the number of rows in the UserTables scenario](https://github.com/MaterializeInc/materialize/pull/15695) (@philip-stoev)
* [x] [#15713 marginally improve compute startup logs](https://github.com/MaterializeInc/materialize/pull/15713) (@brennanvincent)
* [x] [#15739 doc/developer: add an error message example](https://github.com/MaterializeInc/materialize/pull/15739) (@ggnall)
* [x] [#15746 Add feature to save/load flamegraph traces](https://github.com/MaterializeInc/materialize/pull/15746) (@brennanvincent)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`65f6d9343` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/65f6d9343e6fd15797f78cc1e506ad6f6eacd75f) (@materializer)
* [ ] [`bebb55f00` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bebb55f00ce6640b85e5176fc0327da10bae4703) (@materializer)
* [ ] [`81bd681de` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/81bd681dedcdf1a341f125159aeb05efe74bbe11) (@materializer)
* [ ] [`bf9415b37` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bf9415b3772848a7d890fdc90e0caa7c5804cef8) (@materializer)
* [ ] [`fd524a1d0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fd524a1d02dd1dea58afae6572606cfcd0aea871) (@materializer)
* [ ] [`e0d5764af` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e0d5764af7f494ab97896b8737ee366b7f0b90e1) (@materializer)
* [ ] [`0164c9e0f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0164c9e0ff7599047ed8f3f6906c333470fbe4d4) (@materializer)
* [ ] [`8a3d94942` release: bump to version v0.30.0](https://github.com/MaterializeInc/materialize/commit/8a3d949421bd1cb10e7951036a5a87790d028ca0) (@brennanvincent)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15521 doc,test: update for correct handling of subsource sizes](https://github.com/MaterializeInc/materialize/pull/15521) (@benesch)
* [ ] [#15660 ore: configure sentry to attach stack traces](https://github.com/MaterializeInc/materialize/pull/15660) (@benesch)
* [ ] [#15664 storage: move kafka sink to new timely/async integration](https://github.com/MaterializeInc/materialize/pull/15664) (@petrosagg)
* [ ] [#15669 zippy: Add a scenario using parallel Kafka inserts](https://github.com/MaterializeInc/materialize/pull/15669) (@philip-stoev)
* [ ] [#15670 storage: update rustdoc for StorageController::update_write_frontiers](https://github.com/MaterializeInc/materialize/pull/15670) (@aljoscha)
* [ ] [#15682 release: bump to version v0.30.0-dev](https://github.com/MaterializeInc/materialize/pull/15682) (@benesch)
* [ ] [#15658 doc/user: add example for flattening `jsonb` array](https://github.com/MaterializeInc/materialize/pull/15658) (@morsapaes)
* [ ] [#15690 doc/user: update documentation about default cluster](https://github.com/MaterializeInc/materialize/pull/15690) (@benesch)
* [ ] [#15695 zippy: Reduce the number of rows in the UserTables scenario](https://github.com/MaterializeInc/materialize/pull/15695) (@philip-stoev)
* [ ] [#15553 ci,mzcompose: Run all mzcompose tests with SIZE 4 / --workers 4 by de…](https://github.com/MaterializeInc/materialize/pull/15553) (@philip-stoev)
* [ ] [#15697 Add a regression test for #15535](https://github.com/MaterializeInc/materialize/pull/15697) (@teskje)
* [ ] [#15699 storage: downgrade potentially alarming error logs to trace logs](https://github.com/MaterializeInc/materialize/pull/15699) (@aljoscha)
* [ ] [#15485 doc/user: fix overflow in diagrams](https://github.com/MaterializeInc/materialize/pull/15485) (@joacoc)
* [ ] [#15643 doc/user: disable 'how fast are my sources...' in docs](https://github.com/MaterializeInc/materialize/pull/15643) (@joacoc)
* [ ] [#15631 Add SQL error guidance to developer style guide](https://github.com/MaterializeInc/materialize/pull/15631) (@chaas)
* [ ] [#15568 Improve error message for unknown types in postgres source](https://github.com/MaterializeInc/materialize/pull/15568) (@chaas)
* [ ] [#15675 [storage] Filter the InvalidUppers error to only relevant ids](https://github.com/MaterializeInc/materialize/pull/15675) (@bkirwi)
* [ ] [#15635 adapter: add log lines to bootstrap](https://github.com/MaterializeInc/materialize/pull/15635) (@benesch)
* [ ] [#15709 Revert "persist: special case compaction for a single nonempty batch in inputs"](https://github.com/MaterializeInc/materialize/pull/15709) (@pH14)
* [ ] [#15612 sql: add pre-function selection type conversion for int + uint](https://github.com/MaterializeInc/materialize/pull/15612) (@sploiselle)
* [ ] [#15713 marginally improve compute startup logs](https://github.com/MaterializeInc/materialize/pull/15713) (@brennanvincent)
* [ ] [#15712 test: Fix test flake on pgwire::test_pgtest](https://github.com/MaterializeInc/materialize/pull/15712) (@jkosh44)
* [ ] [#15710 tracing: filter librdkafka events out from sentry](https://github.com/MaterializeInc/materialize/pull/15710) (@guswynn)
* [ ] [#15632 sql: refactor subsource AST handling](https://github.com/MaterializeInc/materialize/pull/15632) (@sploiselle)
* [ ] [#15717 sql: adjust required cast context for uint16 -> int16](https://github.com/MaterializeInc/materialize/pull/15717) (@sploiselle)
* [ ] [#15689 doc/user: polish v0.29.0 release notes](https://github.com/MaterializeInc/materialize/pull/15689) (@morsapaes)
* [ ] [#15550 doc/user: use new parenthesis syntax for options](https://github.com/MaterializeInc/materialize/pull/15550) (@benesch)
* [ ] [#15721 doc: specify anchor targets for ambiguous links](https://github.com/MaterializeInc/materialize/pull/15721) (@mjibson)
* [ ] [#15726 pg-cdc: Fix merge skew in test/pg-cdc/pg-cdc.td](https://github.com/MaterializeInc/materialize/pull/15726) (@philip-stoev)
* [ ] [#15467 Perform add replica orchestrator calls outside coord thread](https://github.com/MaterializeInc/materialize/pull/15467) (@lluki)
* [ ] [#15729 doc: Remove redundant lines in python examples](https://github.com/MaterializeInc/materialize/pull/15729) (@lluki)
* [ ] [#15614 Fix replica frontier tracking in compute](https://github.com/MaterializeInc/materialize/pull/15614) (@teskje)
* [ ] [#15734 storage: in rehydrating client, be lenient about extra upper updates](https://github.com/MaterializeInc/materialize/pull/15734) (@aljoscha)
* [ ] [#15727 sql: remote replica must have same number of compute addresses](https://github.com/MaterializeInc/materialize/pull/15727) (@lluki)
* [ ] [#15739 doc/developer: add an error message example](https://github.com/MaterializeInc/materialize/pull/15739) (@ggnall)
* [ ] [#15714 adapter: de-duplicate identical notices](https://github.com/MaterializeInc/materialize/pull/15714) (@mjibson)
* [ ] [#15724 environmentd: deflake test_auth_expiry](https://github.com/MaterializeInc/materialize/pull/15724) (@mjibson)
* [ ] [#15730 compute controller: don't remove cancelled peeks immediately](https://github.com/MaterializeInc/materialize/pull/15730) (@teskje)
* [ ] [#15586 [sinks] Create healthchecker and surface indefinite errors](https://github.com/MaterializeInc/materialize/pull/15586) (@cjubb39)
* [ ] [#15738 stash: Add batched APIs for update and remove](https://github.com/MaterializeInc/materialize/pull/15738) (@jkosh44)
* [ ] [#15745 persist: be more lenient when applying compaction diffs to state](https://github.com/MaterializeInc/materialize/pull/15745) (@danhhz)
* [ ] [#15732 persist: substantially improve compaction perf](https://github.com/MaterializeInc/materialize/pull/15732) (@pH14)
* [ ] [#15703 Protect `Subscribe` against computed-based OOMs](https://github.com/MaterializeInc/materialize/pull/15703) (@frankmcsherry)
* [ ] [#15737 compute-controller: Fix race between replica crash and drop](https://github.com/MaterializeInc/materialize/pull/15737) (@lluki)
* [ ] [#15576 Privatelink connection](https://github.com/MaterializeInc/materialize/pull/15576) (@alex-hunt-materialize)
* [ ] [#15750 storage: turn off strict host checking in ssh tunnels](https://github.com/MaterializeInc/materialize/pull/15750) (@guswynn)
* [ ] [#15743 [sinks] [kafka] Remove explicit Init/Running state machine](https://github.com/MaterializeInc/materialize/pull/15743) (@cjubb39)
* [ ] [#15741 doc/developer: add a log message style guide](https://github.com/MaterializeInc/materialize/pull/15741) (@benesch)
* [ ] [#15753 Limit heartbeat activation of persist sinks](https://github.com/MaterializeInc/materialize/pull/15753) (@antiguru)
* [ ] [#15746 Add feature to save/load flamegraph traces](https://github.com/MaterializeInc/materialize/pull/15746) (@brennanvincent)
* [ ] [#15701 Clean up peeks that are no longer pending from compute command history ](https://github.com/MaterializeInc/materialize/pull/15701) (@vmarcos)
* [ ] [#15702 ci: fix check for unused Rust dependencies](https://github.com/MaterializeInc/materialize/pull/15702) (@teskje)
* [ ] [#15679 Update index usage docs](https://github.com/MaterializeInc/materialize/pull/15679) (@ggevay)
* [ ] [#15767 environmentd: decrease severity of conn errors](https://github.com/MaterializeInc/materialize/pull/15767) (@mjibson)
* [ ] [#15776 stash: use single-statement consolidate](https://github.com/MaterializeInc/materialize/pull/15776) (@mjibson)
* [ ] [#15678 coord: Restrict mz_introspection user privileges](https://github.com/MaterializeInc/materialize/pull/15678) (@jkosh44)
* [ ] [#15774 doc/user: list_agg does not take a delimiter](https://github.com/MaterializeInc/materialize/pull/15774) (@ahelium)
* [ ] [#15618 build(deps): bump toml_edit from 0.14.4 to 0.15.0](https://github.com/MaterializeInc/materialize/pull/15618) (@dependabot[bot])
* [ ] [#15617 build(deps): bump assert_cmd from 2.0.4 to 2.0.5](https://github.com/MaterializeInc/materialize/pull/15617) (@dependabot[bot])
* [ ] [#15616 build(deps): bump futures-util from 0.3.24 to 0.3.25](https://github.com/MaterializeInc/materialize/pull/15616) (@dependabot[bot])
* [ ] [#15615 build(deps): bump serde from 1.0.145 to 1.0.147](https://github.com/MaterializeInc/materialize/pull/15615) (@dependabot[bot])
* [ ] [#15758 Handle replica-targeting in the compute controller](https://github.com/MaterializeInc/materialize/pull/15758) (@teskje)
* [ ] [#15800 zippy,platform-checks: Clean up Process Orchestrator metadata on restart](https://github.com/MaterializeInc/materialize/pull/15800) (@philip-stoev)
* [ ] [#15806 doc/user: improve documentation on CREATE TABLE](https://github.com/MaterializeInc/materialize/pull/15806) (@morsapaes)
* [ ] [#15804 doc/developer: add some development tips to cloudtest.md](https://github.com/MaterializeInc/materialize/pull/15804) (@benesch)
* [ ] [#15796 doc: tweak mz_now() documentation](https://github.com/MaterializeInc/materialize/pull/15796) (@rjnn)
* [ ] [#15814 devcontainer: require 64g of disk](https://github.com/MaterializeInc/materialize/pull/15814) (@mjibson)
* [ ] [#15812 sql-parser: correct type of AwsPrivateLinkConnectionOption](https://github.com/MaterializeInc/materialize/pull/15812) (@benesch)
* [ ] [#15816 sql: Fix statement timeout error code](https://github.com/MaterializeInc/materialize/pull/15816) (@jkosh44)
* [ ] [#15802 doc/user: improve documentation on `SHOW CLUSTERS`](https://github.com/MaterializeInc/materialize/pull/15802) (@morsapaes)
* [ ] [#15765 sql/test: Add builtin schema migration test](https://github.com/MaterializeInc/materialize/pull/15765) (@jkosh44)
* [ ] [#15819 Add note about rebooting after changing rds.logical_replication](https://github.com/MaterializeInc/materialize/pull/15819) (@alex-hunt-materialize)
* [ ] [#15748 Test that even non-enforced keys get grouped properly](https://github.com/MaterializeInc/materialize/pull/15748) (@bkirwi)
* [ ] [#15818 stash: add set method to TableTransaction](https://github.com/MaterializeInc/materialize/pull/15818) (@mjibson)
* [ ] [#15736 compute-client: faster rehydration of failed replicas](https://github.com/MaterializeInc/materialize/pull/15736) (@teskje)
* [ ] [#15756 dbt-materialize: check and document connection parameters](https://github.com/MaterializeInc/materialize/pull/15756) (@ahelium)
* [ ] [#15773 *: introduce halting as a softer way to panic](https://github.com/MaterializeInc/materialize/pull/15773) (@benesch)
* [ ] [#15826 doc/user: update for v0.29.3](https://github.com/MaterializeInc/materialize/pull/15826) (@benesch)
* [ ] [#15801 compute-client: fix handling of subscribe reponses](https://github.com/MaterializeInc/materialize/pull/15801) (@teskje)
* [ ] [#15815 [mz] move all configuration management behind a single abstraction ](https://github.com/MaterializeInc/materialize/pull/15815) (@sjwiesman)
* [ ] [#15823 dbt-materialize: release v1.2.1](https://github.com/MaterializeInc/materialize/pull/15823) (@ahelium)
* [ ] [#15825 Avoid blocking Tokio runtime during cluster bootup.](https://github.com/MaterializeInc/materialize/pull/15825) (@brennanvincent)
* [ ] [`65f6d9343` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/65f6d9343e6fd15797f78cc1e506ad6f6eacd75f) (@materializer)
* [ ] [`bebb55f00` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bebb55f00ce6640b85e5176fc0327da10bae4703) (@materializer)
* [ ] [`81bd681de` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/81bd681dedcdf1a341f125159aeb05efe74bbe11) (@materializer)
* [ ] [`bf9415b37` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bf9415b3772848a7d890fdc90e0caa7c5804cef8) (@materializer)
* [ ] [`fd524a1d0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fd524a1d02dd1dea58afae6572606cfcd0aea871) (@materializer)
* [ ] [`e0d5764af` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e0d5764af7f494ab97896b8737ee366b7f0b90e1) (@materializer)
* [ ] [`0164c9e0f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0164c9e0ff7599047ed8f3f6906c333470fbe4d4) (@materializer)
* [ ] [`8a3d94942` release: bump to version v0.30.0](https://github.com/MaterializeInc/materialize/commit/8a3d949421bd1cb10e7951036a5a87790d028ca0) (@brennanvincent)

**Comment by benesch** [comment]
All unreviewed commits and PRs that I did not author LGTM.
