### ISSUE TITLE
release: v0.31.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#15973]
The following PRs in [`v0.31.0`](https://github.com/MaterializeInc/materialize/tree/v0.31.0) require review:
* [ ] [#15846 zippy,platform-checks: Add peek cancellation to frameworks](https://github.com/MaterializeInc/materialize/pull/15846) (@philip-stoev)
* [ ] [#15517 Unify IndexedFilter printing between fast path and dataflow](https://github.com/MaterializeInc/materialize/pull/15517) (@ggevay)
* [ ] [#15946 Get rid of stray debugging println](https://github.com/MaterializeInc/materialize/pull/15946) (@umanwizard)
* [ ] [#15797 adapter,sql[-parser]: allow referencing AWS PrivateLink connections](https://github.com/MaterializeInc/materialize/pull/15797) (@benesch)
* [ ] [#15950 testdrive: Fix system-cluster.td to run in cloudtest/K8s](https://github.com/MaterializeInc/materialize/pull/15950) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`70c9c45a7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/70c9c45a7dab4a9f11e914f22ca0c812cbd9aee2) (@materializer)
* [ ] [`ba19f29b3` Update lib.rs](https://github.com/MaterializeInc/materialize/commit/ba19f29b388cfdb4530407a62f5dbc84713de8fa) (@web-flow)
* [ ] [`0fc992e47` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0fc992e47fcb37f6a70c7e290bf57aca06909dc9) (@materializer)
* [ ] [`cb50ec791` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cb50ec79145a5bb5bffde6110fa093ae8199aa19) (@materializer)
* [ ] [`8a27d258d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8a27d258d5b0cc8c4afb7d3246dc903262e07766) (@materializer)
* [ ] [`436f275f6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/436f275f694b47bd3f3e46ea76c9052c1879f333) (@materializer)
* [ ] [`5323ed292` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5323ed292b1d550793f389078c370a4da2689c4a) (@materializer)
* [ ] [`250e4eff2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/250e4eff2a334a234b8ae4359327942f74b6fb08) (@materializer)
* [ ] [`09e815589` release: bump to version v0.31.0](https://github.com/MaterializeInc/materialize/commit/09e8155894b272200b6ef61e09c292251990a8b7) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15644 coord: Handle objects that are ahead of read hold](https://github.com/MaterializeInc/materialize/pull/15644) (@jkosh44)
* [ ] [#15835 persist: add missing "tracing" feature to mz_ore dep](https://github.com/MaterializeInc/materialize/pull/15835) (@danhhz)
* [ ] [#15809 coord: Add guard-rails to timestamp oracle API](https://github.com/MaterializeInc/materialize/pull/15809) (@jkosh44)
* [ ] [#15836 coord: Speed up storage collection usage](https://github.com/MaterializeInc/materialize/pull/15836) (@jkosh44)
* [ ] [#15838 adapter: only do a single read over storage usage](https://github.com/MaterializeInc/materialize/pull/15838) (@mjibson)
* [ ] [#15839 persist: increase write lease duration from 15m to 1h](https://github.com/MaterializeInc/materialize/pull/15839) (@danhhz)
* [ ] [#15846 zippy,platform-checks: Add peek cancellation to frameworks](https://github.com/MaterializeInc/materialize/pull/15846) (@philip-stoev)
* [ ] [#15844 testdrive: Fortify recent Kafka tests against message re-ordering](https://github.com/MaterializeInc/materialize/pull/15844) (@philip-stoev)
* [ ] [#15845 Prevent persist subscribe if dataflow token has been dropped](https://github.com/MaterializeInc/materialize/pull/15845) (@frankmcsherry)
* [ ] [#15852 persist: log when heartbeat tasks take longer than expected to fire](https://github.com/MaterializeInc/materialize/pull/15852) (@pH14)
* [ ] [#15837 persist: another special case in apply_diffs_spine](https://github.com/MaterializeInc/materialize/pull/15837) (@danhhz)
* [ ] [#15854 release: bump to version v0.31.0-dev](https://github.com/MaterializeInc/materialize/pull/15854) (@umanwizard)
* [ ] [#15857 stash: consolidate in a background task](https://github.com/MaterializeInc/materialize/pull/15857) (@mjibson)
* [ ] [#15848 doc/user: polish v0.30.0 release notes](https://github.com/MaterializeInc/materialize/pull/15848) (@morsapaes)
* [ ] [#15849 Always install introspection indexes](https://github.com/MaterializeInc/materialize/pull/15849) (@teskje)
* [ ] [#15728 ci: Run CI with SIZE '4-4' by default](https://github.com/MaterializeInc/materialize/pull/15728) (@philip-stoev)
* [ ] [#15867 sql: prohibit dropping subsources](https://github.com/MaterializeInc/materialize/pull/15867) (@sploiselle)
* [ ] [#15869 stash: set cockroach gc ttl](https://github.com/MaterializeInc/materialize/pull/15869) (@mjibson)
* [ ] [#15870 persist: cache len on SpineBatch::Fueled](https://github.com/MaterializeInc/materialize/pull/15870) (@danhhz)
* [ ] [#15824 stash-debug: add upgrade check](https://github.com/MaterializeInc/materialize/pull/15824) (@mjibson)
* [ ] [#15821 [sinks] Hold an extra handle for input data in the sink](https://github.com/MaterializeInc/materialize/pull/15821) (@bkirwi)
* [ ] [#15657 storage: restore panic when reclock compaction goes backwards](https://github.com/MaterializeInc/materialize/pull/15657) (@guswynn)
* [ ] [#15872 Add quick and dirty script for launching the flamegraph visualizer](https://github.com/MaterializeInc/materialize/pull/15872) (@umanwizard)
* [ ] [#15876 make mzfg formut robust to semicolons in symbol names](https://github.com/MaterializeInc/materialize/pull/15876) (@umanwizard)
* [ ] [#15881 storage: split out a client crate for faster compiles](https://github.com/MaterializeInc/materialize/pull/15881) (@petrosagg)
* [ ] [#15888 optbench: add `--db-pass` and `--db-require-ssl` CLI options](https://github.com/MaterializeInc/materialize/pull/15888) (@aalexandrov)
* [ ] [#15885 Prevent leak in progress tracking state](https://github.com/MaterializeInc/materialize/pull/15885) (@frankmcsherry)
* [ ] [#15880 otel: simplify and fix local jaeger setup](https://github.com/MaterializeInc/materialize/pull/15880) (@guswynn)
* [ ] [#15878 add knobs for sampling rate and time to the CPU profiler](https://github.com/MaterializeInc/materialize/pull/15878) (@umanwizard)
* [ ] [#15893 stash: expose epoch counter](https://github.com/MaterializeInc/materialize/pull/15893) (@mjibson)
* [ ] [#15895 fixed type-o](https://github.com/MaterializeInc/materialize/pull/15895) (@GregKarabinos)
* [ ] [#15902 update codebase for 1.65 clippy](https://github.com/MaterializeInc/materialize/pull/15902) (@guswynn)
* [ ] [#15868 persist: replace LeasedBatchPart's panic on drop with a metric](https://github.com/MaterializeInc/materialize/pull/15868) (@danhhz)
* [ ] [#15884 sql: don't add quotes when converting idents to values](https://github.com/MaterializeInc/materialize/pull/15884) (@benesch)
* [ ] [#15905 Update to 1.65](https://github.com/MaterializeInc/materialize/pull/15905) (@guswynn)
* [ ] [#15883 Make a few log lines less spammy](https://github.com/MaterializeInc/materialize/pull/15883) (@benesch)
* [ ] [#15882 computed,storaged,timely-util: halt, not panic, on TCP errors](https://github.com/MaterializeInc/materialize/pull/15882) (@benesch)
* [ ] [#15918 build(deps): bump native-tls from 0.2.10 to 0.2.11](https://github.com/MaterializeInc/materialize/pull/15918) (@dependabot[bot])
* [ ] [#15917 build(deps): bump prost from 0.11.0 to 0.11.2](https://github.com/MaterializeInc/materialize/pull/15917) (@dependabot[bot])
* [ ] [#15924 add TimeZone and interval_style to notify set](https://github.com/MaterializeInc/materialize/pull/15924) (@umanwizard)
* [ ] [#15910 Fix issues with psycopg3 SUBSCRIBE instructions](https://github.com/MaterializeInc/materialize/pull/15910) (@umanwizard)
* [ ] [#15911 build(deps): bump ubuntu from jammy-20221003 to jammy-20221101 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15911) (@dependabot[bot])
* [ ] [#15913 build(deps): bump boto3 from 1.24.91 to 1.26.3 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15913) (@dependabot[bot])
* [ ] [#15860 persist_source: Ensure drops also stop subscribe](https://github.com/MaterializeInc/materialize/pull/15860) (@lluki)
* [ ] [#15894 docs: bootstrap reference docs folder](https://github.com/MaterializeInc/materialize/pull/15894) (@aalexandrov)
* [ ] [#15862 Clean-up of leaking `CollectionState` metadata in compute controller](https://github.com/MaterializeInc/materialize/pull/15862) (@vmarcos)
* [ ] [#15900 Reduce MirScalarExprs when planning CREATE INDEX ](https://github.com/MaterializeInc/materialize/pull/15900) (@tokenrove)
* [ ] [#15932 Update mz CLI CLOUD_PROVIDERS path](https://github.com/MaterializeInc/materialize/pull/15932) (@arusahni)
* [ ] [#15871 Rewrite cluster startup flow to fix crash loops on restart](https://github.com/MaterializeInc/materialize/pull/15871) (@umanwizard)
* [ ] [#15928 fix capitalization in DROP MATERIALIZED VIEW response](https://github.com/MaterializeInc/materialize/pull/15928) (@umanwizard)
* [ ] [#15840 dbt-materialize: add BaseDocsTests](https://github.com/MaterializeInc/materialize/pull/15840) (@ahelium)
* [ ] [#15898 Coord: Separate capability of storage and compute](https://github.com/MaterializeInc/materialize/pull/15898) (@jkosh44)
* [ ] [#15929 Show warning about RAM usage on profiler page](https://github.com/MaterializeInc/materialize/pull/15929) (@umanwizard)
* [ ] [#15775 dbt-utils: move cross-database macros into dbt-materialize](https://github.com/MaterializeInc/materialize/pull/15775) (@ahelium)
* [ ] [#15933 Fix broken memory profiler due to #15878](https://github.com/MaterializeInc/materialize/pull/15933) (@umanwizard)
* [ ] [#15936 stash: optimize improve consolidation queries](https://github.com/MaterializeInc/materialize/pull/15936) (@mjibson)
* [ ] [#15909 storage: model type relationships through traits](https://github.com/MaterializeInc/materialize/pull/15909) (@petrosagg)
* [ ] [#15943 parser: fix NULLIF printing](https://github.com/MaterializeInc/materialize/pull/15943) (@mjibson)
* [ ] [#15744 [sinks] [status] Put sink status collection behind unsafe](https://github.com/MaterializeInc/materialize/pull/15744) (@cjubb39)
* [ ] [#15766 Join EXPLAIN improvements and other stuff](https://github.com/MaterializeInc/materialize/pull/15766) (@ggevay)
* [ ] [#15517 Unify IndexedFilter printing between fast path and dataflow](https://github.com/MaterializeInc/materialize/pull/15517) (@ggevay)
* [ ] [#15945 persist: add debugging information for unexpectedly long seqno holds](https://github.com/MaterializeInc/materialize/pull/15945) (@danhhz)
* [ ] [#15934 Print status in SHOW CLUSTER REPLICAS](https://github.com/MaterializeInc/materialize/pull/15934) (@umanwizard)
* [ ] [#15946 Get rid of stray debugging println](https://github.com/MaterializeInc/materialize/pull/15946) (@umanwizard)
* [ ] [#15797 adapter,sql[-parser]: allow referencing AWS PrivateLink connections](https://github.com/MaterializeInc/materialize/pull/15797) (@benesch)
* [ ] [#15950 testdrive: Fix system-cluster.td to run in cloudtest/K8s](https://github.com/MaterializeInc/materialize/pull/15950) (@philip-stoev)
* [ ] [#15953 docs: add `CONTRIBUTING.md` for reference developer docs](https://github.com/MaterializeInc/materialize/pull/15953) (@aalexandrov)
* [ ] [#15604 doc(user): pattern for single parsing](https://github.com/MaterializeInc/materialize/pull/15604) (@joacoc)
* [ ] [#15751 Reconcile dataflows differently](https://github.com/MaterializeInc/materialize/pull/15751) (@frankmcsherry)
* [ ] [#15958 coord: Don't count subsources for resource limits](https://github.com/MaterializeInc/materialize/pull/15958) (@jkosh44)
* [ ] [`70c9c45a7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/70c9c45a7dab4a9f11e914f22ca0c812cbd9aee2) (@materializer)
* [ ] [`ba19f29b3` Update lib.rs](https://github.com/MaterializeInc/materialize/commit/ba19f29b388cfdb4530407a62f5dbc84713de8fa) (@web-flow)
* [ ] [`0fc992e47` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0fc992e47fcb37f6a70c7e290bf57aca06909dc9) (@materializer)
* [ ] [`cb50ec791` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cb50ec79145a5bb5bffde6110fa093ae8199aa19) (@materializer)
* [ ] [`8a27d258d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8a27d258d5b0cc8c4afb7d3246dc903262e07766) (@materializer)
* [ ] [`436f275f6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/436f275f694b47bd3f3e46ea76c9052c1879f333) (@materializer)
* [ ] [`5323ed292` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5323ed292b1d550793f389078c370a4da2689c4a) (@materializer)
* [ ] [`250e4eff2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/250e4eff2a334a234b8ae4359327942f74b6fb08) (@materializer)
* [ ] [`09e815589` release: bump to version v0.31.0](https://github.com/MaterializeInc/materialize/commit/09e8155894b272200b6ef61e09c292251990a8b7) (@umanwizard)

**Comment by guswynn** [comment]
commits LGTM
