### ISSUE TITLE
[Epic] Back-End Work in Support of Real-Time Recency

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#16060]
### Problem

To support our correctness guarantees and be able to answer questions such as "is my view up to date", `STORAGE` needs to expose reclocking data to both `ADAPTER` and the end-user.

### Acceptance Criteria

Storage exposes the relevant reclocking data such that Surfaces can correctly determine timestamps for real-time recency.

### Priority

High

### Size

Large

### Eng Tasks

- [ ] https://github.com/MaterializeInc/materialize/issues/12867
- [ ] https://github.com/MaterializeInc/materialize/issues/13149

### Testing

TBD

### Blockers

None

### Blocks

https://github.com/MaterializeInc/materialize/issues/11531

**Comment by sploiselle** [comment]
Here's a more detailed roadmap for an MVP of RTR.

- [ ] envd feature flag work #11531
- [ ] design process
	- [ ] prototype: we decided to start with a prototype which first determines the upstream's frontier (in its native logical timestamp) and then listens to updates in the remap shard until we see that frontier pass by; the RTR timestamp is the MZ timestamp at which we first encounter the upstream frontier. We do that in `envd` in the storage controller because it's the easiest place to wire everything together. [Notion link](https://www.notion.so/materialize/Storage-meeting-on-RTR-subsource-dependency-inversion-e8d31a2eeb9d4a7b91e419240c4f9f6e#4ef0bfdd108647fdbd3d176a66c81e99)
	- [ ] iteration
		- [ ] make the solution more scalable
		- [ ] investigate what moving RTR timestamps into reclocking would look like
- [ ] Coding: building prototype #25195
- [ ] QA (_in progress_): Ensure that the prototype meets QA's requirements (i.e. it works and doesn't cause everything to fall over when it's in use)
- [ ] Code review
- [ ] PrPr release
	- [ ] Docs?

**Comment by ryanwith** [comment]
Could someone explain to me what the customer benefit of this is?  Is it that it exposes lag?

**Comment by sploiselle** [comment]
@ryanwith https://materialize.com/docs/get-started/isolation-level/#real-time-recency

**Comment by ryanwith** [comment]
@sploiselle can you confirm if my understanding is correct?
1/ Materialize sees data at time 0 at begins dataflow
2/ Materialize processes the dataflow for 10 seconds
3/ Materialize has data fully processed at time 10

With real-time-recency, a query issued between 0 and time 10 will not return results until ~time 10, and when it returns, it will include the data that was ingested at time 0 instead of just what was already processed at time 0?
