### ISSUE TITLE
[Epic] persist: Support for manual restoration of an environment - milestone 1

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#16082]
### Feature request
In the event of data corruption of a customers environment we need some mechanism for restoring the environment state as of a previous point in time. This is the tracking ticket for the first milestone of this work, which has a goal of being able to manually restore a customers environment in case of corruption however with heavy engineering involvement. Future milestones will involve more automation and guardrails for this process

This is the storage team's tracking ticket. Details TBD.
```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/materialize/pull/18157
- [ ] https://github.com/MaterializeInc/materialize/issues/22770
- [ ] https://github.com/MaterializeInc/materialize/issues/22982
- [x] Playbook and dry run in QA
- [ ] https://github.com/MaterializeInc/materialize/issues/23287
```
```[tasklist]
### Followups
- [ ] https://github.com/MaterializeInc/materialize/issues/22814
- [ ] https://github.com/MaterializeInc/materialize/issues/22816
- [ ] https://github.com/MaterializeInc/materialize/issues/22762
```

**Comment by bkirwi** [comment]
Time for an update!

The original scope of this ticket is ~complete: we can now recover the S3 state that corresponds to a particular CRDB snapshot, and we've tested that this restore process works in CI and in Staging.

There are two categories of issues left open on this epic:
- "Footgun reduction". For example, bad things will happen if you try and restore a CRDB backup while MZ is also writing to the same database. Right now it is the operator's job to make sure that doesn't happen; it would be nice if we could catch that sort of thing automatically, though.
- Sources and sinks. While we can now restore our internal state to a consistent snapshot, we can't restore an external system to the state it was in at that time. In the worst case, this can cause corruption as eg. a source retracts data that isn't present in the backup; even in the best case we may need to put a source or sink in a permanent "stalled" state.

Neither of these are strictly Persist issues, so on one hand I'm tempted to call this specific epic done. On the other: I think the consistency issue with restoring the PG source in particular is particularly bad, and I'd like to get that fixed before we put this aside. In theory the PG source has an existing consistency check for this, but it's been disabled due to some other recent changes. The most recent discussion is here: https://github.com/MaterializeInc/materialize/issues/23287
