### ISSUE TITLE
release: v0.32.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16084]
The following PRs in [`v0.32.0`](https://github.com/MaterializeInc/materialize/tree/v0.32.0) require review:
* [x] [#15979 testdrive: Fix connection-create-drop.td to run in cloudtest/K8s](https://github.com/MaterializeInc/materialize/pull/15979) (@philip-stoev)
* [x] [#16008 ci: install a placeholder Release Qualification pipeline](https://github.com/MaterializeInc/materialize/pull/16008) (@philip-stoev)
* [x] [#16049 testdrive: Fortify cvs-sources.td against #16048](https://github.com/MaterializeInc/materialize/pull/16049) (@philip-stoev)
* [x] [#16077 test/cluster: Increase the timeout for the 'cluster' test](https://github.com/MaterializeInc/materialize/pull/16077) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`d5a263ab4` fix bump-version](https://github.com/MaterializeInc/materialize/commit/d5a263ab4cf54953aaff07047d91615c72e2d37d) (@umanwizard)
* [x] [`5f02b0da1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5f02b0da138ad2b6cf53ee0db96f7f475ce67c25) (@materializer)
* [x] [`8a5118aaf` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8a5118aafb9363bea2c111d26c7fb45c7d4e5e4d) (@materializer)
* [x] [`7a4f0851d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7a4f0851d857371d054f090bbf7610774187cf88) (@materializer)
* [x] [`a86790840` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a86790840771537cd51ce457f4ea402b7045e2db) (@materializer)
* [x] [`c7cde8202` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c7cde82020800ea6eefa6a0f91ccc94a6826a20e) (@materializer)
* [x] [`b3b7dffb2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b3b7dffb21fc9060eaf794492ceadeba3bb48bd7) (@materializer)
* [x] [`bc18d36df` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bc18d36df820a6177a364bc48a2f564f6f43943c) (@materializer)
* [x] [`b04623960` release: bump to version v0.32.0](https://github.com/MaterializeInc/materialize/commit/b0462396039605f112bb5873d4c88771d77e4bdc) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15927 storage: punctuation response for strict id checks](https://github.com/MaterializeInc/materialize/pull/15927) (@petrosagg)
* [ ] [#15951 mzcompose: Fortify mzcompose against #15725](https://github.com/MaterializeInc/materialize/pull/15951) (@philip-stoev)
* [ ] [#15966 Minor doc update for index lookups](https://github.com/MaterializeInc/materialize/pull/15966) (@ggevay)
* [ ] [#15940 k8s-orchestrator: logically name containers](https://github.com/MaterializeInc/materialize/pull/15940) (@guswynn)
* [ ] [#15971 sqllogictest: teach simple about users](https://github.com/MaterializeInc/materialize/pull/15971) (@mjibson)
* [ ] [#15959 compute: assert that imported indexes are not compacted](https://github.com/MaterializeInc/materialize/pull/15959) (@teskje)
* [ ] [#15975 release: bump to version v0.32.0-dev](https://github.com/MaterializeInc/materialize/pull/15975) (@umanwizard)
* [ ] [#15822 persist: introduce "critical" SinceHandles](https://github.com/MaterializeInc/materialize/pull/15822) (@danhhz)
* [ ] [#15967 Clean up of frontier introspection events during reconciliation](https://github.com/MaterializeInc/materialize/pull/15967) (@vmarcos)
* [ ] [#15978 expr: correctly return NULL on jsonb path array](https://github.com/MaterializeInc/materialize/pull/15978) (@mjibson)
* [ ] [#15972 storage: fix nightly unused deps check](https://github.com/MaterializeInc/materialize/pull/15972) (@petrosagg)
* [ ] [#15979 testdrive: Fix connection-create-drop.td to run in cloudtest/K8s](https://github.com/MaterializeInc/materialize/pull/15979) (@philip-stoev)
* [ ] [#15762 Doc: add Confluent ACLs references](https://github.com/MaterializeInc/materialize/pull/15762) (@bobbyiliev)
* [ ] [#15987 persist: remove dep on tokio-test](https://github.com/MaterializeInc/materialize/pull/15987) (@danhhz)
* [ ] [#15875 dbt v1.3.0](https://github.com/MaterializeInc/materialize/pull/15875) (@ahelium)
* [ ] [#15986 Regression testing for invalid retractions from `mz_worker_compute_frontiers` upon reconciliation](https://github.com/MaterializeInc/materialize/pull/15986) (@vmarcos)
* [ ] [#15976 coord: Implement introspection source migrations](https://github.com/MaterializeInc/materialize/pull/15976) (@jkosh44)
* [ ] [#15988 Remove a stale TODO](https://github.com/MaterializeInc/materialize/pull/15988) (@teskje)
* [ ] [#15989 persist: fix comparison on `since` for updating `opaque`; actually rate limit](https://github.com/MaterializeInc/materialize/pull/15989) (@pH14)
* [ ] [#15997 persist: use a new Opaque trait instead of Default for CaDS](https://github.com/MaterializeInc/materialize/pull/15997) (@danhhz)
* [ ] [#15879 Correct type in reachability source](https://github.com/MaterializeInc/materialize/pull/15879) (@frankmcsherry)
* [ ] [#15633 [sources] Write source errors to persist](https://github.com/MaterializeInc/materialize/pull/15633) (@bkirwi)
* [ ] [#15977 doc/user: polish v0.31.0 release notes](https://github.com/MaterializeInc/materialize/pull/15977) (@morsapaes)
* [ ] [#15992 dbt-materialize: release v1.3.0](https://github.com/MaterializeInc/materialize/pull/15992) (@ahelium)
* [ ] [#15982 doc/user: hodgepodge improvements to navigation and guides](https://github.com/MaterializeInc/materialize/pull/15982) (@morsapaes)
* [ ] [#15960 compute-controller: Fix remove crashing replica](https://github.com/MaterializeInc/materialize/pull/15960) (@lluki)
* [ ] [#15990 Doc: add reference to status page API](https://github.com/MaterializeInc/materialize/pull/15990) (@bobbyiliev)
* [ ] [#16005 Bump hyper from 0.14.20 to 0.14.23](https://github.com/MaterializeInc/materialize/pull/16005) (@teskje)
* [ ] [#15547 doc/user: cube integration guide](https://github.com/MaterializeInc/materialize/pull/15547) (@joacoc)
* [ ] [#16001 adapter: remove replica not ready notice](https://github.com/MaterializeInc/materialize/pull/16001) (@mjibson)
* [ ] [#16016 persist: fix "ships passing" build break](https://github.com/MaterializeInc/materialize/pull/16016) (@danhhz)
* [ ] [#16019 doc/user: Unpublish quickstarts index](https://github.com/MaterializeInc/materialize/pull/16019) (@ruf-io)
* [ ] [#16022 storage: cleanup stored sink state on drop response](https://github.com/MaterializeInc/materialize/pull/16022) (@petrosagg)
* [ ] [#16014 [sinks] Unify parameters of StorageSinkDesc](https://github.com/MaterializeInc/materialize/pull/16014) (@cjubb39)
* [ ] [#16025 Improve compute controller error handling](https://github.com/MaterializeInc/materialize/pull/16025) (@teskje)
* [ ] [#16020 adapter: add metrics for some adapter client ops](https://github.com/MaterializeInc/materialize/pull/16020) (@mjibson)
* [ ] [#16013 stash: use metrics for transactions and errors](https://github.com/MaterializeInc/materialize/pull/16013) (@mjibson)
* [ ] [#15938 sql: include actual catalog item type in 'is not of type x' errors](https://github.com/MaterializeInc/materialize/pull/15938) (@chaas)
* [ ] [#16032 doc/user: update memory visualizer URL for cloud](https://github.com/MaterializeInc/materialize/pull/16032) (@benesch)
* [ ] [#16033 run an init container for computed and storaged if requested](https://github.com/MaterializeInc/materialize/pull/16033) (@doy-materialize)
* [ ] [#15877 instrument pgwire with some metrics](https://github.com/MaterializeInc/materialize/pull/15877) (@doy-materialize)
* [ ] [#16035 Add the unique replica ID to `mz_audit_events`](https://github.com/MaterializeInc/materialize/pull/16035) (@necaris)
* [ ] [#15912 build(deps): bump ubuntu from jammy-20221003 to jammy-20221101 in /misc/images/ubuntu-base](https://github.com/MaterializeInc/materialize/pull/15912) (@dependabot[bot])
* [ ] [#16041 build(deps): bump indicatif from 0.17.1 to 0.17.2](https://github.com/MaterializeInc/materialize/pull/16041) (@dependabot[bot])
* [ ] [#15908 sql: begin to use structured errors in purification](https://github.com/MaterializeInc/materialize/pull/15908) (@guswynn)
* [ ] [#16047 ci: Use larger EC2 instances for some Nightly CI jobs](https://github.com/MaterializeInc/materialize/pull/16047) (@philip-stoev)
* [ ] [#16008 ci: install a placeholder Release Qualification pipeline](https://github.com/MaterializeInc/materialize/pull/16008) (@philip-stoev)
* [ ] [#16049 testdrive: Fortify cvs-sources.td against #16048](https://github.com/MaterializeInc/materialize/pull/16049) (@philip-stoev)
* [ ] [#15969 adapter: add `window_functions` feature flag](https://github.com/MaterializeInc/materialize/pull/15969) (@aalexandrov)
* [ ] [#16051 ore: add `Vec::drain_filter_swapping` method](https://github.com/MaterializeInc/materialize/pull/16051) (@petrosagg)
* [ ] [#16009 Monitoring of `computed` compute command history size](https://github.com/MaterializeInc/materialize/pull/16009) (@vmarcos)
* [ ] [#16053 kafka-util,ssh-util: Remove unused dependencies](https://github.com/MaterializeInc/materialize/pull/16053) (@philip-stoev)
* [ ] [#15817 [mz] Add create, set, and show commands](https://github.com/MaterializeInc/materialize/pull/15817) (@sjwiesman)
* [ ] [#16031 timely-util: ode to the polonius crab](https://github.com/MaterializeInc/materialize/pull/16031) (@petrosagg)
* [ ] [#16037 Add back a log message for when the network is successfully established](https://github.com/MaterializeInc/materialize/pull/16037) (@umanwizard)
* [ ] [#16030 testdrive: support DETAIL and HINT assertions](https://github.com/MaterializeInc/materialize/pull/16030) (@guswynn)
* [ ] [#16015 storage: add basic source progress metrics](https://github.com/MaterializeInc/materialize/pull/16015) (@guswynn)
* [ ] [#16063 adapter: measure coord select busy time](https://github.com/MaterializeInc/materialize/pull/16063) (@mjibson)
* [ ] [#16011 [sources] Thread more errors through to the health check](https://github.com/MaterializeInc/materialize/pull/16011) (@bkirwi)
* [ ] [#15999 [storage] Don't panic if someone else moves table upper](https://github.com/MaterializeInc/materialize/pull/15999) (@cjubb39)
* [ ] [#16066 orchestrator-kubernetes: use _ instead of / as separator](https://github.com/MaterializeInc/materialize/pull/16066) (@benesch)
* [ ] [#16069 storage: replace force_yield with tokio::task::yield_now](https://github.com/MaterializeInc/materialize/pull/16069) (@guswynn)
* [ ] [#16058 Add service_metrics API to namespaced orchestrator](https://github.com/MaterializeInc/materialize/pull/16058) (@umanwizard)
* [ ] [#16046 environmentd: make --bootstrap-system-var consistent](https://github.com/MaterializeInc/materialize/pull/16046) (@benesch)
* [ ] [#16073 kafka-util: add info! log when rewriting a broker address](https://github.com/MaterializeInc/materialize/pull/16073) (@benesch)
* [ ] [#16075 buildkite: Do not fail if 'docker-compose kill' fails in pre-exit hook](https://github.com/MaterializeInc/materialize/pull/16075) (@philip-stoev)
* [ ] [#16077 test/cluster: Increase the timeout for the 'cluster' test](https://github.com/MaterializeInc/materialize/pull/16077) (@philip-stoev)
* [ ] [#15841 sql: fix database scoping in pg_catalog and information_schema](https://github.com/MaterializeInc/materialize/pull/15841) (@benesch)
* [ ] [#16010 sql+storage: allow ingesting unsupported types as text](https://github.com/MaterializeInc/materialize/pull/16010) (@sploiselle)
* [ ] [`d5a263ab4` fix bump-version](https://github.com/MaterializeInc/materialize/commit/d5a263ab4cf54953aaff07047d91615c72e2d37d) (@umanwizard)
* [ ] [`5f02b0da1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5f02b0da138ad2b6cf53ee0db96f7f475ce67c25) (@materializer)
* [ ] [`8a5118aaf` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8a5118aafb9363bea2c111d26c7fb45c7d4e5e4d) (@materializer)
* [ ] [`7a4f0851d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7a4f0851d857371d054f090bbf7610774187cf88) (@materializer)
* [ ] [`a86790840` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a86790840771537cd51ce457f4ea402b7045e2db) (@materializer)
* [ ] [`c7cde8202` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c7cde82020800ea6eefa6a0f91ccc94a6826a20e) (@materializer)
* [ ] [`b3b7dffb2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b3b7dffb21fc9060eaf794492ceadeba3bb48bd7) (@materializer)
* [ ] [`bc18d36df` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bc18d36df820a6177a364bc48a2f564f6f43943c) (@materializer)
* [ ] [`b04623960` release: bump to version v0.32.0](https://github.com/MaterializeInc/materialize/commit/b0462396039605f112bb5873d4c88771d77e4bdc) (@umanwizard)

**Comment by benesch** [comment]
LGTM
