### ISSUE TITLE
[Epic] Allow querying historical data (`AS OF` and related issues),

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#16359]
### Product Outcome

Materialize will allow querying relations at times other than the present (`AS OF`). Furthermore, to make this useful, the user must be able to specify compaction frontiers other than 1ms in the past.

### Specification

(None exists yet)

### Design

(None exists yet)

### Required Issues (Must Haves)

- [x] https://github.com/MaterializeInc/materialize/issues/16356
- [x] https://github.com/MaterializeInc/materialize/issues/16357
- [x] https://github.com/MaterializeInc/materialize/issues/16358

### Discretionary Issues (Nice To Haves)

None yet

**Comment by RobinClowers** [comment]
This is done, right?
