### ISSUE TITLE
release: v0.33.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16376]
The following PRs in [`v0.33.0`](https://github.com/MaterializeInc/materialize/tree/v0.33.0) require review:
* [x] [#16133 Add some commentary to the top of .mzfg files](https://github.com/MaterializeInc/materialize/pull/16133) (@umanwizard)
* [x] [#16162 doc/user: remove duplicated clause from load gen source syntax diagram](https://github.com/MaterializeInc/materialize/pull/16162) (@benesch)
* [x] [#16166 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/16166) (@benesch)
* [x] [#16192 deps: bump Rust dependencies](https://github.com/MaterializeInc/materialize/pull/16192) (@benesch)
* [x] [#16193 testdrive: Adjust fix-replica-targeted-select.td for cloudtest](https://github.com/MaterializeInc/materialize/pull/16193) (@philip-stoev)
* [x] [#16196 deps: bump to open v3.2.0](https://github.com/MaterializeInc/materialize/pull/16196) (@benesch)
* [x] [#16006 Zippy parameterized actions](https://github.com/MaterializeInc/materialize/pull/16006) (@philip-stoev)
* [x] [#16242 Remove dead constant](https://github.com/MaterializeInc/materialize/pull/16242) (@umanwizard)
* [x] [#16262 testdrive: Fortify cvs-sources.td against #16048 (Part #3)](https://github.com/MaterializeInc/materialize/pull/16262) (@philip-stoev)
* [x] [#16267 ci: Run the Release Qualification Test with the right queue](https://github.com/MaterializeInc/materialize/pull/16267) (@philip-stoev)
* [x] [#16286 zippy: Increase the timeout of the KafkaSourcesLarge test to 48h](https://github.com/MaterializeInc/materialize/pull/16286) (@philip-stoev)
* [x] [#16287 feature-benchmark: Re-enable for the Platform era](https://github.com/MaterializeInc/materialize/pull/16287) (@philip-stoev)
* [x] [#16311 feature-benchmark: Increase the retry attempts to 5](https://github.com/MaterializeInc/materialize/pull/16311) (@philip-stoev)
* [x] [#16328 platform checks: Restart Debezium and Redpanda together](https://github.com/MaterializeInc/materialize/pull/16328) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`859332c10` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/859332c10b1d5efce84db2be42ff18d7ee719cc2) (@materializer)
* [x] [`3df034a0d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3df034a0d4440e7a8bd0d176f63094b185313d4f) (@materializer)
* [x] [`97e8105d8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/97e8105d865a26e888e2ef4fdbead3bf69802052) (@materializer)
* [x] [`7aa2cfab2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7aa2cfab21b22e575a39234b84775eac77ddb075) (@materializer)
* [x] [`30bd48701` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/30bd48701d92002ffa88b2df5971fa384c2daa1d) (@materializer)
* [x] [`fc6b99bd4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fc6b99bd4f950804d9d21729d8f6d38bc3318701) (@materializer)
* [x] [`94d58a158` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/94d58a158329f3d6f01975ed388b09ba6b01bcb0) (@materializer)
* [x] [`24ead302a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/24ead302a98be7668cd1ee993ea78db580d9631a) (@materializer)
* [x] [`cf5b24d1d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cf5b24d1d4e96ea139ca8c7982640621e5d6951f) (@materializer)
* [x] [`7f1b71041` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7f1b71041c4eb3868fce022332b960055584036c) (@materializer)
* [x] [`1766ab397` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1766ab3978bc90abf75eb9b1fbadfcc95eca1993) (@materializer)
* [x] [`b7b1ca8df` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b7b1ca8df98f4e941226bd2bef5fdab6ee300c48) (@materializer)
* [x] [`354efaf84` release: bump to version v0.33.0](https://github.com/MaterializeInc/materialize/commit/354efaf8489430a3493dc4bf8a25999e6d666e91) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#15970 add dark mode + make the design consistent with www.](https://github.com/MaterializeInc/materialize/pull/15970) (@nisarhassan12)
* [ ] [#16055 sql[-parser]: remove STATISTICS INTERVAL MS Kafka option](https://github.com/MaterializeInc/materialize/pull/16055) (@benesch)
* [ ] [#16132 persist: fix rustdoc of `compare_and_downgrace_since`](https://github.com/MaterializeInc/materialize/pull/16132) (@aljoscha)
* [ ] [#16116 adapter: Prevent resource leaks in connection DDL](https://github.com/MaterializeInc/materialize/pull/16116) (@jkosh44)
* [ ] [#16134 docs: missing Materialize at start of sentence](https://github.com/MaterializeInc/materialize/pull/16134) (@ruchirK)
* [ ] [#16101 dbt-materialize: fix custom seed materialization, re-enable tests](https://github.com/MaterializeInc/materialize/pull/16101) (@morsapaes)
* [ ] [#16099 Find a starting arrangement for a linear join](https://github.com/MaterializeInc/materialize/pull/16099) (@frankmcsherry)
* [ ] [#16094 [sources / sinks] Status history views](https://github.com/MaterializeInc/materialize/pull/16094) (@bkirwi)
* [ ] [#16133 Add some commentary to the top of .mzfg files](https://github.com/MaterializeInc/materialize/pull/16133) (@umanwizard)
* [ ] [#16117 adapter: add determine_timestamp metrics](https://github.com/MaterializeInc/materialize/pull/16117) (@mjibson)
* [ ] [#16135 dbt-materialize: release v1.3.2](https://github.com/MaterializeInc/materialize/pull/16135) (@morsapaes)
* [ ] [#16136 coord: Refactor catalog_transact](https://github.com/MaterializeInc/materialize/pull/16136) (@jkosh44)
* [ ] [#16097 Adapter: add notice for invalid database or cluster name in SET command](https://github.com/MaterializeInc/materialize/pull/16097) (@chaas)
* [ ] [#16129 test: fix select_introspection.slt](https://github.com/MaterializeInc/materialize/pull/16129) (@teskje)
* [ ] [#16148 storage: in (compute) persist_sink, only consolidate updates when needed](https://github.com/MaterializeInc/materialize/pull/16148) (@aljoscha)
* [ ] [#16150 storage: deprovision hosts in `StorageController::process`](https://github.com/MaterializeInc/materialize/pull/16150) (@teskje)
* [ ] [#16151 Clean up in replica-targeted-select.td](https://github.com/MaterializeInc/materialize/pull/16151) (@teskje)
* [ ] [#16139 doc: update SUBSCRIBE example](https://github.com/MaterializeInc/materialize/pull/16139) (@bobbyiliev)
* [ ] [#14046 persist: track per-writer compare_and_append idempotency token](https://github.com/MaterializeInc/materialize/pull/14046) (@danhhz)
* [ ] [#16138 apachify some code](https://github.com/MaterializeInc/materialize/pull/16138) (@umanwizard)
* [ ] [#16162 doc/user: remove duplicated clause from load gen source syntax diagram](https://github.com/MaterializeInc/materialize/pull/16162) (@benesch)
* [ ] [#14845 build(deps): bump k8s-openapi from 0.15.0 to 0.16.0](https://github.com/MaterializeInc/materialize/pull/14845) (@dependabot[bot])
* [ ] [#16042 build(deps): bump sentry-tracing from 0.27.0 to 0.28.0](https://github.com/MaterializeInc/materialize/pull/16042) (@dependabot[bot])
* [ ] [#16165 build(deps): bump predicates from 2.1.1 to 2.1.3](https://github.com/MaterializeInc/materialize/pull/16165) (@dependabot[bot])
* [ ] [#16163 build(deps): bump num_cpus from 1.13.1 to 1.14.0](https://github.com/MaterializeInc/materialize/pull/16163) (@dependabot[bot])
* [ ] [#16167 build(deps): bump uuid from 1.2.1 to 1.2.2](https://github.com/MaterializeInc/materialize/pull/16167) (@dependabot[bot])
* [ ] [#16169 Prepare mz-ore for publication](https://github.com/MaterializeInc/materialize/pull/16169) (@umanwizard)
* [ ] [#15296 build(deps): bump tokio from 1.20.2 to 1.22.0](https://github.com/MaterializeInc/materialize/pull/15296) (@dependabot[bot])
* [ ] [#16166 deps: weekly python dependency bump](https://github.com/MaterializeInc/materialize/pull/16166) (@benesch)
* [ ] [#15445 build(deps): bump types-pymysql from 1.0.19 to 1.0.19.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15445) (@dependabot[bot])
* [ ] [#16175 build(deps): bump rpassword from 7.0.0 to 7.1.0](https://github.com/MaterializeInc/materialize/pull/16175) (@dependabot[bot])
* [ ] [#16173 build(deps): bump syn from 1.0.102 to 1.0.103](https://github.com/MaterializeInc/materialize/pull/16173) (@dependabot[bot])
* [ ] [#16171 build(deps): bump libc from 0.2.135 to 0.2.137](https://github.com/MaterializeInc/materialize/pull/16171) (@dependabot[bot])
* [ ] [#16170 build(deps): bump prost-build from 0.11.1 to 0.11.2](https://github.com/MaterializeInc/materialize/pull/16170) (@dependabot[bot])
* [ ] [#15788 build(deps): bump kubernetes from 22.6.0 to 25.3.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15788) (@dependabot[bot])
* [ ] [#15620 build(deps): bump pandas from 1.5.0 to 1.5.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15620) (@dependabot[bot])
* [ ] [#16039 build(deps): bump psutil from 5.9.2 to 5.9.4 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16039) (@dependabot[bot])
* [ ] [#16181 build(deps): bump typemap_rev from 0.1.5 to 0.3.0](https://github.com/MaterializeInc/materialize/pull/16181) (@dependabot[bot])
* [ ] [#15787 build(deps): bump types-prettytable from 3.4.2 to 3.4.2.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/15787) (@dependabot[bot])
* [ ] [#16176 build(deps): bump regex from 1.6.0 to 1.7.0](https://github.com/MaterializeInc/materialize/pull/16176) (@dependabot[bot])
* [ ] [#16178 build(deps): bump digest from 0.10.5 to 0.10.6](https://github.com/MaterializeInc/materialize/pull/16178) (@dependabot[bot])
* [ ] [#16184 build(deps): bump cc from 1.0.73 to 1.0.76](https://github.com/MaterializeInc/materialize/pull/16184) (@dependabot[bot])
* [ ] [#16183 build(deps): bump sysinfo from 0.26.4 to 0.26.7](https://github.com/MaterializeInc/materialize/pull/16183) (@dependabot[bot])
* [ ] [#16182 build(deps): bump snap from 1.0.5 to 1.1.0](https://github.com/MaterializeInc/materialize/pull/16182) (@dependabot[bot])
* [ ] [#16179 build(deps): bump setuptools from 65.5.0 to 65.6.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16179) (@dependabot[bot])
* [ ] [#16192 deps: bump Rust dependencies](https://github.com/MaterializeInc/materialize/pull/16192) (@benesch)
* [ ] [#16193 testdrive: Adjust fix-replica-targeted-select.td for cloudtest](https://github.com/MaterializeInc/materialize/pull/16193) (@philip-stoev)
* [ ] [#16147 Fix double localizing in `consequence_for_input`](https://github.com/MaterializeInc/materialize/pull/16147) (@ggevay)
* [ ] [#16144 Adapter: add notice when user drops active database or cluster](https://github.com/MaterializeInc/materialize/pull/16144) (@chaas)
* [ ] [#16196 deps: bump to open v3.2.0](https://github.com/MaterializeInc/materialize/pull/16196) (@benesch)
* [ ] [#16154 persist: fix maelstrom flake](https://github.com/MaterializeInc/materialize/pull/16154) (@danhhz)
* [ ] [#16156 [source] Percolate up a few more Kafka errors](https://github.com/MaterializeInc/materialize/pull/16156) (@bkirwi)
* [ ] [#16202 doc: add latency talk to required reading](https://github.com/MaterializeInc/materialize/pull/16202) (@mjibson)
* [ ] [#16096 coord: Protect timestamp from crash loop](https://github.com/MaterializeInc/materialize/pull/16096) (@jkosh44)
* [ ] [#16160 coord: Initialize new tables uppers](https://github.com/MaterializeInc/materialize/pull/16160) (@jkosh44)
* [ ] [#15567 storage: timely native timestamp reclock implementation ](https://github.com/MaterializeInc/materialize/pull/15567) (@petrosagg)
* [ ] [#16102 storage: statically enforce definite errors](https://github.com/MaterializeInc/materialize/pull/16102) (@petrosagg)
* [ ] [#16006 Zippy parameterized actions](https://github.com/MaterializeInc/materialize/pull/16006) (@philip-stoev)
* [ ] [#16215 test: ignore flaky test](https://github.com/MaterializeInc/materialize/pull/16215) (@jkosh44)
* [ ] [#16220 github: update Slack bug notification workflow](https://github.com/MaterializeInc/materialize/pull/16220) (@uce)
* [ ] [#16221 github: drop C-triage from bug issue template](https://github.com/MaterializeInc/materialize/pull/16221) (@uce)
* [ ] [#16207 Sql: add hint on MzTimestampOutOfRange error around required format](https://github.com/MaterializeInc/materialize/pull/16207) (@chaas)
* [ ] [#16203 adapter: restore and improve replica not ready notices](https://github.com/MaterializeInc/materialize/pull/16203) (@mjibson)
* [ ] [#16227 adapter: improve various metrics](https://github.com/MaterializeInc/materialize/pull/16227) (@mjibson)
* [ ] [#16231 doc: correct and improve http api typescript](https://github.com/MaterializeInc/materialize/pull/16231) (@mjibson)
* [ ] [#16230 test: Clean up envd integration tests](https://github.com/MaterializeInc/materialize/pull/16230) (@jkosh44)
* [ ] [#16216 test: Fix flaky startup test](https://github.com/MaterializeInc/materialize/pull/16216) (@jkosh44)
* [ ] [#16158 storage: support BROKER USING SSH TUNNEL](https://github.com/MaterializeInc/materialize/pull/16158) (@guswynn)
* [ ] [#16209 Add mz_cluster_replica_metrics table](https://github.com/MaterializeInc/materialize/pull/16209) (@umanwizard)
* [ ] [#16212 Reduce ON expression in JOIN lowering](https://github.com/MaterializeInc/materialize/pull/16212) (@frankmcsherry)
* [ ] [#16245 Don't spam the console with errors on local builds due to querying metrics from the process orchestrator](https://github.com/MaterializeInc/materialize/pull/16245) (@umanwizard)
* [ ] [#16213 Downgrade k8s service watch errors to warnings](https://github.com/MaterializeInc/materialize/pull/16213) (@teskje)
* [ ] [#16242 Remove dead constant](https://github.com/MaterializeInc/materialize/pull/16242) (@umanwizard)
* [ ] [#16229 persist: routinely reconnect to postgres/crdb to rebalance load](https://github.com/MaterializeInc/materialize/pull/16229) (@pH14)
* [ ] [#16248 test: Panic in test instead of returning an error](https://github.com/MaterializeInc/materialize/pull/16248) (@jkosh44)
* [ ] [#16223 doc/user: document kafka-over-ssh](https://github.com/MaterializeInc/materialize/pull/16223) (@guswynn)
* [ ] [#16243 dbt-materialize: remove PostgreSQL 63-character limitation on relation names](https://github.com/MaterializeInc/materialize/pull/16243) (@morsapaes)
* [ ] [#16258 Heeringa add epic template](https://github.com/MaterializeInc/materialize/pull/16258) (@heeringa)
* [ ] [#16254 Revert "Add examples + adapt SSH tunnel connections guide"](https://github.com/MaterializeInc/materialize/pull/16254) (@guswynn)
* [ ] [#16253 Enable test_coord_startup_blocking](https://github.com/MaterializeInc/materialize/pull/16253) (@jkosh44)
* [ ] [#16251 test: Make test_no_block easier to debug](https://github.com/MaterializeInc/materialize/pull/16251) (@jkosh44)
* [ ] [#16261 adapter: instrument all coord message functions](https://github.com/MaterializeInc/materialize/pull/16261) (@mjibson)
* [ ] [#16234 doc/user: polish v0.32.x release notes](https://github.com/MaterializeInc/materialize/pull/16234) (@morsapaes)
* [ ] [#16233 adapter: split peek into mutable and immutable parts](https://github.com/MaterializeInc/materialize/pull/16233) (@mjibson)
* [ ] [#16262 testdrive: Fortify cvs-sources.td against #16048 (Part #3)](https://github.com/MaterializeInc/materialize/pull/16262) (@philip-stoev)
* [ ] [#16267 ci: Run the Release Qualification Test with the right queue](https://github.com/MaterializeInc/materialize/pull/16267) (@philip-stoev)
* [ ] [#16281 sql-parser: permit EXPLAIN WITH ...](https://github.com/MaterializeInc/materialize/pull/16281) (@tokenrove)
* [ ] [#16263 ore: allow catching panics after set_abort_on_panic](https://github.com/MaterializeInc/materialize/pull/16263) (@benesch)
* [ ] [#16280 storage-client: fix CSR PrivateLink tunneling](https://github.com/MaterializeInc/materialize/pull/16280) (@benesch)
* [ ] [#16270 cloudtest: Improve the debuggability of cloudtest](https://github.com/MaterializeInc/materialize/pull/16270) (@philip-stoev)
* [ ] [#16272 don't prevent the default link behaviour when the SVG is clicked.](https://github.com/MaterializeInc/materialize/pull/16272) (@nisarhassan12)
* [ ] [#16286 zippy: Increase the timeout of the KafkaSourcesLarge test to 48h](https://github.com/MaterializeInc/materialize/pull/16286) (@philip-stoev)
* [ ] [#16287 feature-benchmark: Re-enable for the Platform era](https://github.com/MaterializeInc/materialize/pull/16287) (@philip-stoev)
* [ ] [#16277 Improve MIR builder patterns](https://github.com/MaterializeInc/materialize/pull/16277) (@frankmcsherry)
* [ ] [#16278 Developer documentation: Fix tokio-console documentation](https://github.com/MaterializeInc/materialize/pull/16278) (@lluki)
* [ ] [#16302 build(deps): bump dogsdogsdogs from `78e7319` to `93da913`](https://github.com/MaterializeInc/materialize/pull/16302) (@dependabot[bot])
* [ ] [#16299 build(deps): bump cryptography from 38.0.3 to 38.0.4 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16299) (@dependabot[bot])
* [ ] [#16298 build(deps): bump boto3 from 1.26.13 to 1.26.16 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16298) (@dependabot[bot])
* [ ] [#16300 build(deps): bump flake8 from 5.0.4 to 6.0.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16300) (@dependabot[bot])
* [ ] [#16303 build(deps): bump setuptools from 65.6.0 to 65.6.3 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16303) (@dependabot[bot])
* [ ] [#16311 feature-benchmark: Increase the retry attempts to 5](https://github.com/MaterializeInc/materialize/pull/16311) (@philip-stoev)
* [ ] [#16301 build(deps): bump postgres-openssl from `abff35e` to `3379576`](https://github.com/MaterializeInc/materialize/pull/16301) (@dependabot[bot])
* [ ] [#16310 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.26.13 to 1.26.17 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16310) (@dependabot[bot])
* [ ] [#16295 Add a regression test for #16128](https://github.com/MaterializeInc/materialize/pull/16295) (@ggevay)
* [ ] [#16328 platform checks: Restart Debezium and Redpanda together](https://github.com/MaterializeInc/materialize/pull/16328) (@philip-stoev)
* [ ] [#16282 Simple fix. Remove and rephrase](https://github.com/MaterializeInc/materialize/pull/16282) (@joacoc)
* [ ] [#16292 Remove GROUP BY from `optimization.md`](https://github.com/MaterializeInc/materialize/pull/16292) (@ggevay)
* [ ] [#16290 Add a comment explaining why we poll to in a loop to get process metrics](https://github.com/MaterializeInc/materialize/pull/16290) (@umanwizard)
* [ ] [#16330 Rename some metrics columns](https://github.com/MaterializeInc/materialize/pull/16330) (@umanwizard)
* [ ] [#16320 build(deps): bump rpassword from 7.1.0 to 7.2.0](https://github.com/MaterializeInc/materialize/pull/16320) (@dependabot[bot])
* [ ] [#16201 persist: write debugging info into state](https://github.com/MaterializeInc/materialize/pull/16201) (@danhhz)
* [ ] [#16157 Semijoin Idempotence](https://github.com/MaterializeInc/materialize/pull/16157) (@frankmcsherry)
* [ ] [#16334 adapter: Properly load indexes on system objects](https://github.com/MaterializeInc/materialize/pull/16334) (@jkosh44)
* [ ] [#16341 storage: correctly calculate the times to reclock to](https://github.com/MaterializeInc/materialize/pull/16341) (@petrosagg)
* [ ] [#16338 test: Disable flaky pgwire test](https://github.com/MaterializeInc/materialize/pull/16338) (@jkosh44)
* [ ] [#16339 stash: in-memory impl; remove rusqlite](https://github.com/MaterializeInc/materialize/pull/16339) (@mjibson)
* [ ] [#16342 test: Fix mz-ore test flake](https://github.com/MaterializeInc/materialize/pull/16342) (@jkosh44)
* [ ] [#16285 dbt-materialize: override postgres__listagg()](https://github.com/MaterializeInc/materialize/pull/16285) (@morsapaes)
* [ ] [#16314 build(deps): bump aho-corasick from 0.7.19 to 0.7.20](https://github.com/MaterializeInc/materialize/pull/16314) (@dependabot[bot])
* [ ] [#16268 test: Test source/sink status reporting](https://github.com/MaterializeInc/materialize/pull/16268) (@philip-stoev)
* [ ] [#16350 adapter: don't panic in EXPLAIN if the expected stage is mising](https://github.com/MaterializeInc/materialize/pull/16350) (@aalexandrov)
* [ ] [#16352 doc/user: fix style inside lists](https://github.com/MaterializeInc/materialize/pull/16352) (@joacoc)
* [ ] [#16279 doc: Add AWS MSK PrivateLink guide](https://github.com/MaterializeInc/materialize/pull/16279) (@bobbyiliev)
* [ ] [#16293 Don't pick `arbitrary_arrangement` in IndexedFilter lowering.](https://github.com/MaterializeInc/materialize/pull/16293) (@ggevay)
* [ ] [#16226 [sources] Report indefinite errors from the postgres source](https://github.com/MaterializeInc/materialize/pull/16226) (@bkirwi)
* [ ] [#16143 persist: read a bounded # of rows from CRDB when fetching latest state](https://github.com/MaterializeInc/materialize/pull/16143) (@pH14)
* [ ] [#16260 CREATE CONNECTION: add uppercase validation for kafka SASL MECHANISM](https://github.com/MaterializeInc/materialize/pull/16260) (@chaas)
* [ ] [#16235 adapter: improve cluster status change notices](https://github.com/MaterializeInc/materialize/pull/16235) (@benesch)
* [ ] [#16333 [sources] Use metadata poll to detect consumer errors in the Kafka source](https://github.com/MaterializeInc/materialize/pull/16333) (@bkirwi)
* [ ] [#16336 [sources] Remove sources from unsafe mode](https://github.com/MaterializeInc/materialize/pull/16336) (@bkirwi)
* [ ] [`859332c10` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/859332c10b1d5efce84db2be42ff18d7ee719cc2) (@materializer)
* [ ] [`3df034a0d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3df034a0d4440e7a8bd0d176f63094b185313d4f) (@materializer)
* [ ] [`97e8105d8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/97e8105d865a26e888e2ef4fdbead3bf69802052) (@materializer)
* [ ] [`7aa2cfab2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7aa2cfab21b22e575a39234b84775eac77ddb075) (@materializer)
* [ ] [`30bd48701` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/30bd48701d92002ffa88b2df5971fa384c2daa1d) (@materializer)
* [ ] [`fc6b99bd4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fc6b99bd4f950804d9d21729d8f6d38bc3318701) (@materializer)
* [ ] [`94d58a158` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/94d58a158329f3d6f01975ed388b09ba6b01bcb0) (@materializer)
* [ ] [`24ead302a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/24ead302a98be7668cd1ee993ea78db580d9631a) (@materializer)
* [ ] [`cf5b24d1d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cf5b24d1d4e96ea139ca8c7982640621e5d6951f) (@materializer)
* [ ] [`7f1b71041` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7f1b71041c4eb3868fce022332b960055584036c) (@materializer)
* [ ] [`1766ab397` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1766ab3978bc90abf75eb9b1fbadfcc95eca1993) (@materializer)
* [ ] [`b7b1ca8df` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b7b1ca8df98f4e941226bd2bef5fdab6ee300c48) (@materializer)
* [ ] [`354efaf84` release: bump to version v0.33.0](https://github.com/MaterializeInc/materialize/commit/354efaf8489430a3493dc4bf8a25999e6d666e91) (@jkosh44)

**Comment by benesch** [comment]
The commits and PRs that are not mine LGTM.

**Comment by jkosh44** [comment]
@benesch unreviewed PRs LGTM.
