### ISSUE TITLE
release: v0.33.1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16391]
No PRs in [`v0.33.1`](https://github.com/MaterializeInc/materialize/tree/v0.33.1) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`3fb13c999` Merge pull request #16380 from petrosagg/trace-bug](https://github.com/MaterializeInc/materialize/commit/3fb13c9999901145eb0a4b48d7c0f87546e0f6b9) (@jkosh44)
* [x] [`5bc69ea1e` Revert "persist: read a bounded # of rows from CRDB when fetching latest state (#16143)" (#16386)](https://github.com/MaterializeInc/materialize/commit/5bc69ea1ee2daa59be1629d51d7a7a571d66004a) (@jkosh44)
* [x] [`9f78b0b94` release: bump to version v0.33.1](https://github.com/MaterializeInc/materialize/commit/9f78b0b94d464b116773caa3a06aeb8220ff21b0) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`3fb13c999` Merge pull request #16380 from petrosagg/trace-bug](https://github.com/MaterializeInc/materialize/commit/3fb13c9999901145eb0a4b48d7c0f87546e0f6b9) (@jkosh44)
* [ ] [`5bc69ea1e` Revert "persist: read a bounded # of rows from CRDB when fetching latest state (#16143)" (#16386)](https://github.com/MaterializeInc/materialize/commit/5bc69ea1ee2daa59be1629d51d7a7a571d66004a) (@jkosh44)
* [ ] [`9f78b0b94` release: bump to version v0.33.1](https://github.com/MaterializeInc/materialize/commit/9f78b0b94d464b116773caa3a06aeb8220ff21b0) (@jkosh44)
