### ISSUE TITLE
release: v0.34.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16496]
The following PRs in [`v0.34.0`](https://github.com/MaterializeInc/materialize/tree/v0.34.0) require review:
* [x] [#16257 redo: doc/user: document kafka-over-ssh](https://github.com/MaterializeInc/materialize/pull/16257) (@guswynn)
* [x] [#16384 doc/user: polish v0.33 release notes](https://github.com/MaterializeInc/materialize/pull/16384) (@morsapaes)
* [x] [#16388 ci,zippy: Use a larger machine for the KafkaParallelInsert scenario](https://github.com/MaterializeInc/materialize/pull/16388) (@philip-stoev)
* [x] [#16382 feature-benchmark: Use a unique environment_id on retries](https://github.com/MaterializeInc/materialize/pull/16382) (@philip-stoev)
* [x] [#16410 ci,test: A test for the mz_storage_usage table](https://github.com/MaterializeInc/materialize/pull/16410) (@philip-stoev)
* [x] [#16413 test: Fix flaky storage-usage test](https://github.com/MaterializeInc/materialize/pull/16413) (@philip-stoev)
* [x] [#16434 platform checks: Make validate() of the CreateTables check idempotent](https://github.com/MaterializeInc/materialize/pull/16434) (@philip-stoev)
* [x] [#16438 environmentd: set telemetry report interval to one hour](https://github.com/MaterializeInc/materialize/pull/16438) (@benesch)
* [x] [#16439 mz: add support for custom endpoints and versions](https://github.com/MaterializeInc/materialize/pull/16439) (@benesch)
* [x] [#16443 ore: fix performance regression in tracing](https://github.com/MaterializeInc/materialize/pull/16443) (@benesch)
* [x] [#16436 zippy,ci: Add a Release Qualification Test around dataflows](https://github.com/MaterializeInc/materialize/pull/16436) (@philip-stoev)
* [x] [#16465 platform checks: Fortify the CheckDatabases scenario](https://github.com/MaterializeInc/materialize/pull/16465) (@philip-stoev)
* [x] [#16347 environmentd: Have environmentd panic on child crashes during testing](https://github.com/MaterializeInc/materialize/pull/16347) (@philip-stoev)
* [x] [#16024 platform checks: Add a Check that uses mz_now() with pg-cdc](https://github.com/MaterializeInc/materialize/pull/16024) (@philip-stoev)
* [x] [#16479 zippy: Silence docker-compose run command lines](https://github.com/MaterializeInc/materialize/pull/16479) (@philip-stoev)
* [x] [#16490 switch from a tag because main category items are not links.](https://github.com/MaterializeInc/materialize/pull/16490) (@nisarhassan12)
* [x] [#16492 theme switcher fixes & updates.](https://github.com/MaterializeInc/materialize/pull/16492) (@nisarhassan12)
* [x] [#16495 environmentd: add other DML statements to environment rollup](https://github.com/MaterializeInc/materialize/pull/16495) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`caeccd046` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/caeccd046a29ca5caad93e0ec5e08801d9d9ffa1) (@materializer)
* [ ] [`34211fd37` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/34211fd3791da3524fe9e95374ba015a27464f51) (@materializer)
* [ ] [`9f759bdab` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9f759bdab552472c25f97b1e5357847df90f21d3) (@materializer)
* [ ] [`84035fe8d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/84035fe8d811ba942423aca240c0ae62f475d92a) (@materializer)
* [ ] [`bd3a5cb36` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bd3a5cb36626df7cbca5c74aecaae7c0ba97f53c) (@materializer)
* [ ] [`f11b0122b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f11b0122bc3d62d3600f8eaadf1d2e89f9cf3f0f) (@materializer)
* [ ] [`a936bf7a7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a936bf7a7a1c59a8d91385442745bb7a55fe7702) (@materializer)
* [ ] [`bd926d3c8` release: bump to version v0.34.0](https://github.com/MaterializeInc/materialize/commit/bd926d3c81196e80d3045ca15fd4142d3f19afb2) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#16200 Remove orphaned orchestrator nodes on environmentd startup](https://github.com/MaterializeInc/materialize/pull/16200) (@lluki)
* [ ] [#16291 Fuse `InlineLet` and `UpdateLet` into `RelationCSE`](https://github.com/MaterializeInc/materialize/pull/16291) (@ggevay)
* [ ] [#16360 test: Increase timeouts in flaky test](https://github.com/MaterializeInc/materialize/pull/16360) (@jkosh44)
* [ ] [#16349 doc: Add psql installation guide](https://github.com/MaterializeInc/materialize/pull/16349) (@bobbyiliev)
* [ ] [#16297 Add Differential join's start_keys to EXPLAIN](https://github.com/MaterializeInc/materialize/pull/16297) (@ggevay)
* [ ] [#16137 doc: Add Serializable query guarantees to docs](https://github.com/MaterializeInc/materialize/pull/16137) (@jkosh44)
* [ ] [#16364 release: bump to version v0.34.0-dev](https://github.com/MaterializeInc/materialize/pull/16364) (@jkosh44)
* [ ] [#16317 build(deps): bump openssl-sys from 0.9.77 to 0.9.78](https://github.com/MaterializeInc/materialize/pull/16317) (@dependabot[bot])
* [ ] [#16380 storage: report native frontier when tracing](https://github.com/MaterializeInc/materialize/pull/16380) (@petrosagg)
* [ ] [#16244 compute: error on peeks before the compaction frontier](https://github.com/MaterializeInc/materialize/pull/16244) (@teskje)
* [ ] [#16386 Revert "persist: read a bounded # of rows from CRDB when fetching latest state"](https://github.com/MaterializeInc/materialize/pull/16386) (@pH14)
* [ ] [#16389 [sources] Expect to see the running state in the status history table](https://github.com/MaterializeInc/materialize/pull/16389) (@bkirwi)
* [ ] [#16395 adapter: add `launchdarkly-server-sdk` dependency](https://github.com/MaterializeInc/materialize/pull/16395) (@aalexandrov)
* [ ] [#16256 Add a commandline flag --stderr-log-format for optional json logging](https://github.com/MaterializeInc/materialize/pull/16256) (@antifuchs)
* [ ] [#16401 don't provide default features for mz_ore](https://github.com/MaterializeInc/materialize/pull/16401) (@doy-materialize)
* [ ] [#16257 redo: doc/user: document kafka-over-ssh](https://github.com/MaterializeInc/materialize/pull/16257) (@guswynn)
* [ ] [#16384 doc/user: polish v0.33 release notes](https://github.com/MaterializeInc/materialize/pull/16384) (@morsapaes)
* [ ] [#16388 ci,zippy: Use a larger machine for the KafkaParallelInsert scenario](https://github.com/MaterializeInc/materialize/pull/16388) (@philip-stoev)
* [ ] [#16382 feature-benchmark: Use a unique environment_id on retries](https://github.com/MaterializeInc/materialize/pull/16382) (@philip-stoev)
* [ ] [#16408 ore: fix typo of tracing feature](https://github.com/MaterializeInc/materialize/pull/16408) (@petrosagg)
* [ ] [#16410 ci,test: A test for the mz_storage_usage table](https://github.com/MaterializeInc/materialize/pull/16410) (@philip-stoev)
* [ ] [#16412 timely-util: automatically drain dropped handles](https://github.com/MaterializeInc/materialize/pull/16412) (@petrosagg)
* [ ] [#16413 test: Fix flaky storage-usage test](https://github.com/MaterializeInc/materialize/pull/16413) (@philip-stoev)
* [ ] [#16414 timely-util: shutdown button for all async operators](https://github.com/MaterializeInc/materialize/pull/16414) (@petrosagg)
* [ ] [#16390 persist: in persist_source, do very fine-grained output activation](https://github.com/MaterializeInc/materialize/pull/16390) (@aljoscha)
* [ ] [#16416 storage: in controller, simplify internal collection-management API](https://github.com/MaterializeInc/materialize/pull/16416) (@aljoscha)
* [ ] [#16353 Fix compute persist_sink shutdown](https://github.com/MaterializeInc/materialize/pull/16353) (@teskje)
* [ ] [#16417 Remove `id_gen` field from `TransformArgs`](https://github.com/MaterializeInc/materialize/pull/16417) (@frankmcsherry)
* [ ] [#16228 persist: admin tool to manually compact a shard](https://github.com/MaterializeInc/materialize/pull/16228) (@danhhz)
* [ ] [#16351 Skip ArrangeBys in constant folding](https://github.com/MaterializeInc/materialize/pull/16351) (@ggevay)
* [ ] [#16400 [sources] Uncomment source error tests](https://github.com/MaterializeInc/materialize/pull/16400) (@bkirwi)
* [ ] [#16418 storage: remove custom operator tokens and legacy async integration](https://github.com/MaterializeInc/materialize/pull/16418) (@petrosagg)
* [ ] [#16402 adapter: Fix builtin schema migrations](https://github.com/MaterializeInc/materialize/pull/16402) (@jkosh44)
* [ ] [#16403 persist_source: backpressure on inflight bytes](https://github.com/MaterializeInc/materialize/pull/16403) (@pH14)
* [ ] [#16407 upgrade: Increase coverage in upgrade tests](https://github.com/MaterializeInc/materialize/pull/16407) (@philip-stoev)
* [ ] [#16428 adapter: Decrease bootstrap memory requirements](https://github.com/MaterializeInc/materialize/pull/16428) (@jkosh44)
* [ ] [#16374 [sinks] Limit the number of retries on retriable transaction errors](https://github.com/MaterializeInc/materialize/pull/16374) (@bkirwi)
* [ ] [#16411 [doc/user]: small fixes and updates.](https://github.com/MaterializeInc/materialize/pull/16411) (@nisarhassan12)
* [ ] [#16423 compute,storage: install timely_util panic hook after sentry hook](https://github.com/MaterializeInc/materialize/pull/16423) (@danhhz)
* [ ] [#16406 environmentd: periodically report environment summaries to Segment](https://github.com/MaterializeInc/materialize/pull/16406) (@benesch)
* [ ] [#16434 platform checks: Make validate() of the CreateTables check idempotent](https://github.com/MaterializeInc/materialize/pull/16434) (@philip-stoev)
* [ ] [#16429 adapter: Fix storage collection usage timestamps](https://github.com/MaterializeInc/materialize/pull/16429) (@jkosh44)
* [ ] [#16438 environmentd: set telemetry report interval to one hour](https://github.com/MaterializeInc/materialize/pull/16438) (@benesch)
* [ ] [#16439 mz: add support for custom endpoints and versions](https://github.com/MaterializeInc/materialize/pull/16439) (@benesch)
* [ ] [#16409 doc/user: document source status system catalog objects](https://github.com/MaterializeInc/materialize/pull/16409) (@morsapaes)
* [ ] [#16437 Refactor show command logic in parser ](https://github.com/MaterializeInc/materialize/pull/16437) (@CNLHC)
* [ ] [#16443 ore: fix performance regression in tracing](https://github.com/MaterializeInc/materialize/pull/16443) (@benesch)
* [ ] [#15810 orchestrator-process: store PID metadata in temp directory](https://github.com/MaterializeInc/materialize/pull/15810) (@benesch)
* [ ] [#16459 build(deps): bump async-trait from 0.1.58 to 0.1.59](https://github.com/MaterializeInc/materialize/pull/16459) (@dependabot[bot])
* [ ] [#16462 build(deps): bump jsonwebtoken from 8.1.1 to 8.2.0](https://github.com/MaterializeInc/materialize/pull/16462) (@dependabot[bot])
* [ ] [#16460 build(deps): bump openssl from 0.10.42 to 0.10.43](https://github.com/MaterializeInc/materialize/pull/16460) (@dependabot[bot])
* [ ] [#16316 build(deps): bump serde_json from 1.0.88 to 1.0.89](https://github.com/MaterializeInc/materialize/pull/16316) (@dependabot[bot])
* [ ] [#16313 build(deps): bump sysinfo from 0.26.7 to 0.26.8](https://github.com/MaterializeInc/materialize/pull/16313) (@dependabot[bot])
* [ ] [#16461 build(deps): bump chrono-tz from 0.8.0 to 0.8.1](https://github.com/MaterializeInc/materialize/pull/16461) (@dependabot[bot])
* [ ] [#16453 build(deps): bump pandas from 1.5.1 to 1.5.2 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16453) (@dependabot[bot])
* [ ] [#16457 build(deps): bump boto3 from 1.26.16 to 1.26.22 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16457) (@dependabot[bot])
* [ ] [#16456 build(deps): bump types-prettytable from 3.4.2.1 to 3.4.2.2 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16456) (@dependabot[bot])
* [ ] [#16454 build(deps): bump types-setuptools from 65.6.0.0 to 65.6.0.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16454) (@dependabot[bot])
* [ ] [#16452 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.26.17 to 1.26.22 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16452) (@dependabot[bot])
* [ ] [#16455 build(deps): bump twine from 4.0.1 to 4.0.2 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16455) (@dependabot[bot])
* [ ] [#16433 interchange: don't crash on invalid Avro field/record names](https://github.com/MaterializeInc/materialize/pull/16433) (@benesch)
* [ ] [#16436 zippy,ci: Add a Release Qualification Test around dataflows](https://github.com/MaterializeInc/materialize/pull/16436) (@philip-stoev)
* [ ] [#16465 platform checks: Fortify the CheckDatabases scenario](https://github.com/MaterializeInc/materialize/pull/16465) (@philip-stoev)
* [ ] [#16466 legacy upgrade: isolate each individual upgrade attempt](https://github.com/MaterializeInc/materialize/pull/16466) (@philip-stoev)
* [ ] [#16335 create `jobs` image for running one-offs against deployed environments](https://github.com/MaterializeInc/materialize/pull/16335) (@pH14)
* [ ] [#16250 docs: Add style guide for cargo tests](https://github.com/MaterializeInc/materialize/pull/16250) (@jkosh44)
* [ ] [#16468 remove required for discretionary issues](https://github.com/MaterializeInc/materialize/pull/16468) (@heeringa)
* [ ] [#13035 ci: pull cargo test out of the build CI job](https://github.com/MaterializeInc/materialize/pull/13035) (@benesch)
* [ ] [#16440 Stop pushing dummy demand at sources](https://github.com/MaterializeInc/materialize/pull/16440) (@frankmcsherry)
* [ ] [#16347 environmentd: Have environmentd panic on child crashes during testing](https://github.com/MaterializeInc/materialize/pull/16347) (@philip-stoev)
* [ ] [#16471 orchestrator-process: remove unused tempfile dev dependency](https://github.com/MaterializeInc/materialize/pull/16471) (@benesch)
* [ ] [#16284 adapter: print COUNT(*) when EXPLAIN'ing COUNT(*)](https://github.com/MaterializeInc/materialize/pull/16284) (@tokenrove)
* [ ] [#16024 platform checks: Add a Check that uses mz_now() with pg-cdc](https://github.com/MaterializeInc/materialize/pull/16024) (@philip-stoev)
* [ ] [#16431 [sinks] Capture errors in the sink via the Kafka context](https://github.com/MaterializeInc/materialize/pull/16431) (@bkirwi)
* [ ] [#16405 Add system table that contains the aws privatelink connection principals](https://github.com/MaterializeInc/materialize/pull/16405) (@chaas)
* [ ] [#16479 zippy: Silence docker-compose run command lines](https://github.com/MaterializeInc/materialize/pull/16479) (@philip-stoev)
* [ ] [#16470 adapter: Fix timedomain errors](https://github.com/MaterializeInc/materialize/pull/16470) (@jkosh44)
* [ ] [#16296 repr: add `Datum::Range` + misc.](https://github.com/MaterializeInc/materialize/pull/16296) (@sploiselle)
* [ ] [#16486 repr: fix merge skew prohibiting std::panic::catch_unwind](https://github.com/MaterializeInc/materialize/pull/16486) (@sploiselle)
* [ ] [#16489 stash: verify and seal in known order](https://github.com/MaterializeInc/materialize/pull/16489) (@mjibson)
* [ ] [#16387 Normalize representation of Lets in expressions](https://github.com/MaterializeInc/materialize/pull/16387) (@frankmcsherry)
* [ ] [#16393 storage: log information about pg wal peeks and keepalives](https://github.com/MaterializeInc/materialize/pull/16393) (@guswynn)
* [ ] [#16490 switch from a tag because main category items are not links.](https://github.com/MaterializeInc/materialize/pull/16490) (@nisarhassan12)
* [ ] [#16492 theme switcher fixes & updates.](https://github.com/MaterializeInc/materialize/pull/16492) (@nisarhassan12)
* [ ] [#16493 storage: downgrade offset commit error log and add metrics](https://github.com/MaterializeInc/materialize/pull/16493) (@guswynn)
* [ ] [#16463 [sinks] Move sink status writes out of unsafe mode](https://github.com/MaterializeInc/materialize/pull/16463) (@bkirwi)
* [ ] [#16495 environmentd: add other DML statements to environment rollup](https://github.com/MaterializeInc/materialize/pull/16495) (@benesch)
* [ ] [`caeccd046` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/caeccd046a29ca5caad93e0ec5e08801d9d9ffa1) (@materializer)
* [ ] [`34211fd37` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/34211fd3791da3524fe9e95374ba015a27464f51) (@materializer)
* [ ] [`9f759bdab` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9f759bdab552472c25f97b1e5357847df90f21d3) (@materializer)
* [ ] [`84035fe8d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/84035fe8d811ba942423aca240c0ae62f475d92a) (@materializer)
* [ ] [`bd3a5cb36` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bd3a5cb36626df7cbca5c74aecaae7c0ba97f53c) (@materializer)
* [ ] [`f11b0122b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f11b0122bc3d62d3600f8eaadf1d2e89f9cf3f0f) (@materializer)
* [ ] [`a936bf7a7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a936bf7a7a1c59a8d91385442745bb7a55fe7702) (@materializer)
* [ ] [`bd926d3c8` release: bump to version v0.34.0](https://github.com/MaterializeInc/materialize/commit/bd926d3c81196e80d3045ca15fd4142d3f19afb2) (@guswynn)

**Comment by benesch** [comment]
@guswynn's commits LGTM.
