### ISSUE TITLE
persist: FY24 Q1 checklist

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#16557]
# Update: Q1 is closed! Moved tracking to #19292

- [mfp] => #12684 
- [prod] => production hardening
- [req] => requests from other teams/product for _new_ behavior
- [bug] => incorrect behavior

# Bugs
- [ ] [bug] #15937
- [x] [bug] #16161
- [x] [bug] #16712
- [ ] [bug] #17338
  - [x] #17147
  - [x] #17877
  - Maybe all fixed?
- [x] [bug] #17680
- [ ] #19096

# Triage
- #17776
- #19102

# FY24 Q1
- [x] [req] #17317
- [x] [epic] #17605
- [x] [mfp] Prototyping and demo
- [x] [mfp] #18007
- [x] [mfp] Merge end-to-end skeleton impl
  - Behind feature flags that will only be turned on in throwaway envs
  - [x] #18106
  - [x] #18142
  - [x] #18198
  - [x] #18237
- [x] [mfp] Get to a place where fieldeng/devex can try pushdown in a throwaway env
  - [x] Get a sense fromfieldeng/devex/customers for initial queries we should support filter pushdown on
  - [x] #18386
  - [x] #18487
  - [x] #18573
  - [x] #18597
  - [x] #18646
  - [x] #18749
  - [x] #18771
  - [x] #18478
  - [x] #18932
  - [x] Unmerged version of #18560
- [x] [mfp] Get to a place where we can turn on pushdown feature flags in all staging envs
  - [x] Update #18007
  - [x] #18932
  - [x] #19112
  - [x] First half of #18305
  - [x] #19019
  - [x] #18984
  - [x] #18765
  - [x] #18879
  - [x] Do a pass of addressing TODO(mfp)
  - [x] #19103
- [ ] [mfp] Production ready
  - [ ] Merge #18007
  - [ ] Get QA signoff
  - [ ] Decide on a final SourceData <-> columnar mapping
  - [ ] Decide on a final stats serialization
  - [ ] Address all TODO(mfp)
  - [ ] User visibility into exactly how many parts got filtered/fetched (EXPLAIN?)
  - [ ] Expose stats for testing
- [x] [prod] #18391
  - [x] [prod] Fixes #15680
- [ ] [prod] Reduce CRDB usage
  - [x] #18151
    - [x] Turn this on in prod
  - [ ] Max one polling loop per shard per process to reduce CRDB usage
    - Blocked on #18391
  - [x] #18778
  - [ ] #18981
- [x] #16860
- [x] [req] #17293
- [x] [req] Estimate CRDB and S3 usage for Operations
  - [x] [req] #17552
- [x] [prod] #16403
- [x] [prod] #16553
- [ ] [prod] Limit the blast radius of GC catching up
  - [x] #17086
  - [x] #17350
  - [ ] #17282
  - [ ] [prod] Resurrect #13961
- [ ] https://github.com/MaterializeInc/materialize/issues/18419
- [x] [bug] #13861
- [ ] [prod] #8185
  - [x] #14704
  - #16369
  - Blocked on the storage side of this
  - We might get pulled back into tweaking how this works
- [ ] [prod] Anything else we need to understand how persist is currently going in prod
  - [x] Metric for blobs that are only sticking around because of seqno hold
  - ~Metrics for how close readers/writers are getting to expiry before leases being extended~
  - [x] #16969
  - [x] #16940
  - [x] #17438
  - [ ] Per-shard breakdown of puts+gets
- [x] [prod] Firefighting tools
  - [x] #17192
  - [x] #17294
- [x] [prod] #17717
  - [x] #17299
  - Was too hard to reason about when diagnosing #14719
- [ ] [prod] #16699
- [x] [bug] Calculate part size correctly for user records
  - [x] Consolidate user parts before writing
  - [x] #14579
- [ ] [prod] Turn on CRDB changefeeds -> s3 for all prod environments
  - Extremely useful for debugging/firefighting
  - Also likely a building block for implementing backup/restore
- [ ] [prod] Put timeouts on all s3 and crdb usage (would have caught networking outage)
  - [x] S3 call timeouts
  - [x] CRDB connect timeouts
  - [ ] CRDB tcp user timeouts (requires https://github.com/MaterializeInc/rust-postgres/pull/14)
- [x] [bug] Dig into possibly super-linear ColumnarRecords latencies
  - Just tested this in release and it was linear
  - It was debug #16635
- [ ] [bug] #15985
  - [x] #17526
    - [x] Turn this on in prod
- [ ] [bug] #15470
- [ ] [prod] #12992
- [ ] [prod] #16652
  - [ ] Similarly, mental model of underlying costs for persist users
- [ ] [req] Implement backpressure in persist_source
  - [x] #16403
  - [x] [bug] #16807
  - [x] [bug] #16995
  - [ ] I think this is still blocked on something, TODO check with Jan

# Next (not ordered)

# Open Design Problems
- https://github.com/MaterializeInc/materialize/issues/17777

# Later (not ordered)
- #19225
- [prod] get rid of heatbeat-based leases
  - writers could move to an epoch bases system where epochs are versions of code
  - readers could either use ben's 🤯 idea or frank's "extreme" version
- [req] optimization to "consolidate as we go" in decode_and_mfp
  - instead of decode_one+mfp+repeat, decode and advance timestamps while accumulating the diff as long as you have the same KVT before handing the summed thing to mfp (skipping it entirely if diff=0, an important special case)
- [req] #16783
- #16858
- [epic] #16607
- [epic] Throughput tuning
  - #15518
  - Update open_loop benchmark to stress sharded reads and writes
  - #18066
- [epic] #16625
- Implement https://github.com/MaterializeInc/materialize/pull/18157
- #17492
- [BIG] Indexed lookup (potential first use, UPSERT envelope)
- #13918
- [prod] Add version to inline part metadata
- Add more prompt listening for changes in Consensus
- Extend maelstrom coverage?
- Split mz_persist_client::internal into mz_persist
- Hook client auth for Consensus up in prod
- #17322
- Petros's idea to have a sharded exchangeable description of assigned compaction work
- Aljoscha's idea to balance the compare_and_append work in persist_sink operator 3 instead of a fixed worker
- #15209
- Resurrect #15709
- Proptest coverage of persist protos
  - Ditto for state diffs?
- [req] Structured logging
- #17206

**Comment by danhhz** [comment]
Q1 is closed! Moved tracking to https://github.com/MaterializeInc/materialize/issues/19292
