### ISSUE TITLE
release: v0.35.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16601]
The following PRs in [`v0.35.0`](https://github.com/MaterializeInc/materialize/tree/v0.35.0) require review:
* [ ] [#16500 make the copy button on the codeblocks keyboard accessible.](https://github.com/MaterializeInc/materialize/pull/16500) (@nisarhassan12)
* [ ] [#16505 improve the notes design.](https://github.com/MaterializeInc/materialize/pull/16505) (@nisarhassan12)
* [ ] [#16508 zippy,ci Add a long Zippy pg-cdc test to the Release Qualification pi…](https://github.com/MaterializeInc/materialize/pull/16508) (@philip-stoev)
* [ ] [#16510 platform checks: Fix conflict in the PgCdc* checks](https://github.com/MaterializeInc/materialize/pull/16510) (@philip-stoev)
* [ ] [#16482 doc/user: make sink documentation consistent with sources](https://github.com/MaterializeInc/materialize/pull/16482) (@morsapaes)
* [ ] [#16519 doc/developer: fix formatting in required reading list](https://github.com/MaterializeInc/materialize/pull/16519) (@benesch)
* [ ] [#16538 platform checks: Add a Check for source errors](https://github.com/MaterializeInc/materialize/pull/16538) (@philip-stoev)
* [ ] [#16542 ci: Fortify the storage-usage test](https://github.com/MaterializeInc/materialize/pull/16542) (@philip-stoev)
* [ ] [#16541  pgrepr: support parsing text-encoded arrays #8840 ](https://github.com/MaterializeInc/materialize/pull/16541) (@sploiselle)
* [ ] [#16553 Unrevert "persist: read a bounded # of rows from CRDB when fetching l…](https://github.com/MaterializeInc/materialize/pull/16553) (@danhhz)
* [ ] [#16576 ci/deploy: publish license breakdown via cargo about](https://github.com/MaterializeInc/materialize/pull/16576) (@benesch)
* [ ] [#16585 test: Additional tests for Postgres source errors](https://github.com/MaterializeInc/materialize/pull/16585) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`e48b6b50a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e48b6b50a4e5c066f4bb0a6a66992ff0d2facd1f) (@materializer)
* [ ] [`54ada90bd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/54ada90bdb7e8406e56f62c1ece85f2c3870076e) (@materializer)
* [ ] [`5faf6ed6e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5faf6ed6edfdfaeed4c30935f718ea4983150cd6) (@materializer)
* [ ] [`ea6e4431e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ea6e4431ed8c9989ba7c432206e127fd53681935) (@materializer)
* [ ] [`aeff1ae49` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aeff1ae491c34b5ca7212765e981acc0b56485c9) (@materializer)
* [ ] [`f6a89e1f0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f6a89e1f03e243476e85debda72a2281ac82abcc) (@materializer)
* [ ] [`208801f02` release: bump to version v0.35.0](https://github.com/MaterializeInc/materialize/commit/208801f0245b5f1a4280d69a7bfdf0485e292f64) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#16497 release: bump to version v0.35.0-dev](https://github.com/MaterializeInc/materialize/pull/16497) (@guswynn)
* [ ] [#16500 make the copy button on the codeblocks keyboard accessible.](https://github.com/MaterializeInc/materialize/pull/16500) (@nisarhassan12)
* [ ] [#16505 improve the notes design.](https://github.com/MaterializeInc/materialize/pull/16505) (@nisarhassan12)
* [ ] [#16508 zippy,ci Add a long Zippy pg-cdc test to the Release Qualification pi…](https://github.com/MaterializeInc/materialize/pull/16508) (@philip-stoev)
* [ ] [#16510 platform checks: Fix conflict in the PgCdc* checks](https://github.com/MaterializeInc/materialize/pull/16510) (@philip-stoev)
* [ ] [#16482 doc/user: make sink documentation consistent with sources](https://github.com/MaterializeInc/materialize/pull/16482) (@morsapaes)
* [ ] [#16481 adapter: Fix panic on query cancel](https://github.com/MaterializeInc/materialize/pull/16481) (@jkosh44)
* [ ] [#16518 environmentd: bump auth test expiry even more!](https://github.com/MaterializeInc/materialize/pull/16518) (@mjibson)
* [ ] [#16519 doc/developer: fix formatting in required reading list](https://github.com/MaterializeInc/materialize/pull/16519) (@benesch)
* [ ] [#16516 Add `mz_internal.mz_cluster_replica_sizes`](https://github.com/MaterializeInc/materialize/pull/16516) (@umanwizard)
* [ ] [#16503 Update `BEGIN` doc to clarify isolation levels](https://github.com/MaterializeInc/materialize/pull/16503) (@chuck-alt-delete)
* [ ] [#16522 repr: clean up module structure and dependencies](https://github.com/MaterializeInc/materialize/pull/16522) (@benesch)
* [ ] [#16528 Don't randomly divide memory metrics by 8](https://github.com/MaterializeInc/materialize/pull/16528) (@umanwizard)
* [ ] [#16520 Add API stub for real time recency](https://github.com/MaterializeInc/materialize/pull/16520) (@jkosh44)
* [ ] [#16529 doc: document that SET works over HTTP](https://github.com/MaterializeInc/materialize/pull/16529) (@mjibson)
* [ ] [#16527 adapter: Add source/sink type to audit log DDL](https://github.com/MaterializeInc/materialize/pull/16527) (@jkosh44)
* [ ] [#16534 slt: Speed up SLT tests](https://github.com/MaterializeInc/materialize/pull/16534) (@philip-stoev)
* [ ] [#16538 platform checks: Add a Check for source errors](https://github.com/MaterializeInc/materialize/pull/16538) (@philip-stoev)
* [ ] [#16539 testdrive: Fix audit_log.td for non-default SIZEs](https://github.com/MaterializeInc/materialize/pull/16539) (@philip-stoev)
* [ ] [#16540 persist-sink: let inactive workers return early](https://github.com/MaterializeInc/materialize/pull/16540) (@teskje)
* [ ] [#16542 ci: Fortify the storage-usage test](https://github.com/MaterializeInc/materialize/pull/16542) (@philip-stoev)
* [ ] [#16541  pgrepr: support parsing text-encoded arrays #8840 ](https://github.com/MaterializeInc/materialize/pull/16541) (@sploiselle)
* [ ] [#16445 Propose `WITH MUTUALLY RECURSIVE`](https://github.com/MaterializeInc/materialize/pull/16445) (@frankmcsherry)
* [ ] [#16535 Basic tests for postgres source errors](https://github.com/MaterializeInc/materialize/pull/16535) (@bkirwi)
* [ ] [#16552 Mark implicit arrangements](https://github.com/MaterializeInc/materialize/pull/16552) (@antiguru)
* [ ] [#16509 Prepare for mutually recursive CTEs](https://github.com/MaterializeInc/materialize/pull/16509) (@frankmcsherry)
* [ ] [#16553 Unrevert "persist: read a bounded # of rows from CRDB when fetching l…](https://github.com/MaterializeInc/materialize/pull/16553) (@danhhz)
* [ ] [#16419 persist: remove Indeterminate from the compare_and_append signature](https://github.com/MaterializeInc/materialize/pull/16419) (@danhhz)
* [ ] [#16558 sql-parser: use dedicated column def type for mut rec CTEs](https://github.com/MaterializeInc/materialize/pull/16558) (@benesch)
* [ ] [#16537 Support UDS listen address for tokio-console](https://github.com/MaterializeInc/materialize/pull/16537) (@teskje)
* [ ] [#16565 build(deps): bump tokio from 1.22.0 to 1.23.0](https://github.com/MaterializeInc/materialize/pull/16565) (@dependabot[bot])
* [ ] [#16566 build(deps): bump sentry from 0.29.0 to 0.29.1](https://github.com/MaterializeInc/materialize/pull/16566) (@dependabot[bot])
* [ ] [#16567 build(deps): bump prost from 0.11.2 to 0.11.3](https://github.com/MaterializeInc/materialize/pull/16567) (@dependabot[bot])
* [ ] [#16568 build(deps): bump openssl-sys from 0.9.78 to 0.9.79](https://github.com/MaterializeInc/materialize/pull/16568) (@dependabot[bot])
* [ ] [#16573 build(deps): bump types-setuptools from 65.6.0.1 to 65.6.0.2 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16573) (@dependabot[bot])
* [ ] [#16574 build(deps): bump boto3 from 1.26.22 to 1.26.27 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16574) (@dependabot[bot])
* [ ] [#16572 build(deps): bump black from 22.10.0 to 22.12.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16572) (@dependabot[bot])
* [ ] [#16564 build(deps): bump ubuntu from jammy-20221101 to jammy-20221130 in /misc/images/ubuntu-base](https://github.com/MaterializeInc/materialize/pull/16564) (@dependabot[bot])
* [ ] [#16563 build(deps): bump ubuntu from jammy-20221101 to jammy-20221130 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16563) (@dependabot[bot])
* [ ] [#16575 deps: get back on mainline mysql_common](https://github.com/MaterializeInc/materialize/pull/16575) (@benesch)
* [ ] [#16570 build(deps): bump sysinfo from 0.26.8 to 0.27.0](https://github.com/MaterializeInc/materialize/pull/16570) (@dependabot[bot])
* [ ] [#16571 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.26.22 to 1.26.27 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16571) (@dependabot[bot])
* [ ] [#16321 build(deps): bump bytes from 1.2.1 to 1.3.0](https://github.com/MaterializeInc/materialize/pull/16321) (@dependabot[bot])
* [ ] [#16576 ci/deploy: publish license breakdown via cargo about](https://github.com/MaterializeInc/materialize/pull/16576) (@benesch)
* [ ] [#16551 cloudtest: Reduce DNS TTL to speed up test execution](https://github.com/MaterializeInc/materialize/pull/16551) (@necaris)
* [ ] [#16545 compute-client: remove unnecessary `allow`s](https://github.com/MaterializeInc/materialize/pull/16545) (@teskje)
* [ ] [#16089 config: synchronize `ALTER SYSTEM` parameters with LaunchDarkly](https://github.com/MaterializeInc/materialize/pull/16089) (@aalexandrov)
* [ ] [#16288 compute-client: simplify tracking of peeks](https://github.com/MaterializeInc/materialize/pull/16288) (@teskje)
* [ ] [#16515 compute-client: command module cleanup](https://github.com/MaterializeInc/materialize/pull/16515) (@teskje)
* [ ] [#16585 test: Additional tests for Postgres source errors](https://github.com/MaterializeInc/materialize/pull/16585) (@philip-stoev)
* [ ] [#16536 adapter: add end-to-end test for LaunchDarkly synchronization](https://github.com/MaterializeInc/materialize/pull/16536) (@aalexandrov)
* [ ] [#16525 compute: improve ReduceCollation unwrap error](https://github.com/MaterializeInc/materialize/pull/16525) (@teskje)
* [ ] [#16532 make mz_cluster_replica_sizes static](https://github.com/MaterializeInc/materialize/pull/16532) (@umanwizard)
* [ ] [#16590 environmentd: improve telemetry reporting](https://github.com/MaterializeInc/materialize/pull/16590) (@benesch)
* [ ] [#16594 misc: bump cockroach to 22.2](https://github.com/MaterializeInc/materialize/pull/16594) (@mjibson)
* [ ] [#16562 Correct `Get` types in `ProjectionPushdown`](https://github.com/MaterializeInc/materialize/pull/16562) (@frankmcsherry)
* [ ] [#16488 Adapter: Fix handling of constant queries in txns](https://github.com/MaterializeInc/materialize/pull/16488) (@jkosh44)
* [ ] [#16560 tracing: fix the fast-path in the presence of an otel collector, and add tests](https://github.com/MaterializeInc/materialize/pull/16560) (@guswynn)
* [ ] [#16595 environmentd: try bumping expiry again?](https://github.com/MaterializeInc/materialize/pull/16595) (@mjibson)
* [ ] [#16555 storage: use the new async OperatorBuilder for persist_source stage 1](https://github.com/MaterializeInc/materialize/pull/16555) (@danhhz)
* [ ] [#16592 Make CPU/Memory limits always exist](https://github.com/MaterializeInc/materialize/pull/16592) (@umanwizard)
* [ ] [`e48b6b50a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e48b6b50a4e5c066f4bb0a6a66992ff0d2facd1f) (@materializer)
* [ ] [`54ada90bd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/54ada90bdb7e8406e56f62c1ece85f2c3870076e) (@materializer)
* [ ] [`5faf6ed6e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5faf6ed6edfdfaeed4c30935f718ea4983150cd6) (@materializer)
* [ ] [`ea6e4431e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ea6e4431ed8c9989ba7c432206e127fd53681935) (@materializer)
* [ ] [`aeff1ae49` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aeff1ae491c34b5ca7212765e981acc0b56485c9) (@materializer)
* [ ] [`f6a89e1f0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f6a89e1f03e243476e85debda72a2281ac82abcc) (@materializer)
* [ ] [`208801f02` release: bump to version v0.35.0](https://github.com/MaterializeInc/materialize/commit/208801f0245b5f1a4280d69a7bfdf0485e292f64) (@umanwizard)

**Comment by guswynn** [comment]
@umanwizard's commit LGTM
