### ISSUE TITLE
release: v0.37.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16735]
The following PRs in [`v0.37.0`](https://github.com/MaterializeInc/materialize/tree/v0.37.0) require review:
* [x] [#16578 zippy: Extend the execution time of the Release Qualification tests](https://github.com/MaterializeInc/materialize/pull/16578) (@philip-stoev)
* [x] [#16614 cloudtest: Fix order of execution in Buildkite plugin](https://github.com/MaterializeInc/materialize/pull/16614) (@philip-stoev)
* [x] [#16617 ci,test: Fortify the storage-usage mzcompose workflow](https://github.com/MaterializeInc/materialize/pull/16617) (@philip-stoev)
* [x] [#16618 sqllogitest: Fortify cluster.slt](https://github.com/MaterializeInc/materialize/pull/16618) (@philip-stoev)
* [x] [#16626 Move non-deterministic SLT test to TD](https://github.com/MaterializeInc/materialize/pull/16626) (@umanwizard)
* [x] [#16636 feature-benchmark: Use a fully-formed environment_id](https://github.com/MaterializeInc/materialize/pull/16636) (@philip-stoev)
* [x] [#16659 ci,test: Add a dedicated test for bounded memory operation](https://github.com/MaterializeInc/materialize/pull/16659) (@philip-stoev)
* [x] [#16661 zippy,ci: Add a longer ClusterReplicas Zippy test to the Release Qual…](https://github.com/MaterializeInc/materialize/pull/16661) (@philip-stoev)
* [x] [#16663 nightly: mark the cargo-deps job as soft-fail](https://github.com/MaterializeInc/materialize/pull/16663) (@philip-stoev)
* [x] [#16561 `LetRec`: HIR, lowering, MIR](https://github.com/MaterializeInc/materialize/pull/16561) (@frankmcsherry)
* [x] [#16671 Address comments on #16657](https://github.com/MaterializeInc/materialize/pull/16671) (@umanwizard)
* [x] [#16705 ore,orchestrator-tracing: allow configuring sentry environment](https://github.com/MaterializeInc/materialize/pull/16705) (@benesch)
* [x] [#16707 ci/test: scope down the inputs to the cargo-test job](https://github.com/MaterializeInc/materialize/pull/16707) (@benesch)
* [x] [#16710 orchestrator-tracing: add missing clap annotation for sentry env param](https://github.com/MaterializeInc/materialize/pull/16710) (@benesch)
* [x] [#16728 ci: Fix the cleanup pipeline](https://github.com/MaterializeInc/materialize/pull/16728) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`bb6b6ef7d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bb6b6ef7de16fa9d45b7e8cae49afa2d0f55b52f) (@materializer)
* [x] [`48a3f6e05` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/48a3f6e05a859c77ab70594045f8b18352e8c766) (@materializer)
* [x] [`f27f9c970` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f27f9c970886557ded9b75abab32d6a2ad60aee3) (@materializer)
* [x] [`788137ce2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/788137ce25d65f3ee15c84c7a0b09650b5aa8394) (@materializer)
* [x] [`d2430683d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d2430683dc6af16ddfc0afac2cfa746d76b8fca9) (@materializer)
* [x] [`00f832b53` ci/test: fix inputs glob for cargo-test job](https://github.com/MaterializeInc/materialize/commit/00f832b537496f520ed886e277ba93d57776aaf9) (@benesch)
* [x] [`962bef9f3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/962bef9f3e8b919244c1fa4148f974e3a4568df3) (@materializer)
* [x] [`5d723f498` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5d723f498de05703a4d18fd8efe2db63999734f4) (@materializer)
* [x] [`69f378b9d` release: bump to version v0.37.0](https://github.com/MaterializeInc/materialize/commit/69f378b9dbaa4de93606262e42ed6d85b039df2a) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#16578 zippy: Extend the execution time of the Release Qualification tests](https://github.com/MaterializeInc/materialize/pull/16578) (@philip-stoev)
* [ ] [#16514 storage: adjust the persist "purpose" strings with Aljoscha feedback](https://github.com/MaterializeInc/materialize/pull/16514) (@danhhz)
* [ ] [#16603 bump kubernetes version](https://github.com/MaterializeInc/materialize/pull/16603) (@doy-materialize)
* [ ] [#16597 Add mz_cluster_replica_utilization view](https://github.com/MaterializeInc/materialize/pull/16597) (@umanwizard)
* [ ] [#16504 *: use hakari to manage a workspace-hack crate](https://github.com/MaterializeInc/materialize/pull/16504) (@benesch)
* [ ] [#16600 release: bump to version v0.37.0-dev](https://github.com/MaterializeInc/materialize/pull/16600) (@umanwizard)
* [ ] [#16559 *: disallow potentially dangerous `as` conversions](https://github.com/MaterializeInc/materialize/pull/16559) (@benesch)
* [ ] [#16614 cloudtest: Fix order of execution in Buildkite plugin](https://github.com/MaterializeInc/materialize/pull/16614) (@philip-stoev)
* [ ] [#16617 ci,test: Fortify the storage-usage mzcompose workflow](https://github.com/MaterializeInc/materialize/pull/16617) (@philip-stoev)
* [ ] [#16618 sqllogitest: Fortify cluster.slt](https://github.com/MaterializeInc/materialize/pull/16618) (@philip-stoev)
* [ ] [#16609 Correctly decode negative timestamps with Avro](https://github.com/MaterializeInc/materialize/pull/16609) (@umanwizard)
* [ ] [#16546 Adapter: Remove timestamps from constant peeks](https://github.com/MaterializeInc/materialize/pull/16546) (@jkosh44)
* [ ] [#16613 environmentd: add source and sink types to telemetry reporting](https://github.com/MaterializeInc/materialize/pull/16613) (@benesch)
* [ ] [#16605 adapter: Fix topological sort of schema migration](https://github.com/MaterializeInc/materialize/pull/16605) (@jkosh44)
* [ ] [#16628 update workspace-hack versions to match](https://github.com/MaterializeInc/materialize/pull/16628) (@doy-materialize)
* [ ] [#16608 adapter: Implement MVP for real time recency](https://github.com/MaterializeInc/materialize/pull/16608) (@jkosh44)
* [ ] [#16626 Move non-deterministic SLT test to TD](https://github.com/MaterializeInc/materialize/pull/16626) (@umanwizard)
* [ ] [#16483 [docs] Document more of our intended Kafka semantics](https://github.com/MaterializeInc/materialize/pull/16483) (@bkirwi)
* [ ] [#16632 ci: re-enable cargo test in CI](https://github.com/MaterializeInc/materialize/pull/16632) (@petrosagg)
* [ ] [#16635 persist: fix accidental N^2 in debug-only validations](https://github.com/MaterializeInc/materialize/pull/16635) (@danhhz)
* [ ] [#16636 feature-benchmark: Use a fully-formed environment_id](https://github.com/MaterializeInc/materialize/pull/16636) (@philip-stoev)
* [ ] [#16638 Revert "Merge pull request #16288 from teskje/simplify-peek-tracking"](https://github.com/MaterializeInc/materialize/pull/16638) (@teskje)
* [ ] [#16624 sql: Fix negative fractional timestamp handling](https://github.com/MaterializeInc/materialize/pull/16624) (@jkosh44)
* [ ] [#16643 plan: Update stale comment for plan_view_select](https://github.com/MaterializeInc/materialize/pull/16643) (@jkosh44)
* [ ] [#16645 adapter: add session var to emit timestamp notices](https://github.com/MaterializeInc/materialize/pull/16645) (@mjibson)
* [ ] [#16648 storage: move worker tasks into their own modules](https://github.com/MaterializeInc/materialize/pull/16648) (@aljoscha)
* [ ] [#6763 Allow Row arrangements backed by columns](https://github.com/MaterializeInc/materialize/pull/6763) (@frankmcsherry)
* [ ] [#16627 [sources] Thread a should_halt flag through the source pipeline](https://github.com/MaterializeInc/materialize/pull/16627) (@bkirwi)
* [ ] [#16630 Add "System catalog style" section to developer style guide](https://github.com/MaterializeInc/materialize/pull/16630) (@chaas)
* [ ] [#16655 Collective nouns: +"Utilization"](https://github.com/MaterializeInc/materialize/pull/16655) (@umanwizard)
* [ ] [#16593 Add source/sink status_es_ views](https://github.com/MaterializeInc/materialize/pull/16593) (@bkirwi)
* [ ] [#16659 ci,test: Add a dedicated test for bounded memory operation](https://github.com/MaterializeInc/materialize/pull/16659) (@philip-stoev)
* [ ] [#16661 zippy,ci: Add a longer ClusterReplicas Zippy test to the Release Qual…](https://github.com/MaterializeInc/materialize/pull/16661) (@philip-stoev)
* [ ] [#16663 nightly: mark the cargo-deps job as soft-fail](https://github.com/MaterializeInc/materialize/pull/16663) (@philip-stoev)
* [ ] [#16561 `LetRec`: HIR, lowering, MIR](https://github.com/MaterializeInc/materialize/pull/16561) (@frankmcsherry)
* [ ] [#16666 fix merge skew: add match branch for LetRec](https://github.com/MaterializeInc/materialize/pull/16666) (@aljoscha)
* [ ] [#16611 doc/user: polish v0.36 release notes](https://github.com/MaterializeInc/materialize/pull/16611) (@morsapaes)
* [ ] [#16530 Document the sink status tables](https://github.com/MaterializeInc/materialize/pull/16530) (@bkirwi)
* [ ] [#16480 Update docs to describe and reference the mz_aws_privatelink_connections system table](https://github.com/MaterializeInc/materialize/pull/16480) (@chaas)
* [ ] [#16548 `FilterCharacteristics` behind Gets](https://github.com/MaterializeInc/materialize/pull/16548) (@ggevay)
* [ ] [#16633 storage: support csr over ssh tunnels](https://github.com/MaterializeInc/materialize/pull/16633) (@guswynn)
* [ ] [#16667 Fix embarrassing query error in mz_cluster_replica_utilization](https://github.com/MaterializeInc/materialize/pull/16667) (@umanwizard)
* [ ] [#16657 Support `EXPLAIN TIMESTAMP AS JSON`](https://github.com/MaterializeInc/materialize/pull/16657) (@umanwizard)
* [ ] [#16672 tokio-console: fix task names](https://github.com/MaterializeInc/materialize/pull/16672) (@guswynn)
* [ ] [#16673 mzcompose: Update Redpanda to v22.3.8](https://github.com/MaterializeInc/materialize/pull/16673) (@BenPope)
* [ ] [#16671 Address comments on #16657](https://github.com/MaterializeInc/materialize/pull/16671) (@umanwizard)
* [ ] [#16604 storage: populate `mz_storage_host_metrics` using new metrics scraper](https://github.com/MaterializeInc/materialize/pull/16604) (@aljoscha)
* [ ] [#16656 Support iterative dataflows](https://github.com/MaterializeInc/materialize/pull/16656) (@frankmcsherry)
* [ ] [#16679 doc/user: document self-serve access to AWS PrivateLink principals](https://github.com/MaterializeInc/materialize/pull/16679) (@benesch)
* [ ] [#16683 zippy: Improve log output](https://github.com/MaterializeInc/materialize/pull/16683) (@philip-stoev)
* [ ] [#16688 doc/user: Change note + warning colors](https://github.com/MaterializeInc/materialize/pull/16688) (@joacoc)
* [ ] [#16681 repr: remove Serialize impls from Datum and friends](https://github.com/MaterializeInc/materialize/pull/16681) (@benesch)
* [ ] [#16649 adapter: Fix serializable read-then-writes](https://github.com/MaterializeInc/materialize/pull/16649) (@jkosh44)
* [ ] [#16678 adapter: change the LaunchDarkly context key, upgrade to 1.0.0](https://github.com/MaterializeInc/materialize/pull/16678) (@aalexandrov)
* [ ] [#14704 persist: special-case a shard with empty upper and empty since](https://github.com/MaterializeInc/materialize/pull/14704) (@danhhz)
* [ ] [#16695 adapter/sql: Remove some usages of as](https://github.com/MaterializeInc/materialize/pull/16695) (@jkosh44)
* [ ] [#15518 persist: extract a new shard_source operator from persist_source](https://github.com/MaterializeInc/materialize/pull/15518) (@danhhz)
* [ ] [#16694 adapter: document initial config sync philosophy](https://github.com/MaterializeInc/materialize/pull/16694) (@benesch)
* [ ] [#16569 build(deps): bump mysql_async from 0.31.0 to 0.31.2](https://github.com/MaterializeInc/materialize/pull/16569) (@dependabot[bot])
* [ ] [#16697 *: use ReinterpretCast everywhere it applies](https://github.com/MaterializeInc/materialize/pull/16697) (@benesch)
* [ ] [#16700 deps: upgrade to axum v0.6.1+](https://github.com/MaterializeInc/materialize/pull/16700) (@benesch)
* [ ] [#16677 environmentd: add experimental websocket endpoint](https://github.com/MaterializeInc/materialize/pull/16677) (@mjibson)
* [ ] [#16703 doc/user: mark websocket API as in alpha](https://github.com/MaterializeInc/materialize/pull/16703) (@benesch)
* [ ] [#16702 Switch to HEAD of Chrono 0.4.x](https://github.com/MaterializeInc/materialize/pull/16702) (@umanwizard)
* [ ] [#16705 ore,orchestrator-tracing: allow configuring sentry environment](https://github.com/MaterializeInc/materialize/pull/16705) (@benesch)
* [ ] [#16704 environmentd: use interchange's Datum -> JSON impl](https://github.com/MaterializeInc/materialize/pull/16704) (@benesch)
* [ ] [#16707 ci/test: scope down the inputs to the cargo-test job](https://github.com/MaterializeInc/materialize/pull/16707) (@benesch)
* [ ] [#16710 orchestrator-tracing: add missing clap annotation for sentry env param](https://github.com/MaterializeInc/materialize/pull/16710) (@benesch)
* [ ] [#16725 build(deps): bump libc from 0.2.137 to 0.2.138](https://github.com/MaterializeInc/materialize/pull/16725) (@dependabot[bot])
* [ ] [#16724 build(deps): bump semver from 1.0.14 to 1.0.16](https://github.com/MaterializeInc/materialize/pull/16724) (@dependabot[bot])
* [ ] [#16723 build(deps): bump num-bigint from 0.4.2 to 0.4.3](https://github.com/MaterializeInc/materialize/pull/16723) (@dependabot[bot])
* [ ] [#16722 build(deps): bump memchr from 2.4.1 to 2.5.0](https://github.com/MaterializeInc/materialize/pull/16722) (@dependabot[bot])
* [ ] [#16715 build(deps): bump boto3 from 1.26.27 to 1.26.32 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16715) (@dependabot[bot])
* [ ] [#16718 build(deps): bump isort from 5.10.1 to 5.11.3 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16718) (@dependabot[bot])
* [ ] [#16719 build(deps): bump tower-http from 0.3.4 to 0.3.5](https://github.com/MaterializeInc/materialize/pull/16719) (@dependabot[bot])
* [ ] [#16721 build(deps): bump sentry-tracing from 0.29.0 to 0.29.1](https://github.com/MaterializeInc/materialize/pull/16721) (@dependabot[bot])
* [ ] [#16728 ci: Fix the cleanup pipeline](https://github.com/MaterializeInc/materialize/pull/16728) (@philip-stoev)
* [ ] [#16687 storage: add source/sink utilization views](https://github.com/MaterializeInc/materialize/pull/16687) (@aljoscha)
* [ ] [#16647 Set up metrics stream on replica creation](https://github.com/MaterializeInc/materialize/pull/16647) (@umanwizard)
* [ ] [#16591 adapter,storage: add `envelope` column to `mz_sources`](https://github.com/MaterializeInc/materialize/pull/16591) (@aljoscha)
* [ ] [#16729 Make storage controller metrics warning less verbose](https://github.com/MaterializeInc/materialize/pull/16729) (@umanwizard)
* [ ] [#16711 environmentd: enable server-side TCP keepalives after 60s](https://github.com/MaterializeInc/materialize/pull/16711) (@benesch)
* [ ] [#16731 Remove unnecessary paste macro](https://github.com/MaterializeInc/materialize/pull/16731) (@jkosh44)
* [ ] [#16732 docs: document unqualified delete as a workaround to truncation](https://github.com/MaterializeInc/materialize/pull/16732) (@sjwiesman)
* [ ] [#16730 Revert "misc: bump cockroach to 22.2"](https://github.com/MaterializeInc/materialize/pull/16730) (@arusahni)
* [ ] [`bb6b6ef7d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bb6b6ef7de16fa9d45b7e8cae49afa2d0f55b52f) (@materializer)
* [ ] [`48a3f6e05` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/48a3f6e05a859c77ab70594045f8b18352e8c766) (@materializer)
* [ ] [`f27f9c970` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f27f9c970886557ded9b75abab32d6a2ad60aee3) (@materializer)
* [ ] [`788137ce2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/788137ce25d65f3ee15c84c7a0b09650b5aa8394) (@materializer)
* [ ] [`d2430683d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d2430683dc6af16ddfc0afac2cfa746d76b8fca9) (@materializer)
* [ ] [`00f832b53` ci/test: fix inputs glob for cargo-test job](https://github.com/MaterializeInc/materialize/commit/00f832b537496f520ed886e277ba93d57776aaf9) (@benesch)
* [ ] [`962bef9f3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/962bef9f3e8b919244c1fa4148f974e3a4568df3) (@materializer)
* [ ] [`5d723f498` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5d723f498de05703a4d18fd8efe2db63999734f4) (@materializer)
* [ ] [`69f378b9d` release: bump to version v0.37.0](https://github.com/MaterializeInc/materialize/commit/69f378b9dbaa4de93606262e42ed6d85b039df2a) (@jkosh44)

**Comment by benesch** [comment]
@jkosh44's commit LGTM.

**Comment by jkosh44** [comment]
PRs and commits LGTM.
