### ISSUE TITLE
release: v0.37.1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16745]
No PRs in [`v0.37.1`](https://github.com/MaterializeInc/materialize/tree/v0.37.1) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`364daccc8` Revert "Revert "misc: bump cockroach to 22.2" (#16730)"](https://github.com/MaterializeInc/materialize/commit/364daccc8e93f2def68216e61c46dd402b6455de) (@benesch)
* [x] [`7981bc349` Revert "Merge pull request #14704 from danhhz/persist_empty_antichain"](https://github.com/MaterializeInc/materialize/commit/7981bc3496cf5c97e09cab6a34fb89b312b09862) (@benesch)
* [x] [`e155ee1a6` release: bump to version v0.37.1](https://github.com/MaterializeInc/materialize/commit/e155ee1a626f7ddbedfb74277cbd27fcc084530f) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`364daccc8` Revert "Revert "misc: bump cockroach to 22.2" (#16730)"](https://github.com/MaterializeInc/materialize/commit/364daccc8e93f2def68216e61c46dd402b6455de) (@benesch)
* [ ] [`7981bc349` Revert "Merge pull request #14704 from danhhz/persist_empty_antichain"](https://github.com/MaterializeInc/materialize/commit/7981bc3496cf5c97e09cab6a34fb89b312b09862) (@benesch)
* [ ] [`e155ee1a6` release: bump to version v0.37.1](https://github.com/MaterializeInc/materialize/commit/e155ee1a626f7ddbedfb74277cbd27fcc084530f) (@benesch)

**Comment by arusahni** [comment]
LGTM!
