### ISSUE TITLE
Add dynamic configuration for PersistConfig

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#16753]
As outlined in the [user stories section of the design doc for dynamic environment configuration](https://www.notion.so/materialize/Dynamic-environment-configuration-ad11421b40934e4cba675bbe550cc2b2#80ee54c75ba448eaa23c1b5b81150f35), the storage team would like to be able to tweak [PersistConfig options](https://github.com/MaterializeInc/materialize/blob/0807a06845cce08dd1b9e88b8f4fe7b743bf71ed/src/persist-client/src/lib.rs#L186-L242) using dynamic configuration options.

## Tasks

- [x] compute: Add LaunchDarkly parameter for persist config
    #17076
- [x] compute: Plumb persist config param through to controllers
    #17076
- [ ] storage: Use dynamic options to configure persist clients

## Description

As discussed offline with @teskje and @danhhz, the compute team will put all the required plumbing in place for storage to use the configuration options.

Dan confirms `PersistClient` should be able to handle differing configs (let's say one used in a `persist_source` and another one in a `persist_sink`) which means we don't have to introduce any additional consistency constraints for distribution of these options.

**Comment by teskje** [comment]
There are a whole bunch of persist options, and I think we want to be able to adjust selected ones, without having to specify all the other ones we don't care about. There are two ways I can imagine that to be reflected in the `ALTER SYSTEM` API:

1. Have one parameter per `PersistConfig` field.
2. Have a single `persist_config` parameter that expects a sparse JSON object. Config options that are not specified remain unchanged.

The first option would just work, but might be a bit noisy. We would end up with a bunch of `persist_config_` parameters that might clutter parameter listings. Not sure how much of a concern that is.

The second option is potentially less verbose, but likely harder to implement. I'm not even sure if our current system parameter implementation supports such partial updates at all.

@aalexandrov @danhhz Do you have any preferences for one over the other approach?

**Comment by benesch** [comment]
FWIW I like the sound of (1) better! More annoying to type out, for sure, but it'll be more typo-proof in the LD GUI.

**Comment by teskje** [comment]
I also remembered that LD requires you to create a separate flag variant for each unique value you want to set. If we went with (2) that could quickly lead to a combinatorial explosion of variants we had to define. So I agree (1) seems better.

**Comment by aalexandrov** [comment]
My preference was also for (1), mostly because LD variants are set from an `input` field (no `textarea`), so everything that does not fit in a single line (~100 chars) will require scrolling and will be error-prone.

**Comment by danhhz** [comment]
Also preference for (1)!

**Comment by danhhz** [comment]
> One question that I have to @benesch is what to do with the 21 new parameters that need to be mirrored from PersistConfig in SystemVars - should they be hidden or visible to regular users? I assume we don't want to clutter the SHOW ALL page with parameters that we don't want users to know about.

I have the same question. My initial hunch is we don't particular care about (or even want?) these being vars, just controllable from LaunchDarkly.

**Comment by benesch** [comment]
Agreed! I would set them all as `internal`. That way we can still see their value from the internal SQL port, but customers won't be able to see them.

**Comment by danhhz** [comment]
Threw up a PR for a quick first stab at what the interface between LaunchDarkly and PersistConfig might look like. I don't love how this turned out, so gonna keep mulling it over, but you can definitely get an idea of the basic direction #https://github.com/MaterializeInc/materialize/pull/16797

**Comment by teskje** [comment]
I'm planning to start the adapter/controller work on this this week.

@danhhz #16797 only moves a subset of the `PersistConfig` fields into a `DynamicConfig` struct. Do you only want those four options dynamically configurable, or are these just the ones you selected for a poc?

**Comment by teskje** [comment]
Another question for @danhhz: What should be the scope of persist parameter changes? Should they only apply to to dataflows/sources/sinks created subsequently, or should they also apply to existing persist clients? Does the scope depend on the persist parameter?

If there are parameter changes that should apply to existing persist clients, we have to keep in mind that this will lead to differently configured persist clients reading from/writing to the same shards: One replica might receive a config update later than others, so its persist clients will continue working with the old configuration while other replicas have already switched to the new one.

**Comment by danhhz** [comment]
> Do you only want those four options dynamically configurable, or are these just the ones you selected for a poc?

The latter. The goal of that PR was primarily to show how I imagined the integration between PersistClient and LaunchDarkly working.

I think ideally we'll eventually switch pretty much all of them. I just scanned through the list again and there are 3 that don't make sense as dynamic, 1 that should be removed, and 1 that will be hard to make dynamic, but everything else could be dynamic. That said, there's certainly a bit of a long tail, so happy to come up with a smaller set than "everything" if that makes things significantly easier

> What should be the scope of persist parameter changes? Should they only apply to to dataflows/sources/sinks created subsequently, or should they also apply to existing persist clients? Does the scope depend on the persist parameter?
> 
> If there are parameter changes that should apply to existing persist clients, we have to keep in mind that this will lead to differently configured persist clients reading from/writing to the same shards: One replica might receive a config update later than others, so its persist clients will continue working with the old configuration while other replicas have already switched to the new one.

So, there's only one PersistConfig per process. The way I see this working is for it to be updated with new LaunchDarkly configs and then the next time the fn is called, it will get the updated value.

It's possible we should schedule a quick call to hash this all out? I can imagine a number of different ways this could all work and we could probably save some time by not typing them all out

**Comment by teskje** [comment]
https://github.com/MaterializeInc/materialize/pull/17076 introduced all the required adapter and controller plumbing. AFAICT the only thing left is passing the config to the persist clients in the three relevant places (computed, storaged, storage controller).

**Comment by aalexandrov** [comment]
Unlinking this from #15230 as the remaining task (storage: Use dynamic options to configure persist clients) is independent from the groundwork that was scroped within that epic.
