### ISSUE TITLE
storage: don't use `halt!` in sources and sinks

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#16773]
"don't use `halt!`" here is an umbrella term for: sources and sinks must have a graceful/controlled way of restarting themselves or dealing with errors.

Failing fast was an easy way to get good error recovery in sources and sinks but we cannot do that when we want to let multiple sources and/or sinks share a storage host (or cluster). This is especially important with the long-term goal of unifying compute and storage clusters.

```[tasklist]
### Tasks
 - [x] #16958
 - [x] don't use `halt!` in sources
 - [x] #17208
 - [ ] #17207
 - [ ] (maybe) remove `panic!` in bootup of reclock operator
- [ ] https://github.com/MaterializeInc/materialize/issues/17696
```

**Comment by aljoscha** [comment]
@guswynn @petrosagg @bkirwi: I see two approaches (so far):

1. Sinks and sources must buffer messages in memory so that they can retry when external calls fail.
2. There must be a protocol between storage process(es) and controller that allows sources/sink to request a graceful suspend/restart. A source/sink cannot do this "locally" because it cannot affect other, sharded, parts of itself.

I'm leaning towards 2. because 1. has potentially scary, spiky memory behaviour. What do you think?

**Comment by aljoscha** [comment]
@philip-stoev What do you think we need in terms of testing? This is largely relevant for the postgres sources, which uses `halt!` right now to recover from errors during reading of the initial snapshot and for Kafka sinks which `halt!` (and restart) on errors during writing/committing.

**Comment by philip-stoev** [comment]
What is needed is that:
1. any errors that were previously halts are propagated in a way that will have them properly show up in the `mz_source|sink_status_history` source:
- the status field should be `stalled`
- the error field should have the string that was previously in the `halt!`
- once the source/sink restarts , a new history record should be emitted with the state of `starting` , followed by a record with state = `running`
2. The current locations of `!halts` are modified to have a named failpoint so that those same situations can be re-created in a test e.g. failure to commit to Kafka. The test can mess with postgres/kafka to get some approximation but this is error prone (e.g. kafka does not reliably restart in docker-compose once killed, it may be difficult to kill postgres at the exact time a snapshot is being taken, etc.)

**Comment by bkirwi** [comment]
I also lean towards 2. We adopted `halt!` so heavily in the sink because it vastly simplifies reasoning about how errors are managed; 2 preserves that property while 1 would regress it.

I don't have very many thoughts about implementation, though I suppose if we allow ourselves to hijack the async operator builder you could do nice things like have `input_handle.next()` return a `Result` where `Err` indicates it's time to shut down.

Failpoints are a great idea.

**Comment by petrosagg** [comment]
It's dataflows all the way down and I also love this idea!

**Comment by benesch** [comment]
Wait, that's brilliant! I don't think it even needs to involve the storage controller. In fact I think it shouldn't, because a source or sink dataflow experiencing an error should be local to that replica, right? (I'm imagining that we want to do this in a way that is friendly to future replicated source/sink pipelines.)

I'm handwaving wildly, but imagine that the source ingestion pipeline has access to an additional error stream output. Any operator can choose to emit an error into this stream. At the very end of this stream we have a self destruct operator. If the self destruct operator sees any errors, it drops the currently running dataflow (as if by `AllowCompaction([])`) and then reconstructs the dataflow from its description.

**Comment by aljoscha** [comment]
I took a first stab at implementing the "cluster-internal control dataflow" idea: https://github.com/MaterializeInc/materialize/pull/16875.

There are some subtle issues that I discovered while doing some light thinking (more explanation below):

1. I don't think we can do the (admittedly handwave-y) idea of keeping this local to a given source. Where sources have an error output stream and there is a self destruct operator at the end of the pipeline that can drop and restart a dataflow. cc @benesch 
2. We need to be _very_ careful because we're interleaving commands coming from the controller with internal commands and timely is particular about creating dataflows on all workers in the same,deterministic order.

### 1. Source-local self destruct operator vs. one global, cluster-internal control dataflow

The simplest reason is that sources and sinks currently don't have any code running outside of their dataflow operators. The code that constructs the dataflow is running "outside" the operators, but the only piece of code that is continually running is the timely worker main loop that either steps timely or works of commands from the controller. We need code outside of the operators to be able to tear down dataflows and re-construct them.

I think we need to have one global control dataflow that is used to broadcast commands from a single operator instance to all workers. And then we'll need a piece of code in the timely main loop that is working of these internal commands. This is what I did in my PoC PR.

### 2. Interleaving of internal and controller-issued commands

In order for communication to work correctly between workers, timely dataflows/operators must be constructed in the same (deterministic) order on all workers. The handwave-y explanation is that timely internally uses an incrementing ID for identifying operators.

I think what we need is something similar to how compute clusters already handle commands send from the controller to workers: the controller sends commands only to `worker 0`, and that worker broadcasts them to all workers of the cluster on an internal dataflow. We have to push controller-issued commands through the same global, cluster-internal dataflow and make sure that all workers work them off in the same order. My PoC does **not yet** implement that, so will have subtle issues. 

I think issue 1. is a fine restriction and we can resolve 2. with some elbow grease. Overall I'm still bullish on this solution. What do you think?

**Comment by benesch** [comment]
> I don't think we can do the (admittedly handwave-y) idea of keeping this local to a given source. Where sources have an error output stream and there is a self destruct operator at the end of the pipeline that can drop and restart a dataflow. cc @benesch

Oh, I didn't mean source local! I just meant replica local! As in, tearing down and recreating a source in a cluster replica seems like something the replica can do without communication with the controller or any other replicas of the source.

AFAICT, this is exactly what your PoC does? In a future world where storage clusters can be replicated, seems like your PR would result in `SuspendAndResume` to be a thing that happens in just one replica at a time.

**Comment by aljoscha** [comment]
> AFAICT, this is exactly what your PoC does? 
yep!

> In a future world where storage clusters can be replicated, seems like your PR would result in SuspendAndResume to be a thing that happens in just one replica at a time.

Yes, `SuspendAndResume` is local to the replica. The control flow is really replica-local, not cluster-local. My naming was referring to timely clusters here, which doesn't match our usual usage of the term _cluster_ 😅

**Comment by benesch** [comment]
> The control flow is really replica-local, not cluster-local. My naming was referring to timely clusters here, which doesn't match our usual usage of the term cluster 😅

💡

Sounds good!

**Comment by bkirwi** [comment]
> I think what we need is something similar to how compute clusters already handle commands send from the controller to workers [...]

I like this idea, especially if it brings us closer to how computed does things!

**Comment by teskje** [comment]
> I think what we need is something similar to how compute clusters already handle commands send from the controller to workers: the controller sends commands only to worker 0, and that worker broadcasts them to all workers of the cluster on an internal dataflow.

Note that we have some tentative plans in compute to get rid of the distributor dataflow again: https://github.com/MaterializeInc/materialize/issues/16271. The reasoning here is basically that we introduced this dataflow only to solve an issue with reconciliation, that can be solved in other ways that avoid introducing so many edge-cases in the protocol.

Of course the calculation changes when we find other reasons to have this distributor dataflow, apart from fixing reconciliation. Making internal/external command distribution deterministic is such a reason and it doesn't seem like there is a good alternative (that I can think of).

All that is to say, if we end up leaning more heavily on the distributor dataflow for making `halt!`-less sources/sinks work, I'm fine with burying the plans of getting rid of it!

**Comment by aljoscha** [comment]
> 2\. The current locations of `!halts` are modified to have a named failpoint so that those same situations can be re-created in a test e.g. failure to commit to Kafka. The test can mess with postgres/kafka to get some approximation but this is error prone (e.g. kafka does not reliably restart in docker-compose once killed, it may be difficult to kill postgres at the exact time a snapshot is being taken, etc.)

@philip-stoev double-checking: this is something that allows writing tests in a way that was previously not possible, right? Before, you could only "tickle" the halt indirectly (as you said, by injecting things, killing containers)? Not saying that we shouldn't do it, just clarifying.

**Comment by petrosagg** [comment]
This is now done

**Comment by benesch** [comment]
Just for the record: #17696 is still an issue. But I think that's okay; we can track that issue in isolation.

**Comment by aljoscha** [comment]
for context: we had a backlog grooming session and decided to close this one while we _still_ want to get rid of more `halts`/`panics` as we find them.
