### ISSUE TITLE
release: v0.38.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#16881]
The following PRs in [`v0.38.0`](https://github.com/MaterializeInc/materialize/tree/v0.38.0) require review:
* [x] [#16748 bounded-memory test: Increase mem allowance for environmentd/computed](https://github.com/MaterializeInc/materialize/pull/16748) (@philip-stoev)
* [x] [#16743 Revert "Merge pull request #14704 from danhhz/persist_empty_antichain"](https://github.com/MaterializeInc/materialize/pull/16743) (@benesch)
* [x] [#16772 ci: Fortify cluster_replica_frontiers.td in Nightly](https://github.com/MaterializeInc/materialize/pull/16772) (@philip-stoev)
* [x] [#16770 docs: fix grammar in README intro and About.](https://github.com/MaterializeInc/materialize/pull/16770) (@jstirnaman)
* [x] [#16802 deps: update URL to tokio-console fork](https://github.com/MaterializeInc/materialize/pull/16802) (@benesch)
* [x] [#16706 test: switch tests and dev env to use CockroachDB instead of Postgres](https://github.com/MaterializeInc/materialize/pull/16706) (@benesch)
* [x] [#16811 doc/user: improve documentation on SQL client connections](https://github.com/MaterializeInc/materialize/pull/16811) (@morsapaes)
* [x] [#16814 adapter,environmentd: move segment context fields to properties](https://github.com/MaterializeInc/materialize/pull/16814) (@benesch)
* [x] [#16815 nexttest.toml: fix precedence override](https://github.com/MaterializeInc/materialize/pull/16815) (@benesch)
* [x] [#16816 doc/developer: don't suggest binding port 8080 for Cockroach UI](https://github.com/MaterializeInc/materialize/pull/16816) (@benesch)
* [x] [#16818 *: warn rather than deny lints](https://github.com/MaterializeInc/materialize/pull/16818) (@benesch)
* [x] [#16833 doc/user: consolidate PostgreSQL guides](https://github.com/MaterializeInc/materialize/pull/16833) (@morsapaes)
* [x] [#16849 doc/user: improve network security documentation](https://github.com/MaterializeInc/materialize/pull/16849) (@morsapaes)
* [x] [#16834 test/cloudtest: various improvements](https://github.com/MaterializeInc/materialize/pull/16834) (@benesch)
* [x] [#16856 ci/test: re-enable all restart tests](https://github.com/MaterializeInc/materialize/pull/16856) (@benesch)
* [x] [#16864 zippy: Add a secenario that restarts CRDB and Minio](https://github.com/MaterializeInc/materialize/pull/16864) (@philip-stoev)
* [x] [#16867 bin/cargo-test: set COCKROACH_URL, not POSTGRES_URL](https://github.com/MaterializeInc/materialize/pull/16867) (@benesch)
* [x] [#16871 feature-benchmark: Adjust the ParallelDataflows scenario](https://github.com/MaterializeInc/materialize/pull/16871) (@philip-stoev)
* [x] [#16880 bin/sqllogictest: don't remove clusterd processes](https://github.com/MaterializeInc/materialize/pull/16880) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`c95971f1c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c95971f1c203087f68f14052d6e11deb788c510a) (@materializer)
* [x] [`af6401686` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/af640168612b07e0c4f4ccb7de5885c8cf778881) (@materializer)
* [x] [`0a0a69066` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0a0a6906687e31df038bcfd91cd11f016cfb92d6) (@materializer)
* [x] [`ac90d8a67` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ac90d8a67b3c264e3a193147f99d8c3c42b95d36) (@materializer)
* [x] [`5af5fbaee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5af5fbaeebe0e25c48da456eace2f3da6d43dd59) (@materializer)
* [x] [`496ad1efe` nexttest.toml: bump the environmentd::test_pgtest timeout](https://github.com/MaterializeInc/materialize/commit/496ad1efe22becf1ae96330052b843afe2c07621) (@benesch)
* [x] [`5f6eaa517` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5f6eaa5175d2fc98bac69cbfa8a7b5f628e20359) (@materializer)
* [x] [`c1cacd024` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c1cacd024bcd3a9353d28cba3958e585bc30b588) (@materializer)
* [x] [`6c1108030` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6c1108030414359320a5a3933c52520bd3019442) (@materializer)
* [x] [`432a274a8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/432a274a8875f5b84be6e93e58ba67199296be58) (@materializer)
* [x] [`0ec66cb9c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0ec66cb9ce0b620a732ff562cd39afdc0122f78c) (@materializer)
* [x] [`b93b83266` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b93b832664b0283798b373bb836c4cc7a682db22) (@materializer)
* [x] [`f08cf34d3` release: bump to version v0.38.0](https://github.com/MaterializeInc/materialize/commit/f08cf34d3425fbdea203e489a1e2b9caac5c4fb5) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#16588 Add `mz_cluster_replica_frontiers` table](https://github.com/MaterializeInc/materialize/pull/16588) (@lluki)
* [ ] [#16696 mz: support secret commands in mz](https://github.com/MaterializeInc/materialize/pull/16696) (@sjwiesman)
* [ ] [#16736 release: bump to version v0.38.0-dev](https://github.com/MaterializeInc/materialize/pull/16736) (@jkosh44)
* [ ] [#16622 Replace `as` conversions with safe ones](https://github.com/MaterializeInc/materialize/pull/16622) (@petrosagg)
* [ ] [#16734 storage: reconcile rather than retract managed collections on boot](https://github.com/MaterializeInc/materialize/pull/16734) (@sploiselle)
* [ ] [#16658 Allow custom compaction windows on builtin tables](https://github.com/MaterializeInc/materialize/pull/16658) (@umanwizard)
* [ ] [#16717 build(deps): bump pg8000 from 1.29.3 to 1.29.4 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16717) (@dependabot[bot])
* [ ] [#16714 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.26.27 to 1.26.32 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16714) (@dependabot[bot])
* [ ] [#16749 catalog: Add missing is_retained_metrics_relation](https://github.com/MaterializeInc/materialize/pull/16749) (@lluki)
* [ ] [#16750 Add notifications for `release-blocker` issues to Slack](https://github.com/MaterializeInc/materialize/pull/16750) (@morsapaes)
* [ ] [#16748 bounded-memory test: Increase mem allowance for environmentd/computed](https://github.com/MaterializeInc/materialize/pull/16748) (@philip-stoev)
* [ ] [#16738 Doc: load gen source tick interval example](https://github.com/MaterializeInc/materialize/pull/16738) (@bobbyiliev)
* [ ] [#16751 adapter: fix parameter initialization regression](https://github.com/MaterializeInc/materialize/pull/16751) (@aalexandrov)
* [ ] [#16740 Remove `AS OF` from unsafe mode](https://github.com/MaterializeInc/materialize/pull/16740) (@umanwizard)
* [ ] [#16743 Revert "Merge pull request #14704 from danhhz/persist_empty_antichain"](https://github.com/MaterializeInc/materialize/pull/16743) (@benesch)
* [ ] [#16762 persist: add per-shard largest batch size metric](https://github.com/MaterializeInc/materialize/pull/16762) (@danhhz)
* [ ] [#16757 compute: fix mz_message_counts_received field order](https://github.com/MaterializeInc/materialize/pull/16757) (@teskje)
* [ ] [#16769 Unrevert "Merge pull request #14704 from danhhz/persist_empty_antichain" ](https://github.com/MaterializeInc/materialize/pull/16769) (@danhhz)
* [ ] [#15637 persist: inspect tool for printing contents of a batch part](https://github.com/MaterializeInc/materialize/pull/15637) (@pH14)
* [ ] [#16693 bump to rust 1.66](https://github.com/MaterializeInc/materialize/pull/16693) (@guswynn)
* [ ] [#16767 mzcompose: clear stale process metadata via tmpfs](https://github.com/MaterializeInc/materialize/pull/16767) (@benesch)
* [ ] [#16772 ci: Fortify cluster_replica_frontiers.td in Nightly](https://github.com/MaterializeInc/materialize/pull/16772) (@philip-stoev)
* [ ] [#16589 sql: function error handling improvements](https://github.com/MaterializeInc/materialize/pull/16589) (@sploiselle)
* [ ] [#16779 timely-util: define `ProbeNotify` trait](https://github.com/MaterializeInc/materialize/pull/16779) (@petrosagg)
* [ ] [#16777 Add an Active Replication reference document](https://github.com/MaterializeInc/materialize/pull/16777) (@vmarcos)
* [ ] [#16780 sqllogictest: fix merge skew prohibiting as conversions](https://github.com/MaterializeInc/materialize/pull/16780) (@sploiselle)
* [ ] [#16665 Normalize `LetRec` in expressions](https://github.com/MaterializeInc/materialize/pull/16665) (@frankmcsherry)
* [ ] [#16784 persist: fix bug causing accidentally serial compaction](https://github.com/MaterializeInc/materialize/pull/16784) (@danhhz)
* [ ] [#16646 docs/user: add docs for csr-over-ssh](https://github.com/MaterializeInc/materialize/pull/16646) (@guswynn)
* [ ] [#16775 doc/user: polish v0.37 release notes](https://github.com/MaterializeInc/materialize/pull/16775) (@morsapaes)
* [ ] [#16770 docs: fix grammar in README intro and About.](https://github.com/MaterializeInc/materialize/pull/16770) (@jstirnaman)
* [ ] [#16761 sql: add MVP for ScalarType::Range](https://github.com/MaterializeInc/materialize/pull/16761) (@sploiselle)
* [ ] [#16792 timely-util: fixes for ProbeNotify](https://github.com/MaterializeInc/materialize/pull/16792) (@teskje)
* [ ] [#16795 persist: move impls of admin and inspect cli into src/persist-client](https://github.com/MaterializeInc/materialize/pull/16795) (@danhhz)
* [ ] [#16802 deps: update URL to tokio-console fork](https://github.com/MaterializeInc/materialize/pull/16802) (@benesch)
* [ ] [#16756 mz cli: Fix the app-password list command](https://github.com/MaterializeInc/materialize/pull/16756) (@philip-stoev)
* [ ] [#16796 sql: Range type expansion](https://github.com/MaterializeInc/materialize/pull/16796) (@sploiselle)
* [ ] [#16787 Render some LIR::LetRec expressions](https://github.com/MaterializeInc/materialize/pull/16787) (@frankmcsherry)
* [ ] [#16809 test: fix `~_protobuf_roundtrip` stack overflows in `cargo test`](https://github.com/MaterializeInc/materialize/pull/16809) (@aalexandrov)
* [ ] [#16706 test: switch tests and dev env to use CockroachDB instead of Postgres](https://github.com/MaterializeInc/materialize/pull/16706) (@benesch)
* [ ] [#16810 sql: fix + test range ordering w/r/t NULL](https://github.com/MaterializeInc/materialize/pull/16810) (@sploiselle)
* [ ] [#16806 Follow up on TODOs](https://github.com/MaterializeInc/materialize/pull/16806) (@teskje)
* [ ] [#16811 doc/user: improve documentation on SQL client connections](https://github.com/MaterializeInc/materialize/pull/16811) (@morsapaes)
* [ ] [#16660 clusterd: unify storaged and computed](https://github.com/MaterializeInc/materialize/pull/16660) (@benesch)
* [ ] [#16720 build(deps): bump aws-smithy-types from 0.51.0 to 0.52.0](https://github.com/MaterializeInc/materialize/pull/16720) (@dependabot[bot])
* [ ] [#16713 environmentd: remove startup sysinfo message](https://github.com/MaterializeInc/materialize/pull/16713) (@benesch)
* [ ] [#16814 adapter,environmentd: move segment context fields to properties](https://github.com/MaterializeInc/materialize/pull/16814) (@benesch)
* [ ] [#16815 nexttest.toml: fix precedence override](https://github.com/MaterializeInc/materialize/pull/16815) (@benesch)
* [ ] [#16816 doc/developer: don't suggest binding port 8080 for Cockroach UI](https://github.com/MaterializeInc/materialize/pull/16816) (@benesch)
* [ ] [#16799 use annotations instead of a wrapper script for lint config](https://github.com/MaterializeInc/materialize/pull/16799) (@doy-materialize)
* [ ] [#16818 *: warn rather than deny lints](https://github.com/MaterializeInc/materialize/pull/16818) (@benesch)
* [ ] [#16833 doc/user: consolidate PostgreSQL guides](https://github.com/MaterializeInc/materialize/pull/16833) (@morsapaes)
* [ ] [#16831 build(deps): bump openssl-sys from 0.9.79 to 0.9.80](https://github.com/MaterializeInc/materialize/pull/16831) (@dependabot[bot])
* [ ] [#16830 build(deps): bump crossbeam-deque from 0.8.1 to 0.8.2](https://github.com/MaterializeInc/materialize/pull/16830) (@dependabot[bot])
* [ ] [#16829 build(deps): bump quote from 1.0.21 to 1.0.23](https://github.com/MaterializeInc/materialize/pull/16829) (@dependabot[bot])
* [ ] [#16826 build(deps): bump ryu from 1.0.11 to 1.0.12](https://github.com/MaterializeInc/materialize/pull/16826) (@dependabot[bot])
* [ ] [#16821 build(deps): bump boto3 from 1.26.32 to 1.26.37 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16821) (@dependabot[bot])
* [ ] [#16823 build(deps): bump isort from 5.11.3 to 5.11.4 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16823) (@dependabot[bot])
* [ ] [#16824 build(deps): bump types-requests from 2.28.11.5 to 2.28.11.7 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16824) (@dependabot[bot])
* [ ] [#16825 build(deps): bump semver from 3.0.0.dev3 to 3.0.0.dev4 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16825) (@dependabot[bot])
* [ ] [#16832 build(deps): bump tikv-jemalloc-sys from 0.4.2+5.2.1-patched.2 to 0.4.3+5.2.1-patched.2](https://github.com/MaterializeInc/materialize/pull/16832) (@dependabot[bot])
* [ ] [#16822 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.26.32 to 1.26.37 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16822) (@dependabot[bot])
* [ ] [#16837 build(deps): bump serde from 1.0.151 to 1.0.152](https://github.com/MaterializeInc/materialize/pull/16837) (@dependabot[bot])
* [ ] [#16841 build(deps): bump sysinfo from 0.27.0 to 0.27.1](https://github.com/MaterializeInc/materialize/pull/16841) (@dependabot[bot])
* [ ] [#16839 build(deps): bump parking_lot from 0.12.0 to 0.12.1](https://github.com/MaterializeInc/materialize/pull/16839) (@dependabot[bot])
* [ ] [#16838 build(deps): bump sysctl from 0.5.2 to 0.5.4](https://github.com/MaterializeInc/materialize/pull/16838) (@dependabot[bot])
* [ ] [#16840 build(deps): bump differential-dataflow from `93da913` to `c2e8fef`](https://github.com/MaterializeInc/materialize/pull/16840) (@dependabot[bot])
* [ ] [#16845 build(deps): bump predicates from 2.1.3 to 2.1.4](https://github.com/MaterializeInc/materialize/pull/16845) (@dependabot[bot])
* [ ] [#16844 build(deps): bump cc from 1.0.77 to 1.0.78](https://github.com/MaterializeInc/materialize/pull/16844) (@dependabot[bot])
* [ ] [#16846 build(deps): bump paste from 1.0.9 to 1.0.11](https://github.com/MaterializeInc/materialize/pull/16846) (@dependabot[bot])
* [ ] [#16849 doc/user: improve network security documentation](https://github.com/MaterializeInc/materialize/pull/16849) (@morsapaes)
* [ ] [#16834 test/cloudtest: various improvements](https://github.com/MaterializeInc/materialize/pull/16834) (@benesch)
* [ ] [#16852 compute: remove a panic from reduce implementation](https://github.com/MaterializeInc/materialize/pull/16852) (@benesch)
* [ ] [#16859 test/cloudtest: handle setup failures](https://github.com/MaterializeInc/materialize/pull/16859) (@benesch)
* [ ] [#16857 Simplify some code in the Testdrive parser](https://github.com/MaterializeInc/materialize/pull/16857) (@umanwizard)
* [ ] [#16851 Add `cpu_percent_normalized` to utilization tables](https://github.com/MaterializeInc/materialize/pull/16851) (@umanwizard)
* [ ] [#16861 Work around https://github.com/GuillaumeGomez/sysinfo/issues/898](https://github.com/MaterializeInc/materialize/pull/16861) (@umanwizard)
* [ ] [#16863 doc/developer: recommend `cargo install --locked`](https://github.com/MaterializeInc/materialize/pull/16863) (@benesch)
* [ ] [#16856 ci/test: re-enable all restart tests](https://github.com/MaterializeInc/materialize/pull/16856) (@benesch)
* [ ] [#16864 zippy: Add a secenario that restarts CRDB and Minio](https://github.com/MaterializeInc/materialize/pull/16864) (@philip-stoev)
* [ ] [#16817 orchestrator-process: export a prometheus service discovery configuration](https://github.com/MaterializeInc/materialize/pull/16817) (@benesch)
* [ ] [#16853 mz: cleanup header management](https://github.com/MaterializeInc/materialize/pull/16853) (@sjwiesman)
* [ ] [#16862 mz: Add the ability to store app passwords within the local keychain for more secure storage](https://github.com/MaterializeInc/materialize/pull/16862) (@sjwiesman)
* [ ] [#16768 Implement `SUBSCRIBE ... UP TO`](https://github.com/MaterializeInc/materialize/pull/16768) (@umanwizard)
* [ ] [#16867 bin/cargo-test: set COCKROACH_URL, not POSTGRES_URL](https://github.com/MaterializeInc/materialize/pull/16867) (@benesch)
* [ ] [#16870 Generalize f64_to_i64](https://github.com/MaterializeInc/materialize/pull/16870) (@umanwizard)
* [ ] [#16871 feature-benchmark: Adjust the ParallelDataflows scenario](https://github.com/MaterializeInc/materialize/pull/16871) (@philip-stoev)
* [ ] [#16855 storage: use critical since handle to hold back since of remap shard](https://github.com/MaterializeInc/materialize/pull/16855) (@aljoscha)
* [ ] [#16880 bin/sqllogictest: don't remove clusterd processes](https://github.com/MaterializeInc/materialize/pull/16880) (@benesch)
* [ ] [`c95971f1c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c95971f1c203087f68f14052d6e11deb788c510a) (@materializer)
* [ ] [`af6401686` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/af640168612b07e0c4f4ccb7de5885c8cf778881) (@materializer)
* [ ] [`0a0a69066` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0a0a6906687e31df038bcfd91cd11f016cfb92d6) (@materializer)
* [ ] [`ac90d8a67` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ac90d8a67b3c264e3a193147f99d8c3c42b95d36) (@materializer)
* [ ] [`5af5fbaee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5af5fbaeebe0e25c48da456eace2f3da6d43dd59) (@materializer)
* [ ] [`496ad1efe` nexttest.toml: bump the environmentd::test_pgtest timeout](https://github.com/MaterializeInc/materialize/commit/496ad1efe22becf1ae96330052b843afe2c07621) (@benesch)
* [ ] [`5f6eaa517` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5f6eaa5175d2fc98bac69cbfa8a7b5f628e20359) (@materializer)
* [ ] [`c1cacd024` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c1cacd024bcd3a9353d28cba3958e585bc30b588) (@materializer)
* [ ] [`6c1108030` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6c1108030414359320a5a3933c52520bd3019442) (@materializer)
* [ ] [`432a274a8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/432a274a8875f5b84be6e93e58ba67199296be58) (@materializer)
* [ ] [`0ec66cb9c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0ec66cb9ce0b620a732ff562cd39afdc0122f78c) (@materializer)
* [ ] [`b93b83266` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b93b832664b0283798b373bb836c4cc7a682db22) (@materializer)
* [ ] [`f08cf34d3` release: bump to version v0.38.0](https://github.com/MaterializeInc/materialize/commit/f08cf34d3425fbdea203e489a1e2b9caac5c4fb5) (@umanwizard)

**Comment by umanwizard** [comment]
all but mine lgtm

**Comment by danhhz** [comment]
@umanwizard's unreviewed commits LGTM
