### ISSUE TITLE
[Epic] Stabilize `WITH MUTUALLY RECURSIVE`

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#17012]
### Product Outcome

Materialize currently supports recursive queries, although it's guarded behind the unsafe flag. We should work towards stabilizing the feature so that we can test it, potentially with customer involvement.

This is a continuation of #11176.

### Specification

Stabilize the support for recursive queries. This specifically means:
* Enable optimizer transformations in the presence of recursive queries.
* Add testing for recursive queries, including malformed/infinite recursions. For example, divergent dataflows cannot be canceled at the moment (#16800). Edit: This is fixed now.
* Create documentation and marketing material to explain how to use recursive queries and what benefit they can bring.

### Design

Design doc PR: #17820 ([rendered version](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20230223_stabilize_with_mutually_recursive.md)).

### Required Issues (Must Haves)

- [x] #17911
- [x] #17912
- [x] #17913
- [x] #17914
- [x] #18123
- [x] #17915
- [x] #17921
- [x] #16800
- [x] #18501
- [x] #18362
- [x] https://github.com/MaterializeInc/materialize/issues/18889
- [x] #17916
- [x] https://github.com/MaterializeInc/materialize/issues/18949
- [x] https://github.com/MaterializeInc/materialize/issues/14711
- [x] https://github.com/MaterializeInc/materialize/issues/18832
- [x] https://github.com/MaterializeInc/materialize/issues/19483

### Blockers

* [x] #18656
* [x] #18688
* [x] #18759 

### Discretionary Issues (Nice To Haves)

- [x] #17917
- [x] #18160

### Follow-up Issues

- [ ] #18553 (which will improve [#18170](18170) and other transforms)
- [ ] #19012
- [ ] #18022
- [ ] https://github.com/MaterializeInc/materialize/issues/19334

### Success metric

We measure success in the number of queries that use `WITH MUTUALLY RECURSIVE`:
* as the absolute number,
* and the number relative to all queries/views.

**Comment by frankmcsherry** [comment]
An addition to the specification: `WITH MUTUALLY RECURSIVE` doesn't currently work either nested or in sequence in the same dataflow (it panics, because the current implementation cannot support this). It shouldn't be that much work for me to fix this, but it involves using a new timestamp type (and works in prototype in the DD repo, but surely needs some love porting it to MZ).

**Comment by frankmcsherry** [comment]
I'm pretty sure we will be able to do this, and if that turns out to be correct I think there is a simplicity win in terms of not having to explain / check / test the corner cases. It was not obvious that we would be able to do this at the time the doc was written, and ruling it out seemed best at that time.

**Comment by frankmcsherry** [comment]
> I'm pretty sure we will be able to do this, 

I'm upgrading this to "we have merged the code that does this".

**Comment by aalexandrov** [comment]
Thanks. This is already reflected as done [in the design doc](https://github.com/aalexandrov/materialize/blob/issue_17012/doc/developer/design/20230223_stabilize_with_mutually_recursive.md#explanation).

**Comment by aalexandrov** [comment]
Closing the epic. I'll try to do a final pass on the design doc to reflect more precisely what we managed to do and what is left as future work.
