### ISSUE TITLE
[Tracker] Rendering: Analyses and potential improvements

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#17049]
This is a tracking issue for analyses of our rendering strategies as well as improvement efforts to be spun off as separate epics.

## Top-K
* [X] Monotonic top-k
    * #16698 
* [ ] Non-monotonic top-k
    * [ ] https://github.com/MaterializeInc/materialize/issues/14444
    * [ ] TODO: new issue to investigate strategies to safely reduce depth of non-monotonic top-k stacks, e.g., by squaring fan-out as we move down the hierarchy.
    * [ ] TODO: add more long-term thinking / musing issue to consider to add to DD an arrangement type that works as a top-k pre-filter by shuffling by row, then computing top-k by key. With an appropriate closure parameter, this addition to DD might allow us to compute other algebraic aggregates in a more skew-resilient fashion? 

## Reduce

* [ ] https://materializeinc.slack.com/archives/C02PPB50ZHS/p1673027583623019
* [ ] https://materializeinc.slack.com/archives/C02PPB50ZHS/p1673109203160559
* [ ] TODO

## MFPs
* [ ] https://github.com/MaterializeInc/materialize/issues/14513
* [ ] TODO

## Joins
* [ ] https://github.com/MaterializeInc/materialize/issues/7282
* [ ] https://github.com/MaterializeInc/materialize/issues/15595
* [ ] https://github.com/MaterializeInc/materialize/issues/10022
* [ ] https://github.com/MaterializeInc/materialize/issues/16239
* [ ] TODO
 
## Threshold

TODO

**Comment by bosconi** [comment]
@antiguru worth reviewing at some point to see what items are still relevant?
