### ISSUE TITLE
release: v0.39.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17052]
The following PRs in [`v0.39.0`](https://github.com/MaterializeInc/materialize/tree/v0.39.0) require review:
* [ ] [#16886 materialized: shore up the Docker image](https://github.com/MaterializeInc/materialize/pull/16886) (@benesch)
* [ ] [#16897 doc/user: minor correction to SUBSCRIBE documentation](https://github.com/MaterializeInc/materialize/pull/16897) (@morsapaes)
* [ ] [#16901 testdrive: Fortify system-functions.td](https://github.com/MaterializeInc/materialize/pull/16901) (@philip-stoev)
* [ ] [#16921 orchestrator-process: remove debugging println](https://github.com/MaterializeInc/materialize/pull/16921) (@benesch)
* [ ] [#16928 testdrive: Fortify csv-sources.td](https://github.com/MaterializeInc/materialize/pull/16928) (@philip-stoev)
* [ ] [#16905 zippy: Use a separate storage clusterd](https://github.com/MaterializeInc/materialize/pull/16905) (@philip-stoev)
* [ ] [#16950 upgrade: Fix the upgrade tests for 0.38](https://github.com/MaterializeInc/materialize/pull/16950) (@philip-stoev)
* [ ] [#16952 mzcompose: Protect --persist-blob-url from the shell](https://github.com/MaterializeInc/materialize/pull/16952) (@philip-stoev)
* [ ] [#16953 Fix a lint issue for links in doc comments](https://github.com/MaterializeInc/materialize/pull/16953) (@ggevay)
* [ ] [#16966 add the redirect.](https://github.com/MaterializeInc/materialize/pull/16966) (@nisarhassan12)
* [ ] [#17017 doc/user: minor fix in get started guide](https://github.com/MaterializeInc/materialize/pull/17017) (@morsapaes)
* [ ] [#17020 .github: add checkbox to PR template about cloud changes](https://github.com/MaterializeInc/materialize/pull/17020) (@benesch)
* [ ] [#17036 deps: upgrade to cargo-hakari 0.9.18](https://github.com/MaterializeInc/materialize/pull/17036) (@benesch)
* [ ] [#17042 cloudtest: Set --aws-privatelink-availability-zones via an env variable](https://github.com/MaterializeInc/materialize/pull/17042) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`6d85bf180` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6d85bf18026dcd441b493bf32f76c1caa9906cb6) (@materializer)
* [ ] [`62d21f2b6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/62d21f2b66cddef16b29afaaae429e7054384555) (@materializer)
* [ ] [`b3159ce00` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b3159ce00337d7ed3b3fcbe5d20294281ed0b325) (@materializer)
* [ ] [`10a8e599a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/10a8e599ab83ff468b26042bad94839361509545) (@materializer)
* [ ] [`89cac8b92` release: bump to version v0.39.0-dev](https://github.com/MaterializeInc/materialize/commit/89cac8b9248bed7ae87eb73c658071cae6e15b02) (@umanwizard)
* [ ] [`b0daa917f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b0daa917f68c60ccc3a1ba0b3946b6dd250b0e79) (@materializer)
* [ ] [`2887e638f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/2887e638f9531f1e46dc32ebb4d4e42ee288dbbf) (@materializer)
* [ ] [`d755ec399` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d755ec3997a4a3152dd2cc8c0ffa9af069318e27) (@materializer)
* [ ] [`ed7e9a996` Coord: Use ts oracle to schedule storage usage (#17000)](https://github.com/MaterializeInc/materialize/commit/ed7e9a996b9056f90644cfaca66cc3fe7e3cc7e5) (@web-flow)
* [ ] [`b1f16869f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b1f16869fb21edf19fa40a119092c4ef12e18d08) (@materializer)
* [ ] [`e60b7e238` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e60b7e238c8021db21a96bddef0b0e13d59ccf8d) (@materializer)
* [ ] [`34341f495` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/34341f49513467e44d64845338a4890921fda645) (@materializer)
* [ ] [`d9eff2de3` release: bump to version v0.39.0](https://github.com/MaterializeInc/materialize/commit/d9eff2de3a326424ca3ba982f54baac314850679) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#16877 *: remove some unnecessary mz_persist_types::Codec impls](https://github.com/MaterializeInc/materialize/pull/16877) (@danhhz)
* [ ] [#16886 materialized: shore up the Docker image](https://github.com/MaterializeInc/materialize/pull/16886) (@benesch)
* [ ] [#16887 sql: implement numrange](https://github.com/MaterializeInc/materialize/pull/16887) (@sploiselle)
* [ ] [#16897 doc/user: minor correction to SUBSCRIBE documentation](https://github.com/MaterializeInc/materialize/pull/16897) (@morsapaes)
* [ ] [#16898 fix nesting issues inside ul.](https://github.com/MaterializeInc/materialize/pull/16898) (@nisarhassan12)
* [ ] [#16835 Add `dataflow_id` to invalid accumulation messages](https://github.com/MaterializeInc/materialize/pull/16835) (@vmarcos)
* [ ] [#16899 Fix run's invocation of sqllogictest](https://github.com/MaterializeInc/materialize/pull/16899) (@tokenrove)
* [ ] [#16676 storage: migrate remap shards to Timely-native format](https://github.com/MaterializeInc/materialize/pull/16676) (@sploiselle)
* [ ] [#16894 build(deps): bump nom from 7.1.0 to 7.1.2](https://github.com/MaterializeInc/materialize/pull/16894) (@dependabot[bot])
* [ ] [#16866 materialized: document the Docker image](https://github.com/MaterializeInc/materialize/pull/16866) (@benesch)
* [ ] [#16891 build(deps): bump pydantic from 1.10.1 to 1.10.4 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16891) (@dependabot[bot])
* [ ] [#16889 build(deps): bump types-prettytable from 3.4.2.2 to 3.4.2.3 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16889) (@dependabot[bot])
* [ ] [#16892 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.26.37 to 1.26.41 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/16892) (@dependabot[bot])
* [ ] [#16895 build(deps): bump syn from 1.0.105 to 1.0.107](https://github.com/MaterializeInc/materialize/pull/16895) (@dependabot[bot])
* [ ] [#16901 testdrive: Fortify system-functions.td](https://github.com/MaterializeInc/materialize/pull/16901) (@philip-stoev)
* [ ] [#16904 zippy: Disable sql.stats.forecasts.enabled in CRDB](https://github.com/MaterializeInc/materialize/pull/16904) (@philip-stoev)
* [ ] [#16664 metrics: add jemalloc stats](https://github.com/MaterializeInc/materialize/pull/16664) (@lluki)
* [ ] [#16873 persist: small cleanups](https://github.com/MaterializeInc/materialize/pull/16873) (@danhhz)
* [ ] [#16888 mzcompose: remove dead code from Materialized service](https://github.com/MaterializeInc/materialize/pull/16888) (@benesch)
* [ ] [#16907 bump sysinfo version and fix how we refresh CPU info in the process orchestrator](https://github.com/MaterializeInc/materialize/pull/16907) (@umanwizard)
* [ ] [#16900 sql: implement misc.range functions](https://github.com/MaterializeInc/materialize/pull/16900) (@sploiselle)
* [ ] [#16909 `as`-removal (chapter 1)](https://github.com/MaterializeInc/materialize/pull/16909) (@umanwizard)
* [ ] [#16766 Remove the legacy-named status tables](https://github.com/MaterializeInc/materialize/pull/16766) (@bkirwi)
* [ ] [#16918 sql: Use consistent col ordering for natural join](https://github.com/MaterializeInc/materialize/pull/16918) (@jkosh44)
* [ ] [#16206 [source/sink] Record drops in the status log](https://github.com/MaterializeInc/materialize/pull/16206) (@bkirwi)
* [ ] [#16922 sql: fix aliasing of output of NATURAL joins](https://github.com/MaterializeInc/materialize/pull/16922) (@benesch)
* [ ] [#16921 orchestrator-process: remove debugging println](https://github.com/MaterializeInc/materialize/pull/16921) (@benesch)
* [ ] [#16925 sql: temporarily allow "mzcompose" pseudo cloud provider](https://github.com/MaterializeInc/materialize/pull/16925) (@benesch)
* [ ] [#16928 testdrive: Fortify csv-sources.td](https://github.com/MaterializeInc/materialize/pull/16928) (@philip-stoev)
* [ ] [#16905 zippy: Use a separate storage clusterd](https://github.com/MaterializeInc/materialize/pull/16905) (@philip-stoev)
* [ ] [#16903 UpdateConfiguration compute command](https://github.com/MaterializeInc/materialize/pull/16903) (@teskje)
* [ ] [#16929 Update nightly Rust version for CI](https://github.com/MaterializeInc/materialize/pull/16929) (@teskje)
* [ ] [#16785 compute: configure DD's idle_merge_effort](https://github.com/MaterializeInc/materialize/pull/16785) (@teskje)
* [ ] [#16926 mzcompose: Allow environmentd v0.38.0 to start](https://github.com/MaterializeInc/materialize/pull/16926) (@philip-stoev)
* [ ] [#16807 persist_source: fix memory leak in in-flight parts tracking](https://github.com/MaterializeInc/materialize/pull/16807) (@teskje)
* [ ] [#16919 doc/user: Fix function indexing logic in docs](https://github.com/MaterializeInc/materialize/pull/16919) (@ruf-io)
* [ ] [#16915 Delete billing demo](https://github.com/MaterializeInc/materialize/pull/16915) (@umanwizard)
* [ ] [#16934 ci-builder: mount the host kubeconfig](https://github.com/MaterializeInc/materialize/pull/16934) (@benesch)
* [ ] [#16654 [persist] Always perform routine maintenance](https://github.com/MaterializeInc/materialize/pull/16654) (@bkirwi)
* [ ] [#16788 storage: implement simple version of souce-specific statistics](https://github.com/MaterializeInc/materialize/pull/16788) (@guswynn)
* [ ] [#16940 persist: keep track of per-shard successful cmds in metrics](https://github.com/MaterializeInc/materialize/pull/16940) (@danhhz)
* [ ] [#16737 Add trace IDs to SQL statements as notices, behind a session var](https://github.com/MaterializeInc/materialize/pull/16737) (@chaas)
* [ ] [#16945 Expecting elements takes closure](https://github.com/MaterializeInc/materialize/pull/16945) (@antiguru)
* [ ] [#16924 environmentd: add clusters and replicas by size to telemetry](https://github.com/MaterializeInc/materialize/pull/16924) (@benesch)
* [ ] [#16947 doc/user: polish v0.38 release notes](https://github.com/MaterializeInc/materialize/pull/16947) (@morsapaes)
* [ ] [#16950 upgrade: Fix the upgrade tests for 0.38](https://github.com/MaterializeInc/materialize/pull/16950) (@philip-stoev)
* [ ] [#16952 mzcompose: Protect --persist-blob-url from the shell](https://github.com/MaterializeInc/materialize/pull/16952) (@philip-stoev)
* [ ] [#16953 Fix a lint issue for links in doc comments](https://github.com/MaterializeInc/materialize/pull/16953) (@ggevay)
* [ ] [#16955 Partition `LetRec` correctly](https://github.com/MaterializeInc/materialize/pull/16955) (@frankmcsherry)
* [ ] [#16602 persist: refactor batch builder: merge user + compaction write paths](https://github.com/MaterializeInc/materialize/pull/16602) (@pH14)
* [ ] [#16959 dbt-materialize: release v1.3.3](https://github.com/MaterializeInc/materialize/pull/16959) (@morsapaes)
* [ ] [#16808 Render cleanup](https://github.com/MaterializeInc/materialize/pull/16808) (@frankmcsherry)
* [ ] [#16948 environmentd: use auth message instead of headers for websocket](https://github.com/MaterializeInc/materialize/pull/16948) (@mjibson)
* [ ] [#16923 adapter: implement mz_internal.mz_dependencies](https://github.com/MaterializeInc/materialize/pull/16923) (@guswynn)
* [ ] [#16966 add the redirect.](https://github.com/MaterializeInc/materialize/pull/16966) (@nisarhassan12)
* [ ] [#16967 adapter: delay creating a temp user schema](https://github.com/MaterializeInc/materialize/pull/16967) (@mjibson)
* [ ] [#16949 adapter: allow pgwire to connect before coord acknowledges](https://github.com/MaterializeInc/materialize/pull/16949) (@mjibson)
* [ ] [#16804 Add validation of AWS PrivateLink connection object's availability zones](https://github.com/MaterializeInc/materialize/pull/16804) (@chaas)
* [ ] [#16973 misc: auto create db for bin/sqllogictest](https://github.com/MaterializeInc/materialize/pull/16973) (@mjibson)
* [ ] [#16935 ci-builder: remove KUBECONFIG from Dockerfile](https://github.com/MaterializeInc/materialize/pull/16935) (@benesch)
* [ ] [#16991 environmentd: deflake test_cancel_long_running_query](https://github.com/MaterializeInc/materialize/pull/16991) (@mjibson)
* [ ] [#16975 adapter: use oracle ts for storage collection time](https://github.com/MaterializeInc/materialize/pull/16975) (@mjibson)
* [ ] [#16908 IDLE ARRANGEMENT MERGE EFFORT option](https://github.com/MaterializeInc/materialize/pull/16908) (@teskje)
* [ ] [#16996 compute: remove unused persist_sink scope argument](https://github.com/MaterializeInc/materialize/pull/16996) (@teskje)
* [ ] [#16976 mzcompose: avoid shell when passing commands](https://github.com/MaterializeInc/materialize/pull/16976) (@benesch)
* [ ] [#16813 compute: intra-ts thinning for monotonic topk](https://github.com/MaterializeInc/materialize/pull/16813) (@petrosagg)
* [ ] [#16932 storage: various timestamp related changes](https://github.com/MaterializeInc/materialize/pull/16932) (@petrosagg)
* [ ] [#16994 Extract count from each `Accum`](https://github.com/MaterializeInc/materialize/pull/16994) (@frankmcsherry)
* [ ] [#17009 Avoid clones in subscribe sinks](https://github.com/MaterializeInc/materialize/pull/17009) (@antiguru)
* [ ] [#16971 Enable new-style Rust debug symbols](https://github.com/MaterializeInc/materialize/pull/16971) (@umanwizard)
* [ ] [#17008 Drain input in subscribe that is past its `UP TO`](https://github.com/MaterializeInc/materialize/pull/17008) (@umanwizard)
* [ ] [#16957 Pre-tidy planner output](https://github.com/MaterializeInc/materialize/pull/16957) (@frankmcsherry)
* [ ] [#17005 adapter: use timestamp oracle in bootstrapping](https://github.com/MaterializeInc/materialize/pull/17005) (@benesch)
* [ ] [#17010 Fix path to gen-lints.py in comments](https://github.com/MaterializeInc/materialize/pull/17010) (@umanwizard)
* [ ] [#17017 doc/user: minor fix in get started guide](https://github.com/MaterializeInc/materialize/pull/17017) (@morsapaes)
* [ ] [#17018 Update jemalloc to 0.5.0](https://github.com/MaterializeInc/materialize/pull/17018) (@antiguru)
* [ ] [#16938 adapter: change audit log timestamp to use oracle](https://github.com/MaterializeInc/materialize/pull/16938) (@mjibson)
* [ ] [#17020 .github: add checkbox to PR template about cloud changes](https://github.com/MaterializeInc/materialize/pull/17020) (@benesch)
* [ ] [#16689 persist-client: use `ListenEvent` for `Subscribe::next`](https://github.com/MaterializeInc/materialize/pull/16689) (@petrosagg)
* [ ] [#17019 alloc: extract jemalloc config into new crate](https://github.com/MaterializeInc/materialize/pull/17019) (@benesch)
* [ ] [#16992 environmentd: remove unused TLS modes](https://github.com/MaterializeInc/materialize/pull/16992) (@mjibson)
* [ ] [#17024 adapter: expose Materialize version in mz_version parameter](https://github.com/MaterializeInc/materialize/pull/17024) (@benesch)
* [ ] [#17025 environmentd: add a readiness probe](https://github.com/MaterializeInc/materialize/pull/17025) (@benesch)
* [ ] [#17036 deps: upgrade to cargo-hakari 0.9.18](https://github.com/MaterializeInc/materialize/pull/17036) (@benesch)
* [ ] [#17022 environmentd: support bearer auth over websocket](https://github.com/MaterializeInc/materialize/pull/17022) (@mjibson)
* [ ] [#17023 cloudtest,mzcompose: generalize external service configuration](https://github.com/MaterializeInc/materialize/pull/17023) (@benesch)
* [ ] [#17042 cloudtest: Set --aws-privatelink-availability-zones via an env variable](https://github.com/MaterializeInc/materialize/pull/17042) (@philip-stoev)
* [ ] [#17016 Revert "persist: refactor batch builder: merge user + compaction write paths"](https://github.com/MaterializeInc/materialize/pull/17016) (@pH14)
* [ ] [#16962 Doc: add Upstash Kafka guide](https://github.com/MaterializeInc/materialize/pull/16962) (@bobbyiliev)
* [ ] [#17026 adapter: don't record storage usage for dropped shards](https://github.com/MaterializeInc/materialize/pull/17026) (@benesch)
* [ ] [#16819 Cluster unification part ii](https://github.com/MaterializeInc/materialize/pull/16819) (@benesch)
* [ ] [#17050 stash: add logging for unexpected lower](https://github.com/MaterializeInc/materialize/pull/17050) (@mjibson)
* [ ] [#17015 storage: fix storage statistics test flake](https://github.com/MaterializeInc/materialize/pull/17015) (@guswynn)
* [ ] [`6d85bf180` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6d85bf18026dcd441b493bf32f76c1caa9906cb6) (@materializer)
* [ ] [`62d21f2b6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/62d21f2b66cddef16b29afaaae429e7054384555) (@materializer)
* [ ] [`b3159ce00` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b3159ce00337d7ed3b3fcbe5d20294281ed0b325) (@materializer)
* [ ] [`10a8e599a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/10a8e599ab83ff468b26042bad94839361509545) (@materializer)
* [ ] [`89cac8b92` release: bump to version v0.39.0-dev](https://github.com/MaterializeInc/materialize/commit/89cac8b9248bed7ae87eb73c658071cae6e15b02) (@umanwizard)
* [ ] [`b0daa917f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b0daa917f68c60ccc3a1ba0b3946b6dd250b0e79) (@materializer)
* [ ] [`2887e638f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/2887e638f9531f1e46dc32ebb4d4e42ee288dbbf) (@materializer)
* [ ] [`d755ec399` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d755ec3997a4a3152dd2cc8c0ffa9af069318e27) (@materializer)
* [ ] [`ed7e9a996` Coord: Use ts oracle to schedule storage usage (#17000)](https://github.com/MaterializeInc/materialize/commit/ed7e9a996b9056f90644cfaca66cc3fe7e3cc7e5) (@web-flow)
* [ ] [`b1f16869f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b1f16869fb21edf19fa40a119092c4ef12e18d08) (@materializer)
* [ ] [`e60b7e238` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e60b7e238c8021db21a96bddef0b0e13d59ccf8d) (@materializer)
* [ ] [`34341f495` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/34341f49513467e44d64845338a4890921fda645) (@materializer)
* [ ] [`d9eff2de3` release: bump to version v0.39.0](https://github.com/MaterializeInc/materialize/commit/d9eff2de3a326424ca3ba982f54baac314850679) (@guswynn)

**Comment by antifuchs** [comment]
[d9eff2de3 release: bump to version v0.39.0](https://github.com/MaterializeInc/materialize/commit/d9eff2de3a326424ca3ba982f54baac314850679) looks good to me!

**Comment by guswynn** [comment]
Rest of the commit lgmt
