### ISSUE TITLE
[Epic] storage: UPSERT spill-to-disk

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#17067]
To limit the memory-usage of `UPSERT` (and `DEBEZIUM`) sources, we have decided to move the upsert state map onto a disk. See the design doc in notion for more details.

This issue now tracks the implementation of this feature at a granular level.

[Design doc](https://www.notion.so/materialize/Spill-to-disk-for-UPSERT-a9bbe06e80374528a259635488a544cd?pvs=4)

Update: This comment is being used as the tracking list for the work required on the storage-side to support `UPSERT` with spill-to-disk semantics. Note also that the cloud-side work is tracked here: https://github.com/MaterializeInc/cloud/issues/6095

On the storage side, the following is required:

- [x] Implement a `RocksDB` wrapper (probably its own crate, `mz-rocksdb`, that follows the basic outline of the implementation here: https://github.com/MaterializeInc/materialize/blob/main/src/storage/examples/upsert_open_loop.rs#L1193-L1198
  - [x] Basic implementation https://github.com/MaterializeInc/materialize/pull/18770
  - [ ] Add basic statistics 
    - [x] At least we need histograms or batch read and write latencies
    - [ ] Support rocksdb-reported metrics. Currently the rust bindings make this quite onerous
  - [ ] Determine how we handle errors from RocksDB. I imagine we consider IO errors to be fatal (restart the source), but these _must_ be reported to the user. Note also that RocksDB has retryable errors.
- [ ] Add disk usage statistics
  - [ ] Populate `disk_usage` in `mz_cluster_replica_metrics` (see https://materializeinc.slack.com/archives/CM7ATT65S/p1681759177004099)
  - [x] https://github.com/MaterializeInc/materialize/pull/19044 
  - [ ] Ensure we have `disk_usage` stats in grafana, per-pod, and dashboards.
- [ ] *Core implementation*: Connect the rocksdb map to the upsert operator.
  - [x] https://github.com/MaterializeInc/materialize/pull/18878
  - [x] https://github.com/MaterializeInc/materialize/pull/18810
  - [x] https://github.com/MaterializeInc/materialize/pull/19049
  - [x] Connect the rocksdb `UpsertState` implementation to the `upsert` operator.
  - [x] Bound the memory usage of `upsert` rehydration
  - [x] Add a way to configure the batch size
- [ ] Testing
   - [x] Move `upsert` tests to a separate mzcompose from `testdrive`, and run them against both the memory and rocksdb implementations.
   - [ ] Add basic `KafkaUpsertUnique`-like benchmark for the rocksdb implementation.
   - [ ] https://github.com/MaterializeInc/materialize/issues/19245
- [ ] Error handling
   - [x] Cleanup rocksdb directory more aggressively (see https://github.com/MaterializeInc/materialize/commit/fafa08ef516acfb55bc178f55f2b558acf9586da)
   - [ ] Gracefully restart in the face of io errors
- [ ] Evaluation phase
  - [ ] Test a relatively large upsert source in the `spill2disk` personal stack
     - [ ] Determine if we need to implement backpressure
     - [ ] Get some rough numbers on rehydration time
- [ ] Rollout
  - [ ] Rollout to staging. 
  - [ ] Choose a customer to test the MVP against.
    - [ ] Determine the space amplification we see in practice, tune rocksdb based on this
  - [ ] Rollout to all of production 	
  - [ ] Add Release Qualification test.

**Comment by rjnn** [comment]
It would be great to get size estimates for the work involved in both (1) and (2). Both seem viable at first glance, and (1) has a bunch of product complexity. For (1) we'd have to:
* Attach instance stores to clusters
* Expose the attached disk sizes, metrics, etc.
* Price those, perhaps have them as an option with separate pricing, since we wouldn't want to have them attached to each cluster (or do we because compute spill to disk is a thing too?)

Snowflake does (2) for compute as well. There's a good reason for this: there's no additional dimension of pricing for instance storage in any situation.

There's more product work here than at first appearance cc @heeringa @benesch @crohorner

**Comment by danhhz** [comment]
fwiw, I think any shippable version of (2) also requires spill to disk, the logic just moves inside persist. so this list of things probably has to happen in any world that we do this. however, I think neither really requires that they are _persistent_ disks attached, which makes things a lot simpler

**Comment by aljoscha** [comment]
I've shown these notes to enough people since last week, so might be worth posting here. (Didn't plan doing that this fast, but this seems to be picking up steam quicker than I thought. 😅)

---

- Seems there are three basic shapes for a solution:
  - Use persist as the cache. When we need to re-read sth, go back to persist. This _would_ work, but the persist API is not at all set up for this, and it would be horribly slow.
  - Use a "third system" to offload state, think Redis or similar. This seems hard from an operational perspective.
  - Spill to disk, which would require the pods we run on to have disk that we can use. The good thing is that the disk can be ephemeral, that is we don't need them to survive restarts. We need them purely for spilling our in-memory-state and will rehydrate that from persist on restart.
     - This last one can take different shapes yet again:
       - Custom solution of spill-to-disk.
       - Use something like RocksDB/sqlite.
       - Use swap.
       - Rely on compute to solve out-of-core arrangements, and use an arrangement for UPSERT state. Compute will not do this anytime soon, _plus_ arrangements don't really work well for the access pattern we have with UPSERT.
- Moritz: Compute will not do out-of-core in the near future.
- If we do this, need to add tracking, so that we can figure out how much out-of-core UPSERT sources are used vs. regular UPSERT sources.
- Moritzt suggested: more specific "cluster sizes", that encode disk requirements. Those would then be good for scheduling large UPSERT sources. And we would make it the users problem to figure out what kind of resources they need. Spitballing: "2xsmall-with-disk" (naming very much tbd)
- I don't much like introducing this many knobs for users. Maybe we can dynamically mount disk space when users schedule an UPSERT source?

**Comment by danhhz** [comment]
> Use persist as the cache. When we need to re-read sth, go back to persist. This would work, but the persist API is not at all set up for this, and it would be horribly slow.

fwiw, I've always assumed persist would need to support some sort of indexed access at some point, so the issue here isn't the persist API (it would just be novel work that would need to be scheduled) so much as any _performant_ impl of this in persist would require ephemeral disks for caching

**Comment by aljoscha** [comment]
> fwiw, I've always assumed persist would need to support some sort of indexed access at some point, so the issue here isn't the persist API (it would just be novel work that would need to be scheduled) so much as any _performant_ impl of this in persist would likely require ephemeral disks for caching

Yes! Sorry, this whole block of comments is quite rough/slapdash. 😅 I (handwavingly) meant roughly the same thing as you with that. And I agree that it's not work that's currently scheduled/planned.

It's good that you highlight the need for ephemeral disk caching! I think the "reasonable" solutions require some sort of disk cache, which further reinforces my believe that we need to look into how we can swing that operationally. 

Also, sth that wasn't clear above: I'd favour (in the near/mid timeframe) a solution that is custom to storage, and that uses ephemeral on-disk caching, _without_ introducing too many new knobs for users. Under the assumption that we still want to improve the memory footprint of UPSERT sources.

We might be tempted to introduce syntax for specifying that an UPSERT source should use disk, and be spillable. But that would introduce more knobs. We _could_ just say that UPSERT sources always spill to disk. This would mean throughput is potentially lower for all UPSERT sources, but we keep our DDL simple, and we can improve things down the road. Plus, even with spillable state we would likely still keep some in-memory cache.

**Comment by aljoscha** [comment]
> Hoist upsert operator into compute

Forwarding some comments from slack:
 - I think this is problematic because it makes all readers/multiple replicas more expensive.
 - A nice property of current collections/persist shards is that compute doesn't have to know what's writing to them. All it needs to know is the schema, really. Moving UPSERT logic into compute would break this nice separation.

**Comment by benesch** [comment]
> > fwiw, I've always assumed persist would need to support some sort of indexed access at some point, so the issue here isn't the persist API (it would just be novel work that would need to be scheduled) so much as any _performant_ impl of this in persist would likely require ephemeral disks for caching
> 
> Yes! Sorry, this whole block of comments is quite rough/slapdash. 😅 I (handwavingly) meant roughly the same thing as you with that. And I agree that it's not work that's currently scheduled/planned.
> 
> It's good that you highlight the need for ephemeral disk caching! I think the "reasonable" solutions require some sort of disk cache, which further reinforces my believe that we need to look into how we can swing that operationally.
> 
> Also, sth that wasn't clear above: I'd favour (in the near/mid timeframe) a solution that is custom to storage, and that uses ephemeral on-disk caching, _without_ introducing too many new knobs for users. Under the assumption that we still want to improve the memory footprint of UPSERT sources.
> 
> We might be tempted to introduce syntax for specifying that an UPSERT source should use disk, and be spillable. But that would introduce more knobs. We _could_ just say that UPSERT sources always spill to disk. This would mean throughput is potentially lower for all UPSERT sources, but we keep our DDL simple, and we can improve things down the road. Plus, even with spillable state we would likely still keep some in-memory cache.

I like this plan, personally. At the very least, it feels like disk should be opt out, not opt in.

> Moritzt suggested: more specific "cluster sizes", that encode disk requirements. Those would then be good for scheduling large UPSERT sources. And we would make it the users problem to figure out what kind of resources they need. Spitballing: "2xsmall-with-disk" (naming very much tbd)
> I don't much like introducing this many knobs for users. Maybe we can dynamically mount disk space when users schedule an UPSERT source?

Agreed on not introducing this many knobs! I think it is more defensible to introduce a knob for clusters that support swap than it is to introduce a knob for clusters that have attached EBS volumes that `ENVELOPE UPSERT` sources can take advantage of.

I think we could pretty easily say that every cluster gets an attached ephemeral EBS volume with 10x (?) as much storage as there is memory. So a 16GB memory cluster gets 160GB of attached disk, which would cost us an additional $12/mo (seems reasonable).

**Comment by guswynn** [comment]
Update based on @aljoscha and I starting to investigate this problem more thoroughly:

The general consensus is that we are going to heavily investigate spilling the upsert map onto disk, as opposed to using out-of-core arrangements, or hoisting the operator into compute. This appear to produce the best outcome for users, in comparison to the level of effort is required for implementation.

https://github.com/MaterializeInc/cloud/issues/5909 thoroughly discusses the tradeoffs of EBS vs instance storage, and it appears that generally the cloud team is comfortable with the maintenance of either, with a preference towards EBS. EBS is well-known to have bad random-access performance, which may perform unacceptably poorly for the upsert usecase.

We plan on benchmarking the various options, in multiple ways. First, we will produce a representative _open-loop_ benchmark, which will involve us measuring the latency of producing retractions and updates in the face of increasing load. This will not use materialize, and instead will implement a very basic upsert-style operator, and drive it using a small timely example or something similar.

We can run this benchmark against a in-memory hashmap, EBS, and instance storage (using rocksdb and sqlite, if we are interested in the difference). Its possible that EBS and instance storage perform similarly (or EBS is much slower, but still significantly faster than our estimated maximum throughput into persist), and we can decide the outcome after this benchmark, but we may decide to benchmark using an actual, materialize UPSERT source if we need more data (this requires significantly more setup)

**Comment by rjnn** [comment]
When you benchmark ebs, do take care to note the IOPS pricing of each ebs configuration you test as one can get great ebs numbers, but by throwing dollars at it, which negates the entire point of the exercise. I’m very skeptical that ebs is better than instance store for this use case on a price/performance metric.

**Comment by benesch** [comment]
https://www.speedb.io looks really interesting to evaluate too. Claims to be a faster RocksDB.

**Comment by sjwiesman** [comment]
When testing RocksDB, I expect you to find the best performance with a RocksDB instance per upsert operator. However, you should investigate creating a global [Env](https://docs.rs/rocksdb/latest/rocksdb/struct.Env.html) per clusterd process. It will allow you to control resource usage at a global level, and create a shared set of background processes for compaction. 

Speedb seems to have similar configurations.

**Comment by guswynn** [comment]
@benesch Apparently speedb's rust bindings are basically a copy of the rocksdb ones: https://docs.rs/speedb/latest/speedb/

**Comment by guswynn** [comment]
I am going to use this issue to capture the steps we need to take to enable this feature. Its unclear whether or not an explicit design document is needed yet.

Note also that the cloud-side work is tracked here: https://github.com/MaterializeInc/cloud/issues/6095

On the storage side, the following is required:

- [ ] Implement a `RocksDB` wrapper (probably its own crate, `mz-rocksdb`, that follows the basic outline of the implementation here: https://github.com/MaterializeInc/materialize/blob/main/src/storage/examples/upsert_open_loop.rs#L1193-L1198
  - [ ] Add statistics 
    - [ ] At least we need histograms or batch read and write latencies
    - [ ] Support rocksdb-reported metrics. Currently the rust bindings make this quite onerous
  - [ ] Determine how we handle errors from RocksDB. I imagine we consider IO errors to be fatal (restart the source), but these _must_ be reported to the user
- [ ] Ensure we have dashboards for storage usage
- [ ] Ensure we have disk usage and limits in a system table (ideally `mz_cluster_replica_metrics` if we can handle the schema migration)
- [ ] Connect the rocksdb map (optionally) to the upsert operator. The upsert operator is already `async`
  - [ ] This must be controlled with a LD flag. 
  - [ ] Its undetermined whether or not we will require an explicit `USE STORAGE` clause in the `UPSERT` source creation. Leaning towards yes.
- [ ] Choose a customer to test the MVP against.
  - [ ] Determine the space amplification we see in practice, tune rocksdb based on this
- [ ] Rollout to all of production

**Comment by benesch** [comment]
> Its unclear whether or not an explicit design document is needed yet.

A feature of this magnitude and complexity absolutely needs a design document! It'd be great to cowrite it with the cloud team and cover the change in instance types, and what the interface between cloud and the database will be (where will the scratch space be mounted, for example?).

**Comment by aljoscha** [comment]
> * Its undetermined whether or not we will require an explicit `USE STORAGE` clause in the `UPSERT` source creation. Leaning towards yes.

I'm leaning towards _no additional knobs_, meaning this will be completely transparent and only controllable by us via a LD flag. Which jibes with the _no additional replica SKUs_ thinking.

**Comment by guswynn** [comment]
@aljoscha we don't yet support per-source LD configs, do you think we will need that for this feature?

**Comment by aljoscha** [comment]
> @aljoscha we don't yet support per-source LD configs, do you think we will need that for this feature?

We might! I think you mentioned storing a list of IDs that should use disk somewhere?
