### ISSUE TITLE
[Epic] Adapter: Real-time Recency Production Readiness

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#17130]
### Product Outcome

- Broadly: Uphold Materialize's correctness guarantees.
- Specifically: Release Realtime Recency into production.

### Specification
High level RTR spec, ported from https://github.com/MaterializeInc/materialize/issues/17148: 

Real-time recency is a property not only needed for Jepsen testing, but also for our consistency guarantees. This property relies on Storage providing a hook for each class of source for which we provide this property, and for Adapter to correctly invoke the hook and use the result for timestamp determination. It may be no more complicated than that, though. As a subtle property, the issues requires ownership to design and document why we have this property.

On SELECT commands, Materialize is in principle able to acquire the currentmost data of upstream sources, and ensure that any response reflects at least all of that data. This involves an interaction with the upstream source, but it ensures that the response to the SELECT command has a "real-time recency" guarantee: the answer is correct for a real-time moment greater than that at which the SELECT command was entered.

This is less than strict serializability for Materialize, as we are unable to ensure that all events have orders that respect their real-time orders. In particular, we are unable to ensure that we correctly order events in unrelated external sources, and misordering them relative to their real-time order would be a violation of strict serializability. This property is meant to be the appropriate weakening of strict serializability vis-a-vis this fundamental ambiguity.

### Design
- 

### Documentation
- 

### Issues

```[tasklist]
### Must Have
- [ ] Review initial MVP and add optimizations
- [ ] Conduct E2E, multi-source testing
- [ ] https://github.com/MaterializeInc/materialize/issues/17148

```

```[tasklist]
### Nice to Have
- [ ] Add a draft title or issue reference here
```

_No response_

### Blockers

- [ ] https://github.com/MaterializeInc/materialize/issues/16060

**Comment by benesch** [comment]
Closing due to staleness. Lets use https://github.com/MaterializeInc/materialize/issues/16060 as the main tracking point for this work.
