### ISSUE TITLE
release: v0.40.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17184]
The following PRs in [`v0.40.0`](https://github.com/MaterializeInc/materialize/tree/v0.40.0) require review:
* [ ] [#17063 ci: Remove mentions of Postgres in CI steps that use Cockroach](https://github.com/MaterializeInc/materialize/pull/17063) (@philip-stoev)
* [ ] [#17065 cloudtest: Call the Postgres server 'postgres' rather than 'postgres-…](https://github.com/MaterializeInc/materialize/pull/17065) (@philip-stoev)
* [ ] [#17090 testdrive: Do not run linked-clusters.td with more than 1 replica](https://github.com/MaterializeInc/materialize/pull/17090) (@philip-stoev)
* [ ] [#17092 feature-benchmark: Allow running individual scenarios](https://github.com/MaterializeInc/materialize/pull/17092) (@philip-stoev)
* [ ] [#17120 test/upgrade: fix cluster replica sizing](https://github.com/MaterializeInc/materialize/pull/17120) (@benesch)
* [ ] [#16936 doc/user: document mz_dependencies](https://github.com/MaterializeInc/materialize/pull/16936) (@guswynn)
* [ ] [#17045 test/upgrade: use standalone CockroachDB](https://github.com/MaterializeInc/materialize/pull/17045) (@benesch)
* [ ] [#17162 materialized: move embedded CockroachDB store to mzdata directory](https://github.com/MaterializeInc/materialize/pull/17162) (@benesch)
* [ ] [#17173 doc/user: wrap up #17141](https://github.com/MaterializeInc/materialize/pull/17173) (@morsapaes)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`7ef011613` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7ef011613b25acf447eb1e6df72e303ca944684b) (@materializer)
* [ ] [`d3f0a971c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d3f0a971cc5528c859b6a49b9b751f74905db3e2) (@materializer)
* [ ] [`90f8e070e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/90f8e070e0911cd887e70cc7cb06098e7918865e) (@materializer)
* [ ] [`fbcb1d463` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fbcb1d463e378e7c615ba3b104cb6bd3458848f8) (@materializer)
* [ ] [`ad06bd5da` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ad06bd5daa7d88baa2924212593c56f6dd5d031b) (@materializer)
* [ ] [`9178e16f5` doc/developer: document the existence of CODEOWNERS](https://github.com/MaterializeInc/materialize/commit/9178e16f5627a2bb07c0203a6834cc6bd62db7b7) (@benesch)
* [ ] [`13271a287` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/13271a287f9921a0b3d2f80f6de47bb85bc3a2ce) (@materializer)
* [ ] [`8abdc9e7f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8abdc9e7f933ccd59285ff9978fa399cd4322664) (@materializer)
* [ ] [`c73d5f696` sql: remove `qgm_optimizations` from `OptimizerConfig`](https://github.com/MaterializeInc/materialize/commit/c73d5f6967de5362af7d6f75c6c593a6e300efa3) (@aalexandrov)
* [ ] [`f285d2d5f` sql: remove `qgm_optimizations` from PlanContext](https://github.com/MaterializeInc/materialize/commit/f285d2d5fdef00a9ca98a653b27717362c76f6c3) (@aalexandrov)
* [ ] [`047ab2e6f` adapter: remove `qgm_optimizations` session variable](https://github.com/MaterializeInc/materialize/commit/047ab2e6f56c6fcfa94238e12b4a13600519ee3a) (@aalexandrov)
* [ ] [`8d6ad365d` sql: remove `ExplainStage::(Optimized)QueryGraph`](https://github.com/MaterializeInc/materialize/commit/8d6ad365d4b64cecd3205e6fc840a0004b1267d5) (@aalexandrov)
* [ ] [`6852884d0` sql: remove QGM code and tests](https://github.com/MaterializeInc/materialize/commit/6852884d0fdb41d5b8847a70537730f39039b2a7) (@aalexandrov)
* [ ] [`bd18e2bbe` doc/developer: remove comment from 101 the `Query Compilation 101` doc](https://github.com/MaterializeInc/materialize/commit/bd18e2bbe35524a3591761716fe483e19caf4ea7) (@aalexandrov)
* [ ] [`bd246685b` Merge pull request #17139 from aalexandrov/remove_qgm](https://github.com/MaterializeInc/materialize/commit/bd246685bade627ca84cab99e3747bc181241174) (@web-flow)
* [ ] [`18f68b16f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/18f68b16fc589dccc57066486562c1b6fd353c13) (@materializer)
* [ ] [`39d16ac55` release: bump to version v0.40.0](https://github.com/MaterializeInc/materialize/commit/39d16ac55af2707b6db975858fab52955473fd92) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#17043 doc/user: document `IDLE ARRANGEMENT MERGE EFFORT` replica option](https://github.com/MaterializeInc/materialize/pull/17043) (@teskje)
* [ ] [#17046 compute-client: protocol module](https://github.com/MaterializeInc/materialize/pull/17046) (@teskje)
* [ ] [#17041 test: remove idle_arrangement_merge_effort.td](https://github.com/MaterializeInc/materialize/pull/17041) (@teskje)
* [ ] [#17053 release: bump to version v0.40.0-dev](https://github.com/MaterializeInc/materialize/pull/17053) (@guswynn)
* [ ] [#17033 build(deps): bump boto3 from 1.26.37 to 1.26.45 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/17033) (@dependabot[bot])
* [ ] [#16968 *: remove is_cockroach special casing](https://github.com/MaterializeInc/materialize/pull/16968) (@mjibson)
* [ ] [#16798 compute: wire up persist_source flow control](https://github.com/MaterializeInc/materialize/pull/16798) (@teskje)
* [ ] [#17063 ci: Remove mentions of Postgres in CI steps that use Cockroach](https://github.com/MaterializeInc/materialize/pull/17063) (@philip-stoev)
* [ ] [#17065 cloudtest: Call the Postgres server 'postgres' rather than 'postgres-…](https://github.com/MaterializeInc/materialize/pull/17065) (@philip-stoev)
* [ ] [#17069 Replace some uses of HashMap with BTreeMap](https://github.com/MaterializeInc/materialize/pull/17069) (@teskje)
* [ ] [#17066 mz: make URL in docstring a markdown link](https://github.com/MaterializeInc/materialize/pull/17066) (@teskje)
* [ ] [#17070 adapter: use `environment` context for LaunchDarkly sync](https://github.com/MaterializeInc/materialize/pull/17070) (@aalexandrov)
* [ ] [#17068 compute-client: add protocol documentation](https://github.com/MaterializeInc/materialize/pull/17068) (@teskje)
* [ ] [#17062 adapter: drop linked cluster if sink fails to create](https://github.com/MaterializeInc/materialize/pull/17062) (@benesch)
* [ ] [#16977 storage: add prometheus stats for all user-facing source stats](https://github.com/MaterializeInc/materialize/pull/16977) (@guswynn)
* [ ] [#17060 adapter: fix storage collection timestamp semantics](https://github.com/MaterializeInc/materialize/pull/17060) (@benesch)
* [ ] [#16606 persist: tag each version of state with a strictly increasing walltime](https://github.com/MaterializeInc/materialize/pull/16606) (@danhhz)
* [ ] [#17085 adapter: de-mut readonly get_local_read_ts](https://github.com/MaterializeInc/materialize/pull/17085) (@mjibson)
* [ ] [#17090 testdrive: Do not run linked-clusters.td with more than 1 replica](https://github.com/MaterializeInc/materialize/pull/17090) (@philip-stoev)
* [ ] [#17089 persist: Convert the multi-node Maelstrom CI job to Cockroach](https://github.com/MaterializeInc/materialize/pull/17089) (@philip-stoev)
* [ ] [#17092 feature-benchmark: Allow running individual scenarios](https://github.com/MaterializeInc/materialize/pull/17092) (@philip-stoev)
* [ ] [#17084 make code links distinguishable.](https://github.com/MaterializeInc/materialize/pull/17084) (@nisarhassan12)
* [ ] [#17094 compute history: fix UpdateConfiguration reduction](https://github.com/MaterializeInc/materialize/pull/17094) (@teskje)
* [ ] [#17095 compute: Move compute metrics to mz-compute crate](https://github.com/MaterializeInc/materialize/pull/17095) (@lluki)
* [ ] [#16969 [persist] Track live/current diff/blob metrics during GC](https://github.com/MaterializeInc/materialize/pull/16969) (@bkirwi)
* [ ] [#17048 Initial version of COMPUTE Layer Q&A](https://github.com/MaterializeInc/materialize/pull/17048) (@vmarcos)
* [ ] [#17039 Design document for improvements to monotonic top-k rendering](https://github.com/MaterializeInc/materialize/pull/17039) (@vmarcos)
* [ ] [#17098 environmentd: filter subsources out of `active_sources` field in telemetry](https://github.com/MaterializeInc/materialize/pull/17098) (@benesch)
* [ ] [#17086 [persist] Concurrent deletes during persist GC](https://github.com/MaterializeInc/materialize/pull/17086) (@bkirwi)
* [ ] [#17108 persist: retry Blob::open and Consensus::open in maelstrom](https://github.com/MaterializeInc/materialize/pull/17108) (@danhhz)
* [ ] [#17107 Revert "[persist] Always perform routine maintenance (#16654)"](https://github.com/MaterializeInc/materialize/pull/17107) (@guswynn)
* [ ] [#17076 Dynamic persist configuration (part 1)](https://github.com/MaterializeInc/materialize/pull/17076) (@teskje)
* [ ] [#17093 ore: add a tracing layer for LaunchDarkly monitoring](https://github.com/MaterializeInc/materialize/pull/17093) (@aalexandrov)
* [ ] [#17112 doc/user: push down cast to query for a more clear example](https://github.com/MaterializeInc/materialize/pull/17112) (@joacoc)
* [ ] [#17104 adapter: Send notice for unimplemented isolation levels](https://github.com/MaterializeInc/materialize/pull/17104) (@jkosh44)
* [ ] [#17087 doc/user: polish v0.39 release notes](https://github.com/MaterializeInc/materialize/pull/17087) (@morsapaes)
* [ ] [#17113 Fix lowertest parse error msgs](https://github.com/MaterializeInc/materialize/pull/17113) (@ggevay)
* [ ] [#17115 test: Fix flaky storage usage collection test](https://github.com/MaterializeInc/materialize/pull/17115) (@jkosh44)
* [ ] [#17111 environmentd: add connection count by type to telemetry](https://github.com/MaterializeInc/materialize/pull/17111) (@benesch)
* [ ] [#17120 test/upgrade: fix cluster replica sizing](https://github.com/MaterializeInc/materialize/pull/17120) (@benesch)
* [ ] [#17006 Support using AZ-specific services when consuming a privatelink connection in kafka](https://github.com/MaterializeInc/materialize/pull/17006) (@chaas)
* [ ] [#17117 test: Fix flaky retry test](https://github.com/MaterializeInc/materialize/pull/17117) (@jkosh44)
* [ ] [#16937 doc/user: document mz_internal.mz_source_statistics](https://github.com/MaterializeInc/materialize/pull/16937) (@guswynn)
* [ ] [#16936 doc/user: document mz_dependencies](https://github.com/MaterializeInc/materialize/pull/16936) (@guswynn)
* [ ] [#17106 *: remove Stash trait in favor of a single impl](https://github.com/MaterializeInc/materialize/pull/17106) (@mjibson)
* [ ] [#17138 zippy: Add a scenario using the 'latest' Cockroach Docker image](https://github.com/MaterializeInc/materialize/pull/17138) (@philip-stoev)
* [ ] [#17137 optimizer: replace more Hash collections with BTree equivalents](https://github.com/MaterializeInc/materialize/pull/17137) (@teskje)
* [ ] [#17121 Split literal constraints detection from `CanonicalizeMfp`.](https://github.com/MaterializeInc/materialize/pull/17121) (@ggevay)
* [ ] [#17141 Fix AWS service names in aws-msk.md](https://github.com/MaterializeInc/materialize/pull/17141) (@sthm)
* [ ] [#17128 *: fix nightly unused-deps job](https://github.com/MaterializeInc/materialize/pull/17128) (@danhhz)
* [ ] [#17127 adapter: Pull RTR off the main coord thread](https://github.com/MaterializeInc/materialize/pull/17127) (@jkosh44)
* [ ] [#17149 Remove wrapping token in Rc, irrelevant now](https://github.com/MaterializeInc/materialize/pull/17149) (@antiguru)
* [ ] [#17153 test/cluster: fix a flaky part of the remote storage test](https://github.com/MaterializeInc/materialize/pull/17153) (@guswynn)
* [ ] [#17110 .github: add a CODEOWNERS file to the repository](https://github.com/MaterializeInc/materialize/pull/17110) (@benesch)
* [ ] [#17045 test/upgrade: use standalone CockroachDB](https://github.com/MaterializeInc/materialize/pull/17045) (@benesch)
* [ ] [#17162 materialized: move embedded CockroachDB store to mzdata directory](https://github.com/MaterializeInc/materialize/pull/17162) (@benesch)
* [ ] [#17097 Fix stack overflow in planning set expressions](https://github.com/MaterializeInc/materialize/pull/17097) (@tokenrove)
* [ ] [#16727 ci: Capture dmesg output for the host machine](https://github.com/MaterializeInc/materialize/pull/16727) (@philip-stoev)
* [ ] [#17172 Kafka matrix update versions](https://github.com/MaterializeInc/materialize/pull/17172) (@philip-stoev)
* [ ] [#17173 doc/user: wrap up #17141](https://github.com/MaterializeInc/materialize/pull/17173) (@morsapaes)
* [ ] [#17143 make the toc scrollable independent of the page.](https://github.com/MaterializeInc/materialize/pull/17143) (@nisarhassan12)
* [ ] [#17133 doc/user: replace mz_now() with now() in the TTL pattern](https://github.com/MaterializeInc/materialize/pull/17133) (@joacoc)
* [ ] [#17119 adapter: remove `window_functions` feature flag](https://github.com/MaterializeInc/materialize/pull/17119) (@aalexandrov)
* [ ] [#17179 test/restart: fortify stash test](https://github.com/MaterializeInc/materialize/pull/17179) (@benesch)
* [ ] [#17182 Allow mz_introspection user to query any cluster's system catalog](https://github.com/MaterializeInc/materialize/pull/17182) (@chaas)
* [ ] [#17164 build(deps): bump pytest from 7.2.0 to 7.2.1 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/17164) (@dependabot[bot])
* [ ] [#17163 build(deps): bump setuptools from 65.6.3 to 65.7.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/17163) (@dependabot[bot])
* [ ] [`7ef011613` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7ef011613b25acf447eb1e6df72e303ca944684b) (@materializer)
* [ ] [`d3f0a971c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d3f0a971cc5528c859b6a49b9b751f74905db3e2) (@materializer)
* [ ] [`90f8e070e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/90f8e070e0911cd887e70cc7cb06098e7918865e) (@materializer)
* [ ] [`fbcb1d463` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fbcb1d463e378e7c615ba3b104cb6bd3458848f8) (@materializer)
* [ ] [`ad06bd5da` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ad06bd5daa7d88baa2924212593c56f6dd5d031b) (@materializer)
* [ ] [`9178e16f5` doc/developer: document the existence of CODEOWNERS](https://github.com/MaterializeInc/materialize/commit/9178e16f5627a2bb07c0203a6834cc6bd62db7b7) (@benesch)
* [ ] [`13271a287` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/13271a287f9921a0b3d2f80f6de47bb85bc3a2ce) (@materializer)
* [ ] [`8abdc9e7f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8abdc9e7f933ccd59285ff9978fa399cd4322664) (@materializer)
* [ ] [`c73d5f696` sql: remove `qgm_optimizations` from `OptimizerConfig`](https://github.com/MaterializeInc/materialize/commit/c73d5f6967de5362af7d6f75c6c593a6e300efa3) (@aalexandrov)
* [ ] [`f285d2d5f` sql: remove `qgm_optimizations` from PlanContext](https://github.com/MaterializeInc/materialize/commit/f285d2d5fdef00a9ca98a653b27717362c76f6c3) (@aalexandrov)
* [ ] [`047ab2e6f` adapter: remove `qgm_optimizations` session variable](https://github.com/MaterializeInc/materialize/commit/047ab2e6f56c6fcfa94238e12b4a13600519ee3a) (@aalexandrov)
* [ ] [`8d6ad365d` sql: remove `ExplainStage::(Optimized)QueryGraph`](https://github.com/MaterializeInc/materialize/commit/8d6ad365d4b64cecd3205e6fc840a0004b1267d5) (@aalexandrov)
* [ ] [`6852884d0` sql: remove QGM code and tests](https://github.com/MaterializeInc/materialize/commit/6852884d0fdb41d5b8847a70537730f39039b2a7) (@aalexandrov)
* [ ] [`bd18e2bbe` doc/developer: remove comment from 101 the `Query Compilation 101` doc](https://github.com/MaterializeInc/materialize/commit/bd18e2bbe35524a3591761716fe483e19caf4ea7) (@aalexandrov)
* [ ] [`bd246685b` Merge pull request #17139 from aalexandrov/remove_qgm](https://github.com/MaterializeInc/materialize/commit/bd246685bade627ca84cab99e3747bc181241174) (@web-flow)
* [ ] [`18f68b16f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/18f68b16fc589dccc57066486562c1b6fd353c13) (@materializer)
* [ ] [`39d16ac55` release: bump to version v0.40.0](https://github.com/MaterializeInc/materialize/commit/39d16ac55af2707b6db975858fab52955473fd92) (@benesch)

**Comment by benesch** [comment]
The commits that are not mine LGTM.

**Comment by guswynn** [comment]
@benesch's commits LGTM
