### ISSUE TITLE
release: v0.41.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17288]
The following PRs in [`v0.41.0`](https://github.com/MaterializeInc/materialize/tree/v0.41.0) require review:
* [ ] [#17175 zippy: Add a no-killings Release Qualification Scenario](https://github.com/MaterializeInc/materialize/pull/17175) (@philip-stoev)
* [ ] [#17195 persist: Adjust the bounded-memory test to reality](https://github.com/MaterializeInc/materialize/pull/17195) (@philip-stoev)
* [ ] [#17196 zippy: Increase the timeout used when waiting for Mz to restart](https://github.com/MaterializeInc/materialize/pull/17196) (@philip-stoev)
* [ ] [#16914 Make the docs mobile responsive](https://github.com/MaterializeInc/materialize/pull/16914) (@nisarhassan12)
* [ ] [#17265 adapter: separate cluster [replica] ID allocation from creation](https://github.com/MaterializeInc/materialize/pull/17265) (@benesch)
* [ ] [#17256 Cluster unification part 3.6](https://github.com/MaterializeInc/materialize/pull/17256) (@guswynn)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`3db5c773c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3db5c773caccfa72c1d1c4b974af2acd2536bc10) (@materializer)
* [ ] [`1477aca27` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1477aca27434a42878fb273811bb08bb15957758) (@materializer)
* [ ] [`c41530e40` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c41530e407894e7a29749d173d96e9e822019966) (@materializer)
* [ ] [`0ebfd8440` adapter: fix merge skew](https://github.com/MaterializeInc/materialize/commit/0ebfd844070e29884ed3259b1ef77658e98ea2e2) (@benesch)
* [ ] [`281e18ab8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/281e18ab8f45df3f392a93145fc28162f62031c7) (@materializer)
* [ ] [`ccf6a04a0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ccf6a04a0b7dedbc1f63da4b3eb7b30323625afe) (@materializer)
* [ ] [`fb6a2c8b5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fb6a2c8b5850f65562e12626a96fc302e49937df) (@materializer)
* [ ] [`3044338c7` release: bump to version v0.41.0](https://github.com/MaterializeInc/materialize/commit/3044338c7f9c3408ca9671c9d3bd98f234b5a9bf) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#17056 Specialize Top1Monoid for thread-local aggregation](https://github.com/MaterializeInc/materialize/pull/17056) (@antiguru)
* [ ] [#17160 stash: don't set zone in readonly](https://github.com/MaterializeInc/materialize/pull/17160) (@mjibson)
* [ ] [#17175 zippy: Add a no-killings Release Qualification Scenario](https://github.com/MaterializeInc/materialize/pull/17175) (@philip-stoev)
* [ ] [#17186 ci: Collect additional debugging information](https://github.com/MaterializeInc/materialize/pull/17186) (@philip-stoev)
* [ ] [#17188 sql: remove unused `typemap_rev` dependency](https://github.com/MaterializeInc/materialize/pull/17188) (@aalexandrov)
* [ ] [#16998 Propagate debug_name instead of dataflow_id in reduce rendering](https://github.com/MaterializeInc/materialize/pull/16998) (@vmarcos)
* [ ] [#16533 doc/user: Init data apps quickstart](https://github.com/MaterializeInc/materialize/pull/16533) (@joacoc)
* [ ] [#16803 Docs: Streaming BI Quickstart](https://github.com/MaterializeInc/materialize/pull/16803) (@dehume)
* [ ] [#17071 Doc: add RDS to privatelink docs](https://github.com/MaterializeInc/materialize/pull/17071) (@bobbyiliev)
* [ ] [#17185 release: bump to version v0.41.0-dev](https://github.com/MaterializeInc/materialize/pull/17185) (@benesch)
* [ ] [#17174 slt: make persisted introspection configurable](https://github.com/MaterializeInc/materialize/pull/17174) (@teskje)
* [ ] [#17146 storage: perform some parts of create_collections concurrently](https://github.com/MaterializeInc/materialize/pull/17146) (@guswynn)
* [ ] [#17201 bump kubernetes api version to 1.24](https://github.com/MaterializeInc/materialize/pull/17201) (@doy-materialize)
* [ ] [#17183 [sources/sinks] Healthcheck cleanup](https://github.com/MaterializeInc/materialize/pull/17183) (@bkirwi)
* [ ] [#17195 persist: Adjust the bounded-memory test to reality](https://github.com/MaterializeInc/materialize/pull/17195) (@philip-stoev)
* [ ] [#17196 zippy: Increase the timeout used when waiting for Mz to restart](https://github.com/MaterializeInc/materialize/pull/17196) (@philip-stoev)
* [ ] [#16914 Make the docs mobile responsive](https://github.com/MaterializeInc/materialize/pull/16914) (@nisarhassan12)
* [ ] [#17116 persist: batch builder refactor take two](https://github.com/MaterializeInc/materialize/pull/17116) (@pH14)
* [ ] [#16644 Docs: quick starts abandoned cart](https://github.com/MaterializeInc/materialize/pull/16644) (@bobbyiliev)
* [ ] [#16958 storage: in workers, add internal control dataflow](https://github.com/MaterializeInc/materialize/pull/16958) (@aljoscha)
* [ ] [#16964 Form regions around nontrivial dataflows](https://github.com/MaterializeInc/materialize/pull/16964) (@frankmcsherry)
* [ ] [#17147 persist: ensure shard source emits full batches](https://github.com/MaterializeInc/materialize/pull/17147) (@pH14)
* [ ] [#17197 dbt-materialize: handle absence of cluster `default` on connection](https://github.com/MaterializeInc/materialize/pull/17197) (@morsapaes)
* [ ] [#17217 dbt-materialize: release v1.3.4](https://github.com/MaterializeInc/materialize/pull/17217) (@morsapaes)
* [ ] [#17205 doc/user: polish v0.40 release notes](https://github.com/MaterializeInc/materialize/pull/17205) (@morsapaes)
* [ ] [#17190 SUBSCRIBE on arranged introspection sources](https://github.com/MaterializeInc/materialize/pull/17190) (@teskje)
* [ ] [#17222 storage: reduce the size of DataflowError](https://github.com/MaterializeInc/materialize/pull/17222) (@teskje)
* [ ] [#17125 storage: add `mz_sink_statistics`](https://github.com/MaterializeInc/materialize/pull/17125) (@guswynn)
* [ ] [#17226 storage: remove remap migration code](https://github.com/MaterializeInc/materialize/pull/17226) (@sploiselle)
* [ ] [#17193 persist/storage/compute: add required schema parameter to persist handle constructors, and populate it correctly](https://github.com/MaterializeInc/materialize/pull/17193) (@guswynn)
* [ ] [#17001 Merge fusion operators into one transform](https://github.com/MaterializeInc/materialize/pull/17001) (@frankmcsherry)
* [ ] [#16883 persist: understand structure of persisted data](https://github.com/MaterializeInc/materialize/pull/16883) (@danhhz)
* [ ] [#17231 Docs: SSH tunnel guide -- restrict firewall to mz ips](https://github.com/MaterializeInc/materialize/pull/17231) (@chuck-alt-delete)
* [ ] [#17234 adapter: expose postgres source replication slots](https://github.com/MaterializeInc/materialize/pull/17234) (@benesch)
* [ ] [#17159 Cluster unification, step 3.1](https://github.com/MaterializeInc/materialize/pull/17159) (@benesch)
* [ ] [#17204 Doc: adjust streaming analytics demo](https://github.com/MaterializeInc/materialize/pull/17204) (@bobbyiliev)
* [ ] [#17220 nightly: Add a canary deploy to the staging cloud (take two)](https://github.com/MaterializeInc/materialize/pull/17220) (@philip-stoev)
* [ ] [#17237 adapter: factor out replica creation method](https://github.com/MaterializeInc/materialize/pull/17237) (@benesch)
* [ ] [#17241 doc/user: tweak dbt integration guide for multi-output sources](https://github.com/MaterializeInc/materialize/pull/17241) (@morsapaes)
* [ ] [#17250 adapter: Add hint for statement timeout](https://github.com/MaterializeInc/materialize/pull/17250) (@jkosh44)
* [ ] [#17251 Shrink `correction` buffer when appropriate](https://github.com/MaterializeInc/materialize/pull/17251) (@frankmcsherry)
* [ ] [#17255 persist: remove some short-lived allocations under Trace::push_batch](https://github.com/MaterializeInc/materialize/pull/17255) (@danhhz)
* [ ] [#17244 adapter: move drop cluster code to `catalog_transact`](https://github.com/MaterializeInc/materialize/pull/17244) (@benesch)
* [ ] [#17247 Cluster unification, part 3.4](https://github.com/MaterializeInc/materialize/pull/17247) (@benesch)
* [ ] [#17211 storage: don't use `halt!` in sinks](https://github.com/MaterializeInc/materialize/pull/17211) (@aljoscha)
* [ ] [#17265 adapter: separate cluster [replica] ID allocation from creation](https://github.com/MaterializeInc/materialize/pull/17265) (@benesch)
* [ ] [#17256 Cluster unification part 3.6](https://github.com/MaterializeInc/materialize/pull/17256) (@guswynn)
* [ ] [#17268 storage: fix creation of storage-worker-internal control flow](https://github.com/MaterializeInc/materialize/pull/17268) (@aljoscha)
* [ ] [#17273 compute-controller: cluster unification follow-ups](https://github.com/MaterializeInc/materialize/pull/17273) (@teskje)
* [ ] [#17272 adapter: allow all replica sizes in `Catalog::open`](https://github.com/MaterializeInc/materialize/pull/17272) (@aalexandrov)
* [ ] [#17269 Migration to remove legacy orchestrator services](https://github.com/MaterializeInc/materialize/pull/17269) (@teskje)
* [ ] [#17276 test: fix storage-clusters test](https://github.com/MaterializeInc/materialize/pull/17276) (@jkosh44)
* [ ] [#16502 update description of CREATE DEFAULT INDEX](https://github.com/MaterializeInc/materialize/pull/16502) (@chuck-alt-delete)
* [ ] [#17192 [persist] Admin GC command](https://github.com/MaterializeInc/materialize/pull/17192) (@bkirwi)
* [ ] [#17278 compute-client: remove outdated panic](https://github.com/MaterializeInc/materialize/pull/17278) (@teskje)
* [ ] [#17285 adapter: disallow queries on storage clusters](https://github.com/MaterializeInc/materialize/pull/17285) (@benesch)
* [ ] [#17286 controller: set storage workers appropriately](https://github.com/MaterializeInc/materialize/pull/17286) (@benesch)
* [ ] [#17283 adapter,storage: add envelope_type column to mz_sinks](https://github.com/MaterializeInc/materialize/pull/17283) (@aljoscha)
* [ ] [`3db5c773c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3db5c773caccfa72c1d1c4b974af2acd2536bc10) (@materializer)
* [ ] [`1477aca27` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1477aca27434a42878fb273811bb08bb15957758) (@materializer)
* [ ] [`c41530e40` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c41530e407894e7a29749d173d96e9e822019966) (@materializer)
* [ ] [`0ebfd8440` adapter: fix merge skew](https://github.com/MaterializeInc/materialize/commit/0ebfd844070e29884ed3259b1ef77658e98ea2e2) (@benesch)
* [ ] [`281e18ab8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/281e18ab8f45df3f392a93145fc28162f62031c7) (@materializer)
* [ ] [`ccf6a04a0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ccf6a04a0b7dedbc1f63da4b3eb7b30323625afe) (@materializer)
* [ ] [`fb6a2c8b5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fb6a2c8b5850f65562e12626a96fc302e49937df) (@materializer)
* [ ] [`3044338c7` release: bump to version v0.41.0](https://github.com/MaterializeInc/materialize/commit/3044338c7f9c3408ca9671c9d3bd98f234b5a9bf) (@guswynn)

**Comment by guswynn** [comment]
All the commits that aren't mine look good!

**Comment by benesch** [comment]
The PRs and commits that are not mine LGTM.
