### ISSUE TITLE
dbt-materialize: add `cluster` config to source and sink materialization logic

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#17313]
### Feature request

Materialize v0.41.0 will ship with the new cluster unification logic ([Cloud #4929](https://github.com/MaterializeInc/cloud/issues/4929)), which allows users to assign sources and sinks to a specified cluster. This requires us to allow the [`cluster` config option](https://materialize.com/docs/integrations/dbt/#clusters) in the `dbt-materialize` adapter also for the source and sink materializations.

## TODO
- [ ] Change the logic in the adapter
- [ ] Update the [dbt integration guide](https://materialize.com/docs/integrations/dbt/#configuration)
- [ ] Update the [dbt documentation](https://docs.getdbt.com/reference/resource-configs/materialize-configs)

**Comment by morsapaes** [comment]
In this release, users are required to specify either the `IN CLUSTER` clause or the `SIZE` option. This requirement will be removed in a future release:

> Rather than erroring on a `CREATE SOURCE` or `CREATE SINK` without either `IN CLUSTER` or a `SIZE` specified, create the source or sink in the currently active cluster, to match the behavior of `CREATE INDEX` and `CREATE MATERIALIZED VIEW`.

**Comment by morsapaes** [comment]
I overlooked that the `source` and `sink` custom materializations use the `materialize__create_arbitrary_object(sql)` method, which simply runs the provided DDL statement. This makes it pretty awkward to support the cluster configuration, as you can't do something like:

```sql
{% macro materialize__create_materialized_view_as(relation, sql) -%}
  {%- set cluster = config.get('cluster', target.cluster) -%}

  create materialized view {{ relation }}
  {% if cluster %}
    in cluster {{ cluster }}
  {% endif %}
  as (
    {{ sql }}
  );
{%- endmacro %}
```

I dislike not providing the option because it's inconsistent with the other materializations, but I don't see a non-horrible and non-redundant (since users will have to specify `IN CLUSTER` in the SQL statement to bind it to a non-active cluster) way of implementing this.

**Comment by benesch** [comment]
I've proposed this somewhere in the past, but I can't find that past proposal now, so I'll propose it again here. I think the right thing to do here is to change from having users elide `CREATE SOURCE ... IN CLUSTER ...` from their model definitions.

Specifically, instead of writing:

```sql
-- my_source.sql
CREATE SOURCE my_source IN CLUSTER clstr
FROM KAFKA CONNECTION kconn TOPIC ('foo')
ENVELOPE NONE
```

you'd write:

```sql
-- my_source.sql
FROM KAFKA CONNECTION kconn TOPIC ('foo')
ENVELOPE NONE
```

Yes, this looks a little funny. Yes, it'd be a backwards incompatible change. Nonetheless, I think it is worth the trouble! Here's why:

  * After this change, Kafka sources would be a first class citizen in dbt. I think we could even recommend that users use dbt to manage Kafka sources. They'll properly respect the `schema` and `cluster` configs, and will "just work" with the new [blue/green orchestration](https://github.com/MaterializeInc/materialize/pull/25174) that @sjwiesman is building.
  * We have line of sight to making PostgreSQL sources a first class citizen too. The problem today is subsources. dbt doesn't know about subsources, as they're not defined in a model that dbt can see. But we now [have plans to fix that](https://github.com/MaterializeInc/materialize/issues/20208#issuecomment-1955401921)! We'll eventually introduce syntax to allow "subsources" to be defined individually:

    ```sql
    -- my_postgres_source.sql
    CREATE SOURCE postgres_src
    FROM POSTGRES CONNECTION postgres_conn (PUBLICATION 'pub')
    -- Note: we intentionally don't say FOR ALL TABLES here!
    ```

    ```sql
    -- my_postgres_source_tab1.sql
    FROM SOURCE postgres_src (tab1)
    ```

    ```sql
    -- my_postgres_source_tab2.sql
    FROM SOURCE postgres_src (tab2)
    ```

    dbt would then have knowledge of the existence of each subsource, and they'd be properly referenceable by downstream models and participate in blue/green deployments.

**Comment by morsapaes** [comment]
Still think it's gross, but for lack of better options: put up a prototype in #25405.
