### ISSUE TITLE
release: v0.42.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17397]
The following PRs in [`v0.42.0`](https://github.com/MaterializeInc/materialize/tree/v0.42.0) require review:
* [x] [#17303 doc/user: minor fixups](https://github.com/MaterializeInc/materialize/pull/17303) (@morsapaes)
* [x] [#17307 doc/user: adjust documentation for cluster unification](https://github.com/MaterializeInc/materialize/pull/17307) (@benesch)
* [x] [#17362 doc/user: simple fix to command](https://github.com/MaterializeInc/materialize/pull/17362) (@joacoc)
* [ ] [#17390 deps: upgrade to AWS SDK v0.23/v0.53](https://github.com/MaterializeInc/materialize/pull/17390) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`5d802ee56` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5d802ee5696df6f10d7f395a5bb4582d68224962) (@materializer)
* [ ] [`74a3343fd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/74a3343fdd59be8ece2cc7e3315631d9e1651942) (@materializer)
* [ ] [`261c15f22` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/261c15f22c938156d07c581cc93b39e01d5adfd1) (@materializer)
* [x] [`d4ef23cad` fix typo](https://github.com/MaterializeInc/materialize/commit/d4ef23cadf2a5c2485c8375fd8d2195135ce6b31) (@umanwizard)
* [ ] [`e51264111` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e51264111319a08ecc728d151db38ee0cd37da91) (@materializer)
* [ ] [`8d2a97d1e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8d2a97d1edf8c662be9d26233926190059c6df4d) (@materializer)
* [ ] [`de2e6b03f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/de2e6b03f2db118c39b62365d5e157cae1980c9a) (@materializer)
* [ ] [`aa48ef311` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aa48ef31116e71128e383e5ea8e48bbd685e8dca) (@materializer)
* [ ] [`a6aa750a0` release: bump to version v0.42.0](https://github.com/MaterializeInc/materialize/commit/a6aa750a0623b7028bb71a0045d07d266161f0de) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#17315 dbt-materialize: Replace Deprecated Exceptions](https://github.com/MaterializeInc/materialize/pull/17315) (@dehume)
* [ ] [#17082 Update join optimization](https://github.com/MaterializeInc/materialize/pull/17082) (@chuck-alt-delete)
* [ ] [#17289 release: bump to version v0.42.0-dev](https://github.com/MaterializeInc/materialize/pull/17289) (@guswynn)
* [ ] [#17287 cord: misc. work in support of queryable remap shards, pt. 0](https://github.com/MaterializeInc/materialize/pull/17287) (@sploiselle)
* [ ] [#17161 stash: add txn api](https://github.com/MaterializeInc/materialize/pull/17161) (@mjibson)
* [ ] [#17259 adapter,stash: reduce total stash statement count](https://github.com/MaterializeInc/materialize/pull/17259) (@mjibson)
* [ ] [#17303 doc/user: minor fixups](https://github.com/MaterializeInc/materialize/pull/17303) (@morsapaes)
* [ ] [#17308 pgtest: teach tests to be restartable](https://github.com/MaterializeInc/materialize/pull/17308) (@mjibson)
* [ ] [#17312 adapter: use stash txn during stash init](https://github.com/MaterializeInc/materialize/pull/17312) (@mjibson)
* [ ] [#17314 controller: minor cleanup](https://github.com/MaterializeInc/materialize/pull/17314) (@teskje)
* [ ] [#17297 sqllogictest: return from main rather than exit(2)'ing](https://github.com/MaterializeInc/materialize/pull/17297) (@tokenrove)
* [ ] [#17298 persist: add blob-usage subcommand to persistcli](https://github.com/MaterializeInc/materialize/pull/17298) (@danhhz)
* [ ] [#17316 adapter: align `EXPLAIN AS TEXT` for `With` clauses in HIR/MIR/LIR](https://github.com/MaterializeInc/materialize/pull/17316) (@aalexandrov)
* [ ] [#17305 storage-client: fix emission of "dropped" source/sink status](https://github.com/MaterializeInc/materialize/pull/17305) (@benesch)
* [ ] [#17311 adapter: trace various startup functions](https://github.com/MaterializeInc/materialize/pull/17311) (@mjibson)
* [ ] [#17294 [persist] Inspect any state rollup](https://github.com/MaterializeInc/materialize/pull/17294) (@bkirwi)
* [ ] [#17299 [persist] Perform expiry directly instead of passing it as maintenance](https://github.com/MaterializeInc/materialize/pull/17299) (@bkirwi)
* [ ] [#17323 storage: revert internal control flow changes](https://github.com/MaterializeInc/materialize/pull/17323) (@aljoscha)
* [ ] [#17126 adapter: batch calls to create_collections in bootstrap](https://github.com/MaterializeInc/materialize/pull/17126) (@mjibson)
* [ ] [#16675 persist: monitor rtt latency to blob and consensus in metrics](https://github.com/MaterializeInc/materialize/pull/16675) (@danhhz)
* [ ] [#17326 doc/developer: suggest use of forked Homebrew tap on macOS](https://github.com/MaterializeInc/materialize/pull/17326) (@benesch)
* [ ] [#17329 plan: Generate deterministic plan for table funcs](https://github.com/MaterializeInc/materialize/pull/17329) (@jkosh44)
* [ ] [#17333 adapter: remove unneeded and slow delayed consolidations](https://github.com/MaterializeInc/materialize/pull/17333) (@mjibson)
* [ ] [#17335 adapter: even more tracing](https://github.com/MaterializeInc/materialize/pull/17335) (@mjibson)
* [ ] [#17224 Add compute/storage protocol message size metrics](https://github.com/MaterializeInc/materialize/pull/17224) (@lluki)
* [ ] [#17339 storage: only create async worker once (aka. revert the removal of not halting in storage)](https://github.com/MaterializeInc/materialize/pull/17339) (@aljoscha)
* [ ] [#17345 Ensure `ConsolidateBuffer` maintains target capacity after flush](https://github.com/MaterializeInc/materialize/pull/17345) (@vmarcos)
* [ ] [#17336 Stable wrappers for Hash collections](https://github.com/MaterializeInc/materialize/pull/17336) (@teskje)
* [ ] [#17228 doc/user: document mz_sink_statistics](https://github.com/MaterializeInc/materialize/pull/17228) (@guswynn)
* [ ] [#17235 doc/user: add documentation for mz_internal.mz_postgres_sources](https://github.com/MaterializeInc/materialize/pull/17235) (@benesch)
* [ ] [#17277 test: add `allowed_cluster_replica_sizes` nightly test](https://github.com/MaterializeInc/materialize/pull/17277) (@aalexandrov)
* [ ] [#17334 environmentd: trace startup](https://github.com/MaterializeInc/materialize/pull/17334) (@mjibson)
* [ ] [#17307 doc/user: adjust documentation for cluster unification](https://github.com/MaterializeInc/materialize/pull/17307) (@benesch)
* [ ] [#17341 sql: complex range functions, pt 0](https://github.com/MaterializeInc/materialize/pull/17341) (@sploiselle)
* [ ] [#17332 stash: batch update sets](https://github.com/MaterializeInc/materialize/pull/17332) (@mjibson)
* [ ] [#17344 Add "role" labels to cluster replicas](https://github.com/MaterializeInc/materialize/pull/17344) (@umanwizard)
* [ ] [#17355 stash: dynamically prepare all update statements](https://github.com/MaterializeInc/materialize/pull/17355) (@mjibson)
* [ ] [#17347 doc/user: polish v0.41.0 release notes](https://github.com/MaterializeInc/materialize/pull/17347) (@morsapaes)
* [ ] [#17356 CODEOWNERS: add owners for src/controller](https://github.com/MaterializeInc/materialize/pull/17356) (@teskje)
* [ ] [#17362 doc/user: simple fix to command](https://github.com/MaterializeInc/materialize/pull/17362) (@joacoc)
* [ ] [#17275 Add percentiles to SQL patterns in the docs (#16674)](https://github.com/MaterializeInc/materialize/pull/17275) (@sthm)
* [ ] [#17363 adapter: Add deterministic audit event timestamps](https://github.com/MaterializeInc/materialize/pull/17363) (@jkosh44)
* [ ] [#17295 Kill all of sqllogictest's descendants](https://github.com/MaterializeInc/materialize/pull/17295) (@tokenrove)
* [ ] [#17348 explain: replace column runs with ranges in `~ScalarExpr` sequences](https://github.com/MaterializeInc/materialize/pull/17348) (@aalexandrov)
* [ ] [#17371 Remove some leftover QGM tests](https://github.com/MaterializeInc/materialize/pull/17371) (@ggevay)
* [ ] [#17369 parser: Impose size limit on statement batches](https://github.com/MaterializeInc/materialize/pull/17369) (@jkosh44)
* [ ] [#17330 persist: move PersistConfig and PersistParameters around](https://github.com/MaterializeInc/materialize/pull/17330) (@danhhz)
* [ ] [#17370 Update several dependencies to variants without advisories](https://github.com/MaterializeInc/materialize/pull/17370) (@antiguru)
* [ ] [#17306 Cluster unification followups](https://github.com/MaterializeInc/materialize/pull/17306) (@benesch)
* [ ] [#17378 Update to Rust 1.67](https://github.com/MaterializeInc/materialize/pull/17378) (@teskje)
* [ ] [#17374 explain: deprecate and remove the old `explain` code](https://github.com/MaterializeInc/materialize/pull/17374) (@aalexandrov)
* [ ] [#17380 doc/user: minor improvements in the percentile pattern](https://github.com/MaterializeInc/materialize/pull/17380) (@sthm)
* [ ] [#17246 persist: add metrics to s3 timeouts; timeouts can be dynamically set](https://github.com/MaterializeInc/materialize/pull/17246) (@pH14)
* [ ] [#17352 adapter/controller: start replicas concurrently in bootstrap and CREATE CLUSTER](https://github.com/MaterializeInc/materialize/pull/17352) (@guswynn)
* [ ] [#17129 Avoid multiple InspectBatch probing operators](https://github.com/MaterializeInc/materialize/pull/17129) (@antiguru)
* [ ] [#17105 storage: shard finalization WAL](https://github.com/MaterializeInc/materialize/pull/17105) (@sploiselle)
* [ ] [#17373 Move linked cluster tests to adapter](https://github.com/MaterializeInc/materialize/pull/17373) (@umanwizard)
* [ ] [#17302 Add `sum` field to `mz_raw_peek_durations` and `mz_raw_worker_compute_delays`](https://github.com/MaterializeInc/materialize/pull/17302) (@umanwizard)
* [ ] [#17388 deps: upgrade timely](https://github.com/MaterializeInc/materialize/pull/17388) (@petrosagg)
* [ ] [#17389 environmentd: print run trace id](https://github.com/MaterializeInc/materialize/pull/17389) (@mjibson)
* [ ] [#17390 deps: upgrade to AWS SDK v0.23/v0.53](https://github.com/MaterializeInc/materialize/pull/17390) (@benesch)
* [ ] [#17395 materialized: add warning about version upgrades to Docker image](https://github.com/MaterializeInc/materialize/pull/17395) (@benesch)
* [ ] [`5d802ee56` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5d802ee5696df6f10d7f395a5bb4582d68224962) (@materializer)
* [ ] [`74a3343fd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/74a3343fdd59be8ece2cc7e3315631d9e1651942) (@materializer)
* [ ] [`261c15f22` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/261c15f22c938156d07c581cc93b39e01d5adfd1) (@materializer)
* [ ] [`d4ef23cad` fix typo](https://github.com/MaterializeInc/materialize/commit/d4ef23cadf2a5c2485c8375fd8d2195135ce6b31) (@umanwizard)
* [ ] [`e51264111` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e51264111319a08ecc728d151db38ee0cd37da91) (@materializer)
* [ ] [`8d2a97d1e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8d2a97d1edf8c662be9d26233926190059c6df4d) (@materializer)
* [ ] [`de2e6b03f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/de2e6b03f2db118c39b62365d5e157cae1980c9a) (@materializer)
* [ ] [`aa48ef311` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aa48ef31116e71128e383e5ea8e48bbd685e8dca) (@materializer)
* [ ] [`a6aa750a0` release: bump to version v0.42.0](https://github.com/MaterializeInc/materialize/commit/a6aa750a0623b7028bb71a0045d07d266161f0de) (@benesch)

**Comment by benesch** [comment]
The PRs and commits that aren't mine LGTM.
