### ISSUE TITLE
[Epic] Multipurpose clusters

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17413]
### Product Outcome

Users can install sources, sinks, indexes, and materialized views in the same cluster.

### Specification

This is a followup epic to https://github.com/MaterializeInc/cloud/issues/4929.

https://www.notion.so/materialize/Cluster-unification-472efd2e9b8d4286bacc91b84d6b6f71

### Design

See specification.

### Required Issues (Must Haves)

- [ ] #16773
- [ ] #16582
- [ ] Permit moving sources and sinks between clusters.
- [ ] Unify timely clusters.
- [ ] Reparallelize creating/dropping cluster replicas with Kubernetes
- [ ] Remove mention of storage hosts and default storage sizes
- [ ] Renable test_sink_resizing in cloudtest
