### ISSUE TITLE
[Epic] Postgres source hardening

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#17598]
### Background

Postgres sources have two broad categories of issues that make them somewhat tedious to use:

1. Limitations by design: things that we didn't deem necessary but turned out to be more important. For example: tolerating simple schema changes in a replicated table.
2. Bugs/quality-of-life issues.

### References

 - Draft product spec for Postgres operational concerns (internal): https://www.notion.so/materialize/Postgres-Operational-Improvements-9f40bd3c11b64caab1aeed3f866f1058

### Success Metrics

 - Ratio of `num-postgres-sources / num-sources`, for production users/preview users
 - Ration of `num-postgres-sources / num-debezium-sources`, for production users/preview users

Both metrics should give us roughly the same information. One wrinkle is that users might be using Debezium over direct Postgres sources for reasons outside our control: for example, they might want to replicate a data base to multiple consumers, in which case using Debezium + Kafka could be better, even if our Postgres support is excellent.

Metrics (internal): https://grafana.dev.materialize.com/d/hACINDSVk/active-trial-and-customer-usage?orgId=1&viewPanel=68

---

```[tasklist]
## Feature improvements
 - [ ] #17595
 - [ ] #15832
 - [ ] #16371
- [ ] https://github.com/MaterializeInc/materialize/issues/17956
- [ ] https://github.com/MaterializeInc/materialize/issues/17955
- [ ] https://github.com/MaterializeInc/materialize/issues/17957
- [ ] https://github.com/MaterializeInc/materialize/pull/18403
```

```[tasklist]
## Bugs/quality-of-life
 - [ ] #17924
 - [ ] #17490  
 - [ ] #17927
 - [ ] #14335 
 - [ ] #15044 
 - [ ] #16637 
- [ ] https://github.com/MaterializeInc/materialize/issues/18518
- [ ] https://github.com/MaterializeInc/materialize/issues/18519
- [ ] https://github.com/MaterializeInc/materialize/issues/18683
- [ ] https://github.com/MaterializeInc/materialize/issues/19030
- [ ] https://github.com/MaterializeInc/materialize/issues/19031
```

We should include more issues from the `T-PG` label as we go on.

**Comment by guswynn** [comment]
@sploiselle and @petrosagg also discussed an additional artifact we may want from this epic: a normative description of how the postgres implementation works, to be written after we hash out all these other improvements

**Comment by benesch** [comment]
Recording two more thoughts from a prospect's experience:

  * We should add TCP keepalives, and maybe also TCP user timeouts. @pH14 has some knowledge about how to configure these, based on trying to configure them for CockroachDB. This would let us detect wedged connections more quickly.
  * We should write a test against a GCP Cloud SQL instance, to see if we can reproduce the sporadic "connection closed" errors that one prospect is seeing.

**Comment by pH14** [comment]
> We should add TCP keepalives, and maybe also TCP user timeouts. @pH14 has some knowledge about how to configure these, based on trying to configure them for CockroachDB. This would let us detect wedged connections more quickly.

From what I understand (which is usually just paraphrasing this amazing [Cloudflare blog post](https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/)), we want both TCP keepalives and TCP user timeouts. Keep-alives are useful when the connection is idle && send buffer is empty, user timeouts kick in when the send buffer has an outstanding packet which could be often. We'll additionally want a connection timeout to avoid getting stuck in the initial handshake phase where neither keepalives nor user timeouts apply.

**Comment by benesch** [comment]
Closing, as PostgreSQL sources are GA. Not everything here is fixed, but empirically PostgreSQL sources work quite well for a large class of users.
