### ISSUE TITLE
release: v0.42.4 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17593]
No PRs in [`v0.42.4`](https://github.com/MaterializeInc/materialize/tree/v0.42.4) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`f5de0acef` adapter: Reject requests above a certain size (#17481)](https://github.com/MaterializeInc/materialize/commit/f5de0acefb6225a69d3c7e439594637ead27c3b8) (@benesch)
* [x] [`0e6ebd876` adapter: Reject ws requests above a certain size (#17523)](https://github.com/MaterializeInc/materialize/commit/0e6ebd8761abd48623455bc0e3b8202de171e1ff) (@benesch)
* [x] [`fc160c6e4` sql: Move statement size check to server layer (#17580)](https://github.com/MaterializeInc/materialize/commit/fc160c6e4954a48e51026383674f4c6d8c59121e) (@benesch)
* [x] [`ffe73ec8b` release: bump to version v0.42.4](https://github.com/MaterializeInc/materialize/commit/ffe73ec8b6e742574aa3cd6aaadf4adc12dffbdd) (@benesch)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`f5de0acef` adapter: Reject requests above a certain size (#17481)](https://github.com/MaterializeInc/materialize/commit/f5de0acefb6225a69d3c7e439594637ead27c3b8) (@benesch)
* [ ] [`0e6ebd876` adapter: Reject ws requests above a certain size (#17523)](https://github.com/MaterializeInc/materialize/commit/0e6ebd8761abd48623455bc0e3b8202de171e1ff) (@benesch)
* [ ] [`fc160c6e4` sql: Move statement size check to server layer (#17580)](https://github.com/MaterializeInc/materialize/commit/fc160c6e4954a48e51026383674f4c6d8c59121e) (@benesch)
* [ ] [`ffe73ec8b` release: bump to version v0.42.4](https://github.com/MaterializeInc/materialize/commit/ffe73ec8b6e742574aa3cd6aaadf4adc12dffbdd) (@benesch)

**Comment by jkosh44** [comment]
All the commits LGTM
