### ISSUE TITLE
release: v0.43.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17618]
The following PRs in [`v0.43.0`](https://github.com/MaterializeInc/materialize/tree/v0.43.0) require review:
* [x] [#17410 cloud-canary: Use the same image for both local and cloud Mz instances](https://github.com/MaterializeInc/materialize/pull/17410) (@philip-stoev)
* [x] [#17400 ci: Add journalctl output to the buildkite artifacts](https://github.com/MaterializeInc/materialize/pull/17400) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`d7530b6df` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d7530b6dfed29efa05bb9f4d0d391d0688fa4b06) (@materializer)
* [ ] [`e96e7e203` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e96e7e2030de8eecd4a222d9c48514ddea5afc15) (@materializer)
* [ ] [`cfb2b6cfb` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cfb2b6cfb2ceed01aa0e4c832cad2b1a5cbe6948) (@materializer)
* [ ] [`4e143a70b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4e143a70b3501b513fd742f5b4b3ec4c9a94dc2c) (@materializer)
* [ ] [`e44df23f0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e44df23f0ef6f8505f1a46c1ffbf7b08657fe8b2) (@materializer)
* [ ] [`d314f1f8f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d314f1f8fffe9822d5eab5336aa80bce364b608d) (@materializer)
* [ ] [`b2ff0362a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b2ff0362a50207c3297e40b16e511b21728ceb7e) (@materializer)
* [ ] [`3143ababe` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3143ababe1790aa586eb6faa51e49210a36e9824) (@materializer)
* [ ] [`d0b93e76c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0b93e76c7b05320904ca443b4feaf78d02187cd) (@materializer)
* [ ] [`1b6df3907` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1b6df390749beb41de2fddcd5da80c13f293ed0c) (@materializer)
* [ ] [`a8134a169` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a8134a169cf4821d40ab18d30bf2a4692b73991d) (@materializer)
* [ ] [`21c16338c` release: bump to version v0.43.0](https://github.com/MaterializeInc/materialize/commit/21c16338cc1e4b600d83adf0cdf3365175f3739d) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#17346 Replace more uses of stdlib Hash collections](https://github.com/MaterializeInc/materialize/pull/17346) (@teskje)
* [ ] [#17386 mzcompose: use native Docker Compose healthchecks](https://github.com/MaterializeInc/materialize/pull/17386) (@benesch)
* [ ] [#17385 explain: remove `Displayable` newtype struct](https://github.com/MaterializeInc/materialize/pull/17385) (@aalexandrov)
* [ ] [#17403 avro,build-id,testdrive: remove uses of Hash collections](https://github.com/MaterializeInc/materialize/pull/17403) (@teskje)
* [ ] [#17402 test: Use CRDB v22.2.3 across the board when testing](https://github.com/MaterializeInc/materialize/pull/17402) (@philip-stoev)
* [ ] [#17404 .github: fix line breaks in PR checklist](https://github.com/MaterializeInc/materialize/pull/17404) (@aalexandrov)
* [ ] [#17405 ccsr,npm,cloud-res,orchestrator-k8s: remove uses of Hash collections](https://github.com/MaterializeInc/materialize/pull/17405) (@teskje)
* [ ] [#17406 storage: remove uses of Hash collections](https://github.com/MaterializeInc/materialize/pull/17406) (@teskje)
* [ ] [#17410 cloud-canary: Use the same image for both local and cloud Mz instances](https://github.com/MaterializeInc/materialize/pull/17410) (@philip-stoev)
* [ ] [#17399 fix the missing `DESC` in the doc.](https://github.com/MaterializeInc/materialize/pull/17399) (@nooberfsh)
* [ ] [#17412 secrets: remove uses of Hash collections](https://github.com/MaterializeInc/materialize/pull/17412) (@teskje)
* [ ] [#17372 Clarify JSON Parsing](https://github.com/MaterializeInc/materialize/pull/17372) (@chuck-alt-delete)
* [ ] [#17411 proto: remove RustType impl for HashMap](https://github.com/MaterializeInc/materialize/pull/17411) (@teskje)
* [ ] [#17284 storage: misc. work in support of queryable remap shards, pt. 0](https://github.com/MaterializeInc/materialize/pull/17284) (@sploiselle)
* [ ] [#17407 persist*: remove uses of Hash collections](https://github.com/MaterializeInc/materialize/pull/17407) (@teskje)
* [ ] [#17114 storage: produce definite snapshot](https://github.com/MaterializeInc/materialize/pull/17114) (@petrosagg)
* [ ] [#17423 persist: fix hot loop error path in {blob,consensus}_rtt_latency](https://github.com/MaterializeInc/materialize/pull/17423) (@danhhz)
* [ ] [#17421 adapter: Fix bug in initialize_read_policies](https://github.com/MaterializeInc/materialize/pull/17421) (@jkosh44)
* [ ] [#17431 expr: don't panic on internal func type error](https://github.com/MaterializeInc/materialize/pull/17431) (@mjibson)
* [ ] [#17379 Use `ConsolidateBuffer` for more aggressive per-worker pre-aggregation in `explode_one`](https://github.com/MaterializeInc/materialize/pull/17379) (@vmarcos)
* [ ] [#17432 persist: tiny refactor of {blob,consensus}_rtt_latency task](https://github.com/MaterializeInc/materialize/pull/17432) (@danhhz)
* [ ] [#17430 storage: Change error log to warn](https://github.com/MaterializeInc/materialize/pull/17430) (@jkosh44)
* [ ] [#17252 Convert persist_source to a regular non-async operator](https://github.com/MaterializeInc/materialize/pull/17252) (@antiguru)
* [ ] [#17350 [persist] Timing metrics and delete-rollup parallelism for GC](https://github.com/MaterializeInc/materialize/pull/17350) (@bkirwi)
* [ ] [#16214 storage: push native timestamps further](https://github.com/MaterializeInc/materialize/pull/16214) (@petrosagg)
* [ ] [#17401 compute: use BTreeMaps rather than HashMaps for top-k rendering](https://github.com/MaterializeInc/materialize/pull/17401) (@teskje)
* [ ] [#17434 sql: permit loading catalog with out-of-order dependencies](https://github.com/MaterializeInc/materialize/pull/17434) (@sploiselle)
* [ ] [#17408 surfaces: remove uses of Hash collections](https://github.com/MaterializeInc/materialize/pull/17408) (@teskje)
* [ ] [#17400 ci: Add journalctl output to the buildkite artifacts](https://github.com/MaterializeInc/materialize/pull/17400) (@philip-stoev)
* [ ] [#17442 deps: remove some unused dependencies](https://github.com/MaterializeInc/materialize/pull/17442) (@benesch)
* [ ] [#17445 Disallow stdlib Hash collections throughout the codebase](https://github.com/MaterializeInc/materialize/pull/17445) (@teskje)
* [ ] [#17448 adapter: print view name in `EXPLAIN [MATERIALIZED] VIEW`](https://github.com/MaterializeInc/materialize/pull/17448) (@aalexandrov)
* [ ] [#17452 storage: make sure we efficiently batch records from sources](https://github.com/MaterializeInc/materialize/pull/17452) (@petrosagg)
* [ ] [#17438 [persist] Latency histograms for some key operations](https://github.com/MaterializeInc/materialize/pull/17438) (@bkirwi)
* [ ] [#17453 sql: introduce EXPOSE PROGRESS AS for progress collections](https://github.com/MaterializeInc/materialize/pull/17453) (@sploiselle)
* [ ] [#17456 adapter: Return error for failed dataflows](https://github.com/MaterializeInc/materialize/pull/17456) (@jkosh44)
* [ ] [#17461 test: Fix test_storage_usage_doesnt_update_between_restarts](https://github.com/MaterializeInc/materialize/pull/17461) (@jkosh44)
* [ ] [#17460 adapter: remove deferred_object_name_rewrite migration](https://github.com/MaterializeInc/materialize/pull/17460) (@sploiselle)
* [ ] [#17469 scratch: Print only rounded seconds remaining](https://github.com/MaterializeInc/materialize/pull/17469) (@def-)
* [ ] [#17470 doc/developer: Install postgresql-client, suggest java 11 instead of java 8](https://github.com/MaterializeInc/materialize/pull/17470) (@def-)
* [ ] [#17468 compute: fix typo in metric name](https://github.com/MaterializeInc/materialize/pull/17468) (@teskje)
* [ ] [#17449 Extend documentation on compute clients](https://github.com/MaterializeInc/materialize/pull/17449) (@teskje)
* [ ] [#17474 persist: fix bug where too many rtt tasks were created](https://github.com/MaterializeInc/materialize/pull/17474) (@danhhz)
* [ ] [#17458 test: e2e testing for OpenTelemetry Tracing](https://github.com/MaterializeInc/materialize/pull/17458) (@ParkMyCar)
* [ ] [#17459 adapter: fix TODO, add Timestamp::from_duration](https://github.com/MaterializeInc/materialize/pull/17459) (@ParkMyCar)
* [ ] [#17479 sql: error if a CSR URL contains a path](https://github.com/MaterializeInc/materialize/pull/17479) (@mjibson)
* [ ] [#17475 adapter: remove read policies for dropped compute sinks](https://github.com/MaterializeInc/materialize/pull/17475) (@teskje)
* [ ] [#17473 compute-client: stop leaking subscribe tracking state](https://github.com/MaterializeInc/materialize/pull/17473) (@teskje)
* [ ] [#17485 storage: reclock: take batches into account when downgrading](https://github.com/MaterializeInc/materialize/pull/17485) (@petrosagg)
* [ ] [#17486 sqllogictest: Add explicit test for TRIM BOTH (fixes #17472)](https://github.com/MaterializeInc/materialize/pull/17486) (@def-)
* [ ] [#17450 Initial stab at a `Normalize` transform](https://github.com/MaterializeInc/materialize/pull/17450) (@aalexandrov)
* [ ] [#17464 mz: add connection details to `mz status`](https://github.com/MaterializeInc/materialize/pull/17464) (@joacoc)
* [ ] [#17481 adapter: Reject requests above a certain size](https://github.com/MaterializeInc/materialize/pull/17481) (@jkosh44)
* [ ] [#17441 adapter: Remove unwrap()](https://github.com/MaterializeInc/materialize/pull/17441) (@jkosh44)
* [ ] [#17440 persist: push the Mutex into PersistClientCache](https://github.com/MaterializeInc/materialize/pull/17440) (@danhhz)
* [ ] [#17494 sql: Fix decoding of text arrays](https://github.com/MaterializeInc/materialize/pull/17494) (@jkosh44)
* [ ] [#17495 adapter: Fix inconsistent subscribe metadata](https://github.com/MaterializeInc/materialize/pull/17495) (@jkosh44)
* [ ] [#17439 adapter: cleanup orphaned secrets at bootstrap](https://github.com/MaterializeInc/materialize/pull/17439) (@mjibson)
* [ ] [#17150 persist: extract an Applier from Machine](https://github.com/MaterializeInc/materialize/pull/17150) (@danhhz)
* [ ] [#17501 environmentd: fix test_conn_user flake](https://github.com/MaterializeInc/materialize/pull/17501) (@mjibson)
* [ ] [#17502 storage: stop processing once we commit the empty frontier](https://github.com/MaterializeInc/materialize/pull/17502) (@petrosagg)
* [ ] [#17504 doc: Minor fixes for "Platform Checks" documentation](https://github.com/MaterializeInc/materialize/pull/17504) (@def-)
* [ ] [#17505 dbt-materialize: release v1.4.0](https://github.com/MaterializeInc/materialize/pull/17505) (@morsapaes)
* [ ] [#17508 explain: remove old `explain` code](https://github.com/MaterializeInc/materialize/pull/17508) (@aalexandrov)
* [ ] [#17514 Platform checks: Add ESCAPE to LIKE/ILIKE (part of #17471)](https://github.com/MaterializeInc/materialize/pull/17514) (@def-)
* [ ] [#17516 test: small visibility cleanup](https://github.com/MaterializeInc/materialize/pull/17516) (@ParkMyCar)
* [ ] [#17476 adapter: Drop subscribes when dependencies drop](https://github.com/MaterializeInc/materialize/pull/17476) (@jkosh44)
* [ ] [#17519 Platform checks: Add Cast, String checks, extend JsonbType (fixes #17471)](https://github.com/MaterializeInc/materialize/pull/17519) (@def-)
* [ ] [#16487 [sinks] Relax our behaviour on upsert semantics](https://github.com/MaterializeInc/materialize/pull/16487) (@bkirwi)
* [ ] [#17527 Doc: Fix formatting in formalism](https://github.com/MaterializeInc/materialize/pull/17527) (@jkosh44)
* [ ] [#17531 build(deps): bump boto3 from 1.26.45 to 1.26.64 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/17531) (@dependabot[bot])
* [ ] [#17534 build(deps): bump ubuntu from jammy-20221130 to jammy-20230126 in /misc/images/ubuntu-base](https://github.com/MaterializeInc/materialize/pull/17534) (@dependabot[bot])
* [ ] [#17536 docker: Use CRDB 23.2.3 in the Materialize image](https://github.com/MaterializeInc/materialize/pull/17536) (@philip-stoev)
* [ ] [#17496 adapter: give all subscribes transient IDs](https://github.com/MaterializeInc/materialize/pull/17496) (@teskje)
* [ ] [#17518 explain: various simplifications](https://github.com/MaterializeInc/materialize/pull/17518) (@aalexandrov)
* [ ] [#17537 compute-client: ignore stray `SubscribeResponse`s](https://github.com/MaterializeInc/materialize/pull/17537) (@teskje)
* [ ] [#17539 doc/user: Fix intro blurb typo](https://github.com/MaterializeInc/materialize/pull/17539) (@ruf-io)
* [ ] [#17523 adapter: Reject ws requests above a certain size](https://github.com/MaterializeInc/materialize/pull/17523) (@jkosh44)
* [ ] [#17524 adapter: Drop peeks when dependencies drop](https://github.com/MaterializeInc/materialize/pull/17524) (@jkosh44)
* [ ] [#17304 doc/developer: remove outdated text from architecture-db.md](https://github.com/MaterializeInc/materialize/pull/17304) (@benesch)
* [ ] [#17435 compute: use columnation-backed arrangements explicitly](https://github.com/MaterializeInc/materialize/pull/17435) (@tokenrove)
* [ ] [#17493 compute: log frontiers of subscribes](https://github.com/MaterializeInc/materialize/pull/17493) (@teskje)
* [ ] [#17540 compute-client: fix partitioned subscribe tracking](https://github.com/MaterializeInc/materialize/pull/17540) (@teskje)
* [ ] [#16797 persist: begin hooking up PersistConfig to LaunchDarkly](https://github.com/MaterializeInc/materialize/pull/16797) (@danhhz)
* [ ] [#17551 persist: remove source-example from persistcli](https://github.com/MaterializeInc/materialize/pull/17551) (@danhhz)
* [ ] [#17480 persist: remove K, V, D bounds from State](https://github.com/MaterializeInc/materialize/pull/17480) (@danhhz)
* [ ] [#17552 persist: keep metrics per raw s3 call](https://github.com/MaterializeInc/materialize/pull/17552) (@danhhz)
* [ ] [#8057 sql: add bool_and and bool_or](https://github.com/MaterializeInc/materialize/pull/8057) (@andylokandy)
* [ ] [#17517 Remove panic from reduce collation](https://github.com/MaterializeInc/materialize/pull/17517) (@vmarcos)
* [ ] [#17561 storage: fix typos](https://github.com/MaterializeInc/materialize/pull/17561) (@aljoscha)
* [ ] [#17511 storage: move methods into the `SourceConnection` trait](https://github.com/MaterializeInc/materialize/pull/17511) (@petrosagg)
* [ ] [#17545 SQL: Prevent ambiguous col refs to system objects](https://github.com/MaterializeInc/materialize/pull/17545) (@jkosh44)
* [ ] [#17564 storage: skip committing empty offset partition lists to kafka](https://github.com/MaterializeInc/materialize/pull/17564) (@guswynn)
* [ ] [#17550 sql: implement remaining range functions](https://github.com/MaterializeInc/materialize/pull/17550) (@sploiselle)
* [ ] [#17562 doc/user: polish v0.42 release notes](https://github.com/MaterializeInc/materialize/pull/17562) (@morsapaes)
* [ ] [#17570 Update numpy and scipy to versions supporting Python 3.11](https://github.com/MaterializeInc/materialize/pull/17570) (@antiguru)
* [ ] [#17556 adapter: improve schema resolution](https://github.com/MaterializeInc/materialize/pull/17556) (@mjibson)
* [ ] [#17557 compute: frontier logging for index imports](https://github.com/MaterializeInc/materialize/pull/17557) (@teskje)
* [ ] [#17569 Log peek completion on reconciliation](https://github.com/MaterializeInc/materialize/pull/17569) (@antiguru)
* [ ] [#17577 repr: emit an error on Dummy decoding](https://github.com/MaterializeInc/materialize/pull/17577) (@teskje)
* [ ] [#17579 persist: store encoded size in State's rollups field](https://github.com/MaterializeInc/materialize/pull/17579) (@danhhz)
* [ ] [#17582 persist: make trace_push_batch benchmark faster under `cargo test`](https://github.com/MaterializeInc/materialize/pull/17582) (@danhhz)
* [ ] [#17580 sql: Move statement size check to server layer](https://github.com/MaterializeInc/materialize/pull/17580) (@jkosh44)
* [ ] [#17574 ci: Restore the sql.stats.forecasts.enabled = false CRDB workaround](https://github.com/MaterializeInc/materialize/pull/17574) (@philip-stoev)
* [ ] [#17587 Fix unbounded memory usage in `delay_map`](https://github.com/MaterializeInc/materialize/pull/17587) (@umanwizard)
* [ ] [#17588 test: Add test stash allowing opening and closing](https://github.com/MaterializeInc/materialize/pull/17588) (@jkosh44)
* [ ] [#17576 compute: add reconciliation metrics](https://github.com/MaterializeInc/materialize/pull/17576) (@teskje)
* [ ] [#17602 sql: allow returning NULL from upper, lower range fns](https://github.com/MaterializeInc/materialize/pull/17602) (@sploiselle)
* [ ] [#17581 surfaces: populate mz_object_dependencies correctly](https://github.com/MaterializeInc/materialize/pull/17581) (@guswynn)
* [ ] [#17607 environmentd: report traits in telemetry rollup event](https://github.com/MaterializeInc/materialize/pull/17607) (@benesch)
* [ ] [`d7530b6df` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d7530b6dfed29efa05bb9f4d0d391d0688fa4b06) (@materializer)
* [ ] [`e96e7e203` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e96e7e2030de8eecd4a222d9c48514ddea5afc15) (@materializer)
* [ ] [`cfb2b6cfb` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cfb2b6cfb2ceed01aa0e4c832cad2b1a5cbe6948) (@materializer)
* [ ] [`4e143a70b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4e143a70b3501b513fd742f5b4b3ec4c9a94dc2c) (@materializer)
* [ ] [`e44df23f0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e44df23f0ef6f8505f1a46c1ffbf7b08657fe8b2) (@materializer)
* [ ] [`d314f1f8f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d314f1f8fffe9822d5eab5336aa80bce364b608d) (@materializer)
* [ ] [`b2ff0362a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/b2ff0362a50207c3297e40b16e511b21728ceb7e) (@materializer)
* [ ] [`3143ababe` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/3143ababe1790aa586eb6faa51e49210a36e9824) (@materializer)
* [ ] [`d0b93e76c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0b93e76c7b05320904ca443b4feaf78d02187cd) (@materializer)
* [ ] [`1b6df3907` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1b6df390749beb41de2fddcd5da80c13f293ed0c) (@materializer)
* [ ] [`a8134a169` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a8134a169cf4821d40ab18d30bf2a4692b73991d) (@materializer)
* [ ] [`21c16338c` release: bump to version v0.43.0](https://github.com/MaterializeInc/materialize/commit/21c16338cc1e4b600d83adf0cdf3365175f3739d) (@guswynn)

**Comment by guswynn** [comment]
all commits minus mine look good!

**Comment by benesch** [comment]
All unreviewed PRs and commits LGTM.
