### ISSUE TITLE
release: v0.44.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17710]
The following PRs in [`v0.44.0`](https://github.com/MaterializeInc/materialize/tree/v0.44.0) require review:
* [x] [#17600 cloud-canary: Use environmentd image to obtain mz_version()](https://github.com/MaterializeInc/materialize/pull/17600) (@philip-stoev)
* [x] [#17621 mz: tackle some bugs](https://github.com/MaterializeInc/materialize/pull/17621) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`e77329359` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e773293593931686dbe7d5e5685b5197390106e8) (@materializer)
* [x] [`2637de425` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/2637de4250f4680be131ce50b62bc7ce24dcf67f) (@materializer)
* [x] [`c09957077` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c09957077214607034bb5044bd339c2fd5525cee) (@materializer)
* [x] [`88bb25d31` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/88bb25d31504b4b3c09d709b323142c640ad82e5) (@materializer)
* [x] [`c0dc149e4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c0dc149e4bddfc350a3fee38b27e53a7585537a7) (@materializer)
* [x] [`6d98583eb` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6d98583eb753f24fc335be9e32635eb42a5bee91) (@materializer)
* [x] [`805a76fd6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/805a76fd6fcc66e87cb809df404717697107bb67) (@materializer)
* [x] [`d933c47ea` release: bump to version v0.44.0](https://github.com/MaterializeInc/materialize/commit/d933c47eaeddf30acb5c81719bcdd2ac77d510cd) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#17600 cloud-canary: Use environmentd image to obtain mz_version()](https://github.com/MaterializeInc/materialize/pull/17600) (@philip-stoev)
* [ ] [#17612 release: bump to version v0.44.0-dev](https://github.com/MaterializeInc/materialize/pull/17612) (@guswynn)
* [ ] [#17615 repr: safeguard `tracing::error` call from #17577](https://github.com/MaterializeInc/materialize/pull/17615) (@aalexandrov)
* [ ] [#16874 mz: various improvements](https://github.com/MaterializeInc/materialize/pull/16874) (@benesch)
* [ ] [#17621 mz: tackle some bugs](https://github.com/MaterializeInc/materialize/pull/17621) (@benesch)
* [ ] [#17558 Doc: update DataGrip support level status](https://github.com/MaterializeInc/materialize/pull/17558) (@bobbyiliev)
* [ ] [#17242 doc/user: explain timestamp](https://github.com/MaterializeInc/materialize/pull/17242) (@joacoc)
* [ ] [#17639 Cloud canary kafka sources](https://github.com/MaterializeInc/materialize/pull/17639) (@philip-stoev)
* [ ] [#17521 transform: push predicates through `TopK` and `Threshold`](https://github.com/MaterializeInc/materialize/pull/17521) (@aalexandrov)
* [ ] [#17646 adapter: prevent `ALTER .. SIZE` on unlinked sources and sinks](https://github.com/MaterializeInc/materialize/pull/17646) (@benesch)
* [ ] [#17637 adapter,compute*: dynamic config of persist_source flow control](https://github.com/MaterializeInc/materialize/pull/17637) (@teskje)
* [ ] [#17483 storage/cluster-unification: multi-process storage clusters](https://github.com/MaterializeInc/materialize/pull/17483) (@guswynn)
* [ ] [#17653 storage: followups from multi-process storage replicas](https://github.com/MaterializeInc/materialize/pull/17653) (@guswynn)
* [ ] [#17617 [persist] Pull stats for all the recent rollups in an environment](https://github.com/MaterializeInc/materialize/pull/17617) (@bkirwi)
* [ ] [#17644 Support non-append-only COUNTER sources](https://github.com/MaterializeInc/materialize/pull/17644) (@umanwizard)
* [ ] [#17647 compute-client: retry connecting to replicas more eagerly](https://github.com/MaterializeInc/materialize/pull/17647) (@teskje)
* [ ] [#17663  Remove dmesg from artifacts](https://github.com/MaterializeInc/materialize/pull/17663) (@def-)
* [ ] [#17614 Platform checks: Add strange identifiers check (fixes #17513)](https://github.com/MaterializeInc/materialize/pull/17614) (@def-)
* [ ] [#17623 Mz  restrict profile names](https://github.com/MaterializeInc/materialize/pull/17623) (@joacoc)
* [ ] [#17655 storage: restore pg-snapshot-partial-failure test](https://github.com/MaterializeInc/materialize/pull/17655) (@guswynn)
* [ ] [#17671 Minor fix in join optimization docs](https://github.com/MaterializeInc/materialize/pull/17671) (@ggevay)
* [ ] [#17673 Print human-readable error messages when build fails due to Protobuf issues](https://github.com/MaterializeInc/materialize/pull/17673) (@umanwizard)
* [ ] [#17604 explain: implement `timing` option](https://github.com/MaterializeInc/materialize/pull/17604) (@aalexandrov)
* [ ] [#17603 storage: principled cross-collection since handling](https://github.com/MaterializeInc/materialize/pull/17603) (@aljoscha)
* [ ] [#17676 persist: create and alter consensus table in a single batch](https://github.com/MaterializeInc/materialize/pull/17676) (@guswynn)
* [ ] [#17674 platform-checks: Try shuffling checks in sequential runs](https://github.com/MaterializeInc/materialize/pull/17674) (@def-)
* [ ] [#17695 doc/user: polish v0.43 release notes](https://github.com/MaterializeInc/materialize/pull/17695) (@morsapaes)
* [ ] [#17691 environmentd: deflake test_auth_base](https://github.com/MaterializeInc/materialize/pull/17691) (@mjibson)
* [ ] [#17685 qa: (attempt to) speed up KillClusterdStorage scenario](https://github.com/MaterializeInc/materialize/pull/17685) (@guswynn)
* [ ] [#17699 storage: make pg-snapshot-partial-failure more realistic](https://github.com/MaterializeInc/materialize/pull/17699) (@guswynn)
* [ ] [#17675 sql: Normalize create secret statements](https://github.com/MaterializeInc/materialize/pull/17675) (@jkosh44)
* [ ] [#17687 storage: drop all ingestion exports when dropping IDed dataflow](https://github.com/MaterializeInc/materialize/pull/17687) (@sploiselle)
* [ ] [#17656 persist: introduce additional granularity into usage tracking](https://github.com/MaterializeInc/materialize/pull/17656) (@danhhz)
* [ ] [#17555 adapter: switch mz_storage_usage_by_shard to track (3a)](https://github.com/MaterializeInc/materialize/pull/17555) (@danhhz)
* [ ] [#17622 environmentd: add `storage_usage_retention_threshold`](https://github.com/MaterializeInc/materialize/pull/17622) (@necaris)
* [ ] [#17700 Get rid of `cpu_percent_normalized`](https://github.com/MaterializeInc/materialize/pull/17700) (@umanwizard)
* [ ] [`e77329359` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e773293593931686dbe7d5e5685b5197390106e8) (@materializer)
* [ ] [`2637de425` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/2637de4250f4680be131ce50b62bc7ce24dcf67f) (@materializer)
* [ ] [`c09957077` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c09957077214607034bb5044bd339c2fd5525cee) (@materializer)
* [ ] [`88bb25d31` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/88bb25d31504b4b3c09d709b323142c640ad82e5) (@materializer)
* [ ] [`c0dc149e4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c0dc149e4bddfc350a3fee38b27e53a7585537a7) (@materializer)
* [ ] [`6d98583eb` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6d98583eb753f24fc335be9e32635eb42a5bee91) (@materializer)
* [ ] [`805a76fd6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/805a76fd6fcc66e87cb809df404717697107bb67) (@materializer)
* [ ] [`d933c47ea` release: bump to version v0.44.0](https://github.com/MaterializeInc/materialize/commit/d933c47eaeddf30acb5c81719bcdd2ac77d510cd) (@umanwizard)

**Comment by arusahni** [comment]
LGTM!
