### ISSUE TITLE
release: v0.44.1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17748]
No PRs in [`v0.44.1`](https://github.com/MaterializeInc/materialize/tree/v0.44.1) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`6aa8e702c` Revert "Merge pull request #17555 from danhhz/persist_usage"](https://github.com/MaterializeInc/materialize/commit/6aa8e702cb33aec345c321ccf08f2e978b9e732c) (@bkirwi)
* [x] [`ffa0423f7` environmentd: allow cors *. prefixes (#17711)](https://github.com/MaterializeInc/materialize/commit/ffa0423f7eb6803f7a79b8199ab8eda4ccf301d2) (@bkirwi)
* [x] [`fc4785e07` release: bump to version v0.44.1](https://github.com/MaterializeInc/materialize/commit/fc4785e07fd0acb92224d7837011225e703e2b81) (@bkirwi)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`6aa8e702c` Revert "Merge pull request #17555 from danhhz/persist_usage"](https://github.com/MaterializeInc/materialize/commit/6aa8e702cb33aec345c321ccf08f2e978b9e732c) (@bkirwi)
* [ ] [`ffa0423f7` environmentd: allow cors *. prefixes (#17711)](https://github.com/MaterializeInc/materialize/commit/ffa0423f7eb6803f7a79b8199ab8eda4ccf301d2) (@bkirwi)
* [ ] [`fc4785e07` release: bump to version v0.44.1](https://github.com/MaterializeInc/materialize/commit/fc4785e07fd0acb92224d7837011225e703e2b81) (@bkirwi)

**Comment by benesch** [comment]
Unreviewed commits and PRs look good to me.
