### ISSUE TITLE
release: v0.44.3 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17778]
No PRs in [`v0.44.3`](https://github.com/MaterializeInc/materialize/tree/v0.44.3) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`0df1d8819` Revert "Revert "Merge pull request #17656 from danhhz/persist_usage_granularity""](https://github.com/MaterializeInc/materialize/commit/0df1d8819830c2e58be8205b83b7a240b11db2a2) (@umanwizard)
* [ ] [`46ca6403a` Revert "Revert "Merge pull request #17555 from danhhz/persist_usage""](https://github.com/MaterializeInc/materialize/commit/46ca6403acce6d074e7cce708bfa9e4fb4624a12) (@umanwizard)
* [ ] [`566ed1a05` Merge pull request #17765 from danhhz/persist_usage](https://github.com/MaterializeInc/materialize/commit/566ed1a055a9e5b95437efd5225d0c0ab714c45d) (@umanwizard)
* [ ] [`f09366aea` persist: support uninitialized shards in `fetch_all_live_states`](https://github.com/MaterializeInc/materialize/commit/f09366aead6664add24a357aba347dff4c5deb55) (@umanwizard)
* [ ] [`d67604031` Merge pull request #17759 from aljoscha/storage-info-logging-for-sinks](https://github.com/MaterializeInc/materialize/commit/d67604031f00c2850814fa3edff96a543229d0e9) (@umanwizard)
* [ ] [`4a1d75d53` release: bump to version v0.44.3](https://github.com/MaterializeInc/materialize/commit/4a1d75d53b1c3f11d8ddcdfceb018387e97668e1) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`0df1d8819` Revert "Revert "Merge pull request #17656 from danhhz/persist_usage_granularity""](https://github.com/MaterializeInc/materialize/commit/0df1d8819830c2e58be8205b83b7a240b11db2a2) (@umanwizard)
* [ ] [`46ca6403a` Revert "Revert "Merge pull request #17555 from danhhz/persist_usage""](https://github.com/MaterializeInc/materialize/commit/46ca6403acce6d074e7cce708bfa9e4fb4624a12) (@umanwizard)
* [ ] [`566ed1a05` Merge pull request #17765 from danhhz/persist_usage](https://github.com/MaterializeInc/materialize/commit/566ed1a055a9e5b95437efd5225d0c0ab714c45d) (@umanwizard)
* [ ] [`f09366aea` persist: support uninitialized shards in `fetch_all_live_states`](https://github.com/MaterializeInc/materialize/commit/f09366aead6664add24a357aba347dff4c5deb55) (@umanwizard)
* [ ] [`d67604031` Merge pull request #17759 from aljoscha/storage-info-logging-for-sinks](https://github.com/MaterializeInc/materialize/commit/d67604031f00c2850814fa3edff96a543229d0e9) (@umanwizard)
* [ ] [`4a1d75d53` release: bump to version v0.44.3](https://github.com/MaterializeInc/materialize/commit/4a1d75d53b1c3f11d8ddcdfceb018387e97668e1) (@umanwizard)

**Comment by benesch** [comment]
LGTM
