### ISSUE TITLE
release: v0.45.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#17994]
The following PRs in [`v0.45.0`](https://github.com/MaterializeInc/materialize/tree/v0.45.0) require review:
* [x] [#17507 storage,test: verify that broker/schema-registry errors are reported on source creation](https://github.com/MaterializeInc/materialize/pull/17507) (@aljoscha)
* [x] [#17088 doc/user: add a source troubleshooting guide](https://github.com/MaterializeInc/materialize/pull/17088) (@benesch)
* [x] [#17274 doc/user: update Get Started guide + consolidate Quickstarts](https://github.com/MaterializeInc/materialize/pull/17274) (@morsapaes)
* [x] [#17817 doc/user: bump v0.42 `patch` to 4](https://github.com/MaterializeInc/materialize/pull/17817) (@morsapaes)
* [x] [#17812 doc/user: patch Get Started ahead of v0.44](https://github.com/MaterializeInc/materialize/pull/17812) (@morsapaes)
* [x] [#17822 .github: Route the "debugging experience" issues better (Part #2)](https://github.com/MaterializeInc/materialize/pull/17822) (@philip-stoev)
* [x] [#17751 doc/user: restructure `CREATE CONNECTION` page](https://github.com/MaterializeInc/materialize/pull/17751) (@morsapaes)
* [x] [#17919 Reject null bytes in quoted identifiers in the lexer](https://github.com/MaterializeInc/materialize/pull/17919) (@umanwizard)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`aa9dd377a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aa9dd377aafd4b0f50785cb96620d2173de4135c) (@materializer)
* [ ] [`8c1976fa1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8c1976fa1280009855bae916bee10dd0a085a273) (@materializer)
* [ ] [`03355126d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/03355126df2be212d52f369a86b7dc85d2a00d5d) (@materializer)
* [ ] [`38f1fa3a3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/38f1fa3a3c30a780d7c30a579dc2a7f16ce8ce9c) (@materializer)
* [ ] [`d0f12134c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0f12134ccc5193361c2a156ec57e821db100ca4) (@materializer)
* [ ] [`7aed83a52` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7aed83a52f3411f8b256133580e31e1220d0d789) (@materializer)
* [ ] [`c4a930b78` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c4a930b78879f214c30e61d1be50802918ab02bf) (@materializer)
* [ ] [`0bae56ee0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0bae56ee07e1cd0c6952e05b0cd776e4f241b659) (@materializer)
* [ ] [`36fb1137c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/36fb1137c334823e07a22fe39c2ccbf402c32afd) (@materializer)
* [ ] [`af51aa80a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/af51aa80af5de60d7d45dabfc41602da1ec4e7ff) (@materializer)
* [ ] [`952e3b61b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/952e3b61b31b6269c3201f1393468df036ad8307) (@materializer)
* [ ] [`bbde0269e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bbde0269e31ae5087231b080b1b6555612fc577c) (@materializer)
* [ ] [`486332472` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/486332472d99025fb8ff0ab0cd6aa44680fa1881) (@materializer)
* [ ] [`38326c17e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/38326c17e804752ca7c27738b476823221285f6b) (@materializer)
* [ ] [`295ccb021` release: bump to version v0.45.0](https://github.com/MaterializeInc/materialize/commit/295ccb021e813b084379c688a045410ef0db208c) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#17712 stash: reconnect on an interval](https://github.com/MaterializeInc/materialize/pull/17712) (@mjibson)
* [ ] [#17711 environmentd: allow cors *. prefixes](https://github.com/MaterializeInc/materialize/pull/17711) (@mjibson)
* [ ] [#17722 sql: remove some unused dummy catalog stuff](https://github.com/MaterializeInc/materialize/pull/17722) (@mjibson)
* [ ] [#17718 adapter: load catalog items in less-Ord dependent way](https://github.com/MaterializeInc/materialize/pull/17718) (@sploiselle)
* [ ] [#17723 sql: apply AST transforms to all expressions](https://github.com/MaterializeInc/materialize/pull/17723) (@benesch)
* [ ] [#17720 sql: fix bug in `HirRelationExpr::apply_to`](https://github.com/MaterializeInc/materialize/pull/17720) (@aalexandrov)
* [ ] [#17726 release: bump to version v0.45.0-dev](https://github.com/MaterializeInc/materialize/pull/17726) (@umanwizard)
* [ ] [#17507 storage,test: verify that broker/schema-registry errors are reported on source creation](https://github.com/MaterializeInc/materialize/pull/17507) (@aljoscha)
* [ ] [#17737 sql: transform SHOW queries before planning](https://github.com/MaterializeInc/materialize/pull/17737) (@benesch)
* [ ] [#17743 stroage: subset of commits from #15813](https://github.com/MaterializeInc/materialize/pull/17743) (@sploiselle)
* [ ] [#17749 adapter: implement pg_proc.prorettype](https://github.com/MaterializeInc/materialize/pull/17749) (@mjibson)
* [ ] [#17721 adapter: add `EXPLAIN BROKEN` support](https://github.com/MaterializeInc/materialize/pull/17721) (@aalexandrov)
* [ ] [#17681 compute: avoid FrontierUppers regressions](https://github.com/MaterializeInc/materialize/pull/17681) (@teskje)
* [ ] [#17757 deps: upgrade timely](https://github.com/MaterializeInc/materialize/pull/17757) (@teskje)
* [ ] [#17759 storage: in controller, upgrade debug logging to info around sinks/exports](https://github.com/MaterializeInc/materialize/pull/17759) (@aljoscha)
* [ ] [#17744 mzcompose: Update Redpanda to v22.3.13](https://github.com/MaterializeInc/materialize/pull/17744) (@BenPope)
* [ ] [#17765 persist: fix "blob inputs should be cumulative" panic in usage.](https://github.com/MaterializeInc/materialize/pull/17765) (@danhhz)
* [ ] [#17766 docs: Fix sum docs](https://github.com/MaterializeInc/materialize/pull/17766) (@jkosh44)
* [ ] [#17709 Transform panic in `uint2` and `uint4` sums under invalid accumulations into SQL-level error](https://github.com/MaterializeInc/materialize/pull/17709) (@vmarcos)
* [ ] [#17764 bin/mz: Do not treat inability to open browser as a fatal error](https://github.com/MaterializeInc/materialize/pull/17764) (@antifuchs)
* [ ] [#17761 When logging JSON, include the current span information](https://github.com/MaterializeInc/materialize/pull/17761) (@antifuchs)
* [ ] [#17771 Slightly improve a few comments in the parser](https://github.com/MaterializeInc/materialize/pull/17771) (@umanwizard)
* [ ] [#17773 persist: support uninitialized shards in `fetch_all_live_states`](https://github.com/MaterializeInc/materialize/pull/17773) (@danhhz)
* [ ] [#17088 doc/user: add a source troubleshooting guide](https://github.com/MaterializeInc/materialize/pull/17088) (@benesch)
* [ ] [#17770 sql: Fix column constraints for read-then-writes](https://github.com/MaterializeInc/materialize/pull/17770) (@jkosh44)
* [ ] [#17772 Implement ceiling](https://github.com/MaterializeInc/materialize/pull/17772) (@dseisun-materialize)
* [ ] [#17774 Bind to `0.0.0.0`, not a DNS name.](https://github.com/MaterializeInc/materialize/pull/17774) (@umanwizard)
* [ ] [#17717 [persist] Always perform routine maintenance (take two)](https://github.com/MaterializeInc/materialize/pull/17717) (@bkirwi)
* [ ] [#17769 optimizer: hoist type knowledge into transform::normalize_lets](https://github.com/MaterializeInc/materialize/pull/17769) (@sploiselle)
* [ ] [#17482 Design review process revamp](https://github.com/MaterializeInc/materialize/pull/17482) (@antiguru)
* [ ] [#17786 storage: fix graceful sink restarts](https://github.com/MaterializeInc/materialize/pull/17786) (@aljoscha)
* [ ] [#15813 sql+storage: make remap collections queryable](https://github.com/MaterializeInc/materialize/pull/15813) (@sploiselle)
* [ ] [#17787 persist: trim down new (schema'd) parquet serialization](https://github.com/MaterializeInc/materialize/pull/17787) (@danhhz)
* [ ] [#17753 Prune storage usage rows we don't wish to retain](https://github.com/MaterializeInc/materialize/pull/17753) (@necaris)
* [ ] [#17779 http-util: add CORS helper](https://github.com/MaterializeInc/materialize/pull/17779) (@necaris)
* [ ] [#17780 .github: Add an issue template to record problems with the CI or debu…](https://github.com/MaterializeInc/materialize/pull/17780) (@philip-stoev)
* [ ] [#17793 mzcompose: Increase environmentd startup waiting time to 600s](https://github.com/MaterializeInc/materialize/pull/17793) (@philip-stoev)
* [ ] [#17688 buildkite: Generate junit xml file for logged errors](https://github.com/MaterializeInc/materialize/pull/17688) (@def-)
* [ ] [#17795 persist-client: silence unused-import warnings in release builds](https://github.com/MaterializeInc/materialize/pull/17795) (@teskje)
* [ ] [#17796 expr: deterministic logical operators](https://github.com/MaterializeInc/materialize/pull/17796) (@petrosagg)
* [ ] [#17785 adapter: Plumb frontegg admin status through auth](https://github.com/MaterializeInc/materialize/pull/17785) (@jkosh44)
* [ ] [#17801 buildkite: Fix artifact url to be persistent](https://github.com/MaterializeInc/materialize/pull/17801) (@def-)
* [ ] [#17274 doc/user: update Get Started guide + consolidate Quickstarts](https://github.com/MaterializeInc/materialize/pull/17274) (@morsapaes)
* [ ] [#17803 ore: handle multibyte haystacks in LexBuf::consume_str](https://github.com/MaterializeInc/materialize/pull/17803) (@benesch)
* [ ] [#17810 http-util: make CORS test table-driven](https://github.com/MaterializeInc/materialize/pull/17810) (@benesch)
* [ ] [#17814 ci: Fortify kafka-progress.td](https://github.com/MaterializeInc/materialize/pull/17814) (@philip-stoev)
* [ ] [#17782 compute: report errors through subscribe sinks](https://github.com/MaterializeInc/materialize/pull/17782) (@teskje)
* [ ] [#17817 doc/user: bump v0.42 `patch` to 4](https://github.com/MaterializeInc/materialize/pull/17817) (@morsapaes)
* [ ] [#17812 doc/user: patch Get Started ahead of v0.44](https://github.com/MaterializeInc/materialize/pull/17812) (@morsapaes)
* [ ] [#17821 .github: Route the "debugging experience" issues better](https://github.com/MaterializeInc/materialize/pull/17821) (@philip-stoev)
* [ ] [#17822 .github: Route the "debugging experience" issues better (Part #2)](https://github.com/MaterializeInc/materialize/pull/17822) (@philip-stoev)
* [ ] [#17790 sql: misc. range encodings](https://github.com/MaterializeInc/materialize/pull/17790) (@sploiselle)
* [ ] [#17794 compute*: clean up mz_worker_compute_dependencies](https://github.com/MaterializeInc/materialize/pull/17794) (@teskje)
* [ ] [#17829 sql: support tsrange, tstzrange](https://github.com/MaterializeInc/materialize/pull/17829) (@sploiselle)
* [ ] [#17834 Fix docs for mz_environment_id](https://github.com/MaterializeInc/materialize/pull/17834) (@dseisun-materialize)
* [ ] [#17833 adapter: add mz_operators and pg_operator tables](https://github.com/MaterializeInc/materialize/pull/17833) (@mjibson)
* [ ] [#17809 stash: improve error retry heuristics](https://github.com/MaterializeInc/materialize/pull/17809) (@mjibson)
* [ ] [#17658 adapter: support multi-valued settings](https://github.com/MaterializeInc/materialize/pull/17658) (@mjibson)
* [ ] [#17844 ci: Capture only journalctl entries from the current Buildkite step](https://github.com/MaterializeInc/materialize/pull/17844) (@philip-stoev)
* [ ] [#17751 doc/user: restructure `CREATE CONNECTION` page](https://github.com/MaterializeInc/materialize/pull/17751) (@morsapaes)
* [ ] [#17755 github: remove triage label from flake template](https://github.com/MaterializeInc/materialize/pull/17755) (@uce)
* [ ] [#17454 Doc: add link to privatelink tf modules](https://github.com/MaterializeInc/materialize/pull/17454) (@bobbyiliev)
* [ ] [#17848 storage: downgrade resumption frontier logging to debug!](https://github.com/MaterializeInc/materialize/pull/17848) (@aljoscha)
* [ ] [#17825 Add `mz_dataflow_channel_operators`.](https://github.com/MaterializeInc/materialize/pull/17825) (@umanwizard)
* [ ] [#17851 Remove duplicate copyright notices](https://github.com/MaterializeInc/materialize/pull/17851) (@def-)
* [ ] [#17849 platform checks: Pass base_version around](https://github.com/MaterializeInc/materialize/pull/17849) (@def-)
* [ ] [#17854 coord: add pg_auth_members VIEW](https://github.com/MaterializeInc/materialize/pull/17854) (@parker-timmerman)
* [ ] [#17857 mzbuild: Ignore .mypy_cache](https://github.com/MaterializeInc/materialize/pull/17857) (@def-)
* [ ] [#17853 pgwire: parse "options" startup setting](https://github.com/MaterializeInc/materialize/pull/17853) (@mjibson)
* [ ] [#17846 ci: Use unbuffered python output](https://github.com/MaterializeInc/materialize/pull/17846) (@philip-stoev)
* [ ] [#17863 platform checks: Follow up to base_version](https://github.com/MaterializeInc/materialize/pull/17863) (@def-)
* [ ] [#17867 ci: logged-errors followup](https://github.com/MaterializeInc/materialize/pull/17867) (@def-)
* [ ] [#17806 environmentd: Make admin role a required cmd arg](https://github.com/MaterializeInc/materialize/pull/17806) (@jkosh44)
* [ ] [#17873 sql: Create roles if they are authenticated](https://github.com/MaterializeInc/materialize/pull/17873) (@jkosh44)
* [ ] [#17875 adapter: Add migration to remove materialize role](https://github.com/MaterializeInc/materialize/pull/17875) (@jkosh44)
* [ ] [#17727 sql: Add attributes to role](https://github.com/MaterializeInc/materialize/pull/17727) (@jkosh44)
* [ ] [#17852 persist: add connect timeout to CRDB connections](https://github.com/MaterializeInc/materialize/pull/17852) (@pH14)
* [ ] [#17889 adapter: improve "catalog item ... already exists" errors](https://github.com/MaterializeInc/materialize/pull/17889) (@parker-timmerman)
* [ ] [#17886 storage: downgrade errors to warns in pg source ingest](https://github.com/MaterializeInc/materialize/pull/17886) (@sploiselle)
* [ ] [#16475 Remove `skip(1)` from `differential::plan`](https://github.com/MaterializeInc/materialize/pull/16475) (@ggevay)
* [ ] [#17708 Avoid infinite fixpoint loop with `JoinImplementation`](https://github.com/MaterializeInc/materialize/pull/17708) (@ggevay)
* [ ] [#17878 test: add tests for invalid tick interval values](https://github.com/MaterializeInc/materialize/pull/17878) (@moulimukherjee)
* [ ] [#17891 Doc: Fix Privatelink Terraform module note](https://github.com/MaterializeInc/materialize/pull/17891) (@bobbyiliev)
* [ ] [#17808 Correctly inline lets](https://github.com/MaterializeInc/materialize/pull/17808) (@frankmcsherry)
* [ ] [#17893 timely-util: more ergonomic async handle](https://github.com/MaterializeInc/materialize/pull/17893) (@petrosagg)
* [ ] [#17884 workflows: add Slack notification for external issues](https://github.com/MaterializeInc/materialize/pull/17884) (@morsapaes)
* [ ] [#17894 doc/user: polish v0.44 release notes](https://github.com/MaterializeInc/materialize/pull/17894) (@morsapaes)
* [ ] [#17866 storage: fix more race conditions around sinks](https://github.com/MaterializeInc/materialize/pull/17866) (@aljoscha)
* [ ] [#17705 Support rendering for nested and sequenced `LetRec`](https://github.com/MaterializeInc/materialize/pull/17705) (@frankmcsherry)
* [ ] [#17901 ci: Remove CRDB chaos testing Buildkite jobs](https://github.com/MaterializeInc/materialize/pull/17901) (@philip-stoev)
* [ ] [#17903 build(deps): bump minimist from 1.2.5 to 1.2.8 in /test/lang/js](https://github.com/MaterializeInc/materialize/pull/17903) (@dependabot[bot])
* [ ] [#17902 platform checks: Do not run CREATE ROLE in upgrade context](https://github.com/MaterializeInc/materialize/pull/17902) (@philip-stoev)
* [ ] [#17904 ci: logged errors: add forgotten re.VERBOSE](https://github.com/MaterializeInc/materialize/pull/17904) (@def-)
* [ ] [#17905 Put `JoinImplementation` in the same fixpoint loop with `LiteralLifting`](https://github.com/MaterializeInc/materialize/pull/17905) (@ggevay)
* [ ] [#17907 explain: correctly trace `optimize/local` entry + small timing fixes](https://github.com/MaterializeInc/materialize/pull/17907) (@aalexandrov)
* [ ] [#17910 doc: Add style guide for SQL functions](https://github.com/MaterializeInc/materialize/pull/17910) (@jkosh44)
* [ ] [#17920 stash: retry COMMIT indeterminate errors](https://github.com/MaterializeInc/materialize/pull/17920) (@mjibson)
* [ ] [#17919 Reject null bytes in quoted identifiers in the lexer](https://github.com/MaterializeInc/materialize/pull/17919) (@umanwizard)
* [ ] [#17896 doc/user: link to Cube integration guide](https://github.com/MaterializeInc/materialize/pull/17896) (@morsapaes)
* [ ] [#17890 cloudtest: Create shared fate storage cluster test](https://github.com/MaterializeInc/materialize/pull/17890) (@def-)
* [ ] [#17928 adapter: ensure source + subsources created sequentially](https://github.com/MaterializeInc/materialize/pull/17928) (@sploiselle)
* [ ] [`aa9dd377a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aa9dd377aafd4b0f50785cb96620d2173de4135c) (@materializer)
* [ ] [`8c1976fa1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/8c1976fa1280009855bae916bee10dd0a085a273) (@materializer)
* [ ] [`03355126d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/03355126df2be212d52f369a86b7dc85d2a00d5d) (@materializer)
* [ ] [`38f1fa3a3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/38f1fa3a3c30a780d7c30a579dc2a7f16ce8ce9c) (@materializer)
* [ ] [`d0f12134c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0f12134ccc5193361c2a156ec57e821db100ca4) (@materializer)
* [ ] [`7aed83a52` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7aed83a52f3411f8b256133580e31e1220d0d789) (@materializer)
* [ ] [`c4a930b78` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c4a930b78879f214c30e61d1be50802918ab02bf) (@materializer)
* [ ] [`0bae56ee0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0bae56ee07e1cd0c6952e05b0cd776e4f241b659) (@materializer)
* [ ] [`36fb1137c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/36fb1137c334823e07a22fe39c2ccbf402c32afd) (@materializer)
* [ ] [`af51aa80a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/af51aa80af5de60d7d45dabfc41602da1ec4e7ff) (@materializer)
* [ ] [`952e3b61b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/952e3b61b31b6269c3201f1393468df036ad8307) (@materializer)
* [ ] [`bbde0269e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/bbde0269e31ae5087231b080b1b6555612fc577c) (@materializer)
* [ ] [`486332472` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/486332472d99025fb8ff0ab0cd6aa44680fa1881) (@materializer)
* [ ] [`38326c17e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/38326c17e804752ca7c27738b476823221285f6b) (@materializer)
* [ ] [`295ccb021` release: bump to version v0.45.0](https://github.com/MaterializeInc/materialize/commit/295ccb021e813b084379c688a045410ef0db208c) (@guswynn)

**Comment by arusahni** [comment]
LGTM!
