### ISSUE TITLE
[Epic] Improve user experience around clusters, schemas, and ad-hoc selects

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18028]
### Product Outcome
- Reduce OOMs and mistakes stemming from the current mz_introspection flow.
- Users can create objects and issue ad hoc queries intuitively within an expected cluster.
- Users can create objects intuitively within an expected namepace.

This is essential to our top product strategies:
* Support expansion by improving operational confidence
* Begin to exercise unguided onboarding

### Problems & Goals

Right now, there are a number of unexpected or confusing behaviors we require or inadvertently encourage customers to do because of technical limitations. (For example: our current `mz_introspection` cluster implementation requires users to switch clusters for SHOW commands and then promptly switch back. Not performing this workflow properly can cause environmentd OOMs).

The goal of this project is to think about them holistically so that we can tell a clear story to customers around how to use clusters, databases, and schemas in the context of both object creation and queries.

A secondary goal is to make it easier for support to understand outages/degraded behavior and determine quickly whether it was caused by user actions, and if so, which ones. 

### Required Issues

```[tasklist]
### Relegate the `mz_introspection` cluster to targeted, background use cases
- [x] https://github.com/MaterializeInc/materialize/issues/18075.
- [x] https://github.com/MaterializeInc/materialize/issues/17609.
- [x] https://github.com/MaterializeInc/materialize/issues/18094.
```

```[tasklist]
### Provide more intuitive controls for creating objects within schemas and clusters
- [x] https://github.com/MaterializeInc/materialize/issues/17868.
- [x] https://github.com/MaterializeInc/materialize/issues/18027.
- [x] https://github.com/MaterializeInc/materialize/issues/15195 (maybe...pre-work required to figure out if we still want to do this - see the comments on that issue)
```

### Related Tasks
- [ ] https://github.com/MaterializeInc/materialize/issues/18032
- [ ] https://github.com/MaterializeInc/materialize/issues/18030 (maybe not relevant anymore with #18075)
- [x] https://github.com/MaterializeInc/materialize/issues/17608#issuecomment-1466761857
