### ISSUE TITLE
release: v0.46.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18067]
The following PRs in [`v0.46.0`](https://github.com/MaterializeInc/materialize/tree/v0.46.0) require review:
* [x] [#18001 cloudtest: Disable all tests that use failpoints](https://github.com/MaterializeInc/materialize/pull/18001) (@philip-stoev)
* [x] [#17788 doc: explain sourcce progress collections](https://github.com/MaterializeInc/materialize/pull/17788) (@sploiselle)
* [x] [#18015 doc/user: polish v0.45 release notes](https://github.com/MaterializeInc/materialize/pull/18015) (@morsapaes)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`96aa1f44d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/96aa1f44df8ac772dd9397f919f8764138031d6e) (@materializer)
* [x] [`fc743cc07` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fc743cc0708fb45385bd953d7b0c4acae10d832a) (@materializer)
* [x] [`728c5971f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/728c5971f6ed3daf903662f532156f49d0f6f389) (@materializer)
* [x] [`e54c0a0bd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e54c0a0bdb9c72ceb542ad9fee94894d8c3a5056) (@materializer)
* [x] [`1683eb2ee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1683eb2ee605f50b06b4eac85499ac41b9c98eb0) (@materializer)
* [x] [`0f9072ecd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0f9072ecd0e885da3e2e546efbef508cd5ffb501) (@materializer)
* [x] [`e3d1185d6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e3d1185d6fd4b0518c5a3d74f3a954753acc1834) (@materializer)
* [x] [`7745b33f4` release: bump to version v0.46.0](https://github.com/MaterializeInc/materialize/commit/7745b33f424e721b23e89946b793006d56dc0135) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#17503 misc/nix: add shell hook for stdc++ and shellcheck](https://github.com/MaterializeInc/materialize/pull/17503) (@petrosagg)
* [ ] [#17526 [persist] Write fewer, larger batches in the distributed persist sink](https://github.com/MaterializeInc/materialize/pull/17526) (@bkirwi)
* [ ] [#17918 SQL-level invalid accumulation error in bucketed aggregates with a multi-level hierarchy](https://github.com/MaterializeInc/materialize/pull/17918) (@vmarcos)
* [ ] [#17931 adapter: Add a bit of tracing to cover gaps](https://github.com/MaterializeInc/materialize/pull/17931) (@parker-timmerman)
* [ ] [#17958 storage: order-independent decoding](https://github.com/MaterializeInc/materialize/pull/17958) (@petrosagg)
* [ ] [#17888 adapter: Derive superuser attribute from auth](https://github.com/MaterializeInc/materialize/pull/17888) (@jkosh44)
* [ ] [#17939 run.py: Optionally codesign binaries on macOS to support Instruments](https://github.com/MaterializeInc/materialize/pull/17939) (@parker-timmerman)
* [ ] [#17941 stash: configure connect timeout](https://github.com/MaterializeInc/materialize/pull/17941) (@mjibson)
* [ ] [#17949 sql: implement so operator OID tests](https://github.com/MaterializeInc/materialize/pull/17949) (@mjibson)
* [ ] [#17952 Fix the cloudtest upgrade CI job](https://github.com/MaterializeInc/materialize/pull/17952) (@philip-stoev)
* [ ] [#17953 doc: Fix help command in feature-benchmark](https://github.com/MaterializeInc/materialize/pull/17953) (@def-)
* [ ] [#17906 adapter: add mz_subscribes system table](https://github.com/MaterializeInc/materialize/pull/17906) (@teskje)
* [ ] [#17938 release: bump to version v0.46.0-dev](https://github.com/MaterializeInc/materialize/pull/17938) (@guswynn)
* [ ] [#17923 sql: Adding error messages if FOR ALL TABLES or FOR TABLES is specified fo…](https://github.com/MaterializeInc/materialize/pull/17923) (@moulimukherjee)
* [ ] [#17832 sql: add support for uuid_generate_v5 function](https://github.com/MaterializeInc/materialize/pull/17832) (@dseisun-materialize)
* [ ] [#17935 sql: Handle empty publications and missing for table clauses in pg sources](https://github.com/MaterializeInc/materialize/pull/17935) (@moulimukherjee)
* [ ] [#17962 adapter: Store role ID in session](https://github.com/MaterializeInc/materialize/pull/17962) (@jkosh44)
* [ ] [#17960 sql: Pull role attributes out of unsafe mode](https://github.com/MaterializeInc/materialize/pull/17960) (@jkosh44)
* [ ] [#17968 adapter: prevent OOM found by SQLsmith](https://github.com/MaterializeInc/materialize/pull/17968) (@parker-timmerman)
* [ ] [#17967 nightlies: increse checks-upgrade-entire-mz* timeouts](https://github.com/MaterializeInc/materialize/pull/17967) (@guswynn)
* [ ] [#17971 sql: remove DummyCatalog and func return inference](https://github.com/MaterializeInc/materialize/pull/17971) (@mjibson)
* [ ] [#17974 ci: Clean up all docker containers on job start, regardless of origin](https://github.com/MaterializeInc/materialize/pull/17974) (@philip-stoev)
* [ ] [#17976 cloudtest: Run with parallelism=2 in Buildkite](https://github.com/MaterializeInc/materialize/pull/17976) (@philip-stoev)
* [ ] [#17985 adapter: Set a max number of events OpenTelemetry records per-Span](https://github.com/MaterializeInc/materialize/pull/17985) (@parker-timmerman)
* [ ] [#17977 adapter: Add oprleft, oprright columns to pg_operator](https://github.com/MaterializeInc/materialize/pull/17977) (@def-)
* [ ] [#17954 Doc/user: code color styles](https://github.com/MaterializeInc/materialize/pull/17954) (@joacoc)
* [ ] [#17973 sql: Add pg_function_is_visible](https://github.com/MaterializeInc/materialize/pull/17973) (@andrewrodriguez-m)
* [ ] [#17996 slt: script for generating cluster_log_sinks.slt](https://github.com/MaterializeInc/materialize/pull/17996) (@teskje)
* [ ] [#17999 doc/user: Add install->get-started redirect](https://github.com/MaterializeInc/materialize/pull/17999) (@ruf-io)
* [ ] [#17966 Move WMR behind a dedicated feature flag](https://github.com/MaterializeInc/materialize/pull/17966) (@aalexandrov)
* [ ] [#17991 feature benchmark: Add optbench TPCH runs](https://github.com/MaterializeInc/materialize/pull/17991) (@def-)
* [ ] [#18001 cloudtest: Disable all tests that use failpoints](https://github.com/MaterializeInc/materialize/pull/18001) (@philip-stoev)
* [ ] [#18003 storage: bring reclock optimization back](https://github.com/MaterializeInc/materialize/pull/18003) (@petrosagg)
* [ ] [#18004 adapter: fix merge skew in vars declaration](https://github.com/MaterializeInc/materialize/pull/18004) (@aalexandrov)
* [ ] [#17619 design: add design doc for new storage persist_sink](https://github.com/MaterializeInc/materialize/pull/17619) (@guswynn)
* [ ] [#18012 dev: Update .cargo/config to reserve 1 CPU core](https://github.com/MaterializeInc/materialize/pull/18012) (@parker-timmerman)
* [ ] [#18018 ci: Remove the Checks + Restart Redpanda from the per-push CI](https://github.com/MaterializeInc/materialize/pull/18018) (@philip-stoev)
* [ ] [#17788 doc: explain sourcce progress collections](https://github.com/MaterializeInc/materialize/pull/17788) (@sploiselle)
* [ ] [#17995 sql: Move SystemVars to sql so that it's accessible by SessionCatalog](https://github.com/MaterializeInc/materialize/pull/17995) (@andrewrodriguez-m)
* [ ] [#18015 doc/user: polish v0.45 release notes](https://github.com/MaterializeInc/materialize/pull/18015) (@morsapaes)
* [ ] [#17584 storage: reclock resumption frontier in async worker](https://github.com/MaterializeInc/materialize/pull/17584) (@petrosagg)
* [ ] [#18014 mz: fetch regions from sync server](https://github.com/MaterializeInc/materialize/pull/18014) (@RobinClowers)
* [ ] [#18026 Allow unstable dependencies in temporary views](https://github.com/MaterializeInc/materialize/pull/18026) (@umanwizard)
* [ ] [#18037 *: clean up clippy warnings newly present in rust 1.68.0](https://github.com/MaterializeInc/materialize/pull/18037) (@danhhz)
* [ ] [#17998 timely-util: async output handles](https://github.com/MaterializeInc/materialize/pull/17998) (@petrosagg)
* [ ] [#18021 adapter: generate_series returns set](https://github.com/MaterializeInc/materialize/pull/18021) (@def-)
* [ ] [#18025 Add SQLsmith to CI for nightly runs](https://github.com/MaterializeInc/materialize/pull/18025) (@def-)
* [ ] [#18047 doc/user: remove schema qualifiers from Get Started](https://github.com/MaterializeInc/materialize/pull/18047) (@morsapaes)
* [ ] [#18024 doc/user: fix list indentation](https://github.com/MaterializeInc/materialize/pull/18024) (@benesch)
* [ ] [#18058 mz: revert enable psql query timing by default](https://github.com/MaterializeInc/materialize/pull/18058) (@RobinClowers)
* [ ] [#17925 Clippy deny some Differential and Timely APIs](https://github.com/MaterializeInc/materialize/pull/17925) (@antiguru)
* [ ] [#18049 compute: fix update_type in reachability logging](https://github.com/MaterializeInc/materialize/pull/18049) (@teskje)
* [ ] [#18039 adapter: Add indexes for common internal tables for faster UI](https://github.com/MaterializeInc/materialize/pull/18039) (@andrewrodriguez-m)
* [ ] [#18019 storage: work with `Collection` everywhere](https://github.com/MaterializeInc/materialize/pull/18019) (@petrosagg)
* [ ] [#18065 adapter: correct alteration of source/sink size](https://github.com/MaterializeInc/materialize/pull/18065) (@benesch)
* [ ] [`96aa1f44d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/96aa1f44df8ac772dd9397f919f8764138031d6e) (@materializer)
* [ ] [`fc743cc07` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fc743cc0708fb45385bd953d7b0c4acae10d832a) (@materializer)
* [ ] [`728c5971f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/728c5971f6ed3daf903662f532156f49d0f6f389) (@materializer)
* [ ] [`e54c0a0bd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e54c0a0bdb9c72ceb542ad9fee94894d8c3a5056) (@materializer)
* [ ] [`1683eb2ee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1683eb2ee605f50b06b4eac85499ac41b9c98eb0) (@materializer)
* [ ] [`0f9072ecd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0f9072ecd0e885da3e2e546efbef508cd5ffb501) (@materializer)
* [ ] [`e3d1185d6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e3d1185d6fd4b0518c5a3d74f3a954753acc1834) (@materializer)
* [ ] [`7745b33f4` release: bump to version v0.46.0](https://github.com/MaterializeInc/materialize/commit/7745b33f424e721b23e89946b793006d56dc0135) (@umanwizard)

**Comment by benesch** [comment]
All unreviewed PRs and commits LGTM.
