### ISSUE TITLE
`EXPLAIN` pipeline should reflect different optimization paths

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#18089]
### Feature request

Currently, the optimization pipeline executed by `sequence_exphain_plan` in when handling an

```sql
EXPLAIN ... $explainee
```

statement does not reflect the fact that the SQL frontend will actually implement slightly different pipelines depending on the context and object type. We should understand what these differences are and extend the `EXPLAIN` syntax, implementation, and docs so we can look at the correct pipeline.

### Known differences:

* Dataflows (resulting from `CREATE INDEX / SINK / MATERIALIZED VIEW` statements) are "prepared" for execution by evaluating unmaterializable functions upfront (see `prep_relation_expr` / `prep_scalar_expr` / `eval_unmaterializable_func`).
* Peeks modify the `dataflow` using [a slightly different parametrization of `prep_relation_expr`](https://github.com/MaterializeInc/materialize/blob/4bd170b16c3b4b42eccb4df854c1928bf85f8cb4/src/adapter/src/coord/sequencer.rs#L2561-L2582).
* The `CREATE VIEW` optimization path is not complete because conceptually we store the optimized MIR (no `hir_to_mir` pages).
* Fast path selection is only relevant for one-shot `SELECT` statements.
* ~Specialized rendering for one-shot selects is not reflected (#18546) in `sequence_explain_plan`.~
* ~The `target_cluster` for fast path queries is currently not considered in `EXPLAIN` (#19119, #18310, #20652).~

### Proposed syntax extension

I suggest to determine the optimization path to trace / explain based on the statement:

```sql
EXPLAIN CREATE INDEX $idx_name ON $view -- explain the `sequence_create_index` path
EXPLAIN CREATE VIEW $v as $query -- explain the `sequence_create_view` path
EXPLAIN CREATE MATERIALIZED VIEW $v as $query -- explain the `sequence_create_materialized_view` path
EXPLAIN SELECT $query -- explain the `sequence_peek` path
```

RisingWave [has similar syntax](https://www.risingwave.dev/docs/current/sql-explain/).

### Task list

- [x] ~Add support for `Explainee::CreateMaterializedView` variants~. (done in [#21973](21973))
- [x] Add support for `Explainee::CreateIndex` variants. (done in [#22021](22021))
- [x] ~Remove the `Explainee::Dataflow` variant~. (done in [#20652](20652))
- [x] ~Wrap the HIR plan in the `Explainee::Query` variant~. (done in [#20652](20652))

### Out of scope

Add back support for other `Statement` variants that produce and execute dataflows (listed in the most likely order of importance):

1. `EXPLAIN SUBSCRIBE ...`
1. `EXPLAIN [CREATE] VIEW ...`
1. `EXPLAIN INSERT | UPDATE | DELETE...`

**Comment by aalexandrov** [comment]
@mjibson maybe you or somebody else from @MaterializeInc/surfaces can take a look at the above list and extend it?

**Comment by ggevay** [comment]
+1, this would be great to fix, it's been causing some confusion already: https://github.com/MaterializeInc/materialize/issues/18048#issuecomment-1464909599

**Comment by aalexandrov** [comment]
The biggest challenge that I see here is keeping the explain paths and the actual execution paths in sync. It will be quite easy to add something extra in `sequence_create_materialized_view` but not in the corresponding branch in `sequence_explain_plan`).

**Comment by ggevay** [comment]
Yes. We should put big warning comments in `sequence_create_materialized_view` and similar functions.

**Comment by mjibson** [comment]
`SELECT`s that are after the first statement in a transaction have access to a specific set of indexes (dependent on whatever the first `SELECT` query was). I'm not sure if `EXPLAIN` within a transaction takes the current valid indexes into account or not.

`EXPLAIN TIMESTAMP` has similar problems: (I believe) it doesn't know if it's in a transaction, so won't use the current transaction's timestamp or index set for its output.

**Comment by aalexandrov** [comment]
> I'm not sure if EXPLAIN within a transaction takes the current valid indexes into account or not.

Yes, it uses the available indexes to determine join implementation strategies.

**Comment by mjibson** [comment]
I'm not sure if we're talking about different things or not, or if things have changed and no longer do what they used to, but by "current valid indexes" I mean: "indexes that the in-progress SQL transaction has prevented compaction of to the txn's read timestamp". This is important for cases where a txn starts, then another connection creates an index, then the txn from the first connection runs a SELECT that could use the newly created index but it shouldn't because that index isn't valid at the txn's timestamp.

**Comment by aalexandrov** [comment]
> indexes that the in-progress SQL transaction has prevented compaction of to the txn's read timestamp

I think we are talking about different things. I was thinking about the indexes made available to `optimize_dataflow`

https://github.com/MaterializeInc/materialize/blob/ae9629e8ba329c02eba19e40044731f2fb1c5142/src/transform/src/dataflow.rs#L36-L39

where from what I can see in the `adapter` code the `indexes: &dyn IndexOracle` parameter is always bound to an `ComputeInstanceIndexOracle` instance. I don't think the behavior of the `IndexOracle` implementation for this type will depend on the existence and progress of a surrounding transaction.

https://github.com/MaterializeInc/materialize/blob/baba203a88556cff8a97220924dee381146dcb99/src/adapter/src/coord/indexes.rs#L121-L128

**Comment by ggevay** [comment]
An additional dimension of EXPLAIN variations should be whether we want to see the plan of an already-running dataflow, or whether we want to see what would happen if we ran a CREATE ... command right now.

To print the plan of an already-running dataflow, I guess we would need to save the plans in the catalog. (Which will be needed also by plan pinning soon anyway, but saving it for EXPLAIN is easier, because we can just save it as a string instead of serializing it.)

**Comment by frankmcsherry** [comment]
I was confused by this recently, and wanted to record that the behavior that would have been clarifying (and I would have understood, even though I misused it) is 
```
EXPLAIN <command>
```
where `<command>` is either a `SELECT` command (an ad-hoc query) or a `CREATE` command. The point I mean to stress is that while `SELECT` is ambiguously either a command or a query fragment, the thing to explain would be the command.

**Comment by frankmcsherry** [comment]
Yup! I think the tl;dr for me is that the last line could be `EXPLAIN SELECT $query` instead, flagging it as the command rather than query fragment.

**Comment by teskje** [comment]
So would you then type things like
```
EXPLAIN SELECT SELECT count(*) FROM my_table;
```
?

**Comment by aalexandrov** [comment]
I'm not sure. I think @frankmcsherry interpreted `$query` in

```sql
EXPLAIN $query
```

as a general placeholder for all kinds of statements, whereas I intended to use it as a placeholder for `SELECT` queries.

I guess what I am proposing is

```sql
EXPLAIN $statement
```

where `statement` is something that can be parsed as `Plan::Select`, `Plan::CreateMaterializedView`, `Plan::CreateView`, or `Plan::CreateIndex`.

**Comment by mgree** [comment]
When working on the batch updates (inserts/deletes) for LDBC BI, I've come across some complex queries that I'd like to explain, but they're not `SELECT`s or `CREATE VIEW`s: they're `DELETE`s! Here's an (untranslated) Umbra query:

```sql
DELETE FROM Message
USING (
  WITH RECURSIVE MessagesToDelete AS (
      SELECT id
      FROM Comment_Delete_candidates_unique -- starting from the delete candidate comments
      UNION
      SELECT ChildComment.MessageId AS id
      FROM MessagesToDelete
      JOIN Message ChildComment
        ON ChildComment.ParentMessageId = MessagesToDelete.id
  )
  SELECT id
  FROM MessagesToDelete
  ) sub
WHERE sub.id = Message.MessageId
;
```

The `Comment_Delete_candidates_unique` holds a deletion timestamp and a `Comment` id for every comment to be deleted. Their behavior is to delete the sub-thread below the deleted comment. Being able `EXPLAIN` this query would be nice---I want to check that I'm hitting the right indices, not making cross joins, etc.

**Comment by mjibson** [comment]
Made https://github.com/MaterializeInc/materialize/issues/21304 to track explain delete.
