### ISSUE TITLE
[Epic] Adapter Scalability tracker

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#18222]
This is a high level parent epic to track long-term initiatives for adapter scalability. See the sub-epics for project updates and delivery timelines.

## Product Outcome
- Horizontal scalability: we can support high concurrent request volumes, as well as large writes and reads, within a single environmentd.
- Workload isolation: users performing independent streams of work for the same account are not blocked on each other
- Fast performance: requests return as quickly possible.

## Documentation
- [Planning doc](https://www.notion.so/Environmentd-Adapter-Scaling-Proposal-14a938d03c4e4ad1bc76f240194f2074)

## Issues
```[tasklist]
### Coordinator improvements
- [ ] https://github.com/MaterializeInc/materialize/issues/18184
- [ ] Making coordinator operators proportional to their size
```

```[tasklist]
### Concurrency testing
- [ ] https://github.com/MaterializeInc/materialize/issues/17463
```

```[tasklist]
### Horizontal scalability
- [ ] https://github.com/MaterializeInc/materialize/issues/14568
```

```[tasklist]
### Horizontal scalability
- [ ] Consistency & Session timelines
```

```[tasklist]
### Further items for consideration
- [ ] https://github.com/MaterializeInc/materialize/issues/14052
- [ ] https://github.com/MaterializeInc/materialize/issues/18186
- [ ] Versioned Catalog
- [ ] Optimized plan caching
```
