### ISSUE TITLE
release: v0.47.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18242]
The following PRs in [`v0.47.0`](https://github.com/MaterializeInc/materialize/tree/v0.47.0) require review:
* [x] [#18072 deps: get back onto some mainlines](https://github.com/MaterializeInc/materialize/pull/18072) (@benesch)
* [x] [#18079 ci: automatically sync READMEs to Docker Hub](https://github.com/MaterializeInc/materialize/pull/18079) (@benesch)
* [x] [#18085 ci: don't publish tags for mz](https://github.com/MaterializeInc/materialize/pull/18085) (@benesch)
* [x] [#18086 ci: publish mz](https://github.com/MaterializeInc/materialize/pull/18086) (@benesch)
* [x] [#18099 Fix bug in mz_dataflow_operator_parents](https://github.com/MaterializeInc/materialize/pull/18099) (@umanwizard)
* [x] [#18103 persist: require K: Codec and V: Codec on BatchBuilder struct](https://github.com/MaterializeInc/materialize/pull/18103) (@danhhz)
* [x] [#18111 ci: Move the "Checks + restart CRDB" job to Nightly](https://github.com/MaterializeInc/materialize/pull/18111) (@philip-stoev)
* [x] [#18116 cloudtest: Increase paralellism to 3](https://github.com/MaterializeInc/materialize/pull/18116) (@philip-stoev)
* [x] [#17799 mzcompose: A workflow that tests CRDB rolling restarts](https://github.com/MaterializeInc/materialize/pull/17799) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`262336c5c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/262336c5cb3dbd5f09916a01591c4f2696260513) (@materializer)
* [x] [`e48906f58` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e48906f58099f143efec613c48098e2e832b72b6) (@materializer)
* [x] [`6a07b4a97` mzbuild: handle overridden DOCKER_CONFIG in Image.sync_description](https://github.com/MaterializeInc/materialize/commit/6a07b4a97d2a2e4339810bdbc616e5d90f03a8c0) (@benesch)
* [x] [`55abdce6a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/55abdce6ac0e5f98a95a33587966668fe93a9673) (@materializer)
* [x] [`1821fbe0f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1821fbe0f729970893d2be53904da7aabbf4478a) (@materializer)
* [x] [`d785146d4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d785146d47765f8fb5ecb342c35502fb5f7ef015) (@materializer)
* [x] [`1a2e323d2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1a2e323d2928c77371a0341e7086c17da64d48bd) (@materializer)
* [x] [`5de53939d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5de53939db95abe74957aa7b250fb4662ddab300) (@materializer)
* [ ] [`613cca5c0` release: bump to version v0.47.0](https://github.com/MaterializeInc/materialize/commit/613cca5c00f8e9f7459708d245fbe4a4de5a09c0) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18016 compute: log export-dataflow ID mapping](https://github.com/MaterializeInc/materialize/pull/18016) (@teskje)
* [ ] [#17990 Fallible reduce pair for invalid accumulation error checking in accumulable aggregations](https://github.com/MaterializeInc/materialize/pull/17990) (@vmarcos)
* [ ] [#18064 persist: consolidate as we go in snapshot_and_fetch](https://github.com/MaterializeInc/materialize/pull/18064) (@danhhz)
* [ ] [#18062 Refactor compute logging code for readability](https://github.com/MaterializeInc/materialize/pull/18062) (@teskje)
* [ ] [#18068 release: bump to version v0.47.0-dev](https://github.com/MaterializeInc/materialize/pull/18068) (@umanwizard)
* [ ] [#18070 sql: simplify typeconv::can_cast](https://github.com/MaterializeInc/materialize/pull/18070) (@sploiselle)
* [ ] [#18072 deps: get back onto some mainlines](https://github.com/MaterializeInc/materialize/pull/18072) (@benesch)
* [ ] [#18074 deps: upgrade to arrow v0.16/parquet v0.17](https://github.com/MaterializeInc/materialize/pull/18074) (@benesch)
* [ ] [#18078 storage: remap: keep up with progress updates](https://github.com/MaterializeInc/materialize/pull/18078) (@petrosagg)
* [ ] [#17961 adapter: move user field from Session to SessionVars](https://github.com/MaterializeInc/materialize/pull/17961) (@benesch)
* [ ] [#18079 ci: automatically sync READMEs to Docker Hub](https://github.com/MaterializeInc/materialize/pull/18079) (@benesch)
* [ ] [#18084 build(deps): bump paramiko from 2.12.0 to 3.1.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/18084) (@dependabot[bot])
* [ ] [#18083 build(deps): bump types-setuptools from 65.6.0.2 to 67.6.0.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/18083) (@dependabot[bot])
* [ ] [#18082 build(deps): bump types-psutil from 5.9.5.5 to 5.9.5.10 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/18082) (@dependabot[bot])
* [ ] [#18081 build(deps): bump setuptools from 65.7.0 to 67.6.0 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/18081) (@dependabot[bot])
* [ ] [#18080 build(deps): bump boto3-stubs[ec2,iam,kinesis,s3,sqs,ssm,sts] from 1.26.41 to 1.26.89 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/18080) (@dependabot[bot])
* [ ] [#18085 ci: don't publish tags for mz](https://github.com/MaterializeInc/materialize/pull/18085) (@benesch)
* [ ] [#18046 load test: Extend cloud-canary/mzcompose.py for cloud load testing](https://github.com/MaterializeInc/materialize/pull/18046) (@philip-stoev)
* [ ] [#18090 SQLsmith+Logged Errors CI improvements](https://github.com/MaterializeInc/materialize/pull/18090) (@def-)
* [ ] [#18092 persist-client: Reduce copies in proto serialization](https://github.com/MaterializeInc/materialize/pull/18092) (@parker-timmerman)
* [ ] [#18093 ci: Remove the Checks-one-at-a-time jobs](https://github.com/MaterializeInc/materialize/pull/18093) (@philip-stoev)
* [ ] [#18086 ci: publish mz](https://github.com/MaterializeInc/materialize/pull/18086) (@benesch)
* [ ] [#18011 adapter: Prevent dropping a Compute Sink more than once](https://github.com/MaterializeInc/materialize/pull/18011) (@parker-timmerman)
* [ ] [#18071 Introduce `mz_dataflow_operator_parents` view.](https://github.com/MaterializeInc/materialize/pull/18071) (@umanwizard)
* [ ] [#18099 Fix bug in mz_dataflow_operator_parents](https://github.com/MaterializeInc/materialize/pull/18099) (@umanwizard)
* [ ] [#18101 Refactor catalog transactions](https://github.com/MaterializeInc/materialize/pull/18101) (@andrewrodriguez-m)
* [ ] [#18103 persist: require K: Codec and V: Codec on BatchBuilder struct](https://github.com/MaterializeInc/materialize/pull/18103) (@danhhz)
* [ ] [#18104 sql: compile and test checks for set returning fns](https://github.com/MaterializeInc/materialize/pull/18104) (@mjibson)
* [ ] [#18109 SQLsmith+Logged Errors CI: detect further harmless errors](https://github.com/MaterializeInc/materialize/pull/18109) (@def-)
* [ ] [#18111 ci: Move the "Checks + restart CRDB" job to Nightly](https://github.com/MaterializeInc/materialize/pull/18111) (@philip-stoev)
* [ ] [#18115 storage: fix races to do with rehydration and dropping sources/sinks](https://github.com/MaterializeInc/materialize/pull/18115) (@aljoscha)
* [ ] [#17932 doc/user: `SET`, `SHOW` and `RESET` commands](https://github.com/MaterializeInc/materialize/pull/17932) (@joacoc)
* [ ] [#18116 cloudtest: Increase paralellism to 3](https://github.com/MaterializeInc/materialize/pull/18116) (@philip-stoev)
* [ ] [#17881 mz enable region: Fix pg_isready and other issues](https://github.com/MaterializeInc/materialize/pull/17881) (@antifuchs)
* [ ] [#18010 storage: add a new system var for the future new persist_sink](https://github.com/MaterializeInc/materialize/pull/18010) (@guswynn)
* [ ] [#17877 persist: refactor `shard_source`; remove race between operators](https://github.com/MaterializeInc/materialize/pull/17877) (@pH14)
* [ ] [#18053 persist: single path to update state after CaS mismatches](https://github.com/MaterializeInc/materialize/pull/18053) (@pH14)
* [ ] [#17970 adapter: Check role attributes when executing commands](https://github.com/MaterializeInc/materialize/pull/17970) (@jkosh44)
* [ ] [#18118 docs: Update SHOW docs](https://github.com/MaterializeInc/materialize/pull/18118) (@jkosh44)
* [ ] [#18119 ci: Enable miri for further cargo tests](https://github.com/MaterializeInc/materialize/pull/18119) (@def-)
* [ ] [#18126 Remove cluster replica utilization index. Fixes #18125](https://github.com/MaterializeInc/materialize/pull/18126) (@andrewrodriguez-m)
* [ ] [#18117 Refactor the `limits` Nightly test](https://github.com/MaterializeInc/materialize/pull/18117) (@philip-stoev)
* [ ] [#18133 ci: Ignore 'forced panic' panics](https://github.com/MaterializeInc/materialize/pull/18133) (@philip-stoev)
* [ ] [#16954 zippy: Always generate the expected number of actions](https://github.com/MaterializeInc/materialize/pull/16954) (@philip-stoev)
* [ ] [#18135 limits test: Add a scenario for SUBSCRIBE](https://github.com/MaterializeInc/materialize/pull/18135) (@philip-stoev)
* [ ] [#18130 ci slt: Speed up execution of long-running sqllogictest](https://github.com/MaterializeInc/materialize/pull/18130) (@def-)
* [ ] [#18137 miri: Add separate initializer for SOFT_ASSERTIONS](https://github.com/MaterializeInc/materialize/pull/18137) (@parker-timmerman)
* [ ] [#18139 sqllogictest: Same length timestamps](https://github.com/MaterializeInc/materialize/pull/18139) (@def-)
* [ ] [#18100 coord: Remove objects from Timelines transactionally](https://github.com/MaterializeInc/materialize/pull/18100) (@parker-timmerman)
* [ ] [#18147 adapter: move some send diffs work off coord thread](https://github.com/MaterializeInc/materialize/pull/18147) (@mjibson)
* [ ] [#18034 adapter: Add role membership](https://github.com/MaterializeInc/materialize/pull/18034) (@jkosh44)
* [ ] [#18009 storage: Populate details column with hints to status history](https://github.com/MaterializeInc/materialize/pull/18009) (@moulimukherjee)
* [ ] [#18154 ci slt: Some improvements based on first successful run](https://github.com/MaterializeInc/materialize/pull/18154) (@def-)
* [ ] [#18148 sql: Fix min(int16)](https://github.com/MaterializeInc/materialize/pull/18148) (@andrewrodriguez-m)
* [ ] [#18152 SQLsmith: Ignore new errors that happen when more functions are used](https://github.com/MaterializeInc/materialize/pull/18152) (@def-)
* [ ] [#17980 Introspection sources improvements, part 1](https://github.com/MaterializeInc/materialize/pull/17980) (@teskje)
* [ ] [#18156 sql: disallow null in range flag of create_range](https://github.com/MaterializeInc/materialize/pull/18156) (@sploiselle)
* [ ] [#18178 storage: drop log level of offset commit failures](https://github.com/MaterializeInc/materialize/pull/18178) (@petrosagg)
* [ ] [#18177 SQLsmith: Ignore new error message from create_range](https://github.com/MaterializeInc/materialize/pull/18177) (@def-)
* [ ] [#18127 test: demo fix of #18102](https://github.com/MaterializeInc/materialize/pull/18127) (@sploiselle)
* [ ] [#18054 Fix join plan invalidations by later transforms](https://github.com/MaterializeInc/materialize/pull/18054) (@ggevay)
* [ ] [#18187 platform checks: Reduce the number of clusters involved](https://github.com/MaterializeInc/materialize/pull/18187) (@philip-stoev)
* [ ] [#18151 persist: wire up `next_least_batch` retry params to be configurable](https://github.com/MaterializeInc/materialize/pull/18151) (@pH14)
* [ ] [#18159 doc/user: polish v0.46 release notes](https://github.com/MaterializeInc/materialize/pull/18159) (@morsapaes)
* [ ] [#18149 adapter: Put inner sequence method in private mod](https://github.com/MaterializeInc/materialize/pull/18149) (@jkosh44)
* [ ] [#18155 testdrive: enrich errors with unprocessed rows](https://github.com/MaterializeInc/materialize/pull/18155) (@guswynn)
* [ ] [#18138 Allow some load generators to be monotonic sources](https://github.com/MaterializeInc/materialize/pull/18138) (@tokenrove)
* [ ] [#18140 Replace special-purpose monotonic explode operators with `explode_one`](https://github.com/MaterializeInc/materialize/pull/18140) (@tokenrove)
* [ ] [#18142 persist: placeholder impl of `Schema<SourceData>` for RelationDesc](https://github.com/MaterializeInc/materialize/pull/18142) (@danhhz)
* [ ] [#18189 Fix some regressions introduced by #17658](https://github.com/MaterializeInc/materialize/pull/18189) (@aalexandrov)
* [ ] [#18193 expr: detect char boundaries in LIKE](https://github.com/MaterializeInc/materialize/pull/18193) (@mjibson)
* [ ] [#18150 Updating docs to mention `hint` could be present](https://github.com/MaterializeInc/materialize/pull/18150) (@moulimukherjee)
* [ ] [#18195 sql: correct array_in argument usage](https://github.com/MaterializeInc/materialize/pull/18195) (@mjibson)
* [ ] [#18106 persist: initial skeleton of part stats collection and filtering](https://github.com/MaterializeInc/materialize/pull/18106) (@danhhz)
* [ ] [#18200 adapter: remove start transaction coord message](https://github.com/MaterializeInc/materialize/pull/18200) (@mjibson)
* [ ] [#18158 sql: fix pglegacy char to char, varchar casts](https://github.com/MaterializeInc/materialize/pull/18158) (@sploiselle)
* [ ] [#18191 SQLsmith: Run multiple instances against same server](https://github.com/MaterializeInc/materialize/pull/18191) (@def-)
* [ ] [#18206 ci: Refactor the kafka-matrix test](https://github.com/MaterializeInc/materialize/pull/18206) (@philip-stoev)
* [ ] [#18208 doc/user: small fix in quickstart](https://github.com/MaterializeInc/materialize/pull/18208) (@morsapaes)
* [ ] [#18207 ci: Silence timely 'flushing writer' errors](https://github.com/MaterializeInc/materialize/pull/18207) (@philip-stoev)
* [ ] [#17799 mzcompose: A workflow that tests CRDB rolling restarts](https://github.com/MaterializeInc/materialize/pull/17799) (@philip-stoev)
* [ ] [#18179 testdrive: Reset Materialize with system user](https://github.com/MaterializeInc/materialize/pull/18179) (@jkosh44)
* [ ] [#18198 persist: hook up stats_{collection,filter}_enabled cfgs to LaunchDarkly](https://github.com/MaterializeInc/materialize/pull/18198) (@danhhz)
* [ ] [#18183 compute,adapter: remove dedicated sink `as_of`](https://github.com/MaterializeInc/materialize/pull/18183) (@teskje)
* [ ] [#18217 adapter: Fix bugs with role membership sys table](https://github.com/MaterializeInc/materialize/pull/18217) (@jkosh44)
* [ ] [#17937 Binary variadic introduces null](https://github.com/MaterializeInc/materialize/pull/17937) (@mgree)
* [ ] [#18230 Disallow `log` macros](https://github.com/MaterializeInc/materialize/pull/18230) (@tokenrove)
* [ ] [#18228 persist: fix another potential cause of the missing blob panics](https://github.com/MaterializeInc/materialize/pull/18228) (@danhhz)
* [ ] [#18196 adapter: Add the PUBLIC pseudo role](https://github.com/MaterializeInc/materialize/pull/18196) (@jkosh44)
* [ ] [#18229 Quick fix for merge skew with UuidGenerateV5](https://github.com/MaterializeInc/materialize/pull/18229) (@def-)
* [ ] [#18197 platform-checks: Add GRANT/REVOKE to existing tests](https://github.com/MaterializeInc/materialize/pull/18197) (@def-)
* [ ] [#18223 sql: Fix \d meta command](https://github.com/MaterializeInc/materialize/pull/18223) (@jkosh44)
* [ ] [#18201 slt: extend role tests](https://github.com/MaterializeInc/materialize/pull/18201) (@def-)
* [ ] [`262336c5c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/262336c5cb3dbd5f09916a01591c4f2696260513) (@materializer)
* [ ] [`e48906f58` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e48906f58099f143efec613c48098e2e832b72b6) (@materializer)
* [ ] [`6a07b4a97` mzbuild: handle overridden DOCKER_CONFIG in Image.sync_description](https://github.com/MaterializeInc/materialize/commit/6a07b4a97d2a2e4339810bdbc616e5d90f03a8c0) (@benesch)
* [ ] [`55abdce6a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/55abdce6ac0e5f98a95a33587966668fe93a9673) (@materializer)
* [ ] [`1821fbe0f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1821fbe0f729970893d2be53904da7aabbf4478a) (@materializer)
* [ ] [`d785146d4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d785146d47765f8fb5ecb342c35502fb5f7ef015) (@materializer)
* [ ] [`1a2e323d2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1a2e323d2928c77371a0341e7086c17da64d48bd) (@materializer)
* [ ] [`5de53939d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5de53939db95abe74957aa7b250fb4662ddab300) (@materializer)
* [ ] [`613cca5c0` release: bump to version v0.47.0](https://github.com/MaterializeInc/materialize/commit/613cca5c00f8e9f7459708d245fbe4a4de5a09c0) (@jkosh44)

**Comment by jkosh44** [comment]
All unreviewed commits/PRs that are not mine LGTM.

**Comment by benesch** [comment]
@jkosh44's previously unreviewed commit LGTM.
