### ISSUE TITLE
release: v0.48.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18396]
The following PRs in [`v0.48.0`](https://github.com/MaterializeInc/materialize/tree/v0.48.0) require review:
* [x] [#18202 adapter: resolve startup roles directly from the catalog](https://github.com/MaterializeInc/materialize/pull/18202) (@mjibson)
* [x] [#17805 storage: report actual error for Kafka sink errors](https://github.com/MaterializeInc/materialize/pull/17805) (@aljoscha)
* [x] [#18314 Make `PredicatePushdown` WMR-safe](https://github.com/MaterializeInc/materialize/pull/18314) (@ggevay)
* [x] [#18343 ci: Better SQLancer block detection](https://github.com/MaterializeInc/materialize/pull/18343) (@def-)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`65fbfd384` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/65fbfd384dc80fb183d1211e777f98c4b98faf93) (@materializer)
* [x] [`e06570fe8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e06570fe883348717f67a0404cbb56fc850d6b05) (@materializer)
* [x] [`cba6a0ba2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cba6a0ba203b270727c961808538925f69d6fcf1) (@materializer)
* [x] [`76fd29617` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/76fd29617ca7640ac836bd5d54313ed9cbf6cb87) (@materializer)
* [x] [`1ac8857a1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1ac8857a1943f3f0b2e74387e239549756d51df2) (@materializer)
* [x] [`4f20283e3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4f20283e38b27dd66ea01f2e58e955e6af58edb8) (@materializer)
* [x] [`25e47fcee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/25e47fcee1958c8180a219f99d93679701169f93) (@materializer)
* [x] [`4a3533709` release: bump to version v0.48.0](https://github.com/MaterializeInc/materialize/commit/4a353370958a06e2bd55eca13516a31a0265bf16) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18060 storage: kafka sink encoding as flat map](https://github.com/MaterializeInc/materialize/pull/18060) (@petrosagg)
* [ ] [#18202 adapter: resolve startup roles directly from the catalog](https://github.com/MaterializeInc/materialize/pull/18202) (@mjibson)
* [ ] [#18236 sql-parser: allow compilation to wasm targets](https://github.com/MaterializeInc/materialize/pull/18236) (@mjibson)
* [ ] [#18239 Parse options strings like `-c opt=foo`](https://github.com/MaterializeInc/materialize/pull/18239) (@umanwizard)
* [ ] [#17992 adapter: Remove old migrations](https://github.com/MaterializeInc/materialize/pull/17992) (@jkosh44)
* [ ] [#18205 sql: fix @> range params](https://github.com/MaterializeInc/materialize/pull/18205) (@sploiselle)
* [ ] [#18120 doc/user: Support an additional level for nesting](https://github.com/MaterializeInc/materialize/pull/18120) (@joacoc)
* [ ] [#17975 release qualification: Update workloads to match reality](https://github.com/MaterializeInc/materialize/pull/17975) (@philip-stoev)
* [ ] [#18259 zippy: Allow maximum execution time of the test to be specified](https://github.com/MaterializeInc/materialize/pull/18259) (@philip-stoev)
* [ ] [#18260 platform checks: version check GRANT/REVOKE](https://github.com/MaterializeInc/materialize/pull/18260) (@def-)
* [ ] [#18258 SQLsmith: Larger instance and limited memory for CI runs](https://github.com/MaterializeInc/materialize/pull/18258) (@def-)
* [ ] [#18124 transform: mark trivially `recursion_safe` transforms](https://github.com/MaterializeInc/materialize/pull/18124) (@aalexandrov)
* [ ] [#18264 platform checks: Choose identifiers randomly](https://github.com/MaterializeInc/materialize/pull/18264) (@def-)
* [ ] [#17805 storage: report actual error for Kafka sink errors](https://github.com/MaterializeInc/materialize/pull/17805) (@aljoscha)
* [ ] [#18265 SQLsmith: Also test beta features](https://github.com/MaterializeInc/materialize/pull/18265) (@def-)
* [ ] [#18268 Use Materialized instead of StandaloneMaterialized](https://github.com/MaterializeInc/materialize/pull/18268) (@def-)
* [ ] [#18246 sql: clarify ownership of HirRelationExpr and lowering](https://github.com/MaterializeInc/materialize/pull/18246) (@benesch)
* [ ] [#18275 ore: Fix error message for into_element](https://github.com/MaterializeInc/materialize/pull/18275) (@jkosh44)
* [ ] [#18273 adapter: Prevent connecting as public role](https://github.com/MaterializeInc/materialize/pull/18273) (@jkosh44)
* [ ] [#18271 delete s3 and kinesis source types](https://github.com/MaterializeInc/materialize/pull/18271) (@petrosagg)
* [ ] [#18278 sql: Fix parse create error message](https://github.com/MaterializeInc/materialize/pull/18278) (@jkosh44)
* [ ] [#18279 storage: fix correctness issue of load generators](https://github.com/MaterializeInc/materialize/pull/18279) (@petrosagg)
* [ ] [#17589 storage: multi-worker persist_sink](https://github.com/MaterializeInc/materialize/pull/17589) (@guswynn)
* [ ] [#18247 storage: improve SSH tunnel failure errors](https://github.com/MaterializeInc/materialize/pull/18247) (@benesch)
* [ ] [#18266 ci: Standardize Nightly Zippy execution times to 55m](https://github.com/MaterializeInc/materialize/pull/18266) (@philip-stoev)
* [ ] [#18290 fix a couple of things that slipped through the S3 removal](https://github.com/MaterializeInc/materialize/pull/18290) (@petrosagg)
* [ ] [#18257 frontegg-auth: refactor for reusability](https://github.com/MaterializeInc/materialize/pull/18257) (@benesch)
* [ ] [#18294 platform checks: Fix Check initialization](https://github.com/MaterializeInc/materialize/pull/18294) (@def-)
* [ ] [#18295 Add a test for introspection view consistency](https://github.com/MaterializeInc/materialize/pull/18295) (@teskje)
* [ ] [#18299 sql: Implement pg_get_userbyid function](https://github.com/MaterializeInc/materialize/pull/18299) (@jkosh44)
* [ ] [#18303 storage: make storage-usage test less flaky](https://github.com/MaterializeInc/materialize/pull/18303) (@guswynn)
* [ ] [#18237 persist: introduce mfp pushdown API boundary between persist+compute](https://github.com/MaterializeInc/materialize/pull/18237) (@danhhz)
* [ ] [#18306 slt: Fix default cluster clean up](https://github.com/MaterializeInc/materialize/pull/18306) (@jkosh44)
* [ ] [#18308 slt: Fix error message when run fails](https://github.com/MaterializeInc/materialize/pull/18308) (@jkosh44)
* [ ] [#18317 pgwire: commit session vars on startup](https://github.com/MaterializeInc/materialize/pull/18317) (@mjibson)
* [ ] [#18204 sql: Create subsources using schema of source when applicable](https://github.com/MaterializeInc/materialize/pull/18204) (@moulimukherjee)
* [ ] [#18291 feature-benchmark: Run individual scenarios in Buildkite](https://github.com/MaterializeInc/materialize/pull/18291) (@philip-stoev)
* [ ] [#18288 scratch: add a `forward` command](https://github.com/MaterializeInc/materialize/pull/18288) (@philip-stoev)
* [ ] [#18287 ci: SQLsmith execution time at 55 min](https://github.com/MaterializeInc/materialize/pull/18287) (@def-)
* [ ] [#18293 zippy: Add observability via Prometheus and Grafana](https://github.com/MaterializeInc/materialize/pull/18293) (@philip-stoev)
* [ ] [#18324 upgrade: Add a scenario that upgrades through the previous two Mz rel…](https://github.com/MaterializeInc/materialize/pull/18324) (@philip-stoev)
* [ ] [#18328 ci: Monitor load via sar](https://github.com/MaterializeInc/materialize/pull/18328) (@def-)
* [ ] [#17959 storage: stop silently ignoring NULL keys in upsert source](https://github.com/MaterializeInc/materialize/pull/17959) (@aljoscha)
* [ ] [#18330 slt: add slt file demoing session windows](https://github.com/MaterializeInc/materialize/pull/18330) (@sploiselle)
* [ ] [#18336 Fixes typo](https://github.com/MaterializeInc/materialize/pull/18336) (@SangJunBak)
* [ ] [#18319 release: bump to version v0.48.0-dev](https://github.com/MaterializeInc/materialize/pull/18319) (@benesch)
* [ ] [#18334 adapter: Prevent statements with dropped roles](https://github.com/MaterializeInc/materialize/pull/18334) (@jkosh44)
* [ ] [#18321 CODEOWNERS: change ownership of `doc/user` and `src/mz`](https://github.com/MaterializeInc/materialize/pull/18321) (@morsapaes)
* [ ] [#18311 sql: Allow multiple roles in grant/revoke](https://github.com/MaterializeInc/materialize/pull/18311) (@jkosh44)
* [ ] [#18274 Add SQLancer to CI](https://github.com/MaterializeInc/materialize/pull/18274) (@def-)
* [ ] [#18314 Make `PredicatePushdown` WMR-safe](https://github.com/MaterializeInc/materialize/pull/18314) (@ggevay)
* [ ] [#18331 Mark `UnionBranchCancellation` WMR-safe](https://github.com/MaterializeInc/materialize/pull/18331) (@ggevay)
* [ ] [#18285 adapter: move some catalog work off coord thread](https://github.com/MaterializeInc/materialize/pull/18285) (@mjibson)
* [ ] [#16913 Re-enable coverage](https://github.com/MaterializeInc/materialize/pull/16913) (@tokenrove)
* [ ] [#18343 ci: Better SQLancer block detection](https://github.com/MaterializeInc/materialize/pull/18343) (@def-)
* [ ] [#18349 Support passing in and setting the scheduler name in the pod spec](https://github.com/MaterializeInc/materialize/pull/18349) (@alex-hunt-materialize)
* [ ] [#18348 remove unused dependencies](https://github.com/MaterializeInc/materialize/pull/18348) (@petrosagg)
* [ ] [#18351 ci: Disable SQLancer Having in nightly](https://github.com/MaterializeInc/materialize/pull/18351) (@def-)
* [ ] [#18355 Bump metrics interval from 10s to 60s](https://github.com/MaterializeInc/materialize/pull/18355) (@umanwizard)
* [ ] [#18302 Remove persisted introspection sources](https://github.com/MaterializeInc/materialize/pull/18302) (@teskje)
* [ ] [#17327 storage: finalize dropped shards](https://github.com/MaterializeInc/materialize/pull/17327) (@sploiselle)
* [ ] [#18335 sql: check signed division for overflow](https://github.com/MaterializeInc/materialize/pull/18335) (@tokenrove)
* [ ] [#18350 [design] "Since granularity"](https://github.com/MaterializeInc/materialize/pull/18350) (@umanwizard)
* [ ] [#18359 misc: use LLVM's continuous profiling mode for coverage](https://github.com/MaterializeInc/materialize/pull/18359) (@tokenrove)
* [ ] [#18342 doc: fix broken link in developer guide](https://github.com/MaterializeInc/materialize/pull/18342) (@jseldess)
* [ ] [#18358 Enable some small-batch optimization in tests](https://github.com/MaterializeInc/materialize/pull/18358) (@bkirwi)
* [ ] [#18241 compute: avoid copying data in persist_sink](https://github.com/MaterializeInc/materialize/pull/18241) (@guswynn)
* [ ] [#18365 SQLsmith ci: Add two more known errors and reduce memory available on explain run](https://github.com/MaterializeInc/materialize/pull/18365) (@def-)
* [ ] [#18360 sql: Refactor ObjectType enum](https://github.com/MaterializeInc/materialize/pull/18360) (@jkosh44)
* [ ] [#18280 adapter: Add object owners](https://github.com/MaterializeInc/materialize/pull/18280) (@jkosh44)
* [ ] [#18369 doc: fix link in developer readme](https://github.com/MaterializeInc/materialize/pull/18369) (@jseldess)
* [ ] [#18372 docs: fix architecture overview link](https://github.com/MaterializeInc/materialize/pull/18372) (@jseldess)
* [ ] [#18356 ci: Reenable SQLancer Having and enable SQLancer PQS](https://github.com/MaterializeInc/materialize/pull/18356) (@def-)
* [ ] [#18354 feature-benchmark: Add scenarios around SUBSCRIBE](https://github.com/MaterializeInc/materialize/pull/18354) (@philip-stoev)
* [ ] [#18366 doc/user: polish v0.47 release notes](https://github.com/MaterializeInc/materialize/pull/18366) (@morsapaes)
* [ ] [#18373 persist: remove more clones from various bits under Trace](https://github.com/MaterializeInc/materialize/pull/18373) (@danhhz)
* [ ] [#18380 persist: count compaction fast-path eligible reqs](https://github.com/MaterializeInc/materialize/pull/18380) (@pH14)
* [ ] [#18381 Revert "storage: finalize persist shards when their collections drop"](https://github.com/MaterializeInc/materialize/pull/18381) (@sploiselle)
* [ ] [#18371 storage: increase reliability of ssh connections](https://github.com/MaterializeInc/materialize/pull/18371) (@guswynn)
* [ ] [#18383 environmentd: ignore flaky test](https://github.com/MaterializeInc/materialize/pull/18383) (@danhhz)
* [ ] [#18387 test: Deflake storage usage test](https://github.com/MaterializeInc/materialize/pull/18387) (@jkosh44)
* [ ] [#18385 walkabout: allow building without workspace-hack](https://github.com/MaterializeInc/materialize/pull/18385) (@mjibson)
* [ ] [#18379 Bump openssl to version 0.10.48](https://github.com/MaterializeInc/materialize/pull/18379) (@teskje)
* [ ] [#18390 sql: Add mz_sessions system table](https://github.com/MaterializeInc/materialize/pull/18390) (@jkosh44)
* [ ] [`65fbfd384` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/65fbfd384dc80fb183d1211e777f98c4b98faf93) (@materializer)
* [ ] [`e06570fe8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e06570fe883348717f67a0404cbb56fc850d6b05) (@materializer)
* [ ] [`cba6a0ba2` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/cba6a0ba203b270727c961808538925f69d6fcf1) (@materializer)
* [ ] [`76fd29617` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/76fd29617ca7640ac836bd5d54313ed9cbf6cb87) (@materializer)
* [ ] [`1ac8857a1` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1ac8857a1943f3f0b2e74387e239549756d51df2) (@materializer)
* [ ] [`4f20283e3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4f20283e38b27dd66ea01f2e58e955e6af58edb8) (@materializer)
* [ ] [`25e47fcee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/25e47fcee1958c8180a219f99d93679701169f93) (@materializer)
* [ ] [`4a3533709` release: bump to version v0.48.0](https://github.com/MaterializeInc/materialize/commit/4a353370958a06e2bd55eca13516a31a0265bf16) (@guswynn)
