### ISSUE TITLE
release: v0.48.3 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18451]
No PRs in [`v0.48.3`](https://github.com/MaterializeInc/materialize/tree/v0.48.3) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`8359b3409` Fix monotonic top-k bug #18445](https://github.com/MaterializeInc/materialize/commit/8359b3409972637e712ad6a1b53a4694c64ab67e) (@guswynn)
* [x] [`34d922331` persist: activate shard_source_descs on drop of token/channel rx (#18434)](https://github.com/MaterializeInc/materialize/commit/34d92233192c584823bc676975d297cefbc93b4c) (@guswynn)
* [x] [`e5988b9c4` release: bump to version v0.48.3](https://github.com/MaterializeInc/materialize/commit/e5988b9c4ecf76a125544d03c898f1d1b6d3605c) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [`8359b3409` Fix monotonic top-k bug #18445](https://github.com/MaterializeInc/materialize/commit/8359b3409972637e712ad6a1b53a4694c64ab67e) (@guswynn)
* [ ] [`34d922331` persist: activate shard_source_descs on drop of token/channel rx (#18434)](https://github.com/MaterializeInc/materialize/commit/34d92233192c584823bc676975d297cefbc93b4c) (@guswynn)
* [ ] [`e5988b9c4` release: bump to version v0.48.3](https://github.com/MaterializeInc/materialize/commit/e5988b9c4ecf76a125544d03c898f1d1b6d3605c) (@guswynn)

**Comment by arusahni** [comment]
LGTM!
