### ISSUE TITLE
[Epic] Improve the usability and reliability of `SSH TUNNEL`s

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#18490]
## Product Outcome
SSH tunnel connections are resilient and observable

#### Context
Over the past few weeks, its become clear there are usability, reliability, and debuggability issues with `SSH TUNNEL`s, particularly when used with kafka. This issue tracks a set of improvements that can be made `SSH TUNNEL`s:

### Reliability
- [x] https://github.com/MaterializeInc/materialize/pull/18371
  - releasing in 0.48
- [x] https://github.com/MaterializeInc/materialize/pull/18547
- [x] Ssh tunnels are possibly transiently broken on macos:
  - Fixed https://github.com/MaterializeInc/materialize/pull/18437
- [x] Ssh tunnel connections transiently panic, at least in ci
  - https://buildkite.com/materialize/tests/builds/52408#018724a9-8ece-4afa-affc-319bc1d475e5
  - this assert is hit: https://github.com/openssh-rust/tokio-io-utility/blob/main/src/async_read_utility/inner.rs#L206 
  - Filed upstream as: https://github.com/openssh-rust/tokio-io-utility/issues/17
  - [x] https://github.com/MaterializeInc/materialize/pull/18591
- [ ] ssh connections are mysteriously broken with "the connection was terminated" in production
  - [ ] This is a problem with the control master 
- [x] https://github.com/MaterializeInc/materialize/issues/19252

### Usability
- [ ] Newly advertised kafka brokers aren't routed through tunnels - https://github.com/MaterializeInc/materialize/issues/18375
  - [ ] Fixed in https://github.com/MaterializeInc/materialize/pull/18454
- [ ] [Much lower priority] Harden tunnels by supporting multiple bastions
  - https://www.notion.so/materialize/SSH-tunnel-hardening-e4a4add751754876b32a65c3cf73a714 

### Debuggability (and documentation)
- [ ] https://github.com/MaterializeInc/materialize/issues/18683
- [ ] Broken connections to ssh aren't not communicated to users (related to https://github.com/MaterializeInc/materialize/issues/17826)
  - [x] Source pipeline creation errors are panics, and not routed to `mz_source_status_history`
    - https://github.com/MaterializeInc/materialize/issues/18491 
  - [ ] `mz_source_statuses` doesn't communicate whether or not the errors reported from rdkafka have ssh as an underlying cause
    - [ ] https://github.com/MaterializeInc/materialize/pull/18616
      - [ ] afterwards, enrich errors with rdkafka callbacks
      - [ ] add connection status polling to postgres sources
      - [ ] Consider checking the status at a higher-level: https://github.com/MaterializeInc/materialize/pull/18616#pullrequestreview-1374985692
  - [x] ssh tunnel errors don't communicate the underlying cause of the broken pipe
    - This is particularly helpful when the user forgets to authorize the tunnel keys  
    - [x] https://github.com/MaterializeInc/materialize/pull/18517
- [ ] How to debug ssh connection errors needs to be documented better
  - [ ] https://github.com/MaterializeInc/materialize/issues/18489

**Comment by benesch** [comment]
> Harden tunnels by supporting multiple bastions

I'd propose skipping this one for now! It's a big lift to make it work reliably (how do you detect if a connection has stalled and needs to be restarted in the other SSH bastion?), and I think we have a good workaround (asking customers to ping their SSH bastions and restart them if they fail).

**Comment by guswynn** [comment]
@benesch I mentioned the order of priority here: https://materializeinc.slack.com/archives/C04DJT084KA/p1680117095320179, ill transfer this context to the issue!

**Comment by benesch** [comment]
Awesome, thanks!

**Comment by benesch** [comment]
Wanted to record some thoughts from debugging SSH tunnels over the weekend:

  * We need a more principled take on when and how to report SSH tunnel errors. Right now we'll report an _initial_ SSH tunnel error, but not any future SSH tunnel errors.
    * Chatted with Gus about this a bit today. There's a perhaps not so bad path to improving this, starting by consistentizing Kafka errors. Everywhere we report a Kafka error, we should a) use a metadata fetch request and report only the errors from that API, and b) always prefer to report any SSH tunnel error rather than a Kafka error.
  * The reported error when a PostgreSQL connection fails is terrible (often just "failed to connect to remote host" regardless of whether the SSH tunnel failed, or the SSH credentials were wrong, or the PostgreSQL server was down, or the PostgreSQL credentials were wrong). AFAICT, the error message details _are_ available, but we store the error in [`PlanError::FetchingPostgresPublicationInfoFailed`](https://github.com/MaterializeInc/materialize/blob/bc93581a3680371a8f51345284a6674003823d76/src/sql/src/plan/error.rs#L110), which embeds a `PostgresError::Generic`, which embeds an `anyhow::Error`, which contains "failed to connect to remote host" as the top-level error, with the true cause _embedded within_. Convincing this error to print its causal chain is REALLY hard. You can't convert `Arc<PostgresError>` to an `anyhow::Error`, which means you can't use anyhow's support for printing causal chains. I think we need a rule like "you can never put an anyhow::Error instead another error type; you can only use them at the top level" since otherwise it all falls apart.

**Comment by aljoscha** [comment]
yes! There is https://github.com/MaterializeInc/materialize/issues/17826, which we still need to flesh out

**Comment by aljoscha** [comment]
>     * The reported error when a PostgreSQL connection fails is terrible (often just "failed to connect to remote host" regardless of whether the SSH tunnel failed, or the SSH credentials were wrong, or the PostgreSQL server was down, or the PostgreSQL credentials were wrong). AFAICT, the error message details _are_ available, but we store the error in [`PlanError::FetchingPostgresPublicationInfoFailed`](https://github.com/MaterializeInc/materialize/blob/bc93581a3680371a8f51345284a6674003823d76/src/sql/src/plan/error.rs#L110), which embeds a `PostgresError::Generic`, which embeds an `anyhow::Error`, which contains "failed to connect to remote host" as the top-level error, with the true cause _embedded within_. Convincing this error to print its causal chain is REALLY hard. You can't convert `Arc<PostgresError>` to an `anyhow::Error`, which means you can't use anyhow's support for printing causal chains. I think we need a rule like "you can never put an anyhow::Error instead another error type; you can only use them at the top level" since otherwise it all falls apart.

I think we can actually print the chain of errors, see https://github.com/MaterializeInc/materialize/pull/18583. We might have to do some more work to ensure that all the errors are actually there.

For `PostgresError::Generic` this works because the variants are all `#[error(transparent)]` so we get the `Display` impl of the wrapped error. @benesch I think your example uses `PostgresError::Ssh` or `PostgresError::SshIo`, for which this doesn't work. We'd have to write a custom `Display` impl for `PostgresError` to get those to work nicely, I'm afraid (typing that up quickly, to see).

**Comment by benesch** [comment]
Closing as this is now complete enough!
