### ISSUE TITLE
release: v0.49.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18541]
No PRs in [`v0.49.0`](https://github.com/MaterializeInc/materialize/tree/v0.49.0) require review.

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`84dc30bf3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/84dc30bf3a3e8d313b6635155dc93b7bfb1d2236) (@materializer)
* [x] [`76eca481a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/76eca481a46f6eb780989721677cfd25f6c6b8be) (@materializer)
* [x] [`07f8e607e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/07f8e607e17c3015c946909db9c6905d3b4f8f76) (@materializer)
* [x] [`28a4fadee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/28a4fadeedb2a1a856e8c5b29664c958a3a5723f) (@materializer)
* [x] [`6636afa2f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6636afa2f5f073cd386e21ddebc746ba5decc5ff) (@materializer)
* [x] [`942394d3a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/942394d3aec7b2e6c9fd196814ac6ee830372817) (@materializer)
* [x] [`9c0850faa` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9c0850faaadcc392f0e1e44f7a48271758d1b294) (@materializer)
* [x] [`ace6c8249` release: bump to version v0.49.0](https://github.com/MaterializeInc/materialize/commit/ace6c82496815ad4b430d15bdd15b1987253a76b) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18315 persist: batch construction with partially order time](https://github.com/MaterializeInc/materialize/pull/18315) (@petrosagg)
* [ ] [#18309 [persist] Incremental GC](https://github.com/MaterializeInc/materialize/pull/18309) (@bkirwi)
* [ ] [#18394 persist-client: Reduce copies in proto deserialization](https://github.com/MaterializeInc/materialize/pull/18394) (@parker-timmerman)
* [ ] [#18313 pg sources: make schema change detection harder to fool](https://github.com/MaterializeInc/materialize/pull/18313) (@sploiselle)
* [ ] [#18408 sqlsmith ci:Reduce number of servers for explain run](https://github.com/MaterializeInc/materialize/pull/18408) (@def-)
* [ ] [#18376 Make replica IDs strings in the system tables](https://github.com/MaterializeInc/materialize/pull/18376) (@teskje)
* [ ] [#18226 compute: refactor timely and DD logging for readability](https://github.com/MaterializeInc/materialize/pull/18226) (@teskje)
* [ ] [#18344 storage: cleanup the upsert operator](https://github.com/MaterializeInc/materialize/pull/18344) (@petrosagg)
* [ ] [#18418 stash: Revert serialized role struct](https://github.com/MaterializeInc/materialize/pull/18418) (@jkosh44)
* [ ] [#18388 Hardcode since granularity to 1s](https://github.com/MaterializeInc/materialize/pull/18388) (@umanwizard)
* [ ] [#18421 Fix incorrect log message](https://github.com/MaterializeInc/materialize/pull/18421) (@umanwizard)
* [ ] [#18245 Less verbosity when adding vars](https://github.com/MaterializeInc/materialize/pull/18245) (@bkirwi)
* [ ] [#18310 adapter: Automatically run some queries on mz_introspection](https://github.com/MaterializeInc/materialize/pull/18310) (@parker-timmerman)
* [ ] [#18430 sql: Add owner column to pg catalog views](https://github.com/MaterializeInc/materialize/pull/18430) (@jkosh44)
* [ ] [#18332 Add platform check for ownership of objects](https://github.com/MaterializeInc/materialize/pull/18332) (@def-)
* [ ] [#18429 Rename region for subscribe sinks](https://github.com/MaterializeInc/materialize/pull/18429) (@umanwizard)
* [ ] [#18292 ci: Run the Kafka feature-benchmark scenarios in the per-push CI](https://github.com/MaterializeInc/materialize/pull/18292) (@philip-stoev)
* [ ] [#18440 storage: add test for NULL-key retraction across restarts](https://github.com/MaterializeInc/materialize/pull/18440) (@aljoscha)
* [ ] [#18441 mzcompose: Fix the misc/rqg mzcompose](https://github.com/MaterializeInc/materialize/pull/18441) (@philip-stoev)
* [ ] [#18443 ci: SQLsmith and ci-logged-error fixes](https://github.com/MaterializeInc/materialize/pull/18443) (@def-)
* [ ] [#18444 feature-benchmark: Cooperate with trimming of the CI pipeline](https://github.com/MaterializeInc/materialize/pull/18444) (@philip-stoev)
* [ ] [#18382 Rework `fold_constants` so it is `recursion_safe`](https://github.com/MaterializeInc/materialize/pull/18382) (@aalexandrov)
* [ ] [#18434 persist: activate shard_source_descs on drop of token/channel rx](https://github.com/MaterializeInc/materialize/pull/18434) (@pH14)
* [ ] [#18400 Allow `is_retained_metrics_relation` for indexes; turn on indexing for utilization metrics](https://github.com/MaterializeInc/materialize/pull/18400) (@umanwizard)
* [ ] [#18437 cargo: update signal-hook-registry to prevent a weird bug](https://github.com/MaterializeInc/materialize/pull/18437) (@guswynn)
* [ ] [#18448 Fix monotonic top-k bug #18445](https://github.com/MaterializeInc/materialize/pull/18448) (@vmarcos)
* [ ] [#18428 adapter: allow mz_introspection to run SHOW CREATE commands](https://github.com/MaterializeInc/materialize/pull/18428) (@parker-timmerman)
* [ ] [#18402 sql: Add ALTER OBJECT OWNER](https://github.com/MaterializeInc/materialize/pull/18402) (@jkosh44)
* [ ] [#18389 persist: introduce a type-erased, arc-weak state-by-shard cache](https://github.com/MaterializeInc/materialize/pull/18389) (@danhhz)
* [ ] [#18455 doc: clarify default search path for show commands](https://github.com/MaterializeInc/materialize/pull/18455) (@jseldess)
* [ ] [#18465 cloudtest: Make Mz available as 'materialized' as well](https://github.com/MaterializeInc/materialize/pull/18465) (@philip-stoev)
* [ ] [#18467 cloud canary: Add explicit indexes to all sources and views used](https://github.com/MaterializeInc/materialize/pull/18467) (@philip-stoev)
* [ ] [#18468 testdrive: fix subscribe frontier test](https://github.com/MaterializeInc/materialize/pull/18468) (@teskje)
* [ ] [#18470 timely-util: eagerly check for input handle frontiers](https://github.com/MaterializeInc/materialize/pull/18470) (@petrosagg)
* [ ] [#18464 interchange: add an avro-decode helper program](https://github.com/MaterializeInc/materialize/pull/18464) (@benesch)
* [ ] [#18479 github: remove dependency-czars reviewers](https://github.com/MaterializeInc/materialize/pull/18479) (@teskje)
* [ ] [#18486 proto: add RustType impls for i8 and i16](https://github.com/MaterializeInc/materialize/pull/18486) (@danhhz)
* [ ] [#18431 doc/user: polish v0.48 release notes](https://github.com/MaterializeInc/materialize/pull/18431) (@morsapaes)
* [ ] [#18456 adapter: Add object ownership privilege checks](https://github.com/MaterializeInc/materialize/pull/18456) (@jkosh44)
* [ ] [#18498 upgrade: Add additional upgrade scenarios to Nightly](https://github.com/MaterializeInc/materialize/pull/18498) (@philip-stoev)
* [ ] [#18403 pg sources: apply constraints + tolerate upstream changes](https://github.com/MaterializeInc/materialize/pull/18403) (@sploiselle)
* [ ] [#18504 release: bump to version v0.49.0-dev](https://github.com/MaterializeInc/materialize/pull/18504) (@jkosh44)
* [ ] [#18323 Rework `column_knowledge` so it is `recursion_safe`](https://github.com/MaterializeInc/materialize/pull/18323) (@aalexandrov)
* [ ] [#18497 compute: remove unused `SinkToken::is_subscribe`](https://github.com/MaterializeInc/materialize/pull/18497) (@teskje)
* [ ] [#18415 Guard against negative multiplicities in TopK](https://github.com/MaterializeInc/materialize/pull/18415) (@tokenrove)
* [ ] [#18511 mz: Set the application_name](https://github.com/MaterializeInc/materialize/pull/18511) (@parker-timmerman)
* [ ] [#18469 upsert: dedup correctly, operate on `(hash(key), value)` pairs](https://github.com/MaterializeInc/materialize/pull/18469) (@petrosagg)
* [ ] [#18447 Detect and error on negative multiplicities in DistinctBy](https://github.com/MaterializeInc/materialize/pull/18447) (@tokenrove)
* [ ] [#18493 doc/user: patch link in troubleshooting guide](https://github.com/MaterializeInc/materialize/pull/18493) (@morsapaes)
* [ ] [#18499 ci: Give the zippy-crdb-latest Buildkite step a larger EC2 instance](https://github.com/MaterializeInc/materialize/pull/18499) (@philip-stoev)
* [ ] [#18500 release-qualification: Adjust the execution time of zippy-cluster-rep…](https://github.com/MaterializeInc/materialize/pull/18500) (@philip-stoev)
* [ ] [#18521 ci: Auto-restart Materialized on crash in SQLancer testing](https://github.com/MaterializeInc/materialize/pull/18521) (@def-)
* [ ] [#18277 Introspection sources improvements, part 2](https://github.com/MaterializeInc/materialize/pull/18277) (@teskje)
* [ ] [#18524 transform: use `base_eq` in `DatumKnowledge::join_assign`](https://github.com/MaterializeInc/materialize/pull/18524) (@aalexandrov)
* [ ] [#18514 Bump timely](https://github.com/MaterializeInc/materialize/pull/18514) (@umanwizard)
* [ ] [#18516 adapter: Allow superusers to alter object owners](https://github.com/MaterializeInc/materialize/pull/18516) (@jkosh44)
* [ ] [#18505 storage: ingest PG tables with add'l columns](https://github.com/MaterializeInc/materialize/pull/18505) (@sploiselle)
* [ ] [`84dc30bf3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/84dc30bf3a3e8d313b6635155dc93b7bfb1d2236) (@materializer)
* [ ] [`76eca481a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/76eca481a46f6eb780989721677cfd25f6c6b8be) (@materializer)
* [ ] [`07f8e607e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/07f8e607e17c3015c946909db9c6905d3b4f8f76) (@materializer)
* [ ] [`28a4fadee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/28a4fadeedb2a1a856e8c5b29664c958a3a5723f) (@materializer)
* [ ] [`6636afa2f` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6636afa2f5f073cd386e21ddebc746ba5decc5ff) (@materializer)
* [ ] [`942394d3a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/942394d3aec7b2e6c9fd196814ac6ee830372817) (@materializer)
* [ ] [`9c0850faa` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9c0850faaadcc392f0e1e44f7a48271758d1b294) (@materializer)
* [ ] [`ace6c8249` release: bump to version v0.49.0](https://github.com/MaterializeInc/materialize/commit/ace6c82496815ad4b430d15bdd15b1987253a76b) (@jkosh44)

**Comment by arusahni** [comment]
LGTM!

**Comment by jkosh44** [comment]
All unreviewed commits/PRs that are not mine LGTM.
