### ISSUE TITLE
QA sign-off for the WMR Epic

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18656]
In addition to any per-PR tests , the following sign-off activities are needed:
- [ ] A comprehensive RQG run comparing the tree as it was before the WMR optimizations began to the one with all WMR optimizations enabled
- [ ] Make sure all know WMR examples are present in the regression test suite
- [ ] 24-hour runs for SQLSmith, SQLancer

**Comment by philip-stoev** [comment]
The status is as follows:
-- no real-life queries are available to add to the test suite at this time
-- the envisioned additional RQG run that compares the tree from before the optimizations to the current main will fail due to panics that have been fixed recently
-- the combined execution time of SQLSmith and SQLancer in the CI has already  exceeded 24h since WMR was stabilized.

Therefore I am marking this task as complete. We will revisit testing WMR when actual use cases become available.

**Comment by uce** [comment]
>  the combined execution time of SQLSmith and SQLancer in the CI has already exceeded 24h since WMR was stabilized.

@philip-stoev Just to make sure I'm reading this correctly: CI exceeding 24h and WMR stabilization are two independent events, correct?

**Comment by philip-stoev** [comment]
I meant that since the last WMR PR has been pushed, the combined running time of the fuzzing tools in Nightly has exceeded 24h. So I will not be scheduling a dedicated 24h run.
