### ISSUE TITLE
[Epic] persist: cost efficiency

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#18665]
### Product Outcome

Improving the efficiency and performance of Persist in ways that are targeted towards driving down dollar cost of services used.

### Specification

-

### Design

-

### Required Issues (Must Haves)

```[tasklist]
## Implementation
- [x] Tune down polling interval of Listens - https://github.com/MaterializeInc/materialize/pull/18151
- [x] Shared state - https://github.com/MaterializeInc/materialize/pull/18488
- [x] Monitor / tune perf of `persist_sink` output - https://github.com/MaterializeInc/materialize/issues/15985
```

```[tasklist]
## Design
- [x] Push-based updates to eliminate Consensus reads / CaS mismatches - https://github.com/MaterializeInc/materialize/issues/18391
```

### Discretionary Issues (Nice To Haves)

```[tasklist]
## Implementation
- [x] Remove state rollup responsibility from GC / tune rollup interval. ~35% of blob writes / S3 PUTs are rollups.
- [ ] Bring back compaction special-case, could be 15-20% of blob writes
- [ ] Delete data when shard is dropped - https://github.com/MaterializeInc/materialize/issues/8185
- [ ] Maintenance task to remove unreferenced data
- [ ] Delete blobs that fail compare_and_append
```

```[tasklist]
## Design
- [ ] (Stretch) Inline writes to Consensus for small batches of data
- [ ] (Stretch) Logical sharding on top of MFP pushdown
```

**Comment by pH14** [comment]
All of the must-haves have been completed, and persist is running much leaner than before. There's open work around cleaning up blobs in S3, but we can track that work separately / bucket it under compliance or cleanup work because its cost is so negligible.
