### ISSUE TITLE
release: v0.50.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18667]
The following PRs in [`v0.50.0`](https://github.com/MaterializeInc/materialize/tree/v0.50.0) require review:
* [x] [#18517 storage: improve the detail of errors around kafka+ssh that are logged](https://github.com/MaterializeInc/materialize/pull/18517) (@guswynn)
* [x] [#18653 doc/user: add 3xsmall option to CREATE CLUSTER REPLICA](https://github.com/MaterializeInc/materialize/pull/18653) (@benesch)
* [x] [#18655 platform checks: Fix the UpgradeEntireMzFourVersions scenario](https://github.com/MaterializeInc/materialize/pull/18655) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`f1226b289` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f1226b289057216c639ca9a277ea335ec0fa33a1) (@materializer)
* [x] [`c646940ba` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c646940bac0a244888f1d29ddded2bc47fdcd44a) (@materializer)
* [x] [`47dbbb3d4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/47dbbb3d4ad175986873dc747d04002a930dd033) (@materializer)
* [x] [`aa2b11a70` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aa2b11a703abfdf0459b2d3380f873d13a798802) (@materializer)
* [x] [`41e9054f6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/41e9054f6a8185264c77008125f0af851bfeeef4) (@materializer)
* [x] [`659baf70e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/659baf70e41c85efc4cdc7c7e91aa1c7b2af9d4c) (@materializer)
* [x] [`d0a8687e5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0a8687e5e27f5888099be301f53789a16558f53) (@materializer)
* [x] [`14c46fcef` release: bump to version v0.50.0](https://github.com/MaterializeInc/materialize/commit/14c46fcef1939a2905b36457023294b0548afa34) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18526 compute: refactor logging initialization](https://github.com/MaterializeInc/materialize/pull/18526) (@teskje)
* [ ] [#18386 repr: hook up real columnar encodings for more ScalarTypes](https://github.com/MaterializeInc/materialize/pull/18386) (@danhhz)
* [ ] [#18540 doc/user: Enable deeplinks to tabs](https://github.com/MaterializeInc/materialize/pull/18540) (@ruf-io)
* [ ] [#18487 persist: calculate and store stats for all `T: Data` types](https://github.com/MaterializeInc/materialize/pull/18487) (@danhhz)
* [ ] [#18542 release: bump to version v0.50.0-dev](https://github.com/MaterializeInc/materialize/pull/18542) (@jkosh44)
* [ ] [#18517 storage: improve the detail of errors around kafka+ssh that are logged](https://github.com/MaterializeInc/materialize/pull/18517) (@guswynn)
* [ ] [#18512 Add `mz_internal.mz_dataflow_arrangement_sizes`](https://github.com/MaterializeInc/materialize/pull/18512) (@umanwizard)
* [ ] [#18055 Allow sources to render arbitrary dataflows](https://github.com/MaterializeInc/materialize/pull/18055) (@petrosagg)
* [ ] [#18549 platform-checks: Adjust the PgCdc check to match reality](https://github.com/MaterializeInc/materialize/pull/18549) (@philip-stoev)
* [ ] [#18477 platform checks: Test object ownership privilege](https://github.com/MaterializeInc/materialize/pull/18477) (@def-)
* [ ] [#18552 storage: never call `block_on` on a timely worker](https://github.com/MaterializeInc/materialize/pull/18552) (@petrosagg)
* [ ] [#18555 storage: remove dead code](https://github.com/MaterializeInc/materialize/pull/18555) (@petrosagg)
* [ ] [#18556 github: Transfer ownership of postgres-util crate](https://github.com/MaterializeInc/materialize/pull/18556) (@jkosh44)
* [ ] [#18510 sql: improve WMR error message on type mismatch](https://github.com/MaterializeInc/materialize/pull/18510) (@aalexandrov)
* [ ] [#18550 platform checks: Enable RBAC checks](https://github.com/MaterializeInc/materialize/pull/18550) (@def-)
* [ ] [#18531 compute: make import frontier logging drop-safe](https://github.com/MaterializeInc/materialize/pull/18531) (@teskje)
* [ ] [#18426 adapter: Log origin of requests](https://github.com/MaterializeInc/materialize/pull/18426) (@parker-timmerman)
* [ ] [#18571 adapter: Rename *Object* structs to *Item*](https://github.com/MaterializeInc/materialize/pull/18571) (@andrewrodriguez-m)
* [ ] [#18132 compute,adapter: document and test SUBSCRIBE initial progress](https://github.com/MaterializeInc/materialize/pull/18132) (@benesch)
* [ ] [#18533 deps: cargo update -p postgres](https://github.com/MaterializeInc/materialize/pull/18533) (@parker-timmerman)
* [ ] [#18509 ore: Add infallible_unwrap to ResultExt](https://github.com/MaterializeInc/materialize/pull/18509) (@parker-timmerman)
* [ ] [#18586 Revert "Merge pull request #18309 from bkirwi/incremental-gc"](https://github.com/MaterializeInc/materialize/pull/18586) (@danhhz)
* [ ] [#18588 adapter: docs and followups from #18426](https://github.com/MaterializeInc/materialize/pull/18588) (@parker-timmerman)
* [ ] [#18547 storage: improve reliability of SSH tunnels with large clusters](https://github.com/MaterializeInc/materialize/pull/18547) (@benesch)
* [ ] [#18513 sql: Add maclitem type for privileges](https://github.com/MaterializeInc/materialize/pull/18513) (@jkosh44)
* [ ] [#18589 .github: Add affected pages textarea for docs issues template](https://github.com/MaterializeInc/materialize/pull/18589) (@tr0njavolta)
* [ ] [#18502 #18211/#18212/#17509: error handling in various reductions](https://github.com/MaterializeInc/materialize/pull/18502) (@tokenrove)
* [ ] [#18591 storage: update tokio-io-utility](https://github.com/MaterializeInc/materialize/pull/18591) (@guswynn)
* [ ] [#18592 persist: only debug fmt state diffs in error case](https://github.com/MaterializeInc/materialize/pull/18592) (@pH14)
* [ ] [#18597 repr: move Date to TodoDatumToPersist](https://github.com/MaterializeInc/materialize/pull/18597) (@danhhz)
* [ ] [#18478 [persist] MFP explain config](https://github.com/MaterializeInc/materialize/pull/18478) (@bkirwi)
* [ ] [#18573 persist: collect schemaless stats for Jsonb](https://github.com/MaterializeInc/materialize/pull/18573) (@danhhz)
* [ ] [#18578 adapter: correct stash retraction migrations](https://github.com/MaterializeInc/materialize/pull/18578) (@mjibson)
* [ ] [#18585 ci: Run cargo check on merge with target branch](https://github.com/MaterializeInc/materialize/pull/18585) (@nrainer-materialize)
* [ ] [#18568 optbench: replace deprecated `pkg_resources` package](https://github.com/MaterializeInc/materialize/pull/18568) (@aalexandrov)
* [ ] [#18582 Fix a cast inversion bug in `LiteralConstraints`](https://github.com/MaterializeInc/materialize/pull/18582) (@ggevay)
* [ ] [#18604 ci: Avoid starting agent for merge check when not in PR](https://github.com/MaterializeInc/materialize/pull/18604) (@nrainer-materialize)
* [ ] [#18605 docs: Fix cloudtest setup for Mac users](https://github.com/MaterializeInc/materialize/pull/18605) (@nrainer-materialize)
* [ ] [#18594 doc/user: Update access wording](https://github.com/MaterializeInc/materialize/pull/18594) (@ruf-io)
* [ ] [#18581 #18215: expose errors in ReduceCollation as query-level errors](https://github.com/MaterializeInc/materialize/pull/18581) (@tokenrove)
* [ ] [#18610 adapter: don't hardcode SYSTEM TIME in subscribe start](https://github.com/MaterializeInc/materialize/pull/18610) (@mjibson)
* [ ] [#18602 frontegg-auth: refactor out a more general Client](https://github.com/MaterializeInc/materialize/pull/18602) (@mjibson)
* [ ] [#18614 test: Fix broken sqllogictest](https://github.com/MaterializeInc/materialize/pull/18614) (@parker-timmerman)
* [ ] [#18598 v0.49.0 release notes](https://github.com/MaterializeInc/materialize/pull/18598) (@jseldess)
* [ ] [#18618 docs: add note about cluster AZ assignment](https://github.com/MaterializeInc/materialize/pull/18618) (@tr0njavolta)
* [ ] [#18583 *: make printing of error chain more explicit](https://github.com/MaterializeInc/materialize/pull/18583) (@aljoscha)
* [ ] [#18577 ci: add rocksdb as a dep](https://github.com/MaterializeInc/materialize/pull/18577) (@guswynn)
* [ ] [#18615 adapter: Reduce amount of table advancements](https://github.com/MaterializeInc/materialize/pull/18615) (@jkosh44)
* [ ] [#18611 adapter: Fix mz_sessions retractions](https://github.com/MaterializeInc/materialize/pull/18611) (@jkosh44)
* [ ] [#18619 bump to rust 1.68](https://github.com/MaterializeInc/materialize/pull/18619) (@guswynn)
* [ ] [#18624 bump nightly to one past 1.68.2](https://github.com/MaterializeInc/materialize/pull/18624) (@guswynn)
* [ ] [#18623 adapter: Reset table timer after system writes](https://github.com/MaterializeInc/materialize/pull/18623) (@jkosh44)
* [ ] [#18630 testdrive: Fortify negative-multiplicities.td](https://github.com/MaterializeInc/materialize/pull/18630) (@philip-stoev)
* [ ] [#18631 adapter: handle publications specified as identifiers](https://github.com/MaterializeInc/materialize/pull/18631) (@petrosagg)
* [ ] [#18629 sqlancer: Use official version](https://github.com/MaterializeInc/materialize/pull/18629) (@def-)
* [ ] [#18532 Rework `projection_~` transforms to make them `recursion_safe`](https://github.com/MaterializeInc/materialize/pull/18532) (@aalexandrov)
* [ ] [#18633 ci: Run "Merge skew cargo check" with target dependencies](https://github.com/MaterializeInc/materialize/pull/18633) (@nrainer-materialize)
* [ ] [#18635 Fix #18608: Do not swallow errors before basic TopK](https://github.com/MaterializeInc/materialize/pull/18635) (@tokenrove)
* [ ] [#18634 ci: merge trial check: use existing remote repo ref](https://github.com/MaterializeInc/materialize/pull/18634) (@nrainer-materialize)
* [ ] [#18622 adapter: Buffer updates to metrics system tables](https://github.com/MaterializeInc/materialize/pull/18622) (@jkosh44)
* [ ] [#18554 Mark ReductionPushdown and ReduceElision WMR-safe](https://github.com/MaterializeInc/materialize/pull/18554) (@ggevay)
* [ ] [#18637 storage: exhaust the consumers before entering the wait state](https://github.com/MaterializeInc/materialize/pull/18637) (@petrosagg)
* [ ] [#18557 doc/user: bump to v0.48.4](https://github.com/MaterializeInc/materialize/pull/18557) (@morsapaes)
* [ ] [#18647 adapter: peek refactor](https://github.com/MaterializeInc/materialize/pull/18647) (@mjibson)
* [ ] [#18642 ci: Use ci_..._heading consistently](https://github.com/MaterializeInc/materialize/pull/18642) (@def-)
* [ ] [#18307 storage: write fewer, larger batches in persist sink](https://github.com/MaterializeInc/materialize/pull/18307) (@guswynn)
* [ ] [#18364 storage: add open-loop benchmark for UPSERT perf](https://github.com/MaterializeInc/materialize/pull/18364) (@guswynn)
* [ ] [#18620 adapter: Log application_name with Segment logging](https://github.com/MaterializeInc/materialize/pull/18620) (@parker-timmerman)
* [ ] [#18593 persist: count all live diffs at start of gc](https://github.com/MaterializeInc/materialize/pull/18593) (@pH14)
* [ ] [#18640 Collect errors before concatenating streams](https://github.com/MaterializeInc/materialize/pull/18640) (@antiguru)
* [ ] [#18599 adapter: Refactor DROP stmts into single stmt](https://github.com/MaterializeInc/materialize/pull/18599) (@jkosh44)
* [ ] [#18646 persist: impl PersistSourceDataStats for all ScalarTypes](https://github.com/MaterializeInc/materialize/pull/18646) (@danhhz)
* [ ] [#18652 storage: consolidate how we handle kafka errors](https://github.com/MaterializeInc/materialize/pull/18652) (@guswynn)
* [ ] [#18653 doc/user: add 3xsmall option to CREATE CLUSTER REPLICA](https://github.com/MaterializeInc/materialize/pull/18653) (@benesch)
* [ ] [#18655 platform checks: Fix the UpgradeEntireMzFourVersions scenario](https://github.com/MaterializeInc/materialize/pull/18655) (@philip-stoev)
* [ ] [#18659 persist: bound the size of the seqno hold bug info! log](https://github.com/MaterializeInc/materialize/pull/18659) (@danhhz)
* [ ] [`f1226b289` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/f1226b289057216c639ca9a277ea335ec0fa33a1) (@materializer)
* [ ] [`c646940ba` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c646940bac0a244888f1d29ddded2bc47fdcd44a) (@materializer)
* [ ] [`47dbbb3d4` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/47dbbb3d4ad175986873dc747d04002a930dd033) (@materializer)
* [ ] [`aa2b11a70` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/aa2b11a703abfdf0459b2d3380f873d13a798802) (@materializer)
* [ ] [`41e9054f6` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/41e9054f6a8185264c77008125f0af851bfeeef4) (@materializer)
* [ ] [`659baf70e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/659baf70e41c85efc4cdc7c7e91aa1c7b2af9d4c) (@materializer)
* [ ] [`d0a8687e5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d0a8687e5e27f5888099be301f53789a16558f53) (@materializer)
* [ ] [`14c46fcef` release: bump to version v0.50.0](https://github.com/MaterializeInc/materialize/commit/14c46fcef1939a2905b36457023294b0548afa34) (@jkosh44)

**Comment by jkosh44** [comment]
All unreviewed commits/PRs that are not mine LGTM.

**Comment by arusahni** [comment]
Last unreviewed commit LGTM.
