### ISSUE TITLE
[Epic] persist: tablestakes reliability issues

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#18663]
### Product Outcome

Improving the reliability of Persist

### Specification

-

### Design

-

### Required Issues (Must Haves)

```[tasklist]
## Implementation
- [x] Shared persist state to reduce memory pressure - https://github.com/MaterializeInc/materialize/pull/18488
- [ ] CRDB Changefeeds to S3 for all envs
- [x] Turn on S3 Versioning in staging - https://github.com/MaterializeInc/cloud/pull/6104
- [x] S3 Versioning in prod
- [x] CRDB TCP timeouts + keepalives
- [x] Incremental GC - https://github.com/MaterializeInc/materialize/issues/17282
```

```[tasklist]
## Design
- [ ] Sketching out alternatives to time-based leases of readers and writers - https://github.com/MaterializeInc/materialize/issues/18662
```

### Discretionary Issues (Nice To Haves)

```[tasklist]
## Implementation
- [ ] idle merge effort - https://github.com/MaterializeInc/materialize/pull/17698
- [ ] easier feature flags within persist
- [ ] SQL introspection of persist state - https://github.com/MaterializeInc/materialize/pull/17831
- [ ] hosted version of persistcli to avoid needing prod access to DBs/S3
- [ ] fix the since - https://github.com/MaterializeInc/materialize/pull/15850
- [ ] Runbooks, for us, for others
```

```[tasklist]
## Design
- [ ] Compaction 2.0 - https://github.com/MaterializeInc/materialize/issues/16607
- [ ] Bounding state size regardless of data/# parts within shard
- [ ] Make `persist_source` independent of batch size

### Blockers

_No response_

**Comment by dseisun-materialize** [comment]
@pH14 this is a bit of a disparate list which I'm sure we haven't done all of, but do you think it's still worth leaving open, or closing for something more focused?

**Comment by pH14** [comment]
Can close it. The remaining requirement of `CRDB Changefeeds to S3 for all envs` has had a bunch of roadblocks, and while I'd still like to get it done, isn't something that has an obvious path forward right now
