### ISSUE TITLE
[Epic] Improve Compute metrics dashboard

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#18745]
At the moment, Compute doesn't have a consistent set of metrics dashboards that we can use to quickly characterize the inner workings of the optimizer, rendering and the controller.

### Tasks

* [x] Write a design doc
  * #19717
* [x] Implement proposed Compute metrics
  * #19905
  * #19964
  * #20063
  * #20126
  * https://github.com/MaterializeInc/cloud/pull/7089
* [x] Show the proposed metrics in the Compute dashboard
* [x] Add a dashboard panel that shows per-collection worker skew 
* [x] Fix compute history metrics https://github.com/MaterializeInc/materialize/issues/20242
* [x] https://github.com/MaterializeInc/cloud/issues/7265
