### ISSUE TITLE
release: v0.51.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18775]
The following PRs in [`v0.51.0`](https://github.com/MaterializeInc/materialize/tree/v0.51.0) require review:
* [x] [#18673 ore: add helpers for timing out Result-returning futures](https://github.com/MaterializeInc/materialize/pull/18673) (@benesch)
* [x] [#17597 Design document for invalid accumulations in reductions](https://github.com/MaterializeInc/materialize/pull/17597) (@vmarcos)
* [x] [#18721 v0.50.0 release notes](https://github.com/MaterializeInc/materialize/pull/18721) (@tr0njavolta)
* [x] [#18724 doc/user: bump v0.49 `patch` to 6](https://github.com/MaterializeInc/materialize/pull/18724) (@morsapaes)
* [x] [#18736 Install psql on scratch machines by default](https://github.com/MaterializeInc/materialize/pull/18736) (@tokenrove)
* [x] [#17820 Stabilize `WITH MUTUALLY RECURSIVE` design doc](https://github.com/MaterializeInc/materialize/pull/17820) (@aalexandrov)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`0c8a83922` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0c8a83922e764e96563ab73798b1cfc3dedb3ec5) (@materializer)
* [x] [`ebb39fcd3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ebb39fcd317ff811a4e4c792e3c8aca0b0975da5) (@materializer)
* [x] [`07a870580` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/07a8705801b77bda48cd61ad8190f7f75e66c304) (@materializer)
* [x] [`c7b89d67a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c7b89d67aa476929b5db51905e3b3f7b8845b58d) (@materializer)
* [x] [`ca6fc3f06` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ca6fc3f0647f3814a72de6794c814edfaf5d090f) (@materializer)
* [x] [`17723d170` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/17723d170666bb431fd6b37daf840e56129d741c) (@materializer)
* [x] [`e83a671a0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e83a671a096405f57aec36c3c0ca68a7f4a15c6b) (@materializer)
* [x] [`9b4eae274` release: bump to version v0.51.0](https://github.com/MaterializeInc/materialize/commit/9b4eae27407d0b9838a3a0161f3a6f16e0282dbd) (@danhhz)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18643 ci: Reduce number of joins in SQLsmith](https://github.com/MaterializeInc/materialize/pull/18643) (@def-)
* [ ] [#18660 adapter: Add functions and casts to mz_aclitem](https://github.com/MaterializeInc/materialize/pull/18660) (@jkosh44)
* [ ] [#18651 adapter: Refactor cascading delete statements](https://github.com/MaterializeInc/materialize/pull/18651) (@jkosh44)
* [ ] [#18668 release: bump to version v0.51.0-dev](https://github.com/MaterializeInc/materialize/pull/18668) (@jkosh44)
* [ ] [#18673 ore: add helpers for timing out Result-returning futures](https://github.com/MaterializeInc/materialize/pull/18673) (@benesch)
* [ ] [#18672 pg sources: fix replication stream timeout bug](https://github.com/MaterializeInc/materialize/pull/18672) (@sploiselle)
* [ ] [#18626 pg sources: avoid "rewinding" if possible](https://github.com/MaterializeInc/materialize/pull/18626) (@sploiselle)
* [ ] [#18690 Output buckets in physical `EXPLAIN` text, not skips](https://github.com/MaterializeInc/materialize/pull/18690) (@vmarcos)
* [ ] [#18689 deps: pick up crossbeam soundness fix](https://github.com/MaterializeInc/materialize/pull/18689) (@petrosagg)
* [ ] [#18488 persist: wire up shared state with std mutex](https://github.com/MaterializeInc/materialize/pull/18488) (@pH14)
* [ ] [#18675 ssh-util: configure frequent SSH keepalives](https://github.com/MaterializeInc/materialize/pull/18675) (@benesch)
* [ ] [#18694 ci: Fix dev-site script](https://github.com/MaterializeInc/materialize/pull/18694) (@jkosh44)
* [ ] [#18693 adapter: Refactor cluster replica dependents](https://github.com/MaterializeInc/materialize/pull/18693) (@jkosh44)
* [ ] [#18650 sql: Add more variables for controlling RBAC](https://github.com/MaterializeInc/materialize/pull/18650) (@jkosh44)
* [ ] [#18685 environmentd: allow TLS connections to the internal SQL port](https://github.com/MaterializeInc/materialize/pull/18685) (@benesch)
* [ ] [#18704 platform-checks: Set enable_ld_rbac_checks only on versions that supp…](https://github.com/MaterializeInc/materialize/pull/18704) (@philip-stoev)
* [ ] [#18707 sqlsmith: Mark two common new errors as expected](https://github.com/MaterializeInc/materialize/pull/18707) (@def-)
* [ ] [#17597 Design document for invalid accumulations in reductions](https://github.com/MaterializeInc/materialize/pull/17597) (@vmarcos)
* [ ] [#18606 #18121 use EXPECTED GROUP SIZE hint in basic top-K rendering](https://github.com/MaterializeInc/materialize/pull/18606) (@tokenrove)
* [ ] [#18698 Stop pointing MZDEV_POSTGRES to PG on scratch](https://github.com/MaterializeInc/materialize/pull/18698) (@tokenrove)
* [ ] [#18710 Fix null handling in `LiteralConstraints`](https://github.com/MaterializeInc/materialize/pull/18710) (@ggevay)
* [ ] [#18712 sql: Clarify parsing errors for role id](https://github.com/MaterializeInc/materialize/pull/18712) (@jkosh44)
* [ ] [#18701 Fix broken index migration](https://github.com/MaterializeInc/materialize/pull/18701) (@umanwizard)
* [ ] [#18697 pg sources: do not fast-forward with pending writes](https://github.com/MaterializeInc/materialize/pull/18697) (@sploiselle)
* [ ] [#18721 v0.50.0 release notes](https://github.com/MaterializeInc/materialize/pull/18721) (@tr0njavolta)
* [ ] [#18724 doc/user: bump v0.49 `patch` to 6](https://github.com/MaterializeInc/materialize/pull/18724) (@morsapaes)
* [ ] [#18220 sql: allow filtering subsources by upstream schema](https://github.com/MaterializeInc/materialize/pull/18220) (@sploiselle)
* [ ] [#18728 docs: Update scratch lifetime](https://github.com/MaterializeInc/materialize/pull/18728) (@nrainer-materialize)
* [ ] [#18729 storage-usage-test: Fix expected storage usage for simplest materiali…](https://github.com/MaterializeInc/materialize/pull/18729) (@philip-stoev)
* [ ] [#18713 transform: refine `DatumKnowledge::meet_assign` type handing](https://github.com/MaterializeInc/materialize/pull/18713) (@aalexandrov)
* [ ] [#18735 Make EXPECTED GROUP SIZE changes more consistent](https://github.com/MaterializeInc/materialize/pull/18735) (@tokenrove)
* [ ] [#18736 Install psql on scratch machines by default](https://github.com/MaterializeInc/materialize/pull/18736) (@tokenrove)
* [ ] [#18632 ore: change ResultExt to use error-with-chain printing](https://github.com/MaterializeInc/materialize/pull/18632) (@aljoscha)
* [ ] [#18717 storage/surfaces: add non-populated disk_bytes to mz_cluster_replicas_metrics/sizes](https://github.com/MaterializeInc/materialize/pull/18717) (@guswynn)
* [ ] [#18750 cbrt tests: Don't expect too many digits](https://github.com/MaterializeInc/materialize/pull/18750) (@def-)
* [ ] [#18751 Fix assignment of AZs](https://github.com/MaterializeInc/materialize/pull/18751) (@umanwizard)
* [ ] [#18370 PR Code Coverage](https://github.com/MaterializeInc/materialize/pull/18370) (@def-)
* [ ] [#18753 sqlsmith ci: Expect two further errors](https://github.com/MaterializeInc/materialize/pull/18753) (@def-)
* [ ] [#18754 ci: add labels to pod, reenable cloud test](https://github.com/MaterializeInc/materialize/pull/18754) (@nrainer-materialize)
* [ ] [#18755 platform checks: Fix version for enable_ld_rbac_checks](https://github.com/MaterializeInc/materialize/pull/18755) (@def-)
* [ ] [#18731 Rework `redundant_join` so it is `recursion_safe`](https://github.com/MaterializeInc/materialize/pull/18731) (@aalexandrov)
* [ ] [#17820 Stabilize `WITH MUTUALLY RECURSIVE` design doc](https://github.com/MaterializeInc/materialize/pull/17820) (@aalexandrov)
* [ ] [#18747 Change schema of `mz_dataflow_channel_operators`](https://github.com/MaterializeInc/materialize/pull/18747) (@umanwizard)
* [ ] [#18749 persist: columnar mapping tests and bug fixes](https://github.com/MaterializeInc/materialize/pull/18749) (@danhhz)
* [ ] [#17933 doc: Update adapter parts of formalism](https://github.com/MaterializeInc/materialize/pull/17933) (@jkosh44)
* [ ] [#18768 sql: add translate func](https://github.com/MaterializeInc/materialize/pull/18768) (@rkrishn7)
* [ ] [#18769 pg sources: always return irrecoverable errors during snapshotting](https://github.com/MaterializeInc/materialize/pull/18769) (@sploiselle)
* [ ] [#18773 adapter: Reorganize rbac.rs](https://github.com/MaterializeInc/materialize/pull/18773) (@jkosh44)
* [ ] [`0c8a83922` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/0c8a83922e764e96563ab73798b1cfc3dedb3ec5) (@materializer)
* [ ] [`ebb39fcd3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ebb39fcd317ff811a4e4c792e3c8aca0b0975da5) (@materializer)
* [ ] [`07a870580` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/07a8705801b77bda48cd61ad8190f7f75e66c304) (@materializer)
* [ ] [`c7b89d67a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/c7b89d67aa476929b5db51905e3b3f7b8845b58d) (@materializer)
* [ ] [`ca6fc3f06` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ca6fc3f0647f3814a72de6794c814edfaf5d090f) (@materializer)
* [ ] [`17723d170` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/17723d170666bb431fd6b37daf840e56129d741c) (@materializer)
* [ ] [`e83a671a0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e83a671a096405f57aec36c3c0ca68a7f4a15c6b) (@materializer)
* [ ] [`9b4eae274` release: bump to version v0.51.0](https://github.com/MaterializeInc/materialize/commit/9b4eae27407d0b9838a3a0161f3a6f16e0282dbd) (@danhhz)

**Comment by sploiselle** [comment]
@danhhz's unreviewed commit looks good, as do his other commits

**Comment by danhhz** [comment]
Thanks, Sean! All unreviewed commits/PRs that are not mine LGTM.
