### ISSUE TITLE
Output consistency test framework (data-flow rendering vs. constant folding): V1 + V2

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#18858]
### Feature request

Extensions to https://github.com/MaterializeInc/materialize/issues/17767.

Create a script for generating output consistency test code to
* extend existing mathematical checks with further number types and functions
* address additional operations:
  > * Top-K computation, both with LATERAL JOIN (i.e., with groups) or not.
  > * More coverage of set operations, e.g., EXCEPT, EXCEPT ALL.
  > * More coverage of joins.
  > * If possible, filters.

https://github.com/MaterializeInc/materialize/pull/18812#pullrequestreview-1389816068

```[tasklist]
### Tasks
- [x] https://github.com/MaterializeInc/materialize/issues/19438
- [ ] https://github.com/MaterializeInc/materialize/issues/19439
- [ ] https://github.com/MaterializeInc/materialize/issues/19517
- [ ] https://github.com/MaterializeInc/materialize/issues/19605
- [ ] https://github.com/MaterializeInc/materialize/issues/19826
- [ ] https://github.com/MaterializeInc/materialize/issues/19669
```

#### Basic functionality
* ✅ setup data structures
* ✅ define some data types, functions, and other expressions
* ✅ generate statements to set up and populate tables and views
* ✅ generate queries
* ✅ execute queries and collect results
* ✅ validate the outcome (result and error) of executed queries
* ✅ support functions with arguments of different data types
* ✅ generate expressions for specifically for operations
* ✅ allow skipping known output consistency deviations

#### Execution
* ✅ setup mzcompose entry point
* ✅ integrate into Buildkite
* ✅ allow stand-alone execution without mzcompose
* ✅ provide dry-run mode

#### Optimizations
* ✅ identify and separate expressions likely causing a query error
* ✅ split query and retry execution if outcome is database error and multiple columns are involved
* ✅ support warnings
* ✅ apply random query filtering on the fly to save memory
* ✅ let amount of work depend on specified execution time
* ✅ support fail-fast on first error
* ✅ support functions with variable parameter count

#### Docs
* ✅ document classes

### Version V2 + V3
* ✅ support transposed input matrix ("multi-row structure")
* 🏗️ support top-k queries, aggregates, joins and further queries requested in the ticket
* ✅ test https://github.com/MaterializeInc/materialize/issues/17189 => implicitly though many other features
* ✅ add function nesting (`SUM(ROUND(max_value))`)
* ✅ add further functions and data types: start with timestamps

### Optional
* ❌ generate junit result file

### Other
* Keep complexity and runtime in mind. The test should run at most one to two minutes. (Does not apply if run in nightly.)
* Prefer a select statement with many columns over many select statements with few columns for performance reasons.

CC @vmarcos, @philip-stoev

**Comment by philip-stoev** [comment]
As discussed in zoom, you may be able to yank even more queries/sec if you do a `SET transaction_isolation = SERIALIZABLE` and `BEGIN` in your test.

**Comment by nrainer-materialize** [comment]
V3 in https://github.com/MaterializeInc/materialize/issues/20635
