### ISSUE TITLE
release: v0.52.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#18907]
The following PRs in [`v0.52.0`](https://github.com/MaterializeInc/materialize/tree/v0.52.0) require review:
* [x] [#17858 "External introspection" draft design doc](https://github.com/MaterializeInc/materialize/pull/17858) (@umanwizard)
* [x] [#18743 doc/user document reserved disk_bytes fields in usage tables](https://github.com/MaterializeInc/materialize/pull/18743) (@guswynn)
* [x] [#18892 testdrive: Fortify testdrive-fortify-divergent-dataflow-cancellation.td](https://github.com/MaterializeInc/materialize/pull/18892) (@philip-stoev)
* [x] [#18862 upgrade test: Fix the UpgradeEntireMzFourVersions scenario](https://github.com/MaterializeInc/materialize/pull/18862) (@philip-stoev)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`e67eb3fd0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e67eb3fd01e3d4d019f08070a93a025ac9af0a54) (@materializer)
* [x] [`9376cd633` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9376cd633bb3e689731c2bdcac8d54abceece764) (@materializer)
* [x] [`6609956ee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6609956eef5eca14d57c1859b5e8a18d966620b3) (@materializer)
* [x] [`85ef9f5cf` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/85ef9f5cfd190c1fde45b69537c98bc6ba3bdc9e) (@materializer)
* [x] [`e781222ea` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e781222ea382aa6a7eee1b0e50e94218988f4cad) (@materializer)
* [x] [`25be1e8e3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/25be1e8e3709644bf0a36c1b10e12d32d061a91f) (@materializer)
* [x] [`07f75a9fd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/07f75a9fd2e06e8c995de521d356c18070c121de) (@materializer)
* [ ] [`e36d098e6` release: bump to version v0.52.0](https://github.com/MaterializeInc/materialize/commit/e36d098e6bb499ce24052bf78abd86b166a24b53) (@sploiselle)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18741 doc/dev: document our approach to error handling/printing](https://github.com/MaterializeInc/materialize/pull/18741) (@aljoscha)
* [ ] [#18765 persist: add real implementation of Schema for Maelstrom{Key,Val}](https://github.com/MaterializeInc/materialize/pull/18765) (@danhhz)
* [ ] [#18771 persist: truncate String and Vec<u8> stats to a maximum byte length](https://github.com/MaterializeInc/materialize/pull/18771) (@danhhz)
* [ ] [#18774 docs: Minor fixes in commands](https://github.com/MaterializeInc/materialize/pull/18774) (@def-)
* [ ] [#18776 release: bump to version v0.52.0-dev](https://github.com/MaterializeInc/materialize/pull/18776) (@danhhz)
* [ ] [#18539 pg sources: demux subsource errors](https://github.com/MaterializeInc/materialize/pull/18539) (@sploiselle)
* [ ] [#18772 compute: tokenize error logging](https://github.com/MaterializeInc/materialize/pull/18772) (@teskje)
* [ ] [#18563 storage-client: don't panic if reading Kafka secret fails](https://github.com/MaterializeInc/materialize/pull/18563) (@benesch)
* [ ] [#17858 "External introspection" draft design doc](https://github.com/MaterializeInc/materialize/pull/17858) (@umanwizard)
* [ ] [#18719 adapter: Change id column in mz_databases and mz_schemas](https://github.com/MaterializeInc/materialize/pull/18719) (@parker-timmerman)
* [ ] [#18700 adapter: Add privileges to objects](https://github.com/MaterializeInc/materialize/pull/18700) (@jkosh44)
* [ ] [#18800 coverage: Ignore lines that can't be covered](https://github.com/MaterializeInc/materialize/pull/18800) (@def-)
* [ ] [#18798 adapter: Remove the `enable_auto_route_introspection_queries` LD Flag](https://github.com/MaterializeInc/materialize/pull/18798) (@parker-timmerman)
* [ ] [#18796 Surface OOMs in `mz_cluster_replica_statuses`](https://github.com/MaterializeInc/materialize/pull/18796) (@umanwizard)
* [ ] [#18802 persist: tune "snapshot ... not yet available" info log](https://github.com/MaterializeInc/materialize/pull/18802) (@danhhz)
* [ ] [#18777 adapter: Update privileges when an owner is updated](https://github.com/MaterializeInc/materialize/pull/18777) (@jkosh44)
* [ ] [#18805 persist: proptest coverage for truncate_bytes and truncate_string](https://github.com/MaterializeInc/materialize/pull/18805) (@danhhz)
* [ ] [#18804 adapter: Add test for update_privilege_owners](https://github.com/MaterializeInc/materialize/pull/18804) (@jkosh44)
* [ ] [#18783 sql: Ensure priv role refs are always valid](https://github.com/MaterializeInc/materialize/pull/18783) (@jkosh44)
* [ ] [#18779 sql: Remove inheritance of role attributes](https://github.com/MaterializeInc/materialize/pull/18779) (@jkosh44)
* [ ] [#18780 sql: Update role membership for PostgreSQL v16](https://github.com/MaterializeInc/materialize/pull/18780) (@jkosh44)
* [ ] [#18808 persist: skip truncate_bytes/strings proptests in miri](https://github.com/MaterializeInc/materialize/pull/18808) (@danhhz)
* [ ] [#18781 sql: Ensure role member grantor is always valid](https://github.com/MaterializeInc/materialize/pull/18781) (@jkosh44)
* [ ] [#18758 platform-checks: Add privileges validation to owners check](https://github.com/MaterializeInc/materialize/pull/18758) (@def-)
* [ ] [#18752 adapter: stash migration cleanup](https://github.com/MaterializeInc/materialize/pull/18752) (@mjibson)
* [ ] [#18797 Remove `collapsible_if` and `collapsible_else_if` lints](https://github.com/MaterializeInc/materialize/pull/18797) (@umanwizard)
* [ ] [#18809 doc/user: add `auto_route_introspection_queries` to session variables](https://github.com/MaterializeInc/materialize/pull/18809) (@morsapaes)
* [ ] [#18807 [persist] Track whether or not our JSON contains a map](https://github.com/MaterializeInc/materialize/pull/18807) (@bkirwi)
* [ ] [#18770 storage: add basic mz-rocksdb crate](https://github.com/MaterializeInc/materialize/pull/18770) (@guswynn)
* [ ] [#18762 adapter: Update ObjectId to handle catalog schema](https://github.com/MaterializeInc/materialize/pull/18762) (@jkosh44)
* [ ] [#18819 fix mz-rocksdb merge conflicts](https://github.com/MaterializeInc/materialize/pull/18819) (@guswynn)
* [ ] [#18817 redo of #18737](https://github.com/MaterializeInc/materialize/pull/18817) (@sploiselle)
* [ ] [#18718 compute: add token-controlled fuse in feedback edges](https://github.com/MaterializeInc/materialize/pull/18718) (@petrosagg)
* [ ] [#18818 docs: Update create pg source docs for schemas](https://github.com/MaterializeInc/materialize/pull/18818) (@jkosh44)
* [ ] [#18825 persist: remove `CmdMetrics::run_cmd`](https://github.com/MaterializeInc/materialize/pull/18825) (@pH14)
* [ ] [#18312 adapter: Restrict the queries that can run on mz_introspection](https://github.com/MaterializeInc/materialize/pull/18312) (@parker-timmerman)
* [ ] [#18811 sql: Add parsing for grant/revoke privileges](https://github.com/MaterializeInc/materialize/pull/18811) (@jkosh44)
* [ ] [#18546 Monotonic select](https://github.com/MaterializeInc/materialize/pull/18546) (@frankmcsherry)
* [ ] [#18828 adapter: Update catalog schema IDs namespace](https://github.com/MaterializeInc/materialize/pull/18828) (@jkosh44)
* [ ] [#18709 test: add platform checks for RANGE type](https://github.com/MaterializeInc/materialize/pull/18709) (@nrainer-materialize)
* [ ] [#18412 Doc: SSH host troubleshooting steps](https://github.com/MaterializeInc/materialize/pull/18412) (@bobbyiliev)
* [ ] [#18831 ci: Add further range tests](https://github.com/MaterializeInc/materialize/pull/18831) (@nrainer-materialize)
* [ ] [#18833 testdrive: Fix indexes.td](https://github.com/MaterializeInc/materialize/pull/18833) (@philip-stoev)
* [ ] [#18814 docs: Describe PR Code Coverage](https://github.com/MaterializeInc/materialize/pull/18814) (@def-)
* [ ] [#18834 ci nightly: Remove SLT coverage](https://github.com/MaterializeInc/materialize/pull/18834) (@def-)
* [ ] [#18836 coverage: Use exclamation mark to mark uncovered lines](https://github.com/MaterializeInc/materialize/pull/18836) (@def-)
* [ ] [#18821 python: Remove unnecessary f-strings](https://github.com/MaterializeInc/materialize/pull/18821) (@def-)
* [ ] [#18760 design doc: Faster Dataflow Shutdown](https://github.com/MaterializeInc/materialize/pull/18760) (@teskje)
* [ ] [#18838 test,docs: in cloudtest.md, add small troubleshooting section](https://github.com/MaterializeInc/materialize/pull/18838) (@aljoscha)
* [ ] [#18782 pg sources: subsource health status + snapshot resumption test](https://github.com/MaterializeInc/materialize/pull/18782) (@sploiselle)
* [ ] [#17836 Add design doc for proposed changes to `mz_internal`](https://github.com/MaterializeInc/materialize/pull/17836) (@umanwizard)
* [ ] [#18722 Design doc for upsert order by timestamp](https://github.com/MaterializeInc/materialize/pull/18722) (@moulimukherjee)
* [ ] [#18806 Add test for `oom-killed` reason in `mz_cluster_replica_statuses`](https://github.com/MaterializeInc/materialize/pull/18806) (@umanwizard)
* [ ] [#18850 reduce the number of dependencies pulled in by a few crates](https://github.com/MaterializeInc/materialize/pull/18850) (@doy-materialize)
* [ ] [#18853 [sinks] Fail open when we can't fetch Kafka config](https://github.com/MaterializeInc/materialize/pull/18853) (@bkirwi)
* [ ] [#17702 doc: Add design doc for RBAC](https://github.com/MaterializeInc/materialize/pull/17702) (@jkosh44)
* [ ] [#18840 doc/user: polish v0.51 release notes](https://github.com/MaterializeInc/materialize/pull/18840) (@morsapaes)
* [ ] [#18743 doc/user document reserved disk_bytes fields in usage tables](https://github.com/MaterializeInc/materialize/pull/18743) (@guswynn)
* [ ] [#18856 stash-debug: teach upgrade check about replica sizes](https://github.com/MaterializeInc/materialize/pull/18856) (@mjibson)
* [ ] [#18812 ci: Test output consistency between constant-folding vs. rendered query evaluations](https://github.com/MaterializeInc/materialize/pull/18812) (@nrainer-materialize)
* [ ] [#18860 python: Fix for removed f-strings](https://github.com/MaterializeInc/materialize/pull/18860) (@def-)
* [ ] [#18861 cloudtest: Fortify the test_oom_clusterd test](https://github.com/MaterializeInc/materialize/pull/18861) (@philip-stoev)
* [ ] [#18863 docs: Link to PR code coverage from testing guide](https://github.com/MaterializeInc/materialize/pull/18863) (@def-)
* [ ] [#18827 sql: Implement grant and revoke privilege](https://github.com/MaterializeInc/materialize/pull/18827) (@jkosh44)
* [ ] [#18692 [skunkworks] persist: Don't copy into a single Vec for S3 Blob](https://github.com/MaterializeInc/materialize/pull/18692) (@parker-timmerman)
* [ ] [#18844 Don't force "before" to exist in Debezium](https://github.com/MaterializeInc/materialize/pull/18844) (@umanwizard)
* [ ] [#18867 Add deserialize derive for the pub struct AppPassword](https://github.com/MaterializeInc/materialize/pull/18867) (@joacoc)
* [ ] [#18847 compute: Guarantee that subscribe response data is consolidated](https://github.com/MaterializeInc/materialize/pull/18847) (@andrewrodriguez-m)
* [ ] [#18870 doc/user: remove mentions to PRIMARY KEY...NOT ENFORCED clause](https://github.com/MaterializeInc/materialize/pull/18870) (@morsapaes)
* [ ] [#18878 storage: simplify upsert state management into read and write halves](https://github.com/MaterializeInc/materialize/pull/18878) (@guswynn)
* [ ] [#18873 sql: Allow dropping non-owned descendants](https://github.com/MaterializeInc/materialize/pull/18873) (@jkosh44)
* [ ] [#18877 sql: Correct ownership semantics of indexes](https://github.com/MaterializeInc/materialize/pull/18877) (@jkosh44)
* [ ] [#18887 storage: in NULL-key error message, give hint for resolving it](https://github.com/MaterializeInc/materialize/pull/18887) (@aljoscha)
* [ ] [#18891 python: Fix another removed f-string](https://github.com/MaterializeInc/materialize/pull/18891) (@def-)
* [ ] [#18892 testdrive: Fortify testdrive-fortify-divergent-dataflow-cancellation.td](https://github.com/MaterializeInc/materialize/pull/18892) (@philip-stoev)
* [ ] [#18862 upgrade test: Fix the UpgradeEntireMzFourVersions scenario](https://github.com/MaterializeInc/materialize/pull/18862) (@philip-stoev)
* [ ] [#18648 persist: introduce filter pushdown audit](https://github.com/MaterializeInc/materialize/pull/18648) (@danhhz)
* [ ] [#18846 adapter: Add resource limit for compute credits](https://github.com/MaterializeInc/materialize/pull/18846) (@jkosh44)
* [ ] [#18857 sql: support array casting](https://github.com/MaterializeInc/materialize/pull/18857) (@rkrishn7)
* [ ] [`e67eb3fd0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e67eb3fd01e3d4d019f08070a93a025ac9af0a54) (@materializer)
* [ ] [`9376cd633` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9376cd633bb3e689731c2bdcac8d54abceece764) (@materializer)
* [ ] [`6609956ee` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/6609956eef5eca14d57c1859b5e8a18d966620b3) (@materializer)
* [ ] [`85ef9f5cf` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/85ef9f5cfd190c1fde45b69537c98bc6ba3bdc9e) (@materializer)
* [ ] [`e781222ea` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e781222ea382aa6a7eee1b0e50e94218988f4cad) (@materializer)
* [ ] [`25be1e8e3` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/25be1e8e3709644bf0a36c1b10e12d32d061a91f) (@materializer)
* [ ] [`07f75a9fd` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/07f75a9fd2e06e8c995de521d356c18070c121de) (@materializer)
* [ ] [`e36d098e6` release: bump to version v0.52.0](https://github.com/MaterializeInc/materialize/commit/e36d098e6bb499ce24052bf78abd86b166a24b53) (@sploiselle)

**Comment by sploiselle** [comment]
All unreviewed commits/PRs that are not mine LGTM.

**Comment by benesch** [comment]
Sean's commits/PRs LGTM.
