### ISSUE TITLE
release: v0.53.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#19130]
The following PRs in [`v0.53.0`](https://github.com/MaterializeInc/materialize/tree/v0.53.0) require review:
* [x] [#18923 nix: add required env var for building librocksdb-sys](https://github.com/MaterializeInc/materialize/pull/18923) (@petrosagg)
* [x] [#19057 pgtest: fix range test file](https://github.com/MaterializeInc/materialize/pull/19057) (@sploiselle)
* [x] [#19062 pgrepr: fix numeric encoding for 0](https://github.com/MaterializeInc/materialize/pull/19062) (@sploiselle)
* [x] [#19111 doc/developer: s/smz.testdrive.run_string/mz.testdrive.run](https://github.com/MaterializeInc/materialize/pull/19111) (@sploiselle)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`40062bd0c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/40062bd0cab5e0bd0dd4c70e361545fbd3c71e2f) (@materializer)
* [x] [`693f5d205` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/693f5d205de501e353451c79c2b2e01dacc91d95) (@materializer)
* [x] [`a4d7b3b36` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a4d7b3b366a21f9e3cd6923fa79fa5dfd13bd89d) (@materializer)
* [x] [`7659b5396` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7659b5396ab906852e74cad2845a9635e8b1e237) (@materializer)
* [x] [`822652594` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/82265259481d83b9ee0c83637d91ec77e10b65df) (@materializer)
* [x] [`e88dc889a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e88dc889aebcc26553f226f91a50c2d30d523a44) (@materializer)
* [x] [`ba167f8c7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ba167f8c7659933e3f8455e8aaea87a4c3da207d) (@materializer)
* [x] [`9c631c870` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9c631c870c05a2e78f542ce64a91514b1d21f88b) (@materializer)
* [x] [`fa6bb0064` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fa6bb00645617ac4dc9ccbff26f9181ef1d3c5fa) (@materializer)
* [x] [`5389250db` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5389250dba428a585be849a1f5587ee97bab13af) (@materializer)
* [x] [`ff5c72d41` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ff5c72d411cbb6f9f4868469c07eeaef726d2bc4) (@materializer)
* [ ] [`92c760eb4` release: bump to version v0.53.0](https://github.com/MaterializeInc/materialize/commit/92c760eb465e9a78966e450f0560dc1fdf02ed6f) (@danhhz)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18923 nix: add required env var for building librocksdb-sys](https://github.com/MaterializeInc/materialize/pull/18923) (@petrosagg)
* [ ] [#18864 sql: make error message of `require_unsafe_mode` more actionable](https://github.com/MaterializeInc/materialize/pull/18864) (@aljoscha)
* [ ] [#18874 test refactoring: extract common schema definition from platform checks](https://github.com/MaterializeInc/materialize/pull/18874) (@nrainer-materialize)
* [ ] [#18558 upgrade-matrix: Comprehensive upgrade testing](https://github.com/MaterializeInc/materialize/pull/18558) (@philip-stoev)
* [ ] [#17669 storage: assert on update_read_capabilities](https://github.com/MaterializeInc/materialize/pull/17669) (@aljoscha)
* [ ] [#18922 test: Ignore drain timeouts during a CRDB rolling restart test](https://github.com/MaterializeInc/materialize/pull/18922) (@philip-stoev)
* [ ] [#18914 controller: serde ReplicaAllocation credits_per_hour via strings](https://github.com/MaterializeInc/materialize/pull/18914) (@sploiselle)
* [ ] [#18911 Include IN CLUSTER in source creation error message](https://github.com/MaterializeInc/materialize/pull/18911) (@chaas)
* [ ] [#18876 Retain and index `mz_cluster_replica_statuses`](https://github.com/MaterializeInc/materialize/pull/18876) (@umanwizard)
* [ ] [#18875 ci: add multiple_partitions platform check](https://github.com/MaterializeInc/materialize/pull/18875) (@nrainer-materialize)
* [ ] [#18915 adapter: Remove dead code](https://github.com/MaterializeInc/materialize/pull/18915) (@jkosh44)
* [ ] [#18926 test: Fix upgrade role tests](https://github.com/MaterializeInc/materialize/pull/18926) (@jkosh44)
* [ ] [#18893 `NormalizeLets` -- inlining at inner nesting levels](https://github.com/MaterializeInc/materialize/pull/18893) (@ggevay)
* [ ] [#18929 build(deps): bump enumflags2 v0.7.1 -> v0.7.7](https://github.com/MaterializeInc/materialize/pull/18929) (@def-)
* [ ] [#18916 stash: batch large updates](https://github.com/MaterializeInc/materialize/pull/18916) (@mjibson)
* [ ] [#18841 persist: reintroduce `shard_source_fetch` token](https://github.com/MaterializeInc/materialize/pull/18841) (@pH14)
* [ ] [#18902 persist: fix test flake in test_truncate_string_proptest](https://github.com/MaterializeInc/materialize/pull/18902) (@danhhz)
* [ ] [#18909 release: bump to version v0.53.0-dev](https://github.com/MaterializeInc/materialize/pull/18909) (@sploiselle)
* [ ] [#18925 controller: test deserialization of ReplicaAllocation from json](https://github.com/MaterializeInc/materialize/pull/18925) (@sploiselle)
* [ ] [#18449 storage: finalize dropped shards take 2](https://github.com/MaterializeInc/materialize/pull/18449) (@sploiselle)
* [ ] [#18793 sql: support join_using_alias](https://github.com/MaterializeInc/materialize/pull/18793) (@rkrishn7)
* [ ] [#18939 coverage: Environment variable improvements](https://github.com/MaterializeInc/materialize/pull/18939) (@def-)
* [ ] [#18930 Rework `literal_lifting` so it is `recursion_safe`](https://github.com/MaterializeInc/materialize/pull/18930) (@aalexandrov)
* [ ] [#18942 test,storage: add test for debezium sources without `before` field](https://github.com/MaterializeInc/materialize/pull/18942) (@aljoscha)
* [ ] [#18945 test/zippy: re-enable info logs](https://github.com/MaterializeInc/materialize/pull/18945) (@benesch)
* [ ] [#18937 orchestrator-process: push removal of UDS sockets into Listener::bind](https://github.com/MaterializeInc/materialize/pull/18937) (@benesch)
* [ ] [#18927 compute: tokenize delta join operator](https://github.com/MaterializeInc/materialize/pull/18927) (@teskje)
* [ ] [#18951 Add kill switch to LaunchDarkly](https://github.com/MaterializeInc/materialize/pull/18951) (@umanwizard)
* [ ] [#18961 ci: Fortify source-sink-errors](https://github.com/MaterializeInc/materialize/pull/18961) (@philip-stoev)
* [ ] [#18963 cloudtest: Fortify test_missing_secret](https://github.com/MaterializeInc/materialize/pull/18963) (@philip-stoev)
* [ ] [#18815 coverage: Enable cloudtest](https://github.com/MaterializeInc/materialize/pull/18815) (@def-)
* [ ] [#18969 pg-cdc: Test that the Pg snapshot is not re-ingested on restart](https://github.com/MaterializeInc/materialize/pull/18969) (@philip-stoev)
* [ ] [#18964 tests: Add role_create.slt](https://github.com/MaterializeInc/materialize/pull/18964) (@def-)
* [ ] [#18952 Fix `LetRec` lowering when inserting an `ArrangeBy`](https://github.com/MaterializeInc/materialize/pull/18952) (@ggevay)
* [ ] [#18822 storage: FORMAT JSON](https://github.com/MaterializeInc/materialize/pull/18822) (@sploiselle)
* [ ] [#18778 persist: react immediately to state changes in the same process](https://github.com/MaterializeInc/materialize/pull/18778) (@danhhz)
* [ ] [#18975 sql: Populate pg_auth_members](https://github.com/MaterializeInc/materialize/pull/18975) (@jkosh44)
* [ ] [#18976 adapter: Update attributes for linked clusters](https://github.com/MaterializeInc/materialize/pull/18976) (@jkosh44)
* [ ] [#18903 coverage: Enable unit tests](https://github.com/MaterializeInc/materialize/pull/18903) (@def-)
* [ ] [#18935 adapter: Generate privileges for SQL statement](https://github.com/MaterializeInc/materialize/pull/18935) (@jkosh44)
* [ ] [#18810 storage: abstract upsert state into a trait](https://github.com/MaterializeInc/materialize/pull/18810) (@guswynn)
* [ ] [#18859 doc/user: Refresh the Getting Started guide](https://github.com/MaterializeInc/materialize/pull/18859) (@jseldess)
* [ ] [#18982 fix: `mz_ore` features](https://github.com/MaterializeInc/materialize/pull/18982) (@ParkMyCar)
* [ ] [#18986 sql: don't advance AS OF AT LEAST to upper](https://github.com/MaterializeInc/materialize/pull/18986) (@mjibson)
* [ ] [#18983 Improve `test_utilization_hold`.](https://github.com/MaterializeInc/materialize/pull/18983) (@umanwizard)
* [ ] [#18985 Bump tiberius and connection-string versions](https://github.com/MaterializeInc/materialize/pull/18985) (@umanwizard)
* [ ] [#18987 Bump fs_extra version](https://github.com/MaterializeInc/materialize/pull/18987) (@umanwizard)
* [ ] [#18990 storage: bring back "Starting" status](https://github.com/MaterializeInc/materialize/pull/18990) (@petrosagg)
* [ ] [#18955 doc/user: add documentation for inline Protobuf schemas](https://github.com/MaterializeInc/materialize/pull/18955) (@benesch)
* [ ] [#18995 coverage: Try release build for unittests](https://github.com/MaterializeInc/materialize/pull/18995) (@def-)
* [ ] [#18997 test: Fix the FormatJson scenario in the sql-feature-flags test](https://github.com/MaterializeInc/materialize/pull/18997) (@philip-stoev)
* [ ] [#18998 only write health statuses from the active worker](https://github.com/MaterializeInc/materialize/pull/18998) (@petrosagg)
* [ ] [#18965 storage: move `responsible_for` fn to a better place](https://github.com/MaterializeInc/materialize/pull/18965) (@petrosagg)
* [ ] [#18999 cloudtest: Fortify test_missing_secret (take #2)](https://github.com/MaterializeInc/materialize/pull/18999) (@philip-stoev)
* [ ] [#19001 coverage: Add workaround for invalid profraw files](https://github.com/MaterializeInc/materialize/pull/19001) (@def-)
* [ ] [#18881 design: Improved Stash Migrations](https://github.com/MaterializeInc/materialize/pull/18881) (@parker-timmerman)
* [ ] [#19000 doc/user: polish v0.52 release notes](https://github.com/MaterializeInc/materialize/pull/19000) (@morsapaes)
* [ ] [#18888 doc/user: update What is Materialize?](https://github.com/MaterializeInc/materialize/pull/18888) (@morsapaes)
* [ ] [#17462 storage: cleanup dropped IDs](https://github.com/MaterializeInc/materialize/pull/17462) (@sploiselle)
* [ ] [#19014 storage: don't panic during shutdown](https://github.com/MaterializeInc/materialize/pull/19014) (@petrosagg)
* [ ] [#18984 persist: rework JsonStats](https://github.com/MaterializeInc/materialize/pull/18984) (@danhhz)
* [ ] [#18993 adapter: optimize peeks before timestamp determination](https://github.com/MaterializeInc/materialize/pull/18993) (@mjibson)
* [ ] [#18799 docs: Update CREATEROLE attribute docs](https://github.com/MaterializeInc/materialize/pull/18799) (@jkosh44)
* [ ] [#19018 adapter: re-verify and plan off-thread statements](https://github.com/MaterializeInc/materialize/pull/19018) (@mjibson)
* [ ] [#19021 build(deps): bump bumpalo v3.2.1 -> v3.12.1](https://github.com/MaterializeInc/materialize/pull/19021) (@def-)
* [ ] [#19015 storage: dont use http proxies for csr-over-ssh](https://github.com/MaterializeInc/materialize/pull/19015) (@guswynn)
* [ ] [#19007 test: move FORMAT JSON tests to json_source.py](https://github.com/MaterializeInc/materialize/pull/19007) (@sploiselle)
* [ ] [#19027 Update differential-dataflow](https://github.com/MaterializeInc/materialize/pull/19027) (@teskje)
* [ ] [#19029 cloudtest: Pass --orchestrator-kubernetes-coverage only if supported](https://github.com/MaterializeInc/materialize/pull/19029) (@philip-stoev)
* [ ] [#19003 compute/reconcile: don't report dropped collections](https://github.com/MaterializeInc/materialize/pull/19003) (@teskje)
* [ ] [#19009 stash: Add initial protobuf schemas](https://github.com/MaterializeInc/materialize/pull/19009) (@ParkMyCar)
* [ ] [#19028 coverage: Fix unit test coverage](https://github.com/MaterializeInc/materialize/pull/19028) (@def-)
* [ ] [#19036 build(deps): bump h2 v0.3.13 -> v0.3.18](https://github.com/MaterializeInc/materialize/pull/19036) (@def-)
* [ ] [#19016 docs: Add namespace info to create source](https://github.com/MaterializeInc/materialize/pull/19016) (@jkosh44)
* [ ] [#19042 dbt-materialize: release v1.4.1](https://github.com/MaterializeInc/materialize/pull/19042) (@benesch)
* [ ] [#19045 doc/user: Add schema creation step to getting started guide](https://github.com/MaterializeInc/materialize/pull/19045) (@jseldess)
* [ ] [#19047 Be more precise about third-party tools support](https://github.com/MaterializeInc/materialize/pull/19047) (@jseldess)
* [ ] [#19041 adapter: Allow more kinds of queries to be run on the `mz_introspection` cluster](https://github.com/MaterializeInc/materialize/pull/19041) (@ParkMyCar)
* [ ] [#18829 Design doc for subscribe output types](https://github.com/MaterializeInc/materialize/pull/18829) (@andrewrodriguez-m)
* [ ] [#19032 doc/user: add release note about OOM observability](https://github.com/MaterializeInc/materialize/pull/19032) (@morsapaes)
* [ ] [#19048 deps: Upgrade AWS Deps](https://github.com/MaterializeInc/materialize/pull/19048) (@ParkMyCar)
* [ ] [#19057 pgtest: fix range test file](https://github.com/MaterializeInc/materialize/pull/19057) (@sploiselle)
* [ ] [#19062 pgrepr: fix numeric encoding for 0](https://github.com/MaterializeInc/materialize/pull/19062) (@sploiselle)
* [ ] [#19058 sql: Fix panic on correlated casts](https://github.com/MaterializeInc/materialize/pull/19058) (@jkosh44)
* [ ] [#19070 stash: don't bust compilation cache on every compile](https://github.com/MaterializeInc/materialize/pull/19070) (@benesch)
* [ ] [#19061 pg sources: support complex identifiers in table names](https://github.com/MaterializeInc/materialize/pull/19061) (@sploiselle)
* [ ] [#18816 sql: improve known limitations for tables](https://github.com/MaterializeInc/materialize/pull/18816) (@benesch)
* [ ] [#19008 environmentd: Add boostrap role to startup](https://github.com/MaterializeInc/materialize/pull/19008) (@jkosh44)
* [ ] [#19002 ci: Bump the postgres container to version 15.2](https://github.com/MaterializeInc/materialize/pull/19002) (@philip-stoev)
* [ ] [#19053 sql: error if lacking SELECT privileges on PG source tables](https://github.com/MaterializeInc/materialize/pull/19053) (@sploiselle)
* [ ] [#19073 parser: Clarify item vs object in comments](https://github.com/MaterializeInc/materialize/pull/19073) (@jkosh44)
* [ ] [#19074 docs: Add docs for mz_aclitem](https://github.com/MaterializeInc/materialize/pull/19074) (@jkosh44)
* [ ] [#19072 .github: various issue template improvements](https://github.com/MaterializeInc/materialize/pull/19072) (@benesch)
* [ ] [#18944 test: Add queries from web console to testdrive](https://github.com/MaterializeInc/materialize/pull/18944) (@ParkMyCar)
* [ ] [#18723 adapter: Support subscribe output modifiers](https://github.com/MaterializeInc/materialize/pull/18723) (@andrewrodriguez-m)
* [ ] [#19076 test: fix conflicting table names in pg-cdc tests](https://github.com/MaterializeInc/materialize/pull/19076) (@sploiselle)
* [ ] [#19019 persist: implement stats trimming](https://github.com/MaterializeInc/materialize/pull/19019) (@danhhz)
* [ ] [#19075 Various coverage improvements](https://github.com/MaterializeInc/materialize/pull/19075) (@def-)
* [ ] [#18854 Frontegg-client](https://github.com/MaterializeInc/materialize/pull/18854) (@joacoc)
* [ ] [#19083 platform-checks: Wait for Pg snapshots to complete when upgrading fro…](https://github.com/MaterializeInc/materialize/pull/19083) (@philip-stoev)
* [ ] [#19084 coverage: Down containers to prevent FS strangeness](https://github.com/MaterializeInc/materialize/pull/19084) (@def-)
* [ ] [#19077 plan: use human-readable connection name in error](https://github.com/MaterializeInc/materialize/pull/19077) (@jkosh44)
* [ ] [#18992 update clap and fix 1.69 clippy lints](https://github.com/MaterializeInc/materialize/pull/18992) (@guswynn)
* [ ] [#19087 Improve a few comments](https://github.com/MaterializeInc/materialize/pull/19087) (@umanwizard)
* [ ] [#19081 adapter: Add metrics for subscribe output usage](https://github.com/MaterializeInc/materialize/pull/19081) (@andrewrodriguez-m)
* [ ] [#19086 adapter: Add log for session panic](https://github.com/MaterializeInc/materialize/pull/19086) (@jkosh44)
* [ ] [#19010 Rework `non_null_requirements` so it is `recursion_safe`](https://github.com/MaterializeInc/materialize/pull/19010) (@aalexandrov)
* [ ] [#18879 persist: add initial pushdown metrics](https://github.com/MaterializeInc/materialize/pull/18879) (@danhhz)
* [ ] [#17677 cluster-unification/storage: make it more explicit that storage connects to the last replica](https://github.com/MaterializeInc/materialize/pull/17677) (@guswynn)
* [ ] [#19090 test: Move web console tests to sqllitetest](https://github.com/MaterializeInc/materialize/pull/19090) (@ParkMyCar)
* [ ] [#19091 adapter: Limit number of concurrent connections](https://github.com/MaterializeInc/materialize/pull/19091) (@andrewrodriguez-m)
* [ ] [#19094 .github: remove unused issue templates](https://github.com/MaterializeInc/materialize/pull/19094) (@uce)
* [ ] [#19105 ore: remove PANIC_ON_HALT](https://github.com/MaterializeInc/materialize/pull/19105) (@danhhz)
* [ ] [#19107 testdrive: Fortify subscribe-output.td](https://github.com/MaterializeInc/materialize/pull/19107) (@philip-stoev)
* [ ] [#19110 doc/user: Update sign up link](https://github.com/MaterializeInc/materialize/pull/19110) (@jseldess)
* [ ] [#19108 cloudtest: Dump stdout/stderr on failed kubectl calls](https://github.com/MaterializeInc/materialize/pull/19108) (@philip-stoev)
* [ ] [#19111 doc/developer: s/smz.testdrive.run_string/mz.testdrive.run](https://github.com/MaterializeInc/materialize/pull/19111) (@sploiselle)
* [ ] [#18932 [persist] ResultSpec for MirScalarExpr](https://github.com/MaterializeInc/materialize/pull/18932) (@bkirwi)
* [ ] [#19103 persist: hook stats filter auditing up to a LaunchDarkly config](https://github.com/MaterializeInc/materialize/pull/19103) (@danhhz)
* [ ] [#19114 Revert "adapter: Limit number of concurrent connections"](https://github.com/MaterializeInc/materialize/pull/19114) (@andrewrodriguez-m)
* [ ] [#19116 frontegg-client: turn pub 'fn auth()'](https://github.com/MaterializeInc/materialize/pull/19116) (@joacoc)
* [ ] [#19119 adapter: Update autorun on introspection cluster](https://github.com/MaterializeInc/materialize/pull/19119) (@jkosh44)
* [ ] [#19125 ci: Fortify the pg-cdc-resumption scenario](https://github.com/MaterializeInc/materialize/pull/19125) (@philip-stoev)
* [ ] [#19127 [expr] Ignore equivalence test](https://github.com/MaterializeInc/materialize/pull/19127) (@bkirwi)
* [ ] [#19128 persist: don't truncate serialized proto bytes stats](https://github.com/MaterializeInc/materialize/pull/19128) (@danhhz)
* [ ] [#19129 mzcompose: Allow --project-name](https://github.com/MaterializeInc/materialize/pull/19129) (@def-)
* [ ] [#19117 adapter: Limit number of concurrent connections (#19091)](https://github.com/MaterializeInc/materialize/pull/19117) (@andrewrodriguez-m)
* [ ] [`40062bd0c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/40062bd0cab5e0bd0dd4c70e361545fbd3c71e2f) (@materializer)
* [ ] [`693f5d205` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/693f5d205de501e353451c79c2b2e01dacc91d95) (@materializer)
* [ ] [`a4d7b3b36` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a4d7b3b366a21f9e3cd6923fa79fa5dfd13bd89d) (@materializer)
* [ ] [`7659b5396` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7659b5396ab906852e74cad2845a9635e8b1e237) (@materializer)
* [ ] [`822652594` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/82265259481d83b9ee0c83637d91ec77e10b65df) (@materializer)
* [ ] [`e88dc889a` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e88dc889aebcc26553f226f91a50c2d30d523a44) (@materializer)
* [ ] [`ba167f8c7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ba167f8c7659933e3f8455e8aaea87a4c3da207d) (@materializer)
* [ ] [`9c631c870` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9c631c870c05a2e78f542ce64a91514b1d21f88b) (@materializer)
* [ ] [`fa6bb0064` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/fa6bb00645617ac4dc9ccbff26f9181ef1d3c5fa) (@materializer)
* [ ] [`5389250db` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5389250dba428a585be849a1f5587ee97bab13af) (@materializer)
* [ ] [`ff5c72d41` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/ff5c72d411cbb6f9f4868469c07eeaef726d2bc4) (@materializer)
* [ ] [`92c760eb4` release: bump to version v0.53.0](https://github.com/MaterializeInc/materialize/commit/92c760eb465e9a78966e450f0560dc1fdf02ed6f) (@danhhz)

**Comment by danhhz** [comment]
All unreviewed commits other than mine LGTM

**Comment by jkosh44** [comment]
@danhhz unreviewed commit LGTM
