### ISSUE TITLE
release: v0.54.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#19261]
The following PRs in [`v0.54.0`](https://github.com/MaterializeInc/materialize/tree/v0.54.0) require review:
* [x] [#19141 doc/user: fix double "the" in identifiers doc](https://github.com/MaterializeInc/materialize/pull/19141) (@benesch)
* [x] [#19150 Add libclang-dev to scratch instances](https://github.com/MaterializeInc/materialize/pull/19150) (@tokenrove)
* [x] [#19204 Fix the rendering of bitwise OR in the docs](https://github.com/MaterializeInc/materialize/pull/19204) (@tokenrove)
* [x] [#19212 doc/user: polish v0.53 release notes](https://github.com/MaterializeInc/materialize/pull/19212) (@morsapaes)
* [x] [#19248 doc/user: patch link to quickstart in Get Started landing page](https://github.com/MaterializeInc/materialize/pull/19248) (@morsapaes)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`241686ff9` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/241686ff9ae781a1bc0273fc9bb5114456ede1c3) (@materializer)
* [x] [`5248b46af` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5248b46af37fc4ac3dae7cb2ec27c49011dc6477) (@materializer)
* [x] [`a51c564e5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a51c564e5d0b010595b4af8190db12ec28e7f5a8) (@materializer)
* [x] [`73f10f367` ci: separate docs deploy pipeline](https://github.com/MaterializeInc/materialize/commit/73f10f3674fdd4d647a8a3636a199d11904f9dcf) (@benesch)
* [x] [`677e41843` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/677e418436bffa7f1e02139b1f86145a2f407f4b) (@materializer)
* [x] [`d454deb4b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d454deb4beef71a41539ad3bd64b82d9680dbb40) (@materializer)
* [x] [`97b50ecd7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/97b50ecd7845ce2afdceaf5d5af37c48a7921b9c) (@materializer)
* [x] [`18d038a9c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/18d038a9ced2d1aa54fc318ba0c0521660a77309) (@materializer)
* [x] [`4f02a15a4` release: bump to version v0.54.0](https://github.com/MaterializeInc/materialize/commit/4f02a15a40f220061a1c150c245f469682f741c9) (@jkosh44)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#18576 build(deps): bump async-trait from 0.1.59 to 0.1.68](https://github.com/MaterializeInc/materialize/pull/18576) (@dependabot[bot])
* [ ] [#17038 release qualification: Add a feature benchmark run with --size=+1](https://github.com/MaterializeInc/materialize/pull/17038) (@philip-stoev)
* [ ] [#19131 release: bump to version v0.54.0-dev](https://github.com/MaterializeInc/materialize/pull/19131) (@danhhz)
* [ ] [#18980 adapter: Implement privilege checks](https://github.com/MaterializeInc/materialize/pull/18980) (@jkosh44)
* [ ] [#19141 doc/user: fix double "the" in identifiers doc](https://github.com/MaterializeInc/materialize/pull/19141) (@benesch)
* [ ] [#19145 platform-checks: Enable permissions after upgrade](https://github.com/MaterializeInc/materialize/pull/19145) (@def-)
* [ ] [#19150 Add libclang-dev to scratch instances](https://github.com/MaterializeInc/materialize/pull/19150) (@tokenrove)
* [ ] [#19050 RBAC: Add test privileges_pg.slt](https://github.com/MaterializeInc/materialize/pull/19050) (@def-)
* [ ] [#19132 sql: Restrict role attribute granting](https://github.com/MaterializeInc/materialize/pull/19132) (@jkosh44)
* [ ] [#19049 storage: add WITH (DISK) support to upsert sources](https://github.com/MaterializeInc/materialize/pull/19049) (@guswynn)
* [ ] [#19159 Add mz_internal.mz_cluster_replica_history view](https://github.com/MaterializeInc/materialize/pull/19159) (@umanwizard)
* [ ] [#19113 storage: correct syntax in design doc](https://github.com/MaterializeInc/materialize/pull/19113) (@moulimukherjee)
* [ ] [#19089 adapter: Subscribe with envelope debezium](https://github.com/MaterializeInc/materialize/pull/19089) (@andrewrodriguez-m)
* [ ] [#19171 sql: Add multi-role grant/revoke privilege stmt](https://github.com/MaterializeInc/materialize/pull/19171) (@jkosh44)
* [ ] [#19060 storage: on boot, keep only the most recent source status history](https://github.com/MaterializeInc/materialize/pull/19060) (@sploiselle)
* [ ] [#19026 adapter: fix explain timestamp during transactional contexts](https://github.com/MaterializeInc/materialize/pull/19026) (@rkrishn7)
* [ ] [#19181 sql: Add ALL keyword to grant and revoke stmts](https://github.com/MaterializeInc/materialize/pull/19181) (@jkosh44)
* [ ] [#19185 sql: Fix role specification parsing](https://github.com/MaterializeInc/materialize/pull/19185) (@jkosh44)
* [ ] [#19189 adapter: Fix AS OF panics in transactions](https://github.com/MaterializeInc/materialize/pull/19189) (@jkosh44)
* [ ] [#19193 coverage: Also use clusterd binary when running SLT](https://github.com/MaterializeInc/materialize/pull/19193) (@def-)
* [ ] [#19192 adapter: fix AS OF AT LEAST timestamp selection](https://github.com/MaterializeInc/materialize/pull/19192) (@mjibson)
* [ ] [#19196 ci: Reduce sqlsmith/sqlancer nightly runtimes to 50 min](https://github.com/MaterializeInc/materialize/pull/19196) (@def-)
* [ ] [#18748 Cloud API package](https://github.com/MaterializeInc/materialize/pull/18748) (@joacoc)
* [ ] [#19126 stash: Port initialization to Protobuf](https://github.com/MaterializeInc/materialize/pull/19126) (@ParkMyCar)
* [ ] [#19199 Explicit error msg for WMR with `linear_chains`](https://github.com/MaterializeInc/materialize/pull/19199) (@ggevay)
* [ ] [#19204 Fix the rendering of bitwise OR in the docs](https://github.com/MaterializeInc/materialize/pull/19204) (@tokenrove)
* [ ] [#19205 persist: in shard_source, eagerly downgrade to as_of](https://github.com/MaterializeInc/materialize/pull/19205) (@aljoscha)
* [ ] [#19190 explain: support `mz_now()` on select from indexed table](https://github.com/MaterializeInc/materialize/pull/19190) (@aalexandrov)
* [ ] [#19206 test: Fix flaky dropped source test](https://github.com/MaterializeInc/materialize/pull/19206) (@jkosh44)
* [ ] [#19172 doc: Refactor docs sidenav](https://github.com/MaterializeInc/materialize/pull/19172) (@jseldess)
* [ ] [#19158 ci: Add ci-apply-to to logged errors](https://github.com/MaterializeInc/materialize/pull/19158) (@def-)
* [ ] [#18938 doc/user: add documentation for JOIN ... USING ... AS](https://github.com/MaterializeInc/materialize/pull/18938) (@benesch)
* [ ] [#19156 storage: consider source's sinces](https://github.com/MaterializeInc/materialize/pull/19156) (@sploiselle)
* [ ] [#19195 adapter: check peek validity instead of replanning](https://github.com/MaterializeInc/materialize/pull/19195) (@mjibson)
* [ ] [#19212 doc/user: polish v0.53 release notes](https://github.com/MaterializeInc/materialize/pull/19212) (@morsapaes)
* [ ] [#19115 dbt-materialize: Additional 1.5 Tests](https://github.com/MaterializeInc/materialize/pull/19115) (@dehume)
* [ ] [#19216 cloudtest: improve debugging of testdrive failures](https://github.com/MaterializeInc/materialize/pull/19216) (@philip-stoev)
* [ ] [#19200 coverage: Don't print out unit-test-only and uncovered in one report](https://github.com/MaterializeInc/materialize/pull/19200) (@def-)
* [ ] [#19191 ci: protobuf linting (1/2): add buf config](https://github.com/MaterializeInc/materialize/pull/19191) (@nrainer-materialize)
* [ ] [#19203 pg sources: propagate running status to all subsources](https://github.com/MaterializeInc/materialize/pull/19203) (@sploiselle)
* [ ] [#19227 tests: Deal with different testdrive seed in json_source](https://github.com/MaterializeInc/materialize/pull/19227) (@def-)
* [ ] [#19044 storage: add source envelope metrics for tracking size in bytes and number of records](https://github.com/MaterializeInc/materialize/pull/19044) (@moulimukherjee)
* [ ] [#19232 test: Fix flaky test](https://github.com/MaterializeInc/materialize/pull/19232) (@jkosh44)
* [ ] [#19226 coverage: Don't try to deal with cargo-test](https://github.com/MaterializeInc/materialize/pull/19226) (@def-)
* [ ] [#19240 ci-builder: Bump sqlparse from 0.4.3 to 0.4.4](https://github.com/MaterializeInc/materialize/pull/19240) (@def-)
* [ ] [#19241 java-smoketest: Bump postgresql version from 42.3.0 to 42.6.0](https://github.com/MaterializeInc/materialize/pull/19241) (@def-)
* [ ] [#19242 add ability to set system parameter defaults dynamically](https://github.com/MaterializeInc/materialize/pull/19242) (@guswynn)
* [ ] [#19218 orchestrator-k8s: enable Guaranteed QoS for pods](https://github.com/MaterializeInc/materialize/pull/19218) (@teskje)
* [ ] [#19157 ci: protobuf linting (2/2): ci step to detect breaking changes](https://github.com/MaterializeInc/materialize/pull/19157) (@nrainer-materialize)
* [ ] [#19238 tests: Use json to extract timestamps from EXPLAIN TIMESTAMP](https://github.com/MaterializeInc/materialize/pull/19238) (@def-)
* [ ] [#18966 WMR soft limit](https://github.com/MaterializeInc/materialize/pull/18966) (@ggevay)
* [ ] [#18538 WMR limits design doc](https://github.com/MaterializeInc/materialize/pull/18538) (@ggevay)
* [ ] [#19223 explain: further align explain path with oneshot execution path](https://github.com/MaterializeInc/materialize/pull/19223) (@aalexandrov)
* [ ] [#19224 Fix join visitation](https://github.com/MaterializeInc/materialize/pull/19224) (@ggevay)
* [ ] [#19201 adapter: export `last_sse_time` from LD as a Prometheus metric](https://github.com/MaterializeInc/materialize/pull/19201) (@aalexandrov)
* [ ] [#19220 feature-benchmark: Add a scenario with many clusters](https://github.com/MaterializeInc/materialize/pull/19220) (@philip-stoev)
* [ ] [#19249 ci: Build before running SLT](https://github.com/MaterializeInc/materialize/pull/19249) (@def-)
* [ ] [#19248 doc/user: patch link to quickstart in Get Started landing page](https://github.com/MaterializeInc/materialize/pull/19248) (@morsapaes)
* [ ] [#19112 [persist] Use the new MFP filtering in the persist source](https://github.com/MaterializeInc/materialize/pull/19112) (@bkirwi)
* [ ] [#18981 persist: implementation of state pubsub over grpc](https://github.com/MaterializeInc/materialize/pull/18981) (@pH14)
* [ ] [#19173 [persist/expr] Fix error-swallowing behaviour in the expression interpreter](https://github.com/MaterializeInc/materialize/pull/19173) (@bkirwi)
* [ ] [#19175 sql: Add support for DROP OWNED statement](https://github.com/MaterializeInc/materialize/pull/19175) (@jkosh44)
* [ ] [#19257 Correcting the logic for diff_record](https://github.com/MaterializeInc/materialize/pull/19257) (@moulimukherjee)
* [ ] [#19259 [persist] Use the hacked version of the relationdesc to determine types](https://github.com/MaterializeInc/materialize/pull/19259) (@bkirwi)
* [ ] [`241686ff9` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/241686ff9ae781a1bc0273fc9bb5114456ede1c3) (@materializer)
* [ ] [`5248b46af` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5248b46af37fc4ac3dae7cb2ec27c49011dc6477) (@materializer)
* [ ] [`a51c564e5` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a51c564e5d0b010595b4af8190db12ec28e7f5a8) (@materializer)
* [ ] [`73f10f367` ci: separate docs deploy pipeline](https://github.com/MaterializeInc/materialize/commit/73f10f3674fdd4d647a8a3636a199d11904f9dcf) (@benesch)
* [ ] [`677e41843` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/677e418436bffa7f1e02139b1f86145a2f407f4b) (@materializer)
* [ ] [`d454deb4b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/d454deb4beef71a41539ad3bd64b82d9680dbb40) (@materializer)
* [ ] [`97b50ecd7` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/97b50ecd7845ce2afdceaf5d5af37c48a7921b9c) (@materializer)
* [ ] [`18d038a9c` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/18d038a9ced2d1aa54fc318ba0c0521660a77309) (@materializer)
* [ ] [`4f02a15a4` release: bump to version v0.54.0](https://github.com/MaterializeInc/materialize/commit/4f02a15a40f220061a1c150c245f469682f741c9) (@jkosh44)

**Comment by danhhz** [comment]
jkosh44's unreviewed commits + PRs lgtm

**Comment by jkosh44** [comment]
All unreviewed commits/PRs that are not mine LGTM.
