### ISSUE TITLE
[WIP] persist: FY24 Q2 checklist

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#19292]
# Update: Q1 is closed! Moved tracking to #21200

- [mfp] => #12684 
- [prod] => #18663
- [req] => requests from other teams/product for _new_ behavior
- [bug] => incorrect behavior

# Bugs
- [ ] [bug] #15937
- [ ] [bug] #17214
- [ ] [bug] #19608
- [ ] [bug] #19841
- [ ] [bug] #20042
- [ ] [bug] GC/Shard finalization follow-ups https://github.com/MaterializeInc/cloud/issues/6705 
- [ ] [bug] any needed follow-ups to https://github.com/MaterializeInc/materialize/issues/20287

# Now: FY24 Q2
- [x] [mfp] Turned on in prod
  - [x] #19338
  - [x] Merge #18007
  - [x] #19368
  - [x] Decide on a final SourceData <-> columnar mapping
    - [x] #https://github.com/MaterializeInc/materialize/pull/19309
  - [x] Decide on a final stats serialization
    - [x] #19801
    - [x] #19803
  - [x] Finalize initial interpreter impl
    - [x] #19366
    - [x] #19564
    - [x] #19528
    - [x] #19508
    - [x] #19448
    - [x] #19378
  - [x] Address all TODO(mfp)
    - [x] #19638
    - [x] #19646
    - [x] #19738
    - [x] #19802
  - [ ] persistcli tool for clearing stats on a shard(/env?)
  - [x] #19366
  - [x] #19399
  - [x] #19400
  - [x] #19402
  - [x] #19496
  - [ ] Add buf linting back for persist-types
  - [x] #19102
- [x] [epic] Reduce CRDB usage/cost
  - [x] #18981
    - [x] #19246
    - [x] Get this turned on in prod
- [ ] [epic] #16858
- [ ] [epic] TBD leasing/rollups/GC rework
  - [x] #17282
  - [ ] Resurrect #13961
  - [x] #18419
  - [ ] Turn on CRDB changefeeds -> s3 for all prod environments
    - Extremely useful for debugging/firefighting
    - Also likely a building block for implementing backup/restore
    - Maybe replaced by putting diffs in rollups?
  - [ ] Get rid of heartbeat-based leases
    - [Writers could move to an epoch bases system where epochs are versions of code](https://github.com/MaterializeInc/materialize/issues/20254)
    - Readers could either use ben's 🤯 idea or frank's "extreme" version
    - #15209    
- [x] [prod] Turn on S3 Versioning in prod
  - Currently waiting on validation of this in staging (30 days+)
- [x] [prod] Metric for per-shard breakdown of puts+gets
- [x] [prod] Put timeouts on all s3 and crdb usage (would have caught networking outage)
  - [x] CRDB tcp user timeouts (requires https://github.com/MaterializeInc/rust-postgres/pull/14)
- [x] [bug] #15985
  - [x] #17526
    - [x] Turn this on in prod
- [ ] [req] Implement backpressure in persist_source
  - Might come up again in the context of UPSERT source rehydration
  - [x] #16403
  - [x] [bug] #16807
  - [x] [bug] #16995
  - [ ] [Tuning the initial value of this](https://github.com/MaterializeInc/materialize/issues/15974#issuecomment-1428012662) is blocked on #16783

# Next: FY24 Q3 (epics first, otherwise not ordered)
- [epic] #19322
- [epic] Implement #18157
- [epic] #17777
- [epic] Actually delete and cleanup data
  - #17292
    - Blocked on S3 Versioning in prod
  - #17322

# Later: FY24 Q4+ (epics first, otherwise not ordered)
- [epic] write Schema-ified data blobs
- [epic] #16607
  - Break this down into chunks with incremental benefits
  - Serialize the internals of Spine instead of the raw batches
  - Fix the since used in compaction #15850
  - Consolidate the _deserialized_ K, V so encoding migrations work
  - Resurrect #15709
  - #17698
- [epic] Throughput tuning
  - #15518
  - Update open_loop benchmark to stress sharded reads and writes
  - #18066
- [epic] #16625
- [epic] Indexed lookup
- [epic] #17492
- [epic] #13918
- [epic] Bounding state size
- [epic] Consensus in-line writes
- [prod] #17776
- [prod] #19225
- [req] Optimization to "consolidate as we go" in decode_and_mfp
  - Instead of decode_one+mfp+repeat, decode and advance timestamps while accumulating the diff as long as you have the same KVT before handing the summed thing to mfp (skipping it entirely if diff=0, an important special case)
- [req] #16783
- [prod] Add version to inline part metadata
- [prod] Extend maelstrom coverage?
- Split mz_persist_client::internal into mz_persist
- [prod] Hook client auth for Consensus up in prod
- [prod] Petros's idea to have a sharded exchangeable description of assigned compaction work
- [prod] Aljoscha's idea to balance the compare_and_append work in persist_sink operator 3 instead of a fixed worker
- [prod] Proptest coverage of persist protos
  - #19425
  - Ditto for state diffs?
- [req] Structured logging
- [req] #17206
- [prod] #16699
- [prod] #12992
- [prod] #16652
  - Blocked on getting more experience debugging persist issues
  - Similarly, mental model of underlying costs for persist users
- [prod] dynamically resizable CRDB connection pool (allows throttling of individual envs / processes)
- [prod] prometheus histogram of batch part sizes
- [prod] faster fallback polling for state (use timestamp interval, poll fast after initial delay)
- [prod] https://github.com/MaterializeInc/materialize/issues/20222
- [req] https://github.com/MaterializeInc/materialize/issues/20618
```[tasklist]
### Tasks
- [ ] Wire up stats to a system var (and add extra budget for large parts)
```

**Comment by danhhz** [comment]
Update: Q1 is closed! Moved tracking to https://github.com/MaterializeInc/materialize/issues/21200
