### ISSUE TITLE
[Epic] Enable user to identify memory intensive indexes and materialized views

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#19350]
## Product Outcome
- Users can identify memory intensive / costly indexes and materialized views.
- These views will be an entry point into diagnostic tools: https://github.com/MaterializeInc/console/issues/96 and https://github.com/MaterializeInc/console/issues/95

## Documentation
- [Design](https://www.figma.com/file/AxoV6jI1dqRCGY4ZEj0xZU/Observability-%26-Troubleshooting?type=design&node-id=1076%3A13529&t=p0eyUls9SeqsiSNt-1)

## Issues
```[tasklist]
### Feature work
- [ ] https://github.com/MaterializeInc/console/issues/208
- [ ] https://github.com/MaterializeInc/materialize/issues/19348
- [ ] https://github.com/MaterializeInc/console/issues/219
```

```[tasklist]
### To fix before re-releasing
- [ ] https://github.com/MaterializeInc/materialize/issues/20185
- [x] Turn frontend feature flag back on
```

```[tasklist]
### Improvements
- [ ] https://github.com/MaterializeInc/console/issues/394
- [ ] https://github.com/MaterializeInc/console/issues/368
- [ ] https://github.com/MaterializeInc/console/issues/508
- [ ] https://github.com/MaterializeInc/console/pull/724
```

**Comment by ggnall** [comment]
Marking as down with Invoices available. Follow ons in:
- https://github.com/MaterializeInc/console/issues/374
- https://github.com/MaterializeInc/console/issues/272
