### ISSUE TITLE
release: v0.55.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#19385]
The following PRs in [`v0.55.0`](https://github.com/MaterializeInc/materialize/tree/v0.55.0) require review:
* [ ] [#19356 mzcompose: Allow Mzcompose to start containers with 'devel' or 'unsta…](https://github.com/MaterializeInc/materialize/pull/19356) (@philip-stoev)
* [ ] [#19354 mzcompose: Update Redpanda to v23.1.9](https://github.com/MaterializeInc/materialize/pull/19354) (@BenPope)
* [ ] [#19355 doc/user: polish release notes for v0.54](https://github.com/MaterializeInc/materialize/pull/19355) (@morsapaes)
* [ ] [#19293 doc: Update RBAC warning](https://github.com/MaterializeInc/materialize/pull/19293) (@jkosh44)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`02394d9fc` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/02394d9fc61b43f46dc42fe7bdea4626d2a928ab) (@materializer)
* [ ] [`4eddc5b7d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4eddc5b7d0344a95dd9614e08d7e7ff57d04c51b) (@materializer)
* [ ] [`1174e7050` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1174e7050f18ec4a316a231590b51a862728d889) (@materializer)
* [ ] [`52e5ec46e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/52e5ec46e2c995ff00175a2746657888275396c4) (@materializer)
* [ ] [`e273aabc8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e273aabc880f5a9dca6af6d6edc79f7f7e445e7a) (@materializer)
* [ ] [`9559fab7e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9559fab7e33814d6f1f8b5a76cc7a3d4cbb58663) (@materializer)
* [ ] [`54764be30` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/54764be3056aff757583647f39bde0c2e5b9e10f) (@materializer)
* [ ] [`448db5f3c` release: bump to version v0.55.0](https://github.com/MaterializeInc/materialize/commit/448db5f3c35b8857133fd7ebc56587ce73d7dce0) (@umanwizard)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#19106 Remove absolute path for certificate authorities in docs ](https://github.com/MaterializeInc/materialize/pull/19106) (@SangJunBak)
* [ ] [#18666 MIR type checking](https://github.com/MaterializeInc/materialize/pull/18666) (@mgree)
* [ ] [#19236 sql: Improve ergonomics of setting current schema](https://github.com/MaterializeInc/materialize/pull/19236) (@jkosh44)
* [ ] [#19266 limits test: Allow one more connection](https://github.com/MaterializeInc/materialize/pull/19266) (@def-)
* [ ] [#19262 release: bump to version v0.55.0-dev](https://github.com/MaterializeInc/materialize/pull/19262) (@jkosh44)
* [ ] [#19258 fix cloudtest nightlies with new system param bootstrap logic](https://github.com/MaterializeInc/materialize/pull/19258) (@guswynn)
* [ ] [#19255 cluster test: Make test-mv-source-sink deterministic](https://github.com/MaterializeInc/materialize/pull/19255) (@def-)
* [ ] [#19274 sqlsmith ci: Print all queries for panic](https://github.com/MaterializeInc/materialize/pull/19274) (@def-)
* [ ] [#19278 testdrive: Fortify ubscribe-output.td (take #2)](https://github.com/MaterializeInc/materialize/pull/19278) (@philip-stoev)
* [ ] [#19282 zippy: Restart CRDB on failure](https://github.com/MaterializeInc/materialize/pull/19282) (@philip-stoev)
* [ ] [#19284 upgrade-matrix: Do not skip any Mz versions when upgrading](https://github.com/MaterializeInc/materialize/pull/19284) (@philip-stoev)
* [ ] [#17662 ci: Use SIZE '4-X' cluster for sources](https://github.com/MaterializeInc/materialize/pull/17662) (@philip-stoev)
* [ ] [#19280 docs: Fix atan function entry](https://github.com/MaterializeInc/materialize/pull/19280) (@nrainer-materialize)
* [ ] [#19286 cloudtest: Fortify invocations of kill via kubectl](https://github.com/MaterializeInc/materialize/pull/19286) (@philip-stoev)
* [ ] [#19285 Fix locality of join key references in the typechecker](https://github.com/MaterializeInc/materialize/pull/19285) (@ggevay)
* [ ] [#19281 ci: linting: only print compacted diff, fix python-specific command assignment](https://github.com/MaterializeInc/materialize/pull/19281) (@nrainer-materialize)
* [ ] [#19288 Don't push literal errors past Negate](https://github.com/MaterializeInc/materialize/pull/19288) (@ggevay)
* [ ] [#19177 docs/developer: iterate on design doc process](https://github.com/MaterializeInc/materialize/pull/19177) (@aljoscha)
* [ ] [#19237 Cryptography](https://github.com/MaterializeInc/materialize/pull/19237) (@matthewarthur)
* [ ] [#19289 sqlsmith ci: fix python error](https://github.com/MaterializeInc/materialize/pull/19289) (@def-)
* [ ] [#19269 storage: bring back StorageController::drop_replica](https://github.com/MaterializeInc/materialize/pull/19269) (@guswynn)
* [ ] [#19211 sql: Add support for REASSIGN OWNED statement](https://github.com/MaterializeInc/materialize/pull/19211) (@jkosh44)
* [ ] [#19291 frontegg-client: implements the remove fn + list roles + missing TODOs](https://github.com/MaterializeInc/materialize/pull/19291) (@joacoc)
* [ ] [#19296 ci: Remove build from release qualification pipeline](https://github.com/MaterializeInc/materialize/pull/19296) (@def-)
* [ ] [#19300 Update mz_internal.mz_cluster_replica_history](https://github.com/MaterializeInc/materialize/pull/19300) (@umanwizard)
* [ ] [#19305 ci: Fix python error when junit report upload failed](https://github.com/MaterializeInc/materialize/pull/19305) (@def-)
* [ ] [#19307 ci: Fix conditional for skipping coverage](https://github.com/MaterializeInc/materialize/pull/19307) (@def-)
* [ ] [#19303 ci: Run docker inspect](https://github.com/MaterializeInc/materialize/pull/19303) (@def-)
* [ ] [#19308 misc: Bump CRDB version to v23.1.1](https://github.com/MaterializeInc/materialize/pull/19308) (@def-)
* [ ] [#15719 sql: resolve function names as all other objects](https://github.com/MaterializeInc/materialize/pull/15719) (@sploiselle)
* [ ] [#19233 Update docs to add new columns to `mz_source_statistics`](https://github.com/MaterializeInc/materialize/pull/19233) (@moulimukherjee)
* [ ] [#19188 adapter: Remove old migrations](https://github.com/MaterializeInc/materialize/pull/19188) (@ParkMyCar)
* [ ] [#19176 storage: add baseline RocksDB tune for the upsert usecase](https://github.com/MaterializeInc/materialize/pull/19176) (@guswynn)
* [ ] [#19312 ci: protobuf linting: rework excludes, add comment](https://github.com/MaterializeInc/materialize/pull/19312) (@nrainer-materialize)
* [ ] [#19302 adapter: Enforce max connections at pgwire](https://github.com/MaterializeInc/materialize/pull/19302) (@andrewrodriguez-m)
* [ ] [#19313 rbac: Give mz_introspection role more privileges](https://github.com/MaterializeInc/materialize/pull/19313) (@jkosh44)
* [ ] [#19321 upgrade-matrix: Fix failure with 4-1 default storage size on v0.40.0](https://github.com/MaterializeInc/materialize/pull/19321) (@def-)
* [ ] [#19323 ci: Add stack overflow to the list of errors extracted from the logs](https://github.com/MaterializeInc/materialize/pull/19323) (@philip-stoev)
* [ ] [#19326 Clearer environmentd startup failures](https://github.com/MaterializeInc/materialize/pull/19326) (@def-)
* [ ] [#19330 mzcompose: Allow Mzcompose to start containers with 'latest' tag](https://github.com/MaterializeInc/materialize/pull/19330) (@philip-stoev)
* [ ] [#19316 adapter: correctly terminate all failed Commands](https://github.com/MaterializeInc/materialize/pull/19316) (@ParkMyCar)
* [ ] [#19329 Update RocksDB version](https://github.com/MaterializeInc/materialize/pull/19329) (@ggevay)
* [ ] [#19333 persist: fix bucket ranges on pubsub latency histogram](https://github.com/MaterializeInc/materialize/pull/19333) (@pH14)
* [ ] [#19319 storage: delete single-worker persist_sink](https://github.com/MaterializeInc/materialize/pull/19319) (@guswynn)
* [ ] [#19315 adapter: Cancel `insert .. select`](https://github.com/MaterializeInc/materialize/pull/19315) (@andrewrodriguez-m)
* [ ] [#19208 stash: JSON to Proto migration](https://github.com/MaterializeInc/materialize/pull/19208) (@ParkMyCar)
* [ ] [#19320 sql: consolidate vars Option implementations](https://github.com/MaterializeInc/materialize/pull/19320) (@guswynn)
* [ ] [#19351 sql: refactor RocksDB tuning enum flags](https://github.com/MaterializeInc/materialize/pull/19351) (@sploiselle)
* [ ] [#19325 mzcompose: Principled handling of lists of prior versions](https://github.com/MaterializeInc/materialize/pull/19325) (@philip-stoev)
* [ ] [#19244 Re-order imports](https://github.com/MaterializeInc/materialize/pull/19244) (@teskje)
* [ ] [#19324 ci: Enable various feature flags in CI](https://github.com/MaterializeInc/materialize/pull/19324) (@philip-stoev)
* [ ] [#19356 mzcompose: Allow Mzcompose to start containers with 'devel' or 'unsta…](https://github.com/MaterializeInc/materialize/pull/19356) (@philip-stoev)
* [ ] [#19354 mzcompose: Update Redpanda to v23.1.9](https://github.com/MaterializeInc/materialize/pull/19354) (@BenPope)
* [ ] [#19355 doc/user: polish release notes for v0.54](https://github.com/MaterializeInc/materialize/pull/19355) (@morsapaes)
* [ ] [#19345 persist: shard metrics for batch counts + blob gets and sets](https://github.com/MaterializeInc/materialize/pull/19345) (@pH14)
* [ ] [#19346 stash: Create batches also based on number of args](https://github.com/MaterializeInc/materialize/pull/19346) (@ParkMyCar)
* [ ] [#19347 persist: set tcp user timeout for CRDB connections](https://github.com/MaterializeInc/materialize/pull/19347) (@pH14)
* [ ] [#19299 environmentd: add error structure to http/ws](https://github.com/MaterializeInc/materialize/pull/19299) (@mjibson)
* [ ] [#19293 doc: Update RBAC warning](https://github.com/MaterializeInc/materialize/pull/19293) (@jkosh44)
* [ ] [#19265 [persist] Clean up some disused filter-pushdown code ](https://github.com/MaterializeInc/materialize/pull/19265) (@bkirwi)
* [ ] [#19365 persist: metrics for watch vs sleep resolving next_listen_batch](https://github.com/MaterializeInc/materialize/pull/19365) (@danhhz)
* [ ] [#19366 [persist] Fix a copy/paste error on boolean stats](https://github.com/MaterializeInc/materialize/pull/19366) (@bkirwi)
* [ ] [#19361 adapter: Enforce max connections for http and websocket interfaces](https://github.com/MaterializeInc/materialize/pull/19361) (@andrewrodriguez-m)
* [ ] [#19364 storage: dont allow other sources/sinks to be scheduled on linked clusters](https://github.com/MaterializeInc/materialize/pull/19364) (@guswynn)
* [ ] [#19342 cloud-api: enable Arc in the admin client](https://github.com/MaterializeInc/materialize/pull/19342) (@joacoc)
* [ ] [#19370 ci: Bump upgrade-matrix timeout to 180 min](https://github.com/MaterializeInc/materialize/pull/19370) (@def-)
* [ ] [#19120 sql: remove unsafe mode](https://github.com/MaterializeInc/materialize/pull/19120) (@sploiselle)
* [ ] [#19357 WMR ThresholdElision](https://github.com/MaterializeInc/materialize/pull/19357) (@ggevay)
* [ ] [#19378 [persist] Handle MFP's strict expression evaluation](https://github.com/MaterializeInc/materialize/pull/19378) (@bkirwi)
* [ ] [`02394d9fc` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/02394d9fc61b43f46dc42fe7bdea4626d2a928ab) (@materializer)
* [ ] [`4eddc5b7d` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/4eddc5b7d0344a95dd9614e08d7e7ff57d04c51b) (@materializer)
* [ ] [`1174e7050` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/1174e7050f18ec4a316a231590b51a862728d889) (@materializer)
* [ ] [`52e5ec46e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/52e5ec46e2c995ff00175a2746657888275396c4) (@materializer)
* [ ] [`e273aabc8` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e273aabc880f5a9dca6af6d6edc79f7f7e445e7a) (@materializer)
* [ ] [`9559fab7e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/9559fab7e33814d6f1f8b5a76cc7a3d4cbb58663) (@materializer)
* [ ] [`54764be30` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/54764be3056aff757583647f39bde0c2e5b9e10f) (@materializer)
* [ ] [`448db5f3c` release: bump to version v0.55.0](https://github.com/MaterializeInc/materialize/commit/448db5f3c35b8857133fd7ebc56587ce73d7dce0) (@umanwizard)

**Comment by umanwizard** [comment]
all non-@umanwizard commits lgtm

**Comment by danhhz** [comment]
brennan's unreviewed commit lgtm
