### ISSUE TITLE
[Evergreen] Support SQL clients, tools, and integrations

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#19490]
More "Now" tasks coming soon...

```[tasklist]
### Now
- [ ] https://github.com/MaterializeInc/materialize/issues/9720
- [ ] https://github.com/MaterializeInc/materialize/issues/17216
```
```[tasklist]
### Next
- [ ] https://github.com/MaterializeInc/materialize/issues/9721
- [ ] https://github.com/MaterializeInc/materialize/issues/9694
- [ ] https://github.com/MaterializeInc/product/issues/208
```

```[tasklist]
### Later
```
