### ISSUE TITLE
release: v0.56.0 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#19529]
The following PRs in [`v0.56.0`](https://github.com/MaterializeInc/materialize/tree/v0.56.0) require review:
* [ ] [#19387 release: bump to version v0.56.0-dev](https://github.com/MaterializeInc/materialize/pull/19387) (@umanwizard)
* [ ] [#19472 doc/user: polish release notes for v0.55](https://github.com/MaterializeInc/materialize/pull/19472) (@morsapaes)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`7d6da549b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7d6da549b2cace19f57ec9cc455a136cc483c3b0) (@materializer)
* [ ] [`e16361631` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e16361631bf59f6619e5e55c2e9b914445994c96) (@materializer)
* [ ] [`502956181` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5029561817925f9ee40212b357ac74186d31943f) (@materializer)
* [ ] [`dcbb1c8c9` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/dcbb1c8c9894242f72afb890e56869cfef4bec82) (@materializer)
* [ ] [`a5b342f9b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a5b342f9b43dc5447274bbb128bdf1020262bd1d) (@materializer)
* [ ] [`5972ea96e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5972ea96e1187b6a4ec7948f7240ed159d504b42) (@materializer)
* [ ] [`facae42f0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/facae42f06b0ff6fb912d72a894b2baba5f8abbf) (@materializer)
* [ ] [`9c33edb24` release: bump to version v0.56.0](https://github.com/MaterializeInc/materialize/commit/9c33edb2471a67c11c4088547f62a93b92ba5043) (@guswynn)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#19095 docs: Fix revoke privileges example](https://github.com/MaterializeInc/materialize/pull/19095) (@dehume)
* [ ] [#19369 coverage: git fetch first & ignore cargo-test profraw files](https://github.com/MaterializeInc/materialize/pull/19369) (@def-)
* [ ] [#19217 testdrive: Inline version & platform-checks: Use testdrive inline versioning](https://github.com/MaterializeInc/materialize/pull/19217) (@def-)
* [ ] [#19387 release: bump to version v0.56.0-dev](https://github.com/MaterializeInc/materialize/pull/19387) (@umanwizard)
* [ ] [#19392 Fix nightly tests after unsafe mode removal](https://github.com/MaterializeInc/materialize/pull/19392) (@def-)
* [ ] [#19397 Increase timeout for proptest_stash_migrate_json_to_proto](https://github.com/MaterializeInc/materialize/pull/19397) (@def-)
* [ ] [#19389 CI: Immediate output from SQLancer](https://github.com/MaterializeInc/materialize/pull/19389) (@def-)
* [ ] [#19391 ci: Add 10 min SQLancer runs to normal tests](https://github.com/MaterializeInc/materialize/pull/19391) (@def-)
* [ ] [#19341 frontegg-client: client is now able to return claims + role id type](https://github.com/MaterializeInc/materialize/pull/19341) (@joacoc)
* [ ] [#19404 Fix merge skew in alter_table.py](https://github.com/MaterializeInc/materialize/pull/19404) (@def-)
* [ ] [#19287 Rework `relation_cse` so it is `recursion_safe`](https://github.com/MaterializeInc/materialize/pull/19287) (@aalexandrov)
* [ ] [#19390 storage: allow WITH(DISK) even when enable_create_source_denylist_with_options is off](https://github.com/MaterializeInc/materialize/pull/19390) (@guswynn)
* [ ] [#19415 fix test persist s3 bucket region](https://github.com/MaterializeInc/materialize/pull/19415) (@guswynn)
* [ ] [#19408 pg_catalog: Add missing columns to pg_roles](https://github.com/MaterializeInc/materialize/pull/19408) (@ParkMyCar)
* [ ] [#19407 pg_catalog: Add pg_tablespace table](https://github.com/MaterializeInc/materialize/pull/19407) (@ParkMyCar)
* [ ] [#19428 ci: Fix SQLancer timeouts](https://github.com/MaterializeInc/materialize/pull/19428) (@def-)
* [ ] [#19429 persist: regression test for #19366](https://github.com/MaterializeInc/materialize/pull/19429) (@danhhz)
* [ ] [#19411 slt: Enable table keys for sqlite tests](https://github.com/MaterializeInc/materialize/pull/19411) (@def-)
* [ ] [#19426 qa: increase test coverage of some system vars](https://github.com/MaterializeInc/materialize/pull/19426) (@guswynn)
* [ ] [#19427 sql: Prevent modifying privileges of system users](https://github.com/MaterializeInc/materialize/pull/19427) (@jkosh44)
* [ ] [#19430 ci: product-limits WhereConditionAnd with fewer conditions](https://github.com/MaterializeInc/materialize/pull/19430) (@def-)
* [ ] [#19422 cloud-api: fixes region and environments requests](https://github.com/MaterializeInc/materialize/pull/19422) (@joacoc)
* [ ] [#19421 frontegg-client: enables authentication using email and password](https://github.com/MaterializeInc/materialize/pull/19421) (@joacoc)
* [ ] [#19403 Make `Demand` WMR-safe](https://github.com/MaterializeInc/materialize/pull/19403) (@ggevay)
* [ ] [#19186 compute: better-fueled linear join](https://github.com/MaterializeInc/materialize/pull/19186) (@teskje)
* [ ] [#19424 pg_catalog: Add pg_trigger table](https://github.com/MaterializeInc/materialize/pull/19424) (@ParkMyCar)
* [ ] [#19379 persist: add shard metric for rollup count](https://github.com/MaterializeInc/materialize/pull/19379) (@pH14)
* [ ] [#19417 persist: split out diff unsuccessfully applied metric](https://github.com/MaterializeInc/materialize/pull/19417) (@pH14)
* [ ] [#19440 ci: Make cargo-test faster](https://github.com/MaterializeInc/materialize/pull/19440) (@def-)
* [ ] [#19331 ci: Enable rbac checks by default](https://github.com/MaterializeInc/materialize/pull/19331) (@def-)
* [ ] [#19239 storage: multi-worker postgres source refactor](https://github.com/MaterializeInc/materialize/pull/19239) (@petrosagg)
* [ ] [#19425 persist: proptest coverage for State proto roundtrip](https://github.com/MaterializeInc/materialize/pull/19425) (@danhhz)
* [ ] [#19446 adapter: Fix flaky test_max_connections](https://github.com/MaterializeInc/materialize/pull/19446) (@andrewrodriguez-m)
* [ ] [#19447 adapter: rename Command::{Describe => Prepare}](https://github.com/MaterializeInc/materialize/pull/19447) (@benesch)
* [ ] [#19432 persist: add Serialize impl for persist State](https://github.com/MaterializeInc/materialize/pull/19432) (@danhhz)
* [ ] [#19444 Rename `sql` field in `PreparedStatement` to `stmt`](https://github.com/MaterializeInc/materialize/pull/19444) (@umanwizard)
* [ ] [#19353 deps: remove personal forks/branches, and add a note about why](https://github.com/MaterializeInc/materialize/pull/19353) (@benesch)
* [ ] [#19268 storage: bounded memory upsert snapshot](https://github.com/MaterializeInc/materialize/pull/19268) (@guswynn)
* [ ] [#19133 storage: maybe prevent panic on acquiring sink handle](https://github.com/MaterializeInc/materialize/pull/19133) (@sploiselle)
* [ ] [#19013 Test generator for output consistency checks (V1)](https://github.com/MaterializeInc/materialize/pull/19013) (@nrainer-materialize)
* [ ] [#19457 tests: Fix session.td for cloudtest](https://github.com/MaterializeInc/materialize/pull/19457) (@def-)
* [ ] [#19464 Handle float over/underflows in pow, exp](https://github.com/MaterializeInc/materialize/pull/19464) (@tokenrove)
* [ ] [#19386 storage: add a marketing based load generator](https://github.com/MaterializeInc/materialize/pull/19386) (@sjwiesman)
* [ ] [#19462 Add `checked_recur` to `JoinImplementation`](https://github.com/MaterializeInc/materialize/pull/19462) (@ggevay)
* [ ] [#19372 Exploration of hashing approaches in `consolidate_named_if`](https://github.com/MaterializeInc/materialize/pull/19372) (@vmarcos)
* [ ] [#19474 persist: fix pushdown metrics](https://github.com/MaterializeInc/materialize/pull/19474) (@danhhz)
* [ ] [#19472 doc/user: polish release notes for v0.55](https://github.com/MaterializeInc/materialize/pull/19472) (@morsapaes)
* [ ] [#19465 Remove support to maintain the threshold based on retractions](https://github.com/MaterializeInc/materialize/pull/19465) (@antiguru)
* [ ] [#19466 Remove ReducePlan::DistinctNegated](https://github.com/MaterializeInc/materialize/pull/19466) (@antiguru)
* [ ] [#19478 remove an accidental debug line](https://github.com/MaterializeInc/materialize/pull/19478) (@guswynn)
* [ ] [#19420 sql: refactor session vars](https://github.com/MaterializeInc/materialize/pull/19420) (@sploiselle)
* [ ] [#19480 build: Remove unused const_format dependency](https://github.com/MaterializeInc/materialize/pull/19480) (@def-)
* [ ] [#19461 Collapse `from_mir` and `from_mir_inner`](https://github.com/MaterializeInc/materialize/pull/19461) (@ggevay)
* [ ] [#19491 Explicitly enable WMR in all such slts that involve WMR](https://github.com/MaterializeInc/materialize/pull/19491) (@ggevay)
* [ ] [#19497 sqlsmith: Verify that any queries were actually run](https://github.com/MaterializeInc/materialize/pull/19497) (@def-)
* [ ] [#19468 make new postgres-util code properly use the crate features](https://github.com/MaterializeInc/materialize/pull/19468) (@doy-materialize)
* [ ] [#19481 ci: Change Protobuf linting config from FILE to WIRE](https://github.com/MaterializeInc/materialize/pull/19481) (@nrainer-materialize)
* [ ] [#19488 Update CTE docs on known limitations](https://github.com/MaterializeInc/materialize/pull/19488) (@ggevay)
* [ ] [#19493 adapter: Refactor ConnectionId to be an owned handle](https://github.com/MaterializeInc/materialize/pull/19493) (@ParkMyCar)
* [ ] [#18894 persist: state pubsub design doc](https://github.com/MaterializeInc/materialize/pull/18894) (@pH14)
* [ ] [#19507 github: Update pull request template](https://github.com/MaterializeInc/materialize/pull/19507) (@jkosh44)
* [ ] [#19499 ci: Make SLT files work standalone](https://github.com/MaterializeInc/materialize/pull/19499) (@def-)
* [ ] [#19494 Deduplicate keys in `keys_with_input_keys`](https://github.com/MaterializeInc/materialize/pull/19494) (@ggevay)
* [ ] [#19495 ci: Enable persist_stats_audit_percent=100](https://github.com/MaterializeInc/materialize/pull/19495) (@def-)
* [ ] [#19502 adapter: remove obsolete `last_known_time_seconds` metric](https://github.com/MaterializeInc/materialize/pull/19502) (@aalexandrov)
* [ ] [#19515 platform-checks: Avoid setting the same settings after each upgrade](https://github.com/MaterializeInc/materialize/pull/19515) (@def-)
* [ ] [#19521 cargo-test: Don't run with more CPU cores](https://github.com/MaterializeInc/materialize/pull/19521) (@def-)
* [ ] [#19522 Ignore `cluster-client` in `buf` lint](https://github.com/MaterializeInc/materialize/pull/19522) (@vmarcos)
* [ ] [#19448 [persist/expr] Fallback and optimize for worst-case interpreter path](https://github.com/MaterializeInc/materialize/pull/19448) (@bkirwi)
* [ ] [#19508 [persist/expr] Enhanced explain filter](https://github.com/MaterializeInc/materialize/pull/19508) (@bkirwi)
* [ ] [#19505 test: Fix flaky test test_coord_startup_blocking](https://github.com/MaterializeInc/materialize/pull/19505) (@jkosh44)
* [ ] [#19503 sql: Implement has_table_privilege](https://github.com/MaterializeInc/materialize/pull/19503) (@jkosh44)
* [ ] [#19512 adapter: session ID in mz_subscriptions](https://github.com/MaterializeInc/materialize/pull/19512) (@teskje)
* [ ] [#19524 Resolve merge skew between some interpreter PRs](https://github.com/MaterializeInc/materialize/pull/19524) (@bkirwi)
* [ ] [#19526 Revert multi worker pg](https://github.com/MaterializeInc/materialize/pull/19526) (@petrosagg)
* [ ] [`7d6da549b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/7d6da549b2cace19f57ec9cc455a136cc483c3b0) (@materializer)
* [ ] [`e16361631` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/e16361631bf59f6619e5e55c2e9b914445994c96) (@materializer)
* [ ] [`502956181` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5029561817925f9ee40212b357ac74186d31943f) (@materializer)
* [ ] [`dcbb1c8c9` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/dcbb1c8c9894242f72afb890e56869cfef4bec82) (@materializer)
* [ ] [`a5b342f9b` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/a5b342f9b43dc5447274bbb128bdf1020262bd1d) (@materializer)
* [ ] [`5972ea96e` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/5972ea96e1187b6a4ec7948f7240ed159d504b42) (@materializer)
* [ ] [`facae42f0` LICENSE: update change date](https://github.com/MaterializeInc/materialize/commit/facae42f06b0ff6fb912d72a894b2baba5f8abbf) (@materializer)
* [ ] [`9c33edb24` release: bump to version v0.56.0](https://github.com/MaterializeInc/materialize/commit/9c33edb2471a67c11c4088547f62a93b92ba5043) (@guswynn)

**Comment by benesch** [comment]
All unreviewed PRs and commits LGTM.
