### ISSUE TITLE
[Epic] Blue/Green Workflow for SELECT Consumers

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#19748]
## Product Outcome
* Users can perform basic SWAPs using cluster and schema renames.
* Users can SWAP production views, MVs, and indexes for SELECT use cases.

## Documentation
[Spec](https://www.notion.so/materialize/Blue-Green-Deployments-bc479643d5a34446be19f389dc0d4602)
[Workflow](https://www.figma.com/file/COaCt8iyYHRA0wrmeP3nTH/Blue%2FGreen?type=whiteboard&node-id=57-315&t=uxF42H3IL478ZWKQ-4).

## Discovery
- This is a clear problem for users in or approaching production. 
- Initial discovery will be on the technical solution.
- FE and Dev Ex to test feature against dbt connector.
- Identify several users to build this with us against their actual and desired workflows.

## Work items

```[tasklist]
### v0 Renaming and SWAP
- [ ] https://github.com/MaterializeInc/materialize/issues/22250
- [ ] https://github.com/MaterializeInc/materialize/issues/22554
- [ ] https://github.com/MaterializeInc/materialize/issues/12972
- [ ] https://github.com/MaterializeInc/materialize/issues/22854
```
```[tasklist]
### Documenting Workflows
- [ ] https://github.com/MaterializeInc/materialize/pull/23494
- [ ] https://github.com/MaterializeInc/materialize/pull/24142
- [ ] https://github.com/MaterializeInc/materialize/issues/24196
- [ ] https://github.com/MaterializeInc/materialize/pull/25121#issuecomment-1936132868
- [ ] Add a view for readiness check?
- [ ] Include source and sink checks to readiness queries: https://materializeinc.slack.com/archives/C05SLRXKNGN/p1706780532813009?thread_ts=1706729350.801729&cid=C05SLRXKNGN
```

```[tasklist]
### dbt Support
- [ ] https://github.com/MaterializeInc/materialize/issues/24186
```

```[tasklist]
### Nice to Have
- [ ] https://github.com/MaterializeInc/materialize/issues/3680
- [ ] https://github.com/MaterializeInc/materialize/issues/5680
- [ ] https://github.com/MaterializeInc/materialize/issues/24690
- [ ] https://github.com/MaterializeInc/materialize/issues/24689
```

## Related
- https://github.com/MaterializeInc/materialize/issues/17417

## Decision log

* **18 September 2023.** First milestone: ALTER SWAP for schemas and clusters, support for ALTER ... RENAME  in transactions. Proxy rehydration checks.

**Comment by ggnall** [comment]
Going to keep us honest and name this Epic to how we are approaching this phase. We definitely need tighter milestones to round out our story.

**Comment by ggnall** [comment]
Transferring to Integrations team. Remaining docs and dbt work added to tasklists.

**Comment by morsapaes** [comment]
The remaining work has been shipped, so closing the epic. There's some follow-up work we'll need to figure out over the next quarter(s), in particular blue/green deployments for sinks (#26350).
