### ISSUE TITLE
[Epic] WebSocket API improvements for in-console SQL editor

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#19771]
### Outcome

Improve the WebSocket API to support the MVP of the in-console SQL editor (https://github.com/MaterializeInc/console/issues/221).

This will be a subset of promoting the WS API to GA (#18224).

### Must haves

- [x] https://github.com/MaterializeInc/materialize/pull/19757#pullrequestreview-1466627003
- [x] https://github.com/MaterializeInc/materialize/issues/18503
- [x] https://github.com/MaterializeInc/materialize/issues/19772
- [x] https://github.com/MaterializeInc/materialize/issues/19773
- [x] https://github.com/MaterializeInc/materialize/issues/20262
- [x] https://github.com/MaterializeInc/materialize/issues/20284

### Up for debate

- [ ] https://github.com/MaterializeInc/materialize/issues/19774
- [x] https://github.com/MaterializeInc/console/issues/284 
  Current known work to support the above is #18503, but tracking here in case more work items arise.

### Not haves

* #17934

  The current behavior is actually _simpler_ for everyone involved—`environmentd` does not periodically re-check the authentication of the session, and so the console does not need to periodically send over new credentials.

cc @mjibson @arusahni

**Comment by ggnall** [comment]
Added https://github.com/MaterializeInc/materialize/issues/20262

**Comment by mjibson** [comment]
All must-haves are done. We can probably close this now.

**Comment by ggnall** [comment]
Nice! @arusahni any outstanding shell features blocked here?

**Comment by arusahni** [comment]
@ggnall nope, I agree this can be closed.
