### ISSUE TITLE
Improve support for TablePlus

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#19891]
### Feature request

[TablePlus](https://tableplus.com/) is a common database GUI for PostgreSQL. Although Materialize integrates out-of-the-box via the PostgreSQL connection, there are a few papercuts we can improve.

- [ ] Add `oid` to `pg_am`
- [ ] Support `regexp_replace` (https://github.com/MaterializeInc/materialize/issues/3339)
- [ ] Add `col_description()` shim to `pg_catalog` (linking to #1212, so we remember to tweak this and `obj_description()` when it lands)
- [ ] Add `triggers` shim to `information_schema`
- [ ] Add `pg_stat_activity` shim to `pg_catalog` (this is used for the query logging functionality, so it might be enabled via #19381)

See [this page](https://www.notion.so/materialize/TablePlus-05918279ecdc48b9b40cc4409d62ef2e?pvs=4) more details.

**Comment by benesch** [comment]
> * Add `pg_stat_activity` shim to `pg_catalog` (this is used for the query logging functionality, so it might be enabled via [Add lightweight design doc for statement logging #19381](https://github.com/MaterializeInc/materialize/pull/19381))

Hmm, it's a pretty grim attempt at a query log! It only tells you the currently-executing query on each connection. I think of `pg_stat_activity` as much more akin to `mz_sessions`. Unless I'm misunderstanding something!

**Comment by morsapaes** [comment]
s/logging/monitoring 😴 Wouldn't we need the statement logging work to expose the current query running in a session? The main purpose of `pg_stat_activity` in TablePlus is to support query cancellation (see the [documentation](https://docs.tableplus.com/query-editor/untitled#cancel-queries)), which is anyways also blocked by #13130.

**Comment by benesch** [comment]
> s/logging/monitoring 😴

Ah ok, checks out for me now.

> Wouldn't we need the statement logging work to expose the current query running in a session, though?

Yes!

> The main purpose of `pg_stat_activity` in TablePlus is to support query cancellation (see the [documentation](https://docs.tableplus.com/query-editor/untitled#cancel-queries)), which is anyways also blocked by #13130.

Hey @mjibson here's a tool that our proposal for #19773 would unlock!

**Comment by benesch** [comment]
I looked into supporting `pg_stat_activity`. It's hard, because `pg_stat_activity` shows you the most recently executing/executed query for each connection. Because of how our system tables work, we'd need to actually turn each query into a persist write to make this work today, which is grim. 

And, for TablePlus, we can't just stub out the `query` field, because it runs this query to filter to _only_ non-idle connections whose query is not the query listing `pg_stat_activity`:

```
select * from pg_stat_activity where state!='idle' and query not ilike'%pg_stat_activity%' order by query_start desc;
```

Plus, the whole "connection list" UI is meant to show you the text of all queries currently executing on the system. I just don't see a good way to stub this out today from `mz_sessions`.

Maybe once https://github.com/MaterializeInc/materialize/pull/20862 lands, we'll be able to make `pg_stat_activity` a view over the query executions table that shows all not-yet-finished queries? That's a bit lossy, as that table lags behind real time by a few seconds, but likely better than nothing!

**Comment by morsapaes** [comment]
Noting here that `pg_stat_activity` is also a blocker for query cancellation in Looker (see #9531).
