### ISSUE TITLE
[Epic] Fix inconsistencies in `CREATE SOURCE` and `CREATE SINK` syntaxes

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20135]
## Background

The `CREATE SOURCE` and `CREATE SINK` statements have historical baggage that we would like to clean up:

* They predate the option syntax standardization project from mid last year, where we standardized how options for `CREATE CONNECTION`, `CREATE CLUSTER`, and `CREATE CLUSTER REPLICA` work. Most source/sink options use bespoke syntax.
* We generalized too soon. Many source and sink options that are specific to Kafka are top-level options that need to be handled by all source types (PostgreSQL, soon webhooks), rather than being properly associated with just Kafka sources.

## Design considerations

- [ ] Should `FORMAT` clauses be type-specific? E.g., Kafka supports a `KEY FORMAT` and a `VALUE FORMAT`, while webhook sources will support a `BODY FORMAT`. Attempting to have one top-level `FORMAT` clause was a mistake.

- [ ] Should `INCLUDE` clauses, e.g. `INCLUDE HEADER`, be type specific? (Probably.)

- [ ] Should `ENVELOPE` stay at the top-level?? (Probably.)

- [ ] https://github.com/MaterializeInc/materialize/issues/19143

    Just the part of aligning the `CREATE SINK ... KEY NOT ENFORCED` syntax with `SUBSCRIBE ... ENVELOPE UPSERT` syntax.

- [ ] https://github.com/MaterializeInc/materialize/issues/15272

## Work items

- [ ] Write design document addressing the above considerations
- [ ] TODO

cc @sploiselle
