### ISSUE TITLE
[webhook] Validation of requests

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#20211]
### Feature request

A `WEBHOOK` source will expose a publicly accessible endpoint that theoretically _anyone_ can push data to. In practice it'll be external applications, e.g. Segment, that are pushing data. To ensure that the provided request is authentic, most applications provide some signature that you can validate via a shared secret.

For example, in the headers of a request there would a `signature`, which is generally an [HMAC](https://en.wikipedia.org/wiki/HMAC) of the request body. To validate the request is authentic, you HMAC the request with a shared key and assert that it matches the provided value in the `signature` header. See the [design doc](https://github.com/ParkMyCar/materialize/blob/design/webhook_source/doc/developer/design/20230615_webhook_source.md#request-validation) for more details.

This issues covers all of the work related to supporting the validation of requests for `WEBHOOK` sources.
```[tasklist]
### Tasks
- [ ] Update the SQL parser to support a `VALIDATE USING` clause
- [x] Add `hmac(algo, data)` function to Materialize
- [ ] Run request validation when receving a webhook request
```
