### ISSUE TITLE
[webhook] LaunchDarkly Flag

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#20218]
As part of #20210 we added a LaunchDarkly flag `enable_webhook_sources`, this task is for tracking the successful rollout and cleanup of that flag.
```[tasklist]
### Tasks
- [x] Rollout the `enable_webhook_sources` flag in LaunchDarkly
- [ ] Cleanup the `enable_webhook_sources` flag in code after successful release
- [ ] Delete the `enable_webhook_sources` flag from LaunchDarkly, after release with code cleanup goes out
```
