### ISSUE TITLE
Finalize `FORMAT JSON`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20387]
## Background

We recently shipped support for `CREATE SOURCE ... FORMAT JSON`. This is a small quality of life improvement for JSON-formatted Kafka sources. This diff explains it better than words:

![image](https://github.com/MaterializeInc/materialize/assets/882976/566cad5b-611c-4887-997e-e97deec4eb83)

## Work items

- [x] Announce in #ohship
- [x] Add to changelog ([www #586](https://github.com/MaterializeInc/www/pull/586))
- [x] https://github.com/MaterializeInc/terraform-provider-materialize/pull/227
- [x] https://github.com/MaterializeInc/console/pull/469
- [x] https://github.com/MaterializeInc/materialize/pull/20388
- [x] Remove `enable_format_json` feature flag from LaunchDarkly once v0.60 ships (#20388)
