### ISSUE TITLE
Rename `mz_introspection` user to `mz_support`

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#20553]
The only use case for the `mz_introspection` user is for support to debug customer environments via teleport. As such, we should make it more clear what this user is for to reduce confusion, especially since we also have an `mz_introspection` cluster that is queried by users.

See conversation in https://materializeinc.slack.com/archives/C02FWJ94HME/p1689264753940949

## Work items
* [x] Add `mz_support` alias for `mz_introspection`
* [ ] https://github.com/MaterializeInc/cloud/issues/6918
* [ ] Remove the `mz_introspection` user

**Comment by benesch** [comment]
To do this without disrupting the cloud team, we should have a release where we support _both_ names, then update all the cloud tooling to use `mz_support` instead of `mz_introspection`, and _then_ remove the `mz_introspection` name.

**Comment by andrewrodriguez-m** [comment]
Dashboard for mz_introspection usage in prod: https://grafana.dev.materialize.com/d/bcc6c30a-8b6b-4c50-8f92-c81af3148a20/introspection-user?orgId=1 . Once it hits zero we can proceed

**Comment by benesch** [comment]
This is really cool! Is it expected that there are still so many
mz_introspection logins?

**Comment by andrewrodriguez-m** [comment]
From https://github.com/search?q=repo%3AMaterializeInc%2Fcloud%20mz_introspection&type=code, the sql_exporter looks the most guilty to me. @evanharmon were you looking into that or can I take it?

**Comment by evanharmon** [comment]
@andrewrodriguez-m Sorry for the late reply - I merged changes last Friday for that code area. Looks like the dashboard is now hitting zero. 🙏

**Comment by benesch** [comment]
What a beautiful graph! 🙇🏽 

<img width="852" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/a8eb1883-8a69-490b-b7e2-f72ba9f113e1">
