### ISSUE TITLE
`EXPLAIN <catalog item>` output should align with the catalog state

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#20652]
### Feature request

`EXPLAIN` variations that provide information for catalog items backed by a running dataflow should return the plan that produced that dataflow, not simulate what would happen if we were to re-create the dataflow with the current catalog state (this should be handled by the proposed `EXPLAIN CREATE MATERIALIZED VIEW` syntax in #18089).

More specifically, we want to be able to explain the following stages for an item identified by `$name`:

```sql
EXPLAIN OPTIMIZED PLAN FOR MATERIALIZED VIEW $name;
EXPLAIN PHYSICAL PLAN FOR MATERIALIZED VIEW $name;

EXPLAIN OPTIMIZED PLAN FOR INDEX $name;
EXPLAIN PHYSICAL PLAN FOR INDEX $name;
```

Design doc PR: #20941

### Tasks

- [x] Rework `EXPLAIN OPTIMIZED PLAN FOR MATERIALIZED VIEW` ([#21261](21261))
- [x] Rework `EXPLAIN PHYSICAL PLAN FOR MATERIALIZED VIEW` ([#21369](21369))
- [x] Deprecate `EXPLAIN VIEW` ([#21383](21383))
- [x] Support `EXPLAIN INDEX` ([#21488](21488))
- [x] Update docs ([#21529](21529))
