### ISSUE TITLE
persist: FY24 Q3 checklist

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#21200]
# Update: Q3 is closed! Moved tracking to https://github.com/MaterializeInc/materialize/issues/22470

- [prod] => stability/introspection
- [req] => requests from other teams/product for _new_ behavior
- [bug] => incorrect behavior

# Bugs
- [ ] [bug] #15937
- [ ] [bug] #17214
- [ ] [bug] #19841
- [ ] [bug] GC/Shard finalization follow-ups https://github.com/MaterializeInc/cloud/issues/6705 
- [ ] [bug] any needed follow-ups to https://github.com/MaterializeInc/materialize/issues/20287

# Now: FY24 Q3
- [ ] #21265
- [ ] [epic] Implement #18157
- [ ] [prod] Turn on CRDB changefeeds -> s3 for all prod environments
- [ ] [epic] Actually delete and cleanup data
  - [ ] #17292
  - [ ] #17322
  - [ ] #20222
- [ ] [req] #16783
  - Blocking [tuning the initial value of backpressure](https://github.com/MaterializeInc/materialize/issues/15974#issuecomment-1428012662)

# Next: FY24 Q4 (epics first, otherwise not ordered)

# Later: FY25 Q1+ (epics first, otherwise not ordered)
- [epic] #16858
- [epic] #19322
- [epic] write Schema-ified data blobs
- [epic] #16607
  - Break this down into chunks with incremental benefits
  - Serialize the internals of Spine instead of the raw batches
  - Fix the since used in compaction #15850
  - Consolidate the _deserialized_ K, V so encoding migrations work
  - Resurrect #15709
  - #17698
- [epic] Throughput tuning
  - #15518
  - Update open_loop benchmark to stress sharded reads and writes
  - #18066
- [epic] #16625
- [epic] Indexed lookup
- [epic] #17492
- [epic] #13918
- [epic] Bounding state size (two-level lookup)
- [epic] Consensus in-line writes
- [req] #17206
- [req] https://github.com/MaterializeInc/materialize/issues/20618
- [pushdown] Wire up stats to a system var (and add extra budget for large parts)
- [prod] #17776
- [prod] #19225
- [prod] #19608
- [prod] #15209
  - Readers could either use ben's 🤯 idea or frank's "extreme" version
- [prod] Resurrect #13961
- [prod] Hook client auth for Consensus up in prod
- [prod] Petros's idea to have a sharded exchangeable description of assigned compaction work
- [prod] Aljoscha's idea to balance the compare_and_append work in persist_sink operator 3 instead of a fixed worker
- [prod] Proptest coverage of persist protos
  - #19425
  - Ditto for state diffs?
- [prod] #16699
- [prod] #12992
- [prod] #16652
  - Blocked on getting more experience debugging persist issues
  - Similarly, mental model of underlying costs for persist users
- [prod] dynamically resizable CRDB connection pool (allows throttling of individual envs / processes)
- [prod] prometheus histogram of batch part sizes
- [prod] faster fallback polling for state (use timestamp interval, poll fast after initial delay)
- Split mz_persist_client::internal into mz_persist
