### ISSUE TITLE
[epic] Fast select-limit queries for Persist-backed collections

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#21265]
One of the first things that many users do after loading a dataset is `SELECT * FROM data LIMIT 10` or similar, just to get a rough sense of what data is there and whether it has the shape they'd expect. This is a common pattern in part because most SQL databases make this query quite fast.

In Materialize, these queries are fast when the collection is indexed: simple "fast-path" queries against indexed collections just read the result out of memory, and can usually do work just proportional to the amount of data read. However, a query against an unindexed collection involves loading the entire collection from S3 and spinning up a dataflow to process it, only to throw away much of the result set.

While reading from Persist will always be a bit more expensive than reading from an in-memory index, we should be able to get times for simple queries like the above down to interactive speeds. This issue tracks that work.
```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/materialize/pull/21615
- [x] Bound concurrent fast-path peeks in environmentd
- [x] Bound the byte size for in-progress peeks, not just during finishing
- [x] Explore cancellation for fast-path peeks
- [x] Feature benchmark to prevent regresssing the fast-path performance
- [ ] https://github.com/MaterializeInc/materialize/issues/22042
- [x] Match the error semantics of non-Persist peeks
- [x] Distinguish between index/persist peeks in introspection tables
```
