### ISSUE TITLE
[Epic] Improve regexp support

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#21427]
## Product outcome

Improve Materialize's support for munging data with regular expressions.

## Details

We've had a few asks lately for additional support for regular expression functions. We also have several historical asks for regular expression functions. I figure it'll be a bit more efficient to bundle all this work together to minimize context switching.

## Work items

* [ ] https://github.com/MaterializeInc/materialize/issues/20533
* [ ] https://github.com/MaterializeInc/materialize/issues/7153
* [ ] https://github.com/MaterializeInc/materialize/issues/4714
* [ ] https://github.com/MaterializeInc/materialize/issues/21411
* [ ] https://github.com/MaterializeInc/materialize/issues/21426

## Search keywords

(To help out GitHub's issue search.)

* regex
* regexp
* regular expressions

**Comment by benesch** [comment]
@mjibson did I err by including https://github.com/MaterializeInc/materialize/issues/20533 in this bundle? It's pretty different work from just knocking out a few `regexp` functions.

**Comment by mjibson** [comment]
I'd keep that and also add https://github.com/MaterializeInc/materialize/issues/16464 which breaks ordering on `regexp_split_to_table`. 16464 is silent incorrectness. Both that and 20533 make regexes sometimes not work, and an epic seems like the correct place to decide that regexes should work.

**Comment by benesch** [comment]
> I'd keep that and also add #16464 which breaks ordering on `regexp_split_to_table`. 16464 is silent incorrectness. Both that and 20533 make regexes sometimes not work, and an epic seems like the correct place to decide that regexes should work.

Makes sense. Done.

**Comment by mjibson** [comment]
See #24559 which will fix the bugs here. After that adding regexp_like would close this!
