### ISSUE TITLE
Internal tables for optimization hints

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#21513]
The optimizer emits a notice (in EXPLAIN for now; [discussion is ongoing](https://materializeinc.slack.com/archives/CQM08AP9V/p1693388342390429) whether to show a notice in psql) when an index is too wide to use for a literal constraint (https://github.com/MaterializeInc/materialize/issues/20768). We will have several other similar notices soon (https://github.com/MaterializeInc/console/issues/549).

We should make this information available in built-in tables, so that the Web UI (or anyone else) can read it. There are several degrees of freedom that will influence the schema design:

1. Notices associated with a single item vs notices that have to be derived from the entire catalog state (e.g. because they want to look at the plans for all dataflow-backed catalog objects).
2. Notices associated with ad-hoc queries vs dataflow-backed catalog objects.

As @uce and @pH14 [noted](https://materializeinc.slack.com/archives/CQM08AP9V/p1693508962249579?thread_ts=1693388342.390429&cid=CQM08AP9V), we could also gather metrics based on these internal tables, and then we'd know how often each problem is happening, and for which users.

Edit: The metric gathering is partially done (without relying on the internal table). There is a Grafana dashboard  [here](https://grafana.dev.materialize.com/d/d286afce-f50f-4665-8f71-3b332620e0c7/gabor-sandbox?orgId=1&from=now-30d&to=now) for now. (Will create a better dashboard later.)

```[tasklist]
### Tasks
- [x] Discuss envisioned UX for notices with Graham
- [x] Socialize high-level design and API extensions in a design doc
- [x] Sketch a prototype based on the design doc
- [x] Merge prototype
- [x] Address fast follow-ups
- [x] Merge desgin doc
```
