### ISSUE TITLE
Opening many connections in parallel has terrible latency

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#21782]
## Description

@josharenberg observed that opening 2048 connections against Materialize takes _200s_, even when the connections are opened in parallel.

Some initial thinking with @ParkMyCar, @jkosh44, and @aljoscha revealed a likely culprit: updating the system tables (`mz_roles`, `mz_sessions`) during connection initiation. This involves an S3 write that takes 100-300ms. When multiple connections are opened in parallel, the S3 writes to update the system tables is handled _sequentially_ for each connection, resulting in abysmal performance.

@def- has a local repro that we should work into CI:

```
bin/mzcompose --find parallel-workload run default --runtime=3000 --complexity=read --seed=1694043310 --threads=950
```

## Work items

- [x] Adjust coordinator to batch up connection requests that arrive simultaneously. E.g., if 2048 connection requests arrive simultaneously, the coordinator should update `mz_roles` and `mz_sesions` just once.
  - [x] https://github.com/MaterializeInc/materialize/pull/21783
  - [x] https://github.com/MaterializeInc/materialize/pull/21801
- [x] Add a test to lock in the new performance to CI. @def-, can you help with this?

@ParkMyCar — adding you as the assignee since you said you were planning to pick this up on Monday. Feel free to adjust as you see fit. cc @chaas 

## See also

Slack conversation: https://materializeinc.slack.com/archives/C02FWJ94HME/p1694714722433879

## Decision log

*29 September 2023.* Added new work items for improved performance targets.
*15 September 2023.* Issue filed.

**Comment by benesch** [comment]
I feel like the P50 here should be ~150ms and the P99 should be ~300ms.

**Comment by def-** [comment]
Both my repro and what @josharenberg was running will run a query in the connection as well. So it might be running many queries at once which causes the latency to skyrocket, not the connections themselves.

**Comment by benesch** [comment]
> So it might be running many queries at once which causes the latency to skyrocket, not the connections themselves.

We're pretty sure it's async connection initialization that's makes that first query appear to be so slow. That first query on a connection can't run until the connection is initialized. After that, though, should be fast. I would be absolutely shocked if running 2048 `SELECT 1` statements in parallel on pre-initialized connections was anywhere close to this slow.

**Comment by pH14** [comment]
Another factor is that the writes to `mz_roles` and `mz_sessions` advance the timeline of every other system table. In addition to the CRDB work needed, we could also be blocking on acquiring a CRDB connection from the pool given that we have ~50 system tables and a connection pool size of 50

**Comment by def-** [comment]
I tried using @philip-stoev 's scalability testing framework for this: https://github.com/MaterializeInc/materialize/blob/main/test/scalability/README.md
But it seems to keep connections open, so doesn't accurately measure the latency: `bin/mzcompose --find scalability run default --workload SelectOneWorkload --max-concurrency 2048 --count 1`.

**Comment by def-** [comment]
> I feel like the P50 here should be ~150ms and the P99 should be ~300ms—even with thousands of connections.

There is now a test-concurrent-connections for this scenario, but we don't hit the target numbers yet:

https://github.com/MaterializeInc/materialize/blob/main/test/cluster/mzcompose.py#L2388-L2427

Numbers from CI: `min: 0.17s, p50: 0.44s, p99: 0.70s, max: 0.88s` (with 2000 concurrent `SELECT 1` connections). If this gets improved in the future we should adapt the test. It doesn't live in feature-benchmark (which would automatically adapt to better numbers since testdrive doesn't allow running multiple queries concurrently.

**Comment by josharenberg** [comment]
We were seeing different results from external tests, so I pulled the testing code out of mzcompose in order to run it externally. Based on these results, It seems possible that the bottleneck has moved to the auth code ( since that isn't run in CI ). Including the standalone test code and results here. 

Code: 
`import time
import os
import ssl
from statistics import quantiles
from threading import Thread
import pg8000

# Create an SSL context
ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE  # Use ssl.CERT_REQUIRED if you want to verify server certificate

# Fetch environment variables and set connection parameters
DB_PARAMS = {
    "user": os.environ.get("MZ_USER"),
    "password": os.environ.get("MZ_PASSWORD"),
    "host": os.environ.get("MZ_HOST"),
    "port": 6875,
    "database": "materialize",
    "ssl_context": ssl_context
}



def worker(i: int, runtimes: list) -> None:
    start_time = time.time()
    
    conn = pg8000.connect(**DB_PARAMS)
    cursor = conn.cursor()
    cursor.execute("SELECT 1")
    cursor.fetchone()
    
    end_time = time.time()

    runtimes[i] = end_time - start_time
    cursor.close()
    conn.close()

def workflow_test_concurrent_connections() -> None:
    """
    Run many concurrent connections, measure their p50 and p99 latency.
    """
    num_conns = 2000
    runtimes = [float("inf")] * num_conns

    threads = [Thread(name=f"worker_{i}", target=worker, args=(i, runtimes)) for i in range(num_conns)]

    for thread in threads:
        thread.start()

    for thread in threads:
        thread.join()

    p = quantiles(runtimes, n=100)
    print(
        f"min: {min(runtimes):.2f}s, p50: {p[49]:.2f}s, p99: {p[98]:.2f}s, max: {max(runtimes):.2f}s"
    )
    assert p[49] < 1.0, f"p50 is {p[49]:.2f}s, should be less than 1.0s"
    assert p[98] < 4.0, f"p99 is {p[98]:.2f}s, should be less than 4.0s"

if __name__ == '__main__':
    workflow_test_concurrent_connections()`

And my test restults against my staging env:

`$MZ_USER=josh@materialize.com MZ_PASSWORD=mypassword MZ_HOST=myhost python3.8 ./semiostest.py
min: 23.43s, p50: 24.43s, p99: 25.05s, max: 25.33s`

**Comment by ParkMyCar** [comment]
Since all of the original work items have been completed, I'm going to close out this issue.

We have further ideas of how to reduce connection latency, those are tracked here:
* https://github.com/MaterializeInc/materialize/issues/21838
* https://github.com/MaterializeInc/materialize/issues/22323
