### ISSUE TITLE
[Epic] Ingress balancer

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#21843]
Part of #20966.

- [x] Metrics
- [ ] Performance testing: measure in production infra the latency difference directly connecting to envd vs balancerd.
- [ ] Limit total memory use.
- [ ] Care about network usage (maybe make this a health check and metric).
- [ ] Care about number of open sockets (maybe health check this and metric).
- [ ] Test what happens if a connection task panics.
- [ ] Investigate if we need to disable nagle or modify other tcp stream options.
- [ ] Do tcp streams need timeouts? (This and the above nagle question need to be addressed for pgwire, https, and cancellation, maybe with different answers for each.)
- [ ] Think about other multitenant problems.

### Testing

* [x] End-to-end testing as much as possible in the mz repo. This would be: spin up an test envd with generate CA injected, start balancerd with that cert and a mock frontegg server, make sure things work.
- [x] End-to-end testing in cloud.
- [ ]  code coverage report
- [x] feature benchmark / scalability benchmarks comparison with and without balancerd . (pstoev: No regressions).
- [x] end-to-end tests around the authentication and hanshake parts and such
- [x] integrate balancerd into Zippy

**Comment by benesch** [comment]
The plan to run the scalability tests sounds good to me.

I also want to do a staged rollout in production. It'd be good to turn it on for new playground/trial environments only, and monitor those playground/trial environments for a bit, before flipping it on for everyone.

**Comment by mjibson** [comment]
Results from running the scalability tests:

I ran the scalability tests on a stack with and without auto scaling, and the balancer handled them both totally fine. Max connections was only in about the 250 range or so, so not actually that much.

Then I ran `ab` with `select 1`. Balancer handled 1k and 2k concurrent connections just fine:

![image](https://github.com/MaterializeInc/materialize/assets/41181/3db1594b-bfba-4a9c-9996-d93067ca99b2)

At around 2k connections cpu was at .8 (out of 1) and memory at 128MiB, so seems like we should have roughly 4 cpu per gb memory and we'd still be safe. 2x or 3x ratio if we want to be even more conservative with memory.

When the concurrent connections was bumped to 10k:

![image](https://github.com/MaterializeInc/materialize/assets/41181/928aa01b-65f1-42cd-bd2c-6c13379d1565)

This did *something* to cause the process to oom (as reported by exit code 137). But 128*5 is around 650, so I would not have expected a 5x connection increase to increase the memory by more than 5x. I assume some other effect is happening like balancer doesn't have enough cpu to transfer all the bytes around, so they build up in memory and crash it? Kinda makes sense, but I know very little about linux networking so that's very much a guess.

It seems that we can safely handle 500 connections per 1 cpu core (at whatever unit k8s uses) and 128M. I would like a cloud person to take those recommendations and convert them into more specific k8s recommendations. Is it better to have fewer big boxes with more connections, or more smaller boxes?

I did try to make the network usage go way up by sending lots of data back using generate series and string repeat, but wasn't able to pull more than 500KiB/s. That was perhaps because of http compression though since all the rows were the same. Unclear. But it did seem like network just wasn't at all a limiting resource.

**Comment by alex-hunt-materialize** [comment]
AWS compute optimized instances max out at 1:2 CPU:RAM, which is their most CPU favoring ratio. We have a few RAM-hungry daemonsets to balance it out, but a 4:1 CPU:RAM ratio will likely leave a lot of RAM unused. Maybe we should do a 2:1 CPU:RAM ratio, which would waste less of the machine, and give us a larger RAM safety margin.

I don't have strong opinions on whether to go with fewer larger pods vs more smaller pods. There are benefits to both approaches. In favor of the larger pods, we wouldn't have to scale as often, we'd have lower scheduler overhead, and the daemonset overhead would potentially be less (assuming we also properly bin-pack into larger instances). In favor of the smaller pods, we would have fewer connections disrupted by a noisy neighbor connection, and AWS may have better availability of the smaller instance sizes.

We probably want to somewhat closely match the instance sizes to `daemonsets + N*balancer pods + karpenter estimation margin`. To avoid paying extra to waste instance resources, `N` should probably be 1, but that conflicts with avoiding noisy neighbors. For now, I'll try to size it for a single balancer per instance, with our current instance sizes. Currently we have a bit over 1 CPU to spare, so I'll bump the pods to 2 CPUs and 1GiB RAM. We might eventually want to go one size up and swap to `c` series instances. We can't quite fit in the same tier `c` series due to daemonset memory use.

Do we currently do CPU pinning in the balancers? If not, I wonder if that would significantly affect these numbers.

For context of our current balancer instances (before any pod request changes):
```
Capacity:
  cpu:                4
  ephemeral-storage:  103189828Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  hugepages-32Mi:     0
  hugepages-64Ki:     0
  memory:             15986248Ki
  pods:               41
Allocatable:
  cpu:                3920m
  ephemeral-storage:  94026003504
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  hugepages-32Mi:     0
  hugepages-64Ki:     0
  memory:             13475400Ki
  pods:               41

Non-terminated Pods:          (7 in total)
  Namespace                   Name                                            CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                            ------------  ----------  ---------------  -------------  ---
  kube-system                 cilium-lcfdx                                    800m (20%)    0 (0%)      2Gi (15%)        2Gi (15%)      3d22h
  kube-system                 ebs-csi-node-h5pkz                              30m (0%)      0 (0%)      192Mi (1%)       192Mi (1%)     10d
  kubecost                    kubecost-network-costs-ctfjp                    350m (8%)     0 (0%)      512Mi (3%)       512Mi (3%)     10d
  mz-balancer                 balancer-us-east-1b-db8b69bfc-clnnh             1 (25%)       0 (0%)      1Gi (7%)         1Gi (7%)       10d
  mz-system                   cilium-eip-no-masquerade-agent-r9kzp            5m (0%)       0 (0%)      64Mi (0%)        64Mi (0%)      145m
  node-exporter               node-exporter-prometheus-node-exporter-jkw9s    100m (2%)     0 (0%)      180Mi (1%)       180Mi (1%)     10d
  vector                      vector-agent-hlwpn                              300m (7%)     0 (0%)      2Gi (15%)        2Gi (15%)      10d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                2585m (65%)   0 (0%)
  memory             6068Mi (46%)  6068Mi (46%)
  ephemeral-storage  0 (0%)        0 (0%)
  hugepages-1Gi      0 (0%)        0 (0%)
  hugepages-2Mi      0 (0%)        0 (0%)
  hugepages-32Mi     0 (0%)        0 (0%)
  hugepages-64Ki     0 (0%)        0 (0%)
```

**Comment by mjibson** [comment]
SGTM!

> Do we currently do CPU pinning in the balancers?

No.

**Comment by jubrad** [comment]
>>Do we currently do CPU pinning in the balancers?

>No.


We would pin the CPUs from a k8s perspective, pinning is enabled and the limit was a whole number which matched the request. If we only had one core during this test would we expect there to be different if we were using core_affinity to explicitly pin threads?

**Comment by mjibson** [comment]
I'm not aware of what pinning or affinity do, or what kinds of workloads they are good at.

**Comment by benesch** [comment]
Calling this complete as all major work is complete and the balancer layer is rolled out to production.

**Comment by benesch** [comment]
If there are requests for additional metrics, let's track as part of https://github.com/MaterializeInc/cloud/issues/7522.
