### ISSUE TITLE
Arrangements Epic

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#219]
Differential dataflow provides the opportunity to "arrange" maintained collections, which is in effect a continually updated index of the data in a stream-compatible representation. Arrangements are useful because several differential dataflow operators can directly import an arrangement rather than re-arrange the data, if the arrangement is by the correct key.

We have the opportunity to introduce standard RDBMS internals of indices, secondary indices, and things like this, which can dramatically reduce the deployment time and maintenance footprint of queries that re-use the same indexed forms of relations.

* [x] Add primary key information (#149)
* [x] Manage arrangements (#218)
* [ ] Introduce secondary indices (#220)
* [ ] Specialize arrangements (#221)
* [ ] Arrangement wrappers (#222)
* [ ] Partition vs Broadcast arrangements (#223)

**Comment by cuongdo** [comment]
Superseded by project board https://github.com/MaterializeInc/materialize/projects/7
