### ISSUE TITLE
storage/sources: hydration flow control

### ISSUE THREAD

**Issue by dseisun-materialize** [MaterializeInc/materialize#21989]
## Product outcome
Today when initializing a source, materialize will try to read in the initial snapshot in one pass, potentially leading to an OOM on the source cluster even if the source cluster is appropriately sized in steads state. As a result customers frequently need to size up their clusters for the initial snapshot of a source and then size it back down. The ask is to create some backpressure mechanism for this initial "hydration" step

## Discovery

[Product brief](https://www.notion.so/materialize/Product-brief-Hydration-backpressure-dc79703a1aa84f89af6467c86c6864df)

## Decision log
- 13 June 2024: Superseded by https://github.com/MaterializeInc/materialize/issues/27630
- Go with worker-local suspendable scopes instead of feedback-based
- Implement feedback-based if the above doesn't in practice for `UPSERT` sources.

### Tasks

Dependency tree: https://app.excalidraw.com/s/6NqJ5ikTEpv/PLFs0BqqMp

```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/materialize/issues/27210
- [ ] https://github.com/MaterializeInc/materialize/pull/27206
- [ ] https://github.com/MaterializeInc/materialize/issues/27211
- [ ] https://github.com/MaterializeInc/materialize/issues/27212
- [ ] https://github.com/MaterializeInc/materialize/issues/27213
- [ ] storage: ensure all sources never emit data beyond the progress frontier when yielding
- [ ] https://github.com/MaterializeInc/materialize/issues/27214
```

**Comment by bosconi** [comment]
@petrosagg should we use this to track the work you have planned to try and avoiid the need for hydration flow control?

**Comment by petrosagg** [comment]
Created an issue here https://github.com/MaterializeInc/materialize/issues/27630

**Comment by morsapaes** [comment]
Thanks, @petrosagg! ❤️ Closing in favour of the new issue.
