### ISSUE TITLE
[Epic] Add distributed TimestampOracle backed by Postgres/CRDB

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#22029]
Part of #20966.

Umbrella issue for implementing (yet unmerged) design doc for a distributed TimestampOracle: https://github.com/MaterializeInc/materialize/pull/21977.

```[tasklist]
### Checklist for Rollout to Staging/Production
- [x] Finish all subtasks
- [ ] https://github.com/MaterializeInc/cloud/issues/8217
- [x] Activate `timestamp_oracle=postgres` for staging and canary environments
- [x] Add new metrics to Coordinator/environmentd dashboard
- [x] Monitor internal metrics: query latency, latency of timestamp oracle operations, crdb connection pool metrics
- [x] Monitor CRDB metrics, potentially increased query load
- [x] Seek approval from QA
- [x] Activate `timestamp_oracle=postgres` for production environments (still waiting for one customer to be flipped)
```

```[tasklist]
### Subtasks
- [ ] https://github.com/MaterializeInc/materialize/pull/21977
- [ ] https://github.com/MaterializeInc/materialize/pull/22008
- [ ] https://github.com/MaterializeInc/materialize/pull/22018
- [ ] https://github.com/MaterializeInc/materialize/pull/22091
- [ ] https://github.com/MaterializeInc/materialize/pull/22112
- [ ] https://github.com/MaterializeInc/materialize/pull/22262
- [ ] https://github.com/MaterializeInc/materialize/pull/23022
- [ ] https://github.com/MaterializeInc/materialize/issues/23405
- [ ] https://github.com/MaterializeInc/materialize/issues/23406
- [ ] https://github.com/MaterializeInc/materialize/issues/23409
```
