### ISSUE TITLE
[Epic] SSH Tunnel improvements - Milestone 1

### ISSUE THREAD

**Issue by dseisun-materialize** [MaterializeInc/materialize#22280]
## Product outcome
* Allow new kafka brokers that are discovered to automatically use the existing SSH tunnel (currently any change in kafka brokers using SSH tunnels causes a failure)
* Allow for better error reporting as it relates to SSH tunnels to improve the ability to debug when an SSH tunnel is the culprit of a failing connection

This is a subset of the list of issues in the broader SSH Tunnels epic here: https://github.com/MaterializeInc/materialize/issues/18490

## Discovery
These are issues our customers have seen in production

## Work items

```[tasklist]
- [ ] https://github.com/MaterializeInc/materialize/issues/18375
- [x] https://github.com/MaterializeInc/materialize/pull/22718
- [ ] correctly categorize and test ssh statuses for sinks
- [ ] Followup on https://github.com/MaterializeInc/materialize/pull/22718: ensure we categorize kafka creation errors correctly
- [ ] Followup on https://github.com/MaterializeInc/materialize/pull/22718: ensure we categorize deode ssh errors correctly
```

## Decision log
* 10/1/23 - Chose to scope the larger SSH Tunnel epic down to these issues for the first milestone

**Comment by guswynn** [comment]
All outstanding tasks are closed by: https://github.com/MaterializeInc/materialize/pull/22869

**Comment by guswynn** [comment]
docs pr here: https://github.com/MaterializeInc/materialize/pull/22895
