### ISSUE TITLE
Scalability Framework Extensions

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#22306]
### Feature request

See https://www.notion.so/materialize/Scalability-Framework-Extension-Oct-2023-6f61701551e74d8fbad65fdf2eddf106
```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/materialize/issues/22307
- [ ] https://github.com/MaterializeInc/materialize/issues/22308
- [ ] https://github.com/MaterializeInc/materialize/issues/22309
- [ ] https://github.com/MaterializeInc/materialize/issues/22461
- [ ] https://github.com/MaterializeInc/materialize/issues/23799
- [ ] https://github.com/MaterializeInc/materialize/issues/23800
- [ ] https://github.com/MaterializeInc/materialize/issues/23801
```
