### ISSUE TITLE
[Epic] Improve lowering strategies for outer joins

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#22343]
## Product outcome

Customers often define SQL queries that contain one or more `OUTER JOIN` clauses, most commonly a `LEFT JOIN` stack.
Expand the class of `OUTER JOIN` predicates that lead to execution plans that utilize equality predicate structure, as they typically use less memory at runtime.

## Discovery

We produce two different types of plans for outer joins in the HIR ⇒ MIR lowering phase. The decision which plan type depends on an analysis pass of the `ON` condition for the `OUTER JOIN` clause:

1. A more robust and optimizable plan type based on equi-join conditions.
2. A less robust and optimizable, but more general plan type that supports arbitrary join conditions.

At the moment, this analysis is very limited, which means that we frequently produce type (2) even if we could use type (1). As a workaround, customers are therefore asked to write their SQL queries in a specific way in order to hit the more efficient type (1) path. We should cover a broader set of queries automatically in order to remove this burden from our customers.

The discovery for this epic happened within the scope of #22191. The product outcomes tracked here were identified as having potentially higher impact and more predictable delivery timeline compared to the ones in #22191.

The issues tackled here are a duplicate of #20801. See #20801 for more context of this happening in the past.

## Work items

```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/materialize/issues/22347
- [ ] https://github.com/MaterializeInc/materialize/issues/22348
- [ ] https://github.com/MaterializeInc/materialize/issues/22728
- [ ] https://github.com/MaterializeInc/materialize/issues/22729
- [ ] https://github.com/MaterializeInc/materialize/issues/22951
- [ ] https://github.com/MaterializeInc/materialize/issues/22952
- [ ] https://github.com/MaterializeInc/materialize/issues/22953
```

```[tasklist]
### Later
- [ ] https://github.com/MaterializeInc/materialize/issues/23297
- [ ] https://github.com/MaterializeInc/materialize/issues/23142
- [ ] https://github.com/MaterializeInc/materialize/issues/22443
- [ ] https://github.com/MaterializeInc/materialize/issues/22652
- [ ] https://github.com/MaterializeInc/materialize/issues/22646
- [ ] https://github.com/MaterializeInc/materialize/issues/22647
- [ ] https://github.com/MaterializeInc/materialize/issues/22622
- [ ] https://github.com/MaterializeInc/materialize/issues/22581
- [ ] https://github.com/MaterializeInc/materialize/issues/22582
- [ ] https://github.com/MaterializeInc/materialize/issues/22688
- [ ] https://github.com/MaterializeInc/materialize/issues/22954
```

```[tasklist]
### Related
- [ ] https://github.com/MaterializeInc/materialize/issues/22463
- [ ] https://github.com/MaterializeInc/materialize/issues/22437
- [ ] https://github.com/MaterializeInc/materialize/issues/24508
```

## Decision log

* **25 October 2023** Decided to rollout [#22347](22347) and  [#22348](22348) behind a feature flag. Target release is `v0.76.x`. With the help of [#22728](22728) and [#22729](22729) we should be able to get a sense about possible plan regressions and plan improvements to all index or view maintenance dataflows in `production` using a script that collects `EXPLAIN` outputs. If there are no concerns we will turn feature flag on for `v0.77.x`.
* **12 October 2023.** Issue created with discovery completed based on work done in #22191.

**Comment by aalexandrov** [comment]
All tasks in this epic are going to be resolved with #22560.

I plan to track how this PR affects production workloads with the following `log_filter` value:

```sql
ALTER SYSTEM SET log_filter = 'mz_sql::plan::lowering=DEBUG,INFO'
```

This will result in `DEBUG` lines such as

```text
DEBUG mz_sql::plan::lowering: OnPredicates::new case="thetajoin (subquery)"
DEBUG mz_sql::plan::lowering: OnPredicates::new case="thetajoin (error)"
DEBUG mz_sql::plan::lowering: OnPredicates::new case="thetajoin (eq)"
DEBUG mz_sql::plan::lowering: OnPredicates::new case="thetajoin (non-eq)"
DEBUG mz_sql::plan::lowering: OnPredicates::is_equijoin const_cnt=0 lhs_cnt=0 rhs_cnt=0 eq_cnt=1 theta_cnt=0
DEBUG mz_sql::plan::lowering: OnPredicates::join_keys case="outputs"
DEBUG mz_sql::plan::lowering: OnPredicates::is_equijoin const_cnt=0 lhs_cnt=0 rhs_cnt=0 eq_cnt=1 theta_cnt=0
DEBUG mz_sql::plan::lowering: OnPredicates::join_keys case="scalars"
DEBUG mz_sql::plan::lowering: OnPredicates::is_equijoin const_cnt=0 lhs_cnt=1 rhs_cnt=1 eq_cnt=1 theta_cnt=0
DEBUG mz_sql::plan::lowering: OnPredicates::join_keys case="scalars"
DEBUG mz_sql::plan::lowering: OnPredicates::is_equijoin const_cnt=0 lhs_cnt=1 rhs_cnt=1 eq_cnt=1 theta_cnt=0
DEBUG mz_sql::plan::lowering: OnPredicates::join_keys case="scalars"
DEBUG mz_sql::plan::lowering: OnPredicates::is_equijoin const_cnt=1 lhs_cnt=1 rhs_cnt=1 eq_cnt=1 theta_cnt=0
DEBUG mz_sql::plan::lowering: OnPredicates::join_keys case="scalars"
```
being visible in Loki / Grafana. Each `OnPredicates::join_keys case="scalars"` entry demonstrates a case covered by #22347. Each `OnPredicates::is_equijoin` entry where `const_cnt + lhs_cnt + rhs_cnt > 0` demonstrates a case covered by #22348.
