### ISSUE TITLE
[Epic] Refine Persist backed catalog State

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#22392]
After https://github.com/MaterializeInc/materialize/issues/20953 is complete, we'll have an implementation of persist backed catalog. However, there is still some outstanding work needed to make the implementation production ready.

## Product outcome

Add one of the primitives needed to increase customer use case isolation and zero downtime migrations.

## Discovery

Design document can be found here: https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20230806_durable_catalog_state.md

## Work items

TODO: Create GH issues for all tasks.

```[tasklist]
- [ ] Refine persist key-value schema.
- [ ] Update ShardID for better observability.
- [ ] Implement data format migrations.
- [ ] Implement a linearizable way to confirm leadership.
- [ ] Figure out a way to cleanly drop persist handles.
- [ ] Remove audit log from the catalog.
- [ ] Remove storage usage from the catalog.
- [ ] Implement a catalog debug tool to replace the stash debug tool.
- [ ] Move `mz_adapter::catalog` module into the `mz_catalog` crate.
```

**Comment by jkosh44** [comment]
Make sure to update docs around here: https://www.notion.so/materialize/Troubleshooting-failing-LaunchDarkly-synchronization-006583554b714dea82880338d7375907#20908feae9354b309c39bb4269ed904b once persist is the main store.

**Comment by jkosh44** [comment]
Scalability test results: https://buildkite.com/materialize/nightlies/builds/5692#018c8ce0-86c1-4c41-b1b7-13b46a44fc59
