### ISSUE TITLE
persist: FY24 Q4 checklist

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#22470]
- [prod] => stability/introspection
- [req] => requests from other teams/product for _new_ behavior
- [bug] => incorrect behavior

# Bugs
- [x] [bug] #15937
- [x] [bug] #17214
- [x] [bug] #19841
- [ ] [bug] GC/Shard finalization follow-ups https://github.com/MaterializeInc/cloud/issues/6705 
- [x] ~[bug] any needed follow-ups to https://github.com/MaterializeInc/materialize/issues/20287~
    - all connections are TTLed except for the catalog
- [ ] [bug] consensus_scan traffic when an MV input is stuck [context](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1703156679083869)

# Now: FY24 Q4
- [x] [prod] Constant-overhead auditing
- [ ] [bug] #22509
- [x] #21265
  - [x] #21615
- [x] [epic] Implement #18157
  - [x] #20482
  - [x] #22524
- [ ] [prod] Turn on CRDB changefeeds -> s3 for all prod environments
- [ ] [epic] Actually delete and cleanup data
  - [x] #17292
    - [x] Turned on in staging
    - [ ] Turned on in prod
  - [ ] #17322
  - [x] #20222

# Next: FY25 Q1 (epics first, otherwise not ordered)
- https://github.com/MaterializeInc/materialize/issues/24498
- [epic] Compute rehydration memory spikes
  - #22549
- [epic] [`PARTITION BY`](https://github.com/MaterializeInc/materialize/issues/23942)
- [epic] #16607
  - Break this down into chunks with incremental benefits
  - [Serialize the internals of Spine instead of the raw batches](https://github.com/MaterializeInc/materialize/issues/23848)
  - Fix the since used in compaction #15850
  - Consolidate the _deserialized_ K, V so encoding migrations work
  - Resurrect #15709
  - #17698
- [epic] #16858 
  - #18244
- [epic] Bounding state size (two-level lookup)
- [prod] #15209
  - Readers could either use ben's 🤯 idea or frank's "extreme" version

# Later: FY25 Q2+ (epics first, otherwise not ordered)
- [epic] #19322
- [epic] write Schema-ified data blobs
- [epic] Throughput tuning
  - #15518
  - Update open_loop benchmark to stress sharded reads and writes
  - #18066
- [epic] #16625
- [epic] Indexed lookup
- [epic] #17492
- [epic] #13918
- [epic] Consensus in-line writes
- [req] #24342
- [req] #17206
- [req] https://github.com/MaterializeInc/materialize/issues/20618
- [pushdown] Wire up stats to a system var (and add extra budget for large parts)
- [prod] #17776
- [prod] #19225
- [prod] #19608
- [prod] Resurrect #13961
- [prod] Hook client auth for Consensus up in prod
- [prod] Petros's idea to have a sharded exchangeable description of assigned compaction work
- [prod] Aljoscha's idea to balance the compare_and_append work in persist_sink operator 3 instead of a fixed worker
- [prod] #16699
- [prod] #16652
  - Blocked on getting more experience debugging persist issues
  - Similarly, mental model of underlying costs for persist users
- [prod] dynamically resizable CRDB connection pool (allows throttling of individual envs / processes)
- [prod] prometheus histogram of batch part sizes
- Split mz_persist_client::internal into mz_persist

**Comment by danhhz** [comment]
It's a couple days before the end of the quarter, but closing this early in favor of #24829 so we don't have two sources of truth.
