### ISSUE TITLE
[Epic] Improve memory attribution in Compute

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#22881]
## Product outcome

We can explain to users how allocated memory is used.

## Discovery

* We currently don't attribute memory for arrangement holding pens, for Reduce operators, for monotonic TopK, other buffers (persist_source, persist_sink).
* [Missing memory attribution in rendering](https://www.notion.so/materialize/Missing-Memory-Attribution-in-Rendering-39b0090b03004118b0b474e091fb5ba7?pvs=4).
* We want the additional metrics to be connected to https://github.com/MaterializeInc/console/issues/808.
* [Memory attribution in accumulable reductions](https://www.notion.so/materialize/Memory-Attribution-in-Accumulable-Reductions-800f3625893949f189e22f289aa0e2bf).
* [Memory Attribution: Potential Next Steps](https://www.notion.so/materialize/Memory-Attribution-Potential-Next-Steps-072d2b81d7824a1688735960d22f5e7f)

## Work items

```[tasklist]
# Milestone 1
- [X] Scope work
- [ ] https://github.com/MaterializeInc/materialize/issues/23113
- [ ] https://github.com/MaterializeInc/materialize/issues/23150
```

```[tasklist]
# Milestone 2
- [ ] https://github.com/MaterializeInc/materialize/pull/23646
- [ ] https://github.com/MaterializeInc/materialize/issues/23081
```

```[tasklist]
# Later
- [ ] https://github.com/MaterializeInc/materialize/issues/7428
- [ ] https://github.com/MaterializeInc/materialize/issues/23148
- [ ] https://github.com/MaterializeInc/materialize/issues/23202
- [ ] https://github.com/MaterializeInc/materialize/issues/23340
- [ ] Add changelog entry
- [ ] https://github.com/MaterializeInc/materialize/issues/23868
```

## Decision log

* **10 January 2023.** We observed significant improvements in memory attribution as a result of this epic. We are thus closing the issue and will tackle any items in the Later list only as needed.
* **14 December 2023.** Since some region-allocation changes landed for the arrangement holding bin, we decided to cut a milestone 2 with improved memory attribution picking up these changes as well as internal metrics to keep track of the `correction` buffer capacity in `persist_sink`.
* **29 November 2023.** We decided to cut a Milestone 1 with the changes to improve memory attribution of reductions (v0.78). Further work in this epic is better scheduled for later, after we invest more energy in region allocation ([internal doc with argument](https://www.notion.so/materialize/Memory-Attribution-Potential-Next-Steps-072d2b81d7824a1688735960d22f5e7f)).
* **7 November 2023.** @umanwizard and @vmarcos are scoping out the epic.
* **2 November 2023.** Issue created.
