### ISSUE TITLE
[Epic] Default session variables per user to GA

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#23048]
Make `ALTER ROLE ... SET ...` GA. It's currently behind a feature flag in private preview because of a conflict with the term "default". `SET cluster TO default` is ambiguous whether it should reset `cluster` to the default value, or the cluster named `default`, which we auto-create for every org. See discussion on https://github.com/MaterializeInc/materialize/issues/22351 for proposed solutions.

## Product outcome
Resolve release conflicts, add docs, and move to public preview and then GA.

## Work items
```[tasklist]
- [ ] https://github.com/MaterializeInc/materialize/issues/23754
- [ ] https://github.com/MaterializeInc/materialize/issues/22351
- [ ] https://github.com/MaterializeInc/materialize/issues/22107
```

## Decision log
* **8 Nov 2023** Commit to GA this feature within the quarter.

**Comment by chaas** [comment]
@morsapaes Is this worth a changelog post?
Here's the docs PR with more context for what changed https://github.com/MaterializeInc/materialize/pull/24050

**Comment by morsapaes** [comment]
For sure! There's a tracking changelog issue ([www #758](https://github.com/MaterializeInc/www/issues/758)).
