### ISSUE TITLE
Support `AWS` connections

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#23055]
## Context

We plan to build an AWS S3 sink, in which we write to an S3 bucket under the end user's control: https://github.com/MaterializeInc/materialize/issues/7256.

We'll need to integrate with AWS IAM so that our users can grant their Materialize region the ability to write to their desired S3 bucket.

Integration with AWS IAM would also be useful for facilitating IAM authentication with the following existing source types:

  * PostgreSQL on AWS RDS (https://github.com/MaterializeInc/materialize/issues/23056)
  * Kafka on AWS MSK (https://github.com/MaterializeInc/materialize/issues/8237)

While we support AWS RDS/MSK today via traditional username/password authentication, many users prefer to use AWS IAM with these services, as it eliminates the need to manage additional user accounts/passwords.

## Design sketch

See the [AWS connector](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220404_connectors.md#aws-connector) in the original `CREATE CONNECTION` design document for prior art.

Here's a version that's updated for what we've learned since that design document was written 1.5 years ago:

```sql
CREATE CONNECTION <connector_name> TO AWS (
  ACCESS KEY ID [[=] <value>],
  SECRET ACCESS KEY [[=] SECRET <value>],
  TOKEN [[=] SECRET <value>],
  ASSUME ROLE ARN [[=] <value>],
  ASSUME ROLE SESSION NAME [[=] <value>]
);
```

There are two ways to use this connection:

  1. You can specify `ACCESS KEY ID`, `SECRET ACCESS KEY`, and possibly `TOKEN`. This way is a bit sketchy, as you have  to punch your access credentials into Materialize, but it's secure enough via our secrets support. After all, punching in usernames/passwords is exactly what you have to do to connect to PostgreSQL/Kafka today.
  2. You can specify `ASSUME ROLE ARN`, and optionally `ASSUME ROLE SESSION NAME`, and use IAM policies in your target AWS account to allow Materialize to assume that role in your account.

Option 2 is the preferred way for production/sensitive connections. Option 1 is easier to get up and running with in development for nonsensitive connections (e.g., to a test/staging account).

Here's an example of using option 2:

1. You create a role in your target AWS account with a name of your choosing, e.g. `MaterializeS3`. Note down its ARN, e.g., `arn:aws:iam::001234567890:role/MaterializeS3Conn`.

2. You create the connection in Materialize:
    
    ```sql
    CREATE CONNECTION s3_conn TO AWS (
        ASSUME ROLE ARN = 'arn:aws:iam::001234567890:role/MaterializeS3Conn'
    );
    ```
    
    Note down the connection ID, e.g., u45.

3. You add a trust policy to the role that allows your Materialize deployment to access that role:

    ```json
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "",
          "Effect": "Allow",
          "Principal": {
            "AWS": "664411391173"
          },
          "Action": "sts:AssumeRole",
          "Condition": {
            "StringEquals": {
              "sts:ExternalId": "6f11558e-89da-4733-9a24-36eb9fd58129_u45"
            }
          }
        }
      ]
    }
    ```

4. Use the AWS connection as you like, e.g., to copy to S3: `COPY ... TO 's3://...' USING AWS CONNECTION s3_conn`. Materialize assumes the `MaterializeS3Conn` role in your account, as directed, and uses that role to write the data to your S3 bucket. 

Under the hood, Materialize will use the AWS credentials provided to create an AWS SDK client for the appropriate service. We have old code for this from when we supported S3 sources that we can dredge up. It's pretty straightforward: you plug the access key or assume role configuration into the SDK pretty directly.

One part that requires close attention to detail is external ID handling. When assuming a role, to make things safe, Materialize needs to specify a user ID that identifies from which Materialize region the request originates, as well as which _connection_ within that organization. The cloud already passes in the AWS external ID _prefix_ to use for the region (always a randomly generated UUID, [as AWS recommends](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html)). But Materialize needs to to be sure to append the connection ID to the external ID. This allows end users to write trust policies that ensure a given role can be assumed by only the _one_ identified connection in their Materialize account—and then they can use RBAC in Materialize to control who has `USAGE` privileges on that connection. Described in much more detail here: https://github.com/MaterializeInc/cloud/issues/2837

The upshot is that the external ID Materialize should use with assume role-style AWS connections is:

```
<external-id-prefix-provided-by-cloud>_<connection-id>
```

## See also

* The equivalent in Snowflake is [`CREATE STORAGE INTEGRATION`](https://docs.snowflake.com/en/sql-reference/sql/create-storage-integration) and [Configuring Secure Access to Amazon S3](https://docs.snowflake.com/en/user-guide/data-load-s3-config)
* https://github.com/MaterializeInc/cloud/issues/2837
* https://github.com/MaterializeInc/cloud/issues/7920
```[tasklist]
### Work Items
- [ ] https://github.com/MaterializeInc/materialize/pull/23173
- [x] Put AWS Connection retroactively behind feature flag
- [ ] https://github.com/MaterializeInc/materialize/pull/23626
- [ ] https://github.com/MaterializeInc/materialize/pull/23282
- [ ] https://github.com/MaterializeInc/cloud/issues/8191
- [ ] https://github.com/MaterializeInc/materialize/pull/23957
- [ ] https://github.com/MaterializeInc/materialize/pull/23958
- [ ] #23963
```

**Comment by benesch** [comment]
I just opened #23963, which is the last piece of the puzzle here. That PR will close this issue once merged. 

There's an outstanding cloud issue about adding a cloud-side end-to-end test for AWS connections. This is a great idea, but I think we can punt on this until we have `COPY {TO|FROM} S3`, at which point we can write a much more powerful cloud end-to-end test that validates not just AWS connections but also copying to/from S3.
