### ISSUE TITLE
[Epic] Query Lifecycle v0

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#23314]
## Product outcome
An initial version of query the lifecycle, where we expose key points in time in the query lifecycle as part of the statement log, such that the wall-clock durations can be calculated.
Outcome: users and field eng can see what caused their query to be slow, enabling further troubleshooting/debugging.

## Discovery
Initial proposal by Frank: https://www.notion.so/materialize/A-Model-for-Materialize-s-Operation-831f0a35782547518a8c05617dc087ca
Slack proposal by Frank: https://materializeinc.slack.com/archives/CQM08AP9V/p1698864009455029
Query lifecycle in-person workshop: https://www.notion.so/materialize/Query-lifecycle-workshop-8588c2fbdff5490a978701b85a3df5ad

Strawman design:
Add new catalog table `mz_internal.mz_activity_log_timestamps`
With columns:
* `stage`: an enum for the lifecycle stage, one of `EXECUTION_START`, `SOURCES_READY`, `MATERIALIZATIONS_READY`, `EXECUTION_FINISHED`, `LAST_ROW_RETURNED` (optional, can exclude this one to start).
* `wall_clock_time`: the wall clock time at which the stage was complete, type timestamp with time zone.

Stages:
| Stage  | Customer facing description | Technical definition | Already exists in mz_activity_log? |
| ------------- | ------------- | ------------- | ------------- |
| EXECUTION_START  | The wall-clock time at which the statement began executing.  | The time at which Materialize selected logical timestamp `t` for the query. | yes, `began_at` |
| SOURCES_READY  | The wall-clock time at which the sources were up-to-date and ready to return.  | The time at which the source data caught up to `t` (uppers ≥ `t`) and can thus return results. | no |
| MATERIALIZATIONS_READY  | The wall-clock time at which the dependent materialized views and indexes were up-to-date and ready to return.  | The time at which all the views and indexes that the query depends on are caught up to `t` and can thus return results.  | no |
| EXECUTION_FINISHED  | The wall-clock time at which the query finished executing and starts returning rows.  | The time at which we can return the first row. When all the temporary dataflows have loaded and/or results fetches from indexes. | yes, `finished_at` |
| LAST_ROW_RETURNED  | The wall-clock time at which the query finished returning all rows to the client. | The wall-clock time at which the query finished returning all rows to the client. | no |

Design alternative: made a separate column for each stage, and only have one row per statement execution.
The proposed design does not require updates to rows in the catalog table, at the cost of additional data size, as compared to the alternative.

Open questions:
* What to name the table? Should it join with the `mz_activity_log` or `mz_statement_execution_history`? Should the name be "lifecycles", "events", "timelines"?
* What to name the the columns?
* The existing `mz_activity_log` view already has `began_at` and `finished_at` - should we duplicate the data? Remove it from the `mz_activity_log`?
* What's the right term for "materialized views and indexes" aka objects that are incrementally maintained in memory, that a query might depend on? I used "materializations" here, but it might be confusing since we don't use that term universally, and in other contexts it might include sinks & subscribes?

Solution alternative: only make this information available as notices or some other transient solution, where the user opts in to receiving these notices via a session var (like with `emit_trace_id_notice`), and then receives notices for each stage in the lifecycle.
We may want to implement this alternative in addition to the proposed design, since they serve different functions.
The proposed design enables looking back at previous queries, or at queries run by others (such as field eng remotely debugging a customer issue). The alternative is more useful for live debugging one's own queries, and avoids the activity log sample rate and RBAC limitations of the activity log.

## Work items

```[tasklist]
- [x] Design doc that defines: 1) the catalog table schema and naming 2) how the stages will be measures and written to the table
- [ ] https://github.com/MaterializeInc/materialize/pull/24117
- [ ] Enable feature flag
```

## Decision log

<!--
Record all notable decisions as the project evolves, such as setting a target
date or changing the epic's scope or its breakdown. Please order entries in
descending order (the latest update should be the top most item).

Example:
* **15 November 2023.** Frank, Cara, Graham, Jan agree to prioritize building the query lifecycle v0 as a result of the query lifecycle workshop session, with helpful input from Brennan on design.

**Comment by ggnall** [comment]
The core work has merged, but is not enabled for any environments and may have some more design revisions. I recommend keeping this epic open to track any additional work and to match the state of the feature flag.

**Comment by ggnall** [comment]
Shipped! Categorizing as Public Preview as this is available to all users but part of the mz_internal schema.
