### ISSUE TITLE
[Epic] Troubleshooting docs for unresponsive & slow queries

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#23322]
## Product outcome
Step-by-step "decision tree" style troubleshooting guides for 1) why is my query hanging and 2) why is my query slow.
These are two of the most commonly asked questions when it comes to live troubleshooting, and lead to a wide/deep tree of steps.
The goal is threefold:
1) Produce the decision tree internally for debugging these issues, and get consensus across the org about the approach
2) Turn that into a user-facing guide, so that users can debug these issues themselves
3) Influence the product roadmap by identifying areas in which we're lacking actionable steps for users along this decision tree

## Discovery
Existing requests for troubleshooting content: https://github.com/MaterializeInc/materialize/issues/20719
Troubleshooting docs workshop notes: https://www.notion.so/materialize/Troubleshooting-docs-workshop-8918cdea74df47f4aec29766a4fb5c3e

## Work items

```[tasklist]
- [ ] Write up the decision tree for "why is my query hanging"
- [ ] Write up the decision tree for  "why is my query slow"
- [ ] Create an outline for the docs pages
- [ ] Write the docs copy
```

## Decision log

<!--
Record all notable decisions as the project evolves, such as setting a target
date or changing the epic's scope or its breakdown. Please order entries in
descending order (the latest update should be the top most item).

Example:
* **16 November 2022.** Project defined, prioritized, and assigned to @chaas .

**Comment by chaas** [comment]
I put together a decision tree diagram for debugging slow queries
https://www.figma.com/file/vWqkD8zAmkmrABzfJfDezG/Query-Debugging?type=whiteboard&node-id=0%3A1&t=7K1mj8zlCZpp83fK-1

Planning to use this as the foundation for troubleshooting docs
