### ISSUE TITLE
Improve AWS Kinesis sources 

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2346]
Information of V0 for Kinesis sources can be found here: https://github.com/MaterializeInc/materialize/issues/1239

Moving forward, we're currently prioritizing the following work for `v0.2.0`:
- [x] Create Kinesis source documentation: note known limitations, persistence, durability: https://github.com/MaterializeInc/materialize/issues/2198
- [x] Add Kinesis source testing to CI: https://github.com/MaterializeInc/materialize/issues/2197
- [x] Add Kinesis source testing to testdrive: https://github.com/MaterializeInc/materialize/issues/2196
- [ ] Load test Kinesis sources: https://github.com/MaterializeInc/materialize/issues/2202

The stretch goals:
- [x] Implement Kinesis source that can read from all of a stream's shards: https://github.com/MaterializeInc/materialize/issues/2222

Other Kinesis tickets exist, but are not scoped for `v0.2.0` unless we get direct feedback from customers.

**Comment by JLDLaughlin** [comment]
closing this tracking ticket! all things completed, except for merging/making load tests run nightly (which is in progress)
