### ISSUE TITLE
[persist] Bound the resources that we'll use in maintenance

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#24055]
Inspiration:
- Persist compaction [can cause large spikes in memory use](https://materializeinc.slack.com/archives/C04UK7BNVL7/p1702405882624009?thread_ts=1702404364.334199&cid=C04UK7BNVL7)
- Persist GC [can consume all of a machine's CPU](https://github.com/MaterializeInc/cloud/issues/6705)

We'd like to bound Persist's total resource use for maintenance purposes, to make it easier to size clusters etc.

```[tasklist]
### Tasks
- [ ] Bound the overall memory used by maintenance at one time
- [ ] Bound the amount of CPU maintenance may use at once
- [ ] Stress test / ensure that the maintenance limits are respected
```
