### ISSUE TITLE
[Epic] Fivetran destination, v1

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#24109]
## Product outcome

Users can use [Fivetran](https://fivetran.com) to continually load data into Materialize from any of its hundreds of supported connectors.

## Discovery

Fivetran has built a destination SDK with a clear specification to follow:

  * SDK documentation: https://github.com/fivetran/fivetran_sdk
  * Slack channel: #materialize-fivetran (internal only)

The destination SDK is built with a traditional data warehouse in mind—i.e., it is fundamentally a batch-oriented SDK. However, we have full latitude over the specific SQL we execute against Materialize, and some latitude in rejecting or working around features we don't support (e.g., `ALTER TABLE`).

Here's what we've determined to be in scope for v1:

  * Efficient bulk initial load
  * Efficient truncates (for full resyncs)
  * High throughput updates
  * Support for backwards-compatible `ALTER TABLE`s (i.e., adding a column with a default)

Here's what is _not_ in scope for v1:

  * Support for other `ALTER TABLE` operations (e.g., dropping columns)
  * Low latency updates

## Work items

```[tasklist]
- [ ] Get https://github.com/MaterializeInc/materialize/pull/23795 merged
- [ ] Add `cluster` configuration to Fivetran destination
- [ ] https://github.com/MaterializeInc/materialize/issues/16625
- [ ] Support adding new columns with a default in `ALTER TABLE`
- [ ] Support `AlterTableRequest` in the Fivetran destination
- [ ] Use `COPY ... FROM` in the Fivetran destination into a temporary table, rather than issuing point inserts/deletes
- [ ] Decide whether to support (`INSERT ... ON CONFLICT` and primary keys) or `MERGE`
- [ ] (Likely) Support `MERGE`
- [ ] (Likely) Use `MERGE` in the Fivetran destination
- [ ] Move heavy lifting for `COPY ... FROM` and `MERGE` to `clusterd`, to get `environmentd` off of the critical path
```

## Decision log

* **26 December 2023.** Issue created.

**Comment by ParkMyCar** [comment]
Unassigned myself for the time being since we're putting the work down for the moment
