### ISSUE TITLE
storage: Q1FY25 mega tracker

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#24755]
All known storage issues, sorted loosely by area and priority within area, except for those issues that are part of an epic on the product roadmap.

Legend:

  * p0: a correctness issue or panic, drop everything
  * p1: a painful bug or limitation, fix soon
  * p2: a nonpainful limitation or new feature, prioritize normally
  * onboarding: a good first issue
  * bitesized: small, straightforward issue, easy to work in alongside existing projects
  * flake: test flake
  * stale?: possibly irrelevant

## Connections

* [ ] https://github.com/MaterializeInc/materialize/issues/25707
* [ ] https://github.com/MaterializeInc/materialize/issues/26649

### SSH tunnels

* [ ] https://github.com/MaterializeInc/materialize/issues/24808 (p2, flake)
* [ ] https://github.com/MaterializeInc/materialize/issues/15723 (p2)

### AWS PrivateLink

* [ ] https://github.com/MaterializeInc/materialize/issues/20128 (bitesized)
* [x] https://github.com/MaterializeInc/materialize/issues/25468

### Kafka

* [x] https://github.com/MaterializeInc/materialize/issues/24864 (p0, flake)
* [x] https://github.com/MaterializeInc/materialize/issues/24858 (p0, flake)
* [x] https://github.com/MaterializeInc/materialize/issues/24901 (p1, flake)
* [x] https://github.com/MaterializeInc/materialize/issues/24712 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/8237 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/19543 (p2)

### PostgreSQL

* [ ] https://github.com/MaterializeInc/materialize/issues/23056 (p2)

### Foundational

* [ ] https://github.com/MaterializeInc/console/issues/1635 (p1)

### Foundational

* [x] https://github.com/MaterializeInc/materialize/issues/22128
* [ ] https://github.com/MaterializeInc/materialize/issues/26389
* [ ] https://github.com/MaterializeInc/materialize/issues/25707

### Load generators

* [ ] https://github.com/MaterializeInc/materialize/issues/18757 (p1, flake)
* [ ] https://github.com/MaterializeInc/materialize/issues/20436 (p2)

### Kafka

* [x] https://github.com/MaterializeInc/materialize/issues/21862 (p2)
* [x] https://github.com/MaterializeInc/materialize/issues/13748 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/25831 (p0, correctness)
* [ ] https://github.com/MaterializeInc/materialize/issues/10523 (XXX does this still repro?)
* [ ] https://github.com/MaterializeInc/materialize/issues/7462 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/10114 (p1, bitesized)
* [ ] https://github.com/MaterializeInc/materialize/issues/20819 (p1, disabled test)
* [ ] https://github.com/MaterializeInc/materialize/issues/22061 (p1, worth investigating)
* [ ] https://github.com/MaterializeInc/materialize/issues/24250 (p1, unverified correctness issue)
* [ ] https://github.com/MaterializeInc/materialize/issues/25803 (p1, liveness issue)
* [ ] https://github.com/MaterializeInc/materialize/issues/17491 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/7838 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/15698 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/20141 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/26136 (p2)

### PostgreSQL

* [x] https://github.com/MaterializeInc/materialize/issues/6930
* [x] https://github.com/MaterializeInc/materialize/issues/6742
* [x] https://github.com/MaterializeInc/materialize/issues/20936
* [x] https://github.com/MaterializeInc/materialize/issues/18537 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/23287 (p1, XXX is this stalled?)
* [ ] https://github.com/MaterializeInc/materialize/issues/22486 (p1, flake, correctness)
* [x] https://github.com/MaterializeInc/materialize/issues/24324 (p1, flake, correctness)
* [ ]  https://github.com/MaterializeInc/materialize/issues/14037 (p1)
* [ ] https://github.com/MaterializeInc/materialize/issues/26465 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/17955 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/14154 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/6825 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/15008 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/16371 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/17955 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/17956 (p2)
* [x] https://github.com/MaterializeInc/materialize/issues/17957 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/18826 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/19904 (p2, bitesized)
* [ ] https://github.com/MaterializeInc/materialize/issues/21001 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/21056 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/24357 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/24396 (p2, flake)
* [ ] https://github.com/MaterializeInc/materialize/issues/17986 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/15803 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/6819 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/6818 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/18518 (p2, bitesized)
* [ ] https://github.com/MaterializeInc/materialize/issues/18519 (p2, bitesized)
* [ ] https://github.com/MaterializeInc/materialize/issues/19510 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/19876 (p2)
* [ ] https://github.com/MaterializeInc/materialize/issues/15044 (p2, stale?)
* [ ] https://github.com/MaterializeInc/materialize/issues/6984 (p2, stale?)
* [ ] https://github.com/MaterializeInc/materialize/issues/15236 (p2, stale?)
* [ ] https://github.com/MaterializeInc/materialize/issues/26813

### MySQL

* [ ] https://github.com/MaterializeInc/materialize/issues/24797 (onboarding)

### Webhooks

* [ ] https://github.com/MaterializeInc/materialize/issues/22388

#### Debezium/Foundation

* [ ] https://github.com/MaterializeInc/materialize/issues/6854
* [ ] https://github.com/MaterializeInc/materialize/issues/11772
* [ ] https://github.com/MaterializeInc/materialize/issues/12077
* [ ] https://github.com/MaterializeInc/materialize/issues/6377
* [ ] https://github.com/MaterializeInc/materialize/issues/14211
* [ ] https://github.com/MaterializeInc/materialize/issues/17155
* [ ] https://github.com/MaterializeInc/materialize/issues/24941

#### Debezium/PostgreSQL

* [ ] https://github.com/MaterializeInc/materialize/issues/6535 (XXX is this still an issue?)
* [ ] https://github.com/MaterializeInc/materialize/issues/6521
* [ ] https://github.com/MaterializeInc/materialize/issues/6536
* [ ] https://github.com/MaterializeInc/materialize/issues/6537
* [ ] https://github.com/MaterializeInc/materialize/issues/6570
* [ ] https://github.com/MaterializeInc/materialize/issues/6596

#### Debezium/MySQL

* [ ] https://github.com/MaterializeInc/materialize/issues/10816
* [ ] https://github.com/MaterializeInc/materialize/issues/555

#### Debezium/SQL Server

* [ ] https://github.com/MaterializeInc/materialize/issues/8054

#### Debezium/New

* [ ] https://github.com/MaterializeInc/materialize/issues/7289
* [ ] https://github.com/MaterializeInc/materialize/issues/5508

### Requests for new sources

* [x] https://github.com/MaterializeInc/materialize/issues/15582
* [ ] https://github.com/MaterializeInc/materialize/issues/8328
* [ ] https://github.com/MaterializeInc/materialize/issues/2137
* [ ] https://github.com/MaterializeInc/materialize/issues/8633
* [ ] https://github.com/MaterializeInc/materialize/issues/2237
* [ ] https://github.com/MaterializeInc/materialize/issues/5918
* [ ] https://github.com/MaterializeInc/materialize/issues/6455
* [ ] https://github.com/MaterializeInc/materialize/issues/1704
* [x] https://github.com/MaterializeInc/materialize/issues/3423
* [ ] https://github.com/MaterializeInc/materialize/issues/10349
* [ ] https://github.com/MaterializeInc/materialize/issues/14106
* [ ] https://github.com/MaterializeInc/materialize/issues/14105
* [ ] https://github.com/MaterializeInc/materialize/issues/24763
* [ ] https://github.com/MaterializeInc/materialize/issues/3517
* [ ] https://github.com/MaterializeInc/materialize/issues/24769
* [ ] https://github.com/MaterializeInc/materialize/issues/2439
* [ ] https://github.com/MaterializeInc/materialize/issues/15901
* [ ] https://github.com/MaterializeInc/materialize/issues/26072

### Foundational

* [ ] https://github.com/MaterializeInc/materialize/issues/26350

### Kafka

* [x] https://github.com/MaterializeInc/materialize/issues/24928
* [x] https://github.com/MaterializeInc/materialize/issues/1576
* [ ] https://github.com/MaterializeInc/materialize/issues/26353
* [ ] https://github.com/MaterializeInc/materialize/issues/6223
* [ ] https://github.com/MaterializeInc/materialize/issues/10859
* [ ] https://github.com/MaterializeInc/materialize/issues/3517
* [ ] https://github.com/MaterializeInc/materialize/issues/15781
* [ ] https://github.com/MaterializeInc/materialize/issues/17565
* [ ] https://github.com/MaterializeInc/materialize/issues/17549
* [ ] https://github.com/MaterializeInc/materialize/issues/23794
* [ ] https://github.com/MaterializeInc/materialize/issues/23955
* [ ] https://github.com/MaterializeInc/materialize/issues/24043
* [x] https://github.com/MaterializeInc/materialize/issues/24721 (flake)
* [x] https://github.com/MaterializeInc/materialize/issues/24734
* [ ] https://github.com/MaterializeInc/materialize/issues/16266
* [ ] https://github.com/MaterializeInc/materialize/issues/23925
* [ ] https://github.com/MaterializeInc/materialize/issues/24801
* [ ] https://github.com/MaterializeInc/materialize/issues/25242
* [x] https://github.com/MaterializeInc/materialize/issues/24936
* [ ] https://github.com/MaterializeInc/materialize/issues/25479 (p1, flake, correctness)
* [ ] https://github.com/MaterializeInc/materialize/issues/26787

### Requests for new sinks

* [ ] https://github.com/MaterializeInc/materialize/issues/2372
* [ ] https://github.com/MaterializeInc/materialize/issues/2678
* [ ] https://github.com/MaterializeInc/materialize/issues/1077
* [ ] https://github.com/MaterializeInc/materialize/issues/4779
* [ ] https://github.com/MaterializeInc/materialize/issues/1706
* [x] https://github.com/MaterializeInc/materialize/issues/3423
* [ ] https://github.com/MaterializeInc/materialize/issues/24764
* [ ] https://github.com/MaterializeInc/materialize/issues/7256
* [ ] https://github.com/MaterializeInc/materialize/issues/20316

### JSON

* [x] https://github.com/MaterializeInc/materialize/issues/25148 (bitesized)

### Confluent Schema Registry

* [ ] https://github.com/MaterializeInc/materialize/issues/7107 (XXX is this still happening?)
* [ ] https://github.com/MaterializeInc/materialize/issues/18269 (flake)
* [ ] https://github.com/MaterializeInc/materialize/issues/24644 (arm)

### Avro

* [ ] https://github.com/MaterializeInc/materialize/issues/6461
* [ ] https://github.com/MaterializeInc/materialize/issues/7105
* [ ] https://github.com/MaterializeInc/materialize/issues/6434
* [ ] https://github.com/MaterializeInc/materialize/issues/8917
* [x] https://github.com/MaterializeInc/materialize/issues/8919
* [ ] https://github.com/MaterializeInc/materialize/issues/14134
* [ ] https://github.com/MaterializeInc/materialize/issues/14133
* [ ] https://github.com/MaterializeInc/materialize/issues/18544
* [ ] https://github.com/MaterializeInc/materialize/issues/3629

### Protobuf

* [ ] https://github.com/MaterializeInc/materialize/issues/8158
* [ ] https://github.com/MaterializeInc/materialize/issues/9598

### Requests for new formats

* [ ] https://github.com/MaterializeInc/materialize/issues/7186
* [ ] https://github.com/MaterializeInc/materialize/issues/12304

### Upsert

* [ ] https://github.com/MaterializeInc/materialize/issues/10819
* [ ] https://github.com/MaterializeInc/materialize/issues/6389
* [ ] https://github.com/MaterializeInc/materialize/issues/15781
* [ ] https://github.com/MaterializeInc/materialize/issues/16512
* [ ] https://github.com/MaterializeInc/materialize/issues/19557
* [ ] https://github.com/MaterializeInc/materialize/issues/19622
* [ ] https://github.com/MaterializeInc/materialize/issues/19860
* [ ] https://github.com/MaterializeInc/materialize/issues/20214
* [ ] https://github.com/MaterializeInc/materialize/issues/21057
* [ ] https://github.com/MaterializeInc/materialize/issues/22466 (flake)
* [ ] https://github.com/MaterializeInc/accounts/issues/16
* [ ] https://github.com/MaterializeInc/materialize/issues/23998
* [ ] https://github.com/MaterializeInc/materialize/issues/9369
* [ ] https://github.com/MaterializeInc/materialize/issues/18842
* [ ] https://github.com/MaterializeInc/materialize/issues/19999 (flake)

### Requests for new envelopes

* [ ] https://github.com/MaterializeInc/materialize/issues/20957

### Conceptual model

* [ ] https://github.com/MaterializeInc/materialize/issues/20208
* [ ] https://github.com/MaterializeInc/materialize/issues/24843
* [ ] https://github.com/MaterializeInc/materialize/issues/25122
* [ ] https://github.com/MaterializeInc/materialize/issues/16060
* [ ] https://github.com/MaterializeInc/materialize/issues/15903
* [ ] https://github.com/MaterializeInc/materialize/issues/17021
* [ ] https://github.com/MaterializeInc/materialize/issues/17668
* [ ] https://github.com/MaterializeInc/materialize/issues/17672
* [ ] https://github.com/MaterializeInc/materialize/issues/19322
* [ ] https://github.com/MaterializeInc/materialize/issues/21428
* [ ] https://github.com/MaterializeInc/materialize/issues/24773
* [ ] https://github.com/MaterializeInc/materialize/issues/17413

### SQL syntax/semantics

* [ ] https://github.com/MaterializeInc/materialize/issues/15272
* [ ] https://github.com/MaterializeInc/materialize/issues/11957
* [ ] https://github.com/MaterializeInc/materialize/issues/20930
* [ ] https://github.com/MaterializeInc/materialize/issues/24676
* [ ] https://github.com/MaterializeInc/materialize/issues/17826
* [ ] https://github.com/MaterializeInc/materialize/issues/18767
* [ ] https://github.com/MaterializeInc/materialize/issues/20135
* [ ] https://github.com/MaterializeInc/materialize/issues/18210
* [ ] https://github.com/MaterializeInc/materialize/issues/26283 (onboarding)

### Timely async bridge

* [ ] https://github.com/MaterializeInc/materialize/issues/19098

### Reclocking

* [ ] https://github.com/MaterializeInc/materialize/issues/22812
* [ ] https://github.com/MaterializeInc/materialize/issues/23345
* [ ] https://github.com/MaterializeInc/materialize/issues/21047 (p1)

### Retention policy

* [ ] https://github.com/MaterializeInc/materialize/issues/15899
* [ ] https://github.com/MaterializeInc/materialize/issues/16547

### Observability

* [ ] https://github.com/MaterializeInc/materialize/issues/13489
* [ ] https://github.com/MaterializeInc/materialize/issues/11657
* [ ] https://github.com/MaterializeInc/materialize/issues/16580
* [ ] https://github.com/MaterializeInc/materialize/issues/16582
* [ ] https://github.com/MaterializeInc/materialize/issues/17180
* [ ] https://github.com/MaterializeInc/materialize/issues/17207
* [ ] https://github.com/MaterializeInc/materialize/issues/13489
* [ ] https://github.com/MaterializeInc/materialize/issues/19492
* [ ] https://github.com/MaterializeInc/materialize/issues/19304
* [ ] https://github.com/MaterializeInc/materialize/issues/20036
* [ ] https://github.com/MaterializeInc/materialize/issues/16332
* [ ] https://github.com/MaterializeInc/materialize/issues/21352 (XXX is this done?)
* [ ] https://github.com/MaterializeInc/materialize/issues/21354
* [ ] https://github.com/MaterializeInc/materialize/issues/21617
* [ ] https://github.com/MaterializeInc/materialize/issues/22208
* [x] https://github.com/MaterializeInc/materialize/issues/23154
* [ ] https://github.com/MaterializeInc/materialize/issues/24204
* [x] https://github.com/MaterializeInc/materialize/issues/23950
* [ ] https://github.com/MaterializeInc/materialize/issues/24676
* [ ] https://github.com/MaterializeInc/materialize/issues/24937
* [ ] https://github.com/MaterializeInc/materialize/issues/20997
* [x] https://github.com/MaterializeInc/materialize/issues/24996
* [ ] https://github.com/MaterializeInc/materialize/issues/25349
* [ ] https://github.com/MaterializeInc/materialize/issues/25446
* [ ] https://github.com/MaterializeInc/materialize/issues/25501 (onboarding)
* [ ] https://github.com/MaterializeInc/materialize/issues/26279 (onboarding)
* [ ] https://github.com/MaterializeInc/cloud/issues/9021 (onboarding, bitesized)
* [ ] https://github.com/MaterializeInc/materialize/issues/26349 (onboarding, bitesized)
* [ ] https://github.com/MaterializeInc/materialize/issues/25821 (p2, flake)
* [ ] https://github.com/MaterializeInc/materialize/issues/26060 (p2, flake)

### Test frameworks

* [ ] https://github.com/MaterializeInc/materialize/issues/8418
* [ ] https://github.com/MaterializeInc/materialize/issues/14533
* [ ] https://github.com/MaterializeInc/materialize/issues/22628

### Resource cleanup

* [ ] https://github.com/MaterializeInc/materialize/issues/14551
* [ ] https://github.com/MaterializeInc/materialize/issues/8185
* [ ] https://github.com/MaterializeInc/materialize/issues/19155
* [ ] https://github.com/MaterializeInc/materialize/issues/24586

### Controller

* [ ] https://github.com/MaterializeInc/materialize/issues/14729
* [ ] https://github.com/MaterializeInc/materialize/issues/17416
* [ ] https://github.com/MaterializeInc/materialize/issues/17417
* [ ] https://github.com/MaterializeInc/materialize/issues/17418
* [ ] https://github.com/MaterializeInc/materialize/issues/17650 (XXX is this superseded by dynconfig?)
* [ ] https://github.com/MaterializeInc/materialize/issues/19097
* [ ] https://github.com/MaterializeInc/materialize/issues/19279
* [ ] https://github.com/MaterializeInc/materialize/issues/19917
* [ ] https://github.com/MaterializeInc/materialize/issues/20299
* [ ] https://github.com/MaterializeInc/materialize/issues/21316
* [ ] https://github.com/MaterializeInc/materialize/issues/18763
* [ ] https://github.com/MaterializeInc/materialize/issues/21817
* [ ] https://github.com/MaterializeInc/materialize/issues/21945
* [ ] https://github.com/MaterializeInc/materialize/issues/23513
* [ ] https://github.com/MaterializeInc/materialize/issues/17375
* [ ] https://github.com/MaterializeInc/materialize/issues/24266
* [ ] https://github.com/MaterializeInc/materialize/issues/24914
* [ ] https://github.com/MaterializeInc/materialize/issues/24955
* [ ] https://github.com/MaterializeInc/materialize/issues/25523

### Miscellaneous

* [ ] https://github.com/MaterializeInc/materialize/issues/26545
* [ ] https://github.com/MaterializeInc/materialize/issues/20115
* [ ] https://github.com/MaterializeInc/materialize/issues/21989
* [ ] https://github.com/MaterializeInc/materialize/issues/3790
* [ ] https://github.com/MaterializeInc/materialize/issues/15213
* [ ] https://github.com/MaterializeInc/materialize/issues/15897
* [ ] https://github.com/MaterializeInc/materialize/issues/25770
* [x] https://github.com/MaterializeInc/materialize/issues/26011
* [ ] https://github.com/MaterializeInc/materialize/issues/26139 (onboarding)

### Developer productivity improvements

* [ ] https://github.com/MaterializeInc/materialize/issues/12599
* [ ] https://github.com/MaterializeInc/materialize/issues/20044
* [ ] https://github.com/MaterializeInc/materialize/issues/17011
* [ ] https://github.com/MaterializeInc/materialize/issues/23111
* [ ] https://github.com/MaterializeInc/materialize/issues/15199

### External documentation

* [ ] https://github.com/MaterializeInc/materialize/issues/15755
* [ ] https://github.com/MaterializeInc/materialize/issues/20526
* [ ] https://github.com/MaterializeInc/materialize/issues/18145

### Backup and restore

* [ ] https://github.com/MaterializeInc/materialize/issues/22742
* [ ] https://github.com/MaterializeInc/materialize/issues/22762
* [ ] https://github.com/MaterializeInc/materialize/issues/22770
* [ ] https://github.com/MaterializeInc/materialize/issues/22814
* [ ] https://github.com/MaterializeInc/materialize/issues/22816

### Sanitizer issues

Issues discovered by AddressSanitizer, LeakSanitizer, et al that may not be real issues

* [ ] https://github.com/MaterializeInc/materialize/issues/25070
* [ ] https://github.com/MaterializeInc/materialize/issues/25078
* [ ] https://github.com/MaterializeInc/materialize/issues/25079

## persist

TODO(benesch): incorporate these into the mega persist tracker?

* [ ] https://github.com/MaterializeInc/materialize/issues/14122
* [ ] https://github.com/MaterializeInc/materialize/issues/13918
* [ ] https://github.com/MaterializeInc/materialize/issues/13491
* [ ] https://github.com/MaterializeInc/materialize/issues/13576
* [ ] https://github.com/MaterializeInc/materialize/issues/9193
* [ ] https://github.com/MaterializeInc/materialize/issues/15066
* [ ] https://github.com/MaterializeInc/materialize/issues/15093
* [ ] https://github.com/MaterializeInc/materialize/issues/15209
* [ ] https://github.com/MaterializeInc/materialize/issues/16524
* [ ] https://github.com/MaterializeInc/materialize/issues/16625
* [ ] https://github.com/MaterializeInc/materialize/issues/16652
* [ ] https://github.com/MaterializeInc/materialize/issues/16858
* [ ] https://github.com/MaterializeInc/materialize/issues/17206
* [ ] https://github.com/MaterializeInc/materialize/issues/17322
* [ ] https://github.com/MaterializeInc/materialize/issues/17492
* [ ] https://github.com/MaterializeInc/materialize/issues/16607
* [ ] https://github.com/MaterializeInc/materialize/issues/18213
* [ ] https://github.com/MaterializeInc/materialize/issues/18052
* [ ] https://github.com/MaterializeInc/materialize/issues/18213
* [ ] https://github.com/MaterializeInc/materialize/issues/18076
* [ ] https://github.com/MaterializeInc/materialize/issues/18368
* [x] https://github.com/MaterializeInc/materialize/issues/21265
* [ ] https://github.com/MaterializeInc/materialize/issues/18662
* [ ] https://github.com/MaterializeInc/materialize/issues/18898
* [ ] https://github.com/MaterializeInc/materialize/issues/19102
* [ ] https://github.com/MaterializeInc/materialize/issues/19155
* [ ] https://github.com/MaterializeInc/materialize/issues/19225
* [ ] https://github.com/MaterializeInc/materialize/issues/19608
* [ ] https://github.com/MaterializeInc/materialize/issues/20396
* [ ] https://github.com/MaterializeInc/materialize/issues/20618
* [ ] https://github.com/MaterializeInc/materialize/issues/20879
* [ ] https://github.com/MaterializeInc/materialize/issues/21353
* [ ] https://github.com/MaterializeInc/materialize/issues/21355
* [ ] https://github.com/MaterializeInc/materialize/issues/22289
* [x] https://github.com/MaterializeInc/materialize/issues/22509
* [ ] https://github.com/MaterializeInc/materialize/issues/22680
* [ ] https://github.com/MaterializeInc/materialize/issues/23848
* [ ] https://github.com/MaterializeInc/materialize/issues/23942
* [ ] https://github.com/MaterializeInc/materialize/issues/24055
* [ ] https://github.com/MaterializeInc/materialize/issues/24498
* [x] https://github.com/MaterializeInc/materialize/issues/24695
* [ ] https://github.com/MaterializeInc/materialize/issues/24342
* [ ] https://github.com/MaterializeInc/materialize/issues/19020

**Comment by morsapaes** [comment]
Ported all unresolved issues to a fresh mega tracker for Q2FY25: #26815.
