### ISSUE TITLE
[Epic] adapter: multi-subscriber Catalog

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#24844]
## Background

Use-case isolation is meant to provide customers with the tools for managing incidental unavailability.

Milestones Overview: https://www.notion.so/materialize/Use-case-Isolation-Milestones-b64e53900c0c498eae4bd38df6adb7c8

---

Currently the coordinator/adapter takes the following actions in response to certain events, in no particular order:

- Update the durable catalog contents.
- Update the in-memory catalog state.
- Append updates to builtin tables.
- Send commands to controllers.

The coordinator/adapter must separate the logic for updating the durable catalog contents from everything else listed above. It should be able to update the in-memory catalog state, append updates to builtin tables, and send commands to controllers in response to changes in the durable catalog contents.

Note: Not all builtin table updates and controller commands are sent in response to catalog changes, for example updates to the `mz_sessions` tables. Those do not need to change as part of this epic.

```[tasklist]
### Subtasks
- [ ] https://github.com/MaterializeInc/materialize/issues/25253
- [ ] https://github.com/MaterializeInc/materialize/pull/26359
- [ ] https://github.com/MaterializeInc/materialize/pull/26380
- [ ] https://github.com/MaterializeInc/materialize/pull/26387
- [ ] https://github.com/MaterializeInc/materialize/pull/26388
- [ ] https://github.com/MaterializeInc/materialize/pull/26461
- [ ] https://github.com/MaterializeInc/materialize/pull/26464
- [ ] https://github.com/MaterializeInc/materialize/pull/26507
- [ ] https://github.com/MaterializeInc/materialize/pull/26542
- [ ] https://github.com/MaterializeInc/materialize/pull/26544
- [ ] https://github.com/MaterializeInc/materialize/pull/26562
- [ ] https://github.com/MaterializeInc/materialize/pull/26578
- [ ] https://github.com/MaterializeInc/materialize/pull/26579
- [ ] https://github.com/MaterializeInc/materialize/pull/26781
- [ ] https://github.com/MaterializeInc/materialize/pull/27290
- [ ] https://github.com/MaterializeInc/materialize/pull/27293
- [ ] https://github.com/MaterializeInc/materialize/pull/27295
- [ ] https://github.com/MaterializeInc/materialize/pull/27441
- [ ] https://github.com/MaterializeInc/materialize/pull/27449
- [ ] https://github.com/MaterializeInc/materialize/pull/27473
- [ ] https://github.com/MaterializeInc/materialize/pull/27504
- [ ] https://github.com/MaterializeInc/materialize/pull/27519
- [ ] https://github.com/MaterializeInc/materialize/pull/27551
- [ ] https://github.com/MaterializeInc/materialize/pull/27569
- [ ] https://github.com/MaterializeInc/materialize/pull/27573
- [ ] https://github.com/MaterializeInc/materialize/pull/27575
- [ ] https://github.com/MaterializeInc/materialize/pull/27606
- [ ] https://github.com/MaterializeInc/materialize/pull/27644
- [ ] https://github.com/MaterializeInc/materialize/pull/27667
- [ ] https://github.com/MaterializeInc/materialize/pull/27607
- [ ] https://github.com/MaterializeInc/materialize/pull/27778
- [ ] https://github.com/MaterializeInc/materialize/pull/27872
- [ ] https://github.com/MaterializeInc/materialize/pull/27994
- [ ] https://github.com/MaterializeInc/materialize/pull/28025
- [ ] Generate controller commands from durable catalog changes
```

**Comment by jkosh44** [comment]
I'm replacing this epic with the one remaining issue: https://github.com/MaterializeInc/materialize/issues/29279
