### ISSUE TITLE
[Epic] Cluster-specific optimization

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#25273]
## Product outcome

Materialize engineers working on changes in the compute layer that require changes to the optimizer pipeline can perform production experiments on unbilled clusters which force the proposed new version of the pipeline (enabled behind a cluster-specific feature flag).

## Discovery

- [ ] Design: https://github.com/MaterializeInc/materialize/pulls/aalexandrov
- [ ] MVP: https://github.com/MaterializeInc/materialize/pull/25165

## Work items

```[tasklist]

## Pre-production (discovery)
- [ ] Create design doc draft
- [ ] Socialize design doc
- [ ] Complete MVP
```

```[tasklist]
## Production (development)
- [ ] Merge parser changes
- [ ] Merge planner changes
- [ ] Merge catalog changes
- [ ] Merge optimizer changes
```

## Post-production (rollout)
- [ ] Use it to run `enable_eager_delta_joins` experiments
- [ ] Use it to run `enable_outer_join_stack_lowering` experiments
```

## Decision log

<!--
Record all notable decisions as the project evolves, such as setting a target
date or changing the epic's scope or its breakdown. Please order entries in
descending order (the latest update should be the top most item).

Example:
> * **18 September 2023.** Added Nullability control for Avro-formatted sinks #21722 as a work item.
> * **28 August 2023.** Set a target release date of October 31.
-->

* **15 February 2024.** Putting active development on hold in order to prioritize #24155.
* **1 February 2024.** Initiated the discovery phase.

**Comment by ggevay** [comment]
This really seems done.
