### ISSUE TITLE
storage/connections/aws-privatelink: promote to GA

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25503]
Per discussion with @pH14 in today's roadmap review, we feel that the time has come to promote AWS PrivateLink connections to GA. They are effectively GA already, in that many of our customers already rely on them for their production workloads and we treat any PrivateLink problems as p0 issues.

## Work items

* [x] https://github.com/MaterializeInc/cloud/issues/8642
* [x] https://github.com/MaterializeInc/materialize/issues/25468
* [x] https://github.com/MaterializeInc/materialize/issues/20128
* [x] https://github.com/MaterializeInc/cloud/issues/8238
* [x] Ensure PrivateLink E2E tests are running in cloud staging and production
* [x] https://github.com/MaterializeInc/materialize/pull/27337
* [x] #shipped-it post
* ~Changelog post~

## Activity log

* **23 February 24.** Create this issue on the storage roadmap with a target delivery date of Mar 30. 

cc @morsapaes @jubrad

**Comment by pH14** [comment]
Justin needs to get all the credit here. This is done! @jubrad feel free to reopen and reclose when you're back 😉
