### ISSUE TITLE
[Epic] Use latest cluster infrastructure for mz_introspection & mz_system

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#25517]
Bundle of work to move the mz_introspection and mz_system cluster to the modern cluster infrastructure and add some robustness.
The main highlights are migrating to a managed cluster and using the new cc sizes with disk enabled, so that we can get the benefits of lgalloc for mz_introspection, which gets heavy use from the console + user analytics and monitoring queries.
We also want to add some robustness around scaling clusters up.

```[tasklist]
### Required
- [ ] https://github.com/MaterializeInc/materialize/issues/24983
- [ ] https://github.com/MaterializeInc/materialize/issues/22326
- [x] https://github.com/MaterializeInc/materialize/issues/25134 (might need different design for managed clusters)
- [ ] https://github.com/MaterializeInc/materialize/issues/25834
- [ ] New monitoring/alerting required to identify scale-up needs?
```

```[tasklist]
### Nice to have
- [ ] Automation/configuration in retool for scaling up mz_introspection cluster for specific customers
```

**Comment by chaas** [comment]
Linking to initial investigation from @jkosh44 
https://materializeinc.slack.com/archives/C02FWJ94HME/p1709149601018389

**Comment by benesch** [comment]
@chaas heads up that I added a work item here to add an `mz_probe` cluster: https://github.com/MaterializeInc/materialize/issues/25834. Let me know if you disagree with bundling that with this work. I added an agenda item to tomorrow's roadmap review.
