### ISSUE TITLE
[Epic] Activity log improvements

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#25868]
Follow up items for the activity log and statement lifecycle

```[tasklist]
### Feature requests
- [ ] https://github.com/MaterializeInc/materialize/issues/25665
- [ ] https://github.com/MaterializeInc/materialize/issues/25752
```

```[tasklist]
### Scalability
- [ ] https://github.com/MaterializeInc/materialize/issues/25697
- [ ] https://github.com/MaterializeInc/materialize/issues/25696
```

**Comment by parkerhendo** [comment]
@chaas Do we have a tracking issue for the problem with Session Id's in the activity log not aligning with what's in `mz_sessions`? I didn't see it here, so wanted to check.

**Comment by chaas** [comment]
> @chaas Do we have a tracking issue for the problem with Session Id's in the activity log not aligning with what's in mz_sessions? I didn't see it here, so wanted to check.

That's this first one in the "Feature requests" list https://github.com/MaterializeInc/materialize/issues/25665

**Comment by parkerhendo** [comment]
@chaas oof sorry, I completely missed that 🤦
