### ISSUE TITLE
adapter: Read hold not being dropped on system objects

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#26154]
### What version of Materialize are you using?

v0.91.0

### What is the issue?

We've observed the read frontier of system objects, e.g. the `mz_frontiers_ind` index, getting stuck and not advancing with time. This can cause a large memory increase (especially if an index is stuck, and most of our system objects are indexed) but also result in query latency spikes as dataflows now have to churn through lots of uncompacted data.

We observed this in @SangJunBak's staging account and after some debugging found a SQL session was started <1 second before the read frontier became stuck. This session was (still?) alive for multiple days which points at some connection or session cleanup not occurring. Also according to Jun he almost exclusively uses the web console so this problem might be specific to the HTTP and websocket endpoints, not positive though.

Our discussion while debugging can be found [here in Slack](https://github.com/MaterializeInc/materialize/issues/26154)

Proposed action items

- [x] Find a consistent repro of the issue
- [x] Review http/websocket endpoints to see if we're failing to drop connections on certain disconnection flows
- [ ] https://github.com/MaterializeInc/materialize/issues/10390
- [ ] https://github.com/MaterializeInc/materialize/issues/13130 - will allow us to kill any stray connections/transactions left open
- [ ] https://github.com/MaterializeInc/materialize/issues/26155 - will allow us to restart envd without restarting clusterds
```[tasklist]
### Tasks
```

**Comment by benesch** [comment]
Per [discussion on Slack](https://materializeinc.slack.com/archives/C02FWJ94HME/p1711427166891969), calling this complete despite outstanding work items. #26165 fixed the bug that almost certainly led to this escalation, and we feel good about prioritizing the remaining work via the normal roadmap process.
