### ISSUE TITLE
[Epic] mz_now() UX improvements

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#26184]
## Product outcome

We should lean into
1) The EpochMillis Timestamp Oracle tracking ~system type
2) Making the UX of `mz_now()` (logical timestamp) in temporal filters as good as possible

### Rationale
Temporal filters are essential to customers’ use of Materialize as an ODW. The primary use cases are:

1) Limiting the amount of data pulled into materialized views, indexes, and queries to reduce resource usage. This is an essential use-case because we don’t support data expiration, so is the primary way we tell users to manage their growing data volumes.
2) Performing computations on a sliding window of recent data, because the use case only wants to consider recent data.
3) Apply a grace period. Users can set up a temporal filter to ignore events that arrive within a given grace period and only take action after the grace period has elapsed.

The use cases above all have some `event_ts` field in the user data, and all assume the mz timestamp of the data has a significant relationship to their `event_ts` field.

Materialize spent years attempting to make CDCv2 work (to allow users to bring their own timestamps from upstream), which is the “ideal” way of ensuring Materialize’s logical time is exactly lined up with the user’s event times. The takeaway was that, as it stands, its a) there are complexities in building a "good" solution (we don’t have a good story for 1) using CDCv2 with PostgreSQL/MySQL and 2) joining across different CDCv2 sources with different notions of time, and doing either of those things would be hard) and b) users in general don’t want to do the work to use it. While it’s likely we will *one day* find a way to allow users to bring their own timestamps to Materialize, we don't want to wait for that to happen.

As such, temporal filters, as we have them now, are the best solution.

Given that, we should prioritize efforts to make temporal filters as useful as possible.

### Braindump + extended conversations
https://www.notion.so/materialize/mz_now-braindump-3acde85e02d84cb09808d7c63dab009a

### Proposed changes details
https://www.notion.so/materialize/mz_now-braindump-3acde85e02d84cb09808d7c63dab009a?pvs=4#3a56d5b83d554ccfb630300b02ffe5aa

## Work items
```[tasklist]
- [ ] Support `timestamp` operations on `mz_now()` if casting `mz_timestamp` to `timestamp` and `timestamptz` is non-erroring
- [ ] Issue a notice when `mz_now()` is far into the future
- [ ] Update docs to highlight the different behavior of `mz_now()` in different isolation levels
```

Out of scope:
- Support `AS OF now()`
- Stricter enforcement around the EpochMillis Timestamp Oracle
- Rename mz_now() to something more explicit about the fact that it’s a logical timestamp
- New isolation levels
- Whether to expose the timestamp oracle time as a function
- Changes to `determine_timestamp`

## Decision log
 * **20 March 2024.** Adapter team met with Nikhil + Jessica to agree on work items

**Comment by chaas** [comment]
Customer ask to support `timestamp` operations on `mz_now()/allow anywhere in the temporal filter conditional for ease of reasoning https://materializeinc.slack.com/archives/C03REC5MEKU/p1718646062942029?thread_ts=1718645358.183079&cid=C03REC5MEKU
