### ISSUE TITLE
[Epic] Support region-allocated data in dataflows end-to-end

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#26891]
Related to #25286.

Change timely, differential, Materialize to support containers on dataflow edges. This enables us to use specific containers, such as `flatcontainer` that limit the amount of memory allocations shared between threads, and improve locality.

## Product outcome

Materialize uses less CPU cycles to compute a result.

## Work items

```[tasklist]
- [ ] https://github.com/TimelyDataflow/timely-dataflow/pull/562
- [ ] https://github.com/TimelyDataflow/timely-dataflow/pull/556
- [ ] https://github.com/TimelyDataflow/timely-dataflow/pull/541
- [ ] https://github.com/TimelyDataflow/differential-dataflow/pull/478
- [ ] https://github.com/TimelyDataflow/differential-dataflow/pull/474
```

## Decision log

* **1 January 1970.** Issue created.
