### ISSUE TITLE
[Epic] "Zero Downtime" Upgrades M1: Responsiveness

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#27406]
*Part of the "Zero Downtime" Upgrades epic (#22567).*

## Background

See the epic (#22567) and [(Internal) design doc](https://www.notion.so/materialize/Zero-Downtime-Upgrades-Milestone-1-f2817f1acaa34ab78c6df24e4b616601) for important background context.

## Goals

We define the goals in terms of what of responsiveness or freshness we want to provide for objects during or right after an upgrade.

- freshness for compute objects that don't transitively depend on sources
- responsiveness for compute objects that do transitively depend on sources
- the above two imply: cut connections over within reasonable time from old to new adapter processes

### August target

* 0dt deployment enabled for all staging
* 0dt deployment enabled for production canaries
* Have a plan of attack for enabling in risk-tolerant production regions. Open questions:
  * Builtin migrations (either a solution or agreement to punt)
  * Decide on promotion approach
    * Halt and restart (will likely require speeding up `envd` startup)
    * Graceful in-process promotion

## Side effects

- almost freshness for compute objects that transitively depend on PostgreSQL sources, MySQL sources, and Kafka sources using `ENVELOPE NONE`

This is not an explicit goal of this milestone, but something that falls out as a natural consequence of the work, as these source types rehydrate nearly instantly.

## Non-goals

Implicitly, everything not mentioned above, but explicitly:

- a consistent cut-over timestamp across all objects
- smart handling of behavior changes: changes to query plans, changes to builtin functions
- freshness for sources
- additional release verification (whatever that may be) during the upgrade process

```[tasklist]
## Work items
- [ ] https://github.com/MaterializeInc/materialize/issues/27688
- [ ] https://github.com/MaterializeInc/materialize/pull/27342
- [ ] https://github.com/MaterializeInc/materialize/pull/27695
- [ ] https://github.com/MaterializeInc/materialize/pull/27696
- [ ] https://github.com/MaterializeInc/cloud/pull/9595
- [ ] https://github.com/MaterializeInc/cloud/pull/9594
- [ ] https://github.com/MaterializeInc/materialize/pull/27559
- [ ] https://github.com/MaterializeInc/materialize/pull/27496
- [ ] https://github.com/MaterializeInc/materialize/pull/27738
- [ ] https://github.com/MaterializeInc/materialize/pull/27852
- [ ] https://github.com/MaterializeInc/materialize/pull/27819
- [ ] https://github.com/MaterializeInc/materialize/pull/27816
- [ ] https://github.com/MaterializeInc/materialize/pull/27836
- [ ] https://github.com/MaterializeInc/materialize/pull/27970
- [ ] https://github.com/MaterializeInc/materialize/pull/27971
- [ ] https://github.com/MaterializeInc/materialize/pull/27997
- [ ] https://github.com/MaterializeInc/materialize/issues/28151
- [ ] https://github.com/MaterializeInc/materialize/pull/28319
- [ ] https://github.com/MaterializeInc/materialize/pull/28396
- [ ] https://github.com/MaterializeInc/materialize/pull/28122
- [ ] https://github.com/MaterializeInc/materialize/pull/28464
- [ ] https://github.com/MaterializeInc/materialize/pull/28540
- [ ] https://github.com/MaterializeInc/cloud/pull/9806
- [ ] https://github.com/MaterializeInc/cloud/pull/9814
- [ ] #24844
- [ ] https://github.com/MaterializeInc/materialize/issues/27981
- [ ] https://github.com/MaterializeInc/materialize/issues/28575
- [ ] https://github.com/MaterializeInc/materialize/issues/28576
- [ ] https://github.com/MaterializeInc/materialize/issues/28440
- [ ] adapter: turn cluster/replica statuses into a (differential) storage-managed collection
- [ ] cloud: enhanced orchestration and metrics for zero-downtime upgrades?
```

```[tasklist]
## Bugs
- [ ] https://github.com/MaterializeInc/materialize/issues/28220
- [ ] https://github.com/MaterializeInc/materialize/issues/28219
- [ ] https://github.com/MaterializeInc/materialize/issues/28325
- [ ] https://github.com/MaterializeInc/materialize/issues/28339
- [ ] https://github.com/MaterializeInc/materialize/issues/28378
- [ ] https://github.com/MaterializeInc/materialize/issues/28570
```

**Comment by benesch** [comment]
Following up on this August target outcome:

> Decide on promotion approach

This was decided! We decided to go with the crash-and-restart approach.
