### ISSUE TITLE
mzbuild tracking issue

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2752]
A centralized issue for the known bugs and deficiencies in [mzbuild](https://github.com/MaterializeInc/materialize/tree/master/doc/developer/mzbuild.md). In loose priority order:

  * [x] Venv bootstrapping on a fresh install of Ubuntu is broken, because the venv ships without pip. Ubuntu prints a very helpful error message about the package you need to install (`python3-venv`, IIRC), but the venv that was originally created gets wedged into a permanently broken state, and needs to be removed with `rm -rf misc/python/venv`.

  * [ ] Error messages are bad. There is only the most minimal attempt to provide human-readable error messages. Most errors are exceptions that get raised and printed to the console with a backtrace.

  * [x] ~Compiling in Linux requires the large (\~2GB) CI builder Docker image. Perhaps we want to allow folks to use a cross-compiling toolchain that they have locally, to avoid the overhead of Docker. This requires a C/C++ toolchain that targets a glibc older than any glibc in our container images—whatever ships with ubuntu:bionic.~ Upon reflection, this isn't worth it.

**Comment by jakeswenson** [comment]
Can you update the link to mzbuild? I'd like to read more on it and it's currently broken.

**Comment by benesch** [comment]
Oops, sorry! Try now.

**Comment by benesch** [comment]
The error messages are much improved as of late, and we've got the right framework in place now to continue to improve them (`UIError`). I'm going to call this closed. We can continue to improve the error messages as we go.
