### ISSUE TITLE
[Epic] Optimization Notices -- short term

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#27713]
## Product outcome

We should show notices when we can clearly see that users could create better indexes. This will make the product easier to use.

This epic is just picking out a few work items from the many ideas in https://github.com/MaterializeInc/console/issues/549. These are the ideas that I think are not too hard to implement and will have a significant impact.

## Discovery

The selected issues have been seen occurring at customers repeatedly. Also, I know how to implement them, and they are not super complicated.

## Work items

```[tasklist]
- [ ] https://github.com/MaterializeInc/materialize/issues/21512
- [ ] https://github.com/MaterializeInc/materialize/issues/20802
- [ ] https://github.com/MaterializeInc/materialize/issues/22133
```

## Decision log

* **17 June 2024.** Issue created.
