### ISSUE TITLE
storage/sinks: FY2025Q2 urgent issues

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#27859]
## Overview

Tracking of urgent sink issues in FY2025Q2.

## Work items

* [ ] https://github.com/MaterializeInc/materialize/issues/25242
* [ ] https://github.com/MaterializeInc/materialize/pull/26423
* [ ] https://github.com/MaterializeInc/materialize/issues/27758
* [ ] https://github.com/MaterializeInc/materialize/issues/26787
* [ ] https://github.com/MaterializeInc/incidents-and-escalations/issues/33

**Comment by bosconi** [comment]
Assigning to me so I can track and prioritize this in GH project views.

**Comment by benesch** [comment]
@morsapaes what's the difference between "Backlog" and "Later"?

**Comment by morsapaes** [comment]
`Backlog` is for issues that are related to sink productionization, but that we haven't explicitly prioritized. It doesn't really matter, as long as we keep track of any relevant issues by linking them to this epic.
