### ISSUE TITLE
adapter,storage: adapt builtin and catalog migrations for 0dt upgrades

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#27981]
*Part of the "Zero Downtime" Upgrades M1: Responsiveness epic ([#27406](https://github.com/MaterializeInc/materialize/issues/27406)).*

## Description

We run various types of migrations during a version upgrade. Most of these migrations today assume a stop the world philosophy to version upgrades and expect to have exclusive access to the Materialize catalog while being run. To ship 0dt, we need to adapt each of these types of migrations to be compatible with the new 0dt deployment flow.

Some initial design thinking from @jkosh44 in: https://www.notion.so/materialize/Catalog-Migrations-b5e104417b5f44ac85513b7ef6eafdbd?showMoveTo=true&saveParent=true

## Work items

* [ ] https://github.com/MaterializeInc/materialize/issues/18767
* [x] https://github.com/MaterializeInc/materialize/pull/28118
* [x] https://github.com/MaterializeInc/materialize/pull/28122
* [x] https://github.com/MaterializeInc/materialize/pull/28266
* [x] https://github.com/MaterializeInc/materialize/pull/28124
* [x] https://github.com/MaterializeInc/materialize/pull/28434
* [x] https://github.com/MaterializeInc/materialize/pull/28643
* Additional items TODO

**Comment by jkosh44** [comment]
Migrated non-table storage collections (i.e. builtin sources) will be truncated, but we probably still need to advance their upper to some non-zero timestamp so they're reported as hydrated in read-only mode.
