### ISSUE TITLE
[Epic] Map SQL CTE and view names to MIR CTE names

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#28389]
To make EXPLAINs more valuable, we should make it easier to figure out which part of an EXPLAIN belongs to which parts of the original query.

Note that this will complement plan profiling (https://github.com/MaterializeInc/materialize/issues/21835): Plan profiling will automate mapping run-time information from dataflows to MIR, whereas the current issue will make it easier to map MIR to SQL.

Currently, the CTEs in MIR have no correspondence with SQL CTEs or views: views are inlined, and `RelationCSE`/`NormalizeLets` completely reshuffle the entire plan in terms of CTEs, making up new CTE names. So, the following needs to happen:
- [ ] SQL CTE names should be preserved during HIR planning.
- [ ] CTE names should be preserved during HIR-to-MIR lowering.
- [ ] View inlining should put the view names into the CTEs that it creates.
- [ ] CTEs that the HIR lowering comes up with (outer joins, global aggregates, subqueries, etc.) should include the surrounding CTE's name.
- [ ] MIR transforms (mainly `RelationCSE` and `NormalizeLets`, but there might be some others that manipulate CTEs) should keep track of the original CTE names, and relate the new CTEs back to the old ones. This can't simply be a one-to-one correspondence, so this requires some thinking. Maybe it will be a 1-to-many mapping from the new CTEs to old ones, and the name of each new CTE will involve the names of all original CTEs that contributed to it. This needs a bit of discovery/design work/experimentation.

**Comment by ggevay** [comment]
Relatedly, we could enhance arrangement names. Frank:
> ArrangeBy could have names explaining why they exist. Right now the names that are used just describe the expressions on which the thing is arranged, rather than `"foreign keys missing from <table>"`. It's unclear how easily we could do this, as we use things like Distinct that don't come with "hey, let's pick a name for me!" arguments.

**Comment by ggevay** [comment]
One big problem here is that if a CTE c1 is inlined, then we can't really do anything better than just adding it to the name of that CTE c2 that it was inlined into, but then things that were in c1 get smeared around all over c2.
