### ISSUE TITLE
[Epic] Source Versioning / Handling Source Schema Changes

### ISSUE THREAD

**Issue by rjobanp** [MaterializeInc/materialize#28430]
## Product outcome

Implement the design for source versioning outlined in https://github.com/MaterializeInc/materialize/pull/27907
[Rendered Design Doc](https://github.com/rjobanp/materialize/blob/subsource-deprecation-blue-green/doc/developer/design/20240625_source_versioning__table_from_sources.md)

## Discovery

Previous issues that are subsumed by this epic:
-   https://github.com/MaterializeInc/materialize/issues/20208
-   https://github.com/MaterializeInc/materialize/issues/24843
-   https://github.com/MaterializeInc/materialize/issues/17021

## Work items

```[tasklist]
- [ ] https://github.com/MaterializeInc/materialize/pull/27907
- [ ] https://github.com/MaterializeInc/materialize/pull/28125
- [ ] https://github.com/MaterializeInc/materialize/pull/28095
- [x] https://github.com/MaterializeInc/materialize/pull/28310 (Separate the planning of sources and subsources)
- [ ] storage/sources: Update the underlying `IngestionDesc`/`SourceDesc` and `SourceExport` structs to store each export's details and options on the `SourceExport` rather than the top-level `SourceDesc` (e.g. move `table_casts` and `text columns` to each `SourceExport`)
- [ ] storage/sources: Update source implementations to handle multiple `SourceExport`s ingesting the same upstream table using potentially different decodings
- [ ] storage/sources: Implement purification and planning for `CREATE TABLE .. FROM SOURCE`
- [ ] storage/sources: Update the storage controller to use both subsources and read-only tables as source_exports for existing multi-output sources
- [ ] storage/sources: Implement an opt-in migration to convert subsources to tables for postgres and mysql sources
- [ ] storage/sources: Restructure kafka source planning and rendering to use source_export structure
- [ ] storage/sources: Migrate kafka sources to use tables
- [ ] storage/sources: Remove subsource logic (purification, planning, parsing, etc)
```

## Decision log

* **July 2024.** Epic being actively worked on by @rjobanp .

**Comment by nrainer-materialize** [comment]
Issues:
* https://github.com/MaterializeInc/materialize/issues/29496
* https://github.com/MaterializeInc/materialize/issues/29498
