### ISSUE TITLE
[Epic] storage/sinks: support custom partitioning

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#28837]
## Notion epic

**Link:** https://www.notion.so/storage-sinks-support-custom-partitioning-f35bac62f0cf44ccac564a66686978a7
**Product brief:** 
**Status:** Done
**Prioritization:** 08 - August
**Estimated delivery date:** 2024-08-28

## Notion epic

**Link:** https://www.notion.so/storage-sinks-support-custom-partitioning-f35bac62f0cf44ccac564a66686978a7
**Product brief:** 
**Status:** In progress
**Prioritization:** 08 - August
**Estimated delivery date:** 2024-08-28

## Overview

Allow specifying the partitioning key for a Kafka sink. This gives users control over how messages are distributed across partitions in the sink topic, which has performance, availability and governance implications.

## Details

After #26423, we'll default sinks to a custom partitioning strategy that provides _some_ level of determinism, in comparison to the previous partitioning strategy (inherited from `librdkafka`). Although this is a strict improvement for some customers (_e.g._ those using Avro schema documentation), other customers need explicit control over the partitioniong keys.

@benesch pointed out a workaround for the tombstone limitation, in the meantime:

> One alternative that should work today is to make the property ID a Kafka header. That way it will still be attached when the value is a tombstone.

We should consider introducing an option that gives users complete control over the partition selection (_e.g._ `PARTITION USING (...)`).

## Work items

* [x] https://github.com/MaterializeInc/materialize/pull/28968
* [x] https://github.com/MaterializeInc/materialize/pull/29099
* [ ] https://github.com/MaterializeInc/materialize/pull/28972
* [x] https://github.com/MaterializeInc/materialize/pull/29102

**Comment by benesch** [comment]
Next PR in the series is up: https://github.com/MaterializeInc/materialize/pull/29099
