### ISSUE TITLE
Promote mz_kafka_sources from mz_internal to mz_catalog

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#29078]
```[tasklist]
### Tasks
- [x] Materialize repo PR
- [ ] ~Cloud Repo PR - need to coordinate rollout~ No longer needed since we're not promoting mz_cluster_replica_frontiers
- [x] Console Repo PR - conditional versioning
- [ ] ~Demos Repo PR~
- [ ] ~Benchmarking PR~ this repo is not actively maintained (https://github.com/MaterializeInc/letrec-bench)
- [ ] ~Accounts PR~ the customer script in the accounts repo is no longer used, replaced by dbt blue/green
```

**Comment by chaas** [comment]
@morsapaes as part of this effort, I noticed it'll affect one of Vivian's deployment scripts you checked in here 

https://github.com/MaterializeInc/accounts/blob/ae1898ed16b27d05d8280628e99a480b64d22376/vivian-health/deployment-scripts/create_test_model.py#L121

Should I update the checked in script? Do we need to notify Vivian?

**Comment by morsapaes** [comment]
I _think_ they ditched the scripts and started using the standard dbt workflow. It should be straightforward to confirm using the Metabase dashboard for blue/green deployments.

**Comment by chaas** [comment]
The customer has `"USES_BLUE_GREEN" == 1` in the metabase dashboard, so we're good then! That was a good suggestion

**Comment by chaas** [comment]
Update, we are no longer promoting `mz_cluster_replica_frontiers` because it's a builtin source that is uniquely used to power when the 0DT cutover happens. Promotion of this object will be tackled by pv2.
We also discovered a complication that builtin sources are truncated when changed, and the promotion is a change, so we may need special handling of builtin sources if we don't want truncation on promotion.

**Comment by chaas** [comment]
Additional update - we're also no longer promoting `mz_cluster_replica_metrics` and  `mz_cluster_replica_utilization` in this effort, since those will be handled as part of https://github.com/MaterializeInc/materialize/issues/28795.
