### ISSUE TITLE
[Epic] Outer join low-hanging fruits

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#29480]
## Overview

This issue is a collection of easy outer join work. It's a tiny subset of the outer join megatracker: https://github.com/MaterializeInc/materialize/issues/20830

## Work items

```[tasklist]
- [ ] https://github.com/MaterializeInc/materialize/issues/22320
- [ ] https://github.com/MaterializeInc/materialize/issues/22688
- [ ] https://github.com/MaterializeInc/materialize/issues/29255
```
