### ISSUE TITLE
Tracking issue for short / medium term things related to sinks

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2957]
There's a lot of work items that we need to tackle with sinks and its a little challenging to keep track of so I'm going to list them all in this issue. 

- [ ] https://github.com/MaterializeInc/materialize/issues/2958: More realistic nightly tests for sinks
- [ ] https://github.com/MaterializeInc/materialize/issues/2808: Currently sinks write to Kafka on a single thread, and also write a stream of data, rather than taking a structured batch. It's unclear if this is giving us any value and maybe we should switch to writing batches in parallel
- [x] https://github.com/MaterializeInc/materialize/issues/2862: CREATE SINK ... AS OF ...
- [ ] https://github.com/MaterializeInc/materialize/issues/1576: Specify keys and metadata when creating Kafka Sinks
- [ ] https://github.com/MaterializeInc/materialize/issues/3216: Add data valid from/to
- [x] https://github.com/MaterializeInc/materialize/issues/2806: Loss of interactivity when creating a sink. This has gotten a lot better with recent improvements to how we write out to Kafka but it still grows linearly with the size of the topic. It's also unclear how this is for Avro OCF sinks at the moment
- [x] https://github.com/MaterializeInc/materialize/issues/2860: Make it so we don't try to flush a sink when we drop it. This one might not sound that important but I think its actually really critical to have for scenarios where the downstream broker is running into issues
- [x] https://github.com/MaterializeInc/materialize/issues/2956: Grafana metrics for sinks
- [x] https://github.com/MaterializeInc/materialize/issues/1539: Better runtime error handling for sinks. Currently we log these to the error log but we should also add them to the errors collection / for some errors pause and retry sending the message.

Not on this list but known larger issues

- [ ] https://github.com/MaterializeInc/materialize/issues/2915: Make it so we can reuse the same topic for sinks. This requires a larger rethink and we should probably wait until source persistence has landed?
- [ ] https://github.com/MaterializeInc/materialize/issues/1541: protobuf data to sinks requires a large number of features that don't currently exist in serde_protobuf

**Comment by cuongdo** [comment]
@ruchirK This is a useful list. I've converted the bulleted lists to checklists. Aside from the ability to check off items, this also allows items to be easily rearranged according to priority.

What is your rough priority order for these sink tasks?

**Comment by ruchirK** [comment]
Reordered in what I think is a decent priority order and order to do work in from an engineering point of view

**Comment by frankmcsherry** [comment]
Thanks @ruchirK! Some quick comments / thoughts:
1. #2860 isn't about blocking on flushes, it is about doing flushes at all afaict. We currently flush in another thread, which shouldn't block anything.
2. #2915 probably doesn't need source persistence to land, but it doesn't make sense to work too hard on it without some contract from the user that they have persistent timestamped source data. But if that is the case, then we should produce the same output on replay and can at the least just subtract out everything that has been made visible downstream in the sink.  Do you recall what needed to be re-thought? (( my recollection: doing it well / going fast requires help, but doing it at all didn't seem too bad? ))
3. > protobuf data to sinks requires a large

    large what?

**Comment by ruchirK** [comment]
> #2860 isn't about blocking on flushes, it is about doing flushes at all afaict. We currently flush in another thread, which shouldn't block anything.

Yup yup I just spaced while writing the summary. Thanks for the catch!

> #2915 probably doesn't need source persistence to land, but it doesn't make sense to work too hard on it without some contract from the user that they have persistent timestamped source data.

Your recollection seems right, though from what I remember the biggest open question (not necessarily the hardest one) was around what should the output look like (i.e. (row, timestamp, diff) is one way that would make subtracting everything downstream easy but unclear if that's something people will want to use / maybe we could inject the materialize timestamp as a field in the result avro schema?)

Also probably good to try to validate with product whether subtracting everything out on restart is something clients will be ok with?

**Comment by frankmcsherry** [comment]
> Also probably good to try to validate with product whether subtracting everything out on restart is something clients will be ok with?

Fwiw, I think this can be invisible to the client. On restart (and presuming durably recorded timestamps on inputs) each **SINK**
1. Re-reads what it has written, negates each message, and buffers that as part of its output.
2. As data complete from its normal input channel, the negated input are added to it, and (if everything goes according to plan) it only writes down novel changes.

A different take is that every SINK could be re-written as a function of inputs normal stream `output` as well as a new SOURCE `prior_output` that effectively has `(tail = false)` where we write
```rust
let actual_output = output.concat(&prior_output.negate());
sink(actual_output);
```
I think we could do this today, but we'd have to make sure we are paying attention to determinism throughput (could be a fun exercise).

**Comment by frankmcsherry** [comment]
@ruchirK I have another sink issue for you, which might be part of the CDC for Materialize issue (#2221): We probably want sink data to reveal progress information. This could be one of a. sink data are written in timestamp order, or b. sink data are written as batches, or perhaps c. a consistency topic (I prefer this one less than b., but it might integrate better with what we have now).

**Comment by ruchirK** [comment]
I thought about this a bunch over the past two days -- I think theres a way we can do this in avro where we stash the message timestamp as part of an extra field in our avro output (outside of the diff envelope). I think Debezium gives us a fair amount of precedent for doing that. At that point, our records are essentially (row, timestamp, +/- 1) but we replicate the actual diff in unary. Now we would need to store which batches we had written down separately (to recover without having to load in the entire topic) but crucially we wouldn't have to store the mapping between offsets in our kafka topic and message timestamps (which as far as I can tell will get tricky really fast if we ever want to have > 1 writer per output partition). This maps most closely to approach b above, but its a lot more lightweight in that a. we can reuse most of what we do for avro, and the information about which batches are written down is not tightly coupled to where physically in the kafka topic it is

The big downside to that kind of approach is that it doesn't map to how we read in consistency information for sources at all :|

**Comment by frankmcsherry** [comment]
> The big downside to that kind of approach is that it doesn't map to how we read in consistency information for sources at all :|

I think we should fix this. It's not SINK related, but we should be able to abstract out the way in which consistency information comes at the sources to prevent blocking otherwise sane work.

**Comment by ruchirK** [comment]
> I think we should fix this. It's not SINK related, but we should be able to abstract out the way in which consistency information comes at the sources to prevent blocking otherwise sane work.

Agreed (though not sure how to best achieve that). Aside from that does my proposal for sink persistence seem roughly sane?

**Comment by cuongdo** [comment]
@ruchirK Could you clearly indicate which of these tasks you believe *must* be part of 0.4.0? Our goal is to release in the next 2-3 weeks. We use the `M-milestone-blocker` label to denote that. It's up to you whether that label should apply to this task or the individual items on this list.

**Comment by ruchirK** [comment]
In my opinion the only other must-release task is some flavor of support for #3216 which is going to be addressed in a preliminary way by #3458 (I think at that point it makes sense to close both and make separate issues for future changes in the design)

**Comment by cuongdo** [comment]
@ruchirK I'm closing this issue, because I believe it's served its purpose. I've added a new `A-sinks` label to all issues that you referenced from this issue, so that the issues are discoverable. Because we can set independent priorities and labels for each of the `A-sinks` issues, I don't believe we're losing any flexibility or information.
