### ISSUE TITLE
Tracking issue for source persistence work

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#3305]
Pretty much exactly what the name implies

- [ ] RowWriter implementation + RowReader implementation. We need to be able to write down files of length prefixed Rows and read them back in. Test by confirming that writing -> reading is identity
- [ ] use RowWriter to write down pairs of (data), (offset, timestamp, diff) -- each thing in parentheses can be a Row. Need to buffer to some extent to avoid spamming the file system. Let's not bother appending to a file and instead just write to new files as we read more
- [ ] write a separate Rust program that can take in these pairs and collate them to figure out a complete prefix of offsets. This should probably have its own unit tests. Also maybe it should be aware of its prior outputs so that it doesn't output old offsets every time. Note that this also needs some way of being "catalog-aware" - to be able to know which sources to continue to persist vs which ones to disregard
- [ ] use RowReader to read in old complete prefixes and pass a starting offset to the Kafka client. Note that here we need to handle cases like "there's no data over here" or "this data is all corrupt".  Unclear also how we will be downgrading capabilities for the set of offsets for which we persisted data.

Open problems that I don't exactly know how to solve yet:

- [ ] Materialize crashes in the middle of writing something down
- [ ] CREATE SOURCE / DELETE SOURCE / CREATE SOURCE hot loop
- [ ] Materialize restarts with a different number of threads than it originally ran with

And to be very clear - punting on compaction of persisted data for now

Initial issue with user stories: https://github.com/MaterializeInc/materialize/issues/1182

**Comment by cuongdo** [comment]
@ruchirK @justinj is this list still current? do you intend to complete all of these during 0.5 development?

**Comment by justinj** [comment]
This design is a little outdated. I'm not sure if Ruchir has a written up version of the current design anywhere, but I think morally the things this list was accomplishing are still intended to be done for 0.5.

**Comment by ruchirK** [comment]
Closing this because roughly everything in this task has now been completed. I'm going to write up a bunch of followup tickets with the A-persistence label to track specific next steps
