### ISSUE TITLE
[tracking] consistency: make SQL transactions serializable/linearizable

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#5073]
This is a meta issue that will hopefully track ongoing work to achieve our goal of serializable SQL transactions. Our goal is not to become a transactional database of record. Rather, it is to be a fast and correct incrementally updated view engine. A user of our system that expects it to have similar semantics to Postgres will thus expect that SQL transactions do what they are advertised to do: provide the documented level of consistency and error if they cannot. Our consistency target is serializable. We will aim to have our txns work as documented for read-only workloads.

Below is some known work in order to reach this goal.

- [x] Change txns to be read-only. Currently our txns don't really do anything besides set the "I'm in a txn" bit. Change them to reject SQL statements that are not read queries (SELECT, TAIL) or session accessors (DECLARE, FETCH, SET). DECLARE and FETCH already only work in txns since all portals (DECLAREs) are destroyed at the end of a txn.
- [x] Do something to fix a txn's read timestamp such that all queries in the txn all use the same timestamp. See https://github.com/MaterializeInc/materialize/pull/4625 for one approach. Currently we do not guarantee anything about this and so the timestamp can move around based on the tables in the query.
- [x] Audit SQL functions like `now` to make sure they act correctly within transactions. Figure out if there are more of these that need to be fixed.
- [x] Decide if and how to implement time domains. We would like txns to be serializable by default, with maybe the user option to downgrade to a lower level if requested in order to achieve more performance or some other goal. For a txn to provide that (serializable), it must know all of the tables from which it will read before it reads from them so it can prevent them from being compacted after a timestamp. We would like to not force users to tell us this at the beginning of every transaction since some ORMs or tools might not be able to support the extended syntax this would require. Instead, do something where, say, "all tables in a database/schema are in the same time domain", and a time domain is a thing that compacts all tables in it at the same rate. Time domains should also probably be user-definable and removable (i.e., can remove the default which puts all tables in the same db in the same time domain).
- [ ] Decide on and implement a strategy for handling timestamps on different sessions. Should two separate sessions have some kind of defined relationship where the timestamp selected by a txn in one session is guaranteed to be higher than a timestamp from a txn of another session that started at a lower wall-clock time?
- [x] Figure out how BYO and debezium consistency topics (i.e., some kind of external transaction ordering info) should work with linearizability.
- [ ] Run jepsen ourselves to attempt to verify some of this.
- [ ] #7323
  - [x] INSERTs not persisted between restarts
  - [ ] non-determinism in source reading (I think this is the "different views over the same non-materialized source can generate different timestamps"). I'm not clear on exactly how of if this breaks serializability. Maybe it's similar to inserts because things can change on restart?
  - [ ] Other stuff?
- [x] #6747

**Comment by benesch** [comment]
Superseded by #11631.
