### ISSUE TITLE
Authentication epic

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5735]
## Background

Basic support for securing Materialize's network interface landed in #5620. Secure mode today is based on TLS to provide both encryption and authentication via client certificates. Materialize supports a basic notion of roles, via `CREATE ROLE`, that make it possible to revoke a user's access to the cluster via `DROP ROLE`.

Based on discussion in #4626, a number of folks have concerns about the burden of managing TLS certificates. Password authentication is the requested alternative.

TLS and password authentication are not mutually exclusive. When using password authentication, you typically still want to use TLS to provide _encryption_. In PostgreSQL, you can even require _both_ TLS and password authentication, if you like. 

Supporting password authentication will be a good chunk of work. It's not that `ALTER ROLE ... SET PASSWORD` is hard, or that verifying passwords on connection is hard, but that exposing the right configuration knobs to the user is rather involved.

## Plan

We'll use PostgreSQL's SCRAM-SHA-256 password encryption scheme, since the alternative (MD5) is terribly insecure. Tasks, in no particular order or consistent granularity:

* [ ] Support creating and setting passwords with `{CREATE | ALTER} USER ... PASSWORD <pass>`. 

* [ ] Add a command-line option like `--password-auth` that requires password authentication. This setting is entirely orthogonal to the `--tls-mode` setting. You can require passwords without TLS, or you can require both passwords and TLS authentication.

* [ ] Support the `scram-sha-256` password authentication method in the pgwire protocol.

* [ ] Figure out how to support passwords for the HTTP interface. A login form? HTTP basic + TLS encryption? Unfortunately there's no (reasonable) way to do SCRAM-SHA-256 over HTTP to allow securely performing password auth over untrusted connections.

* [ ] Decide if we want to support something like [pg_hba.conf](https://www.google.com/search?client=safari&rls=en&q=pg_hba&ie=UTF-8&oe=UTF-8) (per @mjibson) to allow finer-grained control over authentication methods _per_ protocol. pg_hba.conf allows you to express, for example, that HTTP connections via localhost are permitted without authentication, but TLS + password auth is required for HTTP connections from elsewhere, and TLS certificate auth without passwords is required for pgwire connections.

/cc @krishmanoh2 @umanwizard @cirego @benLogN @mjibson

**Comment by mjibson** [comment]
pg_hba.conf also allows limiting which users can use which connection method, making it easier to separate auth methods for pgwire and http (say, if http only allowed a single user).

Is there a problem limiting md5 password auth to only over TLS? I've understood that to be "secure enough".

**Comment by cirego** [comment]
For the HTTP interface, I would recommend using something like JSON web tokens (https://jwt.io/), although that requires standing up a separate authentication service. But, for better or worse, JWT are well known and are supported in a variety of libraries.

**Comment by benesch** [comment]
> Is there a problem limiting md5 password auth to only over TLS? I've understood that to be "secure enough".

My issue with supporting md5-based encryption is that it's just a pretty bad look. Indeed, as long as you're transmitted the passwords over a TLS-encrypted connection you don't need to worry about someone sniffing the password. But transmitting the passwords in plaintext would be exactly as secure, given how broken md5 is; going to the trouble of md5'ing them implies you have no idea what you're doing, and then you have to explain to people that you're just copying this sort of broken but still ok thing from Postgres...

There's also the issue that to support md5 auth you need to _store_ the passwords on the server in md5, so if mzdata/catalog gets leaked, you've essentially leaked everyone's passwords, because md5 is so easy to crack. Not to mention that Postgres decided to use the username in the input to the hash, and so you can't rename users without breaking their passwords if you use md5 passwords.

Peter Eisentraut has a great blog post on all the ways they messed up auth in PostgreSQL: https://www.2ndquadrant.com/en/blog/password-authentication-methods-in-postgresql/

SCRAM is actually good and permits plugging in new hashes if SHA-256 gets broken, so that's definitely my preference even though it's much harder than plaintext or md5 passwords.

**Comment by mjibson** [comment]
Are there known application/user constraints here? I guess: is there anyone who wants to use mz and does not support SCRAM?

Regarding HTTP, we may want to figure out who the HTTP endpoint would be for, and then figure out how/if auth should fit into that. Is it just humans browsing the few pages we have, or do we expect to add a production endpoint for data consumption?

**Comment by benesch** [comment]
> For the HTTP interface, I would recommend using something like JSON web tokens (https://jwt.io/), although that requires standing up a separate authentication service. But, for better or worse, JWT are well known and are supported in a variety of libraries.
> 
> The basic workflow looks like this:
> 
> 1. Client requests JWT from authentication service
> 2. Client makes request to `materialized`, setting an `Authorization: Bearer <foo>` header
> 3. Materialized validates the JWT signature and TTL and returns the appropriate response.

I'm afraid I don't follow how this would help us out! We're the ones providing the authentication service because we're the ones maintaining the list of users (via `CREATE USER`). I suppose our HTTP interface could issue JWTs via some authentication endpoint and require valid JWTs to access all others, but seems rather roundabout. We could just generate some random data to use as a `Bearer` tokens rather than JWTs.

> Are there known application/user constraints here? I guess: is there anyone who wants to use mz and does not support SCRAM?

There may have been a few years ago, but I haven't been able to find any PostgreSQL drivers that don't support SCRAM these days. I guess if someone was using an ancient version of some driver. But I can't really imagine that someone would both want to use a new technology like Materialize and insist upon using some ancient PostgreSQL driver with it.

> Regarding HTTP, we may want to figure out who the HTTP endpoint would be for, and then figure out how/if auth should fit into that. Is it just humans browsing the few pages we have, or do we expect to add a production endpoint for data consumption?

We already have a production endpoint for data consumption, `/metrics`, which Prometheus scrapes. (Pretty sure Prometheus can use TLS auth, though I haven't actually tried.) The problem is the rest of the endpoints, which are for humans, and browsers pretty much don't support TLS auth. If someone wants to look at the HTTPS interface in `verify` mode right now, they're not gonna have a fun time.

I think we'll probably want both a cookie-based session strategy for humans browsing the UI, with a login form, and a separate HTTP Basic-style mechanism for authenticating the programmatic endpoints.

**Comment by krishmanoh2** [comment]
pg_hba.conf would be preferable to have. This would allow for maintenance as needed without needing to know the password.

**Comment by quodlibetor** [comment]
Sorry if I'm missing context and this isn't useful, but, re:

> Unfortunately there's no (reasonable) way to do SCRAM-SHA-256 over HTTP to allow securely performing password auth over untrusted connections.

My understanding of this is that we are looking for a way for users to send us passwords over the open web, without them needing to set up a client certificate? If that's the case, we should be able to set up an [AWS NLB with its own TLS cert for e.g. cloud.materialize.com](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html), and tell clients to connect to that using their existing certificate store. That would depend on clients not requiring the mz server itself to be the TLS terminator -- I'm not sure how client-side TLS works in postgres, so I'm not sure if that'd work.

**Comment by quodlibetor** [comment]
However an NLB/ALB TLS terminator will definitely work for encrypting passwords in-flight to the HTTP interface.

**Comment by benesch** [comment]
I think the design of authenticating the HTTP interface is more of a UX question rather than a technical question. We can certainly use HTTP Basic authentication, which will be secure as long as you have enabled TLS encryption (no client certificate required). That'll work plenty well for e.g. Prometheus. But Basic auth forms just _look_ janky, so we might want to consider having a proper login form that uses session cookies, for example.

**Comment by mkysel** [comment]
Putting on my security hat, here are a few questions I would pose:
- what is the enforced password strength? Can I enforce a certain minimum requirement in my installation to meet my corporate requirements?
- What is the support for password rotation? Do I have to manage that in a separate system, or can MZ do that for me?
- When a password gets compromised, how easy is it for the DevSecOps team to revoke it?
- When a password gets changed or revoked: What happens to the existing connections? Do they get killed? Does the change take effect on the next login?
- How do I change the password without application downtime?
- can I store the passwords in a separate system? (most likely LDAP, SSO, Okta...)
- what if I have a malicious actor in my enterprise that has been fired and changed all passwords. How do I recover the data stored in MZ? What is the "master password reset button"?
- what level of audit logging is supported? How observable is the system?

A few other relevant topics:
- who or what is the "primordial user". Do we automatically create one? If so, what do we do with its password? If not, do we make creating the first DB a 2 step process? 1) create DB 2) log in and create a master password?
- how do we keep the passwords between the cloud and the instance in sync? Is there a noticeable delay in replication? What are the failure modes?
- can a user have both a client x509 certificate and a password? Can the admin configure the requirements?

**Comment by benesch** [comment]
Ok, so I think we should go with roughly the plan laid out in the issue description for now. We have some gnarly user authentication integration questions to sort out in cloud already; I don't think supporting password authentication really makes the situation any worse. 

To try to cover both the design of the `materialized` feature and the cloud integration:

  * We add the `{CREATE | ALTER} ROLE ... WITH PASSWORD <pass>` statements to support creating/altering users with passwords. The default password is `NULL` (this comes from PostgreSQL), and indicates that you cannot log in as that user with a password.
  * Passwords are always required for users that have them. If you've specified `--tls-mode=verify-ca` or `--tls-mode=verify-full`, the password will be verified in _addition_ to the TLS certificate. 
  * Cloud deployments will allow users to change the TLS mode from `--tls-mode=verify-full` to `--tls-mode=required`. 

That means the process of configuring a Materialize Cloud instance to accept password authentication looks like this:

1. Create a new deployment in `--tls-mode=verify-full` mode.
2. Connect once with a TLS client certificate and set a password for the `materialize` user.
3. Restart the deployment in `--tls-mode=required` mode.
4. Connect with the password and no TLS certificate.

That's definitely too many steps. But! We can wrap that up in a nice cloud UI or API call. Imagine we add an "Enable password authentication" dialog that does steps 2 and 3 automatically. That would alleviate the pain and I think the cloud backend is well positioned as of recently to do that sort of stuff.

(Note: what we definitely _don't_ want to do is introduce a CLI flag like`--bootstrap-password=PASS` or somesuch. CLI flags get stored in various places in Kubernetes and are visible to other processes on the machine etc etc. So the most secure way to do this is to just connect to the `materialized` process and issue the `ALTER USER` command. The SCRAM protocol ensures that we never actually store anything sensitive related to the password, which is awesome.)

cc @mjibson @andrioni @TonyRippy

**Comment by benesch** [comment]
> Putting on my security hat, here are a few questions I would pose:

Responses inline.

> * what is the enforced password strength? Can I enforce a certain minimum requirement in my installation to meet my corporate requirements?
> * What is the support for password rotation? Do I have to manage that in a separate system, or can MZ do that for me?
> * When a password gets compromised, how easy is it for the DevSecOps team to revoke it?
> * When a password gets changed or revoked: What happens to the existing connections? Do they get killed? Does the change take effect on the next login?
> * How do I change the password without application downtime?

All of these are questions that will come up, but I think we can punt on these for now. PostgreSQL's answers to all of these is "no" or "it's hard" or "you can't". I think it's fine to have the same answer for now.

> * can I store the passwords in a separate system? (most likely LDAP, SSO, Okta...)

This is something that I think we can punt to when we design a proper authentication integration between Materialize Cloud and `materialized`. The auth provider we use for Materialize Cloud (Frontegg) already has these sorts of SSO integrations, so our challenge is only to integrate Frontegg with `materialized`.

> * what if I have a malicious actor in my enterprise that has been fired and changed all passwords. How do I recover the data stored in MZ? What is the "master password reset button"?

Contact support. :D


> * what level of audit logging is supported? How observable is the system?

> * who or what is the "primordial user". Do we automatically create one? If so, what do we do with its password? If not, do we make creating the first DB a 2 step process? 1) create DB 2) log in and create a master password?

The username is called `materialize` and it automatically exists. My proposal above is that setting a password for this user requires first logging in with a TLS client certificate, but it can be the cloud backend that does this bootstrapping rather than the end user.

> * how do we keep the passwords between the cloud and the instance in sync? Is there a noticeable delay in replication? What are the failure modes?

Yeah, this is hard, but I think we can punt it to the Platform.

> * can a user have both a client x509 certificate and a password? Can the admin configure the requirements?

Yes and yes (see above proposal).

**Comment by mkysel** [comment]
I saw `--tls-mode=verify-ca` in the post above so I found my hat again! Let's focus on the CA here. CAs are really cool, but also overly complicated.
- is there a relationship between server-side certificates and client certificates? Can they both be signed by the same CA?
- is there a global CA specified by the cloud product and all customer certificates are derived from that CA? Or more likely a CA per customer?
- Do we plan on providing well-known CA certificate chains that do not require any additional installation on customer machines? (the way websites are signed and the well-known CAs are already pre-configured on user machines). This would mostly apply to server-side certificates.
- When using a CA, can you revoke a single derived compromised certificate? Is there a blacklist/revocation-list? Can you DDoS the blacklist?
- Who is responsible for managing the CA keys and signing processes?
- What is the expected CA expiration duration? (again, rotation comes into play) Is it configurable?

**Comment by benesch** [comment]
> Let's focus on the CA here. 

Can you file a different issue for the CA questions? I'd like to focus here on the specific issue of how to deliver username/password authentication for our existing cloud customers as quickly as possible.

**Comment by mjibson** [comment]
Are these three scenarios correct?

- client connects without a cert: must use scram auth with a user that has a password
- client connects with a cert requesting a username with no password: cert username must match requested user
- client connects with a cert requesting a username with a password: cert username is ignored, must scram auth for requested user

**Comment by benesch** [comment]
I was thinking something slightly different. Whether or not a cert is required is entirely determined by the `--tls-mode` flag. Whether or not a password is required is entirely determined by whether there is a password on the account. 

So if you connect without a cert, you'll be rejected by the TLS auth layer if `--tls-mode=verify-ca|verify-full`. If you make it through that, password authentication proceeds according to whether there is (or isn't) a password on the desired account.

If you connect with a cert, the TLS auth layer with either verify the username in the cert if the TLS mode is `verify-full`, or just verify the CA if the TLS mode is `verify-ca`. Then you may have to auth with a password too, depending on whether the account you're connecting to has a password.

**Comment by mjibson** [comment]
I had some confusion because I didn't realize `--tls-mode` is a server cli option. I'm on board now.

**Comment by benesch** [comment]
Closing as stale. Since switching to platform, we support username/password authentication via Frontegg, and no longer need to support other authentication options.
