### ISSUE TITLE
[Tracking] postgres replication [0.8 milestone]

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#5971]
## What's in scope
* Support `CREATE SOURCES FROM POSTGRES` statements that sync all the tables of an upstream publication
* Initially, all tables will be realized as materialized sources

# MVP Tasks
- [x] Upstream support for replication stream in `rust-postgres` (PR is up https://github.com/sfackler/rust-postgres/pull/752)
- [x] Add syntax for `CREATE SOURCES` (plural) requiring fully qualified table definitions (#6299)
- [x] Support dynamically fetching schema in `CREATE SOURCE` if omitted during purification (https://github.com/MaterializeInc/materialize/pull/6207)
- [x] Implement the dataflow end of `CREATE SOURCES` (plural), making sure we only use a single replication stream (#6582)
- [x] Allow users to select which tables they want from an upstream publication (https://github.com/MaterializeInc/materialize/pull/6299)
- [x] Allow users to selectively drop specific tables **after** having run the `CREATE SOURCES` statement (https://github.com/MaterializeInc/materialize/pull/6299)
- [x] Documentation (#7017)
- [ ] Record upstream OIDs during purification to detect schema changes
- [x] Support for TLS connections (#6716)

## Tasks
- [x] Validate `CREATE SOURCE` statement options before returning to the user during purification
- [x] Cleanup upstream resources after `DROP SOURCE` (#6785)
- [x] Recovery from disconnection events during replication phase (https://github.com/MaterializeInc/materialize/pull/6477)
- [x] Surface replication errors into the sources
- [x] Propagate primary key information from postgres into the source (#6338)
- [ ] #7869
- [x] Fix https://github.com/MaterializeInc/materialize/issues/6600 (support timestamptz)
- [x] Handle disconnections during initial table sync (#6799)

## Out of scope / Future work
* Support non-materialized tables that when requested they automatically spin up a replication stream, catch up to the main one and join it

**Comment by petrosagg** [comment]
https://github.com/MaterializeInc/materialize/issues/6600

**Comment by videni** [comment]
Hope this can be resolved soon, need this feature badly

**Comment by petrosagg** [comment]
@videni the feature is included in the 0.8 release (that got out just yesterday!) behind the experimental flag! So you can just download the new binary and try it out :) 

We're in the process of finalizing documentation here https://github.com/MaterializeInc/materialize/pull/7017

**Comment by videni** [comment]
@petrosagg  , thanks for your quick reminder.

**Comment by benesch** [comment]
@petrosagg are the two remaining issues important?

**Comment by petrosagg** [comment]
I created an issue for the timeline one, I think we can close this tracking issue
