### ISSUE TITLE
release: Automation Long Term Goal

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5987]
This captures my thinking about what the best possible state for our release process could be. The first section describes the ideal workflow, and the second section is a checklist of things that we need to accomplish to get there.

## Ideal Workflow

For context, see the current release checklist (https://github.com/MaterializeInc/materialize/issues/5959) which has 39 checkboxes on it.

1. [human] A Materialize engineer chooses a commit to base the release off of and performs an
   action (runs a script/clicks a button) which creates all of the initial artifacts in the
   materialize repo, most importantly the release tag and a release checklist issue.
2. [machine] The tag existing in the repo automatically triggers: all the release qualification
   steps (currently the full SQL Logic Tests and several load tests) with useful direct links to
   them automatically getting sent to appropriate channels (slack and/or github)
   1. Even better would be if we have a dashboard that includes all links for all previous
      releases to make comparison easy.
3. [machine] Automatic release qualification is performed and sent to the same channels, in
   particular:
   * statistical performance similarity to/divergence from the previous release along
     various axes is automatically reported
   * correctness checks (standard test suite and full SLT) are linked to and called out
4. [human] A validity check of the qualification metrics in our dashboard is also performed
5. [human] A the final release is tagged via a script, which triggers the various remaining
   artifacts to be created: apt/homebrew packages, release page in github.

## Steps to get there

Numbers correspond to the workflow steps above, several of these steps have alternate options for
implementation, and this isn't prescriptive or against future changes to the set of things that we use for release qualification (e.g. if we add benchmarking as part of release qualification), this is just how I'm thinking of it right now:

1. Improvements to release script
   - [ ] mkrelease should create the initial issue
   - [ ] mkrelease should only require one command (currently it's 3) to create and integrate the
         release tag
2. Automate the release qualification
   - [ ] automatically run SLTs (plausibly just a buildkite config change)
     - [ ] automatically link to the qualification SLT from the github issue
     - [ ] auto-link the commit test suite from the github issue
   - [ ] create a service that listens for github tags and automatically spins up qualification
         LTs, and sends links to their dashboards to various places
     - [ ] A step on the way to this is creating a script that can auto-generate these links,
           there exist good prometheus client libraries ([particularly for
           go](https://github.com/prometheus/client_golang)) and our prometheus schema is designed
           to support efficiently linking to these items.
     - [ ] any service that can do those things can easily provide a dashboard of all previous
           qualification runs, which would be nice.
   - [ ] Automatic release qualification can be performed in two ways:
     * Just by creating prometheus/grafana alerts for static values -- this is worth doing
       independently, as they can trigger if any nightly fails.
     * Using the same prometheus client library as auto-linking -- checking things like
       min/max/avg query latencies, ingest/sink rates, all the things that re currently eyeballed
       as part of the release process.
   - [ ] automatically deprovision any infrastructure that was created for qualification
3. The validity check doesn't need to change, but it will be much easier if direct comparison
   links are available.
4. Improvements to the release finalization:
   1. Improvements to the release script:
      - [ ] automatically updating the release page in github with the template that's currently in
            the release checklist
      - [ ] the final tagging also takes several steps, but could be reduced to 1
   2. Improvements to artifact creation
      - [ ] homebrew package should be auto-created on the final release tag

Orthogonal to those changes, we should improve the alerting on nightlies more, such that release
qualification is never (or almost never) slowed down due to changes in materialized -- ideally all
release-related issues are caught within 24 hours, due to nightly runs.

Related to #3018

**Comment by benesch** [comment]
We'll have to rethink this all for platform, so closing out.
