### ISSUE TITLE
[Epic] Surface connector errors (and consistent policy for errors/retries to external systems)

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#7115]
Materialize has accumulated a long list of external systems that it interacts with. Most of these were integrated with fairly ad-hoc error/retry policies, so failures are surfaced in different ways or throw materialize into different states.

Some recent examples of issues we've found include:
https://github.com/MaterializeInc/materialize/issues/7035
https://github.com/MaterializeInc/materialize/issues/7009
https://github.com/MaterializeInc/materialize/issues/6586
https://github.com/MaterializeInc/materialize/issues/7107

We should:
1. Decide what our general error and retry policy should be for sources/sinks integrations. This involves both how the system behaves (retry infinitely or set amount, on what schedule) and how it's presented to the user (logging, erroring out the source, un-erroring or restarting the source once the error has recovered). It's important to keep the UX of cloud in mind as well (should errors/error state be surfaced in an mz internal table instead of only logs).
2. Decide what our general error and retry policy should be for failures during purification.
3. After settling on 1/2, make separate tasks for bringing the current source/sink implementations into sync with the spec.

A current list of concrete areas that need to be considered (courtesy Philip):
- Scanning an S3 bucket over HTTP
- Fetching keys from S3 over HTTP
- Receiving SQS notifications
- Reading/writing from Kafka topics (main topic, txn topic, debezium metadata topic)
- Readaing/writing from the schema registry
- Postgres snapshot and ongoing replication
- External calls happening during purification
- File I/O
- REST API calls to Pubnub
- Kinesis
- HTTP calls for SSE (not merged)

This work falls under hardening for 1.0.

## Implementation
**Design document:** [20210728_error_handling_surfacing_connector_failures.md](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20210728_error_handling_surfacing_connector_failures.md)

### Sub-tasks

- [x] #7804
- [x] Surface connector errors (from sources/sinks) in a new system view/source
- [x] #7805
- [x] #7803
- [x] #7806
- [x] #7807
- [x] muse: add "depends_on" to `mz_views` which allows finding the indexes that a view depends on. This would then allow checking the error status for a view
- [x] Decide if we want to report ongoing TAILs as a sink in system tables
- [x] Report connector as `DEGRADED` when in a transient failure state
- [x] When restarting, mark individual connectors as FAILED instead of panicking
- [x] ~~#11669~~ (now linked under the Debezium Correctness EPIC: https://github.com/MaterializeInc/materialize/issues/11772
### Testing tasks

- [x] ~~confirm that all errors listed above are handled as expected~~ (too broad)

### Bugs

 - [x] #6285
 - [x] ~~#6292~~ handed off to compute team
 - [x] #6293
 - [x] #7396
 - [x] ~~#7009~~ now tracked in https://github.com/MaterializeInc/materialize/issues/14105
 - [x] #6586
 - [x] ~~#7035~~ moved to Icebox because the issue does not show up in production and has not been reproduced
 - [x] #6916
 - [x] #10269 
 - [x] #12389
 - [x] #9242
 - [x] #12450 - an unreadable source in the catalog causes failure to startup rather than surfacing a recoverable error
 - [x] #12091 - a panicking dataflow causes a crash loop that requires an explicit DROP VIEW to recover from, instead of just an error surfacing somewhere
- [x] #6350
- [x] #4607
- [x] ~~#6814~~ now tracked separately
- [x] ~~#6596~~ now tracked in #11772
- [x] #6248
- [x] ~~#8579~~ continue tracking this as a general S3 bug
- [x] #12669
- [x] #6186

**Comment by awang** [comment]
thanks for writing this up!  here's some of my thoughts re: UX:  https://github.com/MaterializeInc/materialize/pull/6843#issuecomment-850868937

**Comment by antifuchs** [comment]
Related: #6952 (via #6010).

**Comment by philip-stoev** [comment]
Another aspect came up -- handling errors with existing sources/sinks at Mz boot time --  #7396

**Comment by aljoscha** [comment]
This is also related: https://github.com/MaterializeInc/materialize/issues/6916

**Comment by aljoscha** [comment]
Related: https://github.com/MaterializeInc/materialize/issues/2918

**Comment by awang** [comment]
very tangentially related: #6285

**Comment by aljoscha** [comment]
Thanks! These are actually quite important, I think.

**Comment by aljoscha** [comment]
Forwarding a result from https://github.com/MaterializeInc/materialize/issues/7804#issuecomment-910334478:

Logging the results of an internal discussion on this:

 - connector errors (for example sink or source) shouldn't be added to the already exiting "err" collections/arrangements. Mostly because they are not deterministic/reproducible. A division by zero error, for example, can be removed by retracting the offending input errors.
 - There are different classes of errors. System errors (which happen "randomly", mostly when interacting with other systems) and the deterministic errors that originate from SQL, let's call them dataflow errors.
 - For SQL/dataflow errors, we can create a timely logging view that reports "has error" if there is any error, but we don't need to report back the individual errors through logging. (Thats what this Github issue is about)

For addressing system errors, we should add an `mz_connector_errors` view (technically a timely logging source) where we throw in all the system errors. Maybe? I'm adding a new subtask for this one.

**Comment by philip-stoev** [comment]
Another aspect -- a persisted kafka source may be in a state where it is reading its data from disk and re-hydrating. This state should also be communicated to the user, as it can take arbitrary long amount of time. Ticket https://github.com/MaterializeInc/materialize/issues/9242

**Comment by philip-stoev** [comment]
Another one https://github.com/MaterializeInc/materialize/issues/10269 - if the KEY SCHEMA fails to be fetched from the schema registry due to a transient network problem, we make no attempts to retry and we return a bogus error message to the user.

**Comment by philip-stoev** [comment]
And another one:
* https://github.com/MaterializeInc/materialize/issues/12389

**Comment by aljoscha** [comment]
We finished all subtasks or moved them off to other issues/will track them separately by themselves.
