### ISSUE TITLE
persist: August milestone

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#7140]
Success Metric: Persist mz_metrics (beta)
Motivation: Forcing function to think early about productionization. Size of data is small and (more-or-less) bounded. Rate of writes is small and predictable.

Concretely (anything large enough to warrant discussion should be broken out into its own issue and linked here):
- [x] Finalize initial deliverable
- [x] #7103
- [x] #7273
- [x] #7388
- [x] #7138
- [X] #7248
- [x] [ruchirK] Initial simple compaction
  - [x] #7426
  - [x] #7686 
  - [x] #7847
  - [x] #7964
- [x] #7483
- [x] #7800
- [x] #7325
- [x] #7403
- [x] #7387
- [x] [danhhz] Nemesis-based testing
  - [x] #7369
  - [x] #7466
  - [x] #7791
  - [x] #7830
- [x] #7285
- [x] Ensure that transactional sql writes are persisted transactionally #7540
- [x] #7544
- [x] https://github.com/MaterializeInc/materialize/pull/7659
- [x] #7878
- [x] #7696
- [x] #7848
- [x] [danhhz] Figure out clean shutdown vs LOCK handling story
  - [x] #7762
  - [x] #7781
- [x] #7937
- [x] #7966
- [x] #7902
- [x] #7935
- [x] #8034
- [x] #8077
- [x] #8033
- [ ] #8031

**Comment by ruchirK** [comment]
re: 

> Revisit persist::error::Error (probably make it more actionable by users and replace internal stuff with anyhow)

I think maybe a good initial step is to break it down into `InvalidCommand` and `StorageError` or something like that to indicate "your command was wrong" vs "everything you said was fine, we just had an issue reading/writing it down"

**Comment by danhhz** [comment]
Another I've thought of is something like a `DecodeError` to indicate that your Row didn't decode correctly or (once we add it) a checksum failed

**Comment by ruchirK** [comment]
I can take on:
- end to end read benchmark
- perf work on end to end benchmark
- metrics
- table persistence load test
- splitting up persist::Error
- unit test for persistence

Does that sound like the right amount / too much / too little? I mostly just want to have a personal burn list of "things I need to get done before I leave" and try to run through that list as fast as possible.

**Comment by danhhz** [comment]
All those things but one are fairly straightforward/timeboxed, which I think is a good plan given how big the compaction stuff is. The single exception is the perf work, so lets leave that off your list and whoever ends up with cycles can pick it up.
