### ISSUE TITLE
persist: Milestone 3: Scope out Milestone 4

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#7567]
Success Metrics: Fast restarts for one source (beta)
Motivation: Get customer feedback as early as possible
Concretely: The source will be Kafka, but not all formats and envelopes. Eng and Product to define this more precisely based on initial customer needs.

- [x] Hook up kafka to persist
- [ ] Model of beta tester traffic for driving performance work
- [x] Get snapshot doesn't download blobs before returning
- [x] S3 impl of blob
- [x] Audit TODOs

Performance Investigations
- [ ] Write hot path
- [ ] Maintenance path
- [ ] Replay path
- [ ] 10s of active persisted collections
- [ ] Create models of beta tester workloads

Big Project Investigations
- [ ] Additional nemesis coverage
  - [ ] Full pipelining
  - [ ] Crash testing
- [ ] Encoding format
- [ ] Incremental meta

**Comment by danhhz** [comment]
Obsoleted by #12847
