### ISSUE TITLE
release: v0.9.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#7738]
The following PRs in v0.9.0-rc1 require review:
* [ ] [#7108 upgrade: A dedicated framework for testing upgrade.](https://github.com/MaterializeInc/materialize/pull/7108) (@philip-stoev)
* [ ] [#7546 antithesis: put libvoidstar.so in /usr/lib](https://github.com/MaterializeInc/materialize/pull/7546) (@philip-stoev)
* [ ] [#7538 upgrade test: cosmetic fixes post-merge](https://github.com/MaterializeInc/materialize/pull/7538) (@philip-stoev)
* [ ] [#7519 mkrelease: Simplify instructions and add a list-prs subcommand](https://github.com/MaterializeInc/materialize/pull/7519) (@quodlibetor)
* [ ] [#7541 small doc fix for 'ceil' function](https://github.com/MaterializeInc/materialize/pull/7541) (@josharenberg)
* [ ] [#7512 Code coverage](https://github.com/MaterializeInc/materialize/pull/7512) (@philip-stoev)
* [ ] [#7543 (docs) Add "Node.js and Materialize" guide](https://github.com/MaterializeInc/materialize/pull/7543) (@ruf-io)
* [ ] [#7573 sqllogictest: add a regression test for #7472](https://github.com/MaterializeInc/materialize/pull/7573) (@philip-stoev)
* [ ] [#7574 docs,testdrive: change mentions of BUILD_MODE to --mz-build-mode](https://github.com/MaterializeInc/materialize/pull/7574) (@aljoscha)
* [ ] [#7591 pgrepr+repr: clean references to apd](https://github.com/MaterializeInc/materialize/pull/7591) (@sploiselle)
* [ ] [#7602 sql: update dec library for new primitive cast semantics](https://github.com/MaterializeInc/materialize/pull/7602) (@sploiselle)
* [ ] [#7625 docs,sql: temporarily remove CONSISTENCY TOPIC and FORMAT](https://github.com/MaterializeInc/materialize/pull/7625) (@JLDLaughlin)
* [ ] [#7499 docs: Update Getting Started guide.](https://github.com/MaterializeInc/materialize/pull/7499) (@morsapaes)
* [ ] [#7650 decimals,test: Additional tests for the DECIMAL type](https://github.com/MaterializeInc/materialize/pull/7650) (@philip-stoev)
* [ ] [#7652 upgrade test: fix mzcompose.yml to conform to new format](https://github.com/MaterializeInc/materialize/pull/7652) (@philip-stoev)
* [ ] [#7628 Describe TAIL behavior in a type, provide all progress information](https://github.com/MaterializeInc/materialize/pull/7628) (@frankmcsherry)
* [ ] [#7399 Switch Redpanda CI to internal schema-registry](https://github.com/MaterializeInc/materialize/pull/7399) (@BenPope)
* [ ] [#7658 Various improvement to scratch.py script](https://github.com/MaterializeInc/materialize/pull/7658) (@umanwizard)
* [ ] [#7666 dataflow: remove outdated/misleading comment about experimental mode](https://github.com/MaterializeInc/materialize/pull/7666) (@aljoscha)
* [ ] [#7667 Rebrand SequencedCommand and WorkerFeedbackWithMeta](https://github.com/MaterializeInc/materialize/pull/7667) (@frankmcsherry)
* [ ] [#7677 docs: Update MZ Cloud Quickstart guide](https://github.com/MaterializeInc/materialize/pull/7677) (@morsapaes)
* [ ] [#7693 interchange: remove some dead code](https://github.com/MaterializeInc/materialize/pull/7693) (@benesch)
* [ ] [#7694 finish writing release.json](https://github.com/MaterializeInc/materialize/pull/7694) (@umanwizard)
* [ ] [#7702 ci/builder: bump nightly image](https://github.com/MaterializeInc/materialize/pull/7702) (@benesch)
* [ ] [#7709 persist: quick cleanups](https://github.com/MaterializeInc/materialize/pull/7709) (@ruchirK)
* [ ] [#7710 avoid InvalidParameterCombination on empty set of instances to delete](https://github.com/MaterializeInc/materialize/pull/7710) (@umanwizard)
* [ ] [#7731 dependabot: bump python dependencies too](https://github.com/MaterializeInc/materialize/pull/7731) (@benesch)
* [ ] [#7733 persist: fix SELECT on persisted user tables](https://github.com/MaterializeInc/materialize/pull/7733) (@danhhz)
* [ ] [#7734 persist: disable flaky nemesis operation](https://github.com/MaterializeInc/materialize/pull/7734) (@danhhz)

**Comment by benesch** [comment]
This _almost_ came out right. Going to retrigger.
