### ISSUE TITLE
release: v0.9.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#7739]
The following PRs in [`v0.9.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.0-rc1) require review:
* [x] [#7108 upgrade: A dedicated framework for testing upgrade.](https://github.com/MaterializeInc/materialize/pull/7108) (@philip-stoev)
* [x] [#7546 antithesis: put libvoidstar.so in /usr/lib](https://github.com/MaterializeInc/materialize/pull/7546) (@philip-stoev)
* [x] [#7538 upgrade test: cosmetic fixes post-merge](https://github.com/MaterializeInc/materialize/pull/7538) (@philip-stoev)
* [x] [#7519 mkrelease: Simplify instructions and add a list-prs subcommand](https://github.com/MaterializeInc/materialize/pull/7519) (@quodlibetor)
* [x] [#7541 small doc fix for 'ceil' function](https://github.com/MaterializeInc/materialize/pull/7541) (@josharenberg)
* [x] [#7512 Code coverage](https://github.com/MaterializeInc/materialize/pull/7512) (@philip-stoev)
* [x] [#7543 (docs) Add "Node.js and Materialize" guide](https://github.com/MaterializeInc/materialize/pull/7543) (@ruf-io)
* [x] [#7573 sqllogictest: add a regression test for #7472](https://github.com/MaterializeInc/materialize/pull/7573) (@philip-stoev)
* [x] [#7574 docs,testdrive: change mentions of BUILD_MODE to --mz-build-mode](https://github.com/MaterializeInc/materialize/pull/7574) (@aljoscha)
* [x] [#7591 pgrepr+repr: clean references to apd](https://github.com/MaterializeInc/materialize/pull/7591) (@sploiselle)
* [x] [#7602 sql: update dec library for new primitive cast semantics](https://github.com/MaterializeInc/materialize/pull/7602) (@sploiselle)
* [x] [#7625 docs,sql: temporarily remove CONSISTENCY TOPIC and FORMAT](https://github.com/MaterializeInc/materialize/pull/7625) (@JLDLaughlin)
* [x] [#7499 docs: Update Getting Started guide.](https://github.com/MaterializeInc/materialize/pull/7499) (@morsapaes)
* [x] [#7650 decimals,test: Additional tests for the DECIMAL type](https://github.com/MaterializeInc/materialize/pull/7650) (@philip-stoev)
* [x] [#7652 upgrade test: fix mzcompose.yml to conform to new format](https://github.com/MaterializeInc/materialize/pull/7652) (@philip-stoev)
* [x] [#7628 Describe TAIL behavior in a type, provide all progress information](https://github.com/MaterializeInc/materialize/pull/7628) (@frankmcsherry)
* [x] [#7399 Switch Redpanda CI to internal schema-registry](https://github.com/MaterializeInc/materialize/pull/7399) (@BenPope)
* [x] [#7658 Various improvement to scratch.py script](https://github.com/MaterializeInc/materialize/pull/7658) (@umanwizard)
* [x] [#7666 dataflow: remove outdated/misleading comment about experimental mode](https://github.com/MaterializeInc/materialize/pull/7666) (@aljoscha)
* [x] [#7667 Rebrand SequencedCommand and WorkerFeedbackWithMeta](https://github.com/MaterializeInc/materialize/pull/7667) (@frankmcsherry)
* [x] [#7677 docs: Update MZ Cloud Quickstart guide](https://github.com/MaterializeInc/materialize/pull/7677) (@morsapaes)
* [x] [#7693 interchange: remove some dead code](https://github.com/MaterializeInc/materialize/pull/7693) (@benesch)
* [x] [#7694 finish writing release.json](https://github.com/MaterializeInc/materialize/pull/7694) (@umanwizard)
* [x] [#7702 ci/builder: bump nightly image](https://github.com/MaterializeInc/materialize/pull/7702) (@benesch)
* [x] [#7709 persist: quick cleanups](https://github.com/MaterializeInc/materialize/pull/7709) (@ruchirK)
* [x] [#7710 avoid InvalidParameterCombination on empty set of instances to delete](https://github.com/MaterializeInc/materialize/pull/7710) (@umanwizard)
* [x] [#7731 dependabot: bump python dependencies too](https://github.com/MaterializeInc/materialize/pull/7731) (@benesch)
* [x] [#7733 persist: fix SELECT on persisted user tables](https://github.com/MaterializeInc/materialize/pull/7733) (@danhhz)
* [x] [#7734 persist: disable flaky nemesis operation](https://github.com/MaterializeInc/materialize/pull/7734) (@danhhz)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#7108 upgrade: A dedicated framework for testing upgrade.](https://github.com/MaterializeInc/materialize/pull/7108) (@philip-stoev)
* [ ] [#7546 antithesis: put libvoidstar.so in /usr/lib](https://github.com/MaterializeInc/materialize/pull/7546) (@philip-stoev)
* [ ] [#7531 build(deps): bump futures from 0.3.15 to 0.3.16](https://github.com/MaterializeInc/materialize/pull/7531) (@dependabot[bot])
* [ ] [#7527 build(deps): bump enum-iterator from 0.6.0 to 0.7.0](https://github.com/MaterializeInc/materialize/pull/7527) (@dependabot[bot])
* [ ] [#7538 upgrade test: cosmetic fixes post-merge](https://github.com/MaterializeInc/materialize/pull/7538) (@philip-stoev)
* [ ] [#7519 mkrelease: Simplify instructions and add a list-prs subcommand](https://github.com/MaterializeInc/materialize/pull/7519) (@quodlibetor)
* [ ] [#7541 small doc fix for 'ceil' function](https://github.com/MaterializeInc/materialize/pull/7541) (@josharenberg)
* [ ] [#7505 dataflow-types: refactor Kafka connector information](https://github.com/MaterializeInc/materialize/pull/7505) (@JLDLaughlin)
* [ ] [#7542 De-experimentalize CDCv2 sources](https://github.com/MaterializeInc/materialize/pull/7542) (@umanwizard)
* [ ] [#7407 Add a design doc for S3 Sources with Headers](https://github.com/MaterializeInc/materialize/pull/7407) (@quodlibetor)
* [ ] [#7540 persist: various prep for #7283](https://github.com/MaterializeInc/materialize/pull/7540) (@danhhz)
* [ ] [#7539 Remove some incorrect docs for the CI base image](https://github.com/MaterializeInc/materialize/pull/7539) (@quodlibetor)
* [ ] [#7503 persist: evict / trim Future batches](https://github.com/MaterializeInc/materialize/pull/7503) (@ruchirK)
* [ ] [#7512 Code coverage](https://github.com/MaterializeInc/materialize/pull/7512) (@philip-stoev)
* [ ] [#7552 *: update API documentation link](https://github.com/MaterializeInc/materialize/pull/7552) (@ruchirK)
* [ ] [#7544 persist: implement destroy](https://github.com/MaterializeInc/materialize/pull/7544) (@ruchirK)
* [ ] [#7515 doc/syntax: Correct format_spec diagram and use it in all Kafka sources](https://github.com/MaterializeInc/materialize/pull/7515) (@quodlibetor)
* [ ] [#7518 persist: add a new source operator for mirroring a persisted stream](https://github.com/MaterializeInc/materialize/pull/7518) (@danhhz)
* [ ] [#7556  tests: bump topic_metadata_refresh_interval_ms on some Kafka tests](https://github.com/MaterializeInc/materialize/pull/7556) (@aljoscha)
* [ ] [#7558 persist: errror on invalid future snapshot interval](https://github.com/MaterializeInc/materialize/pull/7558) (@ruchirK)
* [ ] [#7534 sources,sinks: de-experimentalize RT timestamp binding persistence (AKA exactly-once sinks)](https://github.com/MaterializeInc/materialize/pull/7534) (@aljoscha)
* [ ] [#7559 persist: extend nemesis to use allow_compaction](https://github.com/MaterializeInc/materialize/pull/7559) (@ruchirK)
* [ ] [#7543 (docs) Add "Node.js and Materialize" guide](https://github.com/MaterializeInc/materialize/pull/7543) (@ruf-io)
* [ ] [#7493 Make metrics modular & report from a per-server registry](https://github.com/MaterializeInc/materialize/pull/7493) (@antifuchs)
* [ ] [#7564 Bound amount of work done in constant folding](https://github.com/MaterializeInc/materialize/pull/7564) (@frankmcsherry)
* [ ] [#7573 sqllogictest: add a regression test for #7472](https://github.com/MaterializeInc/materialize/pull/7573) (@philip-stoev)
* [ ] [#7574 docs,testdrive: change mentions of BUILD_MODE to --mz-build-mode](https://github.com/MaterializeInc/materialize/pull/7574) (@aljoscha)
* [ ] [#7510 Add option to include mz_catalog in http memory page](https://github.com/MaterializeInc/materialize/pull/7510) (@antiguru)
* [ ] [#7565 Testing: Support for MirRelationExpr::Reduce and TopK](https://github.com/MaterializeInc/materialize/pull/7565) (@wangandi)
* [ ] [#7560 testdrive: Create dedicated error report at end](https://github.com/MaterializeInc/materialize/pull/7560) (@quodlibetor)
* [ ] [#7578 source,kafka: clarify log message, change from warn! to info!](https://github.com/MaterializeInc/materialize/pull/7578) (@aljoscha)
* [ ] [#7582 kafka: give context to Kafka error arising during purification](https://github.com/MaterializeInc/materialize/pull/7582) (@aljoscha)
* [ ] [#7563 coord: check while dropping error'd sink connector](https://github.com/MaterializeInc/materialize/pull/7563) (@mjibson)
* [ ] [#7561 coordtest: requeue skipped upper updates](https://github.com/MaterializeInc/materialize/pull/7561) (@mjibson)
* [ ] [#7588 materialized: cleanup memory.jsx](https://github.com/MaterializeInc/materialize/pull/7588) (@mjibson)
* [ ] [#7591 pgrepr+repr: clean references to apd](https://github.com/MaterializeInc/materialize/pull/7591) (@sploiselle)
* [ ] [#7545 support JSON-encoded Kafka sinks](https://github.com/MaterializeInc/materialize/pull/7545) (@JLDLaughlin)
* [ ] [#7593 *: remove some unused async](https://github.com/MaterializeInc/materialize/pull/7593) (@mjibson)
* [ ] [#7596 limit CPUs used to lower of physical or logical cores](https://github.com/MaterializeInc/materialize/pull/7596) (@alex-hunt-materialize)
* [ ] [#7478 ore: introduce optional assertions framework](https://github.com/MaterializeInc/materialize/pull/7478) (@benesch)
* [ ] [#7599 tests,kafka: verify output of consistency topic with real-time timestamp binding](https://github.com/MaterializeInc/materialize/pull/7599) (@aljoscha)
* [ ] [#7336 Extend predicate canonicalization to remove redundant IS NOT NULL predicates](https://github.com/MaterializeInc/materialize/pull/7336) (@asenac)
* [ ] [#7283 persist: hook up user tables to persistence core behind flag](https://github.com/MaterializeInc/materialize/pull/7283) (@danhhz)
* [ ] [#7589 sql-parser: add consistency topic format to Kafka connector](https://github.com/MaterializeInc/materialize/pull/7589) (@JLDLaughlin)
* [ ] [#7602 sql: update dec library for new primitive cast semantics](https://github.com/MaterializeInc/materialize/pull/7602) (@sploiselle)
* [ ] [#7604 github: add materialize cloud install option](https://github.com/MaterializeInc/materialize/pull/7604) (@JLDLaughlin)
* [ ] [#7605 Update to Rust 1.54](https://github.com/MaterializeInc/materialize/pull/7605) (@umanwizard)
* [ ] [#7571 decimal: fix some broken internal casts](https://github.com/MaterializeInc/materialize/pull/7571) (@sploiselle)
* [ ] [#7607 coord: seal all persisted tables in a single operation for efficiency](https://github.com/MaterializeInc/materialize/pull/7607) (@danhhz)
* [ ] [#7585 push down join equivalences with runtime constants](https://github.com/MaterializeInc/materialize/pull/7585) (@asenac)
* [ ] [#7616 Hierarchical memory visualization tool](https://github.com/MaterializeInc/materialize/pull/7616) (@asenac)
* [ ] [#7621 bin: add unused_async lint](https://github.com/MaterializeInc/materialize/pull/7621) (@mjibson)
* [ ] [#7594 Make SequencedCommand serializable and deserializable](https://github.com/MaterializeInc/materialize/pull/7594) (@frankmcsherry)
* [ ] [#7623 interchange: disallow Protobuf messages with unsigned integers](https://github.com/MaterializeInc/materialize/pull/7623) (@benesch)
* [ ] [#7626 Fix building with the dev-web feature](https://github.com/MaterializeInc/materialize/pull/7626) (@antifuchs)
* [ ] [#7625 docs,sql: temporarily remove CONSISTENCY TOPIC and FORMAT](https://github.com/MaterializeInc/materialize/pull/7625) (@JLDLaughlin)
* [ ] [#7624 Temporal tidy-up](https://github.com/MaterializeInc/materialize/pull/7624) (@frankmcsherry)
* [ ] [#7632 http-util: prepare for open-source release as mz-http-proxy](https://github.com/MaterializeInc/materialize/pull/7632) (@benesch)
* [ ] [#7634 (docs) Correct formatting in CREATE SINK example for EO sinks](https://github.com/MaterializeInc/materialize/pull/7634) (@morsapaes)
* [ ] [#7640 build(deps): bump assert_cmd from 1.0.7 to 1.0.8](https://github.com/MaterializeInc/materialize/pull/7640) (@dependabot[bot])
* [ ] [#7641 build(deps): bump timely from `9f481f9` to `09b16c5`](https://github.com/MaterializeInc/materialize/pull/7641) (@dependabot[bot])
* [ ] [#7642 build(deps): bump semver from 1.0.3 to 1.0.4](https://github.com/MaterializeInc/materialize/pull/7642) (@dependabot[bot])
* [ ] [#7643 build(deps): bump proc-macro2 from 1.0.27 to 1.0.28](https://github.com/MaterializeInc/materialize/pull/7643) (@dependabot[bot])
* [ ] [#7644 build(deps): bump async-trait from 0.1.50 to 0.1.51](https://github.com/MaterializeInc/materialize/pull/7644) (@dependabot[bot])
* [ ] [#7638 build(deps): bump serde_json from 1.0.64 to 1.0.66](https://github.com/MaterializeInc/materialize/pull/7638) (@dependabot[bot])
* [ ] [#7635 build(deps): bump backtrace from 0.3.60 to 0.3.61](https://github.com/MaterializeInc/materialize/pull/7635) (@dependabot[bot])
* [ ] [#7637 build(deps): bump criterion from 0.3.4 to 0.3.5](https://github.com/MaterializeInc/materialize/pull/7637) (@dependabot[bot])
* [ ] [#7636 build(deps): bump predicates from 2.0.0 to 2.0.1](https://github.com/MaterializeInc/materialize/pull/7636) (@dependabot[bot])
* [ ] [#7639 build(deps): bump serde from 1.0.126 to 1.0.127](https://github.com/MaterializeInc/materialize/pull/7639) (@dependabot[bot])
* [ ] [#7499 docs: Update Getting Started guide.](https://github.com/MaterializeInc/materialize/pull/7499) (@morsapaes)
* [ ] [#7651 coord,sources: don't publish duplicate consistency information in BYO kafka connector](https://github.com/MaterializeInc/materialize/pull/7651) (@aljoscha)
* [ ] [#7650 decimals,test: Additional tests for the DECIMAL type](https://github.com/MaterializeInc/materialize/pull/7650) (@philip-stoev)
* [ ] [#7652 upgrade test: fix mzcompose.yml to conform to new format](https://github.com/MaterializeInc/materialize/pull/7652) (@philip-stoev)
* [ ] [#7601 mkrelease: Update upgrade tests as part of finishing the release](https://github.com/MaterializeInc/materialize/pull/7601) (@quodlibetor)
* [ ] [#7628 Describe TAIL behavior in a type, provide all progress information](https://github.com/MaterializeInc/materialize/pull/7628) (@frankmcsherry)
* [ ] [#7653 Run upgrade tests if they have changed](https://github.com/MaterializeInc/materialize/pull/7653) (@quodlibetor)
* [ ] [#7654 upgrade: Use testdrive's --ci-output in buildkite](https://github.com/MaterializeInc/materialize/pull/7654) (@quodlibetor)
* [ ] [#7399 Switch Redpanda CI to internal schema-registry](https://github.com/MaterializeInc/materialize/pull/7399) (@BenPope)
* [ ] [#7656 Document that we are improving the SQS Notifications interface](https://github.com/MaterializeInc/materialize/pull/7656) (@quodlibetor)
* [ ] [#7584 docs: add design doc for consistent error handling and surfacing connector failures](https://github.com/MaterializeInc/materialize/pull/7584) (@aljoscha)
* [ ] [#7612 MIR testing: Roundtrip support](https://github.com/MaterializeInc/materialize/pull/7612) (@wangandi)
* [ ] [#7658 Various improvement to scratch.py script](https://github.com/MaterializeInc/materialize/pull/7658) (@umanwizard)
* [ ] [#7660 testdrive: Fix the parsing of "? EXPLAIN" actions](https://github.com/MaterializeInc/materialize/pull/7660) (@philip-stoev)
* [ ] [#7665 kafka-matrix: fix mzcompose.yml to accommodate latest Kafka](https://github.com/MaterializeInc/materialize/pull/7665) (@philip-stoev)
* [ ] [#7666 dataflow: remove outdated/misleading comment about experimental mode](https://github.com/MaterializeInc/materialize/pull/7666) (@aljoscha)
* [ ] [#7667 Rebrand SequencedCommand and WorkerFeedbackWithMeta](https://github.com/MaterializeInc/materialize/pull/7667) (@frankmcsherry)
* [ ] [#7664 (docs) Add "Sinks" to "Connect" in the sidebar](https://github.com/MaterializeInc/materialize/pull/7664) (@morsapaes)
* [ ] [#7671 Mark .svg files as generated (similarly to Cargo.lock), to avoid them polluting docs diffs](https://github.com/MaterializeInc/materialize/pull/7671) (@umanwizard)
* [ ] [#7608 coord: enable consistency topics for JSON-encoded Kafka sinks](https://github.com/MaterializeInc/materialize/pull/7608) (@JLDLaughlin)
* [ ] [#7670 clean up scratch instances after a week](https://github.com/MaterializeInc/materialize/pull/7670) (@umanwizard)
* [ ] [#7674 report cgroup memory limits](https://github.com/MaterializeInc/materialize/pull/7674) (@alex-hunt-materialize)
* [ ] [#7677 docs: Update MZ Cloud Quickstart guide](https://github.com/MaterializeInc/materialize/pull/7677) (@morsapaes)
* [ ] [#7679 python: properly type several values](https://github.com/MaterializeInc/materialize/pull/7679) (@benesch)
* [ ] [#7681 transform: remove dead code](https://github.com/MaterializeInc/materialize/pull/7681) (@petrosagg)
* [ ] [#7672 migrate: Give migrations names in error messages](https://github.com/MaterializeInc/materialize/pull/7672) (@quodlibetor)
* [ ] [#7630 persist: start replacing CmdResponse with Future](https://github.com/MaterializeInc/materialize/pull/7630) (@danhhz)
* [ ] [#7692 *: reduce all "deny" and "forbid" lints to "warn"](https://github.com/MaterializeInc/materialize/pull/7692) (@benesch)
* [ ] [#7685 Avoid cross joins by converting reduced filter expressions into join equivalences](https://github.com/MaterializeInc/materialize/pull/7685) (@asenac)
* [ ] [#7693 interchange: remove some dead code](https://github.com/MaterializeInc/materialize/pull/7693) (@benesch)
* [ ] [#7694 finish writing release.json](https://github.com/MaterializeInc/materialize/pull/7694) (@umanwizard)
* [ ] [#7690 Reduce the amount of duplicate code in per-dataflow-worker metrics](https://github.com/MaterializeInc/materialize/pull/7690) (@antifuchs)
* [ ] [#7689 sql: support environment variable lookups in WITH options](https://github.com/MaterializeInc/materialize/pull/7689) (@sploiselle)
* [ ] [#7702 ci/builder: bump nightly image](https://github.com/MaterializeInc/materialize/pull/7702) (@benesch)
* [ ] [#7703 Retrieve jemalloc stats through http GET](https://github.com/MaterializeInc/materialize/pull/7703) (@antiguru)
* [ ] [#7171 [dataflow] Fuel the arrangement to stream operator](https://github.com/MaterializeInc/materialize/pull/7171) (@frankmcsherry)
* [ ] [#7673 docs: JSON Kafka sinks and consistency topics](https://github.com/MaterializeInc/materialize/pull/7673) (@JLDLaughlin)
* [ ] [#7709 persist: quick cleanups](https://github.com/MaterializeInc/materialize/pull/7709) (@ruchirK)
* [ ] [#7710 avoid InvalidParameterCombination on empty set of instances to delete](https://github.com/MaterializeInc/materialize/pull/7710) (@umanwizard)
* [ ] [#7712 lowertest: Support specifying zero-arg structs.](https://github.com/MaterializeInc/materialize/pull/7712) (@wangandi)
* [ ] [#7716 dbt-materialize: bump to dbt 0.20.0](https://github.com/MaterializeInc/materialize/pull/7716) (@benesch)
* [ ] [#7332 docs: Update CREATE SOURCE syntax for Protobuf over Kafka/Kinesis + Billing Demo](https://github.com/MaterializeInc/materialize/pull/7332) (@morsapaes)
* [ ] [#7717 dependabot: configure automatic updates for dbt](https://github.com/MaterializeInc/materialize/pull/7717) (@benesch)
* [ ] [#7720 build(deps): bump differential-dataflow from `9d33cda` to `c29b8a3`](https://github.com/MaterializeInc/materialize/pull/7720) (@dependabot[bot])
* [ ] [#7722 build(deps): bump assert_cmd from 1.0.8 to 2.0.0](https://github.com/MaterializeInc/materialize/pull/7722) (@dependabot[bot])
* [ ] [#7725 build(deps): bump dogsdogsdogs from `9d33cda` to `c29b8a3`](https://github.com/MaterializeInc/materialize/pull/7725) (@dependabot[bot])
* [ ] [#7726 build(deps): bump sysctl from 0.4.1 to 0.4.2](https://github.com/MaterializeInc/materialize/pull/7726) (@dependabot[bot])
* [ ] [#7686 persist: split seal into physical and logical components.](https://github.com/MaterializeInc/materialize/pull/7686) (@ruchirK)
* [ ] [#7659 persist: support per-stream key Codec and val Codec](https://github.com/MaterializeInc/materialize/pull/7659) (@danhhz)
* [ ] [#7728 generate temporary ssh key rather than using ~/.ssh/id_rsa](https://github.com/MaterializeInc/materialize/pull/7728) (@umanwizard)
* [ ] [#7729 testdrive: remove support for corrupting avro/protobuf](https://github.com/MaterializeInc/materialize/pull/7729) (@benesch)
* [ ] [#7701 repr testing: Change datum creation to row creation to get rid of lifetime problem.](https://github.com/MaterializeInc/materialize/pull/7701) (@wangandi)
* [ ] [#7727 build(deps): bump sysinfo from 0.19.2 to 0.20.0](https://github.com/MaterializeInc/materialize/pull/7727) (@dependabot[bot])
* [ ] [#7723 build(deps): bump timely from `09b16c5` to `0c83fc0`](https://github.com/MaterializeInc/materialize/pull/7723) (@dependabot[bot])
* [ ] [#7627 Add a metrics registry for "third parties"](https://github.com/MaterializeInc/materialize/pull/7627) (@antifuchs)
* [ ] [#7731 dependabot: bump python dependencies too](https://github.com/MaterializeInc/materialize/pull/7731) (@benesch)
* [ ] [#7730 Fix cleanup job to run in us-east-2 as originally intended](https://github.com/MaterializeInc/materialize/pull/7730) (@umanwizard)
* [ ] [#7733 persist: fix SELECT on persisted user tables](https://github.com/MaterializeInc/materialize/pull/7733) (@danhhz)
* [ ] [#7698 (WIP) coord: refactor catalog content migrations](https://github.com/MaterializeInc/materialize/pull/7698) (@sploiselle)
* [ ] [#7734 persist: disable flaky nemesis operation](https://github.com/MaterializeInc/materialize/pull/7734) (@danhhz)
* [ ] [#7696 coord: enable select sys table persistence behind a flag (default off)](https://github.com/MaterializeInc/materialize/pull/7696) (@danhhz)
* [ ] [#7724 build(deps): bump phf from 0.9.0 to 0.9.1](https://github.com/MaterializeInc/materialize/pull/7724) (@dependabot[bot])

</details>

**Comment by benesch** [comment]
@umanwizard could you please sign off on the three commits of mine, and comment when you've done so?

**Comment by umanwizard** [comment]
lgtm
