### ISSUE TITLE
mzcloud: feature tracker

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#7860]
Just jotting down a bunch of features we'll want to add to the mzcloud CLI (#7714):

* [ ] Support for named profiles (a la `aws profile`), to support users with multiple workspaces, and to spare people from having to manage OAuth credentials on their own. Probably stored in `~/.config/materialize/mzcloud.toml` or somesuch.
* [ ] Pretty output formats, with the current JSON output format behind a `--format=json` flag.
* [ ] Ability to wait for a deployment to become ready, with a progress indicator.
* [ ] Packaging in the Debian and Homebrew repositories

**Comment by rjnn** [comment]
nit: rename `--secret` to `--secret-key` to match `--client-id` naming
