### ISSUE TITLE
release: v0.9.1-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#7880]
The following PRs in [`v0.9.1-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.1-rc1) require review:
* [x] [#7740 dependabot: fix typo](https://github.com/MaterializeInc/materialize/pull/7740) (@benesch)
* [x] [#7746 Prepare 0.9.1 dev](https://github.com/MaterializeInc/materialize/pull/7746) (@benesch)
* [x] [#7752 ci/builder: update for new Python dependencies](https://github.com/MaterializeInc/materialize/pull/7752) (@benesch)
* [x] [#7769 add "LaunchedBy" tag to instances](https://github.com/MaterializeInc/materialize/pull/7769) (@umanwizard)
* [x] [#7780 Print more stuff about the instances in scratch.py](https://github.com/MaterializeInc/materialize/pull/7780) (@umanwizard)
* [x] [#7789 doc/user: mark 0.9.0 as released](https://github.com/MaterializeInc/materialize/pull/7789) (@benesch)
* [x] [#7792 doc/user: fix beta version for exactly once sinks](https://github.com/MaterializeInc/materialize/pull/7792) (@benesch)
* [x] [#7700 sql-parser,sql: refactor Protobuf format](https://github.com/MaterializeInc/materialize/pull/7700) (@JLDLaughlin)
* [x] [#7795 coverage: disable the nightly job due to persistent OOMs when linking](https://github.com/MaterializeInc/materialize/pull/7795) (@philip-stoev)
* [x] [#7822 mzcompose: make "./mzcompose help" equivalent to "./mzcompose --help"](https://github.com/MaterializeInc/materialize/pull/7822) (@benesch)
* [x] [#7828 allow specifying git revision in `scratch create`](https://github.com/MaterializeInc/materialize/pull/7828) (@umanwizard)
* [x] [#7829 Don't break when tags is none](https://github.com/MaterializeInc/materialize/pull/7829) (@umanwizard)
* [x] [#7832 unsharing mz_logical_timestamp() example  ](https://github.com/MaterializeInc/materialize/pull/7832) (@msudberg)
* [x] [#7841 mzworkflows: allow Python workflows to run Steps](https://github.com/MaterializeInc/materialize/pull/7841) (@philip-stoev)
* [x] [#7859 ci: bump build pipeline to 60m](https://github.com/MaterializeInc/materialize/pull/7859) (@benesch)
* [x] [#7876 allow null sequence field in dbz sources](https://github.com/MaterializeInc/materialize/pull/7876) (@umanwizard)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#7740 dependabot: fix typo](https://github.com/MaterializeInc/materialize/pull/7740) (@benesch)
* [ ] [#7741 build(deps-dev): bump mypy from 0.800 to 0.910 in /misc/python](https://github.com/MaterializeInc/materialize/pull/7741) (@dependabot[bot])
* [ ] [#7742 build(deps): bump typing-extensions from 3.7.4.2 to 3.10.0.0 in /misc/python](https://github.com/MaterializeInc/materialize/pull/7742) (@dependabot[bot])
* [ ] [#7743 build(deps-dev): bump humanize from 2.3.0 to 3.11.0 in /misc/python](https://github.com/MaterializeInc/materialize/pull/7743) (@dependabot[bot])
* [ ] [#7746 Prepare 0.9.1 dev](https://github.com/MaterializeInc/materialize/pull/7746) (@benesch)
* [ ] [#7745 build(deps): bump pyyaml from 5.4 to 5.4.1 in /misc/python](https://github.com/MaterializeInc/materialize/pull/7745) (@dependabot[bot])
* [ ] [#7744 build(deps): bump pymysql from 0.9.3 to 1.0.2 in /misc/python](https://github.com/MaterializeInc/materialize/pull/7744) (@dependabot[bot])
* [ ] [#7732 Run periodic (e.g. monthly) load tests via Buildkite and the scratch account](https://github.com/MaterializeInc/materialize/pull/7732) (@umanwizard)
* [ ] [#7749 expr: don't crash on long LIKE patterns](https://github.com/MaterializeInc/materialize/pull/7749) (@benesch)
* [ ] [#7752 ci/builder: update for new Python dependencies](https://github.com/MaterializeInc/materialize/pull/7752) (@benesch)
* [ ] [#7750 Switch back to upstream tikv/jemallocator](https://github.com/MaterializeInc/materialize/pull/7750) (@umanwizard)
* [ ] [#7758 build(deps): bump differential-dataflow from `c29b8a3` to `65d1a5a`](https://github.com/MaterializeInc/materialize/pull/7758) (@dependabot[bot])
* [ ] [#7760 build(deps): bump dogsdogsdogs from `c29b8a3` to `65d1a5a`](https://github.com/MaterializeInc/materialize/pull/7760) (@dependabot[bot])
* [ ] [#7759 dataflow: remove serde_variant](https://github.com/MaterializeInc/materialize/pull/7759) (@benesch)
* [ ] [#7631 Improve temporal filter error text](https://github.com/MaterializeInc/materialize/pull/7631) (@frankmcsherry)
* [ ] [#7761 editorconfig: remove max_line_length directives](https://github.com/MaterializeInc/materialize/pull/7761) (@benesch)
* [ ] [#7669 Use struct init shorthand in one instantiation](https://github.com/MaterializeInc/materialize/pull/7669) (@quodlibetor)
* [ ] [#7705 dataflow,coord: add reachability introspection views](https://github.com/MaterializeInc/materialize/pull/7705) (@aljoscha)
* [ ] [#7767 coord: make AS OF on unmaterialized sources error](https://github.com/MaterializeInc/materialize/pull/7767) (@mjibson)
* [ ] [#7765 Improve formatting of "launched instances" output](https://github.com/MaterializeInc/materialize/pull/7765) (@umanwizard)
* [ ] [#7764 persist: de-flake allow_compaction on nemesis.](https://github.com/MaterializeInc/materialize/pull/7764) (@ruchirK)
* [ ] [#7768 doc: add release note for #7467](https://github.com/MaterializeInc/materialize/pull/7768) (@sploiselle)
* [ ] [#7769 add "LaunchedBy" tag to instances](https://github.com/MaterializeInc/materialize/pull/7769) (@umanwizard)
* [ ] [#7771 upgrade: Remove the shared volumes between different version workflows](https://github.com/MaterializeInc/materialize/pull/7771) (@quodlibetor)
* [ ] [#7775 sql: future-proof unsupported! macro](https://github.com/MaterializeInc/materialize/pull/7775) (@sploiselle)
* [ ] [#7778 build(deps): bump libc from 0.2.98 to 0.2.99](https://github.com/MaterializeInc/materialize/pull/7778) (@dependabot[bot])
* [ ] [#7779 build(deps): bump timely from `0c83fc0` to `a410670`](https://github.com/MaterializeInc/materialize/pull/7779) (@dependabot[bot])
* [ ] [#7762 persist: make storage locks reentrant for the "same" process after crash](https://github.com/MaterializeInc/materialize/pull/7762) (@danhhz)
* [ ] [#7780 Print more stuff about the instances in scratch.py](https://github.com/MaterializeInc/materialize/pull/7780) (@umanwizard)
* [ ] [#7678 coord: make the metrics scraper async](https://github.com/MaterializeInc/materialize/pull/7678) (@benesch)
* [ ] [#7695 sql-parser: break Connector into sink and source connectors](https://github.com/MaterializeInc/materialize/pull/7695) (@JLDLaughlin)
* [ ] [#7788 python: fix some bugs in `mkrelease finish`](https://github.com/MaterializeInc/materialize/pull/7788) (@benesch)
* [ ] [#7789 doc/user: mark 0.9.0 as released](https://github.com/MaterializeInc/materialize/pull/7789) (@benesch)
* [ ] [#7786 deps: bump to secure version of tar](https://github.com/MaterializeInc/materialize/pull/7786) (@benesch)
* [ ] [#7522 sql: implement char, varchar](https://github.com/MaterializeInc/materialize/pull/7522) (@sploiselle)
* [ ] [#7792 doc/user: fix beta version for exactly once sinks](https://github.com/MaterializeInc/materialize/pull/7792) (@benesch)
* [ ] [#7782 add scratch-mine script to print a users instances](https://github.com/MaterializeInc/materialize/pull/7782) (@umanwizard)
* [ ] [#7777 materialized: move uptime metric maintenance into callback](https://github.com/MaterializeInc/materialize/pull/7777) (@benesch)
* [ ] [#7793 allow printing output in csv](https://github.com/MaterializeInc/materialize/pull/7793) (@umanwizard)
* [ ] [#7700 sql-parser,sql: refactor Protobuf format](https://github.com/MaterializeInc/materialize/pull/7700) (@JLDLaughlin)
* [ ] [#7587 (docs) Node.js guide update](https://github.com/MaterializeInc/materialize/pull/7587) (@ruf-io)
* [ ] [#7795 coverage: disable the nightly job due to persistent OOMs when linking](https://github.com/MaterializeInc/materialize/pull/7795) (@philip-stoev)
* [ ] [#7801 update ci-builder to Ubuntu 20.04](https://github.com/MaterializeInc/materialize/pull/7801) (@umanwizard)
* [ ] [#7802 add destroy script](https://github.com/MaterializeInc/materialize/pull/7802) (@umanwizard)
* [ ] [#7799 materialized: remove mz_server_scrape_metrics_times metric](https://github.com/MaterializeInc/materialize/pull/7799) (@benesch)
* [ ] [#7781 coord: hook up cluster_id to persist's reentrance lock id](https://github.com/MaterializeInc/materialize/pull/7781) (@danhhz)
* [ ] [#7791 persist: various nemesis additions](https://github.com/MaterializeInc/materialize/pull/7791) (@danhhz)
* [ ] [#7811 docs: release note for JSON sinks](https://github.com/MaterializeInc/materialize/pull/7811) (@JLDLaughlin)
* [ ] [#7794 persist: call Indexed::step less frequently.](https://github.com/MaterializeInc/materialize/pull/7794) (@ruchirK)
* [ ] [#7815 misc/www: add sudo to oneliners](https://github.com/MaterializeInc/materialize/pull/7815) (@benesch)
* [ ] [#7818 materialized: remove most metrics from /status](https://github.com/MaterializeInc/materialize/pull/7818) (@benesch)
* [ ] [#7817 rust-toolchain: write up policy for Rust version bumps](https://github.com/MaterializeInc/materialize/pull/7817) (@benesch)
* [ ] [#7822 mzcompose: make "./mzcompose help" equivalent to "./mzcompose --help"](https://github.com/MaterializeInc/materialize/pull/7822) (@benesch)
* [ ] [#7823 mzbuild: take over all responsibility for managing RUSTFLAGS](https://github.com/MaterializeInc/materialize/pull/7823) (@benesch)
* [ ] [#7797 Allow Python based workflows](https://github.com/MaterializeInc/materialize/pull/7797) (@philip-stoev)
* [ ] [#7800 persist: remove Buffer from Indexed](https://github.com/MaterializeInc/materialize/pull/7800) (@ruchirK)
* [ ] [#7796 dataflow/logging: Base batch size off content size](https://github.com/MaterializeInc/materialize/pull/7796) (@antiguru)
* [ ] [#7828 allow specifying git revision in `scratch create`](https://github.com/MaterializeInc/materialize/pull/7828) (@umanwizard)
* [ ] [#7829 Don't break when tags is none](https://github.com/MaterializeInc/materialize/pull/7829) (@umanwizard)
* [ ] [#7820 build(deps): bump dbt from 0.20.0 to 0.20.1 in /misc/dbt-materialize](https://github.com/MaterializeInc/materialize/pull/7820) (@dependabot[bot])
* [ ] [#7832 unsharing mz_logical_timestamp() example  ](https://github.com/MaterializeInc/materialize/pull/7832) (@msudberg)
* [ ] [#7553 Update issue templates](https://github.com/MaterializeInc/materialize/pull/7553) (@msudberg)
* [ ] [#7833 .github: tweak issue templates](https://github.com/MaterializeInc/materialize/pull/7833) (@benesch)
* [ ] [#7715 Relation CSE](https://github.com/MaterializeInc/materialize/pull/7715) (@frankmcsherry)
* [ ] [#7842 Mention that /metrics is machine-readable](https://github.com/MaterializeInc/materialize/pull/7842) (@awang)
* [ ] [#7843 fix KeyError in scratch](https://github.com/MaterializeInc/materialize/pull/7843) (@umanwizard)
* [ ] [#7813 INCLUDE KEY: correctly require that KEY FORMAT is provided](https://github.com/MaterializeInc/materialize/pull/7813) (@quodlibetor)
* [ ] [#7830 persist: add nemesis coverage of PersistedSource operator](https://github.com/MaterializeInc/materialize/pull/7830) (@danhhz)
* [ ] [#7841 mzworkflows: allow Python workflows to run Steps](https://github.com/MaterializeInc/materialize/pull/7841) (@philip-stoev)
* [ ] [#7844 test/pubnub: merge into main testdrive suite](https://github.com/MaterializeInc/materialize/pull/7844) (@benesch)
* [ ] [#7846 docs: fix typo on CREATE SINK doc](https://github.com/MaterializeInc/materialize/pull/7846) (@andrioni)
* [ ] [#7837 sql: support array_agg](https://github.com/MaterializeInc/materialize/pull/7837) (@mjibson)
* [ ] [#7821 materialized: use PID file for mutual exclusion](https://github.com/MaterializeInc/materialize/pull/7821) (@benesch)
* [ ] [#7845 pyfmt: enforce isort in CI too](https://github.com/MaterializeInc/materialize/pull/7845) (@benesch)
* [ ] [#7850 persist: use logging framework in nemesis](https://github.com/MaterializeInc/materialize/pull/7850) (@danhhz)
* [ ] [#7859 ci: bump build pipeline to 60m](https://github.com/MaterializeInc/materialize/pull/7859) (@benesch)
* [ ] [#7858 build(deps): bump tokio from 1.9.0 to 1.10.0](https://github.com/MaterializeInc/materialize/pull/7858) (@dependabot[bot])
* [ ] [#7852 build(deps): bump tar from 0.4.36 to 0.4.37](https://github.com/MaterializeInc/materialize/pull/7852) (@dependabot[bot])
* [ ] [#7857 build(deps): bump native-tls from 0.2.7 to 0.2.8](https://github.com/MaterializeInc/materialize/pull/7857) (@dependabot[bot])
* [ ] [#7853 build(deps): bump os_info from 3.0.6 to 3.0.7](https://github.com/MaterializeInc/materialize/pull/7853) (@dependabot[bot])
* [ ] [#7851 build(deps): bump matches from 0.1.8 to 0.1.9](https://github.com/MaterializeInc/materialize/pull/7851) (@dependabot[bot])
* [ ] [#7854 build(deps): bump anyhow from 1.0.42 to 1.0.43](https://github.com/MaterializeInc/materialize/pull/7854) (@dependabot[bot])
* [ ] [#7855 build(deps): bump phf from 0.9.1 to 0.10.0](https://github.com/MaterializeInc/materialize/pull/7855) (@dependabot[bot])
* [ ] [#7713 doc/user: narrow CREATE SOURCE railroad diagrams](https://github.com/MaterializeInc/materialize/pull/7713) (@benesch)
* [ ] [#7714 mzcloud-cli](https://github.com/MaterializeInc/materialize/pull/7714) (@alex-hunt-materialize)
* [ ] [#7849 mzcompose: allow service definitions in mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/7849) (@philip-stoev)
* [ ] [#7839 upgrade: refactor upgrade tests](https://github.com/MaterializeInc/materialize/pull/7839) (@philip-stoev)
* [ ] [#7862 sqllogictest: port to Python workflows](https://github.com/MaterializeInc/materialize/pull/7862) (@benesch)
* [ ] [#7865 pgrepr,pgwire: entirely disable the list/map binary encodings](https://github.com/MaterializeInc/materialize/pull/7865) (@benesch)
* [ ] [#7835 Add guide on enabling topic reuse.](https://github.com/MaterializeInc/materialize/pull/7835) (@msudberg)
* [ ] [#7867 coord: expose table persistence name in mz_tables](https://github.com/MaterializeInc/materialize/pull/7867) (@danhhz)
* [ ] [#7863 sql: add list_agg](https://github.com/MaterializeInc/materialize/pull/7863) (@mjibson)
* [ ] [#7848 persist: add initial attempt at monitoring metrics](https://github.com/MaterializeInc/materialize/pull/7848) (@danhhz)
* [ ] [#7876 allow null sequence field in dbz sources](https://github.com/MaterializeInc/materialize/pull/7876) (@umanwizard)

</details>

**Comment by benesch** [comment]
@umanwizard I've signed off on all the above PRs that aren't my own.
