### ISSUE TITLE
doc: Source documentation restructure

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#7885]
### Motivation

The organization of our docs for sources has been a long-standing pet peeve. On one hand, there is an unnecessary amount of information duplication, and on the other the pages seem to grow wild, with no real structure that can help users navigate the content.

We should rip off the band-aid and do a full restructure that can improve not only the user experience, but also the docs maintainability.

### Proposal

**1. Create `connect/sources.md` page**

Instead of directly linking to `/sql/create-source/`, create a new `/connect/sources.md` landing page that gives users a quick-to-parse overview of all the supported sources, including high-level information about **connectors**, **formats** and **envelopes**. In contrast, `/sql/create-source` should provide lower-level information, like connector->format mapping and direct links to the dedicated connector pages.

**2. Create `/sql/create-source/<connector>.md` pages**

The current page structure is hard to parse and not intuitive to navigate. There is also an When landing on a connector page, it should be **immediate** to users:

* Formats and envelopes supported.

* Desirable features supported (_e.g._ for Kafka, surfacing "Using source metadata", "Setting start offsets", "Handling upserts" as submenu levels instead of having all the different supported features jammed under "Kafka source details"), including examples with the reference syntax. For desirable features that we explicitly know are not supported, we should still list them and link to the relevant tracking tickets, to gauge user interest and avoid repeated questions about the same set of features (_e.g._ enhanced fan-out in Kinesis Data Streams). Non-generic `WITH` options should also be associated with the respective relevant features (_i.e._ filled under the matching submenu), instead of bulked into an ever-growing list with all the _possible_ options.

* Authentication options.

**3. Adapt railroad diagrams**

Each existing connector+format page uses a subset of the railroad diagram specific to the format. This is probably the most annoying and time consuming part to sort out, though [`format spec`](https://materialize.com/docs/sql/create-source/protobuf-kafka/#format_spec) already seems to conflate the syntax for all formats.

In the future, I'd like to explore an **alternative** to the current syntax representation.

## Changelog

Touching all source docs will inevitably lead to some intense yak shaving, as it is a golden opportunity to incorporate issues that have been laying around for a while. Below is a changelog of documented and undocumented issues that will be covered as part of the restructuring.

#### Kafka + Redpanda (fixed in #10678)

~- [x] https://github.com/MaterializeInc/materialize/issues/9611~
~- [x] https://github.com/MaterializeInc/materialize/pull/9643~
~- [x] https://github.com/MaterializeInc/materialize/issues/7645~
~- [x] https://github.com/MaterializeInc/materialize/pull/9997 / https://github.com/MaterializeInc/materialize/issues/10257~

~**Undocumented issues**~

~- [x] Replace `mz_kafka_consumer_partitions` with `mz_kafka_source_statistics` for the `statistics_interval_ms` configuration option (related to #8904).~
~- [x] [Basic HTTP authentication](https://docs.confluent.io/platform/current/security/basic-auth.html#basic-auth-sr) for schema registry is supported, but undocumented.~

#### Kinesis Data Streams (fixed in #10914)

- [ ] https://github.com/MaterializeInc/materialize/issues/9652 (also applies to S3)
~- [x] https://github.com/MaterializeInc/materialize/issues/9616~

~**Undocumented issues**~

~- [x] Replace mentions to Rusoto’s `ChainProvider` with AWS Rust SDK (#8754)~

#### S3 (fixed in #10966)

~- [x] https://github.com/MaterializeInc/materialize/pull/9936~

~**Undocumented issues**~

~- [ ] Replace mentions to Rusoto’s `ChainProvider` with AWS Rust SDK (related to #8754)~

#### PostgreSQL (fixed in #10528)

~- [x] https://github.com/MaterializeInc/materialize/issues/10219~

~**Undocumented issues**~

~- [ ] Creating views with a different schema to that of the upstream source is undocumented (see [this thread](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1637684697353100))~
~- [x] Be more intentional about explaining source-specific details (_e.g._ why does the source have to be materialized?) and ensure that some FAQs are answered (see #7281).~

### Formats

- [x] https://github.com/MaterializeInc/materialize/issues/9935
- [ ] https://github.com/MaterializeInc/materialize/issues/7885

@benesch, I'd love to hear your thoughts on what kind of blurb we should provide for formats (you seemed to have some specific wants!). What would, for example, the section about Avro touch? Would it make sense to include _e.g._ supported primitive types, or something like a format->Materialize data type mapping?

### Envelopes

**Undocumented issues**

- [ ] De-emphasize `MATERIALIZE` envelope (see [this discussion](https://materializeinc.slack.com/archives/C015RHB3LDR/p1639476737167800)). Remove `/connect/materialize-cdc.md` and instead link to this page under the envelope description in `connect/sources.md`. 

<hr>

Final TODO:

- [ ] Update [developer docs](https://github.com/MaterializeInc/materialize/tree/main/doc/user)

👹

**Comment by benesch** [comment]
> What would, for example, the section about Avro touch? Would it make sense to include e.g. supported primitive types, or something like a format->Materialize data type mapping?

Yeah, exactly! We're missing a (semi-)formal specification of _how_ the formats actually work. That's the data type mapping, the column name mapping, a list of what other format features might not be supported, etc. Writing this all up would push us to uncover and fix issues like #9723.

**Comment by morsapaes** [comment]
Follow-ups:

- Kafka: https://github.com/MaterializeInc/materialize/pull/10678#issuecomment-1048117861
