### ISSUE TITLE
release: v0.9.2-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#8108]
The following PRs in [`v0.9.2-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.2-rc1) require review:
* [x] [#7919 upgrade test: do not test INTERVAL types that are not supported](https://github.com/MaterializeInc/materialize/pull/7919) (@philip-stoev)
* [x] [#7932 AWS client construction logs should be debug level](https://github.com/MaterializeInc/materialize/pull/7932) (@quodlibetor)
* [x] [#7936 Upsert format deprecated](https://github.com/MaterializeInc/materialize/pull/7936) (@msudberg)
* [x] [#7956 s3 source: Improve logging](https://github.com/MaterializeInc/materialize/pull/7956) (@quodlibetor)
* [x] [#7967 mzbuild: fix double compile bug](https://github.com/MaterializeInc/materialize/pull/7967) (@benesch)
* [x] [#7887 coord: allow booting mz w/ user indexes disabled](https://github.com/MaterializeInc/materialize/pull/7887) (@sploiselle)
* [x] [#7986 mzbuild: fix missing space when building on linux](https://github.com/MaterializeInc/materialize/pull/7986) (@benesch)
* [x] [#7988 doc/user: trivial change to force redeploy](https://github.com/MaterializeInc/materialize/pull/7988) (@benesch)
* [x] [#7990 deny: explicitly ban thiserror per our unwritten policy](https://github.com/MaterializeInc/materialize/pull/7990) (@benesch)
* [x] [#7917 avro-decoder: Fix incorrect return from fn push_coords](https://github.com/MaterializeInc/materialize/pull/7917) (@philip-stoev)
* [x] [#7991 deny: fix merge skew around usage of thiserror](https://github.com/MaterializeInc/materialize/pull/7991) (@benesch)
* [x] [#7998 (docs) Switch Contact link to Slack](https://github.com/MaterializeInc/materialize/pull/7998) (@ruf-io)
* [x] [#7976 Transform test: Streamline transform debugging.](https://github.com/MaterializeInc/materialize/pull/7976) (@wangandi)
* [x] [#7951 Don't imply that source data comes from a database](https://github.com/MaterializeInc/materialize/pull/7951) (@msudberg)
* [x] [#8067 python: avoid invalid reference on module docstring](https://github.com/MaterializeInc/materialize/pull/8067) (@benesch)
* [x] [#8070 persistence: a simple test for table persistence](https://github.com/MaterializeInc/materialize/pull/8070) (@philip-stoev)
* [x] [#8038 coord: structure non-materialized sources error](https://github.com/MaterializeInc/materialize/pull/8038) (@sploiselle)
* [x] [#8075 update OpenSSL to fix security advisories](https://github.com/MaterializeInc/materialize/pull/8075) (@umanwizard)
* [x] [#8079 docs: ALTER INDEX ... SET ENABLED](https://github.com/MaterializeInc/materialize/pull/8079) (@sploiselle)
* [x] [#8080 docs: update ALTER INDEX diagram](https://github.com/MaterializeInc/materialize/pull/8080) (@asenac)
* [x] [#8087 (docs) Style update to fix image refs, tabs and nav](https://github.com/MaterializeInc/materialize/pull/8087) (@ruf-io)
* [x] [#8088 (docs) Fix sidebar imgs](https://github.com/MaterializeInc/materialize/pull/8088) (@ruf-io)
* [x] [#8103 Various changes to release.json](https://github.com/MaterializeInc/materialize/pull/8103) (@umanwizard)
* [x] [#8105 Don't print all the tags; they are too wide for most screens.](https://github.com/MaterializeInc/materialize/pull/8105) (@umanwizard)
* [x] [#8104 Tweaks to new documentation home page](https://github.com/MaterializeInc/materialize/pull/8104) (@msudberg)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#7912 ci/deploy: fix twine paths during upload](https://github.com/MaterializeInc/materialize/pull/7912) (@benesch)
* [ ] [#7919 upgrade test: do not test INTERVAL types that are not supported](https://github.com/MaterializeInc/materialize/pull/7919) (@philip-stoev)
* [ ] [#7874 metrics frequency: Separate from instrospection frequency](https://github.com/MaterializeInc/materialize/pull/7874) (@antiguru)
* [ ] [#7922 coord: assign error code to "no complete timestamps" error](https://github.com/MaterializeInc/materialize/pull/7922) (@petrosagg)
* [ ] [#7920 sql: show connector type in SHOW FULL SOURCES](https://github.com/MaterializeInc/materialize/pull/7920) (@petrosagg)
* [ ] [#7930 Provide a better error message for DROP MATERIALIZED VIEW](https://github.com/MaterializeInc/materialize/pull/7930) (@quodlibetor)
* [ ] [#7910 persist: rename some confusingly named things before it gets too late](https://github.com/MaterializeInc/materialize/pull/7910) (@danhhz)
* [ ] [#7934 coord: correctly clean up read transactions on terminate](https://github.com/MaterializeInc/materialize/pull/7934) (@mjibson)
* [ ] [#7914 MZFROM ubuntu-base, and Dependabot for base image](https://github.com/MaterializeInc/materialize/pull/7914) (@alex-hunt-materialize)
* [ ] [#7932 AWS client construction logs should be debug level](https://github.com/MaterializeInc/materialize/pull/7932) (@quodlibetor)
* [ ] [#7892 Move Materialized source details out of individual CREATE SOURCE page](https://github.com/MaterializeInc/materialize/pull/7892) (@msudberg)
* [ ] [#7931 Fix mkrelease dependencies](https://github.com/MaterializeInc/materialize/pull/7931) (@quodlibetor)
* [ ] [#7937 coord: send each mz_metrics record and its future retraction atomically](https://github.com/MaterializeInc/materialize/pull/7937) (@danhhz)
* [ ] [#7943 build(deps): bump enum-kinds from 0.5.0 to 0.5.1](https://github.com/MaterializeInc/materialize/pull/7943) (@dependabot[bot])
* [ ] [#7944 build(deps): bump predicates from 2.0.1 to 2.0.2](https://github.com/MaterializeInc/materialize/pull/7944) (@dependabot[bot])
* [ ] [#7946 build(deps): bump timely from `a410670` to `2c2a054`](https://github.com/MaterializeInc/materialize/pull/7946) (@dependabot[bot])
* [ ] [#7947 build(deps): bump tracing-subscriber from 0.2.19 to 0.2.20](https://github.com/MaterializeInc/materialize/pull/7947) (@dependabot[bot])
* [ ] [#7948 build(deps): bump openssl from 0.10.35 to 0.10.36](https://github.com/MaterializeInc/materialize/pull/7948) (@dependabot[bot])
* [ ] [#7949 build(deps): bump dogsdogsdogs from `65d1a5a` to `d8775a3`](https://github.com/MaterializeInc/materialize/pull/7949) (@dependabot[bot])
* [ ] [#7950 build(deps): bump num_enum from 0.5.3 to 0.5.4](https://github.com/MaterializeInc/materialize/pull/7950) (@dependabot[bot])
* [ ] [#7936 Upsert format deprecated](https://github.com/MaterializeInc/materialize/pull/7936) (@msudberg)
* [ ] [#6863 coord: err instead of panic when we have a negative multiplicity in constant result](https://github.com/MaterializeInc/materialize/pull/6863) (@prcastro)
* [ ] [#7954 sql: move list_agg to mz_catalog schema](https://github.com/MaterializeInc/materialize/pull/7954) (@mjibson)
* [ ] [#7952 coord: report total insert row diffs as affected](https://github.com/MaterializeInc/materialize/pull/7952) (@mjibson)
* [ ] [#7935 persist: write META atomically](https://github.com/MaterializeInc/materialize/pull/7935) (@danhhz)
* [ ] [#7956 s3 source: Improve logging](https://github.com/MaterializeInc/materialize/pull/7956) (@quodlibetor)
* [ ] [#7962 pgcompat: add pg_catalog.pg_get_expr](https://github.com/MaterializeInc/materialize/pull/7962) (@sploiselle)
* [ ] [#7958 persist: add a delete function to Blob](https://github.com/MaterializeInc/materialize/pull/7958) (@ruchirK)
* [ ] [#7967 mzbuild: fix double compile bug](https://github.com/MaterializeInc/materialize/pull/7967) (@benesch)
* [ ] [#7960 S3: Eagerly exit SQS listener and Object downloader on shutdown](https://github.com/MaterializeInc/materialize/pull/7960) (@quodlibetor)
* [ ] [#7959 sql: support string_agg function](https://github.com/MaterializeInc/materialize/pull/7959) (@sploiselle)
* [ ] [#7961 persist: wire up MultiWriteHandle::allow_compaction](https://github.com/MaterializeInc/materialize/pull/7961) (@danhhz)
* [ ] [#7905 coord: add arg oid checking to postgres oid checker](https://github.com/MaterializeInc/materialize/pull/7905) (@mjibson)
* [ ] [#7963 persist: unbreak nemesis with trace compaction.](https://github.com/MaterializeInc/materialize/pull/7963) (@ruchirK)
* [ ] [#7827 coord: design doc for catalog-only mode](https://github.com/MaterializeInc/materialize/pull/7827) (@sploiselle)
* [ ] [#7966 persist: wire up coordinator to allow compaction in persistence](https://github.com/MaterializeInc/materialize/pull/7966) (@ruchirK)
* [ ] [#7964 persist: wire up physical deletion of batches](https://github.com/MaterializeInc/materialize/pull/7964) (@ruchirK)
* [ ] [#7887 coord: allow booting mz w/ user indexes disabled](https://github.com/MaterializeInc/materialize/pull/7887) (@sploiselle)
* [ ] [#7979 coord: test INSERT affected rows](https://github.com/MaterializeInc/materialize/pull/7979) (@mjibson)
* [ ] [#7894 testdrive: add protobuf CSR schemas](https://github.com/MaterializeInc/materialize/pull/7894) (@JLDLaughlin)
* [ ] [#7981 mzbuild: don't use lld when xcompiling on macOS](https://github.com/MaterializeInc/materialize/pull/7981) (@benesch)
* [ ] [#7953 sql: support generate_series(start, stop, step)](https://github.com/MaterializeInc/materialize/pull/7953) (@JLDLaughlin)
* [ ] [#7980 Dataflow Optimization: Transfer monotonicity info through lets.](https://github.com/MaterializeInc/materialize/pull/7980) (@wangandi)
* [ ] [#7984 coord: add temp workaround for noisy log message](https://github.com/MaterializeInc/materialize/pull/7984) (@danhhz)
* [ ] [#7986 mzbuild: fix missing space when building on linux](https://github.com/MaterializeInc/materialize/pull/7986) (@benesch)
* [ ] [#7988 doc/user: trivial change to force redeploy](https://github.com/MaterializeInc/materialize/pull/7988) (@benesch)
* [ ] [#7989 interchange,testdrive: unfork serde-protobuf](https://github.com/MaterializeInc/materialize/pull/7989) (@benesch)
* [ ] [#7990 deny: explicitly ban thiserror per our unwritten policy](https://github.com/MaterializeInc/materialize/pull/7990) (@benesch)
* [ ] [#7917 avro-decoder: Fix incorrect return from fn push_coords](https://github.com/MaterializeInc/materialize/pull/7917) (@philip-stoev)
* [ ] [#7991 deny: fix merge skew around usage of thiserror](https://github.com/MaterializeInc/materialize/pull/7991) (@benesch)
* [ ] [#7985 expr: genericize generate_series](https://github.com/MaterializeInc/materialize/pull/7985) (@benesch)
* [ ] [#7992 build(deps): bump syn from 1.0.74 to 1.0.75](https://github.com/MaterializeInc/materialize/pull/7992) (@dependabot[bot])
* [ ] [#7993 build(deps): bump serde from 1.0.127 to 1.0.128](https://github.com/MaterializeInc/materialize/pull/7993) (@dependabot[bot])
* [ ] [#7994 build(deps): bump libc from 0.2.99 to 0.2.100](https://github.com/MaterializeInc/materialize/pull/7994) (@dependabot[bot])
* [ ] [#7996 debezium-avro: Convert test/debezium-avro to a Python-only mzworkflows.py test](https://github.com/MaterializeInc/materialize/pull/7996) (@philip-stoev)
* [ ] [#7899 metrics: Add DeleteOnDropWrapper to enforce dropping](https://github.com/MaterializeInc/materialize/pull/7899) (@antiguru)
* [ ] [#7998 (docs) Switch Contact link to Slack](https://github.com/MaterializeInc/materialize/pull/7998) (@ruf-io)
* [ ] [#7976 Transform test: Streamline transform debugging.](https://github.com/MaterializeInc/materialize/pull/7976) (@wangandi)
* [ ] [#8001 sql: rename unsupported to bail_unsupported](https://github.com/MaterializeInc/materialize/pull/8001) (@benesch)
* [ ] [#7970  persist,bench: add end_to_end benchmark](https://github.com/MaterializeInc/materialize/pull/7970) (@aljoscha)
* [ ] [#8003 persist: add a batch of new monitoring metrics](https://github.com/MaterializeInc/materialize/pull/8003) (@danhhz)
* [ ] [#8012 sql: initial support for regproc](https://github.com/MaterializeInc/materialize/pull/8012) (@mjibson)
* [ ] [#8004 update gitignore](https://github.com/MaterializeInc/materialize/pull/8004) (@umanwizard)
* [ ] [#8006 Continue 0.9.2 dev](https://github.com/MaterializeInc/materialize/pull/8006) (@umanwizard)
* [ ] [#8011 fix APT package breakage on Ubuntu < 20.04](https://github.com/MaterializeInc/materialize/pull/8011) (@umanwizard)
* [ ] [#8018 transform/reduction: Avoid copying constants](https://github.com/MaterializeInc/materialize/pull/8018) (@antiguru)
* [ ] [#8019 coord/broadcast: Avoid clone for last worker](https://github.com/MaterializeInc/materialize/pull/8019) (@antiguru)
* [ ] [#8016 row: Manually implement Clone](https://github.com/MaterializeInc/materialize/pull/8016) (@antiguru)
* [ ] [#8024 update crossbeam](https://github.com/MaterializeInc/materialize/pull/8024) (@umanwizard)
* [ ] [#8020 persist: ignore seal notifications before the snapshot in listen_source](https://github.com/MaterializeInc/materialize/pull/8020) (@ruchirK)
* [ ] [#8025 sql: support array_in and regproc equality](https://github.com/MaterializeInc/materialize/pull/8025) (@mjibson)
* [ ] [#7978 coord,pgwire: plumb down implicit transaction failures to pgwire](https://github.com/MaterializeInc/materialize/pull/7978) (@mjibson)
* [ ] [#8033 persist: introduce a placeholder impl of Log to prevent accidental usage](https://github.com/MaterializeInc/materialize/pull/8033) (@danhhz)
* [ ] [#8030 coord: use 'array_in'::regproc in pg_type builtin view](https://github.com/MaterializeInc/materialize/pull/8030) (@sploiselle)
* [ ] [#8034 persist: version the serialization of BlobMeta](https://github.com/MaterializeInc/materialize/pull/8034) (@danhhz)
* [ ] [#8014 persist: better compaction policy](https://github.com/MaterializeInc/materialize/pull/8014) (@ruchirK)
* [ ] [#7977 persist: relax the requirements on allow_compaction and seal](https://github.com/MaterializeInc/materialize/pull/7977) (@ruchirK)
* [ ] [#8037 persist: only instantiate persist details for tables serialized in th…](https://github.com/MaterializeInc/materialize/pull/8037) (@ruchirK)
* [ ] [#8032 coord: add various pg_catalog entries](https://github.com/MaterializeInc/materialize/pull/8032) (@mjibson)
* [ ] [#7929 metrics scraping: Increase default to 30s](https://github.com/MaterializeInc/materialize/pull/7929) (@antiguru)
* [ ] [#7457 Design doc proposing the replacement of HirRelationExpr with a Query Graph Model based representation](https://github.com/MaterializeInc/materialize/pull/7457) (@asenac)
* [ ] [#7997 debezium: A end-to-end test with SQL Server and Debezium](https://github.com/MaterializeInc/materialize/pull/7997) (@philip-stoev)
* [ ] [#7951 Don't imply that source data comes from a database](https://github.com/MaterializeInc/materialize/pull/7951) (@msudberg)
* [ ] [#7957 Add note on Avro case-sensitivity](https://github.com/MaterializeInc/materialize/pull/7957) (@msudberg)
* [ ] [#8042 Set initial auth timeout to 10 seconds uniformly](https://github.com/MaterializeInc/materialize/pull/8042) (@quodlibetor)
* [ ] [#8035 persist: clean up antichain usage](https://github.com/MaterializeInc/materialize/pull/8035) (@ruchirK)
* [ ] [#8053 coord: add temp workaround for noisy log message](https://github.com/MaterializeInc/materialize/pull/8053) (@ruchirK)
* [ ] [#8051 coord: save each table's persist name in the catalog](https://github.com/MaterializeInc/materialize/pull/8051) (@danhhz)
* [ ] [#8028 Transform testing: Trim spaces from end of all lines of an explanation](https://github.com/MaterializeInc/materialize/pull/8028) (@wangandi)
* [ ] [#8056 coord: add column defaults to various catalogs](https://github.com/MaterializeInc/materialize/pull/8056) (@mjibson)
* [ ] [#8055 JSON-formatted exactly-once sinks must use Avro for the format of the consistency topic  ](https://github.com/MaterializeInc/materialize/pull/8055) (@msudberg)
* [ ] [#7773 coord: support AS OF for unmaterialized sources](https://github.com/MaterializeInc/materialize/pull/7773) (@mjibson)
* [ ] [#8064 mzcloud-cli: support local development environments](https://github.com/MaterializeInc/materialize/pull/8064) (@benesch)
* [ ] [#8063 Add (rudimentary) `bin/cloudbench` for running remote load tests, benchmarks, etc. in the scratch account.](https://github.com/MaterializeInc/materialize/pull/8063) (@umanwizard)
* [ ] [#8013 [dataflow] Choose most expressions as key for `Get`](https://github.com/MaterializeInc/materialize/pull/8013) (@frankmcsherry)
* [ ] [#8067 python: avoid invalid reference on module docstring](https://github.com/MaterializeInc/materialize/pull/8067) (@benesch)
* [ ] [#8062 mzworkflows: add options, migrate workflow](https://github.com/MaterializeInc/materialize/pull/8062) (@sploiselle)
* [ ] [#8052  ddl,sinks: make error message around JSON consistency more helpful ](https://github.com/MaterializeInc/materialize/pull/8052) (@aljoscha)
* [ ] [#8070 persistence: a simple test for table persistence](https://github.com/MaterializeInc/materialize/pull/8070) (@philip-stoev)
* [ ] [#8072 avro: fix parsing of nested types](https://github.com/MaterializeInc/materialize/pull/8072) (@aljoscha)
* [ ] [#7897 docs: Add guide for Postgres CDC](https://github.com/MaterializeInc/materialize/pull/7897) (@morsapaes)
* [ ] [#8074 kafka: allow manual override of `enable.idempotence`](https://github.com/MaterializeInc/materialize/pull/8074) (@aljoscha)
* [ ] [#8065 Dataflow/optimization: Fix MFP inlining so it doesn't always happen](https://github.com/MaterializeInc/materialize/pull/8065) (@wangandi)
* [ ] [#8038 coord: structure non-materialized sources error](https://github.com/MaterializeInc/materialize/pull/8038) (@sploiselle)
* [ ] [#8076 coord: structure unsupported feature errors](https://github.com/MaterializeInc/materialize/pull/8076) (@sploiselle)
* [ ] [#8027 coord: support enabling disabled indexes at runtime](https://github.com/MaterializeInc/materialize/pull/8027) (@sploiselle)
* [ ] [#8075 update OpenSSL to fix security advisories](https://github.com/MaterializeInc/materialize/pull/8075) (@umanwizard)
* [ ] [#8079 docs: ALTER INDEX ... SET ENABLED](https://github.com/MaterializeInc/materialize/pull/8079) (@sploiselle)
* [ ] [#8080 docs: update ALTER INDEX diagram](https://github.com/MaterializeInc/materialize/pull/8080) (@asenac)
* [ ] [#8082 transform: Implement fusion/negate](https://github.com/MaterializeInc/materialize/pull/8082) (@antiguru)
* [ ] [#8083 Revert "avro: fix parsing of nested types"](https://github.com/MaterializeInc/materialize/pull/8083) (@aljoscha)
* [ ] [#7507  Implement new CSV WITH HEADER COLUMNS syntax](https://github.com/MaterializeInc/materialize/pull/7507) (@quodlibetor)
* [ ] [#8085 Import recent changes into our Docker dashboard](https://github.com/MaterializeInc/materialize/pull/8085) (@quodlibetor)
* [ ] [#7620 (docs) Update docs style](https://github.com/MaterializeInc/materialize/pull/7620) (@ruf-io)
* [ ] [#8087 (docs) Style update to fix image refs, tabs and nav](https://github.com/MaterializeInc/materialize/pull/8087) (@ruf-io)
* [ ] [#8088 (docs) Fix sidebar imgs](https://github.com/MaterializeInc/materialize/pull/8088) (@ruf-io)
* [ ] [#8089 build(deps): bump sysinfo from 0.20.0 to 0.20.1](https://github.com/MaterializeInc/materialize/pull/8089) (@dependabot[bot])
* [ ] [#8090 build(deps): bump procfs from 0.9.1 to 0.10.1](https://github.com/MaterializeInc/materialize/pull/8090) (@dependabot[bot])
* [ ] [#8091 build(deps): bump tokio from 1.10.0 to 1.10.1](https://github.com/MaterializeInc/materialize/pull/8091) (@dependabot[bot])
* [ ] [#8092 build(deps): bump differential-dataflow from `d8775a3` to `8a5efd7`](https://github.com/MaterializeInc/materialize/pull/8092) (@dependabot[bot])
* [ ] [#8094 build(deps): bump timely from `2c2a054` to `94102cd`](https://github.com/MaterializeInc/materialize/pull/8094) (@dependabot[bot])
* [ ] [#8097 build(deps): bump libc from 0.2.100 to 0.2.101](https://github.com/MaterializeInc/materialize/pull/8097) (@dependabot[bot])
* [ ] [#8093 build(deps): bump tiberius from 0.6.2 to 0.6.3](https://github.com/MaterializeInc/materialize/pull/8093) (@dependabot[bot])
* [ ] [#8099 build(deps): bump serde_json from 1.0.66 to 1.0.67](https://github.com/MaterializeInc/materialize/pull/8099) (@dependabot[bot])
* [ ] [#8098 build(deps): bump serde from 1.0.128 to 1.0.130](https://github.com/MaterializeInc/materialize/pull/8098) (@dependabot[bot])
* [ ] [#8096 build(deps): bump sha-1 from 0.9.7 to 0.9.8](https://github.com/MaterializeInc/materialize/pull/8096) (@dependabot[bot])
* [ ] [#7913 S3: support FORMAT CSV WITH HEADERS (col, ...)](https://github.com/MaterializeInc/materialize/pull/7913) (@quodlibetor)
* [ ] [#8103 Various changes to release.json](https://github.com/MaterializeInc/materialize/pull/8103) (@umanwizard)
* [ ] [#8105 Don't print all the tags; they are too wide for most screens.](https://github.com/MaterializeInc/materialize/pull/8105) (@umanwizard)
* [ ] [#8104 Tweaks to new documentation home page](https://github.com/MaterializeInc/materialize/pull/8104) (@msudberg)
* [ ] [#8106 release checklist: Document the new unreviewed PRs workflow](https://github.com/MaterializeInc/materialize/pull/8106) (@quodlibetor)

</details>

**Comment by benesch** [comment]
Signing off on @quodlibetor's changes.

**Comment by quodlibetor** [comment]
All others LGTM
