### ISSUE TITLE
[Epic] Support ARM

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#8140]
## Summary

Support running `environmentd` and `clusterd` on ARM64 in our production environment.

## Details

x64 no longer dominates the market. ARM is gaining traction on the desktop (see the M1 chip in Macs) and on the server (see AWS Graviton).

We'll use the terms "ARM", "ARM64", and "AArch64" interchangeably throughout this epic.

It's time to think about a path to official support for Materialize on ARM64. ~I don't want to commit to any timelines, but~ here's what we'd need to do:

  - [x] Declare that Materialize on ARM64 is in beta
  - [x] #5917
  - [x] Build ARM64 binaries in CI
  - [x] Run tests on ARM64 in CI
  - [x] Ship multi-arch Docker images
  - [x] https://github.com/MaterializeInc/cloud/issues/8391
  - Fix ARM64-only issues
    - [x] https://github.com/MaterializeInc/materialize/issues/24818
    - [x] ~~https://github.com/MaterializeInc/materialize/issues/24644~~ (not arm64-specific)
    - [x] https://github.com/MaterializeInc/materialize/issues/25145
  - [x] Validate performance on ARM
  - [x] [Migrate `environmentd` to ARM64 in production](https://github.com/MaterializeInc/cloud/issues/9014)
  - [x] Migrate `clusterd` to ARM64 in production (https://github.com/MaterializeInc/cloud/issues/8668)

@philip-stoev had a great list of the tests we'd need to run to. Here's the Slack discussion: https://materializeinc.slack.com/archives/CM7ATT65S/p1629731911322400. I don't want to make that list public without Philip's permission.

## Decision log

* *4 February 2024.* Convert this issue to a proper epic under the "Global" team.

**Comment by benesch** [comment]
@philip-stoev, sending this one your way! All that remains here is figuring out how much more testing we need to do to declare that Materialize officially supports ARM.

**Comment by def-** [comment]
I did a very simple PR to run our existing tests+SLT+nightly suites against arm64: https://github.com/MaterializeInc/materialize/pull/18756
These 3 issues popped up:
- https://github.com/MaterializeInc/materialize/issues/18746
- https://github.com/MaterializeInc/materialize/issues/18744
- https://github.com/MaterializeInc/materialize/issues/18757

**Comment by benesch** [comment]
Since https://github.com/MaterializeInc/cloud/pull/9462 shipped, we're fully off of x86 nodes in production, even for legacy clusters using T-shirt sizes! 🎉
