### ISSUE TITLE
release: v0.9.4-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#8284]
The following PRs in [`v0.9.4-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.4-rc1) require review:
* [x] [#8123 sql: fix max(int2) func selection](https://github.com/MaterializeInc/materialize/pull/8123) (@sploiselle)
* [x] [#8127 Docs navbar](https://github.com/MaterializeInc/materialize/pull/8127) (@msudberg)
* [x] [#8130 New defaults for scratch subnets/SGs](https://github.com/MaterializeInc/materialize/pull/8130) (@umanwizard)
* [x] [#8139 docs: fix typo in join doc](https://github.com/MaterializeInc/materialize/pull/8139) (@sploiselle)
* [x] [#8138 Add `confluent` profile, and avro ingest benchmark as cloudbench example](https://github.com/MaterializeInc/materialize/pull/8138) (@umanwizard)
* [x] [#8146 Correctly report CPU totals for each trial in avro_ingest.py](https://github.com/MaterializeInc/materialize/pull/8146) (@umanwizard)
* [x] [#8153 Add new release notes to docs home page](https://github.com/MaterializeInc/materialize/pull/8153) (@msudberg)
* [x] [#8186 doc: re-add RM Neue fonts for railroad diagrams](https://github.com/MaterializeInc/materialize/pull/8186) (@petrosagg)
* [x] [#8191 expr: fix typo that makes rustdoc fail](https://github.com/MaterializeInc/materialize/pull/8191) (@petrosagg)
* [x] [#8206 deps: add missing twine dep](https://github.com/MaterializeInc/materialize/pull/8206) (@benesch)
* [x] [#8214 deps: upgrade to num-bigint v0.4.2](https://github.com/MaterializeInc/materialize/pull/8214) (@benesch)
* [x] [#8222 tb: bump dependencies and add mysql 8 parameter](https://github.com/MaterializeInc/materialize/pull/8222) (@benesch)
* [x] [#8243 doc: fix minor typo](https://github.com/MaterializeInc/materialize/pull/8243) (@benesch)
* [x] [#8152 doc: Cloud Open Beta updates](https://github.com/MaterializeInc/materialize/pull/8152) (@msudberg)
* [x] [#8256 (docs) add redirect from old to new cloud quickstart url](https://github.com/MaterializeInc/materialize/pull/8256) (@ruf-io)
* [x] [#8258 Cloud redirect](https://github.com/MaterializeInc/materialize/pull/8258) (@msudberg)
* [x] [#8260 Revert "materialized: enable persistent system tables by default"](https://github.com/MaterializeInc/materialize/pull/8260) (@danhhz)
* [x] [#8267 Cloud doc cleanup](https://github.com/MaterializeInc/materialize/pull/8267) (@msudberg)
* [x] [#8282 Cs3 envelope](https://github.com/MaterializeInc/materialize/pull/8282) (@msudberg)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#7903 How to distinguish between no data and a timeout](https://github.com/MaterializeInc/materialize/pull/7903) (@awang)
* [ ] [#7945 build(deps): bump whoami from 1.1.2 to 1.1.3](https://github.com/MaterializeInc/materialize/pull/7945) (@dependabot[bot])
* [ ] [#8100 build(deps): bump hyper from 0.14.11 to 0.14.12](https://github.com/MaterializeInc/materialize/pull/8100) (@dependabot[bot])
* [ ] [#8109 Prepare next phase of development: v0.9.3](https://github.com/MaterializeInc/materialize/pull/8109) (@quodlibetor)
* [ ] [#8102 build(deps): bump bytes from 1.0.1 to 1.1.0](https://github.com/MaterializeInc/materialize/pull/8102) (@dependabot[bot])
* [ ] [#8061 .github: add a PR template](https://github.com/MaterializeInc/materialize/pull/8061) (@benesch)
* [ ] [#7704 Framework for defining functions as individual units](https://github.com/MaterializeInc/materialize/pull/7704) (@petrosagg)
* [ ] [#8121 release: Add a script to create the release qualification dashboard links](https://github.com/MaterializeInc/materialize/pull/8121) (@quodlibetor)
* [ ] [#8118 chaos: Kafka requires Zookeeper to be present at startup](https://github.com/MaterializeInc/materialize/pull/8118) (@quodlibetor)
* [ ] [#8123 sql: fix max(int2) func selection](https://github.com/MaterializeInc/materialize/pull/8123) (@sploiselle)
* [ ] [#8122 Fix 8119 with revised DD](https://github.com/MaterializeInc/materialize/pull/8122) (@frankmcsherry)
* [ ] [#8127 Docs navbar](https://github.com/MaterializeInc/materialize/pull/8127) (@msudberg)
* [ ] [#8130 New defaults for scratch subnets/SGs](https://github.com/MaterializeInc/materialize/pull/8130) (@umanwizard)
* [ ] [#8131 make pr template checkboxes a list](https://github.com/MaterializeInc/materialize/pull/8131) (@elindsey)
* [ ] [#8139 docs: fix typo in join doc](https://github.com/MaterializeInc/materialize/pull/8139) (@sploiselle)
* [ ] [#8128 (docs) Update font CSS](https://github.com/MaterializeInc/materialize/pull/8128) (@ruf-io)
* [ ] [#8138 Add `confluent` profile, and avro ingest benchmark as cloudbench example](https://github.com/MaterializeInc/materialize/pull/8138) (@umanwizard)
* [ ] [#8146 Correctly report CPU totals for each trial in avro_ingest.py](https://github.com/MaterializeInc/materialize/pull/8146) (@umanwizard)
* [ ] [#8148 release: v0.9.2](https://github.com/MaterializeInc/materialize/pull/8148) (@quodlibetor)
* [ ] [#8110 Add some missed features to release notes](https://github.com/MaterializeInc/materialize/pull/8110) (@quodlibetor)
* [ ] [#8084 dataflow: use CSR protobuf schemas](https://github.com/MaterializeInc/materialize/pull/8084) (@JLDLaughlin)
* [ ] [#8153 Add new release notes to docs home page](https://github.com/MaterializeInc/materialize/pull/8153) (@msudberg)
* [ ] [#8154 interchange: add new protobuf decode module](https://github.com/MaterializeInc/materialize/pull/8154) (@JLDLaughlin)
* [ ] [#8157 dataflow: Alias the spine type](https://github.com/MaterializeInc/materialize/pull/8157) (@antiguru)
* [ ] [#8164 build(deps): bump futures from 0.3.16 to 0.3.17](https://github.com/MaterializeInc/materialize/pull/8164) (@dependabot[bot])
* [ ] [#8165 build(deps): bump include_dir from 0.6.1 to 0.6.2](https://github.com/MaterializeInc/materialize/pull/8165) (@dependabot[bot])
* [ ] [#8166 build(deps): bump tiberius from 0.6.3 to 0.6.4](https://github.com/MaterializeInc/materialize/pull/8166) (@dependabot[bot])
* [ ] [#8167 build(deps): bump cc from 1.0.69 to 1.0.70](https://github.com/MaterializeInc/materialize/pull/8167) (@dependabot[bot])
* [ ] [#8170 build(deps): bump tokio-util from 0.6.7 to 0.6.8](https://github.com/MaterializeInc/materialize/pull/8170) (@dependabot[bot])
* [ ] [#8171 build(deps): bump timely from `94102cd` to `c5195eb`](https://github.com/MaterializeInc/materialize/pull/8171) (@dependabot[bot])
* [ ] [#8172 build(deps): bump sysinfo from 0.20.1 to 0.20.3](https://github.com/MaterializeInc/materialize/pull/8172) (@dependabot[bot])
* [ ] [#8174 build(deps): bump ubuntu from focal-20210723 to focal-20210827 in /misc/ubuntu-base-image](https://github.com/MaterializeInc/materialize/pull/8174) (@dependabot[bot])
* [ ] [#8169 build(deps): bump flate2 from 1.0.20 to 1.0.21](https://github.com/MaterializeInc/materialize/pull/8169) (@dependabot[bot])
* [ ] [#8175 build(deps): bump ordered-float from 2.7.0 to 2.8.0](https://github.com/MaterializeInc/materialize/pull/8175) (@dependabot[bot])
* [ ] [#8176 build(deps): bump proc-macro2 from 1.0.28 to 1.0.29](https://github.com/MaterializeInc/materialize/pull/8176) (@dependabot[bot])
* [ ] [#8179 build(deps): bump ctor from 0.1.20 to 0.1.21](https://github.com/MaterializeInc/materialize/pull/8179) (@dependabot[bot])
* [ ] [#8173 build(deps): bump ubuntu from focal-20210723 to focal-20210827 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/8173) (@dependabot[bot])
* [ ] [#8180 build(deps): bump structopt from 0.3.22 to 0.3.23](https://github.com/MaterializeInc/materialize/pull/8180) (@dependabot[bot])
* [ ] [#8177 build(deps): bump syn from 1.0.75 to 1.0.76](https://github.com/MaterializeInc/materialize/pull/8177) (@dependabot[bot])
* [ ] [#8178 build(deps): bump tokio from 1.10.1 to 1.11.0](https://github.com/MaterializeInc/materialize/pull/8178) (@dependabot[bot])
* [ ] [#8186 doc: re-add RM Neue fonts for railroad diagrams](https://github.com/MaterializeInc/materialize/pull/8186) (@petrosagg)
* [ ] [#8077 persist: add a test to catch changes in the end-to-end encoding](https://github.com/MaterializeInc/materialize/pull/8077) (@danhhz)
* [ ] [#8188 doc: fix typos in system-catalog.md](https://github.com/MaterializeInc/materialize/pull/8188) (@uce)
* [ ] [#8190 docs: switch railroad diagrams to Inter font](https://github.com/MaterializeInc/materialize/pull/8190) (@petrosagg)
* [ ] [#8191 expr: fix typo that makes rustdoc fail](https://github.com/MaterializeInc/materialize/pull/8191) (@petrosagg)
* [ ] [#8160 sql: support ORDER BY in aggregates](https://github.com/MaterializeInc/materialize/pull/8160) (@mjibson)
* [ ] [#8192 sqllogictest: add a fail-fast flag](https://github.com/MaterializeInc/materialize/pull/8192) (@mjibson)
* [ ] [#8193 persist: make a single-path variant of MemRegistry](https://github.com/MaterializeInc/materialize/pull/8193) (@danhhz)
* [ ] [#8196 build(deps): bump dbt from 0.20.1 to 0.20.2 in /misc/dbt-materialize](https://github.com/MaterializeInc/materialize/pull/8196) (@dependabot[bot])
* [ ] [#8187 test: DSL support for literal errors](https://github.com/MaterializeInc/materialize/pull/8187) (@asenac)
* [ ] [#8204 Don't emit schemaType when it's avro](https://github.com/MaterializeInc/materialize/pull/8204) (@umanwizard)
* [ ] [#8206 deps: add missing twine dep](https://github.com/MaterializeInc/materialize/pull/8206) (@benesch)
* [ ] [#7895 Transform: Minimize the number of non-leaves in join equivalence expressions.](https://github.com/MaterializeInc/materialize/pull/7895) (@wangandi)
* [ ] [#8214 deps: upgrade to num-bigint v0.4.2](https://github.com/MaterializeInc/materialize/pull/8214) (@benesch)
* [ ] [#8213 Fix migration for CSV Headers from materialized 0.9.1](https://github.com/MaterializeInc/materialize/pull/8213) (@quodlibetor)
* [ ] [#8141 smarter way of comparing union branches for cancellation](https://github.com/MaterializeInc/materialize/pull/8141) (@asenac)
* [ ] [#8219 reduce metric interval parameters for kafka matrix test](https://github.com/MaterializeInc/materialize/pull/8219) (@elindsey)
* [ ] [#8218 expand kafka regression coverage](https://github.com/MaterializeInc/materialize/pull/8218) (@elindsey)
* [ ] [#8220 prepare 0.9.4-dev](https://github.com/MaterializeInc/materialize/pull/8220) (@umanwizard)
* [ ] [#8031 materialized: enable persistent system tables by default](https://github.com/MaterializeInc/materialize/pull/8031) (@danhhz)
* [ ] [#8221 upgrade: Add an "upgrade-from-latest-to-current-source" test](https://github.com/MaterializeInc/materialize/pull/8221) (@quodlibetor)
* [ ] [#7864 Optimization: Projection Pushdown](https://github.com/MaterializeInc/materialize/pull/7864) (@wangandi)
* [ ] [#8222 tb: bump dependencies and add mysql 8 parameter](https://github.com/MaterializeInc/materialize/pull/8222) (@benesch)
* [ ] [#8198 persist: add Kafka persistence example](https://github.com/MaterializeInc/materialize/pull/8198) (@aljoscha)
* [ ] [#8225 exclude protobuf schema registry tests from redpanda nightly](https://github.com/MaterializeInc/materialize/pull/8225) (@elindsey)
* [ ] [#8142 dataflow: ignore trailing newline characters when decoding files](https://github.com/MaterializeInc/materialize/pull/8142) (@petrosagg)
* [ ] [#8227 Implement simple unary float SQL functions with the new method](https://github.com/MaterializeInc/materialize/pull/8227) (@petrosagg)
* [ ] [#8228 Add docs for bin/scratch](https://github.com/MaterializeInc/materialize/pull/8228) (@umanwizard)
* [ ] [#8230 Add docs for bin/cloudbench](https://github.com/MaterializeInc/materialize/pull/8230) (@umanwizard)
* [ ] [#8238 Support fallible SQL functions in `sqlfunc!` macro](https://github.com/MaterializeInc/materialize/pull/8238) (@petrosagg)
* [ ] [#8236 fix crash in CanonicalizeMfp transform](https://github.com/MaterializeInc/materialize/pull/8236) (@asenac)
* [ ] [#8240 Generalize sources and sinks to non-`Child` scopes](https://github.com/MaterializeInc/materialize/pull/8240) (@frankmcsherry)
* [ ] [#8243 doc: fix minor typo](https://github.com/MaterializeInc/materialize/pull/8243) (@benesch)
* [ ] [#8244 build(deps): bump timely from `c5195eb` to `4c2886b`](https://github.com/MaterializeInc/materialize/pull/8244) (@dependabot[bot])
* [ ] [#8245 build(deps): bump sha2 from 0.9.6 to 0.9.8](https://github.com/MaterializeInc/materialize/pull/8245) (@dependabot[bot])
* [ ] [#8246 build(deps): bump assert_cmd from 2.0.0 to 2.0.1](https://github.com/MaterializeInc/materialize/pull/8246) (@dependabot[bot])
* [ ] [#8248 build(deps): bump dogsdogsdogs from `8cdc534` to `7f1133a`](https://github.com/MaterializeInc/materialize/pull/8248) (@dependabot[bot])
* [ ] [#8251 sql-parser: remove dependency on repr](https://github.com/MaterializeInc/materialize/pull/8251) (@mjibson)
* [ ] [#8152 doc: Cloud Open Beta updates](https://github.com/MaterializeInc/materialize/pull/8152) (@msudberg)
* [ ] [#8256 (docs) add redirect from old to new cloud quickstart url](https://github.com/MaterializeInc/materialize/pull/8256) (@ruf-io)
* [ ] [#8258 Cloud redirect](https://github.com/MaterializeInc/materialize/pull/8258) (@msudberg)
* [ ] [#8257 *: reduce dependencies on ore by sql-parser](https://github.com/MaterializeInc/materialize/pull/8257) (@mjibson)
* [ ] [#8260 Revert "materialized: enable persistent system tables by default"](https://github.com/MaterializeInc/materialize/pull/8260) (@danhhz)
* [ ] [#8155 doc: CSR + Protobuf support for sources](https://github.com/MaterializeInc/materialize/pull/8155) (@JLDLaughlin)
* [ ] [#8249 build(deps): bump anyhow from 1.0.43 to 1.0.44](https://github.com/MaterializeInc/materialize/pull/8249) (@dependabot[bot])
* [ ] [#8112 Update release checklist](https://github.com/MaterializeInc/materialize/pull/8112) (@quodlibetor)
* [ ] [#8151 s3: Stream results to dataflow instead of loading entire objects](https://github.com/MaterializeInc/materialize/pull/8151) (@quodlibetor)
* [ ] [#8261 doc: remove JSON Kafka sinks from known limitations](https://github.com/MaterializeInc/materialize/pull/8261) (@JLDLaughlin)
* [ ] [#8161 testdrive: test protobuf + CSR schemas with imports](https://github.com/MaterializeInc/materialize/pull/8161) (@JLDLaughlin)
* [ ] [#8267 Cloud doc cleanup](https://github.com/MaterializeInc/materialize/pull/8267) (@msudberg)
* [ ] [#8265 Deploy entire "misc/python" directory as package to remote machine in cloudbench](https://github.com/MaterializeInc/materialize/pull/8265) (@umanwizard)
* [ ] [#8232 doc: document transactions: BEGIN, COMMIT, ROLLBACK](https://github.com/MaterializeInc/materialize/pull/8232) (@mjibson)
* [ ] [#8266 coord: send warning on implicit txn w/ only COMMIT or ROLLBACK](https://github.com/MaterializeInc/materialize/pull/8266) (@sploiselle)
* [ ] [#8274 doc/user: remove references to catalog-only mode](https://github.com/MaterializeInc/materialize/pull/8274) (@benesch)
* [ ] [#8212 persist: make getting a snapshot fast (don't block on fetching the data)](https://github.com/MaterializeInc/materialize/pull/8212) (@danhhz)
* [ ] [#8277 make avro_ingest.py work with versions of Mz before #7922](https://github.com/MaterializeInc/materialize/pull/8277) (@umanwizard)
* [ ] [#8280 sql-parser: allow keywords in field access expressions](https://github.com/MaterializeInc/materialize/pull/8280) (@benesch)
* [ ] [#8242 sql: error on unsupported transaction options](https://github.com/MaterializeInc/materialize/pull/8242) (@mjibson)
* [ ] [#8281 expr: make `csv_extract` return an Iterator](https://github.com/MaterializeInc/materialize/pull/8281) (@petrosagg)
* [ ] [#8282 Cs3 envelope](https://github.com/MaterializeInc/materialize/pull/8282) (@msudberg)

</details>
