### ISSUE TITLE
release: v0.9.4-rc2 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#8305]
The following PRs in [`v0.9.4-rc2`](https://github.com/MaterializeInc/materialize/tree/v0.9.4-rc2) require review:
* [x] [#8264 Exactly once](https://github.com/MaterializeInc/materialize/pull/8264) (@msudberg)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#8276 Support generic `Datum` arguments in sqlfunc!](https://github.com/MaterializeInc/materialize/pull/8276) (@petrosagg)
* [ ] [#8285 Prepare 0.9.5 dev](https://github.com/MaterializeInc/materialize/pull/8285) (@umanwizard)
* [ ] [#7688 sql, coord: rearrange types for CreateView(s)Plan](https://github.com/MaterializeInc/materialize/pull/7688) (@benesch)
* [ ] [#8291 A few performance improvements in the optimizer](https://github.com/MaterializeInc/materialize/pull/8291) (@asenac)
* [ ] [#8264 Exactly once](https://github.com/MaterializeInc/materialize/pull/8264) (@msudberg)
* [ ] [#8300 persist: fix bug making compaction too aggressive when under high request load](https://github.com/MaterializeInc/materialize/pull/8300) (@danhhz)
* [ ] [#8295 add --env option to mkrelease dashboard_links](https://github.com/MaterializeInc/materialize/pull/8295) (@umanwizard)
* [ ] [#8296 S3 Chunked read handle retry of GZIP streams](https://github.com/MaterializeInc/materialize/pull/8296) (@quodlibetor)
* [ ] [#8287 coord: use all indexes per id in timestamp determination](https://github.com/MaterializeInc/materialize/pull/8287) (@mjibson)
* [ ] [#8299 Store cloudbench results in S3](https://github.com/MaterializeInc/materialize/pull/8299) (@umanwizard)
* [ ] [#8143 dataflow/logging: Avoid count in log analysis, perf improvements](https://github.com/MaterializeInc/materialize/pull/8143) (@antiguru)
* [ ] [#8294 mzworkflows: a dedicated documentation page for Python-based workflows](https://github.com/MaterializeInc/materialize/pull/8294) (@philip-stoev)
* [ ] [#8292 expr-test-util: add support for constant error relations](https://github.com/MaterializeInc/materialize/pull/8292) (@asenac)

</details>
