### ISSUE TITLE
release: v0.9.5-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#8375]
The following PRs in [`v0.9.5-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.5-rc1) require review:
* [x] [#8307 Prepare 0.9.5 (again)](https://github.com/MaterializeInc/materialize/pull/8307) (@umanwizard)
* [x] [#8304 correctly interpret tag.prerelease](https://github.com/MaterializeInc/materialize/pull/8304) (@umanwizard)
* [x] [#8309 Revert "Revert "Revert "materialized: enable persistent system tables…](https://github.com/MaterializeInc/materialize/pull/8309) (@danhhz)
* [x] [#8320 mzworkflows: fix typo in documentation](https://github.com/MaterializeInc/materialize/pull/8320) (@philip-stoev)
* [x] [#8332 Continue 0.9.5 dev](https://github.com/MaterializeInc/materialize/pull/8332) (@umanwizard)
