### ISSUE TITLE
release: v0.9.6-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#8452]
The following PRs in [`v0.9.6-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.6-rc1) require review:
* [x] [#8365 play: add shell.nix file](https://github.com/MaterializeInc/materialize/pull/8365) (@petrosagg)
* [x] [#8382 doc: fix release note order and wording](https://github.com/MaterializeInc/materialize/pull/8382) (@petrosagg)
* [x] [#8385 Release note bump](https://github.com/MaterializeInc/materialize/pull/8385) (@msudberg)
* [x] [#8403 release: v0.9.5](https://github.com/MaterializeInc/materialize/pull/8403) (@quodlibetor)
* [x] [#8406 doc: Release note version bump for Docs home page  ](https://github.com/MaterializeInc/materialize/pull/8406) (@msudberg)
* [x] [#8410 docs: release note for #8021 fix](https://github.com/MaterializeInc/materialize/pull/8410) (@sploiselle)
* [x] [#8431 doc: fix typo on docs home page, shift Timelines page in SQL navigation.](https://github.com/MaterializeInc/materialize/pull/8431) (@msudberg)
* [x] [#8449 doc: Press 's' to search](https://github.com/MaterializeInc/materialize/pull/8449) (@ruf-io)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#8239 Add design doc for user access to Kafka metadata](https://github.com/MaterializeInc/materialize/pull/8239) (@quodlibetor)
* [ ] [#8314 Change "biweekly" string to "weekly", to match new release cycle](https://github.com/MaterializeInc/materialize/pull/8314) (@umanwizard)
* [ ] [#8331 Fix kinesis link in dashboard_links](https://github.com/MaterializeInc/materialize/pull/8331) (@umanwizard)
* [ ] [#8354 doc/user: avoid the term "Materialize node"](https://github.com/MaterializeInc/materialize/pull/8354) (@benesch)
* [ ] [#8326 S3 server-side resume using a resumable `AsyncRead` wrapper](https://github.com/MaterializeInc/materialize/pull/8326) (@petrosagg)
* [ ] [#8365 play: add shell.nix file](https://github.com/MaterializeInc/materialize/pull/8365) (@petrosagg)
* [ ] [#8366 dataflow; expr: Reuse Row allocations for SafeMfp evaluations](https://github.com/MaterializeInc/materialize/pull/8366) (@antiguru)
* [ ] [#8368 Port a lot more float funcs under `sqlfunc!`](https://github.com/MaterializeInc/materialize/pull/8368) (@petrosagg)
* [ ] [#8377 Prepare v0.9.6-dev](https://github.com/MaterializeInc/materialize/pull/8377) (@quodlibetor)
* [ ] [#8376 coord: only import "valid" indexes into dataflows](https://github.com/MaterializeInc/materialize/pull/8376) (@sploiselle)
* [ ] [#8371 pg-cdc: handle unchanged toast values during updates](https://github.com/MaterializeInc/materialize/pull/8371) (@petrosagg)
* [ ] [#8382 doc: fix release note order and wording](https://github.com/MaterializeInc/materialize/pull/8382) (@petrosagg)
* [ ] [#8385 Release note bump](https://github.com/MaterializeInc/materialize/pull/8385) (@msudberg)
* [ ] [#8367 dataflow: in upsert.rs factor out core upsert logic](https://github.com/MaterializeInc/materialize/pull/8367) (@aljoscha)
* [ ] [#8389 coord+dataflow: prevent client hangs while canceling pending peeks](https://github.com/MaterializeInc/materialize/pull/8389) (@sploiselle)
* [ ] [#8392 transform: avoid crash in InlineLet transform with very deep dataflows](https://github.com/MaterializeInc/materialize/pull/8392) (@asenac)
* [ ] [#8403 release: v0.9.5](https://github.com/MaterializeInc/materialize/pull/8403) (@quodlibetor)
* [ ] [#7263 sql: support DELETE and UPDATE for tables](https://github.com/MaterializeInc/materialize/pull/7263) (@mjibson)
* [ ] [#8384 expr/MfpPlan: Make evaluate generic over the error type](https://github.com/MaterializeInc/materialize/pull/8384) (@antiguru)
* [ ] [#8406 doc: Release note version bump for Docs home page  ](https://github.com/MaterializeInc/materialize/pull/8406) (@msudberg)
* [ ] [#8373 doc,coord: use external name of --disable-persistent-system-tables-test flag](https://github.com/MaterializeInc/materialize/pull/8373) (@danhhz)
* [ ] [#8410 docs: release note for #8021 fix](https://github.com/MaterializeInc/materialize/pull/8410) (@sploiselle)
* [ ] [#8404 Improve `DataflowDescription` interfaces](https://github.com/MaterializeInc/materialize/pull/8404) (@frankmcsherry)
* [ ] [#8370 sql-parser: parse kafka consistency two ways](https://github.com/MaterializeInc/materialize/pull/8370) (@JLDLaughlin)
* [ ] [#8412 test: ensure server can cancel long-running queries](https://github.com/MaterializeInc/materialize/pull/8412) (@sploiselle)
* [ ] [#8417 update favicon for HTTP server](https://github.com/MaterializeInc/materialize/pull/8417) (@umanwizard)
* [ ] [#8408 Fix inverted arguments in log_b(x) docs](https://github.com/MaterializeInc/materialize/pull/8408) (@umanwizard)
* [ ] [#8363 s3: refactor the s3-resumption test](https://github.com/MaterializeInc/materialize/pull/8363) (@philip-stoev)
* [ ] [#8421 sql+expr: move int unary funcs to sqlfunc!](https://github.com/MaterializeInc/materialize/pull/8421) (@sploiselle)
* [ ] [#8429 test: deflake test/testdrive/prometheus.td](https://github.com/MaterializeInc/materialize/pull/8429) (@ruchirK)
* [ ] [#8431 doc: fix typo on docs home page, shift Timelines page in SQL navigation.](https://github.com/MaterializeInc/materialize/pull/8431) (@msudberg)
* [ ] [#8432 expr: remove dead module](https://github.com/MaterializeInc/materialize/pull/8432) (@petrosagg)
* [ ] [#8334 coord: improve same timedomain error text](https://github.com/MaterializeInc/materialize/pull/8334) (@mjibson)
* [ ] [#8440 build(deps): bump openssl-sys from 0.9.66 to 0.9.67](https://github.com/MaterializeInc/materialize/pull/8440) (@dependabot[bot])
* [ ] [#8441 build(deps): bump whoami from 1.1.3 to 1.1.4](https://github.com/MaterializeInc/materialize/pull/8441) (@dependabot[bot])
* [ ] [#8442 build(deps): bump inotify from 0.9.3 to 0.9.4](https://github.com/MaterializeInc/materialize/pull/8442) (@dependabot[bot])
* [ ] [#8443 build(deps): bump tracing-subscriber from 0.2.23 to 0.2.24](https://github.com/MaterializeInc/materialize/pull/8443) (@dependabot[bot])
* [ ] [#8379 persist: allow multiple workers to together concurrently read a snapshot](https://github.com/MaterializeInc/materialize/pull/8379) (@danhhz)
* [ ] [#8289 persist: initial impl of S3Blob storage](https://github.com/MaterializeInc/materialize/pull/8289) (@danhhz)
* [ ] [#8439 build(deps): bump tokio from 1.11.0 to 1.12.0](https://github.com/MaterializeInc/materialize/pull/8439) (@dependabot[bot])
* [ ] [#8438 build(deps): bump syn from 1.0.76 to 1.0.77](https://github.com/MaterializeInc/materialize/pull/8438) (@dependabot[bot])
* [ ] [#8437 build(deps): bump http from 0.2.4 to 0.2.5](https://github.com/MaterializeInc/materialize/pull/8437) (@dependabot[bot])
* [ ] [#8449 doc: Press 's' to search](https://github.com/MaterializeInc/materialize/pull/8449) (@ruf-io)
* [ ] [#8433 pgwire: don't chain row batches](https://github.com/MaterializeInc/materialize/pull/8433) (@mjibson)
* [ ] [#8444 ci/test: enable persist external storage tests](https://github.com/MaterializeInc/materialize/pull/8444) (@danhhz)

</details>
