### ISSUE TITLE
release: v0.9.7-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#8534]
The following PRs in [`v0.9.7-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.7-rc1) require review:
* [ ] [#8453 Prepare 0.9.7-dev](https://github.com/MaterializeInc/materialize/pull/8453) (@quodlibetor)
* [ ] [#8419 Order by aggregate](https://github.com/MaterializeInc/materialize/pull/8419) (@msudberg)
* [ ] [#8398 sql: support PREPARE, EXECUTE](https://github.com/MaterializeInc/materialize/pull/8398) (@mjibson)
* [ ] [#8455 sql: Support `IS BOOLEAN` operators](https://github.com/MaterializeInc/materialize/pull/8455) (@cjubb39)
* [ ] [#8469 Correct the SLT tests pipeline name](https://github.com/MaterializeInc/materialize/pull/8469) (@quodlibetor)
* [ ] [#8471 release: v0.9.6](https://github.com/MaterializeInc/materialize/pull/8471) (@quodlibetor)
* [ ] [#7343 docs: Fix typo in record type documentation](https://github.com/MaterializeInc/materialize/pull/7343) (@andrioni)
* [ ] [#8486 kafka-matrix: fix record type in nightly test](https://github.com/MaterializeInc/materialize/pull/8486) (@JLDLaughlin)
* [ ] [#8483 doc: We support Postgres-CDC with REPLICA IDENTITY DEFAULT  ](https://github.com/MaterializeInc/materialize/pull/8483) (@msudberg)
* [ ] [#8491 doc: Add link to pricing info from Cloud doc](https://github.com/MaterializeInc/materialize/pull/8491) (@msudberg)
* [ ] [#8493 testdrive: Enable add-partition for Redpanda](https://github.com/MaterializeInc/materialize/pull/8493) (@BenPope)
* [ ] [#8504 sql: use PG's JOIN...USING constraint list syntax](https://github.com/MaterializeInc/materialize/pull/8504) (@sploiselle)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#8416 sql/coord: support INSERT...SELECT](https://github.com/MaterializeInc/materialize/pull/8416) (@sploiselle)
* [ ] [#8435 coord: add details to timedomain error](https://github.com/MaterializeInc/materialize/pull/8435) (@mjibson)
* [ ] [#8453 Prepare 0.9.7-dev](https://github.com/MaterializeInc/materialize/pull/8453) (@quodlibetor)
* [ ] [#8454 release: Automatically trigger Full SLTs for RCs](https://github.com/MaterializeInc/materialize/pull/8454) (@quodlibetor)
* [ ] [#8419 Order by aggregate](https://github.com/MaterializeInc/materialize/pull/8419) (@msudberg)
* [ ] [#8398 sql: support PREPARE, EXECUTE](https://github.com/MaterializeInc/materialize/pull/8398) (@mjibson)
* [ ] [#8455 sql: Support `IS BOOLEAN` operators](https://github.com/MaterializeInc/materialize/pull/8455) (@cjubb39)
* [ ] [#8317 interchange: emit protobuf data as records](https://github.com/MaterializeInc/materialize/pull/8317) (@JLDLaughlin)
* [ ] [#8464 sql: adjust ulp errors for arbitrary base logs w/ numerics](https://github.com/MaterializeInc/materialize/pull/8464) (@sploiselle)
* [ ] [#8450 materialized: hook up s3 persist storage to command line flags](https://github.com/MaterializeInc/materialize/pull/8450) (@danhhz)
* [ ] [#8469 Correct the SLT tests pipeline name](https://github.com/MaterializeInc/materialize/pull/8469) (@quodlibetor)
* [ ] [#8471 release: v0.9.6](https://github.com/MaterializeInc/materialize/pull/8471) (@quodlibetor)
* [ ] [#8456 Add TAIL xref to SELECT doc.](https://github.com/MaterializeInc/materialize/pull/8456) (@msudberg)
* [ ] [#8476 documentation and release notes for #8455](https://github.com/MaterializeInc/materialize/pull/8476) (@cjubb39)
* [ ] [#8475 Dataflow builder dustoff](https://github.com/MaterializeInc/materialize/pull/8475) (@frankmcsherry)
* [ ] [#8481 doc: quickfix - Add S3 and Postgres mention to overview](https://github.com/MaterializeInc/materialize/pull/8481) (@ruf-io)
* [ ] [#8479 Improve fast path logic](https://github.com/MaterializeInc/materialize/pull/8479) (@frankmcsherry)
* [ ] [#8478 Developer doc: Include math on arrangements of aggregations on distinct values](https://github.com/MaterializeInc/materialize/pull/8478) (@wangandi)
* [ ] [#7343 docs: Fix typo in record type documentation](https://github.com/MaterializeInc/materialize/pull/7343) (@andrioni)
* [ ] [#8486 kafka-matrix: fix record type in nightly test](https://github.com/MaterializeInc/materialize/pull/8486) (@JLDLaughlin)
* [ ] [#8394 persist: turn Persist::persist() operator into modular persist()/seal() operators](https://github.com/MaterializeInc/materialize/pull/8394) (@aljoscha)
* [ ] [#8400 upgrade: port the upgrade test to Python](https://github.com/MaterializeInc/materialize/pull/8400) (@philip-stoev)
* [ ] [#8483 doc: We support Postgres-CDC with REPLICA IDENTITY DEFAULT  ](https://github.com/MaterializeInc/materialize/pull/8483) (@msudberg)
* [ ] [#8273 Typ with input types](https://github.com/MaterializeInc/materialize/pull/8273) (@asenac)
* [ ] [#8491 doc: Add link to pricing info from Cloud doc](https://github.com/MaterializeInc/materialize/pull/8491) (@msudberg)
* [ ] [#8482 persist: don't block replay operator construction on snapshot iter](https://github.com/MaterializeInc/materialize/pull/8482) (@danhhz)
* [ ] [#8493 testdrive: Enable add-partition for Redpanda](https://github.com/MaterializeInc/materialize/pull/8493) (@BenPope)
* [ ] [#8474 kafka create sink: add retention.ms and retention.bytes](https://github.com/MaterializeInc/materialize/pull/8474) (@cjubb39)
* [ ] [#8497 remove sqlsmith from nightly CI runs](https://github.com/MaterializeInc/materialize/pull/8497) (@elindsey)
* [ ] [#8504 sql: use PG's JOIN...USING constraint list syntax](https://github.com/MaterializeInc/materialize/pull/8504) (@sploiselle)
* [ ] [#8496 coord: add indisprimary and indkey to pg_index](https://github.com/MaterializeInc/materialize/pull/8496) (@mjibson)
* [ ] [#8508 build(deps): bump smallvec from 1.6.1 to 1.7.0](https://github.com/MaterializeInc/materialize/pull/8508) (@dependabot[bot])
* [ ] [#8509 build(deps): bump libc from 0.2.102 to 0.2.103](https://github.com/MaterializeInc/materialize/pull/8509) (@dependabot[bot])
* [ ] [#8510 build(deps): bump syn from 1.0.77 to 1.0.78](https://github.com/MaterializeInc/materialize/pull/8510) (@dependabot[bot])
* [ ] [#8511 build(deps): bump whoami from 1.1.4 to 1.1.5](https://github.com/MaterializeInc/materialize/pull/8511) (@dependabot[bot])
* [ ] [#8512 build(deps): bump ubuntu from focal-20210827 to focal-20210921 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/8512) (@dependabot[bot])
* [ ] [#8466 release: Some changes to the template](https://github.com/MaterializeInc/materialize/pull/8466) (@quodlibetor)
* [ ] [#8434 dataflow/sink: properly indicate that the sink write frontier is empt…](https://github.com/MaterializeInc/materialize/pull/8434) (@ruchirK)
* [ ] [#8488 coord: verify prepared statements on use](https://github.com/MaterializeInc/materialize/pull/8488) (@mjibson)
* [ ] [#8484 sql: Allow RESTRICT and CASCADE in DROP DATABASE](https://github.com/MaterializeInc/materialize/pull/8484) (@cjubb39)
* [ ] [#8526 doc: more correctly describe FETCH ALL in a loop](https://github.com/MaterializeInc/materialize/pull/8526) (@mjibson)
* [ ] [#8514 upgrade: add tests for persisted user tables](https://github.com/MaterializeInc/materialize/pull/8514) (@philip-stoev)

</details>

**Comment by umanwizard** [comment]
all look legit.
