### ISSUE TITLE
Support the `TIMESTAMPTZ` type

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#858]
We need to support timestamptz  to be semi-postgres-compatible because timestamptz is the [officially](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_timestamp_.28without_time_zone.29_to_store_UTC_times) and [very strongly recommended](https://justatheory.com/2012/04/postgres-use-timestamptz/) setting and so most companies that we integrate with should be expected to be using timestamptz.

Currently we can't even *parse* timestamptzs, so this is going to be a fair amount of work.

The canonical reference for what we want to implement is https://www.postgresql.org/docs/12/datatype-datetime.html .

- [ ] #854 determine how TimestampTZs come out of debezium
- [ ] #856 convert from debezium-provided TimestampTZs to UTC
- [x] #855 Parse TimestampTZs in sqlparser
- [x] #857 support timestampTZs in pgwire
- [x] #867 Support Postgres as an input type for Debezium

**Comment by morsapaes** [comment]
Closing in favor of #24941, which covers the remaining work tied to Debezium.
