### ISSUE TITLE
release: v0.9.11-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#8882]
The following PRs in [`v0.9.11-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.11-rc1) require review:
* [ ] [#8795 Prepare 0.9.11 dev](https://github.com/MaterializeInc/materialize/pull/8795) (@umanwizard)
* [ ] [#8719 Fix periodic tests to not automatically set the AWS profile](https://github.com/MaterializeInc/materialize/pull/8719) (@umanwizard)
* [ ] [#8796 Bi demo](https://github.com/MaterializeInc/materialize/pull/8796) (@msudberg)
* [ ] [#8820 Continue 0.9.11 dev](https://github.com/MaterializeInc/materialize/pull/8820) (@umanwizard)
* [ ] [#8818 Alter logic for yielding from halfjoin](https://github.com/MaterializeInc/materialize/pull/8818) (@frankmcsherry)
* [ ] [#8842 docs: UPDATE statement](https://github.com/MaterializeInc/materialize/pull/8842) (@sploiselle)
* [ ] [#8843 docs: document DELETE statement](https://github.com/MaterializeInc/materialize/pull/8843) (@sploiselle)
* [ ] [#8844 docs: `INSERT...SELECT`](https://github.com/MaterializeInc/materialize/pull/8844) (@sploiselle)
* [ ] [#8845 coord,sql: support `SET LOCAL` and transactional variables](https://github.com/MaterializeInc/materialize/pull/8845) (@benesch)
* [ ] [#8856 test: Extend the limits test to the dataflow operators](https://github.com/MaterializeInc/materialize/pull/8856) (@philip-stoev)
* [ ] [#8848 *: disable unnecessary tiberius features](https://github.com/MaterializeInc/materialize/pull/8848) (@benesch)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#8582 Two phase subquery lowering for projections](https://github.com/MaterializeInc/materialize/pull/8582) (@asenac)
* [ ] [#8771 coord: catalog transactions](https://github.com/MaterializeInc/materialize/pull/8771) (@mjibson)
* [ ] [#8752 persist: in persistent_source(), build consistent operator graph](https://github.com/MaterializeInc/materialize/pull/8752) (@aljoscha)
* [ ] [#8785 build(deps): bump libc from 0.2.104 to 0.2.105](https://github.com/MaterializeInc/materialize/pull/8785) (@dependabot[bot])
* [ ] [#8787 build(deps): bump backtrace from 0.3.61 to 0.3.62](https://github.com/MaterializeInc/materialize/pull/8787) (@dependabot[bot])
* [ ] [#8788 build(deps): bump structopt from 0.3.23 to 0.3.25](https://github.com/MaterializeInc/materialize/pull/8788) (@dependabot[bot])
* [ ] [#8791 Unpatch headers crate](https://github.com/MaterializeInc/materialize/pull/8791) (@petrosagg)
* [ ] [#8795 Prepare 0.9.11 dev](https://github.com/MaterializeInc/materialize/pull/8795) (@umanwizard)
* [ ] [#8719 Fix periodic tests to not automatically set the AWS profile](https://github.com/MaterializeInc/materialize/pull/8719) (@umanwizard)
* [ ] [#8796 Bi demo](https://github.com/MaterializeInc/materialize/pull/8796) (@msudberg)
* [ ] [#8797 coord: prevent UPDATE and DELETE with disable-user-indexes](https://github.com/MaterializeInc/materialize/pull/8797) (@sploiselle)
* [ ] [#8798 coord: add max_index_keys to pg_settings](https://github.com/MaterializeInc/materialize/pull/8798) (@mjibson)
* [ ] [#8634 dataflow: more verbose error message when a peek returns negative mul…](https://github.com/MaterializeInc/materialize/pull/8634) (@ruchirK)
* [ ] [#8782 sql-parser,sql: move some semantic analysis out of the SQL parser](https://github.com/MaterializeInc/materialize/pull/8782) (@benesch)
* [ ] [#8591 Link JSON sources to jsonb data type info.](https://github.com/MaterializeInc/materialize/pull/8591) (@msudberg)
* [ ] [#8803 Fix wrong results issue introduced by #8582](https://github.com/MaterializeInc/materialize/pull/8803) (@asenac)
* [ ] [#8804 add a timeout to ccsr requests](https://github.com/MaterializeInc/materialize/pull/8804) (@elindsey)
* [ ] [#8774 persist: address TODO to handle the operator error output in nemesis](https://github.com/MaterializeInc/materialize/pull/8774) (@danhhz)
* [ ] [#8806 persist: make BlobCache errors more descriptive](https://github.com/MaterializeInc/materialize/pull/8806) (@ruchirK)
* [ ] [#8714 dataflow: allow source operator to optionally emit timestamp bindings](https://github.com/MaterializeInc/materialize/pull/8714) (@aljoscha)
* [ ] [#8515 Explain physical plan](https://github.com/MaterializeInc/materialize/pull/8515) (@asenac)
* [ ] [#8649 persist: pipeline write, seal, and allow_compaction in nemesis](https://github.com/MaterializeInc/materialize/pull/8649) (@danhhz)
* [ ] [#8761 coord,persistence: Introduce failpoints](https://github.com/MaterializeInc/materialize/pull/8761) (@philip-stoev)
* [ ] [#8802 persist,dataflow: for persistent tables, make operator construction deterministic](https://github.com/MaterializeInc/materialize/pull/8802) (@aljoscha)
* [ ] [#8684 persist: add list_keys to Blob](https://github.com/MaterializeInc/materialize/pull/8684) (@ruchirK)
* [ ] [#8815 persist/src/mem: fix merge skew](https://github.com/MaterializeInc/materialize/pull/8815) (@ruchirK)
* [ ] [#8783 build(deps): bump hyper from 0.14.13 to 0.14.14](https://github.com/MaterializeInc/materialize/pull/8783) (@dependabot[bot])
* [ ] [#8701 build(deps): bump timely from `914b6ff` to `de28bb4`](https://github.com/MaterializeInc/materialize/pull/8701) (@dependabot[bot])
* [ ] [#8789 build(deps): bump differential-dataflow from `c88e702` to `c696ec0`](https://github.com/MaterializeInc/materialize/pull/8789) (@dependabot[bot])
* [ ] [#8820 Continue 0.9.11 dev](https://github.com/MaterializeInc/materialize/pull/8820) (@umanwizard)
* [ ] [#8818 Alter logic for yielding from halfjoin](https://github.com/MaterializeInc/materialize/pull/8818) (@frankmcsherry)
* [ ] [#8826 prof: Export jemalloc stats as json if requested](https://github.com/MaterializeInc/materialize/pull/8826) (@antiguru)
* [ ] [#8828 dataflow: Do not clone plan when building dataflows](https://github.com/MaterializeInc/materialize/pull/8828) (@antiguru)
* [ ] [#8829 row: Efficient copy in finish_and_reuse](https://github.com/MaterializeInc/materialize/pull/8829) (@antiguru)
* [ ] [#8830 transform: Avoid a clone for pretty error messages](https://github.com/MaterializeInc/materialize/pull/8830) (@antiguru)
* [ ] [#8831 transform: Reuse knowledge_stack allocation](https://github.com/MaterializeInc/materialize/pull/8831) (@antiguru)
* [ ] [#8833 build(deps): bump rusqlite from 0.26.0 to 0.26.1](https://github.com/MaterializeInc/materialize/pull/8833) (@dependabot[bot])
* [ ] [#8835 deny.toml: ignore inapplicable advisory RUSTSEC-2020-0159](https://github.com/MaterializeInc/materialize/pull/8835) (@benesch)
* [ ] [#8837 build(deps): bump openssl-sys from 0.9.67 to 0.9.68](https://github.com/MaterializeInc/materialize/pull/8837) (@dependabot[bot])
* [ ] [#8832 build(deps): bump reqwest from 0.11.5 to 0.11.6](https://github.com/MaterializeInc/materialize/pull/8832) (@dependabot[bot])
* [ ] [#8836 build(deps): bump tokio-openssl from 0.6.2 to 0.6.3](https://github.com/MaterializeInc/materialize/pull/8836) (@dependabot[bot])
* [ ] [#8799 sql: support READ ONLY transaction mode](https://github.com/MaterializeInc/materialize/pull/8799) (@mjibson)
* [ ] [#8841 coord: document catalog_transact](https://github.com/MaterializeInc/materialize/pull/8841) (@mjibson)
* [ ] [#8842 docs: UPDATE statement](https://github.com/MaterializeInc/materialize/pull/8842) (@sploiselle)
* [ ] [#8843 docs: document DELETE statement](https://github.com/MaterializeInc/materialize/pull/8843) (@sploiselle)
* [ ] [#8844 docs: `INSERT...SELECT`](https://github.com/MaterializeInc/materialize/pull/8844) (@sploiselle)
* [ ] [#8827 Make `persist::Blob` trait async](https://github.com/MaterializeInc/materialize/pull/8827) (@petrosagg)
* [ ] [#8834 build(deps): bump syn from 1.0.80 to 1.0.81](https://github.com/MaterializeInc/materialize/pull/8834) (@dependabot[bot])
* [ ] [#8846 ci-builder: add a convenience command for opening a root shell](https://github.com/MaterializeInc/materialize/pull/8846) (@benesch)
* [ ] [#8694 sql/transform: bypass planning and optimization on known constant inputs](https://github.com/MaterializeInc/materialize/pull/8694) (@ruchirK)
* [ ] [#8839 build(deps): bump openssl from 0.10.36 to 0.10.37](https://github.com/MaterializeInc/materialize/pull/8839) (@dependabot[bot])
* [ ] [#8706 build(deps): bump ubuntu from focal-20210921 to focal-20211006 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/8706) (@dependabot[bot])
* [ ] [#8849 readme: Correct link to cloud introduction](https://github.com/MaterializeInc/materialize/pull/8849) (@antiguru)
* [ ] [#8851 persist: implement `std::future::Future` for `persist::Future`](https://github.com/MaterializeInc/materialize/pull/8851) (@petrosagg)
* [ ] [#8847 Partition `plan::Constant` stages across workers](https://github.com/MaterializeInc/materialize/pull/8847) (@frankmcsherry)
* [ ] [#8854 dataflow: Avoid cloning source imports](https://github.com/MaterializeInc/materialize/pull/8854) (@antiguru)
* [ ] [#8745 dataflow,persist: persist timestamp bindings and use them to restore source offsets](https://github.com/MaterializeInc/materialize/pull/8745) (@aljoscha)
* [ ] [#8845 coord,sql: support `SET LOCAL` and transactional variables](https://github.com/MaterializeInc/materialize/pull/8845) (@benesch)
* [ ] [#8856 test: Extend the limits test to the dataflow operators](https://github.com/MaterializeInc/materialize/pull/8856) (@philip-stoev)
* [ ] [#8865 coord: simplify return paths in end transaction logic](https://github.com/MaterializeInc/materialize/pull/8865) (@mjibson)
* [ ] [#8762 doc: Add guide for dbt](https://github.com/MaterializeInc/materialize/pull/8762) (@morsapaes)
* [ ] [#8711 build(deps): bump nix from 0.20.2 to 0.22.2](https://github.com/MaterializeInc/materialize/pull/8711) (@dependabot[bot])
* [ ] [#8848 *: disable unnecessary tiberius features](https://github.com/MaterializeInc/materialize/pull/8848) (@benesch)
* [ ] [#8867 coord: simplify session txn cleanup more](https://github.com/MaterializeInc/materialize/pull/8867) (@mjibson)
* [ ] [#8786 build(deps): bump rdkafka from `6920144` to `37ba1d2`](https://github.com/MaterializeInc/materialize/pull/8786) (@dependabot[bot])
* [ ] [#8838 build(deps): bump tracing-subscriber from 0.2.25 to 0.3.1](https://github.com/MaterializeInc/materialize/pull/8838) (@dependabot[bot])
* [ ] [#8746 dataflow,persist: wire persistence configs, this enables previously added persistence code](https://github.com/MaterializeInc/materialize/pull/8746) (@aljoscha)
* [ ] [#8814 persist: in conditional_seal() operator, don't block on seal futures](https://github.com/MaterializeInc/materialize/pull/8814) (@aljoscha)
* [ ] [#8817 persist: in persist() operator, don't block on write futures](https://github.com/MaterializeInc/materialize/pull/8817) (@aljoscha)
* [ ] [#8873 build(deps): bump tokio from 1.12.0 to 1.13.0](https://github.com/MaterializeInc/materialize/pull/8873) (@dependabot[bot])
* [ ] [#8874 build(deps): bump libc from 0.2.105 to 0.2.106](https://github.com/MaterializeInc/materialize/pull/8874) (@dependabot[bot])
* [ ] [#8876 build(deps): bump tokio-util from 0.6.8 to 0.6.9](https://github.com/MaterializeInc/materialize/pull/8876) (@dependabot[bot])
* [ ] [#8871 build(deps): bump tokio-stream from 0.1.7 to 0.1.8](https://github.com/MaterializeInc/materialize/pull/8871) (@dependabot[bot])

</details>

**Comment by petrosagg** [comment]
duplicate of #8883. I messed up with tag creation and had to create the tag twice
