### ISSUE TITLE
release: v0.9.12-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9017]
The following PRs in [`v0.9.12-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.12-rc1) require review:
* [x] [#8821 Failpoints documentation](https://github.com/MaterializeInc/materialize/pull/8821) (@philip-stoev)
* [x] [#8884 Prepare 0.9.12 dev](https://github.com/MaterializeInc/materialize/pull/8884) (@petrosagg)
* [x] [#8885 Rename filepoints.md to failpoints.md](https://github.com/MaterializeInc/materialize/pull/8885) (@philip-stoev)
* [x] [#8886 Bi demo restore](https://github.com/MaterializeInc/materialize/pull/8886) (@msudberg)
* [x] [#8920 deps: python dependency bumps](https://github.com/MaterializeInc/materialize/pull/8920) (@benesch)
* [x] [#8906 Continue 0.9.12 dev](https://github.com/MaterializeInc/materialize/pull/8906) (@petrosagg)
* [x] [#8908 doc: fix release note race condition](https://github.com/MaterializeInc/materialize/pull/8908) (@petrosagg)
* [x] [#8915 Fix aliases](https://github.com/MaterializeInc/materialize/pull/8915) (@msudberg)
* [x] [#8918 doc: fix typos and other issues with failpoints.md](https://github.com/MaterializeInc/materialize/pull/8918) (@philip-stoev)
* [x] [#8912 testdrive: switch $ kafka-ingest to use automatic partitioning](https://github.com/MaterializeInc/materialize/pull/8912) (@philip-stoev)
* [x] [#8931 Typo](https://github.com/MaterializeInc/materialize/pull/8931) (@msudberg)
* [x] [#8936 test: Add Kafka partitions, records and envelopes to the product limi…](https://github.com/MaterializeInc/materialize/pull/8936) (@philip-stoev)
* [x] [#8946 devsite: exclude rust-private docs from search engines](https://github.com/MaterializeInc/materialize/pull/8946) (@benesch)
* [x] [#8948 pg-cdc: give hint and offending table oid in error message](https://github.com/MaterializeInc/materialize/pull/8948) (@petrosagg)
* [x] [#8957 Restore bi-demo](https://github.com/MaterializeInc/materialize/pull/8957) (@msudberg)
* [x] [#8975 sql: window function test and doc nits](https://github.com/MaterializeInc/materialize/pull/8975) (@mjibson)
* [x] [#8977 play/nix: add pkg-config to correctly compile openssl-sys](https://github.com/MaterializeInc/materialize/pull/8977) (@petrosagg)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#8821 Failpoints documentation](https://github.com/MaterializeInc/materialize/pull/8821) (@philip-stoev)
* [ ] [#8875 build(deps): bump openssl from 0.10.37 to 0.10.38](https://github.com/MaterializeInc/materialize/pull/8875) (@dependabot[bot])
* [ ] [#8879 persist: fix conditional_seal() operator](https://github.com/MaterializeInc/materialize/pull/8879) (@aljoscha)
* [ ] [#8880 dataflow,persist: wait for updates to be persisted before forwarding from source](https://github.com/MaterializeInc/materialize/pull/8880) (@aljoscha)
* [ ] [#8884 Prepare 0.9.12 dev](https://github.com/MaterializeInc/materialize/pull/8884) (@petrosagg)
* [ ] [#8885 Rename filepoints.md to failpoints.md](https://github.com/MaterializeInc/materialize/pull/8885) (@philip-stoev)
* [ ] [#8886 Bi demo restore](https://github.com/MaterializeInc/materialize/pull/8886) (@msudberg)
* [ ] [#8877 sql: implement date_bin builtin functions](https://github.com/MaterializeInc/materialize/pull/8877) (@sploiselle)
* [ ] [#8864 persist: stronger invariant checking / new invariants with `list_keys`](https://github.com/MaterializeInc/materialize/pull/8864) (@ruchirK)
* [ ] [#8889 Allow even passed deploy steps to be manually retried](https://github.com/MaterializeInc/materialize/pull/8889) (@umanwizard)
* [ ] [#8890 Get rid of retry on trigger step](https://github.com/MaterializeInc/materialize/pull/8890) (@umanwizard)
* [ ] [#8920 deps: python dependency bumps](https://github.com/MaterializeInc/materialize/pull/8920) (@benesch)
* [ ] [#8903 Update mzcloud cli to latest cloud SDK](https://github.com/MaterializeInc/materialize/pull/8903) (@alex-hunt-materialize)
* [ ] [#8906 Continue 0.9.12 dev](https://github.com/MaterializeInc/materialize/pull/8906) (@petrosagg)
* [ ] [#8908 doc: fix release note race condition](https://github.com/MaterializeInc/materialize/pull/8908) (@petrosagg)
* [ ] [#8901 persist: rename Future to PFuture](https://github.com/MaterializeInc/materialize/pull/8901) (@danhhz)
* [ ] [#8878 persist,dataflow: forward persistence errors from persist/upsert operators to differential error collections](https://github.com/MaterializeInc/materialize/pull/8878) (@aljoscha)
* [ ] [#8737 Tell users how to check disk usage](https://github.com/MaterializeInc/materialize/pull/8737) (@msudberg)
* [ ] [#8915 Fix aliases](https://github.com/MaterializeInc/materialize/pull/8915) (@msudberg)
* [ ] [#8918 doc: fix typos and other issues with failpoints.md](https://github.com/MaterializeInc/materialize/pull/8918) (@philip-stoev)
* [ ] [#8759 Have canonicalize_equivalences reduce expressions.](https://github.com/MaterializeInc/materialize/pull/8759) (@wangandi)
* [ ] [#8808 coord: add type_oid to mz_columns](https://github.com/MaterializeInc/materialize/pull/8808) (@mjibson)
* [ ] [#8914 pgwire: allow junk data after end of copy marker](https://github.com/MaterializeInc/materialize/pull/8914) (@sploiselle)
* [ ] [#8928 coord,dataflow: separate coordinator and dataflow startup](https://github.com/MaterializeInc/materialize/pull/8928) (@benesch)
* [ ] [#8718 Implement de-duplication of columns between keys and values in arrangements](https://github.com/MaterializeInc/materialize/pull/8718) (@antiguru)
* [ ] [#8912 testdrive: switch $ kafka-ingest to use automatic partitioning](https://github.com/MaterializeInc/materialize/pull/8912) (@philip-stoev)
* [ ] [#8931 Typo](https://github.com/MaterializeInc/materialize/pull/8931) (@msudberg)
* [ ] [#8934 Fix failures in the cleanup script](https://github.com/MaterializeInc/materialize/pull/8934) (@umanwizard)
* [ ] [#8894 testdrive: introduce ${kafka-ingest.iteration} runtime variable](https://github.com/MaterializeInc/materialize/pull/8894) (@philip-stoev)
* [ ] [#8913 persist: teach persist to handle varying encoding versions.](https://github.com/MaterializeInc/materialize/pull/8913) (@ruchirK)
* [ ] [#8938 Run tests with nocapture](https://github.com/MaterializeInc/materialize/pull/8938) (@umanwizard)
* [ ] [#8936 test: Add Kafka partitions, records and envelopes to the product limi…](https://github.com/MaterializeInc/materialize/pull/8936) (@philip-stoev)
* [ ] [#8893 persist: add microbenchmarks for blob and indexed writes](https://github.com/MaterializeInc/materialize/pull/8893) (@ruchirK)
* [ ] [#8941 ore: introduce a test::timeout helper](https://github.com/MaterializeInc/materialize/pull/8941) (@benesch)
* [ ] [#8904 coord,dataflow: expose librdkafka stats more directly](https://github.com/MaterializeInc/materialize/pull/8904) (@benesch)
* [ ] [#8757 persist: replace Abomonation with serde+bincode](https://github.com/MaterializeInc/materialize/pull/8757) (@danhhz)
* [ ] [#8943 coord: exclude non-mat sources from timedomains](https://github.com/MaterializeInc/materialize/pull/8943) (@mjibson)
* [ ] [#8756 sql: support copy from stdin format csv](https://github.com/MaterializeInc/materialize/pull/8756) (@sploiselle)
* [ ] [#8944 materialized: use assert_contains in test_no_block](https://github.com/MaterializeInc/materialize/pull/8944) (@benesch)
* [ ] [#8945 coordd,dataflowd: add new binaries for independent dataflow/coord servers](https://github.com/MaterializeInc/materialize/pull/8945) (@benesch)
* [ ] [#8946 devsite: exclude rust-private docs from search engines](https://github.com/MaterializeInc/materialize/pull/8946) (@benesch)
* [ ] [#8916 persist: yield to timely while awaiting `Future`s](https://github.com/MaterializeInc/materialize/pull/8916) (@petrosagg)
* [ ] [#8801 Skeleton for QGM generation from Hir](https://github.com/MaterializeInc/materialize/pull/8801) (@asenac)
* [ ] [#8948 pg-cdc: give hint and offending table oid in error message](https://github.com/MaterializeInc/materialize/pull/8948) (@petrosagg)
* [ ] [#8852 Separate metadata non breaking](https://github.com/MaterializeInc/materialize/pull/8852) (@petrosagg)
* [ ] [#8951 persist: limit write benchmarks resource utilization.](https://github.com/MaterializeInc/materialize/pull/8951) (@ruchirK)
* [ ] [#8689 persist: use multi-threaded timely dataflows in nemesis](https://github.com/MaterializeInc/materialize/pull/8689) (@danhhz)
* [ ] [#8949 ci: downgrade docs hugo to 0.87](https://github.com/MaterializeInc/materialize/pull/8949) (@sploiselle)
* [ ] [#8654 Syntax changes for multiple Kafka metadata items](https://github.com/MaterializeInc/materialize/pull/8654) (@quodlibetor)
* [ ] [#8926 persist: give each mutating request a SeqNo](https://github.com/MaterializeInc/materialize/pull/8926) (@danhhz)
* [ ] [#8952 docs: separate beta warning and version added messages](https://github.com/MaterializeInc/materialize/pull/8952) (@benesch)
* [ ] [#8954 Read the full request before responding in test_no_block](https://github.com/MaterializeInc/materialize/pull/8954) (@umanwizard)
* [ ] [#8957 Restore bi-demo](https://github.com/MaterializeInc/materialize/pull/8957) (@msudberg)
* [ ] [#8953 ccsr: Add ability to get subject and all dependencies](https://github.com/MaterializeInc/materialize/pull/8953) (@cjubb39)
* [ ] [#8965 interchange: remove debezium dead code](https://github.com/MaterializeInc/materialize/pull/8965) (@petrosagg)
* [ ] [#8968 sql: remove dead code](https://github.com/MaterializeInc/materialize/pull/8968) (@petrosagg)
* [ ] [#8964 ore: remove unused functions](https://github.com/MaterializeInc/materialize/pull/8964) (@petrosagg)
* [ ] [#8939 sql: fix reduction elision optimization on STRING_AGG reduction](https://github.com/MaterializeInc/materialize/pull/8939) (@mkysel)
* [ ] [#8503 sql: scalar window functions](https://github.com/MaterializeInc/materialize/pull/8503) (@mjibson)
* [ ] [#8809 test: verify pgjdbc getColumns works](https://github.com/MaterializeInc/materialize/pull/8809) (@mjibson)
* [ ] [#8975 sql: window function test and doc nits](https://github.com/MaterializeInc/materialize/pull/8975) (@mjibson)
* [ ] [#8977 play/nix: add pkg-config to correctly compile openssl-sys](https://github.com/MaterializeInc/materialize/pull/8977) (@petrosagg)
* [ ] [#7092 repr: make Row platform independent and less unsafe](https://github.com/MaterializeInc/materialize/pull/7092) (@benesch)
* [ ] [#8971 dataflow: Avoid ephemeral rows for `flat_map`](https://github.com/MaterializeInc/materialize/pull/8971) (@antiguru)
* [ ] [#8972 persist: introduce ingest-side workers in nemesis](https://github.com/MaterializeInc/materialize/pull/8972) (@danhhz)
* [ ] [#8999 play/nix: use a recent enough lld to get working backtraces](https://github.com/MaterializeInc/materialize/pull/8999) (@petrosagg)
* [ ] [#8902 persist: don't consolidate unsealed batches](https://github.com/MaterializeInc/materialize/pull/8902) (@ruchirK)
* [ ] [#9003 fix failing kafka-matrix nightlies](https://github.com/MaterializeInc/materialize/pull/9003) (@elindsey)
* [ ] [#9004 Wake worker threads after dropping LocalClient connections](https://github.com/MaterializeInc/materialize/pull/9004) (@frankmcsherry)
* [ ] [#8979 docs: small fixes, update link checking instructions](https://github.com/MaterializeInc/materialize/pull/8979) (@sys3175)
* [ ] [#8997 sql: disallow ambiguous table references](https://github.com/MaterializeInc/materialize/pull/8997) (@sploiselle)
* [ ] [#8973 sql: fix remaining AGGREGATE functions using reduce elision optimization](https://github.com/MaterializeInc/materialize/pull/8973) (@mkysel)
* [ ] [#9009 docs: Fix formatting issue in `COPY FROM`](https://github.com/MaterializeInc/materialize/pull/9009) (@morsapaes)
* [ ] [#8960 sources and sinks: refactor protobuf descriptors](https://github.com/MaterializeInc/materialize/pull/8960) (@cjubb39)
* [ ] [#9013 QGM Readme: Add Mac instructions for visualizing the graphs.](https://github.com/MaterializeInc/materialize/pull/9013) (@wangandi)
* [ ] [#9012 sql: fix row_number reduce elision optimization](https://github.com/MaterializeInc/materialize/pull/9012) (@mkysel)

</details>

**Comment by quodlibetor** [comment]
CC #8996
