### ISSUE TITLE
release: v0.9.13-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9118]
The following PRs in [`v0.9.13-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.9.13-rc1) require review:
* [x] [#9104 deps: bump python versions](https://github.com/MaterializeInc/materialize/pull/9104) (@benesch)
* [x] [#9018 Prepare 0.9.13 dev](https://github.com/MaterializeInc/materialize/pull/9018) (@quodlibetor)
* [x] [#9025 test: increase the timeout for the product limits test](https://github.com/MaterializeInc/materialize/pull/9025) (@philip-stoev)
* [x] [#9028 Use a DatumVec in FormArrangementKey](https://github.com/MaterializeInc/materialize/pull/9028) (@frankmcsherry)
* [x] [#9029 fix typo](https://github.com/MaterializeInc/materialize/pull/9029) (@msudberg)
* [x] [#9035 antithesis: reduce logging verbosity](https://github.com/MaterializeInc/materialize/pull/9035) (@philip-stoev)
* [x] [#9044 Finish release of 0.9.12](https://github.com/MaterializeInc/materialize/pull/9044) (@quodlibetor)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#9104 deps: bump python versions](https://github.com/MaterializeInc/materialize/pull/9104) (@benesch)
* [ ] [#8966 dataflow: remove dead code for sources and sinks](https://github.com/MaterializeInc/materialize/pull/8966) (@petrosagg)
* [ ] [#8970 repr: move `&self` `Row` methods under `RowRef` and use `Deref`](https://github.com/MaterializeInc/materialize/pull/8970) (@petrosagg)
* [ ] [#8976 Remove unused crate dependencies](https://github.com/MaterializeInc/materialize/pull/8976) (@petrosagg)
* [ ] [#8980 build(deps): bump backtrace from 0.3.62 to 0.3.63](https://github.com/MaterializeInc/materialize/pull/8980) (@dependabot[bot])
* [ ] [#8982 build(deps): bump pprof from 0.6.0 to 0.6.1](https://github.com/MaterializeInc/materialize/pull/8982) (@dependabot[bot])
* [ ] [#8983 build(deps): bump paste from 1.0.5 to 1.0.6](https://github.com/MaterializeInc/materialize/pull/8983) (@dependabot[bot])
* [ ] [#8984 build(deps): bump inotify from 0.9.5 to 0.9.6](https://github.com/MaterializeInc/materialize/pull/8984) (@dependabot[bot])
* [ ] [#8985 build(deps): bump libc from 0.2.106 to 0.2.107](https://github.com/MaterializeInc/materialize/pull/8985) (@dependabot[bot])
* [ ] [#8986 build(deps): bump sysctl from 0.4.2 to 0.4.3](https://github.com/MaterializeInc/materialize/pull/8986) (@dependabot[bot])
* [ ] [#9016 persist: a few small cleanups](https://github.com/MaterializeInc/materialize/pull/9016) (@danhhz)
* [ ] [#9015 coord: remove unnecessary allocations in sequence_send_diffs](https://github.com/MaterializeInc/materialize/pull/9015) (@ruchirK)
* [ ] [#9018 Prepare 0.9.13 dev](https://github.com/MaterializeInc/materialize/pull/9018) (@quodlibetor)
* [ ] [#9022 dataflow: keyed sources should always have keyed RelationDescs](https://github.com/MaterializeInc/materialize/pull/9022) (@petrosagg)
* [ ] [#9024 sql: re-add datadriven crate](https://github.com/MaterializeInc/materialize/pull/9024) (@petrosagg)
* [ ] [#9025 test: increase the timeout for the product limits test](https://github.com/MaterializeInc/materialize/pull/9025) (@philip-stoev)
* [ ] [#8279 Expr: Remove demand field from join and flatmap.](https://github.com/MaterializeInc/materialize/pull/8279) (@wangandi)
* [ ] [#9014 Explain MIR: Remove unnecessary printing of let types.](https://github.com/MaterializeInc/materialize/pull/9014) (@wangandi)
* [ ] [#9028 Use a DatumVec in FormArrangementKey](https://github.com/MaterializeInc/materialize/pull/9028) (@frankmcsherry)
* [ ] [#9029 fix typo](https://github.com/MaterializeInc/materialize/pull/9029) (@msudberg)
* [ ] [#9031 Move `DatumVec` to `repr`](https://github.com/MaterializeInc/materialize/pull/9031) (@frankmcsherry)
* [ ] [#9033 persist: clean up Indexed state](https://github.com/MaterializeInc/materialize/pull/9033) (@danhhz)
* [ ] [#9035 antithesis: reduce logging verbosity](https://github.com/MaterializeInc/materialize/pull/9035) (@philip-stoev)
* [ ] [#9036 testdrive: send all error-related output to stderr](https://github.com/MaterializeInc/materialize/pull/9036) (@philip-stoev)
* [ ] [#9021 transform: new topk fusion transform](https://github.com/MaterializeInc/materialize/pull/9021) (@asenac)
* [ ] [#8571 Support LIST(SUBQUERY) syntax](https://github.com/MaterializeInc/materialize/pull/8571) (@cjubb39)
* [ ] [#9041 update create sink with consistency topic examples](https://github.com/MaterializeInc/materialize/pull/9041) (@elindsey)
* [ ] [#9044 Finish release of 0.9.12](https://github.com/MaterializeInc/materialize/pull/9044) (@quodlibetor)
* [ ] [#8341 exclude isolation.level from admin client creation](https://github.com/MaterializeInc/materialize/pull/8341) (@elindsey)
* [ ] [#9046 persist: avoid overwriting meta in storage with exactly the same bytes](https://github.com/MaterializeInc/materialize/pull/9046) (@danhhz)
* [ ] [#9047 dataflow: Distinct should not duplicate key in value](https://github.com/MaterializeInc/materialize/pull/9047) (@antiguru)
* [ ] [#9048 coord: actively close table timestamps each second](https://github.com/MaterializeInc/materialize/pull/9048) (@mjibson)
* [ ] [#8720 protobuf: support imported message types](https://github.com/MaterializeInc/materialize/pull/8720) (@cjubb39)
* [ ] [#9045 persist: use tokio and async in persistence handles](https://github.com/MaterializeInc/materialize/pull/9045) (@mkysel)
* [ ] [#9042 testdrive: do not retry COMMIT and ROLLBACK on error](https://github.com/MaterializeInc/materialize/pull/9042) (@philip-stoev)
* [ ] [#9051 dataflow: encode source delimited-ness in the type system](https://github.com/MaterializeInc/materialize/pull/9051) (@petrosagg)
* [ ] [#8947 Enable dataflowd/coord to work in clustered mode](https://github.com/MaterializeInc/materialize/pull/8947) (@antiguru)
* [ ] [#9054 persist: make monitoring durations more idiomatic](https://github.com/MaterializeInc/materialize/pull/9054) (@danhhz)
* [ ] [#9055 persist: make thread names more idiomatic](https://github.com/MaterializeInc/materialize/pull/9055) (@danhhz)
* [ ] [#9056 persist: expose external name on read and write handles](https://github.com/MaterializeInc/materialize/pull/9056) (@danhhz)
* [ ] [#9059 persist: disable background test when logical_compaction_window is off](https://github.com/MaterializeInc/materialize/pull/9059) (@danhhz)
* [ ] [#9061 Adds multi-region support to mzcloud cli](https://github.com/MaterializeInc/materialize/pull/9061) (@alex-hunt-materialize)
* [ ] [#9062 dataflowd: minor improvements](https://github.com/MaterializeInc/materialize/pull/9062) (@benesch)
* [ ] [#9037 coord: add simplified explanation of frontiers to docs](https://github.com/MaterializeInc/materialize/pull/9037) (@sploiselle)
* [ ] [#8937 sql: add information_schema._pg_expandarray](https://github.com/MaterializeInc/materialize/pull/8937) (@mjibson)
* [ ] [#9063 persist: change Blob::set allow_overwrite arg to be require_atomic](https://github.com/MaterializeInc/materialize/pull/9063) (@danhhz)
* [ ] [#9064 Partition commands rather than clone](https://github.com/MaterializeInc/materialize/pull/9064) (@frankmcsherry)
* [ ] [#9069 build(deps): bump whoami from 1.1.5 to 1.2.0](https://github.com/MaterializeInc/materialize/pull/9069) (@dependabot[bot])
* [ ] [#9070 build(deps): bump sysinfo from 0.20.5 to 0.21.1](https://github.com/MaterializeInc/materialize/pull/9070) (@dependabot[bot])
* [ ] [#9071 build(deps): bump hex-literal from 0.3.3 to 0.3.4](https://github.com/MaterializeInc/materialize/pull/9071) (@dependabot[bot])
* [ ] [#9068 build(deps): bump cc from 1.0.71 to 1.0.72](https://github.com/MaterializeInc/materialize/pull/9068) (@dependabot[bot])
* [ ] [#9066 build(deps): bump serde_json from 1.0.68 to 1.0.70](https://github.com/MaterializeInc/materialize/pull/9066) (@dependabot[bot])
* [ ] [#8989 build(deps): bump anyhow from 1.0.44 to 1.0.45](https://github.com/MaterializeInc/materialize/pull/8989) (@dependabot[bot])
* [ ] [#9065 dataflow: use `DecodeError` for all decode specific functionality](https://github.com/MaterializeInc/materialize/pull/9065) (@petrosagg)
* [ ] [#9039 coord: add pg_constraint](https://github.com/MaterializeInc/materialize/pull/9039) (@andrioni)
* [ ] [#9079 tweak some details in timestamp explanation](https://github.com/MaterializeInc/materialize/pull/9079) (@frankmcsherry)
* [ ] [#9086 Improve documentation around Kafka start_offset](https://github.com/MaterializeInc/materialize/pull/9086) (@quodlibetor)
* [ ] [#9067 build(deps): bump include_dir from 0.6.2 to 0.7.0](https://github.com/MaterializeInc/materialize/pull/9067) (@dependabot[bot])
* [ ] [#8987 build(deps): bump fail from `6cd91d5` to `481e53f`](https://github.com/MaterializeInc/materialize/pull/8987) (@dependabot[bot])
* [ ] [#9093 persist: add invariant that blob keys are globally unique.](https://github.com/MaterializeInc/materialize/pull/9093) (@ruchirK)
* [ ] [#9106 docs: Update `CREATE SINK` syntax in EO guide](https://github.com/MaterializeInc/materialize/pull/9106) (@morsapaes)
* [ ] [#9038 doc: Add FILTER to aggregate functions](https://github.com/MaterializeInc/materialize/pull/9038) (@mkysel)
* [ ] [#9096 Fix truncated sentence](https://github.com/MaterializeInc/materialize/pull/9096) (@msudberg)

</details>
