### ISSUE TITLE
release: v0.10.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9221]
The following PRs in [`v0.10.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.10.0-rc1) require review:
* [x] [#9119 Prepare 0.9.14 dev](https://github.com/MaterializeInc/materialize/pull/9119) (@umanwizard)
* [x] [#9100 sql: support table/set functions in select projections](https://github.com/MaterializeInc/materialize/pull/9100) (@mjibson)
* [x] [#9152 docs: update known SQL limitations](https://github.com/MaterializeInc/materialize/pull/9152) (@sploiselle)
* [x] [#9156 doc: Update links for temporal filters guide](https://github.com/MaterializeInc/materialize/pull/9156) (@msudberg)
* [x] [#9167 Continue 0.9.14 dev](https://github.com/MaterializeInc/materialize/pull/9167) (@umanwizard)
* [x] [#9120 Update docs navbar to match main site](https://github.com/MaterializeInc/materialize/pull/9120) (@msudberg)
* [x] [#9169 Update reuse-topic example with new syntax](https://github.com/MaterializeInc/materialize/pull/9169) (@msudberg)
* [x] [#9173 dataflow: test for github issue #9027, PR #9047](https://github.com/MaterializeInc/materialize/pull/9173) (@philip-stoev)
* [x] [#9178 test: Fix invalid query in limits test](https://github.com/MaterializeInc/materialize/pull/9178) (@philip-stoev)
* [x] [#9179 docs: add supporting docs for unique view column name requirement](https://github.com/MaterializeInc/materialize/pull/9179) (@sploiselle)
* [x] [#9115 doc: Kinesis resharding is not supported ](https://github.com/MaterializeInc/materialize/pull/9115) (@msudberg)
* [x] [#9153 doc: Warn that we do not support upstream truncation for Dbz and MySQL.](https://github.com/MaterializeInc/materialize/pull/9153) (@msudberg)
* [x] [#9187 make `setup.py sdist` actually produce an installable package, by inc…](https://github.com/MaterializeInc/materialize/pull/9187) (@umanwizard)
* [x] [#9220 sql: add missing aws_util feature](https://github.com/MaterializeInc/materialize/pull/9220) (@petrosagg)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#9119 Prepare 0.9.14 dev](https://github.com/MaterializeInc/materialize/pull/9119) (@umanwizard)
* [ ] [#9099 sql: correctly handle scope aliasing for table/set funcs](https://github.com/MaterializeInc/materialize/pull/9099) (@mjibson)
* [ ] [#9117 sql: avoid stack overflow on deeply nested ASTs](https://github.com/MaterializeInc/materialize/pull/9117) (@benesch)
* [ ] [#9100 sql: support table/set functions in select projections](https://github.com/MaterializeInc/materialize/pull/9100) (@mjibson)
* [ ] [#8969 Skeleton for QGM lowering into Mir](https://github.com/MaterializeInc/materialize/pull/8969) (@asenac)
* [ ] [#9081 Fix window function lowering for correlated subqueries](https://github.com/MaterializeInc/materialize/pull/9081) (@asenac)
* [ ] [#8990 Introduce a SET option to enable/disable QGM per connection](https://github.com/MaterializeInc/materialize/pull/8990) (@aalexandrov)
* [ ] [#9151 expr: rely less on macros and more on traits to define unary functions](https://github.com/MaterializeInc/materialize/pull/9151) (@petrosagg)
* [ ] [#9122 sql: disallow count(distinct *)](https://github.com/MaterializeInc/materialize/pull/9122) (@sploiselle)
* [ ] [#9152 docs: update known SQL limitations](https://github.com/MaterializeInc/materialize/pull/9152) (@sploiselle)
* [ ] [#9156 doc: Update links for temporal filters guide](https://github.com/MaterializeInc/materialize/pull/9156) (@msudberg)
* [ ] [#9098 Absorb (some) permutations into MFPs](https://github.com/MaterializeInc/materialize/pull/9098) (@umanwizard)
* [ ] [#9167 Continue 0.9.14 dev](https://github.com/MaterializeInc/materialize/pull/9167) (@umanwizard)
* [ ] [#9120 Update docs navbar to match main site](https://github.com/MaterializeInc/materialize/pull/9120) (@msudberg)
* [ ] [#9162 sql: prevent creating views with duplicate column names](https://github.com/MaterializeInc/materialize/pull/9162) (@sploiselle)
* [ ] [#9169 Update reuse-topic example with new syntax](https://github.com/MaterializeInc/materialize/pull/9169) (@msudberg)
* [ ] [#9171 sql: allow the Desugarer to grow its stack](https://github.com/MaterializeInc/materialize/pull/9171) (@mjibson)
* [ ] [#9173 dataflow: test for github issue #9027, PR #9047](https://github.com/MaterializeInc/materialize/pull/9173) (@philip-stoev)
* [ ] [#9176 doc: fix link to SSO app](https://github.com/MaterializeInc/materialize/pull/9176) (@andrioni)
* [ ] [#9178 test: Fix invalid query in limits test](https://github.com/MaterializeInc/materialize/pull/9178) (@philip-stoev)
* [ ] [#9179 docs: add supporting docs for unique view column name requirement](https://github.com/MaterializeInc/materialize/pull/9179) (@sploiselle)
* [ ] [#9177 cluster: Add a nightly testdrive task](https://github.com/MaterializeInc/materialize/pull/9177) (@philip-stoev)
* [ ] [#9184 sql: dispatch to a separate function when planning Expr variants](https://github.com/MaterializeInc/materialize/pull/9184) (@petrosagg)
* [ ] [#9087 persist: fix source bindings restore](https://github.com/MaterializeInc/materialize/pull/9087) (@aljoscha)
* [ ] [#9115 doc: Kinesis resharding is not supported ](https://github.com/MaterializeInc/materialize/pull/9115) (@msudberg)
* [ ] [#9183 ore: tolerate larger stacks in debug builds](https://github.com/MaterializeInc/materialize/pull/9183) (@benesch)
* [ ] [#9159 sql: initial support for regtype](https://github.com/MaterializeInc/materialize/pull/9159) (@mkysel)
* [ ] [#8725 doc: Configure Postgres CDC on Cloud services](https://github.com/MaterializeInc/materialize/pull/8725) (@msudberg)
* [ ] [#9168 doc: Add missing operators to EXPLAIN PLAN](https://github.com/MaterializeInc/materialize/pull/9168) (@msudberg)
* [ ] [#9153 doc: Warn that we do not support upstream truncation for Dbz and MySQL.](https://github.com/MaterializeInc/materialize/pull/9153) (@msudberg)
* [ ] [#9187 make `setup.py sdist` actually produce an installable package, by inc…](https://github.com/MaterializeInc/materialize/pull/9187) (@umanwizard)
* [ ] [#9191 bump tokio for security advisory](https://github.com/MaterializeInc/materialize/pull/9191) (@umanwizard)
* [ ] [#9186 Reorg dataflow interface](https://github.com/MaterializeInc/materialize/pull/9186) (@frankmcsherry)
* [ ] [#9198 sql: remove unecessary Rc wrapper](https://github.com/MaterializeInc/materialize/pull/9198) (@petrosagg)
* [ ] [#9197 sql: fix an error in splice_parameters in handling nested queries.](https://github.com/MaterializeInc/materialize/pull/9197) (@mkysel)
* [ ] [#9199 sql: fix generate_series_id oid to match PG](https://github.com/MaterializeInc/materialize/pull/9199) (@mkysel)
* [ ] [#9208 build(deps): bump timely from `596ca50` to `fa63c3a`](https://github.com/MaterializeInc/materialize/pull/9208) (@dependabot[bot])
* [ ] [#9209 build(deps): bump include_dir from 0.7.0 to 0.7.1](https://github.com/MaterializeInc/materialize/pull/9209) (@dependabot[bot])
* [ ] [#9212 build(deps): bump serde_json from 1.0.70 to 1.0.71](https://github.com/MaterializeInc/materialize/pull/9212) (@dependabot[bot])
* [ ] [#9213 build(deps): bump libc from 0.2.107 to 0.2.108](https://github.com/MaterializeInc/materialize/pull/9213) (@dependabot[bot])
* [ ] [#9214 build(deps): bump openssl-sys from 0.9.70 to 0.9.71](https://github.com/MaterializeInc/materialize/pull/9214) (@dependabot[bot])
* [ ] [#9215 build(deps): bump tracing-subscriber from 0.3.1 to 0.3.2](https://github.com/MaterializeInc/materialize/pull/9215) (@dependabot[bot])
* [ ] [#9216 build(deps): bump pdqselect from 0.1.0 to 0.1.1](https://github.com/MaterializeInc/materialize/pull/9216) (@dependabot[bot])
* [ ] [#8754 Upgrade to AWS Rust SDK](https://github.com/MaterializeInc/materialize/pull/8754) (@benesch)
* [ ] [#9210 build(deps): bump anyhow from 1.0.45 to 1.0.47](https://github.com/MaterializeInc/materialize/pull/9210) (@dependabot[bot])
* [ ] [#9105 calculate schemas of decode and envelope stages separately](https://github.com/MaterializeInc/materialize/pull/9105) (@petrosagg)
* [ ] [#9220 sql: add missing aws_util feature](https://github.com/MaterializeInc/materialize/pull/9220) (@petrosagg)

</details>

**Comment by petrosagg** [comment]
all look good
