### ISSUE TITLE
release: v0.11.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9394]
The following PRs in [`v0.11.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.11.0-rc1) require review:
* [x] [#9252 Continue 0.10.1 dev](https://github.com/MaterializeInc/materialize/pull/9252) (@petrosagg)
* [x] [#9275 testdrive: exclude protobuf schema registry tests from redpanda (again)](https://github.com/MaterializeInc/materialize/pull/9275) (@benesch)
* [x] [#9276 Revert "transform: make all optimizer types const"](https://github.com/MaterializeInc/materialize/pull/9276) (@petrosagg)
* [x] [#9294 ci: build native ARM binaries for macOS](https://github.com/MaterializeInc/materialize/pull/9294) (@benesch)
* [x] [#9296 ci/README: mark postgresql as a required install for macOS agents](https://github.com/MaterializeInc/materialize/pull/9296) (@benesch)
* [x] [#9295 deploy/macos: preserve environment when invoking cargo](https://github.com/MaterializeInc/materialize/pull/9295) (@benesch)
* [x] [#9297 doc/user: make version list scrollable](https://github.com/MaterializeInc/materialize/pull/9297) (@benesch)
* [x] [#9299 ci/deploy: further tweak macos deployment env vars](https://github.com/MaterializeInc/materialize/pull/9299) (@benesch)
* [x] [#9301 ci/deploy: fix arm64 -> aarch64 redirects for macos tarballs](https://github.com/MaterializeInc/materialize/pull/9301) (@benesch)
* [x] [#9329 doc: remove mention of a limitation of testdrive that has been lifted](https://github.com/MaterializeInc/materialize/pull/9329) (@philip-stoev)
* [x] [#9344 ci: build ci-builder on arm64 too](https://github.com/MaterializeInc/materialize/pull/9344) (@benesch)
* [x] [#9351 Persistence kafka testdrive nightly](https://github.com/MaterializeInc/materialize/pull/9351) (@philip-stoev)
* [x] [#9377 ci-builder: force consistent sort order when computing hash](https://github.com/MaterializeInc/materialize/pull/9377) (@benesch)
* [x] [#9229 persist: asynchronously retract in filter_and_retract_future_updates()](https://github.com/MaterializeInc/materialize/pull/9229) (@aljoscha)
* [x] [#9307 mzbuild: build ARM binaries](https://github.com/MaterializeInc/materialize/pull/9307) (@benesch)
* [x] [#9388 ci: fix macos deployment](https://github.com/MaterializeInc/materialize/pull/9388) (@benesch)
* [x] [#9389 deploy: fix multi-arch tarball upload](https://github.com/MaterializeInc/materialize/pull/9389) (@benesch)
* [x] [#9390 ci: fix nightly pipeline](https://github.com/MaterializeInc/materialize/pull/9390) (@benesch)
* [x] [#9391 ci/nightly: further correct the redpanda ARM job](https://github.com/MaterializeInc/materialize/pull/9391) (@benesch)
* [x] [#9392 ci/deploy: try a different tarball naming strategy](https://github.com/MaterializeInc/materialize/pull/9392) (@benesch)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#9094 reuse_topic: Create sink without timing out waiting for message](https://github.com/MaterializeInc/materialize/pull/9094) (@cjubb39)
* [ ] [#9252 Continue 0.10.1 dev](https://github.com/MaterializeInc/materialize/pull/9252) (@petrosagg)
* [ ] [#9254 sql: timestamp generate_series and overflow handling](https://github.com/MaterializeInc/materialize/pull/9254) (@sploiselle)
* [ ] [#9240 testdrive: rewrite protobuf tests](https://github.com/MaterializeInc/materialize/pull/9240) (@benesch)
* [ ] [#9237 persist: introduce Arrangement abstraction merging Unsealed and Trace](https://github.com/MaterializeInc/materialize/pull/9237) (@danhhz)
* [ ] [#9165 persist: columnar representation for unsealed batches](https://github.com/MaterializeInc/materialize/pull/9165) (@ruchirK)
* [ ] [#9247 transform: make all optimizer types const](https://github.com/MaterializeInc/materialize/pull/9247) (@petrosagg)
* [ ] [#9266 test: refactor the proxy test](https://github.com/MaterializeInc/materialize/pull/9266) (@philip-stoev)
* [ ] [#9263 doc: Add note about disk usage in Postgres source](https://github.com/MaterializeInc/materialize/pull/9263) (@morsapaes)
* [ ] [#9270 doc: Update Cloud sizes and available regions](https://github.com/MaterializeInc/materialize/pull/9270) (@msudberg)
* [ ] [#9275 testdrive: exclude protobuf schema registry tests from redpanda (again)](https://github.com/MaterializeInc/materialize/pull/9275) (@benesch)
* [ ] [#9276 Revert "transform: make all optimizer types const"](https://github.com/MaterializeInc/materialize/pull/9276) (@petrosagg)
* [ ] [#9277 Convert a few more unary functions](https://github.com/MaterializeInc/materialize/pull/9277) (@petrosagg)
* [ ] [#9280 sql: support special case COLLATE pg_catalog.default as a noop](https://github.com/MaterializeInc/materialize/pull/9280) (@mkysel)
* [ ] [#9288 expr: break out more unary function](https://github.com/MaterializeInc/materialize/pull/9288) (@petrosagg)
* [ ] [#9248 optimization: normalization of commutative operations](https://github.com/MaterializeInc/materialize/pull/9248) (@asenac)
* [ ] [#9290 expr: allow borrowed types when defining SQL functions](https://github.com/MaterializeInc/materialize/pull/9290) (@petrosagg)
* [ ] [#9188 Make `MirRelationExpr::*visit*` methods and HIR ⇒ MIR lowering stack safe](https://github.com/MaterializeInc/materialize/pull/9188) (@aalexandrov)
* [ ] [#9292 Revert "optimization: normalization of commutative operations"](https://github.com/MaterializeInc/materialize/pull/9292) (@asenac)
* [ ] [#9294 ci: build native ARM binaries for macOS](https://github.com/MaterializeInc/materialize/pull/9294) (@benesch)
* [ ] [#9296 ci/README: mark postgresql as a required install for macOS agents](https://github.com/MaterializeInc/materialize/pull/9296) (@benesch)
* [ ] [#9295 deploy/macos: preserve environment when invoking cargo](https://github.com/MaterializeInc/materialize/pull/9295) (@benesch)
* [ ] [#9298 expr: convert i64 casting functions to sqlfunc!](https://github.com/MaterializeInc/materialize/pull/9298) (@petrosagg)
* [ ] [#9297 doc/user: make version list scrollable](https://github.com/MaterializeInc/materialize/pull/9297) (@benesch)
* [ ] [#9299 ci/deploy: further tweak macos deployment env vars](https://github.com/MaterializeInc/materialize/pull/9299) (@benesch)
* [ ] [#9301 ci/deploy: fix arm64 -> aarch64 redirects for macos tarballs](https://github.com/MaterializeInc/materialize/pull/9301) (@benesch)
* [ ] [#9302 testdrive: add a new `psql-execute` action](https://github.com/MaterializeInc/materialize/pull/9302) (@benesch)
* [ ] [#9289 test: Refactor the redpanda testdrive job](https://github.com/MaterializeInc/materialize/pull/9289) (@philip-stoev)
* [ ] [#9306 doc: fix `testdrive` developer docs](https://github.com/MaterializeInc/materialize/pull/9306) (@mkysel)
* [ ] [#9309 build(deps): bump futures-util from 0.3.17 to 0.3.18](https://github.com/MaterializeInc/materialize/pull/9309) (@dependabot[bot])
* [ ] [#9310 build(deps): bump os_info from 3.0.7 to 3.0.8](https://github.com/MaterializeInc/materialize/pull/9310) (@dependabot[bot])
* [ ] [#9311 build(deps): bump syn from 1.0.81 to 1.0.82](https://github.com/MaterializeInc/materialize/pull/9311) (@dependabot[bot])
* [ ] [#9314 build(deps): bump procfs from 0.11.0 to 0.11.1](https://github.com/MaterializeInc/materialize/pull/9314) (@dependabot[bot])
* [ ] [#9319 build(deps): bump futures from 0.3.17 to 0.3.18](https://github.com/MaterializeInc/materialize/pull/9319) (@dependabot[bot])
* [ ] [#9320 build(deps): bump crc32fast from 1.2.1 to 1.2.2](https://github.com/MaterializeInc/materialize/pull/9320) (@dependabot[bot])
* [ ] [#9321 build(deps): bump whoami from 1.2.0 to 1.2.1](https://github.com/MaterializeInc/materialize/pull/9321) (@dependabot[bot])
* [ ] [#9323 build(deps): bump serde_json from 1.0.71 to 1.0.72](https://github.com/MaterializeInc/materialize/pull/9323) (@dependabot[bot])
* [ ] [#9325 build(deps): bump rdkafka from `f41af6c` to `354fe53`](https://github.com/MaterializeInc/materialize/pull/9325) (@dependabot[bot])
* [ ] [#9313 build(deps): bump aws-config from 0.0.25-alpha to 0.0.26-alpha](https://github.com/MaterializeInc/materialize/pull/9313) (@dependabot[bot])
* [ ] [#9324 build(deps): bump predicates from 2.0.3 to 2.1.0](https://github.com/MaterializeInc/materialize/pull/9324) (@dependabot[bot])
* [ ] [#9322 build(deps): bump anyhow from 1.0.47 to 1.0.50](https://github.com/MaterializeInc/materialize/pull/9322) (@dependabot[bot])
* [ ] [#9326 build(deps): bump ryu from 1.0.5 to 1.0.6](https://github.com/MaterializeInc/materialize/pull/9326) (@dependabot[bot])
* [ ] [#9304 Port testdrive mzcompose to python](https://github.com/MaterializeInc/materialize/pull/9304) (@philip-stoev)
* [ ] [#9329 doc: remove mention of a limitation of testdrive that has been lifted](https://github.com/MaterializeInc/materialize/pull/9329) (@philip-stoev)
* [ ] [#8643 sql: allow NOT ENFORCED keys for Kafka Upsert Sink](https://github.com/MaterializeInc/materialize/pull/8643) (@aljoscha)
* [ ] [#9335 sql: fix cargo test -p sql_parser compilation issue](https://github.com/MaterializeInc/materialize/pull/9335) (@mkysel)
* [ ] [#9338 persist: address a batch of encoding TODOs](https://github.com/MaterializeInc/materialize/pull/9338) (@danhhz)
* [ ] [#9260 sql: support ROWS FROM](https://github.com/MaterializeInc/materialize/pull/9260) (@mjibson)
* [ ] [#9337 ci: automatically build builder image in CI](https://github.com/MaterializeInc/materialize/pull/9337) (@benesch)
* [ ] [#9272 QGM: Support a bunch of BoxScalarExpr variants](https://github.com/MaterializeInc/materialize/pull/9272) (@wangandi)
* [ ] [#9255 sql: support OPERATOR syntax and default `pg_catalog` namespace](https://github.com/MaterializeInc/materialize/pull/9255) (@mkysel)
* [ ] [#9343 ci/www: use correct favicon for docs](https://github.com/MaterializeInc/materialize/pull/9343) (@benesch)
* [ ] [#9339 testdrive: support command="\dn <pattern>"](https://github.com/MaterializeInc/materialize/pull/9339) (@mkysel)
* [ ] [#9348 persist: remove unsealed_ts_upper](https://github.com/MaterializeInc/materialize/pull/9348) (@danhhz)
* [ ] [#9264 ccsr: minor cleanups](https://github.com/MaterializeInc/materialize/pull/9264) (@benesch)
* [ ] [#9019 interchange: simplify protobuf decoding code](https://github.com/MaterializeInc/materialize/pull/9019) (@benesch)
* [ ] [#9346 sql: full support for `\dt <pattern>`](https://github.com/MaterializeInc/materialize/pull/9346) (@mkysel)
* [ ] [#9344 ci: build ci-builder on arm64 too](https://github.com/MaterializeInc/materialize/pull/9344) (@benesch)
* [ ] [#9351 Persistence kafka testdrive nightly](https://github.com/MaterializeInc/materialize/pull/9351) (@philip-stoev)
* [ ] [#9361 ci/builder: correct multi-arch linker variables](https://github.com/MaterializeInc/materialize/pull/9361) (@benesch)
* [ ] [#9293 Merge pull request #9293 from aalexandrov/stacker_transform](https://github.com/MaterializeInc/materialize/pull/9293) (@aalexandrov)
* [ ] [#9363 coord,sql: remove mz_workers](https://github.com/MaterializeInc/materialize/pull/9363) (@benesch)
* [ ] [#9355 testdrive: reap Futures periodically during $ kafka-ingest](https://github.com/MaterializeInc/materialize/pull/9355) (@philip-stoev)
* [ ] [#9102 kafka: seek to correct start offset when creating kafka queue](https://github.com/MaterializeInc/materialize/pull/9102) (@aljoscha)
* [ ] [#9246  persist: seal errors must not allow the frontier to advance](https://github.com/MaterializeInc/materialize/pull/9246) (@aljoscha)
* [ ] [#9370 Fix wrong results issue when having a false THEN clause](https://github.com/MaterializeInc/materialize/pull/9370) (@asenac)
* [ ] [#9253 docs: Cloud monitoring](https://github.com/MaterializeInc/materialize/pull/9253) (@msudberg)
* [ ] [#9268 pg-cdc: support numeric data types without scale and precision](https://github.com/MaterializeInc/materialize/pull/9268) (@petrosagg)
* [ ] [#9364 sql: add support for REGCLASS](https://github.com/MaterializeInc/materialize/pull/9364) (@mkysel)
* [ ] [#9377 ci-builder: force consistent sort order when computing hash](https://github.com/MaterializeInc/materialize/pull/9377) (@benesch)
* [ ] [#9229 persist: asynchronously retract in filter_and_retract_future_updates()](https://github.com/MaterializeInc/materialize/pull/9229) (@aljoscha)
* [ ] [#9359 expr: Convert more `strto*` cast functions and `numeric` functions to `sqlfunc!`](https://github.com/MaterializeInc/materialize/pull/9359) (@petrosagg)
* [ ] [#9239 persist: actually use columnar encoding for unsealed batches.](https://github.com/MaterializeInc/materialize/pull/9239) (@ruchirK)
* [ ] [#9307 mzbuild: build ARM binaries](https://github.com/MaterializeInc/materialize/pull/9307) (@benesch)
* [ ] [#9261 doc: Workspace and user management options.](https://github.com/MaterializeInc/materialize/pull/9261) (@msudberg)
* [ ] [#9256 doc: Add disabling user index on Cloud](https://github.com/MaterializeInc/materialize/pull/9256) (@msudberg)
* [ ] [#9381 interchange: accept protobuf message names without a leading dot](https://github.com/MaterializeInc/materialize/pull/9381) (@benesch)
* [ ] [#9365 persist: use protobuf for metadata encoding](https://github.com/MaterializeInc/materialize/pull/9365) (@danhhz)
* [ ] [#9386 coord: don't call sources-only code when dropping tables](https://github.com/MaterializeInc/materialize/pull/9386) (@mjibson)
* [ ] [#9358 Abstract clients to present as a single worker](https://github.com/MaterializeInc/materialize/pull/9358) (@frankmcsherry)
* [ ] [#9388 ci: fix macos deployment](https://github.com/MaterializeInc/materialize/pull/9388) (@benesch)
* [ ] [#9389 deploy: fix multi-arch tarball upload](https://github.com/MaterializeInc/materialize/pull/9389) (@benesch)
* [ ] [#9390 ci: fix nightly pipeline](https://github.com/MaterializeInc/materialize/pull/9390) (@benesch)
* [ ] [#9342 dbt-materialize: use one parameterized spec file](https://github.com/MaterializeInc/materialize/pull/9342) (@benesch)
* [ ] [#9391 ci/nightly: further correct the redpanda ARM job](https://github.com/MaterializeInc/materialize/pull/9391) (@benesch)
* [ ] [#9392 ci/deploy: try a different tarball naming strategy](https://github.com/MaterializeInc/materialize/pull/9392) (@benesch)

</details>

**Comment by umanwizard** [comment]
nikhil's PRs LGTM
