### ISSUE TITLE
release: v0.11.0-rc2 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9450]
The following PRs in [`v0.11.0-rc2`](https://github.com/MaterializeInc/materialize/tree/v0.11.0-rc2) require review:
* [x] [#9395 Prepare 0.11.1 dev](https://github.com/MaterializeInc/materialize/pull/9395) (@benesch)
* [x] [#9404 ci/deploy: add missing f-string specifier](https://github.com/MaterializeInc/materialize/pull/9404) (@benesch)
* [x] [#9408 ci: fix binary tarball uploading for linux](https://github.com/MaterializeInc/materialize/pull/9408) (@benesch)
* [x] [#9438 test: fix test/testdrive/mzworkfows.py](https://github.com/MaterializeInc/materialize/pull/9438) (@philip-stoev)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#9395 Prepare 0.11.1 dev](https://github.com/MaterializeInc/materialize/pull/9395) (@benesch)
* [ ] [#9341 Fast follow-ups from #9000](https://github.com/MaterializeInc/materialize/pull/9341) (@aalexandrov)
* [ ] [#9279 Doc: Update COPY FROM options](https://github.com/MaterializeInc/materialize/pull/9279) (@msudberg)
* [ ] [#9401 persist: fix error on empty writes](https://github.com/MaterializeInc/materialize/pull/9401) (@ruchirK)
* [ ] [#9400 sql: add pg_catalog.pg_tables view](https://github.com/MaterializeInc/materialize/pull/9400) (@mkysel)
* [ ] [#9402 Fix bin/check: the `-A style` after denying style lints re-allowed them](https://github.com/MaterializeInc/materialize/pull/9402) (@quodlibetor)
* [ ] [#9385 protobuf: Normalize protobuf message names](https://github.com/MaterializeInc/materialize/pull/9385) (@cjubb39)
* [ ] [#9404 ci/deploy: add missing f-string specifier](https://github.com/MaterializeInc/materialize/pull/9404) (@benesch)
* [ ] [#9366 sql: allow multiple table functions as long as they are identical](https://github.com/MaterializeInc/materialize/pull/9366) (@mjibson)
* [ ] [#9379 reuse_topic: Add index to timestamp bindings table](https://github.com/MaterializeInc/materialize/pull/9379) (@cjubb39)
* [ ] [#9259 doc: Tailscale connection instructions](https://github.com/MaterializeInc/materialize/pull/9259) (@msudberg)
* [ ] [#9408 ci: fix binary tarball uploading for linux](https://github.com/MaterializeInc/materialize/pull/9408) (@benesch)
* [ ] [#9412 Use uname -m instead of arch](https://github.com/MaterializeInc/materialize/pull/9412) (@antiguru)
* [ ] [#9415 persist: two small refactors to persist operators](https://github.com/MaterializeInc/materialize/pull/9415) (@ruchirK)
* [ ] [#9426 build(deps): bump clap from 2.33.3 to 2.34.0](https://github.com/MaterializeInc/materialize/pull/9426) (@dependabot[bot])
* [ ] [#9427 build(deps): bump anyhow from 1.0.50 to 1.0.51](https://github.com/MaterializeInc/materialize/pull/9427) (@dependabot[bot])
* [ ] [#9429 build(deps): bump rdkafka-sys from `354fe53` to `bbd3417`](https://github.com/MaterializeInc/materialize/pull/9429) (@dependabot[bot])
* [ ] [#9423 build(deps): bump reqwest from 0.11.6 to 0.11.7](https://github.com/MaterializeInc/materialize/pull/9423) (@dependabot[bot])
* [ ] [#9421 build(deps): bump libc from 0.2.108 to 0.2.109](https://github.com/MaterializeInc/materialize/pull/9421) (@dependabot[bot])
* [ ] [#9430 build(deps): bump proc-macro2 from 1.0.32 to 1.0.33](https://github.com/MaterializeInc/materialize/pull/9430) (@dependabot[bot])
* [ ] [#9422 build(deps): bump crc32fast from 1.2.2 to 1.3.0](https://github.com/MaterializeInc/materialize/pull/9422) (@dependabot[bot])
* [ ] [#9431 build(deps): bump tracing-subscriber from 0.3.2 to 0.3.3](https://github.com/MaterializeInc/materialize/pull/9431) (@dependabot[bot])
* [ ] [#9425 build(deps): bump aws-sdk-s3 from 0.0.26-alpha to 0.2.0](https://github.com/MaterializeInc/materialize/pull/9425) (@dependabot[bot])
* [ ] [#9436 test/redpanda: enable protobuf schema tests](https://github.com/MaterializeInc/materialize/pull/9436) (@benesch)
* [ ] [#9437 Various CI and build bugfixes](https://github.com/MaterializeInc/materialize/pull/9437) (@benesch)
* [ ] [#9438 test: fix test/testdrive/mzworkfows.py](https://github.com/MaterializeInc/materialize/pull/9438) (@philip-stoev)

</details>

**Comment by quodlibetor** [comment]
the 3 nikhil PRs all LGTM.
