### ISSUE TITLE
release: v0.11.0-rc3 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9459]
The following PRs in [`v0.11.0-rc3`](https://github.com/MaterializeInc/materialize/tree/v0.11.0-rc3) require review:

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#9447 github: Improve pull request template](https://github.com/MaterializeInc/materialize/pull/9447) (@antiguru)
* [ ] [#9454 doc: Cloud maintenance windows & navigation fixes](https://github.com/MaterializeInc/materialize/pull/9454) (@msudberg)
* [ ] [#9455 Make the kafka-sink-errors testdrive test os-independent](https://github.com/MaterializeInc/materialize/pull/9455) (@quodlibetor)
* [ ] [#9456 Modernize s3.rs's error handling](https://github.com/MaterializeInc/materialize/pull/9456) (@guswynn)
* [ ] [#9458 demo/chbench: downgrade to mysql odbc v8.0.26](https://github.com/MaterializeInc/materialize/pull/9458) (@benesch)

</details>
