### ISSUE TITLE
release: v0.12.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9583]
The following PRs in [`v0.12.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.12.0-rc1) require review:
* [x] [#9476 test/redpanda: Update Redpanda to v21.11.1](https://github.com/MaterializeInc/materialize/pull/9476) (@BenPope)
* [x] [#9478 persistence,test: Run the product limits tests with persistence enabled](https://github.com/MaterializeInc/materialize/pull/9478) (@philip-stoev)
* [x] [#9520 deps: bundle latest dependabot python updates](https://github.com/MaterializeInc/materialize/pull/9520) (@benesch)
* [x] [#9534 deps: update dependabot configuration](https://github.com/MaterializeInc/materialize/pull/9534) (@benesch)
* [x] [#9556 test/kafka-exactly-once: use standard kafka version, not latest](https://github.com/MaterializeInc/materialize/pull/9556) (@benesch)

**Comment by materializer** [comment]
<details>
<summary>All PRs</summary>

* [ ] [#9356 testdrive: Provide additional control over the retry policy](https://github.com/MaterializeInc/materialize/pull/9356) (@philip-stoev)
* [ ] [#9387 expr: more unary func conversion](https://github.com/MaterializeInc/materialize/pull/9387) (@petrosagg)
* [ ] [#9398 Improve key information for Filter](https://github.com/MaterializeInc/materialize/pull/9398) (@asenac)
* [ ] [#9451 persist: add get_description()](https://github.com/MaterializeInc/materialize/pull/9451) (@aljoscha)
* [ ] [#9457 testdrive: Don't truncate SQL queries](https://github.com/MaterializeInc/materialize/pull/9457) (@quodlibetor)
* [ ] [#9445 mzbench-opt: add a Python package for optimizer benchmarks](https://github.com/MaterializeInc/materialize/pull/9445) (@aalexandrov)
* [ ] [#9464 Update careers link (404).](https://github.com/MaterializeInc/materialize/pull/9464) (@morsapaes)
* [ ] [#9476 test/redpanda: Update Redpanda to v21.11.1](https://github.com/MaterializeInc/materialize/pull/9476) (@BenPope)
* [ ] [#9475 mzbuild: update dependency on ci/builder](https://github.com/MaterializeInc/materialize/pull/9475) (@benesch)
* [ ] [#9465 persist: make create_or_load() infallible](https://github.com/MaterializeInc/materialize/pull/9465) (@aljoscha)
* [ ] [#9469 doc: Cloud Edit button, deployment metrics](https://github.com/MaterializeInc/materialize/pull/9469) (@msudberg)
* [ ] [#9467 test/cluster: write up instructions for manual clustering demo](https://github.com/MaterializeInc/materialize/pull/9467) (@benesch)
* [ ] [#9478 persistence,test: Run the product limits tests with persistence enabled](https://github.com/MaterializeInc/materialize/pull/9478) (@philip-stoev)
* [ ] [#9416 persist: build retract_unsealed out of persist and other timely operators.](https://github.com/MaterializeInc/materialize/pull/9416) (@ruchirK)
* [ ] [#9466 Create a crate dependency diagram script](https://github.com/MaterializeInc/materialize/pull/9466) (@quodlibetor)
* [ ] [#9481 optbench: move ` src/transform/benches/mzbench_opt` to `misc/python/materialize/optbench`](https://github.com/MaterializeInc/materialize/pull/9481) (@aalexandrov)
* [ ] [#9491 Generic timestamp interval match](https://github.com/MaterializeInc/materialize/pull/9491) (@sploiselle)
* [ ] [#9492 persist: fix race condition in nemesis test caused by #9465](https://github.com/MaterializeInc/materialize/pull/9492) (@aljoscha)
* [ ] [#9488 Add timestamp_frequency_ms option to Postgres.](https://github.com/MaterializeInc/materialize/pull/9488) (@msudberg)
* [ ] [#9487 persist,table: refactor Tables and SourceDesc to make clear what the persisted_name does](https://github.com/MaterializeInc/materialize/pull/9487) (@aljoscha)
* [ ] [#9497 release: announce v0.11.0](https://github.com/MaterializeInc/materialize/pull/9497) (@benesch)
* [ ] [#9498 .github: update release checklist](https://github.com/MaterializeInc/materialize/pull/9498) (@benesch)
* [ ] [#9499 Backfill release notes](https://github.com/MaterializeInc/materialize/pull/9499) (@benesch)
* [ ] [#9444 coord, dataflow: Move TAIL row processing to coord](https://github.com/MaterializeInc/materialize/pull/9444) (@antiguru)
* [ ] [#9506 support docker-compose versions with 'v' prefixes in mzcompose](https://github.com/MaterializeInc/materialize/pull/9506) (@guswynn)
* [ ] [#9505 qgm: newtype definitions `BoxId` and `QuantifierId`](https://github.com/MaterializeInc/materialize/pull/9505) (@aalexandrov)
* [ ] [#9507 Fix for security advisory](https://github.com/MaterializeInc/materialize/pull/9507) (@umanwizard)
* [ ] [#9486 sql: add support for `pg_type_is_visible`](https://github.com/MaterializeInc/materialize/pull/9486) (@mkysel)
* [ ] [#9516 ci: add python3 to macOS brew deps](https://github.com/MaterializeInc/materialize/pull/9516) (@benesch)
* [ ] [#9518 Rename 6 current_source upgrade tests to v0.11.0](https://github.com/MaterializeInc/materialize/pull/9518) (@benesch)
* [ ] [#9520 deps: bundle latest dependabot python updates](https://github.com/MaterializeInc/materialize/pull/9520) (@benesch)
* [ ] [#9523 fix x86 xcompile step of mzcompose](https://github.com/MaterializeInc/materialize/pull/9523) (@cjubb39)
* [ ] [#9524 linear: Fix permutation for lower/upper bounds](https://github.com/MaterializeInc/materialize/pull/9524) (@antiguru)
* [ ] [#9528 website: Fix download links](https://github.com/MaterializeInc/materialize/pull/9528) (@quodlibetor)
* [ ] [#9529 website: Correct curl install one-liners](https://github.com/MaterializeInc/materialize/pull/9529) (@quodlibetor)
* [ ] [#9530 sql: structure more errors](https://github.com/MaterializeInc/materialize/pull/9530) (@benesch)
* [ ] [#9517 doc: PREPARE/EXECUTE/DEALLOCATE](https://github.com/MaterializeInc/materialize/pull/9517) (@msudberg)
* [ ] [#9494 Implement pg_get_constraintdef](https://github.com/MaterializeInc/materialize/pull/9494) (@guswynn)
* [ ] [#9534 deps: update dependabot configuration](https://github.com/MaterializeInc/materialize/pull/9534) (@benesch)
* [ ] [#9513 sql: move more unary funcs to new framework](https://github.com/MaterializeInc/materialize/pull/9513) (@sploiselle)
* [ ] [#9543 build(deps): bump hyper from 0.14.15 to 0.14.16](https://github.com/MaterializeInc/materialize/pull/9543) (@dependabot[bot])
* [ ] [#9547 build(deps): bump dogsdogsdogs from `c696ec0` to `19808dc`](https://github.com/MaterializeInc/materialize/pull/9547) (@dependabot[bot])
* [ ] [#9548 build(deps): bump chrono-tz from 0.6.0 to 0.6.1](https://github.com/MaterializeInc/materialize/pull/9548) (@dependabot[bot])
* [ ] [#9556 test/kafka-exactly-once: use standard kafka version, not latest](https://github.com/MaterializeInc/materialize/pull/9556) (@benesch)
* [ ] [#9555 build(deps): bump ryu from 1.0.6 to 1.0.7](https://github.com/MaterializeInc/materialize/pull/9555) (@dependabot[bot])
* [ ] [#9553 build(deps): bump include_dir from 0.7.1 to 0.7.2](https://github.com/MaterializeInc/materialize/pull/9553) (@dependabot[bot])
* [ ] [#9550 build(deps): bump inotify from 0.9.6 to 0.10.0](https://github.com/MaterializeInc/materialize/pull/9550) (@dependabot[bot])
* [ ] [#9545 build(deps): bump async-trait from 0.1.51 to 0.1.52](https://github.com/MaterializeInc/materialize/pull/9545) (@dependabot[bot])
* [ ] [#9542 build(deps): bump sysinfo from 0.21.1 to 0.21.2](https://github.com/MaterializeInc/materialize/pull/9542) (@dependabot[bot])
* [ ] [#9559 build(deps): bump procfs from 0.11.1 to 0.12.0](https://github.com/MaterializeInc/materialize/pull/9559) (@dependabot[bot])
* [ ] [#9561 build(deps): bump itertools from 0.10.1 to 0.10.3](https://github.com/MaterializeInc/materialize/pull/9561) (@dependabot[bot])
* [ ] [#9549 build(deps): bump serde from 1.0.130 to 1.0.131](https://github.com/MaterializeInc/materialize/pull/9549) (@dependabot[bot])
* [ ] [#9566 build(deps): bump ryu from 1.0.7 to 1.0.9](https://github.com/MaterializeInc/materialize/pull/9566) (@dependabot[bot])
* [ ] [#9567 build(deps): bump libc from 0.2.109 to 0.2.111](https://github.com/MaterializeInc/materialize/pull/9567) (@dependabot[bot])
* [ ] [#8935 Pass kafka metadata into dataflows](https://github.com/MaterializeInc/materialize/pull/8935) (@quodlibetor)

</details>

**Comment by petrosagg** [comment]
All looks good
