### ISSUE TITLE
release: v0.13.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9692]
The following PRs in [`v0.13.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.13.0-rc1) require review:
* [x] [#9579 deploy: ensure macOS rustup target exists](https://github.com/MaterializeInc/materialize/pull/9579) (@benesch)
* [x] [#9582 play/nix: add postgres build dependency](https://github.com/MaterializeInc/materialize/pull/9582) (@petrosagg)
* [x] [#9584 Prepare 0.12.1 dev](https://github.com/MaterializeInc/materialize/pull/9584) (@petrosagg)
* [x] [#9592 fix command in release issue template](https://github.com/MaterializeInc/materialize/pull/9592) (@petrosagg)
* [x] [#6533 symbiosis: remove](https://github.com/MaterializeInc/materialize/pull/6533) (@benesch)
* [x] [#9627 test,persistence: Add an explicit test for persistence and --disable-…](https://github.com/MaterializeInc/materialize/pull/9627) (@philip-stoev)
* [x] [#9645 perf/upsert: remove outdated source persistence options](https://github.com/MaterializeInc/materialize/pull/9645) (@ruchirK)
* [x] [#9647 mzcompose: bump to latest localstack](https://github.com/MaterializeInc/materialize/pull/9647) (@benesch)
* [x] [#9672 http_logs demo: Fix setup](https://github.com/MaterializeInc/materialize/pull/9672) (@ra-kete)
* [x] [#9688 test,persist: disable kafka-sources/failpoint-after.td until #9687 is…](https://github.com/MaterializeInc/materialize/pull/9688) (@philip-stoev)

**Comment by materializer** [comment]
All PRs:

* [ ] [#9477 QGM: Add support for Get](https://github.com/MaterializeInc/materialize/pull/9477) (@wangandi)
* [ ] [#9537 build(deps): bump dbt-postgres from 0.21.0 to 1.0.0 in /misc/dbt-materialize](https://github.com/MaterializeInc/materialize/pull/9537) (@dependabot[bot])
* [ ] [#9569 CASE optimization with boolean literals](https://github.com/MaterializeInc/materialize/pull/9569) (@asenac)
* [ ] [#9575 xcompile: use a host toolchain on M1 Macs too](https://github.com/MaterializeInc/materialize/pull/9575) (@benesch)
* [ ] [#9577 doc: copy edit release notes](https://github.com/MaterializeInc/materialize/pull/9577) (@sploiselle)
* [ ] [#9496 Upgrade to rust 1.57](https://github.com/MaterializeInc/materialize/pull/9496) (@guswynn)
* [ ] [#9579 deploy: ensure macOS rustup target exists](https://github.com/MaterializeInc/materialize/pull/9579) (@benesch)
* [ ] [#9533 sql: produce a friendlier error when referencing ungrouped column](https://github.com/MaterializeInc/materialize/pull/9533) (@benesch)
* [ ] [#9462 persistence: tests for persistent Kafka upsert sources](https://github.com/MaterializeInc/materialize/pull/9462) (@philip-stoev)
* [ ] [#9582 play/nix: add postgres build dependency](https://github.com/MaterializeInc/materialize/pull/9582) (@petrosagg)
* [ ] [#9584 Prepare 0.12.1 dev](https://github.com/MaterializeInc/materialize/pull/9584) (@petrosagg)
* [ ] [#9589 build(deps): bump libc from 0.2.111 to 0.2.112](https://github.com/MaterializeInc/materialize/pull/9589) (@dependabot[bot])
* [ ] [#9591 misc/ssh: do not use SSH agent when identity file is specified](https://github.com/MaterializeInc/materialize/pull/9591) (@petrosagg)
* [ ] [#9592 fix command in release issue template](https://github.com/MaterializeInc/materialize/pull/9592) (@petrosagg)
* [ ] [#9588 build(deps): bump phf from 0.10.0 to 0.10.1](https://github.com/MaterializeInc/materialize/pull/9588) (@dependabot[bot])
* [ ] [#9585 build(deps): bump openssl-sys from 0.9.71 to 0.9.72](https://github.com/MaterializeInc/materialize/pull/9585) (@dependabot[bot])
* [ ] [#6533 symbiosis: remove](https://github.com/MaterializeInc/materialize/pull/6533) (@benesch)
* [ ] [#9552 sql: implement pg_am as an empty view](https://github.com/MaterializeInc/materialize/pull/9552) (@mkysel)
* [ ] [#9580 doc/user,demo/chbench: update for unforked metabase](https://github.com/MaterializeInc/materialize/pull/9580) (@benesch)
* [ ] [#9581 doc: Update Redpanda page](https://github.com/MaterializeInc/materialize/pull/9581) (@morsapaes)
* [ ] [#9594 Uncomment debug-disabled tests](https://github.com/MaterializeInc/materialize/pull/9594) (@quodlibetor)
* [ ] [#9586 build(deps): bump serde_json from 1.0.72 to 1.0.73](https://github.com/MaterializeInc/materialize/pull/9586) (@dependabot[bot])
* [ ] [#9519 persist: refuse to read data from the future](https://github.com/MaterializeInc/materialize/pull/9519) (@danhhz)
* [ ] [#9597 add --ci-output back to testdrive mzworkflows](https://github.com/MaterializeInc/materialize/pull/9597) (@quodlibetor)
* [ ] [#9472 sql: add support for generate_subscripts for 1-dimensional arrays](https://github.com/MaterializeInc/materialize/pull/9472) (@mkysel)
* [ ] [#9599 sql: add tests to confirm multi-dimensional generate_subscripts](https://github.com/MaterializeInc/materialize/pull/9599) (@mkysel)
* [ ] [#9606 Fix panic with outer columns in the ON clause](https://github.com/MaterializeInc/materialize/pull/9606) (@asenac)
* [ ] [#9490 persist: fix seal operator to only downgrade after successful seals](https://github.com/MaterializeInc/materialize/pull/9490) (@ruchirK)
* [ ] [#9596 coord,persist: make source persist details more structured/detailed on coordinator](https://github.com/MaterializeInc/materialize/pull/9596) (@aljoscha)
* [ ] [#9053 optimization: make `RedundantJoin` work on non-column expressions](https://github.com/MaterializeInc/materialize/pull/9053) (@asenac)
* [ ] [#9489 sql: refactor USING constraint planning](https://github.com/MaterializeInc/materialize/pull/9489) (@sploiselle)
* [ ] [#9417 reimplement `conditional_seal` in terms of `seal`](https://github.com/MaterializeInc/materialize/pull/9417) (@ruchirK)
* [ ] [#9527 Correctly serialize and deserialize simplistic confluent schema magic for protobuf](https://github.com/MaterializeInc/materialize/pull/9527) (@guswynn)
* [ ] [#8399 Optimization: Reduction Pushdown V2 Part 1](https://github.com/MaterializeInc/materialize/pull/8399) (@wangandi)
* [ ] [#9617 deps: opt into the new feature resolver](https://github.com/MaterializeInc/materialize/pull/9617) (@benesch)
* [ ] [#9622 Clarify .*DecoderState .expect errors](https://github.com/MaterializeInc/materialize/pull/9622) (@guswynn)
* [ ] [#9624 deps: bump to latest AWS SDKs](https://github.com/MaterializeInc/materialize/pull/9624) (@benesch)
* [ ] [#9627 test,persistence: Add an explicit test for persistence and --disable-…](https://github.com/MaterializeInc/materialize/pull/9627) (@philip-stoev)
* [ ] [#9629 attempt to get `mzcompose run testdrive` working m1 macs](https://github.com/MaterializeInc/materialize/pull/9629) (@guswynn)
* [ ] [#9630 xcompile: allow parent dir to not exist](https://github.com/MaterializeInc/materialize/pull/9630) (@cjubb39)
* [ ] [#9633 doc/user: migrate to new docsearch application](https://github.com/MaterializeInc/materialize/pull/9633) (@benesch)
* [ ] [#9636 persist: tweak Codec](https://github.com/MaterializeInc/materialize/pull/9636) (@danhhz)
* [ ] [#9638 play/nix: use `mold` to link materialize](https://github.com/MaterializeInc/materialize/pull/9638) (@petrosagg)
* [ ] [#9623 sql: correct lateral scoping in the face of outer joins](https://github.com/MaterializeInc/materialize/pull/9623) (@benesch)
* [ ] [#9640 xcompile: use different toolchains on x86 and M1 OS X](https://github.com/MaterializeInc/materialize/pull/9640) (@cjubb39)
* [ ] [#9642 Fix AWS timeout warnings in console logs](https://github.com/MaterializeInc/materialize/pull/9642) (@quodlibetor)
* [ ] [#9645 perf/upsert: remove outdated source persistence options](https://github.com/MaterializeInc/materialize/pull/9645) (@ruchirK)
* [ ] [#9647 mzcompose: bump to latest localstack](https://github.com/MaterializeInc/materialize/pull/9647) (@benesch)
* [ ] [#9646 Continue 0.12.1 dev](https://github.com/MaterializeInc/materialize/pull/9646) (@umanwizard)
* [ ] [#9649 fix double closing brace in non-f string](https://github.com/MaterializeInc/materialize/pull/9649) (@umanwizard)
* [ ] [#9650 doc/user: complete and polish v0.12 release notes](https://github.com/MaterializeInc/materialize/pull/9650) (@benesch)
* [ ] [#9609 Support for scalar subqueries in QGM](https://github.com/MaterializeInc/materialize/pull/9609) (@asenac)
* [ ] [#9626 persist,dataflow: make source rendering deterministic on workers](https://github.com/MaterializeInc/materialize/pull/9626) (@aljoscha)
* [ ] [#9654 Fix lowering panic with LATERAL references in ROWS FROM](https://github.com/MaterializeInc/materialize/pull/9654) (@asenac)
* [ ] [#9658 Normalize table function names in ROWS FROM](https://github.com/MaterializeInc/materialize/pull/9658) (@asenac)
* [ ] [#9660 make protobuf-import more robust against different worker amounts](https://github.com/MaterializeInc/materialize/pull/9660) (@guswynn)
* [ ] [#9648 mkrelease: Allow creating a release other than the latest tag](https://github.com/MaterializeInc/materialize/pull/9648) (@quodlibetor)
* [ ] [#9510 persist: split out a read-only subset of the Blob trait](https://github.com/MaterializeInc/materialize/pull/9510) (@danhhz)
* [ ] [#9667 pyactivate: Ensure pip and setuptools are up to date](https://github.com/MaterializeInc/materialize/pull/9667) (@quodlibetor)
* [ ] [#9671 doc: Restore Debezium page in "Third-party Tools"](https://github.com/MaterializeInc/materialize/pull/9671) (@morsapaes)
* [ ] [#9672 http_logs demo: Fix setup](https://github.com/MaterializeInc/materialize/pull/9672) (@ra-kete)
* [ ] [#9673 build(deps): bump num_enum from 0.5.4 to 0.5.5](https://github.com/MaterializeInc/materialize/pull/9673) (@dependabot[bot])
* [ ] [#9674 build(deps): bump tokio from 1.14.0 to 1.15.0](https://github.com/MaterializeInc/materialize/pull/9674) (@dependabot[bot])
* [ ] [#9675 build(deps): bump futures from 0.3.18 to 0.3.19](https://github.com/MaterializeInc/materialize/pull/9675) (@dependabot[bot])
* [ ] [#9677 build(deps): bump proc-macro2 from 1.0.33 to 1.0.34](https://github.com/MaterializeInc/materialize/pull/9677) (@dependabot[bot])
* [ ] [#9678 build(deps): bump futures-util from 0.3.18 to 0.3.19](https://github.com/MaterializeInc/materialize/pull/9678) (@dependabot[bot])
* [ ] [#9680 build(deps): bump nix from 0.23.0 to 0.23.1](https://github.com/MaterializeInc/materialize/pull/9680) (@dependabot[bot])
* [ ] [#9683 build(deps): bump tar from 0.4.37 to 0.4.38](https://github.com/MaterializeInc/materialize/pull/9683) (@dependabot[bot])
* [ ] [#9685 build(deps): bump sysinfo from 0.21.2 to 0.22.3](https://github.com/MaterializeInc/materialize/pull/9685) (@dependabot[bot])
* [ ] [#9681 build(deps): bump timely from `dd60878` to `1f09f66`](https://github.com/MaterializeInc/materialize/pull/9681) (@dependabot[bot])
* [ ] [#9679 build(deps): bump serde from 1.0.131 to 1.0.132](https://github.com/MaterializeInc/materialize/pull/9679) (@dependabot[bot])
* [ ] [#9688 test,persist: disable kafka-sources/failpoint-after.td until #9687 is…](https://github.com/MaterializeInc/materialize/pull/9688) (@philip-stoev)
