### ISSUE TITLE
Support DBeaver

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#9694]
[DBeaver Community](https://dbeaver.io/) is a multi-platform open source GUI SQL client that supports multiple databases.

This is an umbrella issue to track the work required to make DBeaver work out of the box with Materialize, when using the Postgres connector (via pgjdbc).

## Open issues
- [x] #8760
- [x] #9695
- [x] #9711 
- [x] #9728
- [x] Support `pg_tablespace` (relation in `pg_catalog`) (#19407)
- [x] Support `reltablespace` (column in `pg_class`) (required for viewing indexes in the UI)
- [x] Support `pg_aggregate` with columns `oid` and `proname` (relation in `pg_catalog`) (required for viewing aggregate functions in the UI)
- [x] Support `pg_trigger` with column `oid` (relation in `pg_catalog`) (required for viewing triggers attached to a table or view) (#19424)
- [x] Support `pg_rewrite` with column `oid` (relation in `pg_catalog`) (required for viewing rules attached to a table or view)
- [x] Support `pg_get_ruledef` (function in `pg_catalog`) (no-op implementation should be fine) (required for viewing rules attached to a table or view)
- [x] #9204 (required for viewing table or view dependencies)
- [x] Support `pg_get_viewdef` (function in `pg_catalog`) (required for viewing view definitions)
- [x] Support `pg_extension` (relation in `pg_catalog`) (required for listing extensions on a database)
- [x] #20426

## Lower priority issues (no visible error)
- [ ] Support `pg_get_keywords` (function in `pg_catalog`) (gets called on startup, no noticeable issues when it fails)

Note: the lists above are not exhaustive.

**Comment by ruf-io** [comment]
@morsapaes @andrioni I noticed this conflicts with the information in docs https://materialize.com/docs/integrations/#sql-clients

is docs wrong?

**Comment by andrioni** [comment]
I think the interpretation we had at that time is that while not everything in DBeaver works, the parts that don't work are because they use features we don't support nor intend to support anytime soon (e.g. triggers).

**Comment by morsapaes** [comment]
What Alessandro said! The non-working parts were pinned down in: https://github.com/MaterializeInc/developer-experience/discussions/53

**Comment by benesch** [comment]
Have we talked to the DBeaver folks at all about contributing a first-class Materialize integration? Eyeballing the CockroachDB integration, it seems like not a whole lot of work. They already have the concept of "PostgreSQL-like but not quite PostgreSQL integration."

**Comment by morsapaes** [comment]
We haven't, but from their [contribution guidelines](https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code) it seems like we can just open an issue in the repo and wait for a green light. The work with these custom integrations comes more from maintaining them over time than implementing them, though. DBeaver has been around for a long while, and looking through the [latest releases](https://dbeaver.io/category/releases/), it seems like it'd be manageable to support a custom connector.

**Comment by benesch** [comment]
Things are _much_ improved after Seth's PR. Unfortunately executing DDL from within DBeaver doesn't work due to transaction control issues:

<img width="1009" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/8cb792fa-bd74-4064-b8cb-53e2fa958a51">

**Comment by benesch** [comment]
> We haven't, but from their [contribution guidelines](https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code) it seems like we can just open an issue in the repo and wait for a green light. The work with these custom integrations comes more from maintaining them over time than implementing them, though. DBeaver has been around for a long while, and looking through the [latest releases](https://dbeaver.io/category/releases/), it seems manageable to support a custom connector.

Done. https://github.com/dbeaver/dbeaver/issues/20514

**Comment by bobbyiliev** [comment]
The initial Materialize driver PR was merged, but it was not part of the latest [v23.1.2 DBeaver release](https://github.com/dbeaver/dbeaver/releases/tag/23.1.2). The driver is just an extension of the Postgres driver but also disables some of the concepts that do not apply to Materialize like triggers and sequences.

I'm planning to do more thorough testing and make sure to disable any other features that are not needed. And then after that we could try implementing Materialize-specific concepts like sources, sinks and etc.

**Comment by morsapaes** [comment]
The first iteration of a custom DBeaver integration shipped in [DBeaver 23.1.3](https://dbeaver.io/2023/07/23/dbeaver-23-1-3/), and the blockers mentioned in this issue were addressed in #20314 and #20426. Closing this thread in favour of an evergreen issue that tracks the work to improve the custom connector. @bobbyiliev, can you kick off a tracker for this?
