### ISSUE TITLE
Support more psql meta-commands

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#9721]
### Feature request

[psql](https://www.postgresql.org/docs/current/app-psql.html) is the standard terminal-based SQL client for Postgres, and comes bundled with Postgres on most operating systems.

One of the most powerful features of psql is its series of handy backslash meta-commands, which provide the most popular way of introspecting a Postgres-compatible database.

This is an umbrella issue to track the status of each of the meta-commands, and a continuation of the work started in #4265. We should strive to eventually support all informational meta-commands, but focusing first on the ones related to objects that actually exist inside Materialize.

## Main meta-commands
- [x] #2156
- [x] #9011
- [x] #4279
- [x] #4283
- [x] #4285
- [x] #4322
- [x] Support `\dT` and `\dT [pattern]`
- [ ] #9595 
- [ ] Support `\df`
- [ ] Support `\du`
- [ ] Support `\sv [view]`

## Other missing features
- [ ] `S` modifier in some commands not working properly (e.g. `\dtS`)
- [ ] `+` modifier in most commands

## Secondary meta-commands
- [ ] Support `\da[S]`
- [ ] Support `\dA[+]` (not available in 9.5, the version psql things we are running)
- [ ] Support `\db[+]` 
- [ ] Support `\dc[S+]`
- [ ] Support `\dC[+]`
- [ ] Support `\dd[S]`
- [ ] Support `\dD[S+]`
- [ ] Support `\ddp`
- [x] Support `\dES`
- [ ] Support `\dE[S]+`
- [ ] Support `\det[+]`
- [ ] Support `\des[+]`
- [ ] Support `\deu[+]`
- [ ] Support `\dew[+]`
- [ ] Support `\dF[+]`
- [ ] Support `\dFd[+]`
- [ ] Support `\dFp[+]`
- [ ] Support `\dFt[+]`
- [ ] Support `\dg[S+]`
- [ ] Support `\dl`
- [ ] Support `\dL[S+]`
- [x] Support `\dm[S]`
- [ ] Support `\dm[S]+`
- [ ] Support `\do[S]`
- [ ] Support `\dO[S+]`
- [ ] Support `\dp`
- [ ] Support `\dP[itn+]` (not available in 9.5, the version psql things we are running)
- [ ] Support `\drds`
- [ ] Support `\dRp[+]` (not available in 9.5, the version psql things we are running)
- [ ] Support `\dRs[+]` (not available in 9.5, the version psql things we are running)
- [x] Support `\ds[S]`
- [ ] Support `\ds[S]+`
- [ ] Support `\dx[+]`
- [ ] Support `\dy`
- [ ] Support `\l+`
- [ ] Support `\sf[+] FUNCNAME`
- [ ] Support `\z`

Note: the list above is exhaustive.

**Comment by jkosh44** [comment]
Just a note to anyone who works on this, passing the `--echo-hidden` option to `psql` shows you all the queries that the meta-command executes and makes it much easier to figure out what is needed to support a meta-command.

From the psql docs:
> Echo the actual queries generated by \d and other backslash commands. You can use this to study psql's internal operations. This is equivalent to setting the variable ECHO_HIDDEN to on.
