### ISSUE TITLE
release: v0.14.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9766]
The following PRs in [`v0.14.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.14.0-rc1) require review:
* [x] [#9693 Prepare 0.13.1 dev](https://github.com/MaterializeInc/materialize/pull/9693) (@umanwizard)
* [x] [#9697 doc/user: remove timestamp_frequency_ms from AWS with options](https://github.com/MaterializeInc/materialize/pull/9697) (@benesch)
* [x] [#9607 Feature benchmark](https://github.com/MaterializeInc/materialize/pull/9607) (@philip-stoev)
* [x] [#9716 testdrive: Allow progress in verify-timestamp-compaction](https://github.com/MaterializeInc/materialize/pull/9716) (@cjubb39)
* [x] [#9717 doc/user: make it harder to add release notes to the wrong header](https://github.com/MaterializeInc/materialize/pull/9717) (@benesch)
* [x] [#9718 Continue 0.13.1 dev](https://github.com/MaterializeInc/materialize/pull/9718) (@benesch)
* [x] [#9722 ci: adjust for native macOS M1 builder](https://github.com/MaterializeInc/materialize/pull/9722) (@benesch)
* [x] [#9739 deps: bump to krb5-src v0.3.1](https://github.com/MaterializeInc/materialize/pull/9739) (@benesch)
* [x] [#9740 dependabot: bump pip open pull requests limit to 10](https://github.com/MaterializeInc/materialize/pull/9740) (@benesch)
* [x] [#9746 feature-benchmark: Make sure the temp directory exists](https://github.com/MaterializeInc/materialize/pull/9746) (@philip-stoev)
* [x] [#9759 Python dep bump 2021-12-27](https://github.com/MaterializeInc/materialize/pull/9759) (@benesch)

**Comment by materializer** [comment]
All PRs:

* [ ] [#9620 persist: unbreak Kafka upsert sources](https://github.com/MaterializeInc/materialize/pull/9620) (@ruchirK)
* [ ] [#9651 aws-util: rework config loading to ensure default values are used](https://github.com/MaterializeInc/materialize/pull/9651) (@benesch)
* [ ] [#9573 expr: concrete function definition for `pg_get_constraintref`](https://github.com/MaterializeInc/materialize/pull/9573) (@petrosagg)
* [ ] [#9603 persist: allow specifying optional role ARN for S3 usage](https://github.com/MaterializeInc/materialize/pull/9603) (@danhhz)
* [ ] [#9693 Prepare 0.13.1 dev](https://github.com/MaterializeInc/materialize/pull/9693) (@umanwizard)
* [ ] [#9696 doc/user: polish release notes for v0.13](https://github.com/MaterializeInc/materialize/pull/9696) (@benesch)
* [ ] [#9697 doc/user: remove timestamp_frequency_ms from AWS with options](https://github.com/MaterializeInc/materialize/pull/9697) (@benesch)
* [ ] [#9702 persist: fix merge skew with AWS configuration](https://github.com/MaterializeInc/materialize/pull/9702) (@benesch)
* [ ] [#9703 ci: fix specification of CARGO_INCREMENTAL in macOS clippy](https://github.com/MaterializeInc/materialize/pull/9703) (@benesch)
* [ ] [#9493 kafka_sink: Empty write frontier with empty input frontier](https://github.com/MaterializeInc/materialize/pull/9493) (@cjubb39)
* [ ] [#9682 expr,sql: support casts from timestamp/tz to time](https://github.com/MaterializeInc/materialize/pull/9682) (@andrioni)
* [ ] [#9663 persist: fix invalid capability downgrades when seal operator is closed](https://github.com/MaterializeInc/materialize/pull/9663) (@ruchirK)
* [ ] [#9686 sql: squash a pile of bugs](https://github.com/MaterializeInc/materialize/pull/9686) (@benesch)
* [ ] [#9607 Feature benchmark](https://github.com/MaterializeInc/materialize/pull/9607) (@philip-stoev)
* [ ] [#9709 qgm: don't leak `RefCell<*>` outside QGM models](https://github.com/MaterializeInc/materialize/pull/9709) (@asenac)
* [ ] [#9704 .github: convert issue templates to issue forms](https://github.com/MaterializeInc/materialize/pull/9704) (@benesch)
* [ ] [#9664 persist: introduce a reusable data generator for benchmarks](https://github.com/MaterializeInc/materialize/pull/9664) (@danhhz)
* [ ] [#9712 coord: add pg_roles builtin view](https://github.com/MaterializeInc/materialize/pull/9712) (@andrioni)
* [ ] [#9713 persist: clean up test logging a bit](https://github.com/MaterializeInc/materialize/pull/9713) (@danhhz)
* [ ] [#9716 testdrive: Allow progress in verify-timestamp-compaction](https://github.com/MaterializeInc/materialize/pull/9716) (@cjubb39)
* [ ] [#9717 doc/user: make it harder to add release notes to the wrong header](https://github.com/MaterializeInc/materialize/pull/9717) (@benesch)
* [ ] [#9669 repr: use numeric as the jsonb number type](https://github.com/MaterializeInc/materialize/pull/9669) (@benesch)
* [ ] [#9714 scratch: several improvements](https://github.com/MaterializeInc/materialize/pull/9714) (@benesch)
* [ ] [#9698 expr,sql: support casts from integer types to/from oid](https://github.com/MaterializeInc/materialize/pull/9698) (@andrioni)
* [ ] [#9718 Continue 0.13.1 dev](https://github.com/MaterializeInc/materialize/pull/9718) (@benesch)
* [ ] [#9722 ci: adjust for native macOS M1 builder](https://github.com/MaterializeInc/materialize/pull/9722) (@benesch)
* [ ] [#9631 test/redpanda: make TD_TEST match normal testdrive's TD_TEST](https://github.com/MaterializeInc/materialize/pull/9631) (@benesch)
* [ ] [#9725 materialized: perform log filtering on the fmt layers](https://github.com/MaterializeInc/materialize/pull/9725) (@benesch)
* [ ] [#9715 qgm: support for `Distinct` and `Reduce`](https://github.com/MaterializeInc/materialize/pull/9715) (@asenac)
* [ ] [#9727 run tests for repurpose_vec and DatumVec under miri](https://github.com/MaterializeInc/materialize/pull/9727) (@guswynn)
* [ ] [#9728 coord: add `pronamespace` and `proargdefaults` to `pg_proc`](https://github.com/MaterializeInc/materialize/pull/9728) (@andrioni)
* [ ] [#9733 build(deps): bump os_info from 3.0.8 to 3.0.9](https://github.com/MaterializeInc/materialize/pull/9733) (@dependabot[bot])
* [ ] [#9735 build(deps): bump num_cpus from 1.13.0 to 1.13.1](https://github.com/MaterializeInc/materialize/pull/9735) (@dependabot[bot])
* [ ] [#9737 build(deps): bump reqwest from 0.11.7 to 0.11.8](https://github.com/MaterializeInc/materialize/pull/9737) (@dependabot[bot])
* [ ] [#9738 build(deps): bump syn from 1.0.82 to 1.0.83](https://github.com/MaterializeInc/materialize/pull/9738) (@dependabot[bot])
* [ ] [#9739 deps: bump to krb5-src v0.3.1](https://github.com/MaterializeInc/materialize/pull/9739) (@benesch)
* [ ] [#9732 xcompile: use first-party cross-compiling toolchains on macOS](https://github.com/MaterializeInc/materialize/pull/9732) (@benesch)
* [ ] [#9734 build(deps): bump askama from 0.10.5 to 0.11.0](https://github.com/MaterializeInc/materialize/pull/9734) (@dependabot[bot])
* [ ] [#9740 dependabot: bump pip open pull requests limit to 10](https://github.com/MaterializeInc/materialize/pull/9740) (@benesch)
* [ ] [#9746 feature-benchmark: Make sure the temp directory exists](https://github.com/MaterializeInc/materialize/pull/9746) (@philip-stoev)
* [ ] [#9748 demo docs: Various fixes](https://github.com/MaterializeInc/materialize/pull/9748) (@ra-kete)
* [ ] [#9414 coord: bump table timestamps less often](https://github.com/MaterializeInc/materialize/pull/9414) (@sploiselle)
* [ ] [#9750 sql: add pg_backend_pid](https://github.com/MaterializeInc/materialize/pull/9750) (@andrioni)
* [ ] [#9413 sql: disallow multiple unnamed columns in views](https://github.com/MaterializeInc/materialize/pull/9413) (@mjibson)
* [ ] [#9752 doc/user: correct position of release note marker](https://github.com/MaterializeInc/materialize/pull/9752) (@benesch)
* [ ] [#9753 build(deps): bump pin-project from 1.0.8 to 1.0.9](https://github.com/MaterializeInc/materialize/pull/9753) (@dependabot[bot])
* [ ] [#9754 build(deps): bump proc-macro2 from 1.0.34 to 1.0.35](https://github.com/MaterializeInc/materialize/pull/9754) (@dependabot[bot])
* [ ] [#9756 build(deps): bump tracing-subscriber from 0.3.3 to 0.3.4](https://github.com/MaterializeInc/materialize/pull/9756) (@dependabot[bot])
* [ ] [#9758 build(deps): bump anyhow from 1.0.51 to 1.0.52](https://github.com/MaterializeInc/materialize/pull/9758) (@dependabot[bot])
* [ ] [#9755 build(deps): bump pprof from 0.6.1 to 0.6.2](https://github.com/MaterializeInc/materialize/pull/9755) (@dependabot[bot])
* [ ] [#9759 Python dep bump 2021-12-27](https://github.com/MaterializeInc/materialize/pull/9759) (@benesch)

**Comment by benesch** [comment]
@umanwizard can you take a look at the few PRs from me that still need review?

**Comment by guswynn** [comment]
Reviewed all @benesch's commits
