### ISSUE TITLE
mzcompose: convert all workflows to mzworkflows.py

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#9809]
See #6439 for context. We now support defining mzcompose workflows in Python rather than YAML, and experience suggests they are _much_ easier to write and debug. 

This issue tracks several work items:

  * [x] Convert all remaining YAML workflows to Python workflows.
    **These should be converted wholesale:**
    * [x] misc/dbt-materialize (#9810)
    * [x] test/kafka-exactly-once (#9820)
    * [x] test/kafka-matrix (#9821)
    * [x] test/kafka-multi-broker (#9827)
    * [x] test/performance/perf-kinesis (#9833)
    * [x] test/performance/perf-upsert (#9828)
    * [x] test/pg-cdc-resumption (#9873)
    * [x] test/pg-cdc (#9823)
    **These should continue to have mzcompose.yml service definitions, since they're intended to be understood by users, but the workflows should move to mzworkflows.py:**
    * [x] demo/billing (#9831)
    * [x] demo/chbench (#9837)
    * [x] play/mbta (#9818)
    * [x] play/wikirecent (#9824)
    **These should be arguably removed entirely, but will need to be considered on a case-by-case basis:**
    * [x] test/bench/* (#9779)
    * [x] test/chaos (#9832)
    * [x] test/mzcompose (#9834)
  * [x] Remove `WorkflowStep` classes and replace with simple functions on `mzcompose.Composition` (#9918)
  * [x] Enable typechecking on mzworkflows.py files (#9918)
  * [ ] Overhaul docs in mzbuild.md

**Comment by benesch** [comment]
cc @philip-stoev who's done all the hard work on the Python-based workflow infrastructure to date!

**Comment by ruchirK** [comment]
I think you can rip out perf-upsert too btw. It's basically just defining a
source and sending it data all within a rust binary. We can achieve the
same thing much more simply with a td file and kgen. I'm also happy to do
the ripping out

**Comment by benesch** [comment]
I filed #9922 to address the doc changes. Everything else is done! 🎉

**Comment by benesch** [comment]
Oh, probably! I'll be more eager to convert all the remaining mzcompose.yml to mzworkflows.py once we've purged the demos from this repository (see https://github.com/MaterializeInc/developer-experience/issues/1).
