### ISSUE TITLE
Rationalize our name handling

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#996]
Currently (and in particular after #982) our naming of identifiers of various parts is pretty obviously odd.

Historically (and in particular _before_ #982) we were enforcing almost no invariants in our names, since the introduction of `QualName`s we are enforcing that names are at least normalized, but there are a few places that we want to be able to enforce more things:

* There are unnamespaced things (Identifiers) which are opaque strings
* There are things that have been verified to exist and maybe should become IDs or references into some object pool (`Scope`, table names, etc)
* There are tokens that are really just opaque identifiers (almost definitely session::Var`possibly kafka sources? I could imagine

Some specific examples:

* Scope's expect to have `Identifiers`
* Inside the dataflow layer really all identifiers are opaque tokens that
  should just have been normalized
* Nobody cares about session vars

**Comment by cuongdo** [comment]
- [ ] #990 QualName: Correctly distinguish between dots inside quoted identifiers and dots in strings
- [ ] #991 Add a `QualNameRef` type that just borrows the thing that it normalizes
- [ ] #994 Make qualname print quotes only if they're required, not just if the input contained them
- [ ] #995 Add a method to display qualnames without quotes if we need to use it in RelationDesc
- [x] #1126 Support "databases" and "schemas" as a namespacing mechanism
- [x] #685 Escaped identifiers
- [x] #821 Sources and views sharing names leads to maintenance burden.
- [x] #987 Change RelationDesc's `name` type
- [x] #988 Change Scope's api to resolve qualnames, rather than store them
- [x] #989 Make Session vars identified by strings
- [x] #992 Don't parse kafka sources as qualnames
- [x] #993 Remove QualName::invalid (it is a bad hack)
- [x] #905 Correctly handle quoted table and projection names

(ported from epic)

**Comment by benesch** [comment]
Turns out these were all finished as part of the work to support databases and schemas!
