### ISSUE TITLE
release: v0.16.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/materialize#9985]
The following PRs in [`v0.16.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.16.0-rc1) require review:
* [x] [#9878 Prepare 0.15.1 dev](https://github.com/MaterializeInc/materialize/pull/9878) (@petrosagg)
* [x] [#9880 feature-benchmark: Add a dedicated Kafka upsert scenario with unique …](https://github.com/MaterializeInc/materialize/pull/9880) (@philip-stoev)
* [x] [#9888 test/kafka-multi-broker: fix merge skew](https://github.com/MaterializeInc/materialize/pull/9888) (@benesch)
* [x] [#9901 mzbench: remove command line script too](https://github.com/MaterializeInc/materialize/pull/9901) (@benesch)
* [x] [#9911 Continue 0.15.1 dev](https://github.com/MaterializeInc/materialize/pull/9911) (@petrosagg)
* [x] [#9919 feature-benchmark: fortify the FastPathFilterIndex scenario](https://github.com/MaterializeInc/materialize/pull/9919) (@philip-stoev)
* [x] [#9920 test: fix kafka-matrix](https://github.com/MaterializeInc/materialize/pull/9920) (@philip-stoev)
* [x] [#9928 mzcompose: emit informational output to stderr](https://github.com/MaterializeInc/materialize/pull/9928) (@benesch)
* [x] [#9932 doc,feature-benchmark: Add documentation on how to perform bisection](https://github.com/MaterializeInc/materialize/pull/9932) (@philip-stoev)
* [x] [#9945 fix the annotation of Let in MirRelationExpr](https://github.com/MaterializeInc/materialize/pull/9945) (@xudong963)
* [x] [#9970 deps: upgrade to latest AWS SDK](https://github.com/MaterializeInc/materialize/pull/9970) (@benesch)
* [x] [#9974 Python dependency bump 2022-01-10](https://github.com/MaterializeInc/materialize/pull/9974) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [x] [`c5c9f44c2` release: v0.16.0-rc1](https://github.com/MaterializeInc/materialize/commit/c5c9f44c253e97da24cad050e05c0e2c66ed045c) (@ruchirK)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#9813 sql: refactor visit methods](https://github.com/MaterializeInc/materialize/pull/9813) (@asenac)
* [ ] [#9814 persist: prep for upcoming changes to data blob encoding format](https://github.com/MaterializeInc/materialize/pull/9814) (@danhhz)
* [ ] [#9836 expr,sql: add functions to remove elements from collections (array_remove, list_remove)](https://github.com/MaterializeInc/materialize/pull/9836) (@andrioni)
* [ ] [#9802 mzcompose: add kgen as a python service](https://github.com/MaterializeInc/materialize/pull/9802) (@ruchirK)
* [ ] [#9872 build(deps): bump dbt-postgres from 1.0.0 to 1.0.1 in /misc/dbt-materialize](https://github.com/MaterializeInc/materialize/pull/9872) (@dependabot[bot])
* [ ] [#9831 demo/billing: port to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9831) (@benesch)
* [ ] [#9839 sql: Implement date_part for Time data type](https://github.com/MaterializeInc/materialize/pull/9839) (@jkosh44)
* [ ] [#9873 test,pg-cdc: Port the pg-cdc-resumption test to Python](https://github.com/MaterializeInc/materialize/pull/9873) (@philip-stoev)
* [ ] [#9874 Revert "sql: refactor visit methods"](https://github.com/MaterializeInc/materialize/pull/9874) (@asenac)
* [ ] [#9875 test,mzcompose: allow None as options to Materialized()](https://github.com/MaterializeInc/materialize/pull/9875) (@philip-stoev)
* [ ] [#9878 Prepare 0.15.1 dev](https://github.com/MaterializeInc/materialize/pull/9878) (@petrosagg)
* [ ] [#9880 feature-benchmark: Add a dedicated Kafka upsert scenario with unique …](https://github.com/MaterializeInc/materialize/pull/9880) (@philip-stoev)
* [ ] [#9821 kafka-matrix: convert to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9821) (@benesch)
* [ ] [#9779 mzbench: remove](https://github.com/MaterializeInc/materialize/pull/9779) (@benesch)
* [ ] [#9884 Use American spelling of "canceled" throughout the codebase.](https://github.com/MaterializeInc/materialize/pull/9884) (@umanwizard)
* [ ] [#9885 QGM: Change Vec<Box<BoxScalarExpr>> to Vec<BoxScalarExpr>.](https://github.com/MaterializeInc/materialize/pull/9885) (@wangandi)
* [ ] [#9886 testdrive: always enable --ci-output](https://github.com/MaterializeInc/materialize/pull/9886) (@benesch)
* [ ] [#9888 test/kafka-multi-broker: fix merge skew](https://github.com/MaterializeInc/materialize/pull/9888) (@benesch)
* [ ] [#9889 Shore up dataflow |-> coord tail protocol by removing the redundant `Complete` variant and changing when `Dropped` is sent.](https://github.com/MaterializeInc/materialize/pull/9889) (@umanwizard)
* [ ] [#9896 Expr: The type of a Datum::Int64 should always be `ScalarType::Int64`.](https://github.com/MaterializeInc/materialize/pull/9896) (@wangandi)
* [ ] [#9837 demo/chbench: restore original simplicity](https://github.com/MaterializeInc/materialize/pull/9837) (@benesch)
* [ ] [#9901 mzbench: remove command line script too](https://github.com/MaterializeInc/materialize/pull/9901) (@benesch)
* [ ] [#9903 sql: refactor visit methods](https://github.com/MaterializeInc/materialize/pull/9903) (@asenac)
* [ ] [#9904 qgm: HIR->QGM: Let support ](https://github.com/MaterializeInc/materialize/pull/9904) (@asenac)
* [ ] [#9902 EXPLAIN QUERY GRAPH FOR <query/view>](https://github.com/MaterializeInc/materialize/pull/9902) (@asenac)
* [ ] [#9912 doc/user: assemble v0.15 release notes](https://github.com/MaterializeInc/materialize/pull/9912) (@benesch)
* [ ] [#9911 Continue 0.15.1 dev](https://github.com/MaterializeInc/materialize/pull/9911) (@petrosagg)
* [ ] [#9913 doc/developer: add an mzcompose.md stub pointing to mzbuild.md](https://github.com/MaterializeInc/materialize/pull/9913) (@danhhz)
* [ ] [#9915 filter MetricsRecorderLayer with the same filter as the fmt layer](https://github.com/MaterializeInc/materialize/pull/9915) (@guswynn)
* [ ] [#9916 materialized: disable clap's handling of --version](https://github.com/MaterializeInc/materialize/pull/9916) (@benesch)
* [ ] [#9710 Store 1 less copy of a key in `upsert_core`](https://github.com/MaterializeInc/materialize/pull/9710) (@guswynn)
* [ ] [#9906 Add GitHub action for Slack notifications of P1 issues](https://github.com/MaterializeInc/materialize/pull/9906) (@morsapaes)
* [ ] [#9919 feature-benchmark: fortify the FastPathFilterIndex scenario](https://github.com/MaterializeInc/materialize/pull/9919) (@philip-stoev)
* [ ] [#9920 test: fix kafka-matrix](https://github.com/MaterializeInc/materialize/pull/9920) (@philip-stoev)
* [ ] [#9900 Support NAMES and SCHEMA in `SET`](https://github.com/MaterializeInc/materialize/pull/9900) (@guswynn)
* [ ] [#9918 mzcompose: typecheck all mzworkflows.py files](https://github.com/MaterializeInc/materialize/pull/9918) (@benesch)
* [ ] [#9927 fix passing materialized extra args in mzcloud-cli](https://github.com/MaterializeInc/materialize/pull/9927) (@alex-hunt-materialize)
* [ ] [#9928 mzcompose: emit informational output to stderr](https://github.com/MaterializeInc/materialize/pull/9928) (@benesch)
* [ ] [#9929 sql-parser: remove spammy logs](https://github.com/MaterializeInc/materialize/pull/9929) (@benesch)
* [ ] [#9932 doc,feature-benchmark: Add documentation on how to perform bisection](https://github.com/MaterializeInc/materialize/pull/9932) (@philip-stoev)
* [ ] [#9925 [kafka sink] Create kafka topics using kafka_util crate](https://github.com/MaterializeInc/materialize/pull/9925) (@cjubb39)
* [ ] [#9936 docs: Fix JSON notation in S3 example](https://github.com/MaterializeInc/materialize/pull/9936) (@ruf-io)
* [ ] [#9939 sql: disallow 'sNaN' as valid numeric value](https://github.com/MaterializeInc/materialize/pull/9939) (@sploiselle)
* [ ] [#9926 Optimization: Fix suboptimal plan in issue #9921.](https://github.com/MaterializeInc/materialize/pull/9926) (@wangandi)
* [ ] [#9940 expr: correctly union types for If exprs](https://github.com/MaterializeInc/materialize/pull/9940) (@mjibson)
* [ ] [#9924 mzcompose: one last big refactor](https://github.com/MaterializeInc/materialize/pull/9924) (@benesch)
* [ ] [#9942 repr: ignore nullability in base_eq for Records](https://github.com/MaterializeInc/materialize/pull/9942) (@mjibson)
* [ ] [#9945 fix the annotation of Let in MirRelationExpr](https://github.com/MaterializeInc/materialize/pull/9945) (@xudong963)
* [ ] [#9947 build(deps): bump ordered-float from 2.8.0 to 2.10.0](https://github.com/MaterializeInc/materialize/pull/9947) (@dependabot[bot])
* [ ] [#9948 build(deps): bump rdkafka-sys from `7a2355f` to `a640a00`](https://github.com/MaterializeInc/materialize/pull/9948) (@dependabot[bot])
* [ ] [#9951 build(deps): bump crossbeam-channel from 0.5.1 to 0.5.2](https://github.com/MaterializeInc/materialize/pull/9951) (@dependabot[bot])
* [ ] [#9954 build(deps): bump tiberius from 0.6.5 to 0.7.1](https://github.com/MaterializeInc/materialize/pull/9954) (@dependabot[bot])
* [ ] [#9956 build(deps): bump ubuntu from focal-20211006 to focal-20220105 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/9956) (@dependabot[bot])
* [ ] [#9970 deps: upgrade to latest AWS SDK](https://github.com/MaterializeInc/materialize/pull/9970) (@benesch)
* [ ] [#9971 build(deps): bump sysinfo from 0.22.4 to 0.22.5](https://github.com/MaterializeInc/materialize/pull/9971) (@dependabot[bot])
* [ ] [#9972 build(deps): bump sha2 from 0.10.0 to 0.10.1](https://github.com/MaterializeInc/materialize/pull/9972) (@dependabot[bot])
* [ ] [#9974 Python dependency bump 2022-01-10](https://github.com/MaterializeInc/materialize/pull/9974) (@benesch)
* [ ] [#9950 build(deps): bump crossbeam-utils from 0.8.5 to 0.8.6](https://github.com/MaterializeInc/materialize/pull/9950) (@dependabot[bot])
* [ ] [#9969 build(deps): bump syn from 1.0.84 to 1.0.85](https://github.com/MaterializeInc/materialize/pull/9969) (@dependabot[bot])
* [ ] [#9978 build(deps-dev): bump types-psutil from 5.8.18 to 5.8.19 in /ci/builder](https://github.com/MaterializeInc/materialize/pull/9978) (@dependabot[bot])
* [ ] [#9909 [kafka sink] Remove blocking tx calls from dataflow thread](https://github.com/MaterializeInc/materialize/pull/9909) (@cjubb39)
* [ ] [#9982 [timely async operator] fuse logic future](https://github.com/MaterializeInc/materialize/pull/9982) (@cjubb39)
* [ ] [`c5c9f44c2` release: v0.16.0-rc1](https://github.com/MaterializeInc/materialize/commit/c5c9f44c253e97da24cad050e05c0e2c66ed045c) (@ruchirK)

**Comment by ruchirK** [comment]
I've reviewed all of the unreviewed PRs on this list and they all look fine

**Comment by benesch** [comment]
Your unreviewed commit LGTM too.
